### ISSUE TITLE
[Emmet] Completions appear inside open tag

### ISSUE THREAD

**Issue by abitwhy** [vuejs/language-tools#1329]
![Snipaste_2022-05-23_00-27-30](https://user-images.githubusercontent.com/68452982/169705873-049d3a37-e2c1-4590-b747-411936d656c9.png)

The causes are probably not:
- Emmet self
  They have already solved [it](https://github.com/microsoft/vscode/issues/45634). And Vetur works properly.
- `tsconfig.json`
  As you see, it's a new [volar-starter](https://github.com/johnsoncodehk/volar-starter) project.

**Comment by johnsoncodehk** [comment]
Reference code: https://github.com/microsoft/vscode/blob/c0769274fa136b45799edeccc0d0a2f645b75caf/extensions/emmet/src/defaultCompletionProvider.ts#L160-L218

**Comment by johnsoncodehk** [comment]
If someone wants to help, it should implement to https://github.com/volarjs/plugins/blob/master/packages/emmet/src/index.ts
