### ISSUE TITLE
Feature Request: Use local vue-tsc when avaliable 

### ISSUE THREAD

**Issue by antfu** [vuejs/language-tools#1388]
Refer: https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1146283225 by @danielwaltz

Not sure if it's possible, but creating this to bring some awareness. While we could not lock the extension's version in VS Code yet, I think it might be a reasonable feature to somehow "lock" the behavior of Volar across different projects.

**Comment by danielwaltz** [comment]
Thanks Anthony! I wasn't sure when I wrote my comment if this had already been requested before, so I appreciate you opening it for me. Would be very cool to see this implemented if it's possible!

**Comment by johnsoncodehk** [comment]
First of all thanks for the proposal, I ultimately decided not to support this feature as this would introduce confusion where language server behavior of the same version might not be consistent, thus increasing potential maintenance costs.
