### ISSUE TITLE
Proper props displaying

### ISSUE THREAD

**Issue by RedBlueKoi** [vuejs/language-tools#1483]
I am pretty happy with the plugin, but there is only one thing that bothers me daily - bad props recognition. 
Example:
I have my child component and I defineProps there with a TS interface and let's imagine it is a required prop. At this point if I would try to use that component in the parent one I will see an error in the VSCode, but upon hovering or trying to hotfix with `cmd + .` nothing useful will happen. Hovering the cursor will display the entire type definition of the component and not what props I am missing and pressing `cmd + .` will say that there is nothing to fix.
Is it possible to fix this?
Thanks!

**Comment by johnsoncodehk** [comment]
Yes this is possible, Vetur is doing like this in my memory. But that's not a priority, I'll check it after clear backlog.

**Comment by johnsoncodehk** [comment]
The missing required props are visualized after v1.1.0, I think no need this anymore.
