### ISSUE TITLE
Expand scopes for vue specific attributes

### ISSUE THREAD

**Issue by roydukkey** [vuejs/language-tools#2038]
As a theme developer, I would like to have more specific scopes to target vue attributes base on their functionality. Here's a proposal to achieve this granularity.

### `v-bind`

**scope**: `meta.attribute.directive.bind.vue`

```html
<span v-bind:src="imageSrc" />
<span v-bind:[var]="value" />
<span :src="imageSrc" />
<span :[var]="value" />
```

### `v-on`

**scope**: `meta.attribute.directive.event.vue`

```html
<button v-on:click="doThis" />
<button v-on:click.once="doThis" />
<button v-on:[event]="doThis" />
<button v-on:[event].once="doThis" />
<button @click="doThis" />
<button @click.once="doThis" />
<button @[event]="doThis" />
<button @[event].once="doThis" />
```

### `v-slot`

**scope**: `meta.attribute.directive.slot.vue`

```html
<template v-slot />
<template v-slot:header />
<template #header />
```

### All Others

**scope**: `meta.attribute.directive.vue`

Remain as currently implemented.

Do you have any thoughts on this? I believe the best plan of action would be to break these three out from [`vue-directives-original`](https://github.com/johnsoncodehk/volar/blob/c21e10ba328859cb72e56c477f777a815836d493/extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json#L935) into their own rules.

If this sound good to go, I can try to get a PR before the end of the month.

**Comment by johnsoncodehk** [comment]
Not sure this is correct, maybe we can try some like `meta.attribute.directive.$1$2$3$4$6.vue`.

**Comment by znck** [comment]
I suggest using https://marketplace.visualstudio.com/items?itemName=znck.vue as a dependency as the extension only includes syntax highlight. The language grammar is written to work with most themes and additional metadata is collected for specific customizations. See https://vuedx.com/guide/creating-vscode-themes#additional-metadata

**Comment by roydukkey** [comment]
Just based on the [Night Owl](https://raw.githubusercontent.com/znck/vue-developer-experience/main/extensions/vscode-vue/demo/NightOwl.png) screen, I think this will achieve exactly what I'm looking for.

**Comment by johnsoncodehk** [comment]
Closed due to inactivity.
