### ISSUE TITLE
vue-component-meta: provide the node as well as rawType?

### ISSUE THREAD

**Issue by treystout** [vuejs/language-tools#2047]
I'm still very new to ts internals, but I am hoping to get a little more control over the schema being provided. I found this section of the code which seems responsible for interpreting ts internals to build up a "schema" of a prop...
https://github.com/johnsoncodehk/volar/blob/e1514295e44b1efbb13f8656106530504a9f51e3/vue-language-tools/vue-component-meta/src/index.ts#L522

I was hoping to maybe keep the node available as well? maybe as a peer of `rawType?` called `rawNode?` This may be a red herring though. All I'm really after is knowing the declared types as individual objects for documentation generation. the string `boolean | undefined` is not as helpful for this as having a ref to each type for something more complicated like `SomeThing[] | OtherThing[]` I'd like to identify the union and then that there are 2 arrays, and then finally produce a doc link to `SomeThing` and `OtherThing`. Am I on the right track? Thank you for this amazing library, makes Vue a great DX.

**Comment by johnsoncodehk** [comment]
I plan to refactor the current implementation for this.

**Comment by johnsoncodehk** [comment]
Hi @treystout, sorry for the late reply, I just reviewed the current implementation and I think rawType is sufficient for your use case, do you find anything missing?
