### ISSUE TITLE
vue-tsc incorrectly identifies html tag as a variable

### ISSUE THREAD

**Issue by hykilpikonna** [vuejs/language-tools#2048]
When I upgraded from vue-tsc `0.40.1` to `1.0.8`, `vue-tsc` failed during compile.

It prompted `error TS2322: Type '{}' is not assignable to type 'ComponentProps<Set<string>>'.
  Type '{}' is missing the following properties from type 'Set<string>': add, clear, delete, forEach, and 7 more.`

In this vue file, I've defined a `loading` variable of type `Set<string>`, and imported `Loading` from `@element-plus/icons-vue`. The `<loading v-else />` tag here should be referencing element-ui's `Loading` component, but `vue-tsc` incorrectly identified it as the class variable with the same name. When I changed the variable's name to something else, the compilation succeeded.

![image](https://user-images.githubusercontent.com/22280294/197362863-d70bb1b9-6d33-4655-87e7-96672630896a.png)

![image](https://user-images.githubusercontent.com/22280294/197362971-f5851df5-e559-47f9-886e-e4af83551c76.png)

**Comment by so1ve** [comment]
Does it work now? If not could you please provide a minimal reproduction?

**Comment by johnsoncodehk** [comment]
Closed due to unable to reproduce in latest version.
