### ISSUE TITLE
Editing CSS in the template results in de-synced document

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#2064]
Volar: 1.0.9
Sublime Text: 4138

In a vue file like:

```vue
<template>
  <div :style="{ color: 'x' }">
  </div>
</template>
```

Typing anything after `color: 'x'` results in document state getting out of sync.

For example if I add `+` after `'x'`:

```vue
<template>
  <div :style="{ color: 'x'+ }">
  </div>
</template>
```

the "Virtual File" will have `+` doubled:

```ts
__VLS_0 = { style: (({ color: 'x'++ })),  };
```

if I add one more `+` the virtual file will have 4 `+`'s:

```ts
__VLS_0 = { style: (({ color: 'x'++++ })),  };
```

After debugging it for a while, I've narrowed it down to Sublime Text triggering a `textDocument/documentColor` request in that context which seems to cause the internal representation to get messed up.

VSCode doesn't trigger `textDocument/documentColor` requests here so it doesn't reproduce.

**Comment by johnsoncodehk** [comment]
Please provide minimum LSP logs so I can troubleshoot.

**Comment by rchl** [comment]
I can reproduce in 1.0.9 but not in 1.0.13 and up.
