### ISSUE TITLE
Vue Language Server crashes with "Request textDocument/semanticTokens/range failed with message: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by severinbeauvais** [vuejs/language-tools#2075]
**Environment:**
Windows 10 22H2 / WSL2 / Ubuntu
VS Code 1.72.2
Node 16.14.2
Vue Language Features (Volar) 1.0.9 (also happened with earlier version)
Vue 2.7.10

**Symptoms:**

1.
![image](https://user-images.githubusercontent.com/10002889/198722884-df2fdbd7-715c-4931-9ad8-b5248de2b1a6.png)

2. Code highlighting goes awry.

3. Heavy memory (Vmmem) usage and sometimes run out and see other errors.

**Output:**
```
[Error - 12:54:26 PM] Request textDocument/semanticTokens/range failed.
  Message: Request textDocument/semanticTokens/range failed with message: Maximum call stack size exceeded
  Code: -32603 
```

**Comment by severinbeauvais** [comment]
^^ I'm going to review my "setup for Vue 2" described on the extension's page. If I find anything, I'll update this issue.

Either way, this issue may help someone else in the future.

**Comment by arpadgabor** [comment]
Experiencing a similar issue here. Same OS, also on WSL2 with Ubuntu. Using node 16.18, Nuxt 3 (rc 12), Volar 1.0.9, also happened before. Sometimes intellisense goes haywire and I need to restart the Vue server for it to get fixed, but then it happens again after another half hour or so. Will check if I can get any useful logs.

**Comment by johnsoncodehk** [comment]
I haven't encountered this problem so can't investigate it. For VSCode, a workaround for now is settings `"editor.semanticHighlighting.enabled": false` in VSCode settings to disable semanticTokens.
