### ISSUE TITLE
Failed to setup using Vue 2.7

### ISSUE THREAD

**Issue by nfantone** [vuejs/language-tools#2100]
I have an existing `vue@2.7` project that I'm trying to run latest `volar` on. After following the ["Setup for Vue 2" section of the docs](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#usage), I can't get most things to work.

1. If I remove `shims-vue.d.ts` and `shims-tsx.d.ts` as suggested, importing any `.vue` file inside a `<script>` results in `Could not find a declaration file for module './MyComponent.vue'` TS errors in every component.
2. For components defined using `defineComponent`, properties exposed via `setup()` are not recognized in templates at all, failing with `Property 'x' does not exist on type '...'`. However, components declared using `<script setup>` do seem to get interpolation type checking as expected.
3. If using `Vue.volar` as the `editor.defaultFormatter` for `.vue` files along with ` "editor.formatOnSave"`, formatting components appears to be applying the expected formatting and undoing it right away, in a flickering glitch — often leaving sources in a bad state. Setting `"editor.formatOnSave": false` resolves the issue — but still formats sources on save, for some reason. The `"editor.formatOnSaveMode"` option seems to be completely ignored, always resorting to formatting the entire file.

`"vueCompilerOptions": { "target": 2.7 }` is correctly set in `tsonfig.json`.

Am I missing something? Many thanks.

**Comment by caosiwei97** [comment]
+1

**Comment by xiaoxiangmoe** [comment]
Are you install both [Vue Language Features (Volar)
](https://marketplace.visualstudio.com/items?itemName=Vue.volar) and [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)

**Comment by nfantone** [comment]
@xiaoxiangmoe I have both of them.

@johnsoncodehk This is still an issue and I don't see any kind of resolution mentioned. Why close it?

**Comment by xiaoxiangmoe** [comment]
@nfantone Can you provide me a reproducible demo repo?

**Comment by nfantone** [comment]
I can't share the repo I'm experiencing this at the moment (private) — but I'll try to put together a new one.

Have you tried creating a barebones 2.7 project from scratch?

**Comment by xiaoxiangmoe** [comment]
https://github.com/vuejs/create-vue

You can try `npm create vue@2`

**Comment by ywsoul** [comment]
+1
