### ISSUE TITLE
Comments inside JSX expressions don't work

### ISSUE THREAD

**Issue by whaaaley** [vuejs/language-tools#2125]
I didn't see an issue for this. If this is already known, I apologize.

![image](https://camo.githubusercontent.com/c6ce48579b1c9a577af5e4964fbb4e029001ce082db940701e1d95165099fb4b/68747470733a2f2f692e6779617a6f2e636f6d2f31316532323063393633346164333539326134383336633461636232613436622e676966)

**Comment by johnsoncodehk** [comment]
I cannot verify this issue as the icon cannot be displayed right now. If you still encounter this problem in the latest version, please let me know.
