### ISSUE TITLE
Volar crashing running typescript files

### ISSUE THREAD

**Issue by joaoggnogueira** [vuejs/language-tools#2132]
First, the Volar starts too slow, takes too many minutes. SO, the Volar is stuck, and the highlighting system is not working in real time, so I restarted the Volar extension, and received this error message without details. I need to restart the vscode, but the problem persists. 

![image](https://user-images.githubusercontent.com/10080622/202801752-399756cc-65a2-4567-bbad-a3df7fe4e51b.png)

**Comment by johnsoncodehk** [comment]
Sorry for the delay, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?
