### ISSUE TITLE
Accepting completion sometimes overwrites text that comes after it

### ISSUE THREAD

**Issue by brawaru** [vuejs/language-tools#2133]
Type: <b>Bug</b>

I am not sure about the reproduction steps, but sometimes when you accept an auto-completion for JS in template, Volar (?) overwrites everything that comes next in the line.

It goes like this:

1. You write some code and request suggestions with <kbd>Ctrl</kbd>+<kbd>Space</kbd> (`|` represents cursor here)
    ```vue
    <template>
      <div
         v-text="$t('hello|')"
       />
    </template>
    ```
2. In the list of completions you choose an suggestion (e.g. `hello-world.text` in this case) and accept it.

   This is what you get:
    ```vue
    <template>
      <div
         v-text="$t('hello-world.text|
       />
    </template>
    ```
   (closing quotation mark for string, parenthesis for function, and double quotation mark for attribute, are all overwritten).

   This is what you would have expected:
    ```vue
    <template>
      <div
         v-text="$t('hello-world.text|')"
       />
    </template>
    ```
    (only text got completed)

   It also works for template expressions: `{{ $t('hello|') }}` may auto-complete into `{{ $t('hello-world.text|' }}` or `{{ $t('hello-world.text|`.

Extension version: 1.0.9
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.95GB (3.17GB free)|
|Process Argv|. --crash-reporter-id 00f2bb44-44e6-48df-99e8-c8d250a1afbb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

<details>
<summary>Enabled extensions</summary>

Extension | Author (truncated) | Version
-- | -- | --
gitlens | eam | 13.1.0
EditorConfig | Edi | 0.16.4
prettier-vscode | esb | 9.9.0
vscode-firefox-debug | fir | 2.9.8
codespaces | Git | 1.13.1
todo-tree | Gru | 0.0.220
vscode-icon-theme | jtl | 1.6.6
vscord | Leo | 5.0.10
fluent-icons | mig | 0.0.18
vscode-language-pack-de | MS- | 1.73.11090923
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-slideshow | ms- | 0.1.5
remote-ssh | ms- | 0.92.0
remote-ssh-edit | ms- | 0.84.0
remote-explorer | ms- | 0.0.2
rewrap | stk | 1.16.3
even-better-toml | tam | 0.19.0
errorlens | use | 3.6.0
intellicode-api-usage-examples | Vis | 0.2.6
volar | Vue | 1.0.9
vscode-wakatime | Wak | 22.0.0
material-theme | zhu | 3.15.6

**Comment by johnsoncodehk** [comment]
I try with following code but can't reproduce, if you can provide minimal reprouction it will be helpful.

```html
<template>
  {{ $t('hello') }}
</template>

<script lang="ts" setup>
function $t(key: 'hello-world.text') { }
</script>
```

**Comment by Brawaru** [comment]
Unfortunately I cannot provide minimal reproduction, but this happens a lot while I'm working on [`i18n-restart` branch of my `Brawaru/knossos` repo](https://github.com/Brawaru/knossos/tree/feat/i18n-restart). It's by no means minimal, but if you want to try it out:

1. Clone the repo:
   `git clone -b feat/i18n-restart https://github.com/Brawaru/knossos.git modrinth-knossos`
   `cd modrinth-knossos`
2. Install all npm packages:
   `npm i`
3. Generate (giant) type declaration file for locale file:
   `npm run i18n:watch` (or `npm run i18n:types` to run without watcher)
4. Go to any `.vue` file and try `$t('')` there.

I noticed it occurs much more frequently after you change the localisation file (`i18n/en-US/index.toml`) and typings re-generate in background, but it does not *only* happen after that — it's very random. Maybe it has something to do with CPU load, I'm not sure, but there are no noticeable freezes in VS Code when such bad auto-completion happens.

**Comment by johnsoncodehk** [comment]
I tried that repo before but couldn't reproduce, do you still find this problem with recent versions?

**Comment by brawaru** [comment]
Haven't worked with Vue recently, so cannot tell. But I did experience similar thing with TypeScript autocompletion (mostly when autocompleting generics) so I guess it's a VS Code or TypeScript bug. It's incredibly inconsistent and I still haven't managed to find a clear reproduction, so I'll just close this (wanted do that quite a while ago, but forgot). Sorry for taking up your time.
