### ISSUE TITLE
Neovim with volar can not find the property reference which define in data or prop

### ISSUE THREAD

**Issue by LauGaHo** [vuejs/language-tools#2154]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/52206004/204517262-a08daab5-6005-4046-adb7-2138c9a260a0.png">

the `typeClass` is use in template, but I can not find the reference by volar.
It show that no reference.

vue: 2.6
neovim: v0.8.0

**Comment by johnsoncodehk** [comment]
`Vue.extend` of Vue 2.6 does not provide enough type information for TS to implement this behavior. You may consider using `defineComponent()` of `@vue/composition-api` to wrap component options for improvement.
