### ISSUE TITLE
Experimental RFC 436 - cannot use generic prop as object key in template without `props`

### ISSUE THREAD

**Issue by cohlar** [vuejs/language-tools#2192]
With `defineProps`, the props are normally available in the template without the need to use `const props = defineProps<...>()` and adding `props.` before the prop name.
However when adding a generic prop as a key to an object in the HTML template, we get an error.

![image](https://user-images.githubusercontent.com/57757008/206926565-5c724c04-c9a4-44b3-81d1-a6d1c15575cf.png)

I made a [public repo](https://github.com/cohlar/vue-rfc436/tree/prop_object_key_error) to showcase the issue. The generic component with the error is `TheWelcome` - please note this repo is shared with https://github.com/johnsoncodehk/volar/issues/2191 (separate branches).

**Comment by johnsoncodehk** [comment]
This is the `DefineComponent` type behavior, T is recognized as PropType to resolve.

@pikax I'm pinging you here, but maybe I can try to fix it when I am free.

**Comment by cohlar** [comment]
Hi, when I try upgrading vue from `3.2.45` to `3.2.47`, I suddenly get a lot of type errors (from `vue-tsc 1.1.7`) on the props of components that use generics. I'm not 100% sure but I have a feeling it is related to this issue.

**Comment by johnsoncodehk** [comment]
@pikax naively changing these few lines would avoid the problem, but I don't know how much this would break. I'll leave this issue for upstream attention.

@cohlar can you open an issue on the vuejs/core repo?

```diff
type InferPropType<T> = [T] extends [null]
  ? any // null & true would fail to infer
  : [T] extends [{ type: null | true }]
  ? any // As TS issue https://github.com/Microsoft/TypeScript/issues/14829 // somehow `ObjectConstructor` when inferred from { (): T } becomes `any` // `BooleanConstructor` when inferred from PropConstructor(with PropMethod) becomes `Boolean`
  : [T] extends [ObjectConstructor | { type: ObjectConstructor }]
  ? Record<string, any>
  : [T] extends [BooleanConstructor | { type: BooleanConstructor }]
  ? boolean
  : [T] extends [DateConstructor | { type: DateConstructor }]
  ? Date
  : [T] extends [(infer U)[] | { type: (infer U)[] }]
  ? U extends DateConstructor
    ? Date | InferPropType<U>
    : InferPropType<U>
-   : [T] extends [Prop<infer V, infer D>]
-   ? unknown extends V
-     ? IfAny<V, V, D>
-     : V
+   : [T] extends [PropType<infer V>] ? V
+   : [T] extends [{ type: PropType<infer V> }] ? V
  : T
```

https://github.com/vuejs/core/blob/ae5a9323b7eaf3dfa11b2a442a02faa992f88225/packages/runtime-core/src/componentProps.ts#L125-L128
