### ISSUE TITLE
类型提示问题

### ISSUE THREAD

**Issue by npmrun** [vuejs/language-tools#2195]
![image](https://user-images.githubusercontent.com/62639956/207004635-c31708a5-c5b7-4bd3-a495-8efde10fc8e8.png)
![image](https://user-images.githubusercontent.com/62639956/207004703-b5571293-181f-45fa-becb-2adad9a851b5.png)
如图，定义了`value?: IData`,但在template中的value是提示类型是{}

```
"vue-tsc": "^1.0.13",
"vite": "^2.9.14",
"vue": "^3.2.33",
```

**Comment by bsr1109** [comment]
![image](https://user-images.githubusercontent.com/120477626/207356060-a15fe770-aa3e-46e8-97f8-902d2a99e457.png)

有类似问题 ，上一个版本还没事呢

**Comment by Sight-wcg** [comment]
> 
```
import type { FormProps } from 'element-plus'

const formSize: Ref<FormProps['size']> = ref("default")
```

**Comment by Sight-wcg** [comment]
> ![image](https://user-images.githubusercontent.com/120477626/207356060-a15fe770-aa3e-46e8-97f8-902d2a99e457.png)
> 
> 有类似问题 ，上一个版本还没事呢

```
import type { FormProps } from 'element-plus'

const formSize: Ref<FormProps['size']> = ref("default")
```

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, please provide minimal reproduction.
