### ISSUE TITLE
vue-tsc error when using vite option to globally import styles in nuxt 3 stable

### ISSUE THREAD

**Issue by davies-maina** [vuejs/language-tools#2213]
I have the following configuration in my `nuxt.config.ts` file :
```
vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/scss/main.scss" as *;'
        }
      }
    }
  },
```

I get the following error from `vue-tsc ` on running npm run dev:

> ERROR(vue-tsc)  Type '{ css: { preprocessorOptions: { scss: { additionalData: string; }; }; }; }' is not assignable to type 'ViteConfig'.
>   Object literal may only specify known properties, and 'css' does not exist in type 'ViteConfig'.

**Comment by johnsoncodehk** [comment]
It is not a `vue-tsc` issue, please exclude `nuxt.config.ts` for tsconfig if it should not check by `vue-tsc` for your project.
