### ISSUE TITLE
vue-html snippet scope not working within {{ }}

### ISSUE THREAD

**Issue by Bubbi** [vuejs/language-tools#2284]
I've written some snippets to use in the `vue-html` scope, but for some reason, they don't work everywhere inside `<template>...</template>`. It seems that I can add snippets in the html-part of vue. But not  inside `{{ }}`.

This works perfectly with Vetur, so I was hoping to get the same functionality with Volar. But maybe the `vue-html` scope for snippets, just don't cover it and it needs to have a different scope. 

example snippet:
```JSON
"Hello world (html)": {
    "scope": "html,vue-html",
    "prefix": "hv",
    "body": ["Hello World"]
  }
```

Here I want to insert it between `<div>` and `</div>` and typing `hv` will show the snippet inside IntelliSense.

![image](https://user-images.githubusercontent.com/863630/210972454-e97613b3-47f5-4eb6-ba70-baca6bbd55da.png)

But if I do this between `{{` and `}}`, it won't appear.

![image](https://user-images.githubusercontent.com/863630/210972518-6674b347-2543-4599-9a8d-ad29f030e34d.png)

If I do this with Volar disabled and Vetur enabled instead, then the snippet works both places.
Maybe it is just because a different scope than `vue-html` is used for Volar with these brackets. I just can't find any information about that.

**Comment by johnsoncodehk** [comment]
<img width="431" alt="螢幕截圖 2023-01-06 18 07 30" src="https://user-images.githubusercontent.com/16279759/210978878-a26b21e7-6f91-4313-9d31-458cbcee5371.png">

The scope should be `typescript` in `{{ | }}`

**Comment by Bubbi** [comment]
Yeah, that made it work..

Hmm.. but then it will also show on typescripts, which is precisely what i'm trying to avoid.. damnit..

I made a snippet, that generates a method call. But in the template, it shouldn't add `this.`, when calling the method, which it should while in the JS/TS part.

**Comment by johnsoncodehk** [comment]
Unless we specify a new language id for template interpolation, there is no way to distinguish between snippets. But this is too expensive, it breaks existing vue snippet extensions, and creating new language ids is something I want to avoid.

Closed due to this is the intended behavior by design.
