### ISSUE TITLE
global component type declare

### ISSUE THREAD

**Issue by faga295** [vuejs/language-tools#2289]
volar version: 1.0.22
vue version: 3.2.45

there is some thing strange when I use volar
this is my volar.d.ts to configure global component
mafs is a global component
<img width="929" alt="image" src="https://user-images.githubusercontent.com/87003751/211160086-eab269a6-c207-4e53-ad87-f2d9cad6f3f8.png">
the result is below
<img width="387" alt="image" src="https://user-images.githubusercontent.com/87003751/211160186-76883293-b7f2-4b40-a23f-0ce1684e32d4.png">
so I change it to this
<img width="578" alt="image" src="https://user-images.githubusercontent.com/87003751/211160276-b39724ed-a071-4808-9101-156f71318400.png">
it works
<img width="940" alt="image" src="https://user-images.githubusercontent.com/87003751/211160328-87a6369e-004f-49a2-9156-7d6b2d0a4859.png">

now it can work, but I think `Mafs: typeof mafs` is better way, can anyone assist to me?

**Comment by johnsoncodehk** [comment]
Please provide minimal reproduction.
