### ISSUE TITLE
vue2.7 + handsontable suggestion doesn't work

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#2290]
reproduce: https://github.com/tjx666/volar-starter/tree/handsontable

https://user-images.githubusercontent.com/41773861/211160761-c8828a1e-dbbe-4928-814e-a70f9e1ead92.mov

**Comment by tjx666** [comment]
I can import the component props type, there any simple way let me define the component type?

<img width="975" alt="image" src="https://user-images.githubusercontent.com/41773861/211161022-6b49a4f9-e65a-49d1-8299-81ad7b47f64f.png">

**Comment by johnsoncodehk** [comment]
```ts
new () => {
  $props: HotTableProps
}
```

Please ask TS problem in https://discord.com/channels/325477692906536972/331999220125138944.
