### ISSUE TITLE
vue2.7 + defineAsyncComponent componet props suggestion doesn't work

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#2298]
reproduce: https://github.com/tjx666/volar-starter/tree/async-component
take-over mode: yes

![image](https://user-images.githubusercontent.com/41773861/211276877-5bc669b9-334f-4070-bf3c-53cde5a7f1f1.png)

**Comment by johnsoncodehk** [comment]
This is `defineAsyncComponent()` type issue of 2.7, please forward to https://github.com/vuejs/vue.
