### ISSUE TITLE
Importing components that are `index.vue` in a parent folder

### ISSUE THREAD

**Issue by chadanuk** [vuejs/language-tools#2300]
We have a code base that has a pattern library approach that has additional files. for components in the component folder and we use `index.vue` for the component files themselves.

We've found that volar doesn't recognise this structure for auto imports.

See https://github.com/johnsoncodehk/volar-starter/pull/10

**Comment by KhanhHH** [comment]
It worked on Vetur, hope Volar support it soon.

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar-starter/pull/10#issuecomment-1436077234
