### ISSUE TITLE
Destructured discriminated unions not working

### ISSUE THREAD

**Issue by mdoesburg** [vuejs/language-tools#2302]
Not 100% sure if I am missing something, but I am having an issue with destructured discriminated unions.

**Volar:** 1.0.24
**TypeScript:** 4.7.4
**Takeover Mode:** enabled

## Example

Here's some example code in which "Example 1" and "Example 2" are not narrowing down to the correct type for `data.value`. The comments in the example below indicate the types that VSCode is showing when hovering over the different variables.

```vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { reactive } from 'vue';

// ---- Example 1 ----------------
const { data, isSuccess } = useQuery({
    queryKey: ['test1'],
    queryFn: () => Promise.resolve(5),
});

// (property) Ref<T = any>.value: boolean
if (isSuccess.value) {
    isSuccess.value; // (property) Ref<true>.value: true
    data.value; // (property) Ref<T = any>.value: number | undefined
}

// ---- Example 2 ----------------
const query2 = useQuery({
    queryKey: ['test2'],
    queryFn: () => Promise.resolve(5),
});

// (property) Ref<T = any>.value: boolean
if (query2.isSuccess.value) {
    query2.isSuccess.value; // (property) Ref<true>.value: true
    query2.data; // (property) data: Ref<number> | Ref<undefined>
}

// ---- Example 3 ----------------
const query3 = reactive(
    useQuery({
        queryKey: ['test3'],
        queryFn: () => Promise.resolve(5),
    })
);

// (property) isSuccess: boolean
if (query3.isSuccess) {
    query3.isSuccess; // (property) isSuccess: true
    query3.data; // (property) data: number
}
</script>
```

## Expected Behavior

I am expecting to be able to destructure the result of `useQuery`, and still be able to benefit from type narrowing. When `isSuccess` is `true`, `data` should no longer be `number | undefined`, but just `number`.

In the example above I can only get it to work if I wrap the `useQuery` call in `reactive` and don't use destructuring. (see "Example 3" above) 

According to the TanStack Query documentation this should work with destructuring. See their section on [Type Narrowing](https://tanstack.com/query/v4/docs/vue/typescript#type-narrowing).

In addition to the TanStack Query documentation, the [Type Narrowing](https://tkdodo.eu/blog/react-query-and-type-script#type-narrowing) section in this [blog post](https://tkdodo.eu/blog/react-query-and-type-script) indicates that [control flow analysis for destructured discriminated unions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/#cfa-destructured-discriminated-unions) was added in TypeScript 4.6, which is what should support my expectation.

## Actual Behavior

I expect `data.value` to be of type `Ref<T = any>.value: number` not `Ref<T = any>.value: number | undefined` as seen in this snippet:

```vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';

const { data, isSuccess } = useQuery({
    queryKey: ['test1'],
    queryFn: () => Promise.resolve(5),
});

// (property) Ref<T = any>.value: boolean
if (isSuccess.value) {
    isSuccess.value; // (property) Ref<true>.value: true
    data.value; // (property) Ref<T = any>.value: number | undefined     <--- EXPECTING ONLY "number" HERE
}
```

**Comment by johnsoncodehk** [comment]
I think `@tanstack/vue-query` doesn't really support your example, if you look at the [TS playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAOQACMAhgHaoMDGA1gPQBuOAtAEcc+KgFgAUKEixEcKOnqsYwbuiKlylKr3RUA3BImsIzeEgAm9BgBo4wVAGVkrVulSp1AXjkKlK9AAUaFjCeAEA2lQwbjBUALq2AQCUcJ4AfHAACpr26AB08qgQADaqAQCsSVWGkiRwAfZOLm6oKQgScJ1wlgwSnJydAHoA-BKEEkA) of `@tanstack/vue-query`, it only works when used with `reactive()`.

I suggest you bring it up to the `@tanstack/vue-query` author, since Volar's behavior is actually consistent with TS.
