### ISSUE TITLE
tsconfig.json not being read in monorepo

### ISSUE THREAD

**Issue by brunomperes** [vuejs/language-tools#2314]
I have a repository with multiple projects each with its own tsconfig, extending the root tsconfig. In this structure:

```
├── project-1/
│   ├── src/
│      ├── Header.vue
│   ├── package.json
│   ├── tsconfig.json
├── project-2/
│   ├── package.json
│   ├── tsconfig.json
├── package.json
├── tsconfig.json    // <-- Root
```

Yet, Volar says it can't find my tsconfig, the Doctor gives me this output:

![Screenshot 2023-01-13 at 11 50 21](https://user-images.githubusercontent.com/1819575/212303611-5344c6c0-b62f-4dc1-b9e0-38b01eb8879c.png)

Which ignores my configuration for `vueCompilerOptions` in either of tsconfig files (root or nested)

Setup:
MacOS 12.6.2
VSCode 1.74.3
Vue 2.7.14
Volar 1.0.24 (Takeover mode)

Long shot, but could [this line](https://github.com/johnsoncodehk/volar/blob/3ffa36146f3d8b526a6b73835fe9cd6474439705/vue-language-tools/vue-language-core/src/utils/ts.ts#L17) be incorrectly reading jsconfig instead of tsconfig?

**Comment by johnsoncodehk** [comment]
Can you provide these tsconfigs content or minimal reproduction?
