### ISSUE TITLE
Cannot find module or its corresponding type declarations from file outside of src/

### ISSUE THREAD

**Issue by teh-mICON** [vuejs/language-tools#2315]
As title says, When a file is outside of the src folder, intellisense breaks, the build on the other hand works.

steps to reproduce:

- create a directory "foo" in root directory.
- create a class or vue component inside that directory.
- try to import a class or vue component in src.

to make it clearer, consider this file tree:
- break
  - Broken.vue
- src
    - Foo.ts
    - components
      - Bar.vue

contents of Broken.vue would be:

```
<script setup lang="ts">
  import Foo from '@/Foo'
  import Bar from '@/components/Bar.vue'
</script>
```

**Comment by johnsoncodehk** [comment]
You can try add `break/Broken.vue` to include in tsconfig.
