### ISSUE TITLE
Support  pug/sass in nvim

### ISSUE THREAD

**Issue by Evil-Coder** [vuejs/language-tools#2317]
Hello, I'm trying to install lsp for nvim via neovim/nvim-lspconfig, however there is no support for sass and pug. Spent a day but couldn't find a solution. Can you please tell me if it is possible to set it up?

<img width="318" alt="Снимок экрана 2023-01-14 в 02 44 20" src="https://user-images.githubusercontent.com/28433513/212438547-20f5ff45-d633-4a22-93ca-26612b22de15.png">

**Comment by johnsoncodehk** [comment]
Vue's syntax highlighting is not implemented for neovim here, please forward the problem to neovim.

For pug intellisense see @uros-5 comment.
