### ISSUE TITLE
outdated link on https://github.com/johnsoncodehk/vue-tsc

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/language-tools#2319]
https://github.com/johnsoncodehk/vue-tsc

![obraz](https://user-images.githubusercontent.com/15625235/212728170-ad9a7192-3928-4c9a-9965-e6f0b1e4e3b3.png)

![obraz](https://user-images.githubusercontent.com/15625235/212728191-2a2d74d1-14ce-4167-88b6-16ea93b727fa.png)

**Comment by dpschen** [comment]
Note also that [a google search for `vue-tsc`](https://www.google.com/search?q=vue-tsc) lists the old repo already on the second position.

![image](https://user-images.githubusercontent.com/6173598/214424146-b2ebdede-e369-492f-a99f-cb2953017545.png)

_(copied from my closed duplicate issue)_

**Comment by johnsoncodehk** [comment]
Thanks for letting me know! I will update the link after moving the repo to vuejs organization.
