### ISSUE TITLE
When WritableComputedRef<T> is set to v-model, it is not unwrapped to T.

### ISSUE THREAD

**Issue by YusukeD** [vuejs/language-tools#2321]
Hello, I am currently having the problem described in the title.

Unwrap does not seem to work when `WritableComputedRef<T>` is defined through a type definition such as `Models<T>` written below.

```typescript
type Models<T> = { [key in keyof T]: WritableComputedRef<T[key]> }
const makeEmitterComputed = <T extends { [key in keyof T]: unknown }>(
  modelValue: T,
  emitter: (fieldName: keyof T, value: T[keyof T]) => void,
): Models<T> => {
  // ...
}

type User = {
  name: string
  age: number
}

const user = reactive<User>({
  name: '',
  age: 0,
})

const models = makeEmitterComputed(user, (value) => value)

</script>

<template>
  <Test v-model="models.name"/>
</template>
```

<img width="659" alt="image" src="https://user-images.githubusercontent.com/61132849/212822180-e087fdbb-cfd7-4671-93a3-535bf35c8400.png">

Webstorm does not have this problem.
Completion shows a candidate as `WritableComputedRef<T>`, but the input is functioning as a type `T`.

It also functions properly in the following cases
```typescript

const models = reactive({
  name: computed({get: () => user.name, set: (value: string) => emit('user', value)})
})
</script>

<template>
  <Test v-model="models.name"/>
</template>
```

This issues occurs on :
 - Volar & Volar TypeScript Vue Plugin: v1.0.24
 - typescript: v4.9.4
 - vue: v3.2.36

**Comment by johnsoncodehk** [comment]
This is `defineComponent` type behavior, please report for https://github.com/vuejs/core.

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5YwA0cA6lMDAIYBGANngWAK4yrIBKGcAvnHRQCcAOQA3NqjEBuALAAoJQGMiAZ3j5wcALwoM2FoWIwAFAiVw461DDZgzASkRXrcNVk1CIEAFyIcPS0UAFUNAzM2uycPBgAPJrUWADmAHwCeoj8CorucFB2bFBYgei+ArnW-Er8TrlmOADucNHOTgB05RAdwVC5APQD+SOjAHoA-EpAA
