### ISSUE TITLE
Vue Semantic Server client: couldn't create connection to server.

### ISSUE THREAD

**Issue by dai-oh** [vuejs/language-tools#2322]
When using vecode to develop a vue3 project, this error is reported when opening the vue file, which has been a very long time problem for me, so I was confused and opened this issue, hoping to get help to solve this problem

**error mssage :** 

<img width="436" alt="image" src="https://user-images.githubusercontent.com/62934849/213074404-45790e35-41af-4c93-9533-fc132b22e317.png">

**output:** 

```
[Error - 11:11:11 AM] Server initialization failed.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'replace')
  Code: -32603 
[Error - 11:11:11 AM] Vue Syntactic Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'replace')
  Code: -32603 
```

**workspace ts version:** 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/62934849/213074764-ca813c26-bc3d-41f7-afe6-63fb3bd8923b.png">

**volar version:** 

<img width="470" alt="image" src="https://user-images.githubusercontent.com/62934849/213074890-09a5c18c-c324-42e7-b14e-07b70e2f0101.png">

**releate:** 
#1942

**Comment by dai-oh** [comment]
Und es führt dazu, dass vscode komplett abstürzt und unbrauchbar wird. Die einzige Möglichkeit, vscode weiter zu verwenden, ist die Deinstallation oder Deaktivierung von volar

**Comment by johnsoncodehk** [comment]
I have not heard of this problem, it may be related to your OS. Can you reproduce it in an isolated environment (e.g. Codespaces)? Otherwise, I may need your help to debug to determine which line of code the problem occurs.

**Comment by johnsoncodehk** [comment]
Can you try to debug it yourself first?

https://github.com/vuejs/language-tools#contribution-guide

If it's difficult to you, you can reach me on discord (johnsoncodehk#0495) and I'll follow up later.

**Comment by dai-oh** [comment]
> Can you try to debug it yourself first?你能先自己调试一下吗？
> 
> https://github.com/vuejs/language-tools#contribution-guide
> 
> If it's difficult to you, you can reach me on discord (johnsoncodehk#0495) and I'll follow up later.如果这对你来说有困难，你可以通过 discord (johnsoncodehk#0495) 联系我，我稍后会跟进。

好的。我先clone

> Can you try to debug it yourself first?
> 
> https://github.com/vuejs/language-tools#contribution-guide
> 
> If it's difficult to you, you can reach me on discord (johnsoncodehk#0495) and I'll follow up later.

I'll clone the repository first and debug locally, if I find the problem and solve it myself I'll reply here and close the issue, thanks for the reply.

**Comment by dai-oh** [comment]
The local F5 error message is as follows:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/62934849/220369104-7bddbc35-3825-49f5-b8cc-9c17c0e312a2.png">


After I cloned the repository to my local environment, I removed the contents.configuration.properties.typescript (as shown) from package.json, and then F5 started the plugin and it worked fine and no longer reported errors. Here is a report to you on the error reporting that occurred on my mac m1. I will close this issue.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/62934849/220367987-15deacea-b1fc-41f5-8457-32c38b9abedf.png">

**Comment by wluobing** [comment]
I have solved this issue. Since I use Neovim, I globally installed the npm package @volar/vue-language-server. After finding it through npm list, I uninstalled it and then restarted VSCode, and the problem was resolved.

```
npm uninstall -g @volar/vue-language-server
// or
npm uninstall @volar/vue-language-server
```
