### ISSUE TITLE
Vue component auto-import from monorepo library

### ISSUE THREAD

**Issue by jmroon** [vuejs/language-tools#2323]
When in a monorepo setup, i.e:

```
apps
-- vue-app
  -- tsconfig.json (paths alias to packages/ui)
packages
-- ui
  -- utils.ts
  -- MyPackageComponent.vue
```

Imports from utils.ts get correctly suggested on auto-import, but Vue components do not get suggested for auto-import. It seems that Vue component auto imports will only detect components that are within the app folder.

Is this a known issue? I was not able to find anything on this. A bit of a dealbreaker for a monorepo setup that relies on relative path imports.

**Comment by johnsoncodehk** [comment]
I'm taking a wild guess that this is expected TS behavior, please provide minimal reproduction if you need more detail information.
