### ISSUE TITLE
Volar缺少事件修饰符

### ISSUE THREAD

**Issue by lengyibai** [vuejs/language-tools#2325]
Vetur：
![image](https://user-images.githubusercontent.com/74140255/213606962-c0d41dd2-b0a1-46d8-9852-f9c6562a7b37.png)

Volar：
![image](https://user-images.githubusercontent.com/74140255/213607104-d7ca0c46-112e-47c9-8bec-93da673366fe.png)

Volar缺少事件修饰符，不知道是否设计如此？

**Comment by johnsoncodehk** [comment]
Cannot reproduce in v1.1.3.
