### ISSUE TITLE
facing error using volar with neovim lsp installed using mason

### ISSUE THREAD

**Issue by prmammoth** [vuejs/language-tools#2326]
When I open src/App.vue I see this error in my LspLogs

`[ERROR][2023-01-20 08:01:03] .../vim/lsp/rpc.lua:733	"rpc"	"vue-language-server"	"stderr"	"/home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/out/languageServerPlugin.js:62\n            return vue.getLanguageServicePlugins(vue2.resolveVueCompilerOptions(host.getVueCompilationSettings()), settings);\n                                                                                     ^\n\nTypeError: host.getVueCompilationSettings is not a function\n    at Object.getLanguageServicePlugins (/home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/out/languageServerPlugin.js:62:86)\n    at /home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/common/project.js:75:190\n    at Array.map (<anonymous>)\n    at Object.getPlugins (/home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/common/project.js:75:69)\n    at Object.get plugins [as plugins] (/home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-service/out/baseLanguageService.js:54:35)\n    at /home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-service/out/utils/featureWorkers.js:53:42\n    at Generator.next (<anonymous>)\n    at /home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-service/out/utils/featureWorkers.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/pankaj/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-service/out/utils/featureWorkers.js:3:12)\n"`

My npm configuration is
nvm use lts/gallium
I have used Mason to install vue-language-server

**Comment by pleshevskiy** [comment]
I've faced to the same issue. I've installed vue-language-server via `npm install -D vue-language-server` and add `node_modules/.bin` to the `PATH` environment variable.

**Comment by jimtendo** [comment]
Am also facing this issue on V1.0.24 (however, I am using KDE's Kate editor, not Neovim).

Anyone have any idea of the fundamental cause/fix for this? I'm thinking it might be mis-configuration.

For reference, this is what I'm using for Kate (largely copied from the Neovim Plugin):

```json
{
   "servers":{
      "vue":{
         "command":[
            "node",
            "/usr/lib/node_modules/@volar/vue-language-server/bin/vue-language-server.js",
            "--stdio"
         ],
         "rootIndicationFileNames":[
            "package.json",
            "package-lock.json"
         ],
         "url":"https://github.com/autozimu/LanguageClient-neovim",
         "highlightingModeRegex":"^Vue.*$",
         "initializationOptions":{
            "typescript": {
               "serverPath": "/usr/lib/node_modules/typescript-language-server/lib/cli.mjs"
            },
            "languageFeatures":{
               "references":true,
               "implementation":true,
               "definition":true,
               "typeDefinition":true,
               "callHierarchy":true,
               "hover":true,
               "rename":true,
               "renameFileRefactoring":true,
               "signatureHelp":true,
               "codeAction":true,
               "workspaceSymbol":true,
               "completion":{
                  "defaultTagNameCase":"both",
                  "defaultAttrNameCase":"kebabCase",
                  "getDocumentNameCasesRequest":false,
                  "getDocumentSelectionRequest":false
               },
               "documentHighlight":true,
               "documentLink":true,
               "codeLens":{
                  "showReferencesNotification":false
               },
               "semanticTokens":true,
               "diagnostics":true,
               "schemaRequestService":true
            },
            "documentFeatures":{
               "selectionRange":true,
               "foldingRange":true,
               "linkedEditingRange":true,
               "documentSymbol":true,
               "documentColor":true,
               "documentFormatting":true
            }
         }
      }
   }
}
```

**Comment by jimtendo** [comment]
The problem appears to be with the Neovim Typescript configuration.

```
            "typescript": {
               // serverPath needs to be renamed to tsdk and this value should be ABSOLUTE path to Typescript lib
               "tsdk": "/usr/lib/node_modules/typescript-language-server/lib/"
            },
```

It'd be nice, as a long term fix, if Volar might be able to auto-predict the path based on the project root though if this value is not provided explicitly. E.g. `${rootDir}/node_modules/typescript/lib`

**Comment by pleshevskiy** [comment]
@jimtendo thanks! relative path is also works for me in neovim editor!
```
{
  "typescript": {
    "tsdk": "node_modules/typescript/lib"
  }
}
```

**Comment by jimtendo** [comment]
@pleshevskiy Nice! Pretty confident I did see somewhere in the code that it had to be an absolute path, but cannot recall where.

In any case, relative path works for me too.

`"tsdk": "./node_modules/typescript/lib"`

**Comment by johnsoncodehk** [comment]
Relative paths may be a side effect of `paths: [tsdk]` in the following code and are not guaranteed to work.
https://github.com/volarjs/volar.js/blob/0550a10a9b70574648d5465ebc723630ef0400e8/packages/language-server/src/node/index.ts#L32

**Comment by jimtendo** [comment]
> Relative paths may be a side effect of `paths: [tsdk]` in the following code and are not guaranteed to work. https://github.com/volarjs/volar.js/blob/0550a10a9b70574648d5465ebc723630ef0400e8/packages/language-server/src/node/index.ts#L32

Might it be possible to officially support relative paths future? In some iDE's (e.g. KDE's Kate Editor), there isn't yet the capability to inject dynamic variables (e.g. current root) into the config, so this'd be useful for things like that.

**Comment by johnsoncodehk** [comment]
You can take it as official, we don't have much chance of changing that code.
