### ISSUE TITLE
Vue-tsc not excluding node_modules even when it is set in the config

### ISSUE THREAD

**Issue by marhyn** [vuejs/language-tools#2328]
## Minimal repo
I made a minimal reproduction repo: https://github.com/marhyn/vue-tsc-not-ignoring-node_modules

## Description
Even when "node_modules" are excluded from the tsconfig.json, type-check report those errors. I would like to type-check only the source code of the project. "skipLibCheck" compiler option is also turned on.

**Comment by johnsoncodehk** [comment]
Duplicate of #2018
