### ISSUE TITLE
Goto definition for Vue components is not working for Nuxt 3 project

### ISSUE THREAD

**Issue by uros-5** [vuejs/language-tools#2330]
This LSP is working really good in Vue 3 projects.
Recently I started using it with Nuxt 3 and it's all good except Goto definition feature for components. I understand why editor redirects me to ```components.d.ts```. But from there I should be redirected directly to component.
Instead it redirects me to ```vue-shim.d.ts```.
![output](https://user-images.githubusercontent.com/59397844/213909245-880adda2-f321-451a-8d16-82737e02f03f.gif)
I'm using Helix Editor, in neovim I have same problem.
Volar version: 1.0.24

**Comment by saschafuchs** [comment]
I had this also in VSCode

**Comment by Flashantik** [comment]
try vscode extension "Goto definition alias" with this files open good, but file components.d.ts still opening and it's very annoying ;((

**Comment by gabrielcipriano** [comment]
I'm having this issue too with Nuxt 3 + typescript

I already have Volar takeOver mode activated 
![image](https://user-images.githubusercontent.com/20933608/218757923-723f0809-d184-449f-943f-c5429e880c9b.png)

**Comment by so1ve** [comment]
Note: the second click redirects to `vue-shim.d.ts` is the expected behavior - to disable it just simply add:

```ts
export default defineNuxtConfig({
  typescript: {
    shim: false
  }
})
```

to your `nuxt.config.ts`

**Comment by so1ve** [comment]
I'm not sure if mark this issu as an `enhancement` is appropriate -  this seemed to be typescript's behavior and we should not change it.

**Comment by rchl** [comment]
For Nuxt 2 I've created https://github.com/rchl/volar-component-types which uses "experimental modules" to provide a mapping so that "go to definition" skips the intermediate file definition. Same could be done for Nuxt 3 but not sure how this could be done in a clean and simple way because my package is anything but that.

**Comment by uros-5** [comment]
> For Nuxt 2 I've created https://github.com/rchl/volar-component-types which uses "experimental modules" to provide a mapping so that "go to definition" skips the intermediate file definition. Same could be done for Nuxt 3 but not sure how this could be done in a clean and simple way because my package is anything but that.

Nice.
This [small script](https://github.com/uros-5/extended-volar)  does that for Nuxt 3 projects. `typescript.js` is not related to build process.
