### ISSUE TITLE
Moving components doesn't trigger import updates

### ISSUE THREAD

**Issue by VladBrok** [vuejs/language-tools#2331]
I have a component with two files: .vue and .ts in one folder. When I move the folder, imports are not updated

Example component:

src/my-cool-component/my-cool-component.vue
```vue
<template>hi</template>
<script lang="ts" src="./my-cool-component.ts"></script>
```
src/my-cool-component/my-cool-component.ts
```ts
export default defineComponent({
  name: "Name",
  setup() {
    ...
  }
})
```

**Comment by VladBrok** [comment]
@johnsoncodehk imports are still not updated. I have to search for files where I import this component and manually update all imports

**Comment by johnsoncodehk** [comment]
I can't reproduce it, please open a new issue and provide minimal reproduction.
