### ISSUE TITLE
Experimental RFC 436 - using `withDefaults` with generic attribute cause error 

### ISSUE THREAD

**Issue by Sengulair** [vuejs/language-tools#2337]
I'm trying to use `withDefaults` function to set the default value for the property, but some error occurs. There is no error if I define props without it.

![image](https://user-images.githubusercontent.com/29776412/214407361-6cf2effb-2580-4152-a49b-8cdf3972ff8d.png)
Here is a [public repo](https://github.com/Sengulair/vue-rfc436) to showcase the issue. The generic component with the error is AppInput.vue

**Comment by johnsoncodehk** [comment]
See https://github.com/vuejs/language-tools/pull/1964#issuecomment-1277536987
