### ISSUE TITLE
No/broken support for declaration maps in takeover mode. 

### ISSUE THREAD

**Issue by filimon-danopoulos-stratsys** [vuejs/language-tools#2340]
I have a typescript project that emits type declarations and [declaration maps](https://www.typescriptlang.org/tsconfig#declarationMap). When I use takeover mode, "F12" does not take me to source code as defined in the declaration map but rather the `.d.ts` file. When I use the builtin typescript language service this works as intended.

**Comment by Dealerpriest** [comment]
I can confirm this behaviour on my end. Seems like a rather important bug to me 🤔

**Comment by filimon-danopoulos-stratsys** [comment]
It is mostly annoying since take over mode is the preferred (and quite heavily pushed) way of running Volar. It could be argued that is not very pressing since the type definitions work.

**Comment by johnsoncodehk** [comment]
Can you try `"volar.vueserver.noProjectReferences": true`? See https://github.com/johnsoncodehk/volar/issues/1344#issuecomment-1279639493

**Comment by filimon-danopoulos-stratsys** [comment]
With Volar takeover mode enabled and the setting proposed in `.vscode/settings.json` it does not not work for me. Tried restarting Volar and VSCode but made no difference. 

Not sure if it makes any difference but the `.d.ts` and corresponding `.d.ts.map`  files are in an npm-package.

**Comment by Dealerpriest** [comment]
Same here. Unfortunately not working in a monorepo with several typescript projects/packages
![image](https://user-images.githubusercontent.com/363913/216333305-551e9401-b37f-474c-98ce-528594b42d13.png)

**Comment by patroza** [comment]
same here, really annoying, especially when onboarding new people

**Comment by blake-newman** [comment]
should be resolved with: https://github.com/volarjs/volar.js/pull/24

**Comment by gustavotoyota** [comment]
I'm having this problem as well. Is there a workaround I can use right now?
I'm trying to use @blake-newman's solution, but I can't find know to test locally.
