### ISSUE TITLE
optimize imported vue component type info when hover

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#2346]
Instead of:

![image](https://user-images.githubusercontent.com/41773861/215379397-7d71dc06-cfb6-4e0b-8df2-6953c1ff5a61.png)

Should like:

![image](https://user-images.githubusercontent.com/41773861/215379491-6dda7da6-1b15-4438-bd14-80e7b8601268.png)

**Comment by johnsoncodehk** [comment]
This is TS behavior and we can't change.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/16279759/219973002-daee2d60-a1b5-4aba-b50d-f33d0ad7b23c.png">
