### ISSUE TITLE
Typeof in template v-if conditions causes syntax color issues.

### ISSUE THREAD

**Issue by ThomasBerne** [vuejs/language-tools#2348]
Using typeof in template causes the syntax color to break:

![image](https://user-images.githubusercontent.com/23033483/215692196-5acbb45a-7f34-49a0-bc8a-473026921923.png)

I expect the syntax color to be normal. The application works well. That only seems to be a Volar issue.

**Comment by johnsoncodehk** [comment]
Duplicate of #656
