### ISSUE TITLE
can't find volar split editor button but only the vite preview button with latest vscode and volar

### ISSUE THREAD

**Issue by 77-arthur** [vuejs/language-tools#2354]
i lose the split button in latest version of vscode and volar.

![image](https://user-images.githubusercontent.com/50293747/216227101-1f9c43b1-e4d5-4be0-98b0-c9c52b2f7df2.png)

**Comment by danielwaltz** [comment]
I think it has defaulted to being hidden, you should be able to get it to show up again by checking the volar options in vscode and enabling it again!

**Comment by 77-arthur** [comment]
> I think it has defaulted to being hidden, you should be able to get it to show up again by checking the volar options in vscode and enabling it again!

thank you!! i found and enabled the split editors in settings
![image](https://user-images.githubusercontent.com/50293747/218668542-d1d58511-b824-44fc-99c6-b18e7f1c6ed6.png)
