### ISSUE TITLE
when dynamic ref have string param,the syntax highlight will broken. 

### ISSUE THREAD

**Issue by chenbimo** [vuejs/language-tools#2356]
if have editDataDialog string param

![image](https://user-images.githubusercontent.com/33003566/216501274-bc46e243-10fc-47dd-ba58-37994d2b06e5.png)

if no editDataDialog string param

![image](https://user-images.githubusercontent.com/33003566/216501566-54a7c9bb-d32b-44a2-8f68-e89907303781.png)

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem, please try disable other vue syntax extensions if you have installed.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/16279759/219972636-0e69bfc6-8ee3-4faf-a749-c5a1340d871b.png">
