### ISSUE TITLE
Provide line comments instead of block comments in SCSS

### ISSUE THREAD

**Issue by otomad** [vuejs/language-tools#2358]
VSCode

In the `<style lang="scss">` block of a vue file,
when **toggle line comment** (default shortcut key is <kbd>Ctrl</kbd> + <kbd>/</kbd>), it will **toggle block comment** like a normal css.

**Before:**  
![image](https://user-images.githubusercontent.com/56647156/216549001-5b3df782-166f-4584-b0d2-a737b08d1212.png)  
**After:**  
![image](https://user-images.githubusercontent.com/56647156/216549165-b23e3fe5-c1da-4407-871c-5a27ce6b601b.png)  
**Expect this:**  
![image](https://user-images.githubusercontent.com/56647156/216549231-3706d262-9a8d-4490-9872-84ca4fb86a45.png)  
And then if you want to remove this line comment, toggle line comment, it will do something strange like this:  
![image](https://user-images.githubusercontent.com/56647156/216549894-c249069f-c5e5-4540-a5cf-08da9181204c.png)

However, **Less** `<style lang="less">` works fine.  
![image](https://user-images.githubusercontent.com/56647156/216550690-f5465d6c-39c1-4ece-92be-d04d85dbf070.png)  
And single .scss file works fine too.

**Comment by johnsoncodehk** [comment]
Commenting behavior is defined by extensions you have installed related to the SCSS language, try disabling extensions that may be related.
