### ISSUE TITLE
vue文件语法检查时使用了@types/react

### ISSUE THREAD

**Issue by volatile-static** [vuejs/language-tools#2364]
![image](https://user-images.githubusercontent.com/59945270/217235786-3bc836ec-dd24-404a-afa4-f7b88d1eaf77.png)
图中的`index.d.ts`是`@types/react`的，在tsconfig中限制了types也没有效果

**Comment by johnsoncodehk** [comment]
See #592. If you also just disable `jsxTemplates` in tsconfig if you can't resolve the problem.
