### ISSUE TITLE
Feature request: add an indicator to show we're on takeover mode

### ISSUE THREAD

**Issue by rodrigocfd** [vuejs/language-tools#2365]
When used with VSCode, Volar may use [takover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) to improve performance, but there's no way to know whether it's active or not. One must redo all the steps in order to check it.

It would be helpful to have, in the status bar, an indicator showing we're currently on takeover mode.

**Comment by yusufkandemir** [comment]
Takeover mode OFF:
![image](https://user-images.githubusercontent.com/6266078/217611396-51a0a9af-d9d8-4460-aa2f-0332ba763e59.png)

Takeover mode ON:
![image](https://user-images.githubusercontent.com/6266078/217611512-ba84c58f-72ae-4d71-9974-bc0d56e75ee1.png)

Along with other stuff, `(vue)` should be enough to understand that it's active. If you click that, you will be presented with this dialog:
![image](https://user-images.githubusercontent.com/6266078/217611787-65a374e7-be14-4e8f-9115-d0be447a01fe.png)
Which also gives a hint about the takeover mode.

**Comment by rodrigocfd** [comment]
So when `packages/client/tsconfig.json` is present, it means takeover mode is active? I really don't think this is a good indication at all.

I'd expect to see something like `Takeover: on`. That would be clear.

**Comment by yusufkandemir** [comment]
That was not what I meant, the version number and `(vue)` after that is the main point. Personally, the version number and `(vue)` is enough, but `(takeover)`/`(vue/takeover)` could also be a more verbose option.

**Comment by johnsoncodehk** [comment]
@yusufkandemir's suggestion is correct, please note that you should be opening .ts not .vue files to judge it.

On the other hand, more explicit prompts can also be considered. In fact, the old version used to display `(takeover)` in the status bar, which was simplified to `(vue)` in order to reduce the space occupied by the status bar.
