### ISSUE TITLE
Documentation is unclear about takeover mode

### ISSUE THREAD

**Issue by bgirschig** [vuejs/language-tools#2373]
I believe the following leads to confusion:
> It's recommended to [use take over mode instead of this plugin](https://github.com/johnsoncodehk/volar/discussions/471).

([source](https://github.com/vuejs/language-tools/blob/master/packages/vscode-typescript-vue-plugin/README.md?plain=1#L7))

Reading the official documentation, trying to create a fresh install for a vue+typescript project, here is what I did:

- `npm init vue@latest`, select options (typescript, unit testing, etc...)
-  install recommended plugins for VSCode
- `TypeScript Vue Plugin (Volar)`'s readme says the following:
> It's recommended to [use take over mode instead of this plugin](https://github.com/johnsoncodehk/volar/discussions/471).
- The link points towards a github issue that states:
> Some content of this post is outdated, please check official document instead of this post.
> 👉 https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode
- I follow the instructions from the official document
- To keep things clean, and because the plugin's documentation recommends using take over mode **INSTEAD OF** using this plugin, I uninstall the plugin.
- VScode complains about missing dependencies on `.vue` imports from `.ts` files
- After a long google+stackoverflow search, I end up re-installing and re-enabling the plugin, which fixes the issue

If I understand correctly (that the `TypeScript Vue Plugin (Volar)` is still required even with takeover mode), I think it would be helpful to:
- update the link to point directly to the [official documentation](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) instead of the obsolete [github issue](https://github.com/johnsoncodehk/volar/discussions/471)
- rephrase the sentence to something like this:
> It's recommended to [enable take over mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) for this plugin.

**Comment by johnsoncodehk** [comment]
> * VScode complains about missing dependencies on `.vue` imports from `.ts` files

I think you just didn't successfully enable takeover mode, otherwise this wouldn't happen. Are you sure `vscode.typescript-language-features` is disabled?

When you are running in takeover mode, `TypeScript Vue Plugin (Volar)` just has no effect, whether it is enabled or not.

This picture might help you understand: https://twitter.com/johnsoncodehk/status/1518166710343241728
