### ISSUE TITLE
Takeover Mode: Cannot Ctrl + Click in TypeScript lib files (e.g. `lib.es2015.core.d.ts`)

### ISSUE THREAD

**Issue by 0x00A1FA** [vuejs/language-tools#2374]
Repro:

1. Make a JS/TS file;
2. Type `HTMLInputElement` or whatever you know is inside a global VS Code resource file and then `Ctrl + Click` it;
3. You'll find yourself inside `lib.dom.d.ts`;
4. Try to `Ctrl + Click` anything and see that it's not working (such as `HTMLElement` from line 7073).

Please note that the default TS extension works fine.

How can we fix this? Sorry if it's already been discussed. I couldn't find a similar issue.

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem, do you have reload vscode after disable built-in TS extension?
