### ISSUE TITLE
File path in console output does not hyperlink to file when running in docker

### ISSUE THREAD

**Issue by austin-agronick** [vuejs/language-tools#2376]
Is there a way to change the file path to a relative path?

For example in the error:
```
ERROR(vue-tsc)  Property 'props' does not exist on type 'never'.
FILE  /srv/app/client/src/components/component.vue:78:54
```
my docker container moves the app files to `/srv/app`. Can `/srv/app` be excluded from this file path?
also can a full file path using `file:///` be used to create a hyperlink to the file?

**Comment by johnsoncodehk** [comment]
What will `tsc` show in this case?

**Comment by austin-agronick** [comment]
Expected output should be: 
```
ERROR(vue-tsc)  Property 'props' does not exist on type 'never'.
FILE  file:////home/austin/PycharmProjects/project/client/src/components/component.vue:78:54
```

**Comment by johnsoncodehk** [comment]
This seems to be the behavior of tsc, vue-tsc is just a wrapper of tsc, so we can't change it.
