### ISSUE TITLE
vue-tsc  error TS2339

### ISSUE THREAD

**Issue by hhucqian** [vuejs/language-tools#2379]
When define two `declare module 'vue' {}` in multiple files , `vue-tsc`  will report  error TS2339。

当在两个文件中定义两次 `declare module 'vue' {}` 时， `vue-tsc`就会报错。

test repo:

https://github.com/hhucqian/vue-tsc-problem

**Comment by johnsoncodehk** [comment]
This is TS 4.7 issue, you can upgrade the workspace TS version to fix.
