### ISSUE TITLE
Still has some problem with functional component.

### ISSUE THREAD

**Issue by jerrywu001** [vuejs/language-tools#2381]
First of all, I appreciate your solution about (#2206), There is still a problem with the functional component.

See: https://github.com/jerrywu001/volar-issue#readme

You can go ahead and run my project to check the problem.

The correct(Volar0.40.x ):
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/12525415/207520016-d60c898a-7cdb-41fa-b018-8506836283db.png">

**But now**:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/12525415/218621835-db6297ea-fafd-45bb-9d22-a148a1db9fff.png">

**Comment by johnsoncodehk** [comment]
Fixed in v1.4.0 later.
