### ISSUE TITLE
代码格式化出错，每格式化一下，script下方会增加一个空白行

### ISSUE THREAD

**Issue by xinde** [vuejs/language-tools#2385]
![image](https://user-images.githubusercontent.com/1617414/219248445-79bd56b2-717a-4dfb-9fe5-238d4a8b9341.png)

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by xinde** [comment]
> Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

奇怪，用这个没有复现，我再查查

**Comment by johnsoncodehk** [comment]
@MothWillion, @xinde do you have volar.config.js?

**Comment by xinde** [comment]
> @MothWillion, @xinde do you have volar.config.js? (Please show me if yes)

No,I don't have volar.config.js

**Comment by johnsoncodehk** [comment]
Do you have TS format settings in `.vscode/settings.json`?

**Comment by xinde** [comment]
> Do you have TS format settings in `.vscode/settings.json`?

没有，因为有工作要马上处理，我安装回了上一个版本的volar，恢复了正常

**Comment by Tanimodori** [comment]
I can reproduce this bug in https://github.com/johnsoncodehk/volar-starter

**Comment by johnsoncodehk** [comment]
Just publish v1.1.1 to fix it, please update later.

**Comment by RoadsideParty** [comment]
我也有同样的问题

**Comment by lmy1991** [comment]
before
![image](https://user-images.githubusercontent.com/12825728/219282633-8a09c2eb-2308-4a00-9440-a1794c0cc8cf.png)

v1.1.1
![image](https://user-images.githubusercontent.com/12825728/219282922-d5922c4f-3773-4ac7-a16c-01488c3c0679.png)

**Comment by johnsoncodehk** [comment]
@lmy1991 please open a new issue.
