### ISSUE TITLE
Takeover mode enabled automatically and cannot be disabled (after upgraded to `1.1.x`)

### ISSUE THREAD

**Issue by ecoms-ye** [vuejs/language-tools#2389]
## Environment 

- Vue: 2.7.14 (from `npm create vue@2`)
- Volar:  1.1.0 & 1.1.1
- vscode: 1.75.1
- WSL2 (ubuntu 22.04)

## Description

After upgraded to `1.1.x`, the takeover mode is enabled automatically even if the builtin "TypeScript and JavaScript Language Features" is not disabled. After rollback to `v1.0.24`, takeover mode would be disabled normally.

## Expectation

Let the take over mode enable/disable as [document](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode).

**Comment by johnsoncodehk** [comment]
That's just a display bug, the takeover mode is not actually enabled if you don't disable the TS extension.
