### ISSUE TITLE
Formatting deletes the template automatically

### ISSUE THREAD

**Issue by leessmin** [vuejs/language-tools#2390]
I added a comment under template, then formatted and found that my template was removed

Before formatting
![uTools_1676522793729](https://user-images.githubusercontent.com/101449039/219271121-e9ab98a3-4bf5-439b-9001-88d9de2d0b8c.png)

After formatting
![uTools_1676522804332](https://user-images.githubusercontent.com/101449039/219271110-0e5a0d7b-dc9b-458b-8d1d-aec95e00fa01.png)

version
![uTools_1676522859778](https://user-images.githubusercontent.com/101449039/219271225-83ed5277-1c4f-4801-9981-a26f75a8e463.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by leessmin** [comment]
> Thanks for the report, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

yes，The same problem arises again。You just need to add a comment under the template tag for formatting。
![uTools_1676523357898](https://user-images.githubusercontent.com/101449039/219272287-c0f3c706-c451-41eb-ae5e-d3f969056dc9.png)

**Comment by johnsoncodehk** [comment]
Confirm!

**Comment by leessmin** [comment]
> Confirm!

thank you

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/2a6ed8e45635635f63a906d41817f311128d2855
