### ISSUE TITLE
typography error after formatting

### ISSUE THREAD

**Issue by lmy1991** [vuejs/language-tools#2393]
v1.0.24
![image](https://user-images.githubusercontent.com/12825728/219284549-dfc1b818-7e3a-4d08-868f-89a354a6a72a.png)

v1.1.1
![image](https://user-images.githubusercontent.com/12825728/219284576-7f87b7b5-d389-43d1-ade9-be4bc8684a57.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report, can you reproduce this problem with https://github.com/johnsoncodehk/volar-starter?

**Comment by lmy1991** [comment]
> 

![image](https://user-images.githubusercontent.com/12825728/219288909-2465e645-d70f-4e79-98c5-2f8e89daa6f5.png)

**Comment by lmy1991** [comment]
> 感谢报告，您可以使用https://github.com/johnsoncodehk/volar-starter重新发现这个问题吗？

![image](https://user-images.githubusercontent.com/12825728/219289023-c449b2ae-8a46-46c7-b360-17d51bf4ff10.png)
v1.1.1
