### ISSUE TITLE
Incidentally inserting indents on all lines when inserting new lines with volar.format.initialIndent set to true in v1.1.1

### ISSUE THREAD

**Issue by Tanimodori** [vuejs/language-tools#2394]
When inserting new lines in vue sfc script block, all lines get indented as shown below:

![volar](https://user-images.githubusercontent.com/29478770/219285582-853ba0b1-c3d4-48dd-a637-5a2da4418a1a.gif)

Related `settings.json` part. Remove these lines will fix this issue.

```
  "volar.format.initialIndent": {
    "html": true,
    "javascript": true,
    "typescript": true
  },
```

Env: Windows 11, vscode 1.75.1, volar 1.1.1

**Comment by johnsoncodehk** [comment]
You can disable `editor.formatOnType` to avoid this problem for now. Please note that remove `volar.format.initialIndent` will change the formatting result.
