### ISSUE TITLE
template内标签不对齐

### ISSUE THREAD

**Issue by MuyianKing** [vuejs/language-tools#2395]
![捕获](https://user-images.githubusercontent.com/44827414/219306390-81ce59f0-d1bc-4803-a3ca-01213f12b8cd.PNG)

**Comment by leessmin** [comment]
我也遇到这个问题了，新版本，bug有点多，我目前已经回退到v1.0.24，这个本版貌似bug比较少。目前正常使用没有发现问题

**Comment by johnsoncodehk** [comment]
Duplicate of #2393
