### ISSUE TITLE
Incidentally removing indents on line when inserting new lines with volar.format.initialIndent set to true in v1.1.2

### ISSUE THREAD

**Issue by otomad** [vuejs/language-tools#2401]
The last error #2394 is fixed, but now it starts to remove the indents, whether `volar.format.initialIndent` set to true or false.

#### settings.json
```json
  "volar.format.initialIndent": {
    "html": true,
    "javascript": true,
    "typescript": true,
  },
  "editor.formatOnType": true,
```

#### Before
```javascript
····​const foo = ref();
····​const bar = ref();
····​const baz = ref();|
```

#### After press enter
```javascript
····​const foo = ref();
····​const bar = ref();
const baz = ref();
····|
```

**Comment by johnsoncodehk** [comment]
Thanks for the report, this is a known limitation, there are too many edge cases to support `formatOnType` for `initialIndent`, so the current version ignores it for now.

**Comment by Tanimodori** [comment]
Add a screenshot for this issue.

![volar2](https://user-images.githubusercontent.com/29478770/219541478-4d54691e-1688-424b-b89f-5a766ea0857a.gif)
