### ISSUE TITLE
The experimental features for vite can not be used after volar1.1

### ISSUE THREAD

**Issue by wen-bug** [vuejs/language-tools#2402]
**This is a version after 1.0**
![Snipaste_2023-02-17_11-44-10](https://user-images.githubusercontent.com/56168055/219544092-3d47c981-7201-47c4-beea-b6d173e4f0ee.png)
![Snipaste_2023-02-17_11-44-31](https://user-images.githubusercontent.com/56168055/219544096-b37c5bb8-c2c8-4db1-8ae7-40bc014193b3.png)

**This is a version  1.0.24**
![image](https://user-images.githubusercontent.com/56168055/219544767-ba25d7b9-20c4-4338-a839-44396bc49fa0.png)
Does anyone know why

**Comment by johnsoncodehk** [comment]
Please use https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-vue-preview, see https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#110-2023216 > Breaking changes.
