### ISSUE TITLE
Missing required props hint not working with `v-model` with recent Volar update

### ISSUE THREAD

**Issue by Meesayen** [vuejs/language-tools#2407]
I've updated to the latest Volar 1.1.2, and now I'm getting missing `modelValue!` hints on all components that defined a required `modelValue` even if the correct `v-model` is passed to them. 

Here some screenshot to better show the problem:
<img width="579" alt="Screenshot 2023-02-17 at 11 02 28" src="https://user-images.githubusercontent.com/298675/219614995-d509a499-a61d-4430-b6ca-d7b0945ea903.png">

here all the components define a required `modelValue` and they are passed a proper value via `v-model` but we still get the hint, as if we were not passing a proper `:modelValue` to them.

Likewise, the same happen with named `v-model` scenarios:
<img width="544" alt="Screenshot 2023-02-17 at 11 00 17" src="https://user-images.githubusercontent.com/298675/219615392-e3e0d7c3-d263-456d-86d8-e1268fdbfcad.png">

**Comment by johnsoncodehk** [comment]
Thanks for the report!

**Comment by sbscan** [comment]
+1
