### ISSUE TITLE
Bug: Cannot collapse code in .ts files after 1.1.0 update

### ISSUE THREAD

**Issue by jagoncalves14** [vuejs/language-tools#2408]
For some weird reason, I can no longer collapse code in TypeScript files.
Note: Everything is working in `.vue` files. It's really just on `.ts` files.

**Here is a video** demonstrating the issue:

https://user-images.githubusercontent.com/17235977/219659722-3aecaa77-f2d2-45aa-8856-6dfa8a58ce76.mp4

**Comment by johnsoncodehk** [comment]
Thanks for the report!
