### ISSUE TITLE
v1.1.x Cannot rename html tags

### ISSUE THREAD

**Issue by ludwig801** [vuejs/language-tools#2410]
### Description

Since version 1.1.x that renaming html tags through F2 command does not work. 
Renaming tags which relate to imported components, however, works just fine.

In version 1.0.24 any tag could be renamed just fine.

### Environment

- VSCode: `v1.75.1`
- Volar: `v1.1.2` (reproduced in `v1.1.1` and `v1.1.0`, working on `v1.0.24`)
- Using takeover mode? `Yes`

**Comment by johnsoncodehk** [comment]
Thanks for the report!
