### ISSUE TITLE
required attribute in defineProps not being autocompleted 

### ISSUE THREAD

**Issue by qwerty084** [vuejs/language-tools#2411]
The required attribute isnt being correctly autocompleted. In provided an example in the video.
Same goes for default attribute

Volar & Volar(TS) Version: v1.1.2
Vscode: 1.75.1
Take over mode is enabled.

Would be nice if those attributes would be autocompleted.

[required_attribute.webm](https://user-images.githubusercontent.com/81753196/219791224-ce2f163a-583e-4d72-9ea9-8cc5ce6cf035.webm)

**Comment by so1ve** [comment]
Oh I think this is a vue type bug. Use union type like `T & Generic<T>` will make all the properties to be any when autocomplete. I also met this error in my project.

**Comment by johnsoncodehk** [comment]
Please forward to https://github.com/vuejs/core
