### ISSUE TITLE
Why does automatic completion is PascalCase not kebab-case?

### ISSUE THREAD

**Issue by R0boter** [vuejs/language-tools#2416]
Why does automatic completion is PascalCase not kebab-case? need me to configure anything? thanks
![image](https://user-images.githubusercontent.com/41858428/219854393-1a6b54ce-95dd-4556-bcec-6917ca9b76d2.png)
I use neovim, completion plugin is nvim-cmp
this is my config

    lspconfig.volar.setup {
      filetypes = {
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "vue"
      },
      init_options = {
        languageFeatures = {
          completion = {
            defaultTagNameCase = "kebabCase",
            defaultAttrNameCase = "camelCase"
          }
        }
      }
    }

I also try vscode, it's no probrem

**Comment by johnsoncodehk** [comment]
You can config `"volar.completion.preferredTagNameCase": "kebab"` to the IDE settings.
