### ISSUE TITLE
volar emit's autocomplete child component shows wrong options

### ISSUE THREAD

**Issue by ezmemoar** [vuejs/language-tools#2418]
This is my component with a declared emit:
![image](https://user-images.githubusercontent.com/48541679/219920447-62be6b1d-eda4-42a9-8a59-475b9c20b1d6.png)

Here, I declared an emit named `log`. When I access it in the parent view, the expected autocomplete property should have been `@log` and `v-on:log`. But it show some wrong options e.g. using `v-bind` and an emit with extra "on" text in the first:
![image](https://user-images.githubusercontent.com/48541679/219920991-13392ac4-d0d2-4dad-8ebc-22c0dd40dd62.png)

**Comment by johnsoncodehk** [comment]
The language server actually provides `@log`, but it seems to be filtered by VSCode.

**Comment by johnsoncodehk** [comment]
It seems that the current version of VSCode does not have this problem.
