### ISSUE TITLE
How to get prop's completion when the component is a property of an object?

### ISSUE THREAD

**Issue by ylw5** [vuejs/language-tools#2419]
I write an vue component, and has two ways to import.

./src/components/popper
```
import Root from './src/components/Root.vue'
import Anchor from './src/components/Anchor.vue'

export default {
  Root,
  Anchor,
}
export const PopperRoot = Root
export const PopperAnchor = Anchor
```
So I can import and use in two ways
```vue
import Popper, { PopperRoot, PopperAnchor } from './src/components/popper'
```
```
<template>
  <Popper.Root>
    <Popper.Anchor />
  </Popper.Root>
</template>
```
or
```
<template>
  <PopperRoot>
    <PopperAnchor />
  </PopperRoot>
</template>
```
only the latter one can get prompt when input props.

[![enter image description here][1]][1]

[![enter image description here][2]][2]

I'm confused, I don't know what should I do to get code hints?

  [1]: https://i.stack.imgur.com/HeVsC.png
  [2]: https://i.stack.imgur.com/YTmXM.png

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/vuejs/language-tools/commit/e3dc9b5964f219ae1b6c11b1a3d10e539b28f8ae
