### ISSUE TITLE
Some component tag has toString! and toLocaleString! attr hint

### ISSUE THREAD

**Issue by kikyous** [vuejs/language-tools#2427]
volar: v1.1.4
vue: 2.6

![image](https://user-images.githubusercontent.com/818616/220064083-a5cae53f-e4f6-400f-88de-504ef682e71c.png)

**Comment by kikyous** [comment]
![image](https://user-images.githubusercontent.com/818616/220074861-b8426253-2e20-447a-9f00-5bfb278c2b29.png)

and `value!`

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by johnsoncodehk** [comment]
Please track #2443 as there has a repro case.
