### ISSUE TITLE
Weird volar.inlayHints.missingRequiredProps behavior.

### ISSUE THREAD

**Issue by houd1ni** [vuejs/language-tools#2432]
If it is enabled in at least last two versions, my inputs goes nut:
![image](https://user-images.githubusercontent.com/7501201/220210427-7505732c-b8f6-4fe0-a0f8-dd37e2859b88.png)
... another some hundred of attributes ...
last columns:
![image](https://user-images.githubusercontent.com/7501201/220210536-b31a8c49-e261-4958-8a46-9917cbe79545.png)

**Comment by johnsoncodehk** [comment]
Duplicate of #2443

**Comment by houd1ni** [comment]
> Duplicate of #2443

Actually, that issue is a duplicate, anyway, thanx for the quick fix !
