### ISSUE TITLE
code format cause <template> lost

### ISSUE THREAD

**Issue by myronxu4ever** [vuejs/language-tools#2435]
If the < template > tag is followed by a comment<! -->,
Repeated running of volar's code format will cause the < template > tag to be lost

**Comment by myronxu4ever** [comment]
first:<img width="75" alt="image" src="https://user-images.githubusercontent.com/99420857/220246489-e3d80cec-337c-4ad3-97da-7655a40cfc8f.png">
second:<img width="112" alt="image" src="https://user-images.githubusercontent.com/99420857/220246424-06e82e22-8c67-48f6-b07c-cd466956201e.png">
and then:<img width="97" alt="image" src="https://user-images.githubusercontent.com/99420857/220246529-cb12960b-5c43-4d1f-8669-6dcadad2fcf2.png">

**Comment by johnsoncodehk** [comment]
Thanks for the report! You can use this version for now: 
[volar-1.1.6-alpha.1.vsix.zip](https://github.com/vuejs/language-tools/files/10790000/volar-1.1.6-alpha.1.vsix.zip)
