### ISSUE TITLE
Rename packages in 2.0

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#2437]
First of all, I'm sorry that this is the second renaming proposal (the first time is `@volar/server` -> `@volar/vue-language-server`). Volar now belongs to Vue, so I hope Volar can be better integrated into the Vue ecosystem in the long run.

Changes:

- `@volar/vue-language-server` -> `@vue/language-server`
- `@volar/vue-language-service` -> `@vue/language-service`
- `@volar/vue-language-core` -> `@vue/tooling-core` / `@vue/tools-core`
- `@volar/vue-language-plugin-pug` -> `@vue/tooling-plugin-pug` / `vue-tooling-plugin-pug` / `vue-tools-plugin-pug`

We currently don't have a timetable for 2.0, this issue is just for changes notice and opinion collection.

cc @yaegassy, @sethidden, @tsukkee, @predragnikolic, @rchl, @kabiaa, @jadestrong, @tommasongr, @yoyo930021, @xiaoxin-sky, @yyx990803, @ouuan, @williamboman

**Comment by jawomg** [comment]
> ก่อนอื่น ฉันขอโทษที่นี่เป็นข้อเสนอการเปลี่ยนชื่อครั้งที่สอง (ครั้งแรกคือ`@volar/server`-> `@volar/vue-language-server`) ตอนนี้ Volar เป็นของ Vue ดังนั้นฉันหวังว่า Volar จะสามารถรวมเข้ากับระบบนิเวศของ Vue ได้ดีขึ้นในระยะยาว
> 
> การเปลี่ยนแปลง:
> 
> * `@volar/vue-language-server`->`@vue/language-server`
> * `@volar/vue-language-service`->`@vue/language-service`
> * `@volar/vue-language-core`-> `@vue/tooling-core`/`@vue/tools-core`
> * `@volar/vue-language-plugin-pug`-> `@vue/tooling-plugin-pug`/ `vue-tooling-plugin-pug`/`vue-tools-plugin-pug`
> 
> ขณะนี้เราไม่มีตารางเวลาสำหรับ 2.0 ปัญหานี้ใช้สำหรับประกาศการเปลี่ยนแปลงและการรวบรวมความคิดเห็นเท่านั้น
> 
> ซีซี@yaegassy,@sethidden,@tsukkee,@predragnikolic,@rchl,@kabiaa,@jadestrong,@tommasongr,@yoyo930021,@xiaoxin-sky,@yyx990803,@ouuan,@williamboman
