### ISSUE TITLE
Error: Request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by Nauxscript** [vuejs/language-tools#2438]
I got the below error after upgrading volar:
```
Error: selectionRange must be contained in fullRange
    at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:26004)
    at new t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:26218)
    at sn (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:33:79365)
    at sn (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:33:79542)
    at sn (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:33:79542)
    at sn (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:33:79542)
    at s (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:33:54756)
    at Object.xP [as map] (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:33:54842)
    at Object.ji [as asDocumentSymbols] (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:33:79332)
    at c (/Users/nauxscript/.vscode/extensions/vue.volar-1.1.6-darwin-x64/dist/node/client.js:37:56075)
    at i.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:32441)
```

and I found I lost all the snippet or suggestion from voloar.

volar version: 1.1.6
vscode version: 1.75.1
OS: MacOS M1 pro, Ventura 13.1

**Comment by johnsoncodehk** [comment]
Thanks for the report, can you provide the code that lead to throw this error?

**Comment by Nauxscript** [comment]
actually i didn't do anything; I opened VSCode as usual and there a notification reminding me to relaunch VSCode to upgrade volar, and I did that, and  the error showed after relaunching.

**Comment by johnsoncodehk** [comment]
Can you provide the code for the file that VSCode is currently opening when the crash occurs?

**Comment by AmelloAster** [comment]
I'm having the same problem, opening any vue file will report an error

**Comment by johnsoncodehk** [comment]
@AmelloAster Please provide the vue code that reporting error as I cannot reproduce.

**Comment by sccpt** [comment]
The same problem occurs

**Comment by Nauxscript** [comment]
> Can you provide the code for the file that VSCode is currently opening when the crash occurs?

I am sorry I couldn't provide the file 😂, but I will try to build a minimal reproduction later; 
but I found that when the error occur, there were some problems in the code files, like eslint warning or error :
```
[{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-unused-vars",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-unused-vars.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-unused-vars.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "'throttle' is defined but never used.",
	"source": "eslint",
	"startLineNumber": 12,
	"startColumn": 10,
	"endLineNumber": 12,
	"endColumn": 18
},{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-unused-vars",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-unused-vars.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-unused-vars.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "'values' is defined but never used.",
	"source": "eslint",
	"startLineNumber": 12,
	"startColumn": 20,
	"endLineNumber": 12,
	"endColumn": 26
},{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-non-null-assertion",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "Forbidden non-null assertion.",
	"source": "eslint",
	"startLineNumber": 655,
	"startColumn": 5,
	"endLineNumber": 655,
	"endColumn": 26
},{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-non-null-assertion",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "Forbidden non-null assertion.",
	"source": "eslint",
	"startLineNumber": 656,
	"startColumn": 5,
	"endLineNumber": 656,
	"endColumn": 26
},{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-non-null-assertion",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "Forbidden non-null assertion.",
	"source": "eslint",
	"startLineNumber": 657,
	"startColumn": 5,
	"endLineNumber": 657,
	"endColumn": 26
},{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-non-null-assertion",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "Forbidden non-null assertion.",
	"source": "eslint",
	"startLineNumber": 1087,
	"startColumn": 8,
	"endLineNumber": 1087,
	"endColumn": 29
},{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-non-null-assertion",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "Forbidden non-null assertion.",
	"source": "eslint",
	"startLineNumber": 1286,
	"startColumn": 21,
	"endLineNumber": 1286,
	"endColumn": 42
},{
	"resource": "...",
	"owner": "eslint",
	"code": {
		"value": "@typescript-eslint/no-non-null-assertion",
		"target": {
			"$mid": 1,
			"external": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"path": "/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-non-null-assertion.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "Forbidden non-null assertion.",
	"source": "eslint",
	"startLineNumber": 1294,
	"startColumn": 21,
	"endLineNumber": 1294,
	"endColumn": 42
}]
```

**Comment by Nauxscript** [comment]
I reinstall volar 1.1.5, and the same eslint problems are also output in the preblems pannel, but volar had not crashed

**Comment by AmelloAster** [comment]
I think I may have found the problem, I noticed that when I opened another vue project	
JavaScript and TypeScript Nightly plugin was reporting an error, so after I disabled the plugin, everything seemed to work fine

**Comment by Nauxscript** [comment]
> I think I may have found the problem, I noticed that when I opened another vue project JavaScript and TypeScript Nightly plugin was reporting an error, so after I disabled the plugin, everything seemed to work fine

I dont have this plugin, but it looks like volar will crash if your code have some problems like  ts error, syntax error, or even just warning.

**Comment by johnsoncodehk** [comment]
@AmelloAster This is another problem, please track #2434 and provide minimal reproduction if possible.

**Comment by wufan999888** [comment]
The same problem occurs

**Comment by 3biubiu** [comment]
The same problem occurs

**Comment by ApeWhoLovesCode** [comment]
The same problem occurred after reloading today.

**Comment by ApeWhoLovesCode** [comment]
v1.1.6  The same problem occurred after reloading today.

**Comment by AmelloAster** [comment]
> > I think I may have found the problem, I noticed that when I opened another vue project JavaScript and TypeScript Nightly plugin was reporting an error, so after I disabled the plugin, everything seemed to work fine
> 
> I dont have this plugin, but it looks like volar will crash if your code have some problems like ts error, syntax error, or even just warning.

I think you are right, I started having this problem again

**Comment by Nauxscript** [comment]
> > > I think I may have found the problem, I noticed that when I opened another vue project JavaScript and TypeScript Nightly plugin was reporting an error, so after I disabled the plugin, everything seemed to work fine
> > 
> > 
> > I dont have this plugin, but it looks like volar will crash if your code have some problems like ts error, syntax error, or even just warning.
> 
> I think you are right, I started having this problem again

In case you didn't already know, v1.1.7 has been released and fixed this problems.

**Comment by AmelloAster** [comment]
> > > > I think I may have found the problem, I noticed that when I opened another vue project JavaScript and TypeScript Nightly plugin was reporting an error, so after I disabled the plugin, everything seemed to work fine
> > > 
> > > 
> > > I dont have this plugin, but it looks like volar will crash if your code have some problems like ts error, syntax error, or even just warning.
> > 
> > 
> > I think you are right, I started having this problem again
> 
> In case you didn't already know, v1.1.7 has been released and fixed this problems.

thank you

**Comment by wilding96** [comment]
I have this problem today, my vue-official version is v2.1.8，now I return to v2.1.6, it is working.

**Comment by KazariEX** [comment]
Please open a new issue with codes that throw the error.

**Comment by faglyramschie7** [comment]
Hey i have the same problem today. Request textDocument/documentSymbol failed.

**Comment by mkchemist** [comment]
> I have this problem today, my vue-official version is v2.1.8，now I return to v2.1.6, it is working.

"This resolves the issue."

**Comment by WangJincheng4869** [comment]
今天更新至 `v2.1.8` 我遇到了同样的问题。

**Comment by daixii83** [comment]
same problem happen when upgrade to v2.1.8

**Comment by adnanhyder** [comment]
same problem happened to me Vue - Official v2.1.8

**Comment by inkkonito** [comment]
same pb now

**Comment by nik-lylo** [comment]
same problem happened to me Vue - Official v2.1.8

**Comment by KazariEX** [comment]
This issue was closed 2 years ago. Please consider opening a [new issue](https://github.com/vuejs/language-tools/issues/new/choose) instead of leaving a comment here.

**Comment by yanbin218** [comment]
Request textDocument/documentSymbol failed.

**Comment by yanbin218** [comment]
> Request textDocument/documentSymbol failed.

Error: selectionRange must be contained in fullRange

**Comment by johnsoncodehk** [comment]
I can't reproduce this issue. Please open a new issue and provide minimal reproduction so we can investigate, thanks.
