### ISSUE TITLE
Hope to enhance, component jump and type detection

### ISSUE THREAD

**Issue by Miboweixin** [vuejs/language-tools#2440]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/44331632/220517737-1a0902d8-2297-49ed-b7cb-44d4dc53b1b4.png">

**Find subcomponent deduced type as "any"**
<img width="518" alt="image" src="https://user-images.githubusercontent.com/44331632/220517951-82c2f577-a145-43ae-9a31-5357dcefb64d.png">
<img width="802" alt="image" src="https://user-images.githubusercontent.com/44331632/220517821-fc44c10d-915f-48a0-9393-f4e787531097.png">

**In component**
<img width="584" alt="image" src="https://user-images.githubusercontent.com/44331632/220518157-30698672-90d1-4747-a1d0-f077117c5106.png">

**Comment by johnsoncodehk** [comment]
Please try `const drawerRef = ref<InstanceType<typeof DrawerDetail>>()`.
