### ISSUE TITLE
props autocomplete on auto imported component not working

### ISSUE THREAD

**Issue by hi-reeve** [vuejs/language-tools#2441]
auto imported components have no auto completion on the props  using the latest version `1.1.7`.
this happen also with nuxt / unplugin-vue-components plugin.
it has no problem just few hours ago.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/45350572/220533672-a580149b-a3a8-42a9-ab81-2e6fcd4fb387.png">

if you need a [repro](https://github.com/hi-reeve/vue-essentials-starter/tree/volar-bug)

**Comment by hi-reeve** [comment]
please fix this, because this is really annoying to not get any autocomplete for the component props @johnsoncodehk

**Comment by hi-reeve** [comment]
additional information, i found a weird way to temporary fix the issue 

adding `import {} from '#components'` is fixing this, so if anyone also got this issue, you can try to do this in development and remove it after finish the development

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem. However, it is likely not Volar's problem. If you still have this issue, please report it to unplugin-vue-components.
