### ISSUE TITLE
无法注册“typescript.tsdk”。此属性已注册

### ISSUE THREAD

**Issue by lianyitj** [vuejs/language-tools#2442]
![FFBDXTOR(EQX @%0FM{CB@4](https://user-images.githubusercontent.com/10227648/220541849-0b429b60-47fa-41e7-8122-2526bea477a4.png)

why？

**Comment by ntnyq** [comment]
VS Code 的内置配置项。

**Comment by lianyitj** [comment]
> 

没有什么影响吧？

**Comment by lianyitj** [comment]
> VS Code 的内置配置项。
> 
> https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions

没有什么影响吧？

**Comment by wluobing** [comment]
#2322 Similar question~ awaiting resolution.

**Comment by wluobing** [comment]
如果你也使用了neovim或者其他的类似插件，可以考虑排查是否全局安装了volar的npm包

[参考方案](https://github.com/vuejs/language-tools/issues/2322#issuecomment-1463406463)

**Comment by so1ve** [comment]
It is just a warning and doesn't matter
