### ISSUE TITLE
inlay hints display wrong suggestions - toString! toLocaleString!

### ISSUE THREAD

**Issue by beljand** [vuejs/language-tools#2443]
I've noticed that inlay hint is displayed but the prop(s) does not exist on the component.

**toString!**
**toLocaleString!**

<img width="442" alt="image" src="https://user-images.githubusercontent.com/697031/220567729-3b99aae9-ab50-4fb0-8f30-f89d70a8972f.png">

[minimal repro repo](https://github.com/beljand/volar-inlay-hints-repro)

**Comment by johnsoncodehk** [comment]
I can't reproduce with the component code, can you provide minimal reproduction?

**Comment by beljand** [comment]
> I can't reproduce with the component code, can you provide minimal reproduction?

Will try

**Comment by beljand** [comment]
@johnsoncodehk managed to reproduce it on a brand new Vue `2.x` project, but not on `3.x` https://github.com/beljand/volar-inlay-hints-repro

<img width="1429" alt="Screenshot 2023-02-22 at 12 40 38" src="https://user-images.githubusercontent.com/697031/220610176-a5d79e6f-9e9c-47ab-837c-cbd2eaad9ea6.png">

**Comment by johnsoncodehk** [comment]
Thanks for the repro case!

**Comment by mythz** [comment]
I have a similar but worse problem where it lists all string members and goes completely off the screen:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/89361/221394865-85b20127-3b48-4f71-87f0-c2bccab48076.png">

Seems to be an issue with the `<label>` and `<select>` elements as when I replace it with `<span>` and `<textarea>` the problem goes away:

```html
<div class="sm:hidden">
    <span :for="id" class="sr-only">Select a tab</span>
    <textarea :id="id" :name="id" class="block w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500" @change="select(($event.target as HTMLSelectElement)?.value)">
        <option :key="tab" v-for="tab in tabNames" :value="tab">{{ label(tab) }}</option>
    </textarea>
</div>
```

> disabling the extension also fixes it

Strange thing is that the library uses `<label>` in several other places already but it's only happening with the new [Tabs.vue](https://github.com/ServiceStack/servicestack-vue/blob/main/src/components/Tabs.vue) component

Repro:

1. Clone https://github.com/ServiceStack/servicestack-vue
2. Open [Tabs.vue](https://github.com/ServiceStack/servicestack-vue/blob/main/src/components/Tabs.vue) in VS Code

**Comment by beljand** [comment]
@johnsoncodehk `v1.2.0` does not solve the problem for me :/
