### ISSUE TITLE
TS errors thrown since vue version 3.2.46

### ISSUE THREAD

**Issue by shoppingQueen** [vuejs/language-tools#2449]
When using the latest vue-tsc release with vue in version 3.2.46 or 3.2.47 typescript errors are thrown.

It seems to concern for example methods in templates:
```
component.vue 8:21 - error TS2349: This expression is not callable.
  Type 'never' has no call signatures.

8         @touchmove="drag($event)"

```

**Comment by johnsoncodehk** [comment]
Thanks for the report, but please provide a minimal reproduction, so that I can check it.
