### ISSUE TITLE
TS Global with Global Components are not working for me

### ISSUE THREAD

**Issue by louiss0** [vuejs/language-tools#2451]
I have not been able to get good types from volar lately. I have taken a project from Stackblits and created one with `create-vue` . I have not been able to get Typescript to work with volar. I don't know what the problem is but This is what I'm dealing with.

![image](https://user-images.githubusercontent.com/29028601/221284365-c1d9e000-273e-4cac-ae01-16cf25398e28.png)
  
I don't know who else to go to about this information.

This is the repo I have been working with https://github.com/louiss0/vuestic-vue-test-repo 

**What you need to know**

- I'm using pnpm without using `--shamefully-hoist`
- I'm using the latest version of Vue
- I got this project from Stackblitz

**Comment by xiaoxiangmoe** [comment]
Add `import { VaButton } from 'vuestic-ui'` to use local component registry in `App.vue`.

Or add file `global-component.d.ts` to declare global component

```ts
import type { VaButton } from "vuestic-ui";
declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    VaButton: typeof VaButton;
  }
}

export {};
```
