### ISSUE TITLE
[Bug?] Two issues when using directives

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2454]
[Source Code](https://github.com/wenfangdu/vite-vue-3/tree/el-plus-volar)

![image](https://user-images.githubusercontent.com/28700378/226234567-dd0923fd-4d28-453e-bcc9-27faacf6be98.png)

<img width="594" alt="image" src="https://user-images.githubusercontent.com/28700378/221357482-c46cb671-f6de-4f2e-904f-d6ed0dd172ee.png">

**Comment by johnsoncodehk** [comment]
It seems normal to me, most likely it is caused by other extensions, try disabling possibly related syntax highlighting extensions.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/16279759/226222911-48903766-1830-4375-b000-77c285da0fe0.png">

**Comment by wenfangdu** [comment]
@johnsoncodehk Sorry, the first issue is no completion suggestion for `v-loading`, not no intellisense:
![image](https://user-images.githubusercontent.com/28700378/226234216-2db68c21-5c28-4f68-9e72-d067fd7ecf11.png)
The second issue seems to be caused by the Dracula theme extension, I'll file an issue there. Please reopen this issue.

**Comment by wenfangdu** [comment]
@johnsoncodehk Sorry, the first issue is no completion suggestion for `v-loading`, not no intellisense:

![image](https://user-images.githubusercontent.com/28700378/226234216-2db68c21-5c28-4f68-9e72-d067fd7ecf11.png)

I've updated the description in the question and in the source code.

For the second issue, I've also tried other themes (builtin and extensions), and they all have the same behavior:

![image](https://user-images.githubusercontent.com/28700378/226235181-a109a702-7c35-410e-8a13-383ebe2eecb5.png)
![image](https://user-images.githubusercontent.com/28700378/226235317-ad24d9f4-b74d-46e9-ad28-9009216eb201.png)
![image](https://user-images.githubusercontent.com/28700378/226235361-0a75c24f-2763-41fd-a706-7cacf88f5647.png)

So I don't think it's caused by a specific theme extension, is there any chance that Volar involves in this?

Please reopen this issue.

**Comment by johnsoncodehk** [comment]
Please try the syntax highlight problem with `Extensions: Disable All Installed Extensions` command, and only enable Volar.

**Comment by wenfangdu** [comment]
@johnsoncodehk Yes, still reproducible using the built-in themes:

![image](https://user-images.githubusercontent.com/28700378/228748781-c1672526-94c9-42fe-b8fe-a7a8219af237.png)

**Comment by johnsoncodehk** [comment]
I can confirm it with "Monokai" theme, thanks.
