### ISSUE TITLE
any action will call update, make the worker always busy

### ISSUE THREAD

**Issue by chenzhiwei199** [vuejs/language-tools#2456]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@volar/language-core@1.0.24` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@volar/language-core/out/languageContext.js b/node_modules/@volar/language-core/out/languageContext.js
index c647606..4c8f01d 100644
--- a/node_modules/@volar/language-core/out/languageContext.js
+++ b/node_modules/@volar/language-core/out/languageContext.js
@@ -98,7 +98,7 @@ function createLanguageContext(host, languageModules) {
         typescript: {
             languageServiceHost: new Proxy(_tsHost, {
                 get: (target, property) => {
-                    update();
+                    // update();
                     return target[property] || host[property];
                 },
             }),
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by johnsoncodehk** [comment]
Could you share more context? We have check project version in update function, so it should not cause frequent calculations.

https://github.com/volarjs/volar.js/blob/7582403cc521d33f642183a32da44fb1f64e65ef/packages/language-core/src/languageContext.ts#L134-L140

**Comment by chenzhiwei199** [comment]
I use monaco-volar,   working with multiple files, when i  add 1000+ d.ts file,  every thing is not working , such as go-to-define, always in loading

**Comment by johnsoncodehk** [comment]
Have you updated monaco-volar to v0.1.0? I made related performance improvements.

**Comment by chenzhiwei199** [comment]
ok, I try to upgrade to version v0.1.0 to see if the problem can be solved.

**Comment by chenzhiwei199** [comment]
when i upgrade to version v0.1.0, the problem is solved, thanks
