### ISSUE TITLE
[Bug?] export type weird behaviors

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2457]
1. Ts throws "Modifiers cannot appear here", while the code runs successfully.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/28700378/221403901-014c8739-b6cd-4190-a544-113c37677ce7.png">

2. Syntax highlighting is broken.
<img width="875" alt="image" src="https://user-images.githubusercontent.com/28700378/221403964-9f136c1a-10e5-4785-93c3-3fc1c5f8b653.png">

[Repro Link](https://github.com/wenfangdu/vite-vue-3/tree/export-bug)

**Comment by johnsoncodehk** [comment]
Please try to move exports to script block.

```html
<script lang="ts">
export type b = boolean;
</script>

<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
import HelloWorld from './components/HelloWorld.vue'
console.log(1);
</script>
```

**Comment by wenfangdu** [comment]
@johnsoncodehk Why? Is this usage documented anywhere? `export` works fine in `<script setup>`, the only issue is TS complaining.

**Comment by wenfangdu** [comment]
@johnsoncodehk I suggest adding a better error message for this, like "Named exports can't be used in `<script setup>`.", currently it's "Modifiers cannot appear here." which is very general and gives the user the impression that it's not a vue related error.

**Comment by wenfangdu** [comment]
> Please try to move exports to script block.
> 
> ```
> <script lang="ts">
> export type b = boolean;
> </script>
> 
> <script setup lang="ts">
> import { RouterLink, RouterView } from 'vue-router'
> import HelloWorld from './components/HelloWorld.vue'
> console.log(1);
> </script>
> ```

@johnsoncodehk And @sxzz [suggest I not do that](https://github.com/sxzz/unplugin-vue-macros/issues/298#issuecomment-1459596650) 😵😵😵.

**Comment by sxzz** [comment]
[Relate comment](https://github.com/sxzz/unplugin-vue-macros/issues/298#issuecomment-1476669991)

For your case, you can try
```
<script setup lang="ts">
export type b = boolean // move export statement to the first line.

console.log(1)
</script>
```

**Comment by wenfangdu** [comment]
@sxzz The issue I'm facing is more like this:

```vue
<script setup lang="ts">
  type A = string

  export type B = boolean | A
</script>
```

Type `A` shouldn't be exported, and TS complains:

![image](https://user-images.githubusercontent.com/28700378/226506093-5b4835aa-a493-46be-89aa-7dda9be90902.png)

Is there any way around this?

**Comment by sxzz** [comment]
@wenfangdu 
1. Export both of them, A and B.
2. Or, extract them into a normal TS file.

---

TBD I personally don't suggest developers use `export` in the Vue SFC file. Because it will cause unexpected behaviors. I will choose Option 2.

**Comment by wenfangdu** [comment]
@sxzz 
1. Why do both `A` and `B` have to be exported?
2. ["Currently complex types and type imports from other files are not supported"](https://vuejs.org/api/sfc-script-setup.html#typescript-only-features), so [`betterDefine`](https://vue-macros.sxzz.moe/features/better-define.html) is required for option 2?

**Comment by sxzz** [comment]
@wenfangdu 
1. This is just a workaround - you have to export both of them and then Volar will work normally.
2. `betterDefine` is designed for resolving the problem (["Currently complex types and type imports from other files are not supported"](https://vuejs.org/api/sfc-script-setup.html#typescript-only-features)). BUT betterDefine cannot resolve the normal script now (maybe will improve in the future). So it's just a workaround that makes you solve the problem temporarily.

**Comment by johnsoncodehk** [comment]
See https://github.com/vuejs/language-tools/discussions/2421

**Comment by wenfangdu** [comment]
@sxzz Thanks for the clarification.

> BUT betterDefine cannot resolve the normal script now (maybe will improve in the future).

By "normal script", do you mean the `<script>`s inside SFC?

**Comment by sxzz** [comment]
@wenfangdu Yes, there are two kinds of script block - normal script block and `<script setup>` block.
