### ISSUE TITLE
Volar auto import not working with kebab-case

### ISSUE THREAD

**Issue by Wissiak** [vuejs/language-tools#2458]
Volar seems to only detect auto import components when using PascalCase:
![image](https://user-images.githubusercontent.com/31206249/221407304-f5543b2c-db64-470f-b1f1-32cba6ca4487.png)

As per the docs I recently disabled Vetur and since then the auto import components are not correctly shown if I use kebab-case. Here, no suggestion comes up:
![image](https://user-images.githubusercontent.com/31206249/221407384-f7c4deae-56ea-4d3a-a78e-b3b7fc4624f1.png)

I've already tried the following settings but they did not fix the bahavior:
![image](https://user-images.githubusercontent.com/31206249/221407438-c009affe-2cbe-4111-bf7e-3dad0aee579d.png)

Did I miss some setting or is there a bug?

**Comment by Chriztiaan** [comment]
I am also having trouble with this.

**Comment by WangJincheng4869** [comment]
这个bug何时修复发版？目前这个bug严重影响开发效率

**Comment by KiddoV** [comment]
I am still having the problem. I am on Volar v1.8.25

**Comment by TurningTide** [comment]
Same with v2.1.10

**Comment by BrevAlessioMk** [comment]
Same with 2.2.4

**Comment by crschmidt2** [comment]
Using neovim, I was able to get kebab-casing working on completions by using the workspace/didChangeConfiguration option: 
```lua
vue.complete.casing.tags = "kebab"
```

For neovim users, configuring this with lspconfig looks like the following:
```lua
require('lspconfig').volar.setup {
    settings = {
        vue = {
            complete = {
                casing = {
                    tags = "autoKebab"
                }
            }
        }
    }
}
```
