### ISSUE TITLE
v1.2.0 breaks extension

### ISSUE THREAD

**Issue by lizardfish0** [vuejs/language-tools#2459]
Upgrading to `v1.2.0` breaks the extension on my system. Downgrading to `v1.1.7` resolves this problem.

Running via WSL Ubuntu 20.04 on Windows 11.

ex:
![image](https://user-images.githubusercontent.com/97480684/221436749-bf9661d7-c190-443f-a141-79619f57a7aa.png)

switching to `v1.2.0`:
![image](https://user-images.githubusercontent.com/97480684/221436790-739ac4b3-8d04-4d80-8a5e-afa2b032b7cc.png)

**Comment by johnsoncodehk** [comment]
Even the syntax highlighting shown in the screenshot of v1.1.7 is not correct, you probably installed other extensions that will cause related effects, please try to check and disable other extensions that may be related.
