### ISSUE TITLE
<svg /> syntax highlting in entire file

### ISSUE THREAD

**Issue by Soya-xy** [vuejs/language-tools#2461]
(Volar) v1.2.0

```vue
<template>
  <div class="w-full h-full">
    <svg />    
    <div>
      123456
    </div>
  </div>
</template>
```

Using `<svg />` in `vue`, `HTML` causes syntax highlighting exceptions throughout the file

Same problem as #1049 

![image](https://user-images.githubusercontent.com/56671014/221473152-91449135-956c-4e51-8793-d29b990960ca.png)
![image](https://user-images.githubusercontent.com/56671014/221473191-1fe76753-f58d-450d-b41b-3c8d7352d861.png)

but use `<svg></svg>` is good

![image](https://user-images.githubusercontent.com/56671014/221473237-fcacf13a-752e-495f-afa6-140f13559441.png)

**Comment by johnsoncodehk** [comment]
`<svg />` is invalid syntax in html, it can reproduce in html document.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/16279759/227736778-dca1a27a-7fb1-4b33-8c33-d710d0334635.png">

**Comment by Glandos** [comment]
OK, but eslint autofix (or autoformat?) makes it auto-closed, so it is a forever loop here, because I have format on save. I have to work around this with `<!-- eslint-disable-next-line vue/html-self-closing -->`

**Comment by Glandos** [comment]
By the way, this is a valid syntax:
![image](https://user-images.githubusercontent.com/297578/232724131-a006fccf-3150-4864-85fc-c8bd21215dc1.png)

Maybe the upstream label says that it's a bug from another extension?
