### ISSUE TITLE
tsconfig.json extends doesn't support jumto definition when using package format

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#2467]
more details ref: https://github.com/microsoft/vscode/issues/171365

https://user-images.githubusercontent.com/41773861/221742874-af506903-f619-45a3-8df7-53ff35a5f4d4.mov

Versions:

```
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
Volar: 1.2.0
Volar Typescript Plugin: 1.2.0
Takeover Mode: yes
```

**Comment by tjx666** [comment]
@johnsoncodehk 老哥。这个跳转还挺常用的，不优先修一下吗？

**Comment by johnsoncodehk** [comment]
Reference for implement: https://github.com/microsoft/vscode/blob/9e1375620e93b2903bf9b4ed41399f1c063141bb/extensions/typescript-language-features/src/languageFeatures/tsconfig.ts#L28-L42

**Comment by tjx666** [comment]
@johnsoncodehk vscode-typescript 的能力 volar 自己都要实现一遍吗？如果我要实现这个，代码写在哪？
