### ISSUE TITLE
[Bug] prop being passed but volar throws that it wasn't

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2468]
![image](https://user-images.githubusercontent.com/28700378/221744956-80106648-8b43-4edd-9439-a8aacc6f77f1.png)
![image](https://user-images.githubusercontent.com/28700378/221745230-de45e175-b5f6-4e0d-b11e-2d5edb5d87f1.png)
<img width="392" alt="image" src="https://user-images.githubusercontent.com/28700378/221745055-7d33dc7f-f40b-4380-a11b-d866912bb308.png">

[Repro Link](https://github.com/wenfangdu/vite-vue-3/tree/prop!)

**Comment by wenfangdu** [comment]
@johnsoncodehk Still reproducible in Volar v1.3.4:

![image](https://user-images.githubusercontent.com/28700378/227140544-16ba62d1-d5e7-45b1-a7c2-6792baf38576.png)

What's worse is that the inline prop-missing hint is gone, before:

![image](https://user-images.githubusercontent.com/28700378/227140722-5e62da2c-9aae-4b6c-a996-ca2b592a098f.png)

Now:

![image](https://user-images.githubusercontent.com/28700378/227140768-084f8e16-2207-4319-aa2f-3eac69468f87.png)

Please reopen this.

**Comment by wenfangdu** [comment]
@johnsoncodehk Still reproducible in Volar v1.3.4:

![image](https://user-images.githubusercontent.com/28700378/227140544-16ba62d1-d5e7-45b1-a7c2-6792baf38576.png)

What's worse is that the inline prop-missing hint is gone, before:

![image](https://user-images.githubusercontent.com/28700378/227140722-5e62da2c-9aae-4b6c-a996-ca2b592a098f.png)

Now:

![image](https://user-images.githubusercontent.com/28700378/227140768-084f8e16-2207-4319-aa2f-3eac69468f87.png)

Please reopen this.

**Comment by johnsoncodehk** [comment]
This is by design, please try:

```diff
defineProps<{
	msg: string
-	onEvent(): void
+	onEvent?(): void
}>()
```

**Comment by wenfangdu** [comment]
@johnsoncodehk But `onEvent` is indeed passed:
![image](https://user-images.githubusercontent.com/28700378/232197021-6a63257a-fb9b-47a4-b3e2-accea4a036a2.png)

> This is by design

_**So there's no way to make onEventListeners required?**_
Also, by whose design, Vue's or Volar's?

**Comment by wenfangdu** [comment]
@johnsoncodehk But `onEvent` is indeed passed:
![image](https://user-images.githubusercontent.com/28700378/232197021-6a63257a-fb9b-47a4-b3e2-accea4a036a2.png)

> This is by design

_**So there's no way to make onEventListeners required?**_
Also, by Vue's design or by Volar's? If it's by Volar's design and not by Vue's, then it's still a bug.

**Comment by wenfangdu** [comment]
@johnsoncodehk Vue clearly allows making onEventListeners required:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/28700378/232971953-5ca76f00-cd74-47f2-bb23-029e6513d63e.png">
Please reopen this issue 🙏.

**Comment by wenfangdu** [comment]
@johnsoncodehk Thanks, passing `onEvent` satisfies Volar now:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/28700378/236602667-4c113b81-c795-4c63-adb6-a22fc055b025.png">
However, the inline error hint for missing `msg` like the below one is gone, can we add it back?
![image](https://user-images.githubusercontent.com/28700378/236602789-69cd77ef-765f-4f7a-ab35-a394345c61d0.png)
