### ISSUE TITLE
[Bug] Duplicate suggestions

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2469]
![image](https://user-images.githubusercontent.com/28700378/221766854-909bc45c-fbc2-4eaf-8b86-ec221df56375.png)

[Repro Link](https://github.com/wenfangdu/vite-vue-3/tree/dup-suggestions)

**Comment by johnsoncodehk** [comment]
This is a TS issue, it can reproduce in .ts, please forward it to TypeScript repo.
