### ISSUE TITLE
Syntax highlighting error with specific character sequence

### ISSUE THREAD

**Issue by jaredmcateer** [vuejs/language-tools#2473]
We have a directive called `v-ar-tooltip` and in vscode the resulting syntax highlight is wrong

![image](https://user-images.githubusercontent.com/781540/221911729-f58bd317-e2ac-4073-ad6a-073ce79f2853.png)

It seems any other sequence (eg., `v-ar-toolti`, `v-ar-tooltips`, `v-my-tooltip` `v-ar-foobar`, etc) renders correctly. 

Here's how inspector is parsing the first part of the attribute
![image](https://user-images.githubusercontent.com/781540/221912794-1f06efa6-c957-41b4-8a37-b534dabee6d2.png)

vs the second part
![image](https://user-images.githubusercontent.com/781540/221912898-198d71a8-7da7-44ca-aa81-c3b1f0b60dba.png)

This only happens inside the SFC, if I write it in a html file I get a similar result as the latter example

![image](https://user-images.githubusercontent.com/781540/221913780-81284acf-e3b0-41ad-b93a-39fc58e80f0f.png)

**Comment by johnsoncodehk** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/16279759/228427970-1c8632aa-af9e-4fcb-8546-89728bbdf54e.png">

I can't reproduce this problem, did you have installed other syntax highlight extensions?

**Comment by jaredmcateer** [comment]
I tried disabling all extensions except Vue Language Features and I can still reproduce but I have found more criteria

1. It's only visible on certain themes, for example Kimbie Dark, Monokai, Solarized Dark, Red
2. You need to import the directive in the script section

[Screencast from 2023-03-30 09:55:55 AM.webm](https://user-images.githubusercontent.com/781540/228894701-eed19db7-c47f-4dff-b1d7-988c72bfb9c1.webm)

**Comment by jaredmcateer** [comment]
Oh another thing it doesn't matter what characters come after `v-ar` if you change the import name to match the attribute

`import vArFoo from '...';`

will reproduce the visual glitch when you use `v-ar-foo="..."`

**Comment by johnsoncodehk** [comment]
Thanks for the information, it is the same problem with #2454.
