### ISSUE TITLE
"volar.inlayHints.eventArgumentInInlineHandlers" height style

### ISSUE THREAD

**Issue by kedniko** [vuejs/language-tools#2474]
`$event =>`  is hiding the underlining of the line above _(those green dots are generated by UnoCSS)_.

![image](https://user-images.githubusercontent.com/42846752/221949582-9df1904e-4d6f-462e-a25b-23b37cb165e9.png)

**Comment by Sight-wcg** [comment]
```json
"workbench.colorCustomizations": {
    "editorInlayHint.parameterBackground": "#00000000",
},
```
You can add it to `settings.json` to bring back the original transparent background for InlayHint parameter .
