### ISSUE TITLE
About the Vscode configuration problem after the takeover is turned on

### ISSUE THREAD

**Issue by bigsnowballhehe** [vuejs/language-tools#2490]
After the takeover mode is turned on, the typescript configuration item that comes with VsCode is not exposed? How can I know what I can configure? Or can I recognize that this item is configurable?
The configuration has taken effect, but the display shows that there is no such configuration.
![image](https://user-images.githubusercontent.com/36768323/223015875-64d97a59-901a-4cdc-a73e-a6f19e4f0a39.png)

**Comment by johnsoncodehk** [comment]
This is a known limitation, you must enable the built-in TS extension to be aware of it for now.
