### ISSUE TITLE
Smart Select is not working inside template

### ISSUE THREAD

**Issue by shoaibsharif** [vuejs/language-tools#2493]
VSCode smart select doesn't work on template blocks, but it works on script blocks.

![CleanShot 2023-03-06 at 15 20 28](https://user-images.githubusercontent.com/29075110/223235271-21b78ea4-da42-416e-8d03-6f40cb81c65a.gif)

**Comment by kikyous** [comment]
related #2477

**Comment by johnsoncodehk** [comment]
Duplicate of #2477
