### ISSUE TITLE
Idea: CSS syntax highlighting inside vue's <component :is="'style'"></component>

### ISSUE THREAD

**Issue by olemarius** [vuejs/language-tools#2499]
The use case for <component :is="'style'"> is to control css variables from vue and apply them to selectors outside the vue application. This is especially useful when migrating a large app/website to vue as a progressive enhancement. 

```vue
  <component
      :is="'test'"
      lang="text/css">
      .selector {
      
        /* Support template */
        {{ true ? '--my-css-var: 123' + ';' : null }}
        
        /* Support template */
        <template v-if="true">
          --my-css-var: {{ 123 }};
        </template>
      }
      .other-selector {
        font-size: 12px; 
        background-image: url('test/image.jpg');
      }
  </component>
  ```

Actual case:
![image](https://user-images.githubusercontent.com/184536/223968236-bd942181-dbbc-4ff3-80d9-ac56bbbcfb0b.png)

After save:
![image](https://user-images.githubusercontent.com/184536/223968292-662e0b50-ebb0-49e8-adb2-7e3f4551ae96.png)

Expected:
Similar formatting/colors as in SFC's <style>
![image](https://user-images.githubusercontent.com/184536/223968768-40c188a7-d498-4687-9703-1fc007f4d023.png)

Note: The following Eslint rule allows indentation it seems, but I'm not an expert on the AST syntax and haven't tested extensively that it doesnt cause any other issues. 

```
'vue/html-indent': ['error', 4, {
    'attribute': 1,
    'baseIndent': 1,
    'closeBracket': 0,
    'alignAttributesVertically': true,
    'ignores': [
        'VElement[name="component"] > VText',
        'VElement[name="component"] > VExpressionContainer'
    ]
}],
```

**Comment by johnsoncodehk** [comment]
Thank you for your suggestion, but this use case is specific to the project, so we will not support it.

On the other hand, the component block content is not a true CSS code format because it also includes template tags and template interpolation.
