### ISSUE TITLE
[@volar-plugins/typescript] sourceFile not found 

### ISSUE THREAD

**Issue by henrychea** [vuejs/language-tools#2500]
This error `[@volar-plugins/typescript] sourceFile not found ....vue.js` keeps appearing server output in VueJS 2.6.x app whether takeover mode is enabled or disabled.

This is my jsconfig.json

```json
{
  "compilerOptions": {
    "strict": true,
    "module": "es2015",
    "target": "es2015",
    "moduleResolution": "node",
    "baseUrl": "wwwroot/js/",
    "allowJs": true
  },
  "vueCompilerOptions": {
    "target": 2,
    "extensions": [
      ".vue"
    ],
    "experimentalDisableTemplateSupport": true
  }
}
```

And volar config

```javascript
const vetur = require('@volar-plugins/vetur')
const prettyhtml = require('@volar-plugins/prettyhtml');
module.exports = {
  plugins: [
    vetur(),
		prettyhtml({ printWidth: 80, wrapAttributes: true, sortAttributes: true, singleQuote: false }),
  ]
}
```

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If not please provide minimal reproduction so that I can check it.

**Comment by henrychea** [comment]
Sorry for the delay, here you go: https://github.com/henrychea/volar-vuejs2-ts-check-issue-repoduce

It seems to only happen when you create a new .vue file, and after you save close and reopen the file it no longer produces that error.

![image](https://user-images.githubusercontent.com/40254517/229332679-1f98166b-325c-46c8-8ed8-dca41fea1ee2.png)
