### ISSUE TITLE
Volar imports component as MyComponentVue instead of MyComponent

### ISSUE THREAD

**Issue by tastytea-github** [vuejs/language-tools#2511]
Requirements:
- VS Code
- Volar plugin
- Vue 3 app

Reproduction steps:
1. Create a new component, in my case I create MyIcon.vue with the content: `<template>[any svg code here]</template>`
2. In any another component start typing "MyIc.." to add MyIcon.vue component inside template.

Actual state:
Autocomplete suggests to import MyIconVue instead of MyIcon. If you accept the suggestion, then import will look like `import type MyIconVue from [path here]`.

Expected state:
Autocomplete suggests to import MyIcon and import looks like `import MyIcon from [path here]`.

There is a screenshot of the issue: https://imgur.com/a/fu5jYOV

**Comment by DanielViberg** [comment]
I observe a similar issue, maybe related to this.
I'm using vim and https://github.com/mattn/vim-lsp-settings. The issue is that when accepting the Component it is not added to the import section.
