### ISSUE TITLE
文件路径导入，代码提示和 Path Autocomplete 重复提示

### ISSUE THREAD

**Issue by wzc-ST** [vuejs/language-tools#2513]
使用Vue Language Features (Volar)v1.3.2 后， 
在.vue文件的 html src导入，或者在import导入，会和插件Path Autocomplete，代码提示重复的内容
<img width="939" alt="image" src="https://user-images.githubusercontent.com/51228283/225483257-e4a30d68-131d-4583-974c-f238cf01d524.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/51228283/225483312-92c3fb01-99ef-4952-a1bf-18069fb48633.png">

**Comment by F-OlO-Y** [comment]
the same problem, Currently, it can only be temporarily resolved by configuring the path autocomplete

**Comment by wzc-ST** [comment]
> the same problem, Currently, it can only be temporarily resolved by configuring the path autocomplete

如何配置呢？

**Comment by tanpengsccd** [comment]
你们这样的写的 
```
import someComponent from "@/xxx/xxx.vue";  //路径无法跳转
import {someFunc} from "@/xxx/xxx.ts";  //路径正常跳转
```
ctr/cmd + 左键点击 能跳转 对应定义吗?   
我发现 以 “@ ”开头 并以”.vue“ 的 路径无法 跳转定义.  但是 ts js都能跳转.

**Comment by johnsoncodehk** [comment]
This extension is not designed to be used with Path Autocomplete, so we won't do anything here.
