### ISSUE TITLE
Formatting is pushing code tags

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuejs/language-tools#2520]
Volar v1.2.0
Vue v3.2.47
VSCode v1.76.2 

**Issue**
When saving and/or formatting code, it will keep pushing a `<code>` tag indefinitely. This can and will affect indentation within the code block.

**Example Code:**
This will push the entire `code` block.
```
<template>
  <div>
    <pre>
      <code>
        const foo = 'bar'
      </code>
    </pre>
  </div>
</template>
```
This will push the entire `code` block _after_ the opening `code` tag.
```
<template>
  <div>
    <code>
      const foo = 'bar'
    </code>
  </div>
</template>
```

**Steps to replicate:**
1. Add that code to a `.vue` file.
2. Format the code.
3. Notice the `<code>` tag will keep indenting each time you save/format.

**Setting in VSCode:**
```
  "[vue]": {
    "editor.defaultFormatter": "Vue.volar"
  },
```

**Comment by idlist** [comment]
Have a similar issue with multi-line attribute value here [(discussion#2512)](https://github.com/vuejs/language-tools/discussions/2512), might be the same source.

**Comment by webdevnerdstuff** [comment]
@johnsoncodehk any estimate on when this will be released into the next version? 

Also I'm not sure if this is related or not, but I found another instance it was behaving the same way.

Issue: https://github.com/vuejs/language-tools/issues/2632
