### ISSUE TITLE
Instructions on how to contribute

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#2525]
Contributing instructions say to do:

```
git clone https://github.com/vuejs/language-tools.git
cd language-tools
pnpm install
pnpm run build
```

but since some of the relevant dependencies live in https://github.com/volarjs/volar.js, if one wants to have all present locally, how to set it up? Could you update the instructions and specify how to set it up so that all needed components are local and editable?

**Comment by johnsoncodehk** [comment]
Yes the readme is outdated, now you need to work with https://github.com/volarjs/workspace, appreciate if you can help update the readme.
