### ISSUE TITLE
No capabilities in Sublime Text

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#2526]
When running the top commit (or later) Volar returns no capabilities to Sublime Text, rendering most of the functionality not working

![Screenshot 2023-03-20 at 00 28 59](https://user-images.githubusercontent.com/153197/226216563-130f2538-6860-4b85-8bf9-9f2e08eda99d.png)

The bottom commit works.
Commit in the middle don't compile.

Maybe something has to be updated in the settings but I don't have time to investigate right now so creating this for the record.

Haven't seen any relevant change in the changelog.

**Comment by rchl** [comment]
current master:

```
{
  "capabilities": {
    "textDocumentSync": 2,
    "workspace": {
      "workspaceFolders": {
        "changeNotifications": true,
        "supported": true
      }
    }
  }
}
```

**Comment by johnsoncodehk** [comment]
Thanks for the report, it should be fixed by https://github.com/volarjs/volar.js/commit/2b6911834740dc85774b35ba14d36cc222a02807.
