### ISSUE TITLE
neovim & vue-language-server won't use kebab-case

### ISSUE THREAD

**Issue by callum-mudbath** [vuejs/language-tools#2527]
**Neovim:**
<img width="362" alt="image" src="https://user-images.githubusercontent.com/102267499/226237815-5b6225f7-6f76-4b2c-b816-fae0ce8efd47.png">

**VSCode:**
![image](https://user-images.githubusercontent.com/102267499/226238261-4f801a48-c33e-4015-a841-79830b13378b.png)

```lua

lspconfig.volar.setup({
	filetypes = {
		"vue",
	},
	init_options = {
		completion = {
			preferredTagNameCase = "kebab",
		},
		languageFeatures = {
			completion = {
				defaultTagNameCase = "kebabCase",
				defaultAttrNameCase = "kebabCase",
			},
		},
	},
})
```
I believe this has been raised before [here](https://github.com/vuejs/language-tools/issues/2416), but the response is for VSCode, not the lsp-config/language server settings

**Comment by johnsoncodehk** [comment]
Now it's not a server options, you should provide it by [workspace/configuration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) request.

**Comment by crschmidt2** [comment]
For any future readers of this: the lspconfig.'language'.setup({ settings = { --insert settings here }) passes in a changeConfiguration notification to your language server. You can read more about it with ":help lspconfig". 

I also found out the newest workspace/configuration request for kebab casing is vue.complete.casing.tags = "kebab". Below is a configuration for hybrid typescript + volar (installed through Mason) that got kebab casing working for me:

--Hybrid Typescript + Vue config. See vuejs/language-tools nvim section for explanation
--Typescript handles <script> section, Volar handles Markup + CSS. Typescript vue plugin lets them communicate.

local typescript_ls_path = vim.fn.stdpath("data") ..
    "/mason/bin/typescript-language-server"

local typescript_lib_path = vim.fn.stdpath("data") ..
    "/mason/packages/typescript-language-server/node_modules/typescript/lib"

local volar_ls_path = vim.fn.stdpath("data") ..
    "/mason/bin/vue-language-server"

local ts_vue_plugin_path = vim.fn.stdpath("data") ..
    "/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/typescript-plugin"
```
require('lspconfig').ts_ls.setup {
    init_options = {
        hostInfo = "neovim",
        plugins = {
            {
                name = '@vue/typescript-plugin',
                location = ts_vue_plugin_path,
                languages = { 'vue' },
            },
        },
    },
    filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue', 'rbql' },
    cmd = { typescript_ls_path, "--stdio" }
}


require('lspconfig').volar.setup {
    cmd = { volar_ls_path, "--stdio" },
    init_options = {
        typescript = {
            tsdk = typescript_lib_path
        }
    },
    settings = {
        vue = {
            complete = {
                casing = {
                    tags = "autoKebab"
                }
            }
        }
    }
}
```
