### ISSUE TITLE
[FR] More accurate error message for named exports in `<script setup>`

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2528]
Currently, it's "Modifiers cannot appear here." which is very general and gives the user the impression that it's not a Vue related error, I suggest changing it to something like "Named exports can't be used in `<script setup>`.", which is more accurate.

![image](https://user-images.githubusercontent.com/28700378/226279981-817a1572-177f-465f-a0e8-261099f3a97d.png)

**Comment by johnsoncodehk** [comment]
Fixed by #2582
