### ISSUE TITLE
[vue-component-meta] extract inject/provide informations

### ISSUE THREAD

**Issue by stafyniaksacha** [vuejs/language-tools#2530]
Similarly to events, we could try to infer types and calls for `inject` and `provide` methods

https://github.com/vuejs/language-tools/blob/master/packages/vue-component-meta/src/index.ts#L316

**Comment by johnsoncodehk** [comment]
Can you share some examples of components using provide inject?

**Comment by johnsoncodehk** [comment]
Closed as inactivity.
