### ISSUE TITLE
Volar always puts all properties on one line

### ISSUE THREAD

**Issue by dddhao** [vuejs/language-tools#2531]
When the code is too long to display in one screen, I wrap each property like this
![Screenshot from 2023-03-20 21-03-24](https://user-images.githubusercontent.com/120425976/226347959-4b36a04d-79b6-47ef-a024-afb836efb70d.png)
but volar puts all properties on one line when formatting.
![Screenshot from 2023-03-20 21-03-39](https://user-images.githubusercontent.com/120425976/226348629-2c08e5a2-c83f-4176-a49b-3ef6d386ec87.png)
if I disable volar, it wouldn't happen. How should I configure volar to solve this problem?

**Comment by cabal95** [comment]
@dddhao @jmcooper  Check your VSCode `html.format.wrapAttributes` setting. We have ours set to `preserve-align` and it _maintains_ the current layout but will align if they are on multiple lines.  Meaning, if all the attributes are _already_ defined on one line it leaves them alone. If they are on multiple lines it will leave on multiple lines, but align all the attributes to start at the same column.

Hopefully that setting just needs to be set a specific way for your liking.

![image](https://user-images.githubusercontent.com/1119863/227095457-fe0a2af9-7f51-4d40-870d-357cb1388b9f.png)
