### ISSUE TITLE
vue-tsc very slow since typescript version 4.9

### ISSUE THREAD

**Issue by fardolieri** [vuejs/language-tools#2533]
Good day everyone,

ever since I updated my typescript version from 4.8 to 4.9, my linting times of `vue-tsc` take significantly longer (about 5 times longer). Updating to typescript 5.0 didn't help either. Before it took a little less than 3 minutes but now they take 15 minutes.

I wanted to know if this is a known problem or if anyone else experiences the same issue?

Sadly I cannot share my company's codebase to give a reproducible example, but if there are other ways to track down the underlying issue I'll gladly offer my help.

**Comment by johnsoncodehk** [comment]
This may be a performance regression of TS. Unfortunately, we cannot investigate it without a repro case. It would be helpful if you can try to extract the business code and provide a repro case.

**Comment by Archetipo95** [comment]
Same here, sorry I can't share a reproduction. But it's very slow vscode

**Comment by fardolieri** [comment]
I checked out some larger open source vue projects to see if any of them has this problem but they didn't. 

So my first guess is that maybe my hastily assembled monorepo plays a part in this (but I could also be completely wrong on this one). I have multiple Typescript projects (multiple tsconfig.json) that carelessly cross reference themselves like the following. I didn't check if that could have some runtime implications.

```ts
// project A
import type { B } from '../../../projectB/foo';

// project B
import type { A } from '../../../projectA/bar';
```

I'll try to dig further into it when I have some spare time.

**Comment by mccxiv** [comment]
> but in my case the option `noErrorTruncation: true` in `tsconfig.app.json` slows down the compilation time by a factor of 10

This was it for us!! Thank you. Without that option we're back to reasonable type checking speed
