### ISSUE TITLE
Type issues after enabling takeover mode

### ISSUE THREAD

**Issue by Thooto** [vuejs/language-tools#2534]
Hi,

I am getting type inference issues in typescript files after having enabled takeover mode.

<img width="589" alt="Capture d’écran 2023-03-22 à 10 43 37" src="https://user-images.githubusercontent.com/33691636/226863831-94f1bc36-bdad-4f40-9a84-a02668b808c3.png">
<img width="511" alt="Capture d’écran 2023-03-22 à 10 45 25" src="https://user-images.githubusercontent.com/33691636/226864299-de809072-1487-47ee-a4f8-524f0acb9199.png">

Prior to that, Typescript would correctly hint accArray and outputArray types as `number[]`.

Any idea of what is causing this issue? Also, theses issues don't appear at build time for the project. Please let me know if I should provide you with my tsconfig.json or anything else that could help.

The issue happens with both 1.2.0 and 1.3.4 (prerelease) versions of Volar.
I'm using Typescript 4.6.3 in my project and Vue 2.6.
Seems to also happen when using latest version of Typescript provided by VSCode.
I correctly disabled VSCode builtin Typescript plugin.

Thanks!

**Comment by johnsoncodehk** [comment]
Just for confirm the problem, can you try if config `"vueCompilerOptions": { "strictTemplates": true }` to tsconfig can avoid the problem or not?
