### ISSUE TITLE
I am done with Vue: DX becoming unbearable (Volar: memory problems, crashing extensions, messes up types etc.)

### ISSUE THREAD

**Issue by 0x00A1FA** [vuejs/language-tools#2535]
Ever since I started using Vue I realized there's a lot of trickery and third-party-ness to it, especially when it comes to IDE plugins. Volar is no exception, unfortunately.

I don't even wanna look into Volar's source code, but I'm sure I'd get quite scared.

Keep in mind that I've not changed my other extensions, so the only thing that changes is Volar.

Anyway, there are these a few annoying things that Volar has been doing lately (since 1.3.4) and conversely will make me switch to a TSX JS framework:
- VS Code lists multiple entries for one single variable;
- Extensions and intellisense crash (CSS, Tailwind etc.);
- Some types are three-dot-marked as `any` (one example is anonymous arrow functions);
- Lack of generics for TypeScript components (in 2023 lol).

**Comment by johnsoncodehk** [comment]
If you want to help out, please open a separate issue and provide a repro case for each problem.

Close since this is just complaining and not constructive, you have even pointed out that will switch to a TSX JS framework.
