### ISSUE TITLE
Can't "fold" (collapse) top level nodes with custom file extensions

### ISSUE THREAD

**Issue by cabal95** [vuejs/language-tools#2536]
When using a custom file extension, the `<template>`, `<script>`, and `<style>` nodes cannot be folded down / collapsed. I have tested and it does work with .vue extensions.

The inner content can be collapsed. So functions declared in the `<script>` tag can be folded. Style declaration can be folded, but I can't fold the entire root node.

I'm happy to dig into this more in my spare time, but if you have a suggestion on where to start looking for where that logic happens that would be great.

![image](https://user-images.githubusercontent.com/1119863/226980833-4b5cdb67-98ac-4850-a250-358e2d7e1542.png)

**Comment by johnsoncodehk** [comment]
Fixed from the framework, thanks for the report!
