### ISSUE TITLE
[vue-component-meta] slot `v-bind` without shorthand

### ISSUE THREAD

**Issue by stafyniaksacha** [vuejs/language-tools#2537]
I found that vue component meta does not detect `v-bind` when not used with shorthand

This is result in default slot typed as any:
```vue
<template>
  <slot v-bind="{ foo: 42, bar: 'baz' }" />
</template>
```

Whereas this is well typed:
```vue
<template>
  <slot :foo="42" :bar="'baz'" />
</template>
```

**Comment by johnsoncodehk** [comment]
It looks normal to me, can you add a test case?

<img width="421" alt="image" src="https://user-images.githubusercontent.com/16279759/232262361-eed5b5a2-c715-41e3-a674-2f5a47bbb4cd.png">

**Comment by johnsoncodehk** [comment]
Closed as inactivity.
