### ISSUE TITLE
Types of property 'emits' are incompatible

### ISSUE THREAD

**Issue by Oleksii14** [vuejs/language-tools#2538]
Hi!

I updated the dependencies in my project recently and now I have some issues in my unit tests.
See example in the repo - https://github.com/Oleksii14/volar-vitest

Steps to reproduce:
- clone the repo
- yarn install
- visit the HelloWorld.spec.ts, and see the error under `HelloWorld` that is provided to `shallowMount`.

Unit test code:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/36737084/227010719-e836f399-91c2-485c-bc93-c591f5d72cba.png">

Component code:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/36737084/227010351-3f121c9e-41ec-40a9-8c15-4139e8766caa.png">

Also, when you uncomment `defineEmits([] as string[]);`, it will fix the issue

**Comment by johnsoncodehk** [comment]
Thanks for the repro case, this is `DefineComponent` type and `@vue/test-utils` issue, please track https://github.com/vuejs/test-utils/pull/2026.
