### ISSUE TITLE
Formatting long template lines inconsistent with airbnb ESLint config

### ISSUE THREAD

**Issue by jmcooper** [vuejs/language-tools#2539]
Vue Language Tools seems to have a bug where it formats long lines that are inconsistent with the airbnb ESLint config.  

This causes an issue where if `"editor.formatOnSave": true,` is set in VSCode, it is impossible to proceed with a line that is longer than 100 characters in the html template (for a SFC). If you try to break up the line by moving HTML attributes to a new line, it will get auto-formatted back onto it's own line. Note that this does not occur when the Vue Language Tools extension is not installed or is disabled.

In doing some testing, this seems to only occur when choosing the airbnb config during the `vue create` setup. Other configs including `ESLint with error prevention only` and `ESLint + Standard config` do not seem to suffer from this problem. 

Here are the steps to reproduce (which I did on a completely fresh machine with fresh a VSCode install):

- Install node 14.16.0
- npm install -g @vue/cli
- vue create vue-test
-   * Choose Manually select features
-   * Proceed with only Babel, Linter / Formatter
-   * Select 3.x
-   * Select ESLint + Airbnb config
-   * Select Lint on save
-   * Select In dedicated config files
- Launch VSCode from vue-test directory: `code .`
- Install Extension: `Vue Language Features (Volar) 1.2.0`
- Remove or disable all other extensions
- Open User Settings and add `"editor.formatOnSave": true`
- Remove all other User and Workspace settings
- Open `App.vue`
- Change the `<HelloWorld .../>` line to this:
```
<HelloWorld msg="A long message to make the line more than 100 characters." style="font-size: 12px;" />
```

- Run `npm run serve`
- Notice the error because the `<HelloWorld...` line is too long.
- Break the `<HelloWorld...` line onto multiple lines as follows:
```
<HelloWorld
  msg="A long message to make the line more than 100 characters."
  style="font-size: 12px;"
/>
```
- Save the file
- Notice that the line is changed to all be on a single line. At this point you are unable to fix the issue and you can't run or build the project due to the linting error.

This issue may be a duplicate: https://github.com/vuejs/language-tools/issues/2531

**Comment by johnsoncodehk** [comment]
See https://github.com/vuejs/language-tools/issues/2531#issuecomment-1480553985
