### ISSUE TITLE
[Vue 2.7] types of built-in components are unknown

### ISSUE THREAD

**Issue by kingyue737** [vuejs/language-tools#2540]
![image](https://user-images.githubusercontent.com/40021217/227120066-3658370b-a326-43df-aad7-3a79abf7d67c.png)

Reproduction:
```
pnpm create vue@2
pnpm install
```
Then add a built-in component to no matter which .vue file, you will find volar cannot detect its type.

According to documentation, Vue 2.7 has built-in JSX types and users do not need to install `@vue/runtime-dom` (which export types of built-in components like `<Transition>` and `<Transition Group>`). But I cannot find such type declarations in Vue 2.7. Maybe they are not exported?

**Comment by johnsoncodehk** [comment]
> Maybe they are not exported?

Right, please forward this issue to the vue 2 repo.
