### ISSUE TITLE
Have vscode-vue closely follow vscode.typescript-language-features

### ISSUE THREAD

**Issue by citriqa** [vuejs/language-tools#2542]
There are a few bugs I'm experiencing when trying to use takeover mode, and while I could report them all and effort could be made to fix them, the reality of the matter is that it will always be behind vscode.typescript-language-features in quality and require a bunch of extra effort.
Instead the vscode-vue extension should probably make direct use of the vscode.typescript-language-features source, such that all the functionality responsible for interfacing with VS Code already implemented there is not implemented again by vscode-vue, but instead only the additions and improvements it provides (such as for example using the Vue language server) are.

**Comment by johnsoncodehk** [comment]
This problem is not specific to Volar, [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server) is also rewriting all the code needed.

**Comment by rchl** [comment]
To be fair there exists https://github.com/yioneko/vtsls which uses a different approach that is easier to keep in sync with vscode but I feel that it probably has its pain points too. Maybe one of them is that it needs to shim various things and it doesn't help clarity of the code.

**Comment by johnsoncodehk** [comment]
Maybe it's time to open a PR for VSCode to migrate that code. 😅
