### ISSUE TITLE
vue-tsc emit a bad error for replaceAll with RegExp argument

### ISSUE THREAD

**Issue by romain-aragon** [vuejs/language-tools#2544]
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

src/views/user/components/UserEmailPassword.vue:223:34 - error TS2345: Argument of type 'RegExp' is not assignable to parameter of type 'string'.

223         email = email.replaceAll(/à|á|â|ä|ã|å/g,"a")
                                     ~~~~~~~~~~~~~~

On the same code, Volar is OK 

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

**Comment by johnsoncodehk** [comment]
This is most likely not a problem with Volar, if your version of typescript is too old, try updating it in project.
