### ISSUE TITLE
Inverted `tsconfig.json.references` in Takeover Mode

### ISSUE THREAD

**Issue by sxzz** [vuejs/language-tools#2548]
When Takeover mode is enabled, the order of `tsconfig.json` references is reversed compared to when it is not disabled.

Reproduction: https://github.com/sxzz/volar-tsconfig-order

`src/common.ts`:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/6481596/227801394-1bef5bab-5555-4fda-a9c9-0772700887fd.png">
<img width="184" alt="image" src="https://user-images.githubusercontent.com/6481596/227801414-513a1525-8b1a-4af0-aafd-b82be5ee9299.png">

**Comment by johnsoncodehk** [comment]
You can config `"volar.vueserver.reverseConfigFilePriority": true` in .vscode/settings.json to change this behavior.
