### ISSUE TITLE
1.3.7升级1.3.8后出现了很严重的问题

### ISSUE THREAD

**Issue by YHSanSheng** [vuejs/language-tools#2552]
今天Vue Language Features (Volar)预览版自动更新后（1.3.7升级到1.3.8）出现了很奇怪的现象，每当我尝试保存时，某些组件前会被莫名添加上“async”字符串，并且每保存一次就会多生成一次
![1](https://user-images.githubusercontent.com/112924145/227935599-f5235332-fa89-4c24-872e-ffd1719910b8.jpg)
![3](https://user-images.githubusercontent.com/112924145/227935850-2a217b04-75d8-421a-aa25-5f40e80516b4.jpg)

![2](https://user-images.githubusercontent.com/112924145/227935600-8347bde8-695d-4e8e-be7a-02c9f9dd8bdf.jpg)

本人是一个正在学习前端的新人，所以可能没有能力提供更多的消息。但是通过排查我可以确定的是这些奇怪的现象是因为这次升级导致的，在之前的1.3.7版本不会出现此现象，目前已回退版本为发布版V1.2.0，可以暂时解决此问题。

**Comment by YHSanSheng** [comment]
很奇怪的现象，经过进一步的排查，这种现象似乎只出现在了我正在学习的项目中，我把可以复现问题的.vue文件提取出来，然后单独用vscode打开尝试保存并不会出现这种情况。这是否说明是与工作区的一些配置冲突？（怀疑是与ESLint配置有冲突）

另外，为了再次确认问题发生与本次Volar预发布版本更新存在关系，我找了另外两名同学（练习的项目相同，前期配置应该是一样的），让他们把Volar插件从正式版切换到预发布版本均复现了此问题

之所以怀疑是与ESLint冲突是因为刚重启vscode后右下角有出现它的提示，在此期间进行保存不会复现。但是提示消失后再次进行保存就会在某些标签或者组件前加上async字符串

**Comment by F-OlO-Y** [comment]
I have the same problem

**Comment by amxmln** [comment]
I can confirm this issue with Versions 1.3.7 and 1.3.8 in VS Codium 1.76.2.

Downgrading to 1.3.6 fixes it. If you don't downgrade, you can also use "Save without Formatting" to save the file, however that can be tedious.

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/vuejs/language-tools/commit/f3febe071d18ad747751d087f87eebf44505a47f and released with v1.3.13.
