### ISSUE TITLE
Slot not typed when wrapped an object

### ISSUE THREAD

**Issue by 0x-jerry** [vuejs/language-tools#2553]
Volar v1.2.0
Vue v3.2.47
VSCode v1.76.2

[Reproduce](https://stackblitz.com/edit/vitejs-vite-zsriyy?file=src/App.vue)

`App.vue`

```vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'

const t = {
  HelloWorld
}

</script>

<template>
  <HelloWorld>
    <template #default="{ msg }"></template>
  </HelloWorld>

  <t.HelloWorld>
    <template #default="{ msg }"></template>
  </t.HelloWorld>
</template>
```

`HelloWorld.vue`
```vue
<script setup lang="ts">
</script>

<template>
  <slot msg="some message"></slot>
</template>
```

<img width="486" alt="image" src="https://user-images.githubusercontent.com/14226737/228171419-5c4f53ec-6205-49dd-87cc-595c2fc2e425.png">

**Comment by johnsoncodehk** [comment]
Thanks for the repro case, it's fixed by https://github.com/vuejs/language-tools/commit/f3febe071d18ad747751d087f87eebf44505a47f.
