### ISSUE TITLE
Slot properties using `v-slot` are not recognized in recent versions

### ISSUE THREAD

**Issue by weilbith** [vuejs/language-tools#2554]
Hey folks 👋🏾 

I just tried to update the `vue-tsc` package to something >=1.2.1 to get support for generic components. Unfortunately this comes with a new issue I'm unable to resolve. The following two SFCs demonstrate the problem:

`ParentWithSlot.vue`
```vue
<template>
  <div>
    <slot :foo="1" />
  </div>
</template>
```

`ChildUsingSlot.vue`
```vue
<script lang="ts" setup>
import ParentWithSlot from "./ParentWithSlot.vue"
</script>

<template>
  <ParentWithSlot v-slot="{ foo }">
     The value of foo is: {{ foo }}
  </ParentWithSlot>
</template>
```

This tells me in the usage of `{{ foo }}` that:

```
Property 'foo' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> &      │
│Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10    │
│more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ?  │
│(args_0: R, args_1: R) => ...'. [2339]                                                                             
```

This definitely worked in the past. And according to the [docs](https://vuejs.org/guide/components/slots.html#scoped-slots) that's how it is supposed to work.

Note that is using a template with a scope name works fine:

`ChildUsingSlot.vue`
```vue
<script lang="ts" setup>
import ParentWithSlot from "./ParentWithSlot.vue"
</script>

<template>
  <ParentWithSlot>
    <template #default="{ foo }">
      The value of foo is: {{ foo }}
    </template>
  </ParentWithSlot>
</template>
```

While this fix is okay as trade-off for generic components, I would be happy to resolve that issue. Thank you very much for any help!

EDIT:
Using `volar` as language server at version `1.3.8`, there is no auto-completion nor hover functionality for the slot properties also for using the working `<template #default="{ foo, bar }">` syntax. Though I can see the references for the slot usages. 🤷🏾

**Comment by unitydynamics** [comment]
As noted, I had to rollback to Volar 1.3.4 to avoid seeing these errors.

**Comment by fabis94** [comment]
I encountered the same issue - Volar in VSCode seems fine but running `vue-tsc` for linting returns errors about slot properties not existing. Downgrading vue-tsc to 1.3.4 resolved the issue for me.
