### ISSUE TITLE
Neovim LSP don't update new files and it's changes

### ISSUE THREAD

**Issue by xxSkyy** [vuejs/language-tools#2556]
Since quite long time volar lsp don't update any new file created after initialization of LSP and I need to restart lsp to make them visible. 

My volar lsp config

```lua
local function get_typescript_server_path(root_dir)
  -- Alternative location if installed as root:
  -- local global_ts = '/usr/local/lib/node_modules/typescript/lib'
  local found_ts = ''
  local function check_dir(path)
    found_ts = util.path.join(path, 'node_modules', 'typescript', 'lib')
    if util.path.exists(found_ts) then
      return path
    end
  end

  if util.search_ancestors(root_dir, check_dir) then
    return found_ts
  else
    return global_ts
  end
end

require 'lspconfig'.volar.setup {
  capabilities = neovim.capabilities,
  filetypes = neovim.is_npm_package_installed 'vue' and { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue', 'json' } or { 'vue' },
  root_dir = require 'lspconfig'.util.root_pattern("package.json"),
  documentFeatures = {
    documentFormatting = {
      defaultPrintWidth = 60
    },
  },
  on_new_config = function(new_config, new_root_dir)
    new_config.init_options.typescript.tsdk = get_typescript_server_path(new_root_dir)
  end
}
```
I'm using `Neovim 0.8.3`

I've checked on `MacOS` and `Manjaro` and have same problem, same happens on minimal config and on some other neovim configs that use volar lsp.

Basically it happens for `.vue` and `.ts` files in same way, I've showed on `.ts` in demo as it was easier to show.

Demo: 

https://user-images.githubusercontent.com/16470866/228670545-6a7f7ae8-f0a7-4fc1-9c3e-62980edb0c52.mp4

**EDIT: SOLUTION:**

Vue LSP uses [DidChangeWatchedFiles Notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) that was implemented recently in `Neovim 0.9.0` and need to be manually enabled.

So just update to `0.9.0` and enable this feature it in in your capabilities with code like -   `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true` fixes this problem with lack of LSP new file updates.

**Comment by JoseEscobarBendezu** [comment]
Same issue on my volar lsp configuration.

**Comment by johnsoncodehk** [comment]
Volar language server register file watcher via [DidChangeWatchedFiles Notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles), did Neovim language client supports it?

**Comment by rijenkii** [comment]
I had the same issue.
`:LspLog` contained following:
```
[START][2023-04-24 10:39:20] LSP logging initiated
[WARN][2023-04-24 10:39:20] ...lsp/handlers.lua:113	"The language server volar triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2023-04-24 10:39:20] .../vim/lsp/rpc.lua:733	"rpc"	"vue-language-server"	"stderr"	"TypeError [ERR_INVALID_ARG_TYPE]: The \"request\" argument must be of type string. Received an instance of Array\n    at new NodeError (node:internal/errors:399:5)\n    at validateString (node:internal/validators:163:11)\n    at Function.resolve (node:internal/modules/helpers:124:5)\n    at createParsedCommandLineBase (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/vue-language-core/out/utils/ts.js:37:41)\n    at Object.createParsedCommandLine (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/vue-language-core/out/utils/ts.js:18:16)\n    at Object.resolveLanguageServiceHost (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/out/languageServerPlugin.js:37:39)\n    at createLanguageServiceHost (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/utils/project.js:161:51)\n    at /home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/utils/project.js:28:37\n    at Generator.next (<anonymous>)\n    at /home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/utils/project.js:7:71 {\n  code: 'ERR_INVALID_ARG_TYPE'\n}\n"
[ERROR][2023-04-24 10:39:20] .../vim/lsp/rpc.lua:733	"rpc"	"vue-language-server"	"stderr"	"TypeError [ERR_INVALID_ARG_TYPE]: The \"request\" argument must be of type string. Received an instance of Array\n    at new NodeError (node:internal/errors:399:5)\n    at validateString (node:internal/validators:163:11)\n    at Function.resolve (node:internal/modules/helpers:124:5)\n    at createParsedCommandLineBase (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/vue-language-core/out/utils/ts.js:37:41)\n    at Object.createParsedCommandLine (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/vue-language-core/out/utils/ts.js:18:16)\n    at Object.resolveLanguageServiceHost (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/out/languageServerPlugin.js:37:39)\n    at createLanguageServiceHost (/home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/utils/project.js:161:51)\n    at /home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/utils/project.js:28:37\n    at Generator.next (<anonymous>)\n    at /home/rijenkii/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/vue-language-server/node_modules/@volar/language-server/out/utils/project.js:7:71 {\n  code: 'ERR_INVALID_ARG_TYPE'\n}\n"
```
However it was fixed after updating the LSP server (through `:Mason` in my case).

**Comment by johnsoncodehk** [comment]
@rijenkii What are your pre-update and post-update version numbers?

**Comment by rijenkii** [comment]
According to the logs, `vue-language-server` was previously updated on Dec 18, 2022.
So, pre-update probably 1.0.14, and post-update is 1.4.4.

**Comment by xxSkyy** [comment]
I did update from 1.2.0 to 1.4.4, still creating new files have same problems

**Comment by xxSkyy** [comment]
@johnsoncodehk Today I've tinkered a bit in this topic and it turned out that neovim `0.9.0` has `[DidChangeWatchedFiles Notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) feature but I had only `0.8.3`. So I've updated it and enabled it in capabilities ( `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true` ) and for now file watcher works quite well and new files exist in completion and don't throw any errors!

I'll leave this issue open as I've made just some small tests on example projects. I'll report if it's all good on real projects till the end of the month.

**Comment by chaozwn** [comment]
> @johnsoncodehk Today I've tinkered a bit in this topic and it turned out that neovim `<=0.9.0` has [DidChangeWatchedFiles Notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) feature but I had only `0.8.3`. So I've updated it and enabled it in capabilities ( `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true` ) and for now file watcher works quite well and new files exist in completion and don't throw any errors!
> 
> I'll leave this issue open as I've made just some small tests on example projects. I'll report if it's all good on real projects till the end of the month.

l have same error.volar can't identify new files.

**Comment by chaozwn** [comment]
> @johnsoncodehk Today I've tinkered a bit in this topic and it turned out that neovim `<=0.9.0` has [DidChangeWatchedFiles Notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) feature but I had only `0.8.3`. So I've updated it and enabled it in capabilities ( `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true` ) and for now file watcher works quite well and new files exist in completion and don't throw any errors!
> 
> I'll leave this issue open as I've made just some small tests on example projects. I'll report if it's all good on real projects till the end of the month.

it works in tsx file.but not work in .vue files.

**Comment by xxSkyy** [comment]
@chaozwn check my config in my repos, here I've got all configured well, check if you have simmilar way.

**Comment by xxSkyy** [comment]
Update: now all works great, I consider it as closed and working, also updated issue comment with solution.

**Comment by chaozwn** [comment]
> Update: now all works great, I consider it as closed and working, also updated issue comment with solution.

Normal file changes are recognizable, but it is bad whether Vue files can detect the latest packages and provide import suggestions after running 'npm install' or 'yarn add'.

**Comment by chaozwn** [comment]
> > Update: now all works great, I consider it as closed and working, also updated issue comment with solution.
> 
> Normal file changes are recognizable, but it is bad whether Vue files provide new packages import suggestions after running 'npm install' or 'yarn add'.
