### ISSUE TITLE
Types for Custom Elements declared on the HTMLElementTagNameMap

### ISSUE THREAD

**Issue by steveworkman** [vuejs/language-tools#2562]
I'm working with a large custom element library based on Lit and built with TypeScript. The team have created types for all elements and have exposed the types like this:

```ts
declare global {
    interface HTMLElementTagNameMap {
        'mc-button': McButton;
    }
}
```
However, the elements still appear as `any` types when using them within SFCs with Volar. 

<img width="297" alt="image" src="https://user-images.githubusercontent.com/994905/228786751-82b6deca-772e-4835-ae21-6a8edaacfb66.png">

Can Volar pick up these tags, and if so, what config is required to make it happen?

**Comment by johnsoncodehk** [comment]
You can try:

```ts
declare module 'vue' {
  export interface GlobalComponents {
    McButton: McButton;
  }
}
```

See https://github.com/vuejs/language-tools/tree/master/packages/vscode-vue#usage

**Comment by steveworkman** [comment]
@johnsoncodehk thanks for that, good to know the context too - When we do that it resolves the tags but it doesn't check the properties - any way to do that?
