### ISSUE TITLE
TypeScript 5 const Type Parameters incorrectly highlighted

### ISSUE THREAD

**Issue by markglattback** [vuejs/language-tools#2564]
The following code is incorrectly highlighted when using the new[ const Type Parameters](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters) with TS 5.0.x and Volar 1.3.8 (pre-release)

```ts
function myFunc<const T extends string[]>(arr: T): T {
  return arr
}

//  error: Type parameter declaration expected. ts(1139)
```

**Comment by johnsoncodehk** [comment]
This is a VSCode issue, and it should be fixed in the latest VSCode release.
