### ISSUE TITLE
template HTMLElement add class propetry lead TS error

### ISSUE THREAD

**Issue by KallkaGo** [vuejs/language-tools#2567]
**in recently webgl demo, i meet some problem** 

![image](https://user-images.githubusercontent.com/82202033/229182588-e0ad2d57-29dc-4657-8aab-7ca48ccfcc00.png)

**i try some soultion but it doesn't work  ,finally i find  if install vercel ,it will be conflicted with volar（is it bug ? i'm not sure）**

**volar version :1.3.7** 
**vercel version: 28.18.3**
**vue version :3.2.47**
**typescript ：4.9.3**

**even more i try roll back vercel and volar versions ，doesn't work either**

**Comment by corsen2000** [comment]
I am seeing the same issue with `vue-tsc` and the `id` attribute. The issue starts occurring in version `1.3.9`. Version `1.3.8` is ok for me.
