### ISSUE TITLE
【bug】 After volar sets non-air parentheses to add Spaces, v-for automatically adds unlimited Spaces

### ISSUE THREAD

**Issue by Autumn-one** [vuejs/language-tools#2571]
After setting "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true , a space is added each time the document is formatted, as shown in the figure
![GIF 2023-4-2 12-33-20](https://user-images.githubusercontent.com/26438145/229331720-1d8ea540-2e23-4ec1-868d-763e7ff4dada.gif)

![image](https://user-images.githubusercontent.com/26438145/229331546-65f9a0fb-7f84-4812-8a38-3f6774f65aec.png)

Unfortunately, if this option is turned off, it can cause an error in the scope slot，It generates the wrong semicolon in the scope slot，

![image](https://user-images.githubusercontent.com/26438145/229331620-6933f164-b173-4871-8e65-35a69c1037c8.png)

**Comment by mrinc** [comment]
@johnsoncodehk is this change live yet ? (`v1.3.18`)

**Comment by davide-granello** [comment]
I have the same issue, also other attributes keep getting appended and prepended spaces:
```vue
<v-list-item
  v-for="option in availableOptions"
  :key="option.id"
  :title="option.name"
  @click.stop="onOptionSelected(option.id)"
/>
```
after format:
```vue
<v-list-item
  v-for=" option  in  availableOptions "
  :key=" option.id "
  :title=" option.name "
  @click.stop="onOptionSelected(option.id)"
/>
```

**Comment by kelvinz** [comment]
This doesn't seem to be fixed yet.
