### ISSUE TITLE
v-for highlight error

### ISSUE THREAD

**Issue by d1313113** [vuejs/language-tools#2574]
When using type as v-for item, it will cause the tag to highlight abnormally.

```vue
<template>
  <div>
    <div v-for="type in options" :key="type.id">
      <span>{{ type.value }}</span>
      <span>222</span>
    </div>
  </div>
</template>
<script>
  export default {
    setup() {
      return {
        list: [
          {
            id: 1,
            value: 1
          }
        ]
      }
    }
  }
</script>

```

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/35473748/229441739-540b0977-4f06-4ba6-91bd-f45713b52f44.png">

**Comment by Shyam-Chen** [comment]
#2560

**Comment by johnsoncodehk** [comment]
See https://github.com/vuejs/language-tools/issues/1290#issuecomment-1140386824
