### ISSUE TITLE
False positives of "Property is private and only accessible within class - ts(2341)"

### ISSUE THREAD

**Issue by omnichronous** [vuejs/language-tools#2576]
First of all, thank you for your work and support. I've read through a lot of issues here and in related repositories but I still can't understand why I see these errors.

Here is the environment of the project I'm working on:

- Vue version: **2.7.13**
- [Class-Style Vue Components](https://class-component.vuejs.org) written in TypeScript
- VSCode version: **1.77.0**
- Volar version: **1.3.8**
- TypeScript Vue Plugin (Volar) version: **1.2.0**
- `TypeScript and JavaScript Language Features` built-in extension disabled, as per Takeover mode

The errors appear when I access methods and properties defined as `private` from the template.

```js
private close() {
  this.$emit('close')
}
```

```vue
<button @click.native="close"/>
```

```
Property 'close' is private and only accessible within class 'MyComponent'.ts(2341)
```

To my understanding the template in a SFC is compiled down to a render function which works the same way as if you had defined it in the component options, i.e. it would be a member of the same class, so it would have no problems calling private methods in that same class. And indeed when I run the project everything works normally.

**Comment by hysan** [comment]
@omnichronous I don't have the same environment, but I have a similar one with class style components. Try setting `experimentalUseElementAccessInTemplate` to true in your `tsconfig.json`. This is what allowed the type hinting to work correctly in templates for me. Example snippet of what I have:

```jsonc
{
  "vueCompilerOptions": {
    // "target": 2.7,
    "target": 2, // For Vue version <= 2.6.14
    "experimentalUseElementAccessInTemplate": true
  },
  "compilerOptions": {
    ...
  }
}
```

The related issue that led me to this setting was: https://github.com/vuejs/language-tools/issues/997
The feature was added last year: https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#109-20221023

**Comment by LukasWillin** [comment]
> @omnichronous I don't have the same environment, but I have a similar one with class style components. Try setting `experimentalUseElementAccessInTemplate` to true in your `tsconfig.json`. This is what allowed the type hinting to work correctly in templates for me. Example snippet of what I have:
> 
> ```js
> {
>   "vueCompilerOptions": {
>     // "target": 2.7,
>     "target": 2, // For Vue version <= 2.6.14
>     "experimentalUseElementAccessInTemplate": true
>   },
>   "compilerOptions": {
>     ...
>   }
> }
> ```
> 
> The related issue that led me to this setting was: #997 The feature was added last year: https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#109-20221023


Simply adding `"experimentalUseElementAccessInTemplate": true` already fixed the issue for me:
VS Code Extension Volar: v1.6.0
VS-Code: 1.77.3
@vue/cli 4.5.14
Typescript: 4.2.2
vue@3.2.47
vue-class-component@7.2.6

**Comment by omnichronous** [comment]
Amazing, thank you so much @hysan! Problem solved, I'll close this issue.

**Comment by Brazlucas** [comment]
Thank you so much @hysan, it's working here!!

**Comment by Chang-Chen** [comment]
<img width="1784" height="787" alt="Image" src="https://github.com/user-attachments/assets/2db6343e-24e4-4618-a3ff-f5687edfe179" />

Project Dependencies：

 "dependencies": {
    "@vueuse/core": "^13.9.0",
    "pinia": "^3.0.3",
    "vue": "^3.5.18",
    "vue-router": "^4.5.1"
  },
  "devDependencies": {
    "@tsconfig/node22": "^22.0.2",
    "@types/node": "^22.16.5",
    "@vitejs/plugin-vue": "^6.0.1",
    "@vitejs/plugin-vue-jsx": "^5.0.1",
    "@vue/eslint-config-prettier": "^10.2.0",
    "@vue/eslint-config-typescript": "^14.6.0",
    "@vue/tsconfig": "^0.7.0",
    "eslint": "^9.31.0",
    "eslint-plugin-vue": "~10.3.0",
    "jiti": "^2.4.2",
    "npm-run-all2": "^8.0.4",
    "prettier": "3.6.2",
    "typescript": "~5.8.0",
    "vite": "^7.0.6",
    "vite-plugin-vue-devtools": "^8.0.0",
    "vue-tsc": "^3.0.4"
  }

Is this issue fixed?

**Comment by KazariEX** [comment]
@Chang-Chen See https://github.com/vuejs/core/issues/2981.
