### ISSUE TITLE
doesn't work after one file is moved to another folder

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#2577]
reproduce:

1. open a ts file, can see type info when hover on a ts variable
2. move the ts file to another folder, then all ts features doesn't work

Versions:

```
Version: 1.77.0 (Universal)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T09:57:11.797Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No
Volar: v1.3.11 Pre-Release
Takeover Mode: yes
```

https://user-images.githubusercontent.com/41773861/229499933-b5ec0887-fc15-4c10-82b0-589f82239108.mov

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/6ae4944f0631ae6f2e7334487416414e4f104342
