### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by MarcusXavierr** [vuejs/language-tools#2583]
I'm using neovim lsp, and on the lsp_config page, it says I need to do additional configuration on Volar to make it work properly on vue 2, but the README file doesn't exist anymore. Is it moved to another place? Or does Volar work fine on vue 2 and not need additional configuration anymore?

https://github.com/vuejs/language-tools/tree/master/extensions/vscode-vue-language-features

**Comment by johnsoncodehk** [comment]
The new link is https://github.com/vuejs/language-tools/tree/master/packages/vscode-vue
