### ISSUE TITLE
Empty global components props typings

### ISSUE THREAD

**Issue by niklv** [vuejs/language-tools#2589]
Upstream issue from https://github.com/nuxt/nuxt/issues/20010 ([comment](https://github.com/nuxt/nuxt/issues/20010#issuecomment-1497433044))

## Environment

    Operating System: Darwin
    Node Version: v16.18.1
    Nuxt Version: 3.3.2
    Nitro Version: 2.3.2
    Package Manager: npm@8.19.2
    Builder: vite
    User Config: -
    Runtime Modules: -
    Build Modules: -

## Reproduction

https://github.com/niklv/nuxt-component-props-def-bug

## Bug

For my project config typing I need to refer to typing of component props.
I try extract props typing in this way. But looks like there are no props typing at all.
```ts
<script lang="ts" setup>
// ComponentA.vue
const {propA} = defineProps<{
    propA: string
}>()
</script>

<template>
    <div v-text="propA" />
</template>

// config.ts
import type {ComponentA} from "#components";
import {ComponentOptionsBase} from "@vue/runtime-core";


type ComponentProps<T> = T extends ComponentOptionsBase<infer P, // Props
    any, // RawBindings
    any, // D
    any, // C
    any, // M
    any, // Mixin
    any, // Extends
    any> ? unknown extends P ? {} : P : {};


type CompAProps = ComponentProps<typeof ComponentA>


const someConfig:CompAProps = {
    // @ts-expect-error
    notExistedProp: true // should be error
}
```

## Additional context
![изображение](https://user-images.githubusercontent.com/3831943/230090658-25e0b818-f2c4-4afd-a912-32917510825c.png)

There are must be some props typing in first generic argument of DefineComponent

**Comment by johnsoncodehk** [comment]
This is probably due to the DefineComponent signature being updated, but now you can use https://github.com/vuejs/language-tools/tree/master/packages/vue-component-type-helpers instead of.

**Comment by niklv** [comment]
@johnsoncodehk I update deps in repoduction
The issue is still there.

**Comment by johnsoncodehk** [comment]
Did you see https://github.com/vuejs/language-tools/tree/master/packages/vue-component-type-helpers?
