### ISSUE TITLE
[Volar] Empty props with `defineProps` causes all properties of the Array prototype to be required

### ISSUE THREAD

**Issue by matthew-dean** [vuejs/language-tools#2591]
With TypeScript + Volar extension in VSCode, I discovered while creating a new component that Volar makes a distracting type inference with empty props.

<img width="923" alt="Screenshot 2023-04-05 at 10 18 03 AM" src="https://user-images.githubusercontent.com/414752/230155635-dac0da40-d1fb-4e4d-8d07-433d9b46d6ac.png">

With no props, it decides the root element is required to have all properties of an Array. This makes it difficult to edit the root node because the end of the element is far off-screen.

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter. Can you provide a minimal reproduction?

**Comment by matthew-dean** [comment]
Hmm now I'm getting `Operator '>' cannot be applied to types 'boolean' and '{}'`:

<img width="580" alt="Screenshot 2023-04-17 at 5 25 53 PM" src="https://user-images.githubusercontent.com/414752/232638309-afd128ce-44bc-4660-a47f-d81536e63ad5.png">

Could it be that Volar / Vue language services bork often when jumping to different branches or different projects? 🤔

**Comment by matthew-dean** [comment]
Ah dang it, I can't repro this one either.

**Comment by johnsoncodehk** [comment]
I think this is a upsteam issue, when the props option is empty, `$props` becomes a strange type, please forward it to the vue core repo.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/16279759/233782011-64814870-b731-42c4-b65b-3d6d60dce3b1.png">

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5bwC+c6UBcA5AG4CuqNA3AFBsDGRAzvPuDgBeFBmx4CkYjAAUSMFTA8AXInKkAlOzYwAnmFRwFEJcLgBrVLojo4ASSx8Ahlk6oAKvtQAePQZtwAmAAfADaNAAkxko0ALrsAPQJcCkAegD8QA
