### ISSUE TITLE
Fall-through attributes error out on third party components

### ISSUE THREAD

**Issue by unitydynamics** [vuejs/language-tools#2594]
using Volar v1.3.11

I've noticed that my templates that leverage fall-through attributes are being underlined in red:
![image](https://user-images.githubusercontent.com/14965930/230366411-58c6bb0b-e455-42d8-956f-af79741d38f8.png)

This happens for every fall-through I use, especially `aria-label` tags that I use for accessibility.
The mouse-over error is:
`
Argument of type '{ [x: string]: any; role: string; }' is not assignable to parameter of type 'VNodeProps & AllowedComponentProps & ComponentCustomProps & QListProps'.
  Object literal may only specify known properties, and 'role' does not exist in type 'VNodeProps & AllowedComponentProps & ComponentCustomProps & QListProps'.ts(2345)
`

I'm using Quasar components--and I've noticed the errors are only on those components--but that shouldn't matter right?  Third party components should always allow for fall-through attributes right?  I feel like this could be a Volar issue instead of a Quasar issue.

Thank you for your work on Volar!

**Comment by unitydynamics** [comment]
Just FYI, rolling back to Volar 1.3.4 removes the error condition.

**Comment by SIGSTACKFAULT** [comment]
appears to be fixed in Volar 1.3.12

**Comment by jesspinklet** [comment]
Same here this problem is really annoying. needs to be fixed in future updates.
