### ISSUE TITLE
vue-tsc error on nested ref parameters when a nested function is added in a reactive object

### ISSUE THREAD

**Issue by wal0x** [vuejs/language-tools#2595]
link to reproduce the error : [here][1]

In `vue 2.7 & 3`, if I am not mistaken any `ref` nested in a object inside `ref` or a `reactive()` will be unwraped as explaned [here][2]

This works fine and as expected in the following simple example :

    interface IName {
      first: string;
      last: string;
      sayHi?: () => void;
    }

    interface IPerson {
     name: IName;
     isAdult: boolean;
    }

    const me: IPerson = reactive({
      isAdult: ref(false),
      name: {
        first: ref("first"),
        last: "last"
      },
    });

No errors are detected and everything is fine since `reactive` unwrap all nested `ref`s and the object is of type `IPerson`

But when I decide to implement the optional function `sayHi: () => void` inside the nested object `name` a `ts` error appears

    const me: IPerson = reactive({
      isAdult: ref(false), // Type 'Ref<boolean>' is not assignable to type 'boolean'.ts(2322)
      name: {
        first: ref("first"), // Type 'Ref<string>' is not assignable to type 'string'.ts(2322)
        last: "last"
      },
      sayHi: function () {
        console.log("Hi !")
      }
    });

What is stranger is that I found that it's not related to `sayHi` but I get the errors when I add any function at any level of the object `me`. Knowing that when I serve/build my app everything works fine and no erros whatsoever and I don't understand why, is it a vue-tsc bug or limitation or something else 

  [1]: https://codesandbox.io/s/autumn-bird-4dsir9?file=/src/index.ts
  [2]: https://vuejs.org/api/reactivity-core.html#reactive

**Comment by rchl** [comment]
This seems more like a an issue specific to Vue types and Typescript since you can reproduce it with plain typescript, without using Volar.

Seems expected given gow `reactive` declaration looks like:

```ts
export declare function reactive<T extends object>(target: T): UnwrapNestedRefs<T>;
```

The return value is unwrapped but the passed object is not so need to match the initial type from the start.

Is there anything that prevents you from unwrapping the values manually? I would say that that would also make intentions clearer as it wouldn't look like then like the expectation is that the reactivity of those the input and output will be linked.

**Comment by wal0x** [comment]
@rchl The example I shared is just a simple basic illustration of the problem I have in my project. In my code I want and I expect to keep reactivity link that is why I have nested refs so I can't unwrap the values manually 
Right, this error is not a Volar issue it is thrown by typescript and by vue-tsc when run via a command line.

**Comment by johnsoncodehk** [comment]
This looks like a TS bug or design limitation, please consider reporting it to TS, unfortunately we can't handle this in this repo.
