### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by adsric** [vuejs/language-tools#2598]
Type: <b>Bug</b>

This is my first time reporting so am not sure if I have done this right but will do my best to provide as many details as possible in the hope it will help.

I've been using Volar in my setup for a long time and latest updates have crippled my performance. Editor seems to work fine for a little and then I get hanging saves with Prettier formatting on save or renaming or any task.

I used Extension Bisect and VSCode reported the Volar extension.

Extensions installed below

Volar
Prettier
Eslint
(PHP, Path, npm, Tailwind) Intellisense

Extension version: 1.2.0
VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:22:38.708Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|--crash-reporter-id 8eb92959-c33b-45e7-8d4d-0a57222e5db5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30705553
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by demiro** [comment]
I have the same issues since I update VSC last week... it is unbearable... when I restart the editor and start fresh, it works fine for 1-2min, and then again.... saving vue components takes 30-40s... 

Vue Language Features (Volar) v1.2.0
TypeScript Vue Plugin (Volar) v1.2.0
Prettier - Code formatter v9.10.4
