### ISSUE TITLE
important  error version bugs

### ISSUE THREAD

**Issue by sunJobGithub** [vuejs/language-tools#2601]
I installed the volar-v1.2.0 plug-in in vscode
This error has been reported in the bottom left corner of vscode when starting up - I have tried again and again to find v1.2.0 problematic.
The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

<img width="933" alt="image" src="https://user-images.githubusercontent.com/127279465/231046827-6e67dfa6-c5b2-41c8-976c-becf488e42c8.png">

I can't write code properly, I click on a function, I can't click on a prompt that's not referenced
My solution was to upgrade the volar version. When I upgraded to the latest version v1.3.14, the above problem was not there, but there was one other problem

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/127279465/231047654-c5d65a87-f781-4f63-8ebf-27721ebda45a.png">

The component of ant-design-vue that I referenced is reporting this Error. The plug-in reporting this error is vscode extensions "Error lens". How can I solve this red error message
So my final solution is to downgrade volar to v1.3.6 where both of the problems don't exist.
Please ask the author to look at how this problem is caused and how it can be solved
     very very think you 
(我在 vscode中安装了 volar - v1.2.0 版本的插件 
在启动vscode的时候一直左下角报这个错误-我经过反复尝试就是这个v1.2.0版本有问题
导致我没法正常写代码，点击某个函数，点不进去没有引用的提示
我的解决方式是升级volar的版本，当我升级到最新版v1.3.14是上述的问题是没有的，但有一个其他的问题
我引用的ant-design-vue的组件 报这种错，报这个错的插件是vscode extensions “Error lens”   不知怎么解决这种红色的错误提示
所以我的最终解决方案是降级 把volar降级到v1.3.6 上面的两个问题都不存在了。
请作者看一下这个问题是怎么引起的怎么解决的)
      very very think you

**Comment by leegee** [comment]
I've been having the problem since about last Thursday. Does VSC auto-update extensions?

I closed my ticket as I thought I had caused the problem, but seeing at least one other person has it....

![image](https://user-images.githubusercontent.com/512816/231188226-740156e5-ba8a-461e-9e1a-3bc72b06e927.png)

My root tsconfig for this package in my monorepo does contain `  "compilerOptions": {"verbatimModuleSyntax": true}`.
