### ISSUE TITLE
Using `Save as` in VSCode results in `Virtual script not found`

### ISSUE THREAD

**Issue by matthew-dean** [vuejs/language-tools#2603]
I thought I filed an issue for this but apparently not.

If you have a `.vue` file open, and you do Save As... and choose a new file name, your new file will be broken permanently until you restart Volar.

The Script tag will have a blue underline with: `Virtual script not found, may missing <script lang="ts"> / "allowJs": true / jsconfig.json.`

Even though this is the same error message as https://github.com/vuejs/language-tools/issues/1786, it only happens when saving as a new file, with the current version of Volar (1.2.0).

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce it. Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by matthew-dean** [comment]
@johnsoncodehk 

After cloning that repo and opening the folder (and HelloWorld.vue), I get:
`The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`

I assume it immediately crashes because I haven't installed modules (looks like that's most of the errors) but it feels like it shouldn't immediately crash.

## Next steps

After restarting, I get in the output:
```
TypeError: require(...).default is not a function
    at Object.<anonymous> (/Users/matthew/git/oss/volar-starter/volar.config.js:3:53)
```
However, TypeScript inference seems to be working.

## Problem

With `HelloWorld.vue` open, I do the keyboard shortcut to "Save As..." HelloWorld1.vue in the same folder, and yep, I get this blue line / error message under the `<script lang="ts" setup>` line `Virtual script not found, may missing <script lang="ts"> / "allowJs": true / jsconfig.json.volar`

**Comment by matthew-dean** [comment]
@johnsoncodehk Did you try "Save as..." with the same folder?

**Comment by matthew-dean** [comment]
@johnsoncodehk In addition, if I add an empty `<script> </script>` block at the top of any file, such as HelloWorld.vue in this case, I get the error: 
```
JSX expressions must have one parent element.ts(2657)
(property) template: ElementAttrs<HTMLAttributes>
```
This was happening to me before. A `<script />` block plus a `<script setup />` block causes Volar to crash / fail at templating.

**Comment by matthew-dean** [comment]
Will open a new issue for the above ☝️

**Comment by johnsoncodehk** [comment]
> With `HelloWorld.vue` open, I do the keyboard shortcut to "Save As..." HelloWorld1.vue in the same folder, and yep, I get this blue line / error message under the `<script lang="ts" setup>` line `Virtual script not found, may missing <script lang="ts"> / "allowJs": true / jsconfig.json.volar`

I can confirm with this, thanks.
