### ISSUE TITLE
Custom components with dot are not being highlighted

### ISSUE THREAD

**Issue by rodrigocfd** [vuejs/language-tools#2605]
I have a bunch of components being exported in a [barrel](https://basarat.gitbook.io/typescript/main-1/barrel), something like:

```ts
export {default as CheckBox} from './CheckBox.vue';
export {default as DatePicker} from './DatePicker.vue';
export {default as Spinner} from './Spinner.vue';
```

And using them as:

```vue
<script setup lang="ts">
import * as Core from '../components';
</script>

<template>
  <Core.Spinner />
</template>
```

The `Core.Spinner` is not being highlighted as a custom component (wrong syntax color):

![highlight-custom](https://user-images.githubusercontent.com/1283868/231767522-84670ecb-ae40-4216-afc4-2bad3876928d.png)

**Comment by johnsoncodehk** [comment]
This is expected, namespaced tags are colored by TS semantic highlighting, not colored like normal component tags.

**Comment by erropix** [comment]
@johnsoncodehk is there fix for this issue, I see the issue been closed but the problem is still there!

**Comment by KermanX** [comment]
> is there fix for this issue, I see the issue been closed but the problem is still there!

The current behavior is expected. If `Core.Spinner` is correctly typed as a component, the color of it will be correct.
