### ISSUE TITLE
Infinite end tag creation loop with .tsx files

### ISSUE THREAD

**Issue by vdemcak** [vuejs/language-tools#2612]
Type: <b>Bug</b>

I have the following component:
```typescript
const Home = () => {
  return (
    <>
      {/* Header */}
      <div className='w-full flex flex-col justify-between'>
        <div className='text-3xl font-semibold text-left text-gray-900  dark:text-white'>
          Probes Index
          <p className='mt-1 text-sm font-normal text-gray-500 dark:text-gray-400'>Browse a list of all registered probes.</p>
        </div>
    </>
  );
};
```
After entering the final `</div>` tag before `</>`, the extension starts to infinitely create new `<></>` tags and the only way to stop it is to close the file.

Extension version: 1.2.0
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 471131e5-af4b-4a88-b0f7-cc7faa1dcf11|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30705553
functionswalk:30687959
pythonms35:30701012
pythonclientmv:30713943

```

</details>

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem, can you provide a screen recording?

**Comment by vdemcak** [comment]
Here you go: https://youtu.be/01Xqvy7C8t4

**Comment by johnsoncodehk** [comment]
Thanks!
