### ISSUE TITLE
请问能否增加中文设置页面？

### ISSUE THREAD

**Issue by WangJincheng4869** [vuejs/language-tools#2614]
目前 Volar 的设置界面只有英文，请问是否有添加中文的打算？

**Comment by so1ve** [comment]
没必要，很多插件也没有中文设置
我记得插件设置没法做多语言

**Comment by WangJincheng4869** [comment]
> 没必要，很多插件也没有中文设置 我记得插件设置没法做多语言

![image](https://user-images.githubusercontent.com/41162158/232641690-84bcfcb3-2c9a-40ce-8d8f-c91c98413acd.png)

**Comment by johnsoncodehk** [comment]
Unfortunately this extension is almost maintained by me, so there is no more effort to maintain localization for other languages.
