### ISSUE TITLE
High memory cost and slow performance

### ISSUE THREAD

**Issue by so1ve** [vuejs/language-tools#2615]
Hi Johnson, thanks for this fantastic extension!
However, there are many users complaining about the slow performance and high memory cost. I also get this problem.
I know it is busy for you to maintain this project, so this issue is a tracker for this problem only. If you don't have much time on it, I can debug and fix this issue gradually (or post some information).
Thanks again!

**Comment by so1ve** [comment]
The ESLint extension is slow with language-tools 🤔

**Comment by so1ve** [comment]
Ah, thanks. Actually, volar is quite fast when use it standalone 😃

**Comment by johnsoncodehk** [comment]
Thanks for confirming that, I saw that your issue was related to ESLint so linked it, if your high memory usage is still an issue you can open a new issue.
