### ISSUE TITLE
Manually typing slot data in template does not work in Volar TS Server prerelease

### ISSUE THREAD

**Issue by loilo** [vuejs/language-tools#2617]
Manually typing slot data of untyped components works with stable TypeScript Vue Plugin (1.2.0) but breaks in the current prerelease (1.3.17):

<img width="579" alt="The component code from below as seen in VS Code, showing an error on the colon after 'data', stating: ',' expected. (ts1005)" src="https://user-images.githubusercontent.com/1922624/232570274-90e07b08-69f3-4256-8235-192a51d929eb.png">

Component code:

```vue
<script lang="ts" setup>
import { defineComponent } from 'vue'

let UntypedComponent = defineComponent({})
</script>

<template>
  <UntypedComponent>
    <template #default="data: { foo: string }">
      {{ data.foo }}
    </template>
  </UntypedComponent>
</template>
```

Is there anything else I can provide to help with resolving this? :)

**Comment by jacob-carlborg-apoex** [comment]
It's broken in the latest version (1.3.18) as well.
