### ISSUE TITLE
Throw an error when `composite` is enabled

### ISSUE THREAD

**Issue by sxzz** [vuejs/language-tools#2622]
Reproduction: https://github.com/sxzz/volar-starter/commit/e83eb070283dc0c06692b5d1bf7c4e486419e559

```
/project/node_modules/.pnpm/vue-tsc@1.3.16_typescript@5.0.4/node_modules/vue-tsc/bin/vue-tsc.js:53
                        throw err;
                        ^

Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at getRelativePathFromDirectory (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:5717:9)
    at relativeToBuildInfo (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:117152:38)
    at convertToReusableDiagnosticRelatedInformation (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:117237:18)
    at /project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:117223:20
    at Array.map (<anonymous>)
    at convertToReusableDiagnostics (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:117222:22)
    at getBuildInfo2 (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:117099:11)
    at newProgram.getBuildInfo (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:117309:41)
    at Object.getBuildInfo (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/typescript.js:116651:70)
    at emitBuildInfo (/project/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/typescript.js:109453:30)
```

**Comment by Mostaard** [comment]
I'm encountering the same issue

**Comment by stefanprobst** [comment]
i am getting the same error with `"incremental": true`

**Comment by FabianMontoya** [comment]
I have the same error:

```
> vue-tsc --noEmit

/Users/fabian.montoya/git/vue-app/node_modules/vue-tsc/bin/vue-tsc.js:53
			throw err;
			^

Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at getRelativePathFromDirectory (.../vue-app/node_modules/typescript/lib/tsc.js:5717:9)
    at relativeToBuildInfo (.../vue-app/node_modules/typescript/lib/tsc.js:117152:38)
    at convertToReusableDiagnosticRelatedInformation (.../vue-app/node_modules/typescript/lib/tsc.js:117237:18)
    at .../vue-app/node_modules/typescript/lib/tsc.js:117223:20
    at Array.map (<anonymous>)
    at convertToReusableDiagnostics (.../vue-app/node_modules/typescript/lib/tsc.js:117222:22)
    at getBuildInfo2 (.../vue-app/node_modules/typescript/lib/tsc.js:117099:11)
    at newProgram.getBuildInfo (.../vue-app/node_modules/typescript/lib/tsc.js:117309:41)
    at Object.getBuildInfo (.../vue-app/node_modules/typescript/lib/typescript.js:116651:70)
    at emitBuildInfo (.../vue-app/node_modules/typescript/lib/typescript.js:109453:30)

Node.js v18.14.2
```

```json
"devDependencies": {
    "@tsconfig/node18": "^2.0.0",
    "@types/node": "^18.16.2",
    "@vitejs/plugin-vue": "^4.2.1",
    "@vue/tsconfig": "^0.3.2",
    "typescript": "~5.0.4",
    "vite": "^4.3.3",
    "vue-tsc": "^1.6.1"
  }
```

**Comment by Ragura** [comment]
This is also blocking us from upgrading.
Current related versions:
`"typescript": "5.0.4"`
`"vue-tsc": "^1.6.4"`

Contents of tsconfig:
```json
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "moduleResolution": "node",
    "lib": [
      "DOM",
      "ESNext",
      "DOM.Iterable"
    ],
    "baseUrl": ".",
    "rootDir": "src",
    "strict": true,
    "alwaysStrict": true,
    "isolatedModules": true,
    "importsNotUsedAsValues": "error",
    "useDefineForClassFields": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "strictPropertyInitialization": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "declaration": true,
    "declarationMap": true,
    "declarationDir": "dist",
    "outDir": "dist",
    "sourceMap": true,
    "composite": true,
    "types": [
      "vite/client",
      "vitest"
    ]
  },
  "paths": {
    "@apps/*": [
      "apps/*/src"
    ],
    "@packages/*": [
      "packages/*/src"
    ]
  },
  "exclude": [
    "node_modules"
  ],
}
```

**Comment by FabianMontoya** [comment]
> I have the same error:
> 
> Running `npm run type-check` that execute `vue-tsc --noEmit`
> 
> ```
> > vue-tsc --noEmit
> 
> [root path...]/vue-app/node_modules/vue-tsc/bin/vue-tsc.js:53
> 			throw err;
> 			^
> 
> Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
>     at getRelativePathFromDirectory (.../vue-app/node_modules/typescript/lib/tsc.js:5717:9)
>     at relativeToBuildInfo (.../vue-app/node_modules/typescript/lib/tsc.js:117152:38)
>     at convertToReusableDiagnosticRelatedInformation (.../vue-app/node_modules/typescript/lib/tsc.js:117237:18)
>     at .../vue-app/node_modules/typescript/lib/tsc.js:117223:20
>     at Array.map (<anonymous>)
>     at convertToReusableDiagnostics (.../vue-app/node_modules/typescript/lib/tsc.js:117222:22)
>     at getBuildInfo2 (.../vue-app/node_modules/typescript/lib/tsc.js:117099:11)
>     at newProgram.getBuildInfo (.../vue-app/node_modules/typescript/lib/tsc.js:117309:41)
>     at Object.getBuildInfo (.../vue-app/node_modules/typescript/lib/typescript.js:116651:70)
>     at emitBuildInfo (.../vue-app/node_modules/typescript/lib/typescript.js:109453:30)
> 
> Node.js v18.14.2
> ```
> 
> ```json
> "devDependencies": {
>     "@tsconfig/node18": "^2.0.0",
>     "@types/node": "^18.16.2",
>     "@vitejs/plugin-vue": "^4.2.1",
>     "@vue/tsconfig": "^0.3.2",
>     "typescript": "~5.0.4",
>     "vite": "^4.3.3",
>     "vue-tsc": "^1.6.1"
>   }
> ```

I found that the error was a type error, but the `type-check` didn't show where was the error, only that `throw`, I had to open file by file and try to found where was the error and fixed it. 😠💀

**Comment by Ragura** [comment]
@FabianMontoya That's interesting, though it wouldn't explain why there is suddenly a type error to begin with after upgrading to the newer version. Do you remember what the type error was that you fixed? Perhaps it would give us an indication of where to look.

**Comment by FabianMontoya** [comment]
> @FabianMontoya That's interesting, though it wouldn't explain why there is suddenly a type error to begin with after upgrading to the newer version. Do you remember what the type error was that you fixed? Perhaps it would give us an indication of where to look.

It was a error in a `:key`, I had an `object` and I was passing it as a value of the `:key` prop of a component, and it had an error said that I can't pass an object as `value`, only a `string | number` and I don't remember what else haha, but I only changed `:key="myObject"` to `:key="myObject.id"`; but it wasn't the only error, in other places I was getting errors of type, and I was getting the same `throw err` in the console.

**Comment by Shujee** [comment]
@Ragura Thank you for sharing that piece of information. In my case, changing `composite` to `false` simply builds the output correctly, without any errors. When I set it to `true` again, I see the dreaded `Debug Failure. False expression: Paths must either both be absolute or both be relative` message again. Not sure what `composite` really does, but I guess I can live without it for now.
