### ISSUE TITLE
[Help] How to disable hover hints on generic html tags and attributes

### ISSUE THREAD

**Issue by ggedde** [vuejs/language-tools#2623]
Sorry if this has been answered or is obvious to others, but I have searched and cannot find the solution.
Is there a way to disable the hover hints for generic html tags and attributes like &lt;div&gt; &lt;span&gt; class="" href="", etc.
Or how to disable it entirely?

<img width="279" alt="2023-04-18_09-45-09" src="https://user-images.githubusercontent.com/3236909/232848891-f88ed785-1787-4b4d-98a8-5374e6588e2b.png">

I have "Show hover documentation" disabled, but it still shows it and I am not sure if it is Volar, Typescript or just VS Code doing it or where to go to disable it, but pretty sure it is the Volar extension for VS Code.

I do like the hover hints for custom components so I can see what props are available, etc, but just don't need the distraction for general tag information.

Is it possible to add which tags and attributes I don't want to see to some sort of settings? I don't mind adding all the ones I don't need information on if that is possible.
Or only show if I am holding down Ctrl or Opt, etc.
Thanks

**Comment by MorevM** [comment]
@ggedde 

This is a VSCode setting "editor.hover.enabled":

![editor hover enabled](https://user-images.githubusercontent.com/49679666/233637880-793650ac-20b9-40db-ad6d-6e732b6eabdf.jpg)

As far I know, you can't disable it for a bunch of features like HTML tags, but keep it for custom components or something similar, so I may recommend to install [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) extension and create a custom keybinding to turn off/on these hints entirely.

**Comment by ggedde** [comment]
Thanks @MorevM, I am familiar with that setting and don't want to disable it for everything.
I will check out Settings Cycler. Thanks

These hover definitions are coming from:
node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts
So it seems that it is related to TypeScript and Vuejs.

So I need a way to disable VS Code or Typescript from using this file or other files I choose for hover definitions.
It would be nice if there was a ignore files setting for this. Not sure exactly what the best way to do this is or how to implement it, but to have this feature would greatly reduce the clutter when working on projects.

**Comment by johnsoncodehk** [comment]
This is technically the correct behavior because it does have TS type messages. If you do a goto definition on attr, it will take you to the TS definition.

Adding settings to disable hover info for attrs is feasible, but unfortunately I don't intend to implement it, because template virtual code generation is already very complicated now, we need to avoid adding more complexity, and it is difficult to distinguish between attrs and props hover behavior.
