### ISSUE TITLE
vue2.7 template tserror

### ISSUE THREAD

**Issue by GGBeng1** [vuejs/language-tools#2625]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/40552498/232989495-da901b16-871c-45b2-9a3d-85074f9e8443.png">

1. Volar v1.2.0
2. Vue v2.7.14

I don't know how to solve this error

**Comment by johnsoncodehk** [comment]
Please provide a reproduction, otherwise I cannot investigate the issue.
