### ISSUE TITLE
defineExpose doesn't seem to be added to autocomplete

### ISSUE THREAD

**Issue by Jona898** [vuejs/language-tools#2628]
If i use `defineExpose({ someFunc, someVal})` and create a reference of the child Component using `<ChildComp ref="childRef" />`, Then the hover shows the exposed values, but if you try to use them then they have the type any.

I created a testRepo to extract when it happens: https://github.com/Jona898/TestDefineExpose_Volar_autocomplete/tree/master/src/components

I know that isn't what you would use that for. I used it to open a context menu i defined once, but needed to call the open function with the MouseEvent and other data. In that case i dodn't think props are the right way.

**Comment by johnsoncodehk** [comment]
Try change this line:

```diff
<script setup lang="ts">
import { ref } from "vue";
import ChildComponent from "./ChildComponent.vue";

const numb1 = ref(0);
const numb2 = ref(0);

- const childRef = ref<typeof ChildComponent | null>(null);
+ const childRef = ref<InstanceType<typeof ChildComponent> | null>(null);
</script>
```

**Comment by Jona898** [comment]
Thank you.
Didn't know about InstanceType. Learned something new.
Thanks for your reply.
