### ISSUE TITLE
Parameter 'XXX' implicitly has an 'any' type, but a better type may be inferred from usage.ts(7044)

### ISSUE THREAD

**Issue by sheremet-va** [vuejs/language-tools#2630]
Version: 1.3.19

I see a lot of false positive errors on hover:

> Parameter 'XXX' implicitly has an 'any' type, but a better type may be inferred from usage.ts(7044)

<img width="757" alt="Screenshot 2023-04-19 at 21 22 16" src="https://user-images.githubusercontent.com/16173870/233178716-733eee94-aa0c-4bdf-aa71-ee52308ec0ea.png">

I wasn't able to make a small reproduction, but you can see the error on this line: https://github.com/zammad/zammad/blob/develop/app/frontend/apps/mobile/pages/ticket/views/TicketDetailArticlesView.vue#L186

There are several errors scattered around the project with the same message. Here is another example: https://github.com/zammad/zammad/blob/develop/app/frontend/apps/mobile/pages/ticket/views/TicketDetailArticlesView.vue#L89

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem on a fresh clone, maybe something to do with node_modules? Can you try a full reinstall of node_modules?

<img width="661" alt="image" src="https://user-images.githubusercontent.com/16279759/233376715-be039a48-96e5-46bf-8b9a-3298b7b0656f.png">

**Comment by sheremet-va** [comment]
> I can't reproduce the problem on a fresh clone, maybe something to do with node_modules? Can you try a full reinstall of node_modules?
> 
> <img alt="image" width="661" src="https://user-images.githubusercontent.com/16279759/233376715-be039a48-96e5-46bf-8b9a-3298b7b0656f.png">

When you hover over this three dots what does it show?

**Comment by johnsoncodehk** [comment]
I don't know, it's gone when I reopen the repo.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/16279759/233383419-45e10e33-f91d-4a86-83fe-371906a39f97.png">

**Comment by sheremet-va** [comment]
Thank you! I was about to tell you that clearing node_modules and restarting the VS Code didn't help.

**Comment by Kane-Kuroneko** [comment]
Same trouble , I am using Webstorm 2023.2 , is it caused the problem ?

**Comment by eggachecat** [comment]
Here's a minimal reproduction
```typescript
export interface IConverter<T, U> {
    toTestFeature(ctx: any, src: T): any;
    fromTestFeature(ctx: any, angaFeature: U): T;
}

class Test implements IConverter<string, number> {
    toTestFeature(ctx, src) {
    }
    fromTestFeature(ctx, angaFeature) {
        return '0';
    }
}

```

**Comment by rsxdalv** [comment]
I'm pretty sure this is purely a typescript problem since I have seen it for several years now, and they still have not fixed it. My best recommendation is just ignoring the ... under a variable name, as the 'workarounds' will disable much more than just this error.

**Comment by Http-status-code-403** [comment]
@johnsoncodehk https://montgomery441.github.io/t8YAIG1MrPS43lw/
