### ISSUE TITLE
1.4.0版本更新后在uniapp+vue3+ts项目中错误提示

### ISSUE THREAD

**Issue by YHSanSheng** [vuejs/language-tools#2640]
![1](https://user-images.githubusercontent.com/112924145/233516578-0fbe2f1d-ccd4-4f3f-b627-6bc6179dce93.jpg)
![2](https://user-images.githubusercontent.com/112924145/233516581-8050ca67-7261-4479-996c-fbbee20d9609.jpg)

如图所示 更新后提示【不能将类型“($event: any) => void”分配给类型never”。】回退1.2.0版本正常。

**Comment by YHSanSheng** [comment]
<view class="help arrow" @tap="showHalfDialog('helps')">

**Comment by luvletterldl** [comment]
+1 我这里是@mousewheel事件
