### ISSUE TITLE
Don't update to version v1.4.0

### ISSUE THREAD

**Issue by roojay520** [vuejs/language-tools#2641]
If you are using TypeScript, avoid updating to version 1.4.0. Upon updating to Volar v1.4.0, the `template` code will display TypeScript type errors. Attempting to install other Volar versions may result in slow.

**Comment by jahnli** [comment]
same problem

**Comment by GeassAthena** [comment]
the same

**Comment by 945967063** [comment]
same problem

**Comment by lainbo** [comment]
same issue here

**Comment by cx690** [comment]
same problem

**Comment by fubd** [comment]
horrible  version 1.4.0

**Comment by saatana97** [comment]
the same
skipped test before release?

**Comment by mayoisuki** [comment]
same problem

**Comment by saatana97** [comment]
I'm using antd-vue components library
all components throw ts error that need bind App<any>
rollback to version 1.2.0 need during some minutes,this is too slow

**Comment by superrunlong** [comment]
use ant design vue
same problem

**Comment by mashuai333** [comment]
I have reback the version v1.2.0

**Comment by warmthsea** [comment]
Me to，If use Volar1.2，in my project ，volar not working

![image](https://user-images.githubusercontent.com/45450994/233530835-2d891c07-cf56-437d-af2f-d39cf3a4d502.png)

**Comment by johnsoncodehk** [comment]
Please open issue for actual bugs, otherwise we can't handle it.

**Comment by warmthsea** [comment]
> Please open issue for actual bugs, otherwise we can't handle it.

Wait a moment, providing minimum reproduction

**Comment by warmthsea** [comment]
> Please open issue for actual bugs, otherwise we can't handle it.

https://github.com/warmthsea/volar-types-err

**Comment by warmthsea** [comment]
> Please open issue for actual bugs, otherwise we can't handle it.

https://github.com/warmthsea/recurrent-volar-types-err

**Comment by warmthsea** [comment]
> > Please open issue for actual bugs, otherwise we can't handle it.
> 
> https://github.com/warmthsea/recurrent-volar-types-err
