### ISSUE TITLE
after v1.4, the color of vue components tag was changed in some theme extensions 

### ISSUE THREAD

**Issue by liweiook** [vuejs/language-tools#2642]
![image](https://user-images.githubusercontent.com/42706756/233518864-322a3c89-44e4-4759-b393-bc3c7f00cc56.png)

its  undistinguishable.

**Comment by warmthsea** [comment]
https://github.com/vuejs/language-tools/issues/2641

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem, what is the theme?

**Comment by liweiook** [comment]
> I can't reproduce the problem, what is the theme?

sorry,  this project is using vue2 , and i just tried vue3 project, its no problem,  but for vue2 project v1.2 is also ok.
