### ISSUE TITLE
[vue-language-core] Nullish coalescing assignment throws in Node 14

### ISSUE THREAD

**Issue by cuebit** [vuejs/language-tools#2643]
The following line throws `SyntaxError: Unexpected token '??='` error in Node 14 since the target has been bumped to `ES2021`.

https://github.com/vuejs/language-tools/blob/5a9f46db24151563e0b4f324c20d60561d82097d/packages/vue-language-core/src/generators/template.ts#L797

Is Node 14 no longer supported? If so, where is this documented?

**Comment by johnsoncodehk** [comment]
We dropped Node 14 support (#2489), are there still use cases where it is necessary?

**Comment by cuebit** [comment]
Thanks for the reference, makes complete sense. 

No, the use case is not trivial. I can work around it. Thanks so much!
