### ISSUE TITLE
今天更新后 第三方组件引用提示缺少类型，请问这个是什么问题

### ISSUE THREAD

**Issue by qieasan** [vuejs/language-tools#2647]
![image](https://user-images.githubusercontent.com/40800725/233532351-d18b05a1-cfbf-4b91-b95d-46099b78d6cc.png)
出现这个问题， 包括 element-plus 也有同样的问题

**Comment by yunxifd** [comment]
+1

**Comment by LQ6666666** [comment]
+1 刚刚的 1.4.1 还是会报错

**Comment by wencwcoder** [comment]
1.4.1 还是不行 😑

**Comment by qieasan** [comment]
如何回退版本？看着太难受了全红

**Comment by LQ6666666** [comment]
@qieasan https://github.com/element-plus/element-plus/issues/12529 这个 issue 有方案退回1.2.0

**Comment by wencwcoder** [comment]
> 如何回退版本？看着太难受了全红

![image](https://user-images.githubusercontent.com/52773820/233533915-75e0a70f-7090-4a22-9d7f-2a15fc5fa8b3.png)
![3(C7GQ{54YGXZHG{95SX91R](https://user-images.githubusercontent.com/52773820/233533986-72ed4697-4430-4eb3-a467-2e1cdcaa504a.png)

**Comment by qieasan** [comment]
> > 如何回退版本？看着太难受了全红
> 
> ![image](https://user-images.githubusercontent.com/52773820/233533915-75e0a70f-7090-4a22-9d7f-2a15fc5fa8b3.png) ![3(C7GQ{54YGXZHG{95SX91R](https://user-images.githubusercontent.com/52773820/233533986-72ed4697-4430-4eb3-a467-2e1cdcaa504a.png)

thanks！

**Comment by johnsoncodehk** [comment]
<img width="250" alt="螢幕截圖 2023-04-21 11 24 52" src="https://user-images.githubusercontent.com/16279759/233533773-d6b8807f-cd01-4eed-a247-df69e8d55b73.png">

Where is the `App<any> &` from?

**Comment by meguoe** [comment]
+1

**Comment by qieasan** [comment]
> <img alt="螢幕截圖 2023-04-21 11 24 52" width="250" src="https://user-images.githubusercontent.com/16279759/233533773-d6b8807f-cd01-4eed-a247-df69e8d55b73.png">
> 
> Where is the `App<any> &` from?

I don't know, back to v1.2.0 is ok

**Comment by qiaozhu** [comment]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/25722049/233535520-b4fee07b-bc7b-4781-b57f-d081a1512db1.png">
31分钟前更新的1.4.1页没解决这个问题
降级到1.2.0没问题

**Comment by johnsoncodehk** [comment]
Please provide a minimal reproduction, otherwise we cannot investigate.

**Comment by warmthsea** [comment]
https://github.com/warmthsea/recurrent-volar-types-err

**Comment by warmthsea** [comment]
> 请提供最小复制，否则我们无法调查。



> Please provide a minimal reproduction, otherwise we cannot investigate.

https://github.com/warmthsea/recurrent-volar-types-err

**Comment by itliujia** [comment]
+1

**Comment by RJQingHuan** [comment]
+1

**Comment by codepandy** [comment]
+1

**Comment by codepandy** [comment]
谁有3月份或者2月份的安装包？

**Comment by warmthsea** [comment]
> 谁有3月份或者2月份的安装包？

![image](https://user-images.githubusercontent.com/45450994/233552861-3a2e832f-6dd3-4ea3-a11b-22ce6f7c0b01.png)
![image](https://user-images.githubusercontent.com/45450994/233552885-d90646e3-3feb-489c-b302-29c1b436e21a.png)

**Comment by codepandy** [comment]
You can use this first

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/1.3.1/vspackage

**Comment by codepandy** [comment]
@warmthsea 我这点击没反应，不知道啥情况

**Comment by itliujia** [comment]
我把 TypeScript Vue Plugin (Volar) 降到1.2.0就可以了

**Comment by itliujia** [comment]
restart vscode 就行了

**Comment by warmthsea** [comment]
> @warmthsea 我这点击没反应，不知道啥情况

等待一下，这个有延迟

**Comment by warmthsea** [comment]
> 我把 TypeScript Vue Plugin (Volar) 降到1.2.0就可以了

大多数项目降到 1.2 可以正常工作
https://github.com/warmthsea/recurrent-volar-types-err/issues/1
但是我的降低到 1.2后，Volar 直接启动错误
![image](https://user-images.githubusercontent.com/45450994/233553807-b4be98b6-0a79-49c7-889c-e36e2a7f0115.png)

**Comment by codepandy** [comment]
@warmthsea  Vue Language Features (Volar) 降低到我上面发的1.3.1没问题，ts那个是最新的

**Comment by codepandy** [comment]
@warmthsea  Vue Language Features (Volar) 降低到我上面发的1.3.1没问题，ts那个是最新的

**Comment by nanq1993** [comment]
+1

**Comment by warmthsea** [comment]
> @warmthsea Vue Language Features (Volar) 降低到我上面发的1.3.1没问题，ts那个是最新的

这个下载下来怎么是文件?
![image](https://user-images.githubusercontent.com/45450994/233555482-ea30ba4c-3af7-4616-a6bc-5a734fb2e519.png)

**Comment by warmthsea** [comment]
> > 我把 TypeScript Vue Plugin (Volar) 降到1.2.0就可以了
> 
> 大多数项目降到 1.2 可以正常工作 [warmthsea/recurrent-volar-types-err#1](https://github.com/warmthsea/recurrent-volar-types-err/issues/1) 但是我的降低到 1.2后，Volar 直接启动错误 ![image](https://user-images.githubusercontent.com/45450994/233553807-b4be98b6-0a79-49c7-889c-e36e2a7f0115.png)

降到了 1.1 ，正常工作了
![image](https://user-images.githubusercontent.com/45450994/233558668-3d0590a1-511c-49d9-8f8e-fe9e64cd5bbd.png)

**Comment by qieasan** [comment]
哈哈哈哈， 你不容易啊 @warmthsea  等他们修复吧，我降了两个版本才可以的

**Comment by yanglee2421** [comment]
+1，element-plus@2.3.3 volar@1.4.1

**Comment by evilArsh** [comment]
降级了是没问题，就是打不了包了，我猜是vue-tsc升级后和element-plus的问题

**Comment by ssuupprr** [comment]
+1

**Comment by johnsoncodehk** [comment]
See https://github.com/element-plus/element-plus/issues/12529#issuecomment-1517523373

**Comment by ArthurSuz** [comment]
+1，antdv同样存在问题，只能暂时回退1.2.0

**Comment by warmthsea** [comment]
> +1，antdv同样存在问题，只能暂时回退1.2.0

可以提供 antdv 的复现么

**Comment by ArthurSuz** [comment]
> > +1，antdv同样存在问题，只能暂时回退1.2.0
> 
> 可以提供 antdv 的复现么

![image](https://user-images.githubusercontent.com/29251610/233605614-aa58ea6a-d63d-45f3-873a-8927b6dd8bb1.png)
任意项目打开安装antdv都存在该问题

**Comment by qieasan** [comment]
如何解决的呀？ 我也是动态生成的文件 @warmthsea

**Comment by warmthsea** [comment]
1.4.2 版本已经修复了
![image](https://user-images.githubusercontent.com/45450994/233631683-0187909d-8db1-44ee-bcbc-1d7e9f9b9b55.png)
