### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by physicx594** [vuejs/language-tools#2649]
"version": "1.4.0",

![image](https://user-images.githubusercontent.com/58924152/233545235-4ad57789-e046-47d7-822f-56e9a108da21.png)

@volar/vue-language-core/out/generators/template.js:553
![image](https://user-images.githubusercontent.com/58924152/233545338-caf65f1e-f425-4079-8843-f1528f6bdd3b.png)

**Comment by johnsoncodehk** [comment]
Duplicate of #2643
