### ISSUE TITLE
Takeover mode seems to be buggy

### ISSUE THREAD

**Issue by youkei-zzz** [vuejs/language-tools#2651]
Volar seems to have this problem after updating to version 1.4.1. In the previous version 1.2, the TS version that comes with vscode can be used when the takeover mode is adopted, but after the update, it seems that there is only the TS version in node_modules. If you choose the TS version that comes with vscode, the following error will appear：

<img width="975" alt="image" src="https://user-images.githubusercontent.com/101049479/233557675-ad681ace-7d51-4daf-aa2d-3caebce4514e.png">

<img width="351" alt="image" src="https://user-images.githubusercontent.com/101049479/233556555-ff3a7e56-d94c-4603-96d6-27b2751333a5.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/101049479/233556620-16ac19ca-116f-4e9a-8a0d-5502c152c536.png">

**Comment by warmthsea** [comment]
Use Volar 1.1

**Comment by Tanimodori** [comment]
It seems "VS Code's Version" doesn't work in 1.4.1 in my local env too. 1.4.0 works.
