### ISSUE TITLE
最新版1.4.1版本出现Saving time is too long. (> 500 ms)

### ISSUE THREAD

**Issue by wjw020206** [vuejs/language-tools#2652]
不知道是什么原因，刚更新最新版本运行项目就出现这个提示
![image](https://user-images.githubusercontent.com/59106659/233562993-1f82204e-eeed-48db-ad2c-9f9cb4db3fb2.png)

**Comment by KBzhu** [comment]
+1

**Comment by wjw020206** [comment]
我顺便补充一下自己所使用的环境
Node.js v16.19.1
VScode v1.77.3
Vue Language Features (Volar) v1.4.1
TypeScript Vue Plugin (Volar) v1.4.1
项目所使用的TypeScript版本 v5.0.4
vite v4.2.1
vue v3.2.47

**Comment by Colory** [comment]
![image](https://user-images.githubusercontent.com/2883413/233588588-c5f86985-5035-4d96-9ae8-dfa00d41fabf.png)
it's the new feat add in v1.4.0 for long time operation.
you can waiting for the action finish or disable it right now.

**Comment by Zzxuxuu** [comment]
我把版本退回到1.2.0了，1.4版本全局报红

**Comment by MrWangJustToDo** [comment]
问题很大  大家忍一下

**Comment by RuanZhongNan** [comment]
是的。我也出现了这样的错误。在代码保存时，出现该错误。

**Comment by johnsoncodehk** [comment]
This is a feature to avoid codeActions causing long save times when used with other extensions. v1.4.2 increases the preset time to 1000ms, you can also change it to a larger value.

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/233991129-fd38541a-0940-4234-a8b8-47497905f4b8.png)

Still got this issue.

**Comment by yoyo837** [comment]
It happens when batch replacing text in multiple files.

**Comment by wjw020206** [comment]
> It happens when batch replacing text in multiple files.

Change the value to something larger than 2665ms.Although I feel like this is not the way to go on.

**Comment by andreshg112** [comment]
Every time I save, the time increases, but the file is correctly saved immediately. It looks like an accumulator in the background is not cleaning the time of the files saved previously.

In this example, it has increased from 70000 to 400000, and now 500000.

![image](https://user-images.githubusercontent.com/15859884/234286195-9bf2a0d5-5efa-4893-9a54-8fd405a5e748.png)

**Comment by johnsoncodehk** [comment]
@andreshg112 I have no idea why, but https://github.com/vuejs/language-tools/commit/3ace934bc61711e4e5fd5e095766d3bb2c4b69ad should avoid the problem.

**Comment by ChloeKurumi** [comment]
+1，看来不是我的问题，突然报错，难受

**Comment by so1ve** [comment]
@johnsoncodehk Hi Johnson, can you add this to the document or pin a new issue about the saving time? This problem is caused by other conflict extensions and it will be good to let users know.

**Comment by johnsoncodehk** [comment]
@so1ve added in https://github.com/vuejs/language-tools/commit/3baacde7e7c093003fca3bc159bea631a1e3a857, thanks.

**Comment by JackieDYH** [comment]
vscode Saving time is too long. (1734 ms > 1000 ms),
