### ISSUE TITLE
Volar中typescript version的问题

### ISSUE THREAD

**Issue by F-OlO-Y** [vuejs/language-tools#2654]
volar自从1.3.0版本开始到1.4.0版本，在windows版本的vscode上status bar无法显示ts版本号只能显示 x.x.x, 也就是说1.3.0-1.4.0版本的volar无法检测vscode's typescript version 和 workspace typescript version(即使在工作区的node_modules中安装了typescript也不行)。

volar 1.4.1版本可以检测到workspace typescript version但是无法检测到vscode's typescript version。当通过点击vscode status bar去切换使用的typescript版本后volar会直接提示 Vue Semantic Server client: couldn't create connection to server，经过3次重试后就崩溃了。

volar在vscode启动后会在控制台出现这样的警告 [Vue.volar]: 无法注册“typescript.tsdk”。此属性已注册。这条警告在windows版的vscode中已经存在了很长一段时间。

**Comment by Tanimodori** [comment]
> volar自从1.3.0版本开始到1.4.0版本，在windows版本的vscode上status bar无法显示ts版本号只能显示 x.x.x, 也就是说1.3.0-1.4.0版本的volar无法检测vscode's typescript version 和 workspace typescript version(即使在工作区的node_modules中安装了typescript也不行)。

Duplicate of #2637 

> volar 1.4.1版本可以检测到workspace typescript version但是无法检测到vscode's typescript version。当通过点击vscode status bar去切换使用的typescript版本后volar会直接提示 Vue Semantic Server client: couldn't create connection to server，经过3次重试后就崩溃了。
> 
> volar在vscode启动后会在控制台出现这样的警告 [Vue.volar]: 无法注册“typescript.tsdk”。此属性已注册。这条警告在windows版的vscode中已经存在了很长一段时间。

Duplicate of #2651

**Comment by MonkeyDCang** [comment]
复议，20230812，
import "....vue", 报错提示Cannot find module or its corresponding type declarations
重装typescript a lot times, settings->workspace enabled，however....
