### ISSUE TITLE
volar 1.4.1  element plus error

### ISSUE THREAD

**Issue by UDDDDD** [vuejs/language-tools#2655]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/54108789/233563731-839d6d80-ef30-4693-861d-7e7b6c727a16.png">

**Comment by hansonfang** [comment]
same here

**Comment by KBzhu** [comment]
same question，we shoule back toV1.2.0

**Comment by Tanimodori** [comment]
Duplicate of #2647

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/issues/12529

**Comment by coderwyd** [comment]
Roll back the Volar version to 1.2.0 and you're good to go!
