### ISSUE TITLE
Slot Props issue after updating to v1.4.1

### ISSUE THREAD

**Issue by MatiasMorici** [vuejs/language-tools#2657]
Deconstructing Slot props shows this error:
![image](https://user-images.githubusercontent.com/11527928/233604973-a8d3547b-ca3a-4b6b-bdab-4fff56314a75.png)

**Comment by johnsoncodehk** [comment]
Can you provide a screenshot of the hover `#default`?

**Comment by MatiasMorici** [comment]
> Can you provide a screenshot of the hover `#default`?

Ok, that was the issue. Before the update, #default had any type, now is handling the type propertly. 

Thanks!

**Comment by johnsoncodehk** [comment]
It should be a same problem with #2646 and fixed in v1.4.2.
