### ISSUE TITLE
Cannot find base config file "@vue/tsconfig/tsconfig.web.json"

### ISSUE THREAD

**Issue by laterdayi** [vuejs/language-tools#2660]
failed to resolve "extends":"@vue/tsconfig/tsconfig.web.json" in \tsconfig.json
20:34:44 [vite] Internal server error: failed to resolve "extends":"@vue/tsconfig/tsconfig.web.json" in F:\tsconfig.json
  Plugin: vite:esbuild

**Comment by laterdayi** [comment]
in 1.4.2

**Comment by johnsoncodehk** [comment]
This is a Vite error.
