### ISSUE TITLE
Type "never" when deconstructing slot props to new variable name

### ISSUE THREAD

**Issue by jf-paradis** [vuejs/language-tools#2667]
In Volar > 1.4+, when a slot prop is assigned to a new variable name, although the prop gets type "any", the new variable gets type "never".

Here we deconstruct the props to get "foo" assigned to "item": 

<img width="330" alt="Screenshot 2023-04-21 at 4 49 10 PM" src="https://user-images.githubusercontent.com/89814003/233750529-2edffedf-6953-453b-aae7-160d95d2ace2.png">

<img width="421" alt="Screenshot 2023-04-21 at 4 49 21 PM" src="https://user-images.githubusercontent.com/89814003/233750495-7b651722-424f-47ec-86c2-c000654f4440.png">

**Observation**
This issue doesn't occur if the component is exposed via global components instead of being a named import. In that case, the new variable is assigned type "any".

**Comment by johnsoncodehk** [comment]
I can't reproduce it, can you provide repro case?

<img width="362" alt="image" src="https://user-images.githubusercontent.com/16279759/233783069-f895d8c4-405e-44d1-8786-76eebc33c11c.png">

**Comment by satrong** [comment]
> I can't reproduce it, can you provide repro case?
> 
> <img alt="image" width="362" src="https://user-images.githubusercontent.com/16279759/233783069-f895d8c4-405e-44d1-8786-76eebc33c11c.png">

> 问题描述有点复杂，英文不好，见谅

假如上面的 `HelloWorld` 组件是一个第三方组件库的组件，而这个第三方组件库并没有类型支持，这个时候我们通过下面方式定义组件类型：
```ts
import { type DefineComponents } from 'vue'

declare module 'vue' {
  export interface GlobalComponents  {
     HelloWorld: DefineComponents<{}>
  }
}
```

由于不知道如何在 `DefineComponents` 去定义 Scoped Slots  的类型，导致 `#default="{ foo }"` 中的 `foo` 类型一直是 `never`。但我的项目使用的是 `vue 2.7`，使用 `#default="{ foo } as { foo: string }"` 这种写法会编译报错。

很困扰~😂

**Comment by johnsoncodehk** [comment]
`#default="{ foo } as { foo: string }"` is not valid syntax, it should be `#default="{ foo }: { foo: string }"`.

**Comment by satrong** [comment]
> `#default="{ foo } as { foo: string }"` is not valid syntax, it should be `#default="{ foo }: { foo: string }"`.

Not work in vue 2.7
```
[plugin:vite:vue2] Unexpected token, expected ","
```
