### ISSUE TITLE
I can use ts-reset with volar

### ISSUE THREAD

**Issue by salemkode** [vuejs/language-tools#2669]
```import "@total-typescript/ts-reset";```

When I add import ts-reset volar server will stop

I am using fedora 37
![image](https://user-images.githubusercontent.com/58360393/233762149-a27b2092-2b26-4069-97ae-bed7bf4214d8.png)

**Comment by salemkode** [comment]
To fix this problem, you must stop JavaScript and TypeScript Nightly
![image](https://user-images.githubusercontent.com/58360393/233762503-a9e243e4-8397-4425-ad60-a0ef90e3818e.png)

**Comment by johnsoncodehk** [comment]
Please track #2663
