### ISSUE TITLE
Cannot find module './enUS.json' or its corresponding type declarations

### ISSUE THREAD

**Issue by coader** [vuejs/language-tools#2675]
I have a vue package with component library mode, and it export json as:
export { default as enUS } from './enUS.json'

after build, it genenate d.ts file but without the single json file in '/dist/'

when another project use this package, when check with vue-tsc
throw error:
Cannot find module './enUS.json' or its corresponding type declarations

**Comment by johnsoncodehk** [comment]
Can you provide repro case?
