### ISSUE TITLE
使用getCurrentInstance解构出proxy时,原本挂载在.d.ts上的属性全部失效

### ISSUE THREAD

**Issue by qhl123456** [vuejs/language-tools#2681]
![c453e640ebf1b174df31ecd939aeafd](https://user-images.githubusercontent.com/74643840/233815756-cdccc2d5-9d49-4699-a4bc-95284eace4b0.png)
![fe6a52e2f33c1c222eaa0c36b2a346d](https://user-images.githubusercontent.com/74643840/233815763-d4b830a9-3828-42c1-a745-eb4b6bc890e6.png)
![a310332b73a010f03154db2bb7930c9](https://user-images.githubusercontent.com/74643840/233815770-887b3e2b-10c7-4158-96b3-4b36b8790cb5.png)
volar版本：1.4.4
切换到1.2.0就恢复正常了

**Comment by johnsoncodehk** [comment]
Please provide repro case.
