### ISSUE TITLE
[Vue 2.7][v1.4.x] component slot type declaration not working any more 

### ISSUE THREAD

**Issue by kingyue737** [vuejs/language-tools#2682]
![image](https://user-images.githubusercontent.com/40021217/233819268-07d9f93f-5978-469a-8001-75e42d03e5c9.png)

`vue-tsc` cannot recognize any slot type of component and all the slot props become `never`

No such issue for version <=1.2

repro: https://github.com/kingyue737/volar-slot-prop-bug
component type is declared in `src/component.d.ts`
component `VDataTable` for testing type is added in template of `src/App.vue`

**Comment by CKATEPTb** [comment]
I have some problem with Vue3 in Intellij Idea. Maybe anyone has solution?

**Comment by ghiscoding** [comment]
I updated to `1.5.2` and that fixed it on my side, note that `1.5.2` is a pre-release and so it might not show in your list of updates. You can see all versions in the main [changelog](https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md) and their pre-release tag
