### ISSUE TITLE
TS2339 <Suspense> slot error in 1.5.0

### ISSUE THREAD

**Issue by 297cwrun** [vuejs/language-tools#2683]
![image](https://user-images.githubusercontent.com/37258929/233819421-3fbb4642-eef7-4a7b-8b76-2451b5d463cb.png)

never happen in 1.2

**Comment by k983551019** [comment]
+1
![image](https://user-images.githubusercontent.com/48147837/233833122-169bd9b7-a254-4928-9f47-9dfeb85e867b.png)

**Comment by k983551019** [comment]
.vue   
tsx
![image](https://user-images.githubusercontent.com/48147837/233833153-918163a7-b49d-4a07-9a8a-eebd0f0c8dcf.png)
