### ISSUE TITLE
Still has some problem with functional component

### ISSUE THREAD

**Issue by jerrywu001** [vuejs/language-tools#2686]
First of all, I appreciate your solution about (#2206), There is still a problem with the functional component.

See: https://github.com/jerrywu001/volar-issue#readme

You can go ahead and run my project to check the problem.

The correct(@0.40.x/@1.4.0 - @1.4.3 ):
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/12525415/207520016-d60c898a-7cdb-41fa-b018-8506836283db.png">

**But now**:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/12525415/218621835-db6297ea-fafd-45bb-9d22-a148a1db9fff.png">

**It work fine with 1.4.0 - 1.4.3, but always error with 1.5.0**

**Comment by johnsoncodehk** [comment]
This is a known limitation. I haven't found a way to generate virtual code while supporting general functional components with 1 parameter and 2 parameters.

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMQMIEYAueAHgBUA+ACgAcYka1iBveANyggFcRiyAadpx5N4ZANoBdeAF8AlPAC8FeFBQBPANwAoUJFgJk6LHgBMxctToNRrDt15jB9kXymzBYDAA9ia9QrKqho62gD0YfAA5iAoIDBQGAgA7gCWGAAW8KgIsFGCePjwyUgwANZo8ABGXCa4pvDAqGgA5Bja2oVUzNoAkC6O+KYAzPx9EfAAAhhoALQg3jTgGPMw9DB9A6ItQ8MtY-KhZt2bwoMjY70T03MLS16r66cO27v72ocdEzFxCUnF6SyGBKqhgUTQBXqxVKFWqtRwBEazTaHS6PX6Z2Iu0u1xm80Wy0epWerngOxG7xkgmYMlUlX8ciO9ROGIcWIu40iN3x9xW8SerNJ5L2B2ptKg9I0jO0QA

If we don't consider supporting general, it can be solved by simple type conversion.

**Comment by johnsoncodehk** [comment]
Okay, I found a way.

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMQMIEYAueAHgBUA+ACgAcYka1iBveANyggFcRiyAadpx5N4ZANoBdeAF8AlPAC8FeFBQBPANwAoUJFgJk6LHgBMxctToNRrDt15jB9kXymzBYDAA9ia9QrKqho6uuDQcPAAZlwoXgCWqNGxCaicuEgAtjSoICgYAIIwAOZoAEogmJZUGHxyfPAg3hh5wGjwtPSMfhqCAHQDsKXE8ShRIDDwZYEq-vAA-FPwxCggbBOhAPSb8MV5E1At8ADu8RgAFvC5qiXa2nj4VMzaAJAujvimAMz8r9vwAAEMGgALRNGjgDBgmD0GCvd6iADkny+iN+Mn6AxicQwiRQ6SyOVW+SKpQqmCoDzkclCZie8OEH2+vxe-yBoPBkOhsIZDiRKLR2gx8AGfWxqXxEAy2VyJJK5UqGEpuFM1K2Oz2qxghwQpwu8AwxyQN1Kdwe9LejOIKJZbOBYO8EK83KQcMtfOIyO+guFovFuLSUsJssK8vJSqpNLNKot72tzL+O3ZDqdUImPPdrngXtR6MxYpSAcl0qJeVDZMVytVUaAA
