### ISSUE TITLE
Property '*' does not exist on type 'Ref<*>' when try to bind attribute from a ref<> object

### ISSUE THREAD

**Issue by Vloz** [vuejs/language-tools#2687]
Injected object with ref<> attribute show an error in the editor when accessing whitout .value.

```
class WillInject{
public refed = ref<Foo>({atr:"test"});
}

<template>
{{injected.refed.atr}} <----- Works as intended but volar show an error: **Property 'atr' does not exist on type 'Ref<Foo>'**

{{injected.refed.value.atr}} <----- Doesnt work, but recommended way by volar
</template>
```

**Comment by polRk** [comment]
The same one. 

Monorepo:
- typescript : 5.3.0
- Vue.vscode-typescript-vue-plugin-1.8.10.vsix
- Vue.volar-1.8.10.vsix
- vue 3.3.4

**Comment by so1ve** [comment]
Any reproduction?

**Comment by blaze-rowland** [comment]
Having the same issue w/ version: 1.8.27
Upgrading any further and LSP doesn't work at all for vue files so stuck for now I suppose

**Comment by johnsoncodehk** [comment]
Closed as missing a suitable reproduction.
