### ISSUE TITLE
nuxt-link component not recognized in 1.5.1

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#2688]
Repo: https://github.com/rchl/nuxt-3-playground

1. Run `yarn`
2. Open `app.vue`

![Screenshot 2023-04-23 at 21 34 46](https://user-images.githubusercontent.com/153197/233861184-21e580fc-f31d-4f95-8239-e10a65fc6ba8.png)

Works in 1.4.4

**Comment by rchl** [comment]
BTW. Maybe slightly off-topic question but is there intention for Volar to detect a case when passing a non-existent prop to the component? For example in case of `nuxt-link` I would expect to see an error when passing a non-existent `xxx="/foo"` prop to it but Volar does not complain about it.

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/vuejs/language-tools/commit/eef20830f89ab91059aa302d4fc3e3fb68baf54e
