### ISSUE TITLE
In template, None of the components display information

### ISSUE THREAD

**Issue by Ddoudou** [vuejs/language-tools#2692]
like this
![image](https://user-images.githubusercontent.com/32379338/233885365-289937eb-4309-4c11-9601-8bad76cda712.png)

Is there something wrong with my configuration?

**Comment by johnsoncodehk** [comment]
It's `any` even in script, please forward to ant-design-vue repo

<img width="308" alt="image" src="https://user-images.githubusercontent.com/16279759/233888436-11f2d395-9cc3-458a-8d4f-ad1935a808fe.png">
.

**Comment by Ddoudou** [comment]
In my vscode, ant-design-vue component has type info
![image](https://user-images.githubusercontent.com/32379338/233889834-0b82291e-2dce-4d88-99ef-185524ef8d9e.png)
But in template has no any info.

And, not only antdv, every component (include my custom component) also has no info in template.
![image](https://user-images.githubusercontent.com/32379338/233890221-b6be424b-5dd4-4e69-b5fc-7646aaf93e83.png)
![image](https://user-images.githubusercontent.com/32379338/233890266-e110bc38-feef-4af3-a7c5-7b5f1bbafebb.png)

**Comment by johnsoncodehk** [comment]
Please provide repro case.

**Comment by Ddoudou** [comment]
In windows, its ok.
you can try it in WSL，use `pnpm create vite my-vue-app --template vue` create a project, it has the probblem

**Comment by johnsoncodehk** [comment]
I can see the type information now, but still can't reproduce the problem.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/16279759/233900281-d06f73b9-d74d-4b92-9516-3b07b0dbe17e.png">

**Comment by Ddoudou** [comment]
I ran the same project on Windows and WSL, no problem on Windows, and can reproduce this bug stably on WSL，maybe this bug is only for WSL
