### ISSUE TITLE
In template, None of the components display information 

### ISSUE THREAD

**Issue by mark3h** [vuejs/language-tools#2694]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/16110230/233890713-6bb74c30-b431-4858-aa20-aaf0fe9567a8.png">

<img width="841" alt="image" src="https://user-images.githubusercontent.com/16110230/233890727-2799ff3b-3ca1-4c8d-90bf-c654517a7158.png">

TypeScript Vue Plugin (Volar)
Vue Language Features (Volar)

v1.5.1 or v1.4.x or v.1.2.0 all of version

**Comment by johnsoncodehk** [comment]
I can't reproduce it in v1.5.1, please provide repro case.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/16279759/233891549-4c780d69-c7db-45a6-952b-2a56a689eeb5.png">

**Comment by MrWangJustToDo** [comment]
same issue for me

**Comment by mark3h** [comment]
解决了，最终执行了rm -rf ~/.vscode/extensions

把所有的插件都重新装了一次后，好用了。
