### ISSUE TITLE
add emmet check for `"vue-html": "html"`

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/language-tools#2696]
https://github.com/vuejs/language-tools/blob/eef20830f89ab91059aa302d4fc3e3fb68baf54e/packages/vscode-vue/src/features/doctor.ts#L196

This line says we can remove `"vue": "html"` from emmet.

maybe we can add the check that you can also remove: `"vue-html": "html"`

```json
  "emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue-html": "html"
  },
```

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion, but `"vue-html": "html"` won't affect Volar, it will only affect Vetur, so it doesn't matter if you don't remove it.
