### ISSUE TITLE
例如，当<template/>中，单独使用v-card 写法报错 ts(2551)，如果使用VCard写法或者混合使用则错误提示消失

### ISSUE THREAD

**Issue by UnforgetMemory** [vuejs/language-tools#2697]
**所遇问题/不解：**
当<template/>中，单独使用v-card 写法报错 ts(2551)，如果使用VCard写法或者混合使用则错误提示消失

**基础环境：**
vscode 
vue3
ts 4.9.5

**版本状况：**
插件版本 1.5.1 （预发布版本） （报错）
插件版本 1.4.4 （发布版本）（不报错 但是 此版本出现/* ts 默认导出 Props */历史错误）

外部第三方组件或者内部自写组件均出现此问题 

**个人开发基础**
菜鸟级

**Comment by johnsoncodehk** [comment]
Duplicate of #2688
