### ISSUE TITLE
vue-tsc 1.4.4 break attributes definitions on Transition component

### ISSUE THREAD

**Issue by parafeu** [vuejs/language-tools#2704]
Hello,

After the upgrade of vue-tsc from 1.2 to 1.4.4, I'm having a TS error when using the "tag" prop of Transition component.
Here is my code : 

```vue
<Transition
      class="y-toaster"
      :class="toastPositionClasses[position]"
      name="toast"
      mode="out-in"
      appear
      tag="div"
>
        [...]
</Transition>
```

Here is the build error : 
![image](https://user-images.githubusercontent.com/39409783/234011003-e2ed59eb-015b-47f5-99f6-48a8db2e8736.png)

Using :
 - Vue 3.2.47
 - Vite 4.3.1

**Comment by so1ve** [comment]
Does it work now? @parafeu

**Comment by johnsoncodehk** [comment]
Closed due to inability to reproduce.
