### ISSUE TITLE
Volar: Bracket Spacing settings and Auto-quotes not working in LiveShare

### ISSUE THREAD

**Issue by matvejs16** [vuejs/language-tools#2705]
After Issue #2663, I noticed that certain settings such as Bracket Spacing, and auto-quotes after @click= or v-for= stopped working during LiveShare sessions when I'm a client. These features were working correctly before the update to v1.4.2, but are no longer functioning correctly. However, they still work correctly when I'm the host.

**Comment by matvejs16** [comment]
I tried to install v1.4.4 (using "Install another version..." because I'm not able to use auto-update from v1.4.3 ( Issue #2699 )) and it throw me to 1.2.0 and in this version Bracket Spacing settings and Auto-quotes working correct in LiveShare session.

**Comment by johnsoncodehk** [comment]
- Is the Volar version of the client consistent with that of the host?
- Can you try the 1.5.2 pre-release?

**Comment by matvejs16** [comment]
> * Is the Volar version of the client consistent with that of the host?
In case v1.4.3 - yes, after changing to v1.2.0 on host there was v1.4.3

> * Can you try the 1.5.2 pre-release?
In v1.5.2 pre-release on client same behavior if host have v1.4.3 or v1.5.2 pre-release, nothing changed.

**Comment by matvejs16** [comment]
Also there is one more thing.
v1.2.0
![image](https://user-images.githubusercontent.com/74150728/234139392-0801b54c-520b-408f-a265-096fbd3a9c7d.png)

v1.5.2
![image](https://user-images.githubusercontent.com/74150728/234139477-740835d0-bda4-4b78-9d1f-77aad0a47626.png)

**Comment by matvejs16** [comment]
Any updates?

**Comment by matvejs16** [comment]
Update from me: This problem seems to be solved in VSCode Insiders, but still exist in VSCode Stable

**Comment by johnsoncodehk** [comment]
> Update from me: This problem seems to be solved in VSCode Insiders, but still exist in VSCode Stable

I'm assuming this has been resolved in the latest VSCode version, but if not please let me know.
