### ISSUE TITLE
New version >= 1.2 Volar lost the very useful auto-repair feature .

### ISSUE THREAD

**Issue by warmthsea** [vuejs/language-tools#2707]
![image](https://user-images.githubusercontent.com/45450994/234163443-00d9dc56-7ed2-48ef-b01f-897a9e89c852.png)
![image](https://user-images.githubusercontent.com/45450994/234163623-a9d89a08-835e-4eba-b6b4-b19f61a426b8.png)
![image](https://user-images.githubusercontent.com/45450994/234163897-1d1bce09-10bf-46bc-8032-3f7eff3e8ea0.png)

**Comment by johnsoncodehk** [comment]
Please provide a repro case.

**Comment by warmthsea** [comment]
2.0 is support.
