### ISSUE TITLE
"TS1002: Unterminated string literal" in slots

### ISSUE THREAD

**Issue by KaelWD** [vuejs/language-tools#2710]
Volar v1.5.2

```vue
<template>
  <v-data-table>
    <template #item.item>
      foo
    </template>
  </v-data-table>
</template>
```

Seems to have something to do with the first part of the slot name being repeated.

1.5.2 and 1.5.3 both output 
```js
__VLS_14.slots!["item>
     "];
```
I expect
```js
__VLS_14.slots!["item.item"];
```

**Comment by johnsoncodehk** [comment]
Hi, do you expect `__VLS_14.slots!["item.item"];` instead of `__VLS_14.slots!["item"];`?
