### ISSUE TITLE
Typescript takeover won't detect tsconfig in subdirectory.

### ISSUE THREAD

**Issue by bradlis7** [vuejs/language-tools#2711]
I have a git repo/folder containing multiple Nuxt modules. When I use Volar takeover mode, it can't resolve modules. I don't think Volar picks up the tsconfig.json files in the subfolders.

Resolution with VSCode's typescript service.

![image](https://user-images.githubusercontent.com/7062604/234302466-496fa330-758d-4278-b06f-f5fa0f6e2ab0.png)

With Volar takeover:

![image](https://user-images.githubusercontent.com/7062604/234302744-ee38063d-2f4b-459b-a2e6-c2c0126c963b.png)

![image](https://user-images.githubusercontent.com/7062604/234302895-e987e373-14be-47ce-83f0-e50f58bb199c.png)

**Comment by Aaron-Pool** [comment]
My team is experiencing this as well. We had to revert to an older version of volar temporarily.

**Comment by johnsoncodehk** [comment]
Can you share a repro case?
