### ISSUE TITLE
vue-tsc: Can't Stop Getting "Object is possibly 'undefined'" In a Template 

### ISSUE THREAD

**Issue by aronduby** [vuejs/language-tools#2713]
I have a SFC component and everything works great, but vue-tsc keeps throwing an error about a v-if expression saying that the object is possibly undefined, but it says that regardless of things I'm trying to do to handle it. I'll post the full SFC below but here's the variations of the expression I've used to try and address it, all to no avail:

```html
<div v-if="labResult.lab_result_lab_panel_id > 0"></div>
<div v-if="labResult!.lab_result_lab_panel_id > 0"></div>
<div v-if="(labResult?.lab_result_lab_panel_id ?? 0) > 0"></div>
```

I'm pretty sure there's something else going on because elsewhere in the component similar checks pass totally fine, and there's a similar v-else-if as a part of this that doesn't throw this error unless I reverse the order and put it first (which makes me think the v-else that this is nested in might be causing confusion).

Here's a simplified version that triggers, actual component if desired is available at [this gist](https://gist.github.com/aronduby/c8325643247e5dc6bb82638bbf5a7184)

```html
<template>
    <MainLayout>
        
        <input v-model="labResult.lab_result_lab_panel_id" type="number" class="bg-background-100" />
        <pre>{{ labResult }}</pre>
        
        <div v-if="labResult.lab_result_lab_panel_id > 0">
            <p>There's a panel id: <code>{{ labResult.lab_result_lab_panel_id }}</code></p>
        </div>
        <div v-else-if="labResult.lab_result_lab_panel_id === NO_PANEL_VALUE">
            <p>NO PANEL VALUE</p>
        </div>
    </MainLayout>

</template>

<script setup lang="ts">
    import MainLayout from "@/components/layouts/MainLayout.vue";
    import type { LabResult } from "@/types/items/LabResult";
    import { ref } from "vue";

    const NO_PANEL_VALUE = -1;
    const labResult = ref<Partial<LabResult>>({});
</script>
```

Windows 11
    "typescript": "~4.5.5",
    "vite": "^2.8.4",
    "vite-plugin-checker": "^0.5.3",
    "vite-plugin-html-env": "^1.1.1",
    "vue-tsc": "^1.0.16"

**Comment by johnsoncodehk** [comment]
Have you try update vue-tsc? The latest version is 1.4.4.

**Comment by aronduby** [comment]
have updated and no change

**Comment by johnsoncodehk** [comment]
`<div v-if="(labResult?.lab_result_lab_panel_id ?? 0) > 0"></div>` works for me, please provide repro case if you still can't get it work.

**Comment by aronduby** [comment]
Looks like I had some caching keeping things from going right after the upgrade. Have cleared that and looks like everything is working again. Thanks!
