### ISSUE TITLE
1.4.4+版本打包，node_modules中@volar/vue-language-core/out/generators/template.js中用到??=运算符，导致打包失败

### ISSUE THREAD

**Issue by Max-EnjoyCode** [vuejs/language-tools#2715]
我在使用1.4.4+版本的时候，vite打包时，提示??=是意外的错误，给出的错误地址是node_modules中@volar/vue-language-core/out/generators/template.js，这里面有一行代码：localVars[varName] ??= 0，因为用到了??=运算符，所以出现了这个报错，然后我切换到1.0.24版本后，打包成功了。

**Comment by mazhewei** [comment]
node升级到16试试

**Comment by johnsoncodehk** [comment]
Duplicate of #2643
