### ISSUE TITLE
🐞 Emmet expand selection doesn't work correctly inside SFC

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/language-tools#2716]
When we use "Expand Selection" & "shrink selection" commands from vscode inside template tag, it doesn't work same as html file or react files like tsx.

Vue SFC vs `index.html`:

https://user-images.githubusercontent.com/47495003/234516144-97bdef8e-b06d-4803-886a-95fd5932e814.mov

Testing snippet:
```html
<template>
  <p>crm</p>
  <div>
    <p>crm</p>
  </div>
  <p>crm</p>
</template>
```

**Comment by dennis-damico** [comment]
Would love to see this fixed as well.

the "Balance (outward)" command works for tags, but there's no quick way to select strings/props, or things inside {{}} (which expand selection should cover all of i'd think)

**Comment by johnsoncodehk** [comment]
Closed due to inability to reproduce this issue in the latest version.
