### ISSUE TITLE
Specify Vue Library

### ISSUE THREAD

**Issue by heywhy** [vuejs/language-tools#2722]
Currently, the vue-language-core assumes that everyone uses Vue, so, it does not cater for projects that make use of a custom renderer.

I will suggest that one is allowed to specify the package to use as part of tsconfig. What this means is that, the below function either makes use of the specified `vueLibrary` (see https://github.com/nativescript-vue/nativescript-vue/pull/1038) or default to vue. 

https://github.com/vuejs/language-tools/blob/b16292c8eccdff475384ba2d41ca5c07647aa0a2/packages/vue-language-core/src/utils/shared.ts#L6

**Comment by johnsoncodehk** [comment]
Do you think "lib" would be a better option name?

**Comment by heywhy** [comment]
@johnsoncodehk Thank you for the updates, hopefully, we get a new release soon. Also, I will like to mention that you missed extending this new feat to the `optionsWrapper` option, see below:

https://github.com/vuejs/language-tools/blob/b8ae905a9ece4aa375ea41db941dbf36be2fdd08/packages/vue-language-core/src/utils/ts.ts#L185-L189

Instead of `import('vue')` we should be having `import('${resolvedLib}')`
