### ISSUE TITLE
Imports of Vue SFC not recognized unless ".vue" added to import

### ISSUE THREAD

**Issue by Preston-Landers** [vuejs/language-tools#2724]
I've got an existing large Vue 2 project, that is itself added on to a preexisting Python project. I'm using webpack to compile things and working entirely with single file components (.vue files). I've been working primarily out of PyCharm but I'm trying to get VS Code with Volar working on this project. Everything is working fine when developing under PyCharm, in terms of my paths being recognized etc.

After some tinkering, for the most part, everything seems to work in VS Code. However one issue I'm running into is that Volar doesn't recognize import statements of my SFC Vue components unless I add ".vue" to the end. For instance, this works fine in PyCharm and webpack:

```
// This is a .vue file
import MyHappyComponent from "~/components/MyHappyComponent"

// This is a .js file:
import myJSLib from "~/js/myJSLib" 
```

Under Volar, it doesn't recognize any of the Vue SFC imports unless I add `.vue` to the end. The JS imports work fine w/o an extension.

```
// Add .vue and it works
import MyHappyComponent from "~/components/MyHappyComponent.vue"

// Still works:
import myJSLib from "~/js/myJSLib" 
```

I'd really prefer not to have to go change every import line in every Vue file if possible. This seems like it should be something that works. Any ideas are appreciated.

```
// volar.config.js at project root
module.exports = {
  settings: {
    "vetur.useWorkspaceDependencies": true,
    "vetur.experimental.templateInterpolationService": true,
    "vetur.experimentalCompatMode": 2,
  },
  projects: [
    {
      root: "./jx/static",
      jsconfig: "./jsconfig.json",
      package: "../../package.json",
    },
  ],
}
```

```
// jsconfig.json at project root
// note that `jx/static` path is the root of all JS and Vue files
{
  "compilerOptions": {
    "baseUrl": "./jx/static",
    "traceResolution": true,
    "paths": {
      "~/*": ["./*"]
    }
  },
  "include": ["jx/static/**/*"],
  "exclude": ["node_modules", "wtp", "dist"]
}
```

Setting these options doesn't show much of anything interesting:
```
  "vue-semantic-server.trace.server": "messages",
  "vue-syntactic-server.trace.server": "messages"
```

**Comment by vidal7** [comment]
I think Volar should have a setting to not add an extension with the auto-import feature. This will work with the moduleSuffixes typescript config. https://www.typescriptlang.org/tsconfig#moduleSuffixes

We have a big code base with thousands of composants and we are converting progressively components from non SFC vue-class-component to SFC options API and to convert progressively, we need to trick typescript to priorise a file with ts extension sometime instead of vue extension. So our imports of vue components are always extensionless.

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar-starter/pull/10#issuecomment-1436077234

**Comment by vidal7** [comment]
@johnsoncodehk, does my comment change something? You posted your last comment in the same timeframe of mine. I was wondering if you have read it before closing this issue.

**Comment by johnsoncodehk** [comment]
Vue 3 no longer supports this, and it's now considered bad design, which is a big reason why Volar decided not to be backwards compatible with this behavior. Thanks for pointing out `moduleSuffixes`, I thought it was helpful to some people.

**Comment by vidal7** [comment]
I understand for Vue 3 but in my case, we are still in Vue 2.7 and my partial tsconfig setting is like that

```json
"moduleSuffixes": [
            "",
            ".vue"
        ]
```

We are migrating non SFC vue-class-component to SFC options API with defineComponent.
