### ISSUE TITLE
TypeError when using ternary operator in <component>

### ISSUE THREAD

**Issue by ymy0622** [vuejs/language-tools#2725]
```vue
<script setup lang="ts">
import { ref } from 'vue';

const flag = ref(true);
</script>

<template>
  <div>
    <Component :is="flag ? 'ComA' : 'ComB'" />
    <Component :is="!flag ? 'ComA' : 'ComB'" style="background: pink" />
  </div>
</template>
```

> ComA & ComB are global registration

![image](https://user-images.githubusercontent.com/54923146/234742558-75783039-7986-4c60-aabb-76205cc2efb8.png)

Repro repo: https://stackblitz.com/edit/vitejs-vite-uonfzg?file=package.json

**Comment by jiikoosol** [comment]
I have the same problem.

**Comment by lihanspace** [comment]
![image](https://user-images.githubusercontent.com/60546798/234789592-c8db3047-88dc-4787-98f3-d3041f4aff10.png)

**Comment by jiikoosol** [comment]
In my case this was the solution. So basically I had to define the returning type of the computed property which is used to define the dynamic component type. It also works with `as any` or just `as Component`.

```
<template>
  <component :is="myComponent"></component>
</template>

<script setup lang="ts">
import { computed, ref, type Component } from "vue";
import type MyComponent from "@/components/MyComponent.vue";

const someCondition = ref(true);

const myComponent = computed(() =>
  someCondition.value ? "my-component-name" : undefined
) as Component<typeof MyComponent>;
</script>
```

**Comment by lihanspace** [comment]
I have rolled back the version of vue-tsc to v1.5.2
