### ISSUE TITLE
ERROR(vue-tsc)  Property 'propname' does not exist on type 'AppConfig'.

### ISSUE THREAD

**Issue by lovkyndig** [vuejs/language-tools#2727]
I love to run `vue-tsc` and get msg about errors on startup with `yarn dev`.
The problem in the last few months is the error-msg above in the header.
To continue to use vue-tsc I have chosen to move all my server-constants to another file.

But maybe the best way is to quit using vue-tsc.
The error is not showing on `yarn dev`.
It is only on `yarn build` the errors is showing up.

Today I discovered that the message can be shown on `dev` if `defineAppConfig` is imported in `app.config.ts` - like this:
```
import { defineAppConfig } from '~/node_modules/nuxt/dist/core/runtime/nitro/config'
export default defineAppConfig({
  propname: {
    obj1: 'aaa',
    obj2: 'bbb',
    ....
  } 
})
```
As you now Nuxt3 imports everything automatic. But something is wrong here, and the only way to get the error on `dev` instead of `build` is import manually.

I have cloned [BlogiNote](https://github.com/Benbinbin/BlogiNote) and added `vue-tsc` to my repo. And I'm also using `typescript < 5.0.0`.

## .nuxt/types/app.config.d.ts:
```
import type { CustomAppConfig } from 'nuxt/schema'
import type { Defu } from 'defu'
import cfg0 from "C:/Users/Public/kirkepostille/app.config"

declare const inlineConfig = {}
type ResolvedAppConfig = Defu<typeof inlineConfig, [typeof cfg0]>
type IsAny<T> = 0 extends 1 & T ? true : false

type MergedAppConfig<Resolved extends Record<string, any>, Custom extends Record<string, any>> = {
  [K in keyof Resolved]: K extends keyof Custom
    ? IsAny<Custom[K]> extends true
      ? Resolved[K]
      : Custom[K] extends Record<string, any>
        ? Resolved[K] extends Record<string, any>
          ? MergedAppConfig<Resolved[K], Custom[K]>
          : Exclude<Custom[K], undefined>
        : Exclude<Custom[K], undefined>
    : Resolved[K]
}

declare module 'nuxt/schema' {
  interface AppConfig extends MergedAppConfig<ResolvedAppConfig, CustomAppConfig> { }
}
declare module '@nuxt/schema' {
  interface AppConfig extends MergedAppConfig<ResolvedAppConfig, CustomAppConfig> { }
}
```

Here is my [repo](https://github.com/lovkyndig/kirkepostille) where I'm using constants from another file (instead of app.config.ts).

**Comment by lovkyndig** [comment]
I fixed this by myself with inspiration from `nuxt3 Doc` about [`Typescript`](https://nuxt.com/docs/guide/directory-structure/app-config).

I defined the types manually, and the errors disappear.
## types/index.d.ts
```
declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Constant configuration */
    propname?: {
      /**Objects */
      obj1?: string,
      obj2?: string
    }
  }
}

export {}
```

**Comment by so1ve** [comment]
I guess it's nuxt's bug :(

**Comment by lovkyndig** [comment]
I'm closing this issue. 
I think this errors is code that have getting loose from the Matrix. They are alive, come and go like the want to trought hidden gateways. Properly living a real life 1000 years in the future.
