### ISSUE TITLE
After upgrading to 1.6, clicking on the function will no longer automatically redirect

### ISSUE THREAD

**Issue by meguoe** [vuejs/language-tools#2728]
After upgrading to 1.6, clicking on the function will no longer automatically redirect, such as the handleCancel() function below, where command+left click has no response

<Modal
      v-model:visible="visible"
      :width="520"
      :confirm-loading="loading"
      @cancel="handleCancel()"
>

**Comment by ymy0622** [comment]
try to restart vscode?

**Comment by meguoe** [comment]
版本: 1.76.2
提交: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
日期: 2023-03-14T17:54:09.061Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.4.0
沙盒化: No

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, please provide minimal reproduction.

**Comment by meguoe** [comment]
> I can't reproduce this problem, please provide minimal reproduction.

After upgrading vscode to version 1.77.3, the issue was resolved

版本: 1.77.3
提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
日期: 2023-04-12T09:19:37.325Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.4.0
沙盒化: Yes
