### ISSUE TITLE
How to override native tags' types and support `uni-app` types in 1.6.0?

### ISSUE THREAD

**Issue by ModyQyW** [vuejs/language-tools#2729]
I am using `nativeTags` in [uni-app-types](https://github.com/uni-helper/uni-app-types), overriding native tags' types and supporting [uni-app](https://uniapp.dcloud.net.cn/) types.

But I notice `nativeTags` has been removed in 1.6.0. How can I do the same things with 1.6.0? Could you please give me some advice? Thanks!

<img width="742" alt="image" src="https://user-images.githubusercontent.com/31850793/234778657-43308faf-a546-4094-b6c7-0ce5afca311b.png">

**Comment by hequ9** [comment]
im facing the same problam and i didn't find a options that would replace `nativeTags`.

**Comment by johnsoncodehk** [comment]
Did you encounter any problems with the uni-app project using v1.6? Is it possible to override the `JSX.IntrinsicElements` type definition to solve it?

**Comment by ModyQyW** [comment]
> Did you encounter any problems with the uni-app project using v1.6?

Yes. Many elements in `uni-app` have lost their type even with `uni-app-types` since `nativeTags` is deprecated.

> Is it possible to override the `JSX.IntrinsicElements` type definition to solve it?

Yes! I will soon publish a new version for `uni-app-types`. Thanks for saving my life ♥️

**Comment by ModyQyW** [comment]
@johnsoncodehk Sorry, I am reopening it.

I tried quickly and I found overriding `JSX.IntrinsicElements` work. 

But when I published a new version for `uni-app-types` and tried again, I found it not working. 

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/234813593-174e396d-fd27-4018-ac6e-7c8d9ff5602e.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/234814590-7006b8f5-4828-4d14-83dc-39302d2541d2.png">

If you are looking for a demo, [here](https://github.com/MillCloud/presets/tree/main/uni-app)  is mine.

**Comment by johnsoncodehk** [comment]
`IntrinsicElements` definition should not be capital, changes these lines works to me.

```diff
declare module '@vue/runtime-core' {
    interface GlobalComponents {
-        View: _View;
    }
}
declare global {
    namespace JSX {
        interface IntrinsicElements {
-            View: _View;
+            view: _View;
        }
    }
}
```

**Comment by ModyQyW** [comment]
Thank you!!!!

**Comment by ModyQyW** [comment]
@johnsoncodehk Hi. Sorry to reopen this issue again.

vue3.3 is out and `uni-app-types` does not work again. I am not sure if it is caused by vue language-tools 1.6 reading 'vue/jsx-runtime' but not 'vue/jsx.d.ts'.

<img width="1549" alt="image" src="https://github.com/vuejs/language-tools/assets/31850793/90a612a1-7ad8-4a78-acef-740b4d5bfe06">


I have tried to override `@vue/runtime-dom` but not working, too. Can you please give me some advice? Thanks!!!! 🙏

<img width="1920" alt="image" src="https://github.com/vuejs/language-tools/assets/31850793/d967736e-f50d-4769-8f09-e2e44a4fd106">

**Comment by ModyQyW** [comment]
I overrode `vue/jsx-runtime` and it worked... Not sure if it is correct or not...
