### ISSUE TITLE
how to disable emmet.

### ISSUE THREAD

**Issue by EvanMeek** [vuejs/language-tools#2733]
I dont need emmet, how to disable it?

**Comment by so1ve** [comment]
PLEASE, DO A LITTLE SEARCH BEFORE CREATING AN ISSUE.
```json
"emmet.showExpandedAbbreviation": "never"
```

**Comment by EvanMeek** [comment]
> 

This is vscode configuration?  Maybe some words in my description are not expressive. Is there a way to turn off using initializationOptions? I didn't find any documentation on this.

**Comment by so1ve** [comment]
> > 
> 
> This is vscode configuration? Maybe some words in my description are not expressive. Is there a way to turn off using lsp initializationOptions? I didn't find any documentation on this.

Yes it is vscode configuration. I don't know much about volar lsp, sorry.

**Comment by johnsoncodehk** [comment]
The language client should provide settings via [Configuration Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) handler.

**Comment by EvanMeek** [comment]
> The language client should provide settings via [Configuration Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) handler.

It needs to provide a ConfigurationItem. What is the name of the section that closes emmet? Is there any documentation about the switch options for this feature? Thank you.

**Comment by yaegassy** [comment]
@EvanMeek Try setting `emmet.showExpandedAbbreviation` by interpreting it based on the settings of the language client you are using.

You're probably using Neovim's built-in LSP, so in that case, it would be the `settings`.

**Comment by bytecodevet** [comment]
Hello everyone. I also ran into trouble in neovim with this volar, when I got tired of these $0, $1, I went to study the language-service code.
I looked at the code and saw that emmet is added to the lsp without the possibility of deletion...
(https://github.com/vuejs/language-tools/blob/master/packages/language-service/index.ts **207 line**).
emmet does not depend on configurations in any way and is added anyway.

And I deleted this definition (yes, I know it's bad to change someone else's code... but I'm already tired of these $0, $1...)

So the solution is:
let's look at where the vue-language-server sources are located.:
(If you are using neovim + mason, then you should run a command in the terminal inside neovim)
```bash
where vue-language-server
# output
~/.local/share/nvim/mason/bin/vue-language-server
```
so we have to edit this file.:
{output}/../packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/language-service/index.js, and find something related to emmet:
```js
(0, volar_service_emmet_1.create)({
 mappedLanguages: {
 'vue-root-tags': 'html',
 'postcss': 'scss',
 },
 }),
```
delete it, And that's it!
