### ISSUE TITLE
Generic component throws errors

### ISSUE THREAD

**Issue by StepanMynarik** [vuejs/language-tools#2738]
My generic components started throwing errors like "**Unexpected ","**" or "**Unterminated string literal**" after the **Volar** extension and **vue-tsc** package 1.6.0 update (at least I believe this was the trigger).

I have managed to create a repro project (based on '_npm init vue@latest_' from today), which is attached to this issue.

Just try '_npm run dev_'. Aforementioned errors will be thrown on build/startup.

Also look at the **CList** component, that's the generic one in question and the only custom component within the project.
Also the **vue-tsc** package was updated from vanilla 1.2.0 to 1.6.0 to reproduce the issue.

[vue-project.zip](https://github.com/vuejs/language-tools/files/11343091/vue-project.zip)

EDIT:
Interesting discovery - the errors are thrown only when using **<** or **>** chars inside the _generic_ attribute.
If you try replacing ```generic="TItem extends Item<TValue>, TValue"``` with ```generic="TItem extends SimpleItem"``` inside the **CList** component then the errors disappear.

**Comment by johnsoncodehk** [comment]
This is not the compiler but not the `vue-tsc` problem, please report it for upstream.

**Comment by StepanMynarik** [comment]
@johnsoncodehk I'm sorry I'm not sure I follow. Upstream should be the original repo language-tools was forked from? Which one is that?

**Comment by johnsoncodehk** [comment]
It's https://github.com/vuejs/core
