### ISSUE TITLE
Syntax colorating and typings stops working since 1.6.0

### ISSUE THREAD

**Issue by vidal7** [vuejs/language-tools#2742]
Hello. I have this problem since version 1.6.0. I have no more syntax coloring in vscode and typescript type of component seems to be of type any.
![image](https://user-images.githubusercontent.com/33458053/234858195-6e39808c-3017-40ef-88ce-ab4e9aaa9adb.png)

In version 1.4.4, everything was working fine
![image](https://user-images.githubusercontent.com/33458053/234857630-83f264fc-a96d-4048-96c3-8f0bfc7f311c.png)

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, please provide minimal reproduction.

**Comment by WAJoakimB** [comment]
Same issue. Prop types are shown as any when hovering over them. Also not getting all Vue warnings/errors in Visual Code, e.g. when a required prop is missing for a child component. No problem in 1.4.4.

**Comment by vidal7** [comment]
@johnsoncodehk, here is a reproduction repo https://github.com/vidal7/volar-issue-2742

**Comment by xzhangi** [comment]
I have the same issue, and tried downgrading version by version. Apparently the issue does not exist in 1.5.2 and only started appearing in 1.5.3 onwards

VSCode version - 1.76.2

**Comment by johnsoncodehk** [comment]
I reproduced it and this happens when using TS 4.8.

**Comment by vidal7** [comment]
@johnsoncodehk you are right.

TS 4.8.3 is not working
TS 4.9.5 is not working
TS 5.0.4 is working

**Comment by vidal7** [comment]
Wow! You are a super human @johnsoncodehk. Thank you for fixing it so fast!
