### ISSUE TITLE
👀 Default doesn't get generated if we import props & defaults from another file

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/language-tools#2753]
Reproduction: https://github.com/jd-solanki/volar-vue-playground/tree/props-sharing-test

> _Make sure you are in props-sharing-test branch_

> **Note**
> I'm at vue 3.3 beta2

**Steps:**
1. Open in vscode
2. Go to `Foo.vue` component
3. Show trigger show component meta command
4. Notice no default for that component

<img src="https://media.discordapp.net/attachments/899997215530029076/1101192492923236372/image.png?width=589&height=630" />

I guess this is same if we use vue-component-meta package.

**Comment by johnsoncodehk** [comment]
This is expected behavior, see https://github.com/vuejs/language-tools/tree/master/packages/vue-component-meta#default-value.

You can do this with:

```ts
const props = withDefaults(defineProps<FooProps>(), {
    color: 'primary',
    ...fooPropsDefaults,
})
```

**Comment by adamdehaven** [comment]
@johnsoncodehk is it possible to update this functionality to support [reactive props destructuring](https://vuejs.org/guide/components/props.html#reactive-props-destructure) that was introduced in `vue@3.5+`?

Ideally, I'd like to be able to access the `default` prop value without needing to utilize `withDefaults`
