### ISSUE TITLE
Incorrect destructured type seems to be passed to v-for value, throws ts(2339) error

### ISSUE THREAD

**Issue by MajesticPotatoe** [vuejs/language-tools#3102]
**Environment:**
OS: OSX 13.3.1 (22E261)
Vue Language Features (Volar) Version: v1.6.2
TypeScript Vue Plugin (Volar) Version: v1.6.2

in v 1.6.1 the following code works:
```html
<script setup lang="ts">
  type Item = {
    id: number,
    text: string
  }
  const items = ref(null as null | Item[])
</script>

<template>
  <div
    v-for="item in items"
    :key="item?.id"
  >
    <div>{{ item?.id }}</div>
    <div>{{ item?.text }}</div>
  </div>
</template>
```

`items` has its correct type of `Item[] | null`, and `item` has the type of `Item`, no error is thrown.
in v1.6.2, `item` is receiving the inferred type of `never` and throwing  `Property '' does not exist on type 'never'. ts(2339)`
![Screenshot 2023-05-01 at 3 52 42 PM](https://user-images.githubusercontent.com/27827979/235519804-ff108c70-254d-4806-8ed0-bf65b5a4291f.png)

**Workaround**
Revert to version 1.6.1 of Vue Language Features (Volar).

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/vuejs/language-tools/commit/83e9ece4a97d5b1b28fb9997547db409266e8085
