### ISSUE TITLE
[Bug] Components exported by `GlobalComponents` interface have no type hints

### ISSUE THREAD

**Issue by Trezedo** [vuejs/language-tools#3107]
## Enviroments & packages:
- VS Code: 1.77.3
- Volar: 1.6.3
- vue-tsc: 1.6.3
- vue: 3.2.47
- typescript: 5.0.4

## Description

Actually I'm using `unplugin-vue-components/vite` to generate dts file:
```ts
// src/components.d.ts
export {};
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyUpload: typeof import('./components/MyUpload/index.vue')['default'];
  }
}
```
The type of component we obtain is `any`:
![image](https://user-images.githubusercontent.com/75014380/235590033-cdcc2114-56f8-4db8-86da-3f1624e2f0a4.png)

However, when we change `'@vue/runtime-core'` to `'vue'`, the type hinting works correctly：

```diff
- declare module '@vue/runtime-core' {
+ declare module 'vue' {
```

![image](https://user-images.githubusercontent.com/75014380/235591306-c85312fe-d142-4a8c-ad2e-6d58384f2f74.png)

**Comment by so1ve** [comment]
Try to downgrade to v1.4.4

**Comment by so1ve** [comment]
Closed because this issue has been fixed in https://github.com/antfu/unplugin-vue-components/pull/638.
