### ISSUE TITLE
`vue-tsc` `key` error on `Transition` component

### ISSUE THREAD

**Issue by Jasenkoo** [vuejs/language-tools#3109]
When the `key` prop is set on the `Transition` component, `vue-tsc` reports:

```sh
Object literal may only specify known properties, and 'key' does not exist in type 'TransitionProps'.
```

![Screenshot 2023-05-02 133042](https://user-images.githubusercontent.com/23171105/235654744-4d79f41c-715b-42e2-850f-41e6f7305b7a.png)

Right now, I am locked on `v1.4.3` , from `v1.5` this started appearing in both typescript `^4` and `^5`.

**Comment by jack-worman** [comment]
I have confirmed that the problem exists `>=1.4.4`

**Comment by johnsoncodehk** [comment]
Closed due to unable to reproduce in latest version.
