### ISSUE TITLE
Typing component Blocks.

### ISSUE THREAD

**Issue by louiss0** [vuejs/language-tools#3110]
I was talking to the maintainer of `vite-plugin-nested-sfc` He said that it's not possible to type Component Blocks.

> Regarding this plugin's component tag, it's handled by Volar and it's not something that can be controlled currently. The same goes for the lang attribute, it's not possible to make it HTML by default, Volar depends on it to highlight the syntax correctly.
The tooling plugin that's added to your tsconfig can only handle what's inside the <component> tag, it cannot control the props suggestions of the <component> tag itself nor their default values. 
-- Hun-Yan-io

This means that you cannot type special blocks in Vue using Volar. There has to be an API implementation made to address this problem. This is what I was talking about https://github.com/HunYan-io/vite-plugin-vue-nested-sfc/issues/2

**Comment by so1ve** [comment]
You can use a Language Plugin to do that.

**Comment by louiss0** [comment]
> You can use a Language Plugin to do that.

Can you tell min please. I was speaking for him.

**Comment by so1ve** [comment]
Here is an example: https://github.com/vuejs/language-tools/blob/a03aae46636ee373fad39d5dd1a4dfc3c8cf1681/packages/language-core/src/plugins/vue-sfc-customblocks.ts#L21
