### ISSUE TITLE
[Vue 2.7] model not supported ?

### ISSUE THREAD

**Issue by stephane303** [vuejs/language-tools#3113]
I have a prop using model (https://v2.vuejs.org/v2/api/#model) like so:
```<script lang="ts">

import { defineComponent } from "vue";

export default defineComponent({
  model: {
    prop: "msg",
    event: "update",
  },
  props: {
    msg: {
      type: Number,
      required:true
    }
  },
});
</script>
```
  
  But I get the error when using it:
![image](https://user-images.githubusercontent.com/1409706/235872466-19379450-5a6c-4be7-97d5-06f067aad56e.png)

Argument of type '{ value: number; }' is not assignable to parameter of type 'Readonly<Partial<{}> & Omit<Readonly<ExtractPropTypes<{ msg: { type: NumberConstructor; required: true; }; }>>, never>> & Record<...>'.
  Property 'msg' is missing in type '{ value: number; }' but required in type 'Readonly<Partial<{}> & Omit<Readonly<ExtractPropTypes<{ msg: { type: NumberConstructor; required: true; }; }>>, never>>'.

**Comment by kachidk** [comment]
It says the msg prop is missing.

**Comment by stephane303** [comment]
I, but it shouldn't as I used model (https://v2.vuejs.org/v2/api/#model) to rename the value to msg.

**Comment by y4n6** [comment]
I am also using Vue version 2.7 and encountered the same issue with ts(2345). I thought it was a problem with my code or the version of the dependent package, and it took me an hour to locate the reason.

Additionally, I also found that it even affects the validation of vue-tsc. My project cannot pass vue-tsc at the moment.

**Comment by y4n6** [comment]
I rolled back the version of Volar to 1.2.0 to solve this problem.

**Comment by rchl** [comment]
Seems like a limitation in Volar. It does have this experimental setting though that can be used to globally define the name of the model property per component-name. In this case it would be something like this in `tsconfig.json`:

```jsonc
{
  "vueCompilerOptions": {
    "experimentalModelPropName": {
      "msg": {
        "hello-world": true,
      }
    }
  }
}
```

**Comment by ShGKme** [comment]
Is this setting still supported?
