### ISSUE TITLE
Neovim LSP set Take-over typescript preferences

### ISSUE THREAD

**Issue by xxSkyy** [vuejs/language-tools#3115]
Are there possibility to pass preferences to `take-over` typescript server through volar? When project has `vue` package typescript server is disabled so volar handles all `.ts` and `.vue` files. 

I wanted to make preference to always use `non-relative` than `shortest` for `importModuleSpecifier` preference and for typescript LSP it works like a charm by passing 
```lua
    init_options = {
      preferences = {
        importModuleSpecifierPreference = "non-relative"
      }
    }
```
init options to tsserver setup.

I've tried many ways of passing it throught volar but none of them worked.
 
Minimal code:
```lua
require 'lspconfig'.volar.setup {
  capabilities = neovim.capabilities,
  filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue', 'json' },
  root_dir = require 'lspconfig'.util.root_pattern("package.json"),
  on_new_config = function(new_config, new_root_dir)
    new_config.init_options.typescript = {
      tsdk = get_typescript_server_path(
        new_root_dir),
      -- Don't work
      preferences = {
        importModuleSpecifierPreference = "non-relative"
      }
    }
  end,
}
```
I've investigated source code of LSP and couldn't find any way of passing preferences. Is it currently possible?

**Comment by johnsoncodehk** [comment]
You should provide TS settings via [Configuration Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration).

**Comment by xxSkyy** [comment]
Thanks for quick resposne, according to [LSP docs](https://github.com/neovim/neovim/blob/f3bbc92476df1112deb34b9c7408cd594ee47a50/runtime/doc/lsp.txt#L758) I had to create `settings` table with following structure
```
  settings = {
    typescript = {
      preferences = {
        importModuleSpecifier = "non-relative"
      }
    }
  },
```
and now it's all good. Thank you!
