### ISSUE TITLE
SVG component attributes type inference error after upgrading to version 1.6.2

### ISSUE THREAD

**Issue by Mini-ghost** [vuejs/language-tools#3123]
## Version

vue: 3.3.0-beta.3 and 3.2.47
vue-tsc: 1.6.2
typescript: 5.0.4

## Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-vn2tf8?terminal=dev

## Description

After upgrading vue-tsc to version 1.6.2, the type checking fails, whereas version 1.2.0 passes.

I load SVG files as Vue components via `vite-svg-loader`, and pass `fill-opacity` attribute to set UI style.

```vue
<script setup lang="ts">
import VueSvg from './assets/vue.svg?component';
</script>

<template>
  <div>
    <VueSvg fill-opacity="0.5" />
  </div>
</template>
```

When I check the type through vue-tsc, it will produce an error:

```
src/App.vue:11:43 - error TS2345: Argument of type '{ width: string; class: string; fillOpacity: string; "fill-opacity": string; }' is not assignable to parameter of type 'SVGAttributes'.
  Object literal may only specify known properties, but 'fillOpacity' does not exist in type 'SVGAttributes'. Did you mean to write 'fill-opacity'?

11       <VueSvg width="96" class="logo vue" fill-opacity="0.9" />
                                             ~~~~~~~~~~~~~~~~~~
```

This issue did not exist in version 1.2.0.

**Comment by Ragura** [comment]
The same happens to me when using a component of type `FunctionalComponent<SVGAttributes, {}>`.
When trying to pass the attribute `data-testid` it gives me the same kind of error, saying the property does not exist in the `SVGAttributees`.
I'm sorry I don't have a simple reproduction in this case, it is part of a large project that I can't easily extract.

**Comment by radusuciu** [comment]
I also hit this error (see: https://github.com/antfu/unplugin-icons/issues/285). I was able to isolate to `vue-tsc` 1.4.4.

Repro with 1.4.4 and failing build: https://stackblitz.com/edit/vitejs-vite-dwhdqp?file=package.json
Repro with 1.4.3 and passing build: https://stackblitz.com/edit/vitejs-vite-2zx4vc?file=package.json

In my case, I was setting the `font-size` property on an `Icon` component from [`unplugin-icons`](https://github.com/antfu/unplugin-icons), but I've been able to reproduce it with any multi-word SVG presentation attribute.

The error persists with later versions of `vue-tsc`. I tried: `1.6.5`, `1.5.4`, `1.5.0`, and `1.4.4` all failing with the same error. On the other hand, `1.2.0`, `1.4.0`, and `1.4.3` did not result in any errors.

Taking a look at the [diff between `1.4.4` and `1.4.3`](https://github.com/vuejs/language-tools/compare/v1.4.3...v1.4.4), nothing really stands out to me, but I suspect that maybe this issue/regression was introduced in one of these commits:
- https://github.com/vuejs/language-tools/commit/e5e2349bcef622960a29b58490047ceb5505ab88
- https://github.com/vuejs/language-tools/commit/b0ace74cc38fe5ae4d7015fbc99001f57550f5c6

The other two commits that were made between those two versions update the changelog and bump the version. Unfortunately I don't understand `vue-tsc` internals sufficiently to see how the changes made impact the behavior described in this issue.

**Comment by Sengulair** [comment]
The same happens if I try to use template refs for the SVG component. I'm not sure if I should create a new issue because the reason seems similar.
```vue
<template>
  <StopIcon ref="myRef" />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import StopIcon from '@/assets/svg/StopIcon.svg?component';

const myRef = ref(null);
</script>
```
And here is the `vue-tsc` error:
```
src/App.vue:2:13 - error TS2345: Argument of type '{ ref: string; }' is not assignable to parameter of type 'SVGAttributes'.
  Object literal may only specify known properties, but 'ref' does not exist in type 'SVGAttributes'. Did you mean to write 'href'?

2   <StopIcon ref="myRef" />
```

**Comment by Mini-ghost** [comment]
This bug still appeared in version 1.8.0, is there any solution to this problem? Or is this actually the expected result?

**Comment by tangtangtangtangtang** [comment]
meet the same error, what is the solution..

**Comment by xiaoxiangmoe** [comment]
Hi, all,  here is a temp solution: change your tsconfig's vueCompilerOptions.htmlAttributes

```json
{
  "vueCompilerOptions": {
    "strictTemplates": true,
    "htmlAttributes": [
      "aria-*",
      "data-*",
      "aria-activedescendant",
      "aria-atomic",
      "aria-autocomplete",
      "aria-busy",
      "aria-checked",
      "aria-colcount",
      "aria-colindex",
      "aria-colspan",
      "aria-controls",
      "aria-current",
      "aria-describedby",
      "aria-details",
      "aria-disabled",
      "aria-dropeffect",
      "aria-errormessage",
      "aria-expanded",
      "aria-flowto",
      "aria-grabbed",
      "aria-haspopup",
      "aria-hidden",
      "aria-invalid",
      "aria-keyshortcuts",
      "aria-label",
      "aria-labelledby",
      "aria-level",
      "aria-live",
      "aria-modal",
      "aria-multiline",
      "aria-multiselectable",
      "aria-orientation",
      "aria-owns",
      "aria-placeholder",
      "aria-posinset",
      "aria-pressed",
      "aria-readonly",
      "aria-relevant",
      "aria-required",
      "aria-roledescription",
      "aria-rowcount",
      "aria-rowindex",
      "aria-rowspan",
      "aria-selected",
      "aria-setsize",
      "aria-sort",
      "aria-valuemax",
      "aria-valuemin",
      "aria-valuenow",
      "aria-valuetext",
      "accent-height",
      "alignment-baseline",
      "arabic-form",
      "baseline-shift",
      "cap-height",
      "clip-path",
      "clip-rule",
      "color-interpolation",
      "color-interpolation-filters",
      "color-profile",
      "color-rendering",
      "dominant-baseline",
      "enable-background",
      "fill-opacity",
      "fill-rule",
      "flood-color",
      "flood-opacity",
      "font-family",
      "font-size",
      "font-size-adjust",
      "font-stretch",
      "font-style",
      "font-variant",
      "font-weight",
      "glyph-name",
      "glyph-orientation-horizontal",
      "glyph-orientation-vertical",
      "horiz-adv-x",
      "horiz-origin-x",
      "image-rendering",
      "letter-spacing",
      "lighting-color",
      "marker-end",
      "marker-mid",
      "marker-start",
      "overline-position",
      "overline-thickness",
      "paint-order",
      "panose-1",
      "pointer-events",
      "shape-rendering",
      "stop-color",
      "stop-opacity",
      "strikethrough-position",
      "strikethrough-thickness",
      "stroke-dasharray",
      "stroke-dashoffset",
      "stroke-linecap",
      "stroke-linejoin",
      "stroke-miterlimit",
      "stroke-opacity",
      "stroke-width",
      "text-anchor",
      "text-decoration",
      "text-rendering",
      "underline-position",
      "underline-thickness",
      "unicode-bidi",
      "unicode-range",
      "unitsPer-em",
      "v-alphabetic",
      "vector-effect",
      "vert-adv-y",
      "vert-origin-x",
      "vert-origin-y",
      "v-hanging",
      "v-ideographic",
      "v-mathematical",
      "word-spacing",
      "writing-mode",
      "x-height"
    ]
  }
}
```

**Comment by johnsoncodehk** [comment]
Closed due to unable to reproduce in latest version.
