### ISSUE TITLE
SyntaxError: Unexpected token '??=' in @volar/vue-language-core/out/generators/template.js

### ISSUE THREAD

**Issue by pol-albert** [vuejs/language-tools#3124]
Hello, I cannot execute
`./node_modules/.bin/vue-tsc`

It gives me the following error : 
```
/node_modules/@volar/vue-language-core/out/generators/template.js:203
                        tagOffsetsMap[tag] ??= [];
                                           ^^^

SyntaxError: Unexpected token '??='
```

Please ask me if you need additional informations... but I don't think it's stack dependant since it also happens when I call the binary directly, I'm I wrong ?

**Comment by pol-albert** [comment]
Doesn't it look like it doesn't interpret the script file as TS but just as simple JS ?

**Comment by 1gn0r4nd** [comment]
Getting the same issue after having upgraded my vite from 3.x to 4.x

**Comment by a-bean** [comment]
?? =      nodejs version > 16 is supported.

**Comment by chaselen** [comment]
> ?? = nodejs version > 16 is supported.

I downgrade vue-tsc to `"vue-tsc": "1.2.1"` instead

**Comment by acastillo9** [comment]
upgrading to node > 16 solve the problem

**Comment by xiaoxiangmoe** [comment]
Hi all, the end-of-life date for Node.js 14 is [April 30, 2023](https://nodejs.org/en/about/releases/).
So please update your node runtime to Node.js 16 or Node.js 18.

Close this issue.
If more help is needed, feel free to comment below.
