### ISSUE TITLE
error on vuejs dynamic component

### ISSUE THREAD

**Issue by hi-reeve** [vuejs/language-tools#3129]
the current version is showing an error when we use the built-in vuejs component.
<img width="781" alt="image" src="https://user-images.githubusercontent.com/45350572/236392299-d2917853-985c-4cac-bfda-cb34678f3d3b.png">

usage is with nuxt 3.

**Comment by fanckush** [comment]
I get the same error:
``` 
Argument of type '{ class: string; style: {}; }' is not assignable to parameter of type 'never'.ts(2345)
```

**Comment by exherb** [comment]
some here.

**Comment by pont1s** [comment]
i have the same problem

**Comment by ldsenow** [comment]
Lucky and also unlucky that i'm not alone.

**Comment by hi-reeve** [comment]
@johnsoncodehk

**Comment by so1ve** [comment]
Are you using dynamic components? Could you please provide a minimal reproduction? 👏

**Comment by hi-reeve** [comment]
> Maybe related to #3138

is this issue won't be fix? it's been a few months now

**Comment by so1ve** [comment]
> is this issue won't be fix? it's been a few months now

> Are you using dynamic components? Could you please provide a minimal reproduction? 👏

Without reproduction nobody can debug this issue 😅

**Comment by johnsoncodehk** [comment]
Closed due to unable to reproduce in latest version.
