### ISSUE TITLE
Component intellisense supressed

### ISSUE THREAD

**Issue by louiss0** [vuejs/language-tools#3132]
I was testing out vue nested sfc and have noticed that the `<component  />` element's intelisense is suppressed when using it. The component is supposed to expect an `:is=` prop. I'm getting no indication of this. I was told by the creator of vue-nested-sfc that I would get an error from Volar for not passing in the right prop. But I did not. 

**Link to minimal reproducible example:**
https://github.com/louiss0/vue-nested-sfc-test

**Comment by johnsoncodehk** [comment]
Closed due to repro being inaccessible, if you still have this problem, please open a new issue.
