### ISSUE TITLE
How to ignore files in vue-tsc type check?

### ISSUE THREAD

**Issue by citrusjunoss** [vuejs/language-tools#3144]
When using vue-tsc for type checking in a Vue project, is it possible to ignore certain files or directories from being checked? I have some files that are generated at build time and don't need to be type checked.

I tried modifying the tsconfig.json file by adding an exclude property to exclude those files, but it doesn't seem to work. The files are still being checked.

Is there a way to properly configure vue-tsc to ignore certain files or directories during type checking? Any help would be appreciated. Thanks!

**Comment by DrJume** [comment]
Using `exclude` in a tsconfig.json with (vue-tsc -p tsconfig.json) doesn't seem to work...

**Comment by binaryfire** [comment]
I'm having this problem too. I need to exclude several subdirectories and all *.test.ts files but it seems like `exclude` in tsconfig.json is being ignored

**Comment by PavelGonzales** [comment]
I have the same problem. `vue-tsc` checks swagger excluded folder.

**Comment by blouflashdb** [comment]
Would also like to exclude some files/directories from vue-tsc type checking.

**Comment by illegalnumbers** [comment]
I also have this problem.

**Comment by cjbathras** [comment]
I'm having the same issue. Adding to `exclude` in `tsconfig.json` doesn't work. It is failing on a third party library I don't have control over.

**Comment by rchl** [comment]
`exclude` can affect `includes` or `files` but it can't affect that are explicitly imported or referenced in the `included` files. That's the same behavior as for typescript itself.

**Comment by KyleBrown-804** [comment]
+1 having the same issue

**Comment by pollux2021** [comment]
+1 having the same issue

**Comment by vlafranca** [comment]
I was able to ignore some directory of my app by manually including the directory I wanted my vue files to be checked.

```json
{
  "extends": "./tsconfig.json",
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/*.vue",
    "src/components/subdirectoryIwantToTypeCheck/**/*.vue",
  ],
  "exclude": ["../backend/**", "../libraries/**"],
  "vueCompilerOptions": {
    "target": 2.7
  }
}

```

then `npx vue-tsc --noEmit -p tsconfig.vue-tsc.json` is type checking only my `subdirectoryIwantToTypeCheck` directory vue files.

**Comment by johnsoncodehk** [comment]
Closed since answered at https://github.com/vuejs/language-tools/issues/3144#issuecomment-1875414251.
