### ISSUE TITLE
Error is reported when defining a component using the `script setup` method.

### ISSUE THREAD

**Issue by coderwyd** [vuejs/language-tools#3146]
![图片](https://user-images.githubusercontent.com/53386850/236975602-5f87dfc3-2f06-44d9-abb2-9373829544f5.png)
![图片](https://user-images.githubusercontent.com/53386850/236975634-6610e3c4-25df-4f4a-8fa6-dcabda0fccb3.png)

**Comment by coderwyd** [comment]
Volar version 1.6.4

**Comment by Tanimodori** [comment]
This may be a issue with [vuejs/vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser).

**Comment by coderwyd** [comment]
> This may be a issue with [vuejs/vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser). What's your eslint configuration?

Thanks, then I'll go under  [vuejs/vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser) and mention one.
