### ISSUE TITLE
running vue-tsc with 1.7 takes 5min instead of 1.5min

### ISSUE THREAD

**Issue by Fuzzyma** [vuejs/language-tools#3148]
I recently updated from vue-tsc v1.2 to the prereleased 1.7 and my ci went up from only 1.5min to a whopping 5min.

Since since is surely not by design, I wonder what changed that makes it so slow and if that is expected.

I will update this ticket with a more narrow version constraint to see with which version it got so slow

// EDIT:
The time increase happens from version 1.5 to version 1.5.1.

These are the changes made between the versions:
https://github.com/vuejs/language-tools/compare/v1.5.0...v1.5.1

Exact commit that caused it:
https://github.com/vuejs/language-tools/commit/6d8829980981b04f6ce69462e47c6be5825088b3

**Comment by douira** [comment]
This should probably be reopened since the PR that closed this was reverted since it didn't fix this issue.
