### ISSUE TITLE
goto definition in template not working

### ISSUE THREAD

**Issue by edison1105** [vuejs/language-tools#3154]
## language-tools version
v1.6.4

## vscode insider version
v1.79.0-insider

## Steps to reproduce
![image](https://github.com/vuejs/language-tools/assets/3705199/244b7e76-81e5-4f21-ad6d-948400edb8e2)

## minimal reproduction
a fresh repo use volar-starter template: https://github.com/edison1105/volar-goto-definition-in-template

## What is expected?
- CMD + left click `HelloWorld` will open HelloWorld.vue
- CMD + left click `msg` will open HelloWorld.vue and locate the definition of msg

## additional comments
Not sure if it's already supported or a new feature.

**Comment by so1ve** [comment]
Does it work now?

**Comment by edison1105** [comment]
> Does it work now?

Not sure. I just switched to WebStorm as u know.

**Comment by so1ve** [comment]
Yeah, in my machine it works now 😃 Close this issue for now!

**Comment by so1ve** [comment]
Hey @danwall, I see you reacted with 👎. Does this issue still exist?
