### ISSUE TITLE
components type error in 1.6.4 | 1.7.1

### ISSUE THREAD

**Issue by laterdayi** [vuejs/language-tools#3155]
```js
不能将类型“{ type: string; onClick: () => Promise<void>; }”分配给类型“IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>”。
  类型“IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>”上不存在属性“type”。ts(2322)
```

```
<NTag type={isLast ? 'ok' : 'false'} onClick={() =>{}}>
   test
</NTag>
```

in 1.2.0  ,it`s ok

**Comment by xiaoxiangmoe** [comment]
@laterdayi Hi, can you provide me a minimal reproduction?

**Comment by laterdayi** [comment]
@xiaoxiangmoe   @johnsoncodehk  This is a repeat of a similar question provided yesterday
    https://play.vuejs.org/#eNrtV1tv2zYU/iuE9pIANnWxLMuZU3Tx2iCDtw7N+jIYCDSJltlIpEBSsYci/32HpO3Ikh04zYq+9CHO4bl850qK/OL8UlX4oSbOhTORqaCVQpKoukJFwvLLuaPkeu68mbOUM6mQICwj4gYW6BKdnaPLN+jLnCHgq1owdKZphCagr/8DJR/yLY3QuiyYBMylUtWF665WK7waYC5yN/A8z9W6Tkv7Yl1Qdn/Qxh+Px64RN60WtChAnXFGTNxb/iQjC9lYA6dK1BLRDLQ1defNHaREwuSCi1JnrukiUeTMQ945ElxZOgzRwDsHZW35u9eLvFkcb369mWf+Iu9vUHD3/UFoiogmC1n3VnDnD5qJmBKAEMLaZ/57iLmimVqCIAzbkiWh+VKByPc6Muv4E6NKt6WWRNxWSUo+sE8Sqrevm/KCiz5lYFBxKAvlrG/tta38eH21V2+bMXlfcJ6hhf7tc8CmahM+jIysCx3XVZLe54LXLLspk5y8pzBwrdIZqKsChg+VPCOmv6JMClCkDFa3vBYpuRZJtaSpYQbHgHdu5TKpIMlDnq6TWkqasKuiFkiq7FfyQE3CYBYMmyBksSCp8u9gZIh1pW26rXdtpV44D+DqtfPgxx3RbiC6s/JjHr7nPOhT6MA0mMPJb5f/xJMqDOGk2rc0x1bo9QI88GdjHI97/hhH4+kIh34v8LEfoKHmBgM8ijZkhKNgZsjIx4N4askQByEyZlGE4xgZsCjWuIAfDzVqGOAw7sUjDRsO8TDY0sDUCrNRjH0A0FbT2MNDQDBgcWD4xseG1q5nljYRTTe0CdTa2vgtpklrBo50plPr3NPQNiZL2jrAad0s0gsP7rDTnZdv1OPb1I+iH/v01fsUvq3/xzaduK17xCRHT/WBOXhuYz7tTN/z0EhfIvb9nYY1ANsm2MhDUQfrBZGBcQNte71poX1tpkfhALBM5L3dSJrq6+naXN9WS6r2728NM5h3ZO59F0tBFqD90+7+1h4K2zKN3k3HzdsF63JObMi4lXOEh/bk/doiBp0iHoZ7RVeOAX4TyG6zNe4JzX6u4RriUMOfafrhNh/jtnn76+Zqoh8vm9XExnT+85w9wt+cgdA8rIANC0XKStcPVhN3t3B6Di0rLlS/TCr8WXIGDzLztJpvBHLuXNjHlubBi02v7btIwsMozRiYZaSgDwIzolxWle5bUHNFzRQtST/j5dsBHuDQzahUTTYmsuz/I/gKPiQAMnd6DTcuMB+I6NunH3wGT3TbMmu6bok67rX3R6geFEVJeGsuaN4qScrLihZEfKj08b5fmqQo+Oo3w1OiJrtc0iVJ7w/wP+sXrs7pT/g+6Mga+atE5ERZ8bvbP8ga6J0QPml1sWnDEeFHInlR6xit2hV8aiDshp6J9sZ0mLL8L/lurQiT26R0oKYaRt/0Y/pM6k/hQrV3VXz8D+cpfao=

**Comment by laterdayi** [comment]
[include](javascript:;)  https://github.com/vuejs/language-tools/issues/3301
