### ISSUE TITLE
Volar encounters errors when coexisting with JavaScript and TypeScript Nightly.

### ISSUE THREAD

**Issue by atlansien** [vuejs/language-tools#3160]
### Environment
- Nuxt Version: 3.4.2
- volar Version: 1.6.3
- JavaScript and TypeScript Nightly Version: v5.1.20230510　

### Describe the bug

I registered a helper from the plugin with reference to [document](https://nuxt.com/docs/guide/directory-structure/plugins#automatically-providing-helpers)

plugins/helllo.ts
```js
export default defineNuxtPlugin(() => {
  const hoge = (message: string) => `hello ${message}`;

  return {
    provide: {
      hoge
    }
  }
})
```
Later, when I used it in PAGE, the type was `unknown`.

app.vue
```js
<script setup lang="ts">
  const { $hoge } = useNuxtApp();
</script>

<template>
  <div>
    <h1>
      {{ $hoge('msg') }}
    </h1>
  </div>
</template>
```
message
```
'__VLS_ctx.$hoge'' is of type 'unknown' ts(18046)
```

### solution
By disabling JavaScript and TypeScript Nightly, we have managed to restore normal functionality.

**Comment by xiaoxiangmoe** [comment]
Can you provide a minimal reproducible example to help us find some clue?
