### ISSUE TITLE
How to ignore files when using vue-tsc? tsconfig.json doe not work.

### ISSUE THREAD

**Issue by adoin** [vuejs/language-tools#3161]
For now it can not ignore style and class on components, so that I had to try some ignore ways. But adding path to tsconfig.json is not working.

**Comment by xiaoxiangmoe** [comment]
Can you provide me a reproductive demo? It maybe TypeScript's limit, but I'm not sure.

**Comment by adoin** [comment]
> Can you provide me a reproductive demo? It maybe TypeScript's limit, but I'm not sure.

好滴 我整个看看

**Comment by adoin** [comment]
> Can you provide me a reproductive demo? It maybe TypeScript's limit, but I'm not sure.

Here is the demo.
[code sandbox](https://codesandbox.io/p/sandbox/vue3-vite-typescript-sass-forked-luyz63?file=%2Ftsconfig.json%3A45%2C28)

**Comment by xiaoxiangmoe** [comment]
This is TypeScript's limit.

For example: you can remove file `HelloWorld.vue`, and add file `HelloWorld.vue.ts`

```ts
// file HelloWorld.vue.ts
declare const HelloWorld: new () => {
    $props: {}
}
export default HelloWorld;

const thisLineHasTypeError: string = 114514;
```

and then exclude file `HelloWorld.vue.ts` in `tsconfig.json`, you will still find type error.

**Comment by xiaoxiangmoe** [comment]
Close this issue.
You can go to https://github.com/microsoft/TypeScript/issues to create a issue.
If more help is needed, feel free to comment below.

**Comment by adoin** [comment]
Thx.
&nbsp;


adoin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHAO ***@***.***&gt;; 
发送时间: 2023年5月12日(星期五) 中午12:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vuejs/language-tools] How to ignore files when using vue-tsc? tsconfig.json doe not work. (Issue #3161)





 
Close this issue.
 You can go to https://github.com/microsoft/TypeScript/issues to create a issue.
 If more help is needed, feel free to comment below.
 
&mdash;
