### ISSUE TITLE
Non-null assertions can only be used in TypeScript files.ts(8013)

### ISSUE THREAD

**Issue by Doston777** [vuejs/language-tools#3163]
https://github.com/microsoft/vscode/issues/181630

We have a new issue with new updated version of VS Code:
https://github.com/microsoft/vscode/issues/181630#issuecomment-1540687359

**Comment by Hobeein** [comment]
https://github.com/microsoft/vscode/issues/181630#issuecomment-1537061653

Need Help

**Comment by johnsoncodehk** [comment]
Duplicate of #3121
