### ISSUE TITLE
Generics: Cannot find name 'T'.

### ISSUE THREAD

**Issue by metkm** [vuejs/language-tools#3164]
I've created a repository with this error.
https://github.com/metkm/generic-issue

Volar versions I have installed:
Vue Language Features (Volar) v1.2.0
TypeScript Vue Plugin (Volar) v1.6.4

![image](https://github.com/vuejs/language-tools/assets/54271295/a719fa0e-c123-40cc-b45d-e66ba45734ad)

**Comment by metkm** [comment]
Also when I switch to pre-release version on both extensions defineModel macro is overwriting the defineProps macro.
```
<script setup lang="ts" generic="T">
defineProps<{
  num: number
}>()
const modelValue = defineModel<T>();
</script>
```
this gives `Argument of type '{ num: number; }' is not assignable to parameter of type '{ modelValue?: unknown; } & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
  Object literal may only specify known properties, and 'num' does not exist in type '{ modelValue?: unknown; } & VNodeProps & AllowedComponentProps & ComponentCustomProps'.`
  
  
![image](https://github.com/vuejs/language-tools/assets/54271295/d0d62db3-06a8-427b-a954-a39a314038bc)

**Comment by metkm** [comment]
It looks like the second error is fixed on the pre-release version, but the first issue still persists on the release version.

**Comment by zf1998** [comment]
Update vue to @3.3.x, vue-tsc to @1.6.x , See [detail](https://blog.vuejs.org/posts/vue-3-3#generic-components) .

**Comment by thimonwentink** [comment]
@zf1998 I'm running into the same problem and have exactly the package versions you mention (vue 3.3.4 and vue-tsc 1.6.5)

**Comment by localusercamp** [comment]
same here

**Comment by metkm** [comment]
> Update vue to @3.3.x, vue-tsc to @1.6.x , See [detail](https://blog.vuejs.org/posts/vue-3-3#generic-components) .

It doesn't work, please try if it works first

**Comment by zf1998** [comment]
I update vue to @3.3.4, vue-tsc to @1.6.5, using webstorm development, manually point the typescript directory to vue-tsc. 

Suggest using vue-tsc to check for type errors on the command line, to help us determine if the editor plugin and vue-tsc type check results are the same
