### ISSUE TITLE
New v3.3 syntax for `defineEmits` does not work

### ISSUE THREAD

**Issue by rodrigocfd** [vuejs/language-tools#3169]
Vue 3.3 introduced a [new syntax](https://blog.vuejs.org/posts/vue-3-3) for [`defineEmits`](https://vuejs.org/api/sfc-script-setup.html#type-only-props-emit-declarations):

```ts
const emit = defineEmits<{
  'update:modelValue': [id: number];
  foo: [value: string];
}>();
```

Which is not supported by Volar yet.

**Comment by Noxdor** [comment]
Could you describe more in which way you are realising this issue? For me, type definitions when defining emits with the new syntax are not working properly. I falsely published that [here](https://github.com/vuejs/eslint-plugin-vue/issues/2176) but I think it has to do with the current version of volar LSP not being up to date with Vue 3.3.

**Comment by rodrigocfd** [comment]
> Could you describe more in which way you are realising this issue?

I just tried the new syntax, and it didn't work... just that.

**Comment by jdk2pq** [comment]
I'm seeing the same issue when I try to use the new `defineEmits` syntax and run `vue-tsc --noEmit` as part of my pre-commit hook. I get errors like these:

```typescript
error TS2344: Type 'Emits' does not satisfy the constraint '((...args: any[]) => any) | Record<string, any[]>'.
```

when doing something like

```typescript
interface Emits {
    someEmit: [value: string];
}

const emits = defineEmits<Emits>();
```

and this error:

```typescript
Argument of type 'string' is not assignable to parameter of type 'Emits'.
```

when trying:

```typescript
emits('someEmit', value);
```

**Comment by rodrigocfd** [comment]
It's working now, apparently after the last [vue/core](https://github.com/vuejs/core) 3.3.2 release.

**Comment by Noxdor** [comment]
I am on 3.3.2 and the issue is not fixed for me, I will open a new issue then.

**Comment by jdk2pq** [comment]
@Noxdor can confirm. still a problem for me on Vue 3.3.4 and vue-tsc 1.7.8

**Comment by mauricewegner** [comment]
Autocompletion with the new syntax is currently missing as well.

<img width="400" alt="image" src="https://github.com/vuejs/language-tools/assets/53715854/0ce2c79c-828a-4dda-a0f9-9b5317123f73">

**Comment by so1ve** [comment]
#3283
