### ISSUE TITLE
Composition API return object documentation not inferred

### ISSUE THREAD

**Issue by jmroon** [vuejs/language-tools#3170]
When using a setup store in pinia, documentation for state, getters, and actions are not inferred.

i.e.

Options Store:
```ts
const useCountOptionStore = defineStore('countOption', {
  state: () => ({
    /**
     * Count State
     */
    count: 0,
  }),
  actions: {
    /**
     * Increment the count
     */
    increment() {
      this.count++
    },
  },
})
```

![image](https://github.com/vuejs/language-tools/assets/36086006/35abe69f-1e71-4afe-a043-425a8d083c52)

Setup Store:
```ts
const useCountSetupStore = defineStore('countSetup', () => {
  /**
   * Count State
   */
  const count = ref(0)

  /**
   * Increment the count
   */
  function increment() {
    count.value++
  }

  return {
    count,
    increment,
  }
})
```

![image](https://github.com/vuejs/language-tools/assets/36086006/97e6b3d2-b617-45f8-a0d5-8d85419c4e0f)

The only way to get the setup store documentation to work is by putting it on the return object, as such:

```ts
const useCountSetupStore = defineStore('countSetup', () => {
  const count = ref(0)

  function increment() {
    count.value++
  }

  return {

    /**
    * Count State
    */
    count,

    /**
    * Increment the count
    */
    increment,
  }
})
```

![image](https://github.com/vuejs/language-tools/assets/36086006/bddb8118-f99b-4535-9572-8b0255d9c726)

I'm not sure if this is simply a limitation of Typescript. For what it's worth, Webstorm is able to infer the documentation.

**Comment by jmroon** [comment]
Upon further inspection, this appears to extend to all of the composition API. 

For example, as written, VueUse's documentation is completely absent from Intellisense.

**Comment by so1ve** [comment]
This is not an issue with language-tools, this is an issue with how the Composition API you use implements type definition. Please post this issue in Pinia / other repositories.
