### ISSUE TITLE
Volar is making false errors on vuetify components

### ISSUE THREAD

**Issue by dhallX** [vuejs/language-tools#3175]
when I add volar to my project i get a strange errors on the components from vuetify. according to the documentation on vuetify I have the correct syntex? maybe I need to change something in setting but don't know what.

![image](https://github.com/vuejs/language-tools/assets/106660145/309d5d00-d4d2-448a-94b0-fba87098c225)

![image](https://github.com/vuejs/language-tools/assets/106660145/4d7362ce-7835-4ac9-8604-4b2c5d575b08)

![image](https://github.com/vuejs/language-tools/assets/106660145/740d1b4c-983d-451a-8504-3d696e0a4bca)

**Comment by rchl** [comment]
Closing per comment above.
