### ISSUE TITLE
Not-required props type declaration should be optional.

### ISSUE THREAD

**Issue by lseeker** [vuejs/language-tools#3177]
### Vue version

3.3.1

### Link to minimal reproduction

https://play.vuejs.org/#eNqdUk1vnDAQ/StTHworAVaUG2W3qXrpvYdeLFUUZndp8Edss0mE+O8ZG4LIRsohHLDnvbHfvBmP7IcxxWVAVrLKNbYzHhz6wRyE6qTR1sMIFo8wwdFqCQmlJiv1U0uz4AUPQeEdsUI1WjkP0p1gH06nyS/sew1/tO3bL8lOqIrPYiRDgUdp+tojRQDV+eYwjvHwNFWcooh2ygweLrnULfZ7wYgXbKZiGZz2Fd/cxDI2l5nL2hT/nVbkcQwHxEI4wUqISMDIWYgFO3tvXMn5oMz9qWi05HfEcTso30nMWy3vbovb4oa3nfNbuEAn839WPzq0JChYtrmbE3hBm1tULVq0H2pd5W71rqh3mkFyEmoi+8tEyPY6yhaPncJAaIXKZ3B+M9lvYRz4FJMptR76uG6PpEEgNVYbt4P9AdL4P6eJSTIYpwwiVXh88rvof2lwhNd2A4SETUjAs8ESfnvbqdPSuPAtZZTw9g1tMiw+DJ3FtoRj3TtcmWnZzWv478jfa1/auTMtNn1tEeYX+3dVmx2uBc7VulgcXTLBV/IandfqmYCrnr3es9FrtLXY+E/ofv+k8PQCqvBJ3Q==

### Steps to reproduce

Compile Comp.ts with tsc or vue-tsc.

### What is expected?

*text* props should optional on Comp.d.ts

```typescript
declare const _default: (props: {
    text?: string;
} & {}) => any;
export default _default;
```

### What is actually happening?

Using Comp on other vue file, Vue Language Feature marks &lt;Comp /&gt; as error *Property 'text' is missing in type*
*text* props is not optional.

```typescript
declare const _default: (props: {
    text: string;
} & {}) => any;
export default _default;
```

### Any additional comments?

Occurs not only *ComponentObjectPropsOptions*, but also array props. Optional props is not respected on type declaration.

**Comment by lseeker** [comment]
@yyx990803 I figure out it occurs by @vue/runtime-core's typescript declaration.

```typescript
export declare function defineComponent<Props extends Record<string, any>, E extends EmitsOptions = {}, EE extends string = string, S extends SlotsType = {}>(setup: (props: Props, ctx: SetupContext<E, S>) => RenderFunction | Promise<RenderFunction>, options?: Pick<ComponentOptions, 'name' | 'inheritAttrs'> & {
    props?: (keyof Props)[];
    emits?: E | EE[];
    slots?: S;
}): (props: Props & EmitsToProps<E>) => any;
export declare function defineComponent<Props extends Record<string, any>, E extends EmitsOptions = {}, EE extends string = string, S extends SlotsType = {}>(setup: (props: Props, ctx: SetupContext<E, S>) => RenderFunction | Promise<RenderFunction>, options?: Pick<ComponentOptions, 'name' | 'inheritAttrs'> & {
    props?: ComponentObjectPropsOptions<Props>;
    emits?: E | EE[];
    slots?: S;
}): (props: Props & EmitsToProps<E>) => any;
```

(keyof Props)[] or ComponentObjectPropsOptions<Props> doesn't respect optional property.

**Comment by xiaoxiangmoe** [comment]
@yyx990803 Compile `Comp.ts` with `tsc` also has this result, Maybe this is vue/core 's issue.

**Comment by dten** [comment]
Also hitting this :)

the type of the props does not think it's optional even if you add ` | undefined` in the PropType

![image](https://github.com/vuejs/language-tools/assets/1019038/74d171cc-f6e2-4bef-8598-6f54def6c706)

https://play.vuejs.org/#eNqNU01v2zAM/SuELk0Azzn0ZjgBtqGH7bAWXY++aDadOFMkjZKzDFn++0g5dZyh3aqLRfLx6fHDR/Xe+3zfoypUGWrqfASj7XpZqRgqtapst/OOIhzhgZx/+uUxgwbbzuJHxxGLNsIJWnI7uGGamzFBwo9oG6RzNF9cXPIiQ/GQoMyne5O+U97ZsbIA9bMZChYxYT1llT3NK1suBt2slY2IO290RLYASkl+Rwm/KhdTS/JGrMq42trZtlvn2+AsNyO9XSlJ6QzSvY+ds9wRFiERiWlj3M/PyRepR5Yz+OsN1t9f8G/DQXyVeiAMSHus1BiLmtYYh/Dd1y944PsY3LmmN4z+R/ARgzO9aBxgH3rbsOwJLqn9lGbT2fVTuDtEtOG5KBEqSGmqoHk+0urXSr/Ivc1vUx7Pgrt4PeHXdoreslUZbDIgbK+3i1P/szQCEZEzz8xhDssVyz775PCYQ4S9NrAU+gGWa9GRs3c+xRLGnizMEstmNg1zo863K/bEJo2a+OQk/hf8ciKXX8D9ty3WEXQYW1IeRWYBIRJPjPvwG3iqqdxmNT4/PYQ/+o6wKaDVJvDm/YW5iL62+Dfi2/gjqdMfhYBUzA==

**Comment by johnsoncodehk** [comment]
Close as this is a upstream issue.

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5YwA0cAFnAL5zpQFwDkAbgK6pMDcAUDwMZEAzvHzg4AXhQZseApGIwAFDwCQSsAzBCAlJIB8cJXomGKSpmCbkE1cpojaAdDFQAPGDtJqEa1Q+0ALkQ-VVcPYN9VaLCATzBUYIBlGChsAHNvGNU0dABDNgAbGGCmAAlUQsKIOAB1aELkAEJrUNUoVABHNmAO5GD8wqFULOi7P3HVcZ1eHiUcAHc4MTAlWzg8oQ2sWJ0dJwASAKEXdxheAHoLuBvbu-uHh4A9AH44cJK4ETSsdKMsCDwRwwYBEPKFHQ8IA
