### ISSUE TITLE
I can't upgrade to 1.6.4 

### ISSUE THREAD

**Issue by louiss0** [vuejs/language-tools#3180]
For some reason when I try to upgrade to 1.6.4. I keep getting redirected to 1.2.0. I decided to upgrade to a pre-release version. 
Every time I install Volar I'm forced to be on 1.2.0. It's even advertised as well.

**What volar looks like when I'm first trying to install it**
  
![Screenshot 2023-05-12 102925](https://github.com/vuejs/language-tools/assets/29028601/48bb09ee-d544-41f8-a460-b7c97272d203)

I had to switch to a pre-release version. 

This is what my versioning screen looks like. 

![Screenshot 2023-05-12 103223](https://github.com/vuejs/language-tools/assets/29028601/62883375-bf16-4bfe-a66a-c4f8da0ba07b)

**Comment by so1ve** [comment]
I think it is a vscode issue
