### ISSUE TITLE
Cant upgrade to 1.6.4

### ISSUE THREAD

**Issue by louiss0** [vuejs/language-tools#3181]
Type: <b>Bug</b>

1. Go to volar you'll see that it's on 1.2.0.
2. Click on install vsersion. 
3. You'll see multiple versions pop-up. 
4. Click on 1.6.4 
 
What ypou will see is that it will keep making you go to 1.2.0 and in the listing it will say that 1.2.0 is current. 

Extension version: 1.7.2
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz (8 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.27GB free)|
|Process Argv|--crash-reporter-id 1c092d58-6cbb-453c-b2f1-8be075281019|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixhidewlkth:30730051
showsbindicator:30730056

```

</details>

**Comment by louiss0** [comment]
For more information please click on tnis https://github.com/vuejs/language-tools/issues/3180

**Comment by kingyue737** [comment]
I also encountered this issue. Switching from pre-release v1.7 to stable will go to v1.2.0 instead of v1.6.5

**Comment by louiss0** [comment]
> I also encountered this issue. Switching from pre-release v1.7 to stable will go to v1.2.0 instead of v1.6.5

Thanks for the advice I did it.
