### ISSUE TITLE
Cannot register 'typescript.tsdk'. This property is already registered.

### ISSUE THREAD

**Issue by henrychea** [vuejs/language-tools#3182]
Issue only when using VS code Insiders Edition

![image](https://github.com/vuejs/language-tools/assets/40254517/4b4ce89e-1372-4285-9006-8de603d62105)

Just load in any Vue project to see this error

https://github.com/henrychea/volar-vuejs2-ts-check-issue-repoduce

**Comment by bitmonti** [comment]
Same issue using vscode --lts (1.78.2)

**Comment by so1ve** [comment]
It is not a bug. The property is register to let volar get the tsdk path when the built-in typescript language extension is disabled and takeover mode is enabled.

**Comment by so1ve** [comment]
duplicate of #2422

**Comment by henrychea** [comment]
Thanks I just thought something was wrong @so1ve
