### ISSUE TITLE
Visual Studio Code - Insiders Component Syntax Not Working

### ISSUE THREAD

**Issue by henrychea** [vuejs/language-tools#3183]
Here's a comparison with VS Code Insiders and VS Code Stable.

VS Code Insiders (1.79.0-insider - Apple M1)
![image](https://github.com/vuejs/language-tools/assets/40254517/cc3cfc1c-546e-42b6-a32e-04f9f61f36b2)

VS Code Stable (1.78.2 - Apple M1)
![image](https://github.com/vuejs/language-tools/assets/40254517/c1efda1f-eb77-4148-9c73-2a0888d550d1)

Reproduction Repo: https://github.com/henrychea/volar-vuejs2-ts-check-issue-repoduce

**Comment by henrychea** [comment]
I tried that but the issue persists

VS Code Stable
![image](https://github.com/vuejs/language-tools/assets/40254517/4e2c6b3c-79e3-49d6-a97b-613566d5d532)


VS Code Insider
![image](https://github.com/vuejs/language-tools/assets/40254517/b51c751c-4d20-4c21-a0ef-475433363ea8)

**Comment by soonbtf** [comment]
same problem here :(
