### ISSUE TITLE
element plus component prompts typescript 2322 type check error

### ISSUE THREAD

**Issue by wlinglinux** [vuejs/language-tools#3187]
![image](https://github.com/vuejs/language-tools/assets/286261/218c2a36-a8d2-42c3-a4ab-8870f172cb13)
hint too long

![image](https://github.com/vuejs/language-tools/assets/286261/16ba3b0f-255e-45d3-b9b3-86c744689d3e)

**Comment by wlinglinux** [comment]
"devDependencies": {
    "nuxt": "^3.4.3"
  },
  "dependencies": {
    "@element-plus/nuxt": "^1.0.4",
    "@nuxtjs/color-mode": "^3.2.0",
    "@nuxtjs/tailwindcss": "^6.6.7",
    "@vueuse/nuxt": "^10.1.2",
    "element-plus": "^2.3.4",
    "sass": "^1.62.1"
  }

TypeScript Vue Plugin (Volar)
v1.6.5

**Comment by xiaoxiangmoe** [comment]
Can you provide me a minimal reproduction demo? @wlinglinux
