### ISSUE TITLE
Component types are missing when using Nuxt 3

### ISSUE THREAD

**Issue by yulafezmesi** [vuejs/language-tools#3188]
I'm trying to make autocomplete available props on Nuxt 3, however the props or events can't show up. I'm not sure this could be misconfiguration or an issue.

Nuxt: "^3.4.3",
Volar: v1.2.0
Volar TS:  v1.6.5

<img width='350' src='https://github.com/vuejs/language-tools/assets/45617686/53da7d77-4a40-42ec-81fb-56448f41c8c8'/>

<img width='350' src='https://github.com/vuejs/language-tools/assets/45617686/9e087a37-fe4a-4548-865c-dc7f93adb93a'/>

**Comment by xiaoxiangmoe** [comment]
Can you provide me a minimal reproduction demo?

**Comment by howard-tzw** [comment]
I am encountering the same issue as well

**Comment by olivier-carre** [comment]
Same issue here but downgrading Volar and Volar TS to 1.6.4 seems to solve it.

**Comment by savokiss** [comment]
Same issue here. 
Volar 1.8.4 still happens.

**Comment by so1ve** [comment]
Please provide a minimal reproduction or we cannot debug.

**Comment by baixiaoyu2997** [comment]
i alreay send you minimal reproduction:
https://github.com/vuejs/language-tools/issues/3304

**Comment by so1ve** [comment]
@baixiaoyu2997 Ah! Sorry for that.

**Comment by johnsoncodehk** [comment]
Duplicate of #3304
