### ISSUE TITLE
1.2.0版本兼容性的问题

### ISSUE THREAD

**Issue by LeadnCode** [vuejs/language-tools#3189]
![image](https://github.com/vuejs/language-tools/assets/54300420/024df09d-f1c4-4b09-a4d0-75d8af33092c)

Today, on a whim, I wanted to update the version of the Node dependency package. After upgrading all the dependency packages, I upgraded vue-tsc from 1.2.0 to 1.6.4, but found that an error occurred during the build. The error is shown in the figure above. I checked the previous ISSUES and the solution was to upgrade the version to 1.7.1, but it still didn’t work. I checked the version record again and upgraded to 1.7.3, but it still didn’t work. In the end, I had to return the version to 1.2. 0, no errors were found, and the build succeeded.

During the period, I asked a lot of front-end technology exchange groups, and they all said that since the version 1.2.0 and later, there will be more or less problems when building.

So now how should I deal with my error reporting problem?

**Comment by ldsenow** [comment]
i have the same issue and the problems are usually coming from the <component/>. The props are unknown at the design time. The new version of the tool must be more strict on the checking now.

**Comment by LeadnCode** [comment]
At present, we dare not upgrade this version at all, so this problem is increasing, because we are all from Vue2 + JavaScript to Vue3 + typescrip, so it is really a headache when we encounter this kind of problem.
By the way, friend, where are you from, is it China?
If yes, why? Why don't you communicate in Chinese? My poor English can't make up so many words~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月22日(星期一) 上午9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vuejs/language-tools] 1.2.0版本兼容性的问题 (Issue #3189)





 
i have the same issue and the problems are usually coming from the . The props are unknown at the design time. The new version of the tool must be more strict on the checking now.

**Comment by LeadnCode** [comment]
> i have the same issue and the problems are usually coming from the . The props are unknown at the design time. The new version of the tool must be more strict on the checking now.

At present, we dare not upgrade this version at all, so this problem is increasing, because we are all from Vue2 + JavaScript to Vue3 + typescrip, so it is really a headache when we encounter this kind of problem.

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction? @LeadnCode 👀

**Comment by LeadnCode** [comment]
> 
Thank you very much for your reply. I have already handled this problem in other ways, thank you. If this happens again in the future, I will try to provide a Demo to you.

**Comment by so1ve** [comment]
Thanks @LeadnCode 👍 I'll close this issue for now, feel free to ping me to reopen.
