### ISSUE TITLE
Automatic import methods are not available within the template

### ISSUE THREAD

**Issue by k983551019** [vuejs/language-tools#3190]
"unplugin-auto-import": "^0.15.3",
    "vue-tsc": "1.6.4"
![image](https://github.com/vuejs/language-tools/assets/48147837/cc2fbf2a-d9cc-4a9a-8e97-214c4bfa824c)
![image](https://github.com/vuejs/language-tools/assets/48147837/66edf2d7-6222-4c38-8fde-fd98a8848eff)
![image](https://github.com/vuejs/language-tools/assets/48147837/84b9c9d2-2bb9-43fe-a513-85b4ca72a9b6)
![image](https://github.com/vuejs/language-tools/assets/48147837/d51b16d7-9704-4c1a-8677-844e125543cb)

**Comment by hi-reeve** [comment]
got the same error with nuxt auto import

**Comment by yulafezmesi** [comment]
same here

**Comment by zhuoqi-chen** [comment]
same here

**Comment by kleinpetr** [comment]
same..

**Comment by dargmuesli** [comment]
Please add :+1: to the issue description and do NOT add "me too" comments! :pray:

**Comment by xiaoxiangmoe** [comment]
It seems that this should be fixed in unplugin-auto-import. 
You can create a issue here https://github.com/antfu/unplugin-auto-import/issues/new/choose

**Comment by xiaoxiangmoe** [comment]
Close this issue now. 
If you have any questions about this, feel free to continue the discussion below. 
We'd also be happy to reopen this issue if there's something volar needs to do.

**Comment by kleinpetr** [comment]
you can upvote related issues please

https://github.com/antfu/unplugin-auto-import/issues/375
and
https://github.com/nuxt/nuxt/issues/20827

**Comment by xiaoxiangmoe** [comment]
Hi all, is there any one willing provide us a minimal reproduction to find some clue and then fix it?
Please provide a repo with script `"type-check": "vue-tsc --noEmit"` and make sure run type-check script will fail.

**Comment by szulcus** [comment]
Any updates?
