### ISSUE TITLE
Type of emit value is always 'any' with new style `defineEmits`

### ISSUE THREAD

**Issue by dotoleeoak** [vuejs/language-tools#3196]
When I use new style `defineEmits` introduced in Vue 3.3, types are not handled correclty (everything is 'any').
Even if I explicitly add the type of emit value as something (eg. string), from the parent component, the type of the value is interpreted as type 'any', not string. For generic, it is same.

Here is reproduction.
https://stackblitz.com/edit/vitejs-vite-fsicsz?file=src%2FApp.vue

When you type command `vue-tsc`, the following error is shown.

```
❯ vue-tsc
src/App.vue:14:8 - error TS7006: Parameter 'x' implicitly has an 'any' type.

14       (x) => {
          ~

src/App.vue:24:8 - error TS7006: Parameter 'x' implicitly has an 'any' type.

24       (x) => {
          ~


Found 2 errors in the same file, starting at: src/App.vue:14
```

**Comment by Anoesj** [comment]
Just checking, but have you tried if `x` is still `any` if you explicitly set its type to e.g. `number` instead of `T`? I've noticed that when using the new style `defineEmits` syntax, I always get `any` for all my emit events and its payloads.

**Comment by dotoleeoak** [comment]
@Anoesj I just checked that the type of emit value is always any, so edited the issue. Thanks a lot!

**Comment by so1ve** [comment]
Please try #3283 out

**Comment by so1ve** [comment]
I'll close this issue and create a new one since we already support defineEmits shorthand now, but it doesn't play well with generics.
