### ISSUE TITLE
Switch to release version, VSCode keep reinstalling v1.2.0 when installing 1.6.5

### ISSUE THREAD

**Issue by filipbekic01** [vuejs/language-tools#3198]
Editor is giving me this error but when I run vue-tsc script in terminal, there is no error at all. On mouse hover, the error says:

`Default export of the module has or is using private name 'Test'. ts(4082)`

    "vue": "^3.2.47",
    "vue-tsc": "^1.6.5"

![image](https://github.com/vuejs/language-tools/assets/16108768/61f7d514-8ac1-4f83-ad49-b7412b7b8d0b)

**Comment by filipbekic01** [comment]
Here is a fix. However, it's not the point. The point is vue-tsc is not reporting this kind of error in console. Our CI/CD is not working well considering this.

![image](https://github.com/vuejs/language-tools/assets/16108768/8b7a4b16-fe7a-43fd-984b-0a592c2a6562)

**Comment by jahnli** [comment]
same

**Comment by xiaoxiangmoe** [comment]
@filipbekic01 @jahnli 
Is the version of your vue-tsc consistent with the version of the Vue Language Features plugin?
Most of the "editor and ci error inconsistencies" are caused by this.

**Comment by jahnli** [comment]
I'll reply after I try

**Comment by filipbekic01** [comment]
I keep my project aligned with versions coming from "create-vue"

**Comment by xiaoxiangmoe** [comment]
@filipbekic01 
Can you provide me your Vue Language Features plugin version and vue-tsc version and the minimal reproduction demo?

**Comment by filipbekic01** [comment]
NPM verions:
```
    "vue": "^3.2.47",
    "vue-tsc": "^1.6.5"
```

Volar extension:
```
Name: Vue Language Features (Volar)
Id: Vue.volar
Description: Language support for Vue 3
Version: 1.6.4
Publisher: Vue
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Vue.volar
```

**Comment by filipbekic01** [comment]
I noticed that VSCode installs Volar version 1.20 by default on other computers, causing this error. Trying to install  Volar 1.6.5 wont even start the installation, however 1.6.4 works well.

I have no idea how I had 1.6.5 on my PC since latest vue-tsc is 1.6.4 only.

**Comment by filipbekic01** [comment]
> I'll reply after I try

Make sure your Visual Studio Code, Volar extension is at least 1.6.4. Something is going on there but keeps installing 1.2.0 which is horrible.

**Comment by xiaoxiangmoe** [comment]
Hi all, I create a issue on VSCode to track this.
https://github.com/microsoft/vscode/issues/182971

**Comment by cordery** [comment]
This happened to me too, even explicitly clicking and selecting version 1.6.5 using "Install another version..." resulted in it installing 1.2.0.   Uninstalling and re-installing or switching between pre-release and release made no difference.  It finally fixed itself when I chose "Install another version...1.6.4" which worked, and then I was able to install the 1.6.5 version.  Extremely strange and wasted a lot of time with confusing error messages not realizing I had the wrong volar version!

**Comment by jahnli** [comment]
@cordery  I can only switch to 1.6.4, I can't switch from 1.6.4 to 1.6.5,

**Comment by filipbekic01** [comment]
Issue is still open after a week. I'm sure it's causing a lot of problems, especially to newcomers.

**Comment by yoyo837** [comment]
You can manually choose to install the previous version of the latest version, which means always one version behind.

**Comment by yoyo837** [comment]
> You can manually choose to install the previous version of the latest version, which means always one version behind.

Wait until the next version is release out, then vscode can upgrade to the latest version normally.
