### ISSUE TITLE
Cannot disable typescript checking in templates when using vite and vue 2.7

### ISSUE THREAD

**Issue by Fnxxxxo** [vuejs/language-tools#3199]
I use vue-tsc@1.6.5 and set vueCompilerOptions.target to 2.7. But vue-tsc still complains type error in templates. Any way to disable it?
If I provide type assertion in templates, vite complains babel error.

**Comment by kleinpetr** [comment]
same here

**Comment by xiaoxiangmoe** [comment]
@kleinpetr @Fnxxxxo Can you provide me a reproduction?

**Comment by Fnxxxxo** [comment]
@xiaoxiangmoe Here is the demo: https://stackblitz.com/edit/vitejs-vite-vv4t4y?file=package.json

**Comment by Fnxxxxo** [comment]
They are too many. I used to add ''experimentalDisableTemplateSupport" but not work any more.

**Comment by xiaoxiangmoe** [comment]
See https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#100-alpha4-2022924

vueCompilerOptions property `experimentalDisableTemplateSupport` renamed to `skipTemplateCodegen`

**Comment by Fnxxxxo** [comment]
But this also disable some component validation. It's better just close typescript in templates.

**Comment by xiaoxiangmoe** [comment]
@Fnxxxxo This just disable type checking for vue template. vue's script's ts validation also works.

**Comment by Fnxxxxo** [comment]
Any component checking in template? Such as "unregister component name".

**Comment by xiaoxiangmoe** [comment]
No, it disables all type checking for template
