### ISSUE TITLE
vue-tsc complains 'vue/jsx-runtime' type issue when using tsx in vue2.7

### ISSUE THREAD

**Issue by Fnxxxxo** [vuejs/language-tools#3203]
When I declare tsx within `<script lang="tsx></script>"`, vue-tsc throw TS2307 error.
I have configure vueCompilerOptions.target to 2.7 but it cannot help.
I find the target check has gone in packages/vue-language-core/src/utils/directorySharedTypes.ts
Any why to fix it?

**Comment by xiaoxiangmoe** [comment]
Hi @Fnxxxxo Can you provide me a minimal reproduction?

**Comment by xiaoxiangmoe** [comment]
Hi @Fnxxxxo Can you provide me a minimal reproduction?

**Comment by johnsoncodehk** [comment]
This is not a problem with Vue language tools. You can reproduce the problem in a .tsx file using the same code. For TS issues please raise them in the Vue Discord server.
