### ISSUE TITLE
Calling prop fields in the template (like `props.foo`) doesn't work with `withDefaults`

### ISSUE THREAD

**Issue by rodrigocfd** [vuejs/language-tools#3204]
This is issue originated from this [vue/core discussion](https://github.com/vuejs/core/issues/8310#issuecomment-1553755650). Apparently it's not a vue/core error.

This is the error:

![gen-err](https://github.com/vuejs/core/assets/1283868/45b0ae33-4ca9-408b-9657-e5986aac2d9c)

Reproducible:

```vue
<script setup lang="ts" generic="T">
const props = withDefaults(defineProps<{
	value?: T | null;
	list: T[];
}>(), {
	value: null,
});
</script>

<template>
	<select>
		<option v-for="item of props.list">

		</option>
	</select>
</template>
```

**Comment by xiaoxiangmoe** [comment]
Temp solution: change `props.list` to `list`.

**Comment by xiaoxiangmoe** [comment]
Hi, @pikax

This also seems to be a vue/core type issue

```ts
import { defineComponent, defineProps, withDefaults } from "vue";
export default <T>() => {
  const props = withDefaults(
    defineProps<{
      value?: T | null;
      list: T[];
    }>(),
    {
      value: null,
    }
  );
  const __VLS_internalComponent = defineComponent({
    setup() {
      return {
        props: props,
      };
    },
  });
  const instance: InstanceType<typeof __VLS_internalComponent> = null as any;

  // Property 'list' does not exist on type 'PropsWithDefaults<{ value?: T | null | undefined; list: T[]; }, { value: null; }, [T | null | undefined] extends [boolean | undefined] ? "value" : never> extends Ref<...> ? V : PropsWithDefaults<...> extends Ref<...> | undefined ? unknown extends V ? undefined : V | undefined : PropsWithDefaults<...>'.ts(2339)
  // @ts-expect-error
  instance.props.list;
};
```

**Comment by pikax** [comment]
@xiaoxiangmoe you're still changing the type of `props` by returning them on the setup, the clean `$props` are located `_ctx.$props` and I would recommend using them instead.

<img width="350" alt="image" src="https://github.com/vuejs/language-tools/assets/4620458/e6eed2ce-c979-418c-bfd5-2e342e97589c">

```html
<script setup lang="ts" generic="T">
const props = withDefaults(defineProps<{
	value?: T | null;
	list: T[];
}>(), {
	value: null,
});
</script>

<template>
	<select>
		<option v-for="item of list">

		</option>
      {{ $props.list }}
    </select>
</template>
```
--- 
While testing this I've noticed Volar does not resolve the type correctly when using instance type, altho it works in the `<template>`?

eg:
```ts
import  MyComp from './MyComp.vue'

// this is errored
const el = ref<null | InstanceType<typeof MyComp>(null)
```
<img width="777" alt="image" src="https://github.com/vuejs/language-tools/assets/4620458/5bea6755-b470-4352-8077-6ae5c2f53214">

**Comment by emilyAzz** [comment]
Hello, I have vue version 3.3.4 and upon using the generic type within the defineProps with defaults value managad with the new updates to make it work but when I come to build I encounter the below error with the defineEmits when I am emitting a generic type back

error TS5088: The inferred type of 'default' references a type with a cyclic structure which cannot be trivially serialized. A type annotation is necessary.

Tried <script setup lang="ts" generic="I extends any"> and also adding
"vueCompilerOptions": { "jsxTemplates": true, "experimentalRfc436": true } 

but nothing is removing this error, anyone has any idea how this can be solved?

**Comment by rodrigocfd** [comment]
@xiaoxiangmoe @pikax Is there any progress on this?

**Comment by so1ve** [comment]
@rodrigocfd I'm working on this now, but I'm not sure if I can fix it 😂

**Comment by ouou12138** [comment]
When I use generic components, I get this error, How can  I resolve it?

```vue
<template>
  <div>{{anyData.name}}</div> // Property 'name' does not exist on type '[{ type: PropType<T>; required: true; }] extends [Prop<infer V, infer D>] ? unknown extends V ? IfAny<V, V, D> : V : { type: PropType<T>; required: true; }'.ts(2339)。

  <button @click="emit('taptap',anyData)"></button> // Argument of type '[{ type: PropType<T>; required: true; }] extends [Prop<infer V, infer D>] ? unknown extends V ? IfAny<V, V, D> : V : { type: PropType<T>; required: true; }' is not assignable to parameter of type 'T'.
</template>
<script lang='ts' setup generic='T extends { name: string }'>
defineProps<{
  anyData:T,
}>()
const emit = defineEmit<{
  (event:'taptap',value:T):void
}>()
</script>
```

however, when i use this component in other component, i can get actually types

**Comment by lmiller1990** [comment]
I have the same issue. If you make the `T` into `T[]`, it works fine, though. I am not clear why this would the case. Eg:

```html
<template>
  <div>{{anyData[0].name}}</div> 
</template>

<script lang="ts" setup generic="T extends { name: string }">
defineProps<{
  anyData:T[],
}>()
</script>
```

This is dup of https://github.com/vuejs/language-tools/issues/3405.

**Comment by so1ve** [comment]
Typescript issue I guess? :(

**Comment by lmiller1990** [comment]
I am trying to reproduce without using an SFC to establish where the issue is.

I would be surprised if this was in Vue core - the PR is here, and it looks like it should be just fine: https://github.com/vuejs/core/pull/7963/files

**Comment by lmiller1990** [comment]
This works fine, I do not think it is in Vue core.

```ts
import { defineComponent, h, ref } from "vue";

export interface ListItem {
  id: string;
  title: string;
}

const Comp = defineComponent(
  // TODO: babel plugin to auto infer runtime props options from type
  // similar to defineProps<{...}>()
  <T extends ListItem>(props: { msg: T; list: T[] }) => {
    // use Composition API here like in <script setup>
    const count = ref(0);

    return () => h("div", props.msg.title);
  }
);
```

<img width="530" alt="image" src="https://github.com/vuejs/language-tools/assets/19196536/347ea2ab-f308-4a76-a645-ecb283e1fe92">

**Comment by rodrigocfd** [comment]
@johnsoncodehk While this works as expected in Volar and dev environment, it still crashes at `npm run build`. Could you please route this issue to the appropriate Vue repo?

**Comment by rodrigocfd** [comment]
@so1ve Compilation error. It says "`props.foo` doesn't exist":

```
error TS2339: Property 'modelValue' does not exist on type 'PropsWithDefaults<{ modelValue: T; lista: { val: T; texto: string; }[]; titulo?: string | undefined; }, { titulo: "Selecione..."; }, [T] extends [boolean | undefined] ? "modelValue" : never> extends Ref<...> ? V : PropsWithDefaults<...> extends Ref<...> | undefined ? unknown extends V ? undefined : V | undefined : P...'.
```

**Comment by so1ve** [comment]
Which version of vue-tsc are you using?
