### ISSUE TITLE
vue-tsc didn't work in dev mode

### ISSUE THREAD

**Issue by CatherineYF** [vuejs/language-tools#3207]
recently,when i found that vite cannot emit the errors in ts, i installed vue-tsc for help.however,when i type some type errors in files and save,vite prompt this in terminal:
<img width="386" alt="image" src="https://github.com/vuejs/language-tools/assets/12647278/9f92a269-b27e-47a4-bffe-46f16f6757ec">
it seems that vue-tsc didn't work!?
Or did i miss something in my config file?
here is my tsconfig.json:
<img width="383" alt="image" src="https://github.com/vuejs/language-tools/assets/12647278/d54b73fd-e67a-45a8-bae8-7a9c3a483c35">
and the tsconfig.app.json written like this:
<img width="526" alt="image" src="https://github.com/vuejs/language-tools/assets/12647278/386fa829-eee7-49a1-93f5-7bc8c32db532">
my vite.config.ts:
<img width="623" alt="image" src="https://github.com/vuejs/language-tools/assets/12647278/093f86de-f1ab-43e4-801a-a22fe1f152fc">
package.json:
<img width="955" alt="image" src="https://github.com/vuejs/language-tools/assets/12647278/2d34a3f6-4ab4-4267-890f-9ea06f0e1c47">

**Comment by xiaoxiangmoe** [comment]
Hi, can you provide me a minimal reproduction repo?

**Comment by xiaoxiangmoe** [comment]
Hi, @CatherineYF  I don't known weather it's a bug in vue-tsc or a bug in [vite-plugin-checker](https://github.com/fi3ework/vite-plugin-checker). Can you provide me a reproduction repo?

cc @fi3ework

**Comment by CatherineYF** [comment]
actually,the problem is solved by changing tsconfig.json to this one:
<img width="791" alt="image" src="https://github.com/vuejs/language-tools/assets/12647278/8fc48ac7-73c3-49c5-84b1-22a189ff559d">
so maybe the problem is not a bug?
and here is the repo
https://github.com/CatherineYF/myVue3
I have restored the code to a version with the bug.

**Comment by fi3ework** [comment]
I don't believe the issue lies with vite-plugin-checker as no errors are thrown when I run `pnpm vue-tsc --noEmit`. The problem might be related to the tsconfig, as previously mentioned.

**Comment by johnsoncodehk** [comment]
> actually,the problem is solved by changing tsconfig.json to this one: <img alt="image" width="791" src="https://private-user-images.githubusercontent.com/12647278/239742432-8fc48ac7-73c3-49c5-84b1-22a189ff559d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjQ3OTAsIm5iZiI6MTcxNTYyNDQ5MCwicGF0aCI6Ii8xMjY0NzI3OC8yMzk3NDI0MzItOGZjNDhhYzctNzNjMy00OWM1LTg0YjEtMjJhMTg5ZmY1NTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE4MjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZjY2MDhjOTY4MWI5ZjFmOGNlOWI0Mjk2OThmMTRjYTI2YjI0YTNhMWY0YjU4OGVjZTk5OTczNTNhMzBmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ygRic8wrSO9634I4cij7JKqJasjotmHrJn_muadeG4Y">

Regardless of whether I use this setting or not, I can't reproduce the problem by running `npm run type-check`. If you still have this problem on the latest version, please let me know.
