### ISSUE TITLE
[Bug] CSS Modules class rename causing issues

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#3208]
Class renaming in template and style both have this issue.

Expected behavior:

`$style.greetings-foo` => `$style['greetings-foo']`

https://github.com/vuejs/language-tools/assets/28700378/6d0c343d-8d22-49d9-aef7-7037937d6a32

**Comment by so1ve** [comment]
This is typescript's behavior and we can't fix.

Try:

```ts
const foo = {
  bar: 1
}

foo.bar
//  ^ trigger rename here, rename it to bar-bar
```
