### ISSUE TITLE
[Bug] Take over mode `import.meta` error

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#3209]
<img width="1055" alt="image" src="https://github.com/vuejs/language-tools/assets/28700378/921dd7cd-d6ea-412b-8c2b-6329737bcca9">

Repro: https://github.com/wenfangdu/vite-vue-3/tree/import.meta

**Comment by so1ve** [comment]
Add `module: "esnext"` to your `tsconfig.config.json`'s `compilerOptions`. It is a create-vue issue.

**Comment by wenfangdu** [comment]
https://github.com/wenfangdu/vite-vue-3/blob/61b0ea88f685377fe9c0943b66c4fe3f4fa247a4/tsconfig.json#L10

@so1ve I had.

**Comment by wenfangdu** [comment]
@so1ve It's causing more errors:

https://github.com/wenfangdu/vite-vue-3/blob/1d80f001ad5742d14c280778439ed07b109cd8fc/tsconfig.config.json#L6
<img width="1087" alt="image" src="https://github.com/vuejs/language-tools/assets/28700378/97584f98-075a-443e-99e5-e1f7cbab599e">

**Comment by so1ve** [comment]
Try to set moduleResolution to nodenext or node16

**Comment by so1ve** [comment]
I personally don't use seperate tsconfigs for vite config and files under src directory. So I prefer add vite.config.ts to tsconfig.json's include list.

**Comment by wenfangdu** [comment]
@so1ve Unfortunately, not working either:
<img width="1412" alt="image" src="https://github.com/vuejs/language-tools/assets/28700378/84e450cc-3fd4-45e6-90ea-8eeadb03fe8d">

**Comment by so1ve** [comment]
That's pretty weird, could you please show me the errors?

**Comment by wenfangdu** [comment]
@so1ve 
<img width="1274" alt="image" src="https://github.com/vuejs/language-tools/assets/28700378/b1203f25-1f2a-4fd7-ad1e-b52e0093234e">
<img width="1036" alt="image" src="https://github.com/vuejs/language-tools/assets/28700378/6f1bfbd0-9db7-4b2b-9ff6-ae1f07f1f354">

**Comment by so1ve** [comment]
Ah, I see. Just replace tsconfig.config.json with:

```json
{
  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "playwright.config.*"],
  "compilerOptions": {
    "composite": true,
    "types": ["node"],
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
  }
}
```

**Comment by wenfangdu** [comment]
@so1ve Thanks buddy, I tweaked your settings a bit, and now the error's gone:

```diff
{
  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "playwright.config.*"],
  "compilerOptions": {
    "composite": true,
    "types": ["node"],
+   "module": "esnext",
+   "moduleResolution": "node"
  }
}
```

Did you use `"moduleResolution": "bundler" intentionally? What's the benefit of that compared to just using `node`?

**Comment by wenfangdu** [comment]
@so1ve Thanks buddy, I tweaked your settings a bit, and now the error's gone:

```diff
{
  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "playwright.config.*"],
  "compilerOptions": {
    "composite": true,
    "types": ["node"],
+   "module": "esnext",
+   "moduleResolution": "node"
  }
}
```

Did you use `"moduleResolution": "bundler"` intentionally? What's the benefit of that compared to just using `node`?

**Comment by so1ve** [comment]
Hmmm, not intentionally. The `bundler` mode is new and the default setting of @vue/tsconfig, so I think it is better to keep them consistent. However, while this mode is recommended, some packages are incompatible with it (such as vue-macros), so feel free to use the node resolution.

**Comment by wenfangdu** [comment]
@so1ve Thanks, that makes sense. For future readers, see https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler.

**Comment by so1ve** [comment]
Can you close this now?
