### ISSUE TITLE
Getting additional space for  first : in @apply

### ISSUE THREAD

**Issue by ASoldo** [vuejs/language-tools#3210]
Hi everyone, 
I'm new here and I hope you can give me some guidance. My problem is when I use volar neovim lsp, every time there is postcss tailwindcss @apply hover:text-black on save it formats the code and add space in between hover:[space]text-black, that breaks the script entirely. Does anyone have similar issues?
![image](https://github.com/vuejs/language-tools/assets/1175537/f2f2b5db-196c-4ed5-bdcc-6cc0bb3911dc)
![](https://cdn.discordapp.com/attachments/1099900750647283723/1109250314906914937/image.png)
It's always the first : that is affected by this and I don't know what to do.

Thank you!

**Comment by so1ve** [comment]
Have you configured any formatter?

**Comment by ASoldo** [comment]
No, but I've read in the documentation that this behavior is kind of anti pattern in the whole scheme of Tailwindcss things, so I guess it's fine...
