### ISSUE TITLE
Strange issue saving files in neovim with vue-language-server

### ISSUE THREAD

**Issue by Thevetat** [vuejs/language-tools#3211]
While using neovim, something has broken with the recent updates.  If I try to wqall! to write and quit all files, I get a full nvim freeze/lockup. The files are saved, but the process becomes unusable. If I reopen neovim, it shows the files have been saved, but it is odd the locking up.

Disabling all language servers it is okay, enabling only ESlint, TSServer and emmet-ls, I am able to wqall. It is only when I enable vue-language-server I am getting this error. 

Will continue to diagnose my local config, but I figured create the issue and use this incase it happens to anyone else.

For reference, this is a very stable configuration which has not had any changes in 4 months.  Cheers.

**Comment by Thevetat** [comment]
Lockup is still only happening when volar is enabled.  Installed via mason.  If I run a combination of json, js, ts files, I am able to write, quit all, or just quit all, due to volar not being shown as active in LSP info.  If I run a .vue file which enables volar, I am now unable to save or write quit all, or just quit all.

Will continue to move stuff around and see if something changes, just wanted to give an update.

**Comment by Thevetat** [comment]
Just tried on a fresh install of lazyvim.  Installed eslint-lsp, html-ls, typescript-language-server and then vue-language-server through mason. Locks up when I have vue-lanuage-server installed. If I uninstall it, then it is able to write quit all, or just quit all.

**Comment by Syakhisk** [comment]
i'm having the same problem.

**Comment by Thevetat** [comment]
Just to update, it is not revolved around writing, or writing all, but quitting all, so then subsequently write, quit all is effected.

If I do a :wall, that works, :w works,

:q on a single buffer works,

:qall does not work, neither does :wqall

**Comment by Thevetat** [comment]
@Syakhisk Is the issue still occuring for you?

With no changes to my local environment that I can thing of, the issue has seemed to resolve.  Will mark it closed in a few days if it persists and keeps working properly.

But as of this comment, I have :wqall multiple times today with no issues.

**Comment by Thevetat** [comment]
Unsure why but getting this issue again

**Comment by johnsoncodehk** [comment]
Sorry we don't have the ability to investigate issues occurring specifically with IDEs other than VSCode, please raise it in neovim's community and if it turns out to be caused by an abnormal state of vue-language-server, please raise an issue against the bug.
