### ISSUE TITLE
Why does volar automatically add a semicolon?

### ISSUE THREAD

**Issue by tieniu1** [vuejs/language-tools#3219]
volar will automatically add a semicolon after the vue file introduces the file, how can I make it not add a semicolon?
![image](https://github.com/vuejs/language-tools/assets/49060203/64d73ae3-7fd5-4131-a0ad-2e60f2a4909f)

**Comment by so1ve** [comment]
Do you mean volar adds a semicolon when you open the file?

**Comment by so1ve** [comment]
@tieniu1 Any updates?

**Comment by antiformatiker** [comment]
I have the same problem in my project. I use Prettier for formatting and have deactivated the semicolons. As soon as I activate the extension and format a Vue file, the Prettier rule is ignored and the semicolons are added automatically.

**Comment by akmalov-i** [comment]
Here's how you can do it:

Open your VS Code settings by pressing Ctrl + , (Windows/Linux) or Cmd + , (Mac).
Click on the "Open Settings (JSON)" icon at the top-right corner of the settings page. This will open the settings.json file.
Add the following lines to the settings.json file:

```
{
"[javascript]": {
  "editor.defaultFormatter": "octref.volar"
},
"[typescript]": {
  "editor.defaultFormatter": "octref.volar"
},
"javascript.format.insertSemicolons": false,
"typescript.format.insertSemicolons": false
}
```

In these settings:

"editor.defaultFormatter": "octref.volar" specifies that the Volar extension should be used as the default formatter for JavaScript and TypeScript files.
"javascript.format.insertSemicolons": false and "typescript.format.insertSemicolons": false are used to disable automatic semicolon insertion for JavaScript and TypeScript files.

**Comment by so1ve** [comment]
`octref.volar`? Should be `Vue.volar`

**Comment by antiformatiker** [comment]
Yes, it should be `Vue.volar`. Whereby it depends on whether VSCode Marketplace is really used here, or the free alternative, e.g. VSCodium.

In my opinion, the proposed solution is correct for this one case, but does not solve the problem that this plugin completely ignores/overwrites Prettier. If I want to use semicolons in one project and not in the other, then I don't want to solve this via the VSCode configuration, as I may still have a ci build pipeline that sounds an alarm if Prettier/ESLint reports an error.

I hope you understand what I mean. What do you think?

**Comment by so1ve** [comment]
Sorry, but I still didn't get your point. Here is my VSCode config: https://github.com/so1ve/dotfiles/blob/main/vscode-settings.jsonc

And Prettier works perfectly with Volar.

**Comment by j46r0** [comment]
Any news on this @so1ve ?

It is kind of funny official project does not use semicolons, but official VS Code Extension uses them.

**Comment by whitefoxx** [comment]
In my case, I fixed it by adding this line to vscode's settings.json:

  "javascript.format.semicolons": "remove"

**Comment by terwer** [comment]
> "javascript.format.semicolons": "remove"

Thanks, and for typescript, youmay add

```json
{
  "javascript.format.semicolons": "remove",
  "typescript.format.semicolons": "remove"
}
```

ro `.vscode/settings.json`

**Comment by rdonadeu** [comment]
I want to note that, I had to add this to main route .vscode. And not inside my project .vscode

**Comment by kazuooooo** [comment]
Thanks 👍 
I think Volar should have option which can disable all formatting 💡
