### ISSUE TITLE
Can't use own type in `defineEmits` in new Vue 3.3 structure

### ISSUE THREAD

**Issue by szulcus** [vuejs/language-tools#3223]
Work:
```ts
const emit = defineEmits<{
	close: [];
}>();
```

Don't work:
```ts
interface Emits {
	close: [];
}
const emit = defineEmits<Emits>();
```

```
Type 'Emits' does not satisfy the constraint '((...args: any[]) => any) | Record<string, any[]>'.
  Type 'Emits' is not assignable to type 'Record<string, any[]>'.ts(2344)
```
![image](https://github.com/vuejs/language-tools/assets/48328739/163e8b1c-951b-4756-8eea-cd5359423eb4)
Previous structure works fine:
![image](https://github.com/vuejs/language-tools/assets/48328739/f63e24a3-44b1-41e8-a2fb-1451de6c6a34)

**Comment by jdk2pq** [comment]
Can confirm. Related: https://github.com/vuejs/language-tools/issues/3169#issuecomment-1550263812

**Comment by so1ve** [comment]
try to use `type Emits = ...`?

**Comment by jdk2pq** [comment]
@so1ve Sure thing. When I use the `Simplify` type, no issues:

![Screenshot 2023-05-30 at 12 34 42 PM](https://github.com/vuejs/language-tools/assets/1759726/4df2eb4b-f093-4aca-b9e1-69a34a2f057b)

But if I don't use that, I get the same type errors I was seeing before here https://github.com/vuejs/language-tools/issues/3169#issuecomment-1550263812 :
![Screenshot 2023-05-30 at 12 34 14 PM](https://github.com/vuejs/language-tools/assets/1759726/ba0b24d8-eb1d-45a6-82ae-19e44469dee1)

No complaints when I use `type Emits = { ... }` either:
![Screenshot 2023-05-30 at 12 36 35 PM](https://github.com/vuejs/language-tools/assets/1759726/2903cc11-22cb-41dc-b927-6bd9e7e24753)

**Comment by so1ve** [comment]
Created an issue: vuejs/core#8457

**Comment by szulcus** [comment]
Thanks @so1ve !
