### ISSUE TITLE
[takeover] Change in one ts file does not reflect diagnostics in another file

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#3229]
I'm not sure if this affects only takeover mode (ts/js files) or also Vue files but I would suspect that it does affect all.

1. Create files:

### file1.ts

```ts
export const x = 1;
```

### file2.ts

```ts
import { x } from './file1';

export const y = x + 2;
```

2. change `1` in the first file to `'str'`.
3. Switch to file 2

Expected: `file2` shows an error because number and string can't be added.
Actual: `file2` does not show any error until something is changed in the file.

It doesn't seem like Volar listens to the tsserver events (`syntaxDiag`, `semanticDiag`) that update diagnostics.

**Comment by lucasavila00** [comment]
I'm also able to reproduce it with another Volar-based LSP, unrelated to Vue. It does not require takeover mode.

I haven't published its source yet, but the gist of it is: https://gist.github.com/lucasavila00/e7b8014c0d2aec6a8082f2f5b578578d

**Comment by johnsoncodehk** [comment]
What is your language server `diagnosticModel` setting? For value `1` it's handle by language server push, but for value `2` it's handle by language client pull, so we can't control. You should also make sure the LSP client supports [interFileDependencies](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_pullDiagnostics).

**Comment by johnsoncodehk** [comment]
@lucasavila00 [volarjs/starter](https://github.com/volarjs/starter) used `diagnosticModel : 2` for example purposes, changing to `diagnosticModel: 1` or remove the option may fix the problem.

**Comment by rchl** [comment]
It was actually set to `diagnosticModel: 2` when I've tested but it also reproduces with `1`.

**Comment by rchl** [comment]
And BTW. According to the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#relatedFullDocumentDiagnosticReport) the pull diagnostics also support notifying about changes in related documents which means that the server can control updates in not-currently-active document also.

(whether it would be possible to handle with typescript or the current volar architecture, I can't tell)

**Comment by rchl** [comment]
Also note: I'm testing in ST which does support `relatedDocuments` but since it also reproduces with push diagnostics, I don't think that matters much.

**Comment by johnsoncodehk** [comment]
I think it's expected that `x + 2;` doesn't report an error, since string+number is valid code.

You can change it to `x.toPrecision() + 2;` and try again.

**Comment by johnsoncodehk** [comment]
> And BTW. According to the LSP spec the pull diagnostics also support notifying about [changes in related documents](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#relatedFullDocumentDiagnosticReport) which means that the server can notify about updated diagnostics even in the not-currently-active document.

According to the description of LSP refresh diagnostics it doesn't seem to be for individual files, I think the language client needs to handle the refresh itself with re-pull diagnostics.

**Comment by rchl** [comment]
> I think it's expected that `x + 2;` doesn't report an error, since string+number is valid code.
> 
> You can change it to `x.toPrecision() + 2;` and try again.

No. The error gets eventually reported, even in Volar. The issue is that the file needs to be explicitly modified (by adding a space or whatever other change) and then Volar correctly picks up the updated diagnostic.

> According to the description of LSP refresh diagnostics it doesn't seem to be for individual files, I think the language client needs to handle the refresh itself with re-pull diagnostics.

Not sure what you mean.
Server can respond with [DocumentDiagnosticReport](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentDiagnosticReport) that can include `relatedDocuments` array which tells the client in which files the diagnostics need to be pulled. So it's client's responsibility to pull still but now it knows which files to update.
