### ISSUE TITLE
Feature request: Ability to run `vue-tsc` on a single file and extract the context

### ISSUE THREAD

**Issue by gangsthub** [vuejs/language-tools#3233]
I was trying to configure https://github.com/okonet/lint-staged to run `vue-tsc` on the staged files only in a pre-commit step. But `lint-staged` passes by default the absolute path of the file under consideration. Example:

```bash
vue-tsc --noEmit /Absolute/path/to/project/components/Icon.vue
```

And when it's run like this, `vue-tsc` does not get the project's `tsconfig` info correctly. For example, it `"Cannot find module"`s configured (with aliases) in `compilerOptions.paths`, like this:

```json
    "paths": {
      "@/*": ["src/*"]
    },
```

It would be great if `vue-tsc` could be configured with some CLI option to specify the root of the project or where the tsconfig file is at. But I could not find a way to do it granularly with the current options.

**Comment by AKMav** [comment]
Hi! We also have this problem in project, because on pre-commit we need to check only staged files. Thanks if someone will answer for this issue

**Comment by wenfangdu** [comment]
Things to consider:
![image](https://github.com/vuejs/language-tools/assets/28700378/f31339cf-90a9-42d9-b26d-30a1caacd061)
Ref: https://dev.to/samueldjones/run-a-typescript-type-check-in-your-pre-commit-hook-using-lint-staged-husky-30id

**Comment by gangsthub** [comment]
> Things to consider:

It is totally possible to do the same with `vue-tsc` (setting up a Husky hook to run `vue-tsc`), but the problem remains: it's run for the whole project and not just the staged files. I don't know if I missed something from your point, @wenfangdu.

**Comment by wenfangdu** [comment]
> It simply does not help identify errors in other files.
>
> So, for example, if you change the way an export works in FileA and commit your code, any files importing FileA will likely all be broken, and you will not be notified of the breakage until you deploy it.

@gangsthub It's safer to run `vue-tsc` on the whole project.

**Comment by gangsthub** [comment]
Thanks for your quick answer, @wenfangdu. This is what this issue is about! 😅

I'd like to hear the opinion from the maintainers, though.

**Comment by gangsthub** [comment]
Seems like this is an issue with the underlying `tsc` tool:

https://github.com/microsoft/TypeScript/issues/27379

**Comment by chenchenpp** [comment]
所以这个无解了吗？🤔

**Comment by pranav-js** [comment]
it would be good to have it run on particular files by specifying path

**Comment by vonkanehoffen** [comment]
Yep. For my use case I have a project with a LOT of pre-existing type errors - too many to `ts-ignore` in one go - and I'd like to implement `vue-tsc` in a Github action so it guards against new errors being introduced via a PR. Hence I need it to ignore everything but the files touched by that PR (which I'd get with a `git diff`).

Hence an option to specify a list of files would be very useful.
