### ISSUE TITLE
Saving time is too long. (1785 ms > 1000 ms),

### ISSUE THREAD

**Issue by qhl123456** [vuejs/language-tools#3235]
While I was saving  workspace，It always comes up ：Saving time is too long. (1785 ms > 1000 ms),

**Comment by stanzakharin** [comment]
I've also been running into this problem a lot with Volar. Initially, it saves quickly, but over time (~1-2 hours) it eventually crawls to a halt and takes a long time to save. I have tried disabling other extensions like ESLint but no luck. I've probably had this issue for about a month now.

**Comment by qhl123456** [comment]
> I've also been running into this problem a lot with Volar. Initially, it saves quickly, but over time (~1-2 hours) it eventually crawls to a halt and takes a long time to save. I have tried disabling other extensions like ESLint but no luck. I've probably had this issue for about a month now.

Yes, sometimes I wonder if my computer is too bad, it never used to be the case, maybe there are too many lines of code in one file

**Comment by so1ve** [comment]
#2740
