### ISSUE TITLE
`align` prop wrong highlight

### ISSUE THREAD

**Issue by szulcus** [vuejs/language-tools#3236]
I think it's VSCode's warning against old HTML.
![image](https://github.com/vuejs/language-tools/assets/48328739/7d08fb64-18fe-4c88-8d8f-a9fdb3ea8382)
![image](https://github.com/vuejs/language-tools/assets/48328739/f6d3493b-9213-41cf-b4f6-46ed49ac9f4d)

**Comment by so1ve** [comment]
Duplicate of #1317

**Comment by so1ve** [comment]
Duplicate of #1363
