### ISSUE TITLE
component element can't be typed correctlly

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#3237]
I reproduce this in latest volar starter: https://github.com/tjx666/volar-component-element-issue

![image](https://github.com/vuejs/language-tools/assets/41773861/71ae8adc-8410-4d0a-8282-69fe3e3e7a92)

```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T15:00:40.428Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
Volar: v1.7.8
TakeOver Mode: yes
```

**Comment by sfreytag** [comment]
You can work around the issue with dynamic components for the time being with something like:

```
<component :is="HelloWorld as any" />
```

**Comment by tjx666** [comment]
@sfreytag vite vue2.7 doesn't support type assertion:

https://github.com/vitejs/vite-plugin-vue2/issues/87

**Comment by so1ve** [comment]
I think this is the intended behavior. You have defined a required prop `msg` but you didn't pass it to the `<compnent>` element.

**Comment by tjx666** [comment]
@so1ve you are right, but the error message is hard to understand here.

**Comment by so1ve** [comment]
这也没办法，转换出来的TSX类型就是这么又臭又长（

**Comment by so1ve** [comment]
You can install a vscode plugin called `Pretty Typescript Errors`.
