### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by mumumilk** [vuejs/language-tools#3238]
### Problem

I'm trying to use Volar to autocomplete vue scripts within markdown files (as I'm using [Vitepress](https://vitepress.dev/)), but with no success. So I'm wondering if I'm missing any configuration or if it is not supported at the moment.

<img width="943" alt="image" src="https://github.com/vuejs/language-tools/assets/21252014/52adece4-28cc-4cbd-9974-406472249be2">

### What I've tried so far:

- Added the markdown files in the `include` prop in `tsconfig`
- Enabled the `Vue > Server > Vite Press: Support Md File` extension setting
- Tried to listen to both Vue semantic/syntatic server message's output in vscode, but haven't found anything helpful to debug

> _sometimes_ I was able to get it working by setting the language of the document to `vue` then back to `markdown`, but this stopped happening in recent Volar versions.

### Reproduction
https://stackblitz.com/edit/vitejs-vite-sxkhai?file=markdown-example.md

### Env

| Dep | Version |
|--------|--------|
| Volar | 1.7.8 |
| Vue | 3.3.4 |
| Vitepress | 1.0.0-beta.1 |
| TS | 5.0.4 | 

Thanks in advance

**Comment by alephpi** [comment]
encounter the same issue, hoping for investigation
