### ISSUE TITLE
Formatting is pushing multi line comment tags (again)

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuejs/language-tools#3242]
VSCode: 1.78.2 
Vue Lang Tools: 1.2.0
Vue: 3.3.4

This problem seems to have come back again.
https://github.com/vuejs/language-tools/issues/2632

**Comment by webdevnerdstuff** [comment]
Also related: https://github.com/vuejs/language-tools/issues/2520

**Comment by so1ve** [comment]
You are still using v1.2.0?!

Possibly related: #3198

**Comment by webdevnerdstuff** [comment]
@so1ve That issue you gave must be related, as when you install the extension it installs v1.2.0. At the time I wrote this issue when I tried getting anything higher it was a "pre-release", and I don't install pre-releases. I'll close this issue out as that related issue you gave seems to be the actual problem here.
