### ISSUE TITLE
What does this actually DO? There is no plain English intro about what it is and why I should use it

### ISSUE THREAD

**Issue by evilgeniuscreative** [vuejs/language-tools#3245]
Everything assumes I already know what this is and why to use it. Can you please just add a short paragraph explaining what this is and why is helpful and what it will do for me? Not everyone is an expert who comes here you can't assume that people know everything that doesn't work in UX and it doesn't work and documentation

**Comment by ferm10n** [comment]
I'm not really an authority on this here, but my understanding is this is a collection of tools / packages for working with Vue files.

The README has a link to a website https://volarjs.github.io/ and it looks like documentation is WIP, which is where I'd expect to find the intro you're looking for.

There's also this from the README too, which highlights the key packages in this repo:
https://github.com/vuejs/language-tools/blob/24968e16eb2952cec6bcd247d6d6dc1eed13bf74/README.md?plain=1#L7-L18

Each of these packages have additional info in their READMEs linked in that excerpt I linked.

The two main ones IMO are the vscode extension "volar", and the cli tool for performing typescript checks on Vue SFC files "vue-tsc"
