### ISSUE TITLE
"The Vue Semantic Server server crashed 5 times in the last 3 minutes": "Debug.assert(!compilerOptions.verbatimModuleSyntax);"

### ISSUE THREAD

**Issue by leegee** [vuejs/language-tools#3246]
![image](https://github.com/vuejs/language-tools/assets/512816/cbe1ba08-a76e-4162-a483-f19096c0d0a7)

![image](https://github.com/vuejs/language-tools/assets/512816/554e6f22-1f0c-45fe-a9b7-7738e8ad819d)

Do the docs mention anything about `compilerOptions.verbatimModuleSyntax`? 

I have added it like this, in several places, since none seems to be effective:

![image](https://github.com/vuejs/language-tools/assets/512816/f93828fa-553e-4b84-a378-137b42d5afa5)

The initial set-up was through the scaffolding script `create-vue`, so `tsconfig.app.json` contains:
```json
"extends": "@vue/tsconfig/tsconfig.web.json"
```
```bash
node -v
v18.4.0
 npm -v
8.19.0
```
```json
"typescript": "^4.9.5",
```

![image](https://github.com/vuejs/language-tools/assets/512816/df8d9465-a107-4ee3-91c9-f81a41d9d63a)

![image](https://github.com/vuejs/language-tools/assets/512816/9fc26aea-8c11-4c01-b399-15806d54c74a)

![image](https://github.com/vuejs/language-tools/assets/512816/e6a9a638-6667-43c3-9546-3da0d02f35df)

This is all happening on Windows 10, sadly.

**Comment by leegee** [comment]
Similar issue #2663 but not relevant as 'JS & TS nightly' is not installed

![image](https://github.com/vuejs/language-tools/assets/512816/85cbb7c7-71b0-44b0-afab-7b72235ef516)

**Comment by doooooit** [comment]
I got same error alert, but only Volar is installed, no other plugins

alert output:
```
<--- Last few GCs --->

[24204:0x5147d50]    22134 ms: Scavenge 1992.8 (2069.4) -> 1991.0 (2071.1) MB, 7.2 / 0.0 ms  (average mu = 0.749, current mu = 0.343) allocation failure 
[24204:0x5147d50]    22157 ms: Scavenge 1994.6 (2071.1) -> 1993.0 (2090.4) MB, 10.3 / 0.0 ms  (average mu = 0.749, current mu = 0.343) allocation failure 
[24204:0x5147d50]    23276 ms: Mark-sweep 2006.2 (2090.4) -> 1999.6 (2096.4) MB, 1071.6 / 0.0 ms  (average mu = 0.550, current mu = 0.139) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02960 node::Abort() [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 2: 0xa18149 node::FatalError(char const*, char const*) [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 3: 0xcdd22e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 4: 0xcdd5a7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 5: 0xe94c15  [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 6: 0xea48dd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 7: 0xea75de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 8: 0xe68b1a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
 9: 0x11e1886 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
10: 0x15d54f9  [/home/shangke/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node]
[Error - 12:35:04 PM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

environment：
node: v14.21.3
vscode: 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435)
system: Windows 11 Pro 22H2 (22621.1702)

**Comment by leegee** [comment]
> I got same error alert, but only Volar is installed, no other plugins

Since the error message is different, I guess it should have a new ticket.

**Comment by leegee** [comment]
After weeks of this problem, I updated to the latest version of Typescript, but the issue persisted.

I removed the `@vue/tsconfig` dep that the scaffolding app used, and the above error stops -- I now have the below, which is a new issue.

![image](https://github.com/vuejs/language-tools/assets/512816/0799a410-e8fc-49f2-a299-f2a677edb1e8)


![image](https://github.com/vuejs/language-tools/assets/512816/040f7cac-03e5-4097-a810-17193d38f7b7)
