### ISSUE TITLE
JSDoc does not work on template scoped prop

### ISSUE THREAD

**Issue by ludwig801** [vuejs/language-tools#3247]
### Issue

When using `<template #slot="props">` syntax for scoped slots I find it sometimes useful to type the scoped properties through the use of `<template #slot="/** @type {MyType} */ props">` syntax.

This worked pretty well in for older versions of the extension. However, in 1.7.x versions, this seems to not work anymore, only accepting the following syntax: `<template #slot="/** @type {{ subProp: SubPropType }} */ { subProp }">`.
This is obviously not ideal since it requires me to deconstruct an object I do not intend to deconstruct.

Is this a bug or intended behaviour?

### Expectation
`<template #slot="/** @type {MyType} */ props">` to type `props` correctly as being of `MyType`.

### Reality
`<template #slot="/** @type {MyType} */ props">` type is not interpreted.

**Comment by johnsoncodehk** [comment]
This is expected, valid syntax should be `<template #slot="props: MyType">`.

**Comment by ludwig801** [comment]
> This is expected, valid syntax should be `<template #slot="props: MyType">`.

What if one is not in a TypeScript environment, would it still work properly?

**Comment by so1ve** [comment]
Would `(/** @type {MyType} */ props)` work?
