### ISSUE TITLE
Volar Takeover 模式。导致每次导入vue模块内容变成添加导入；

### ISSUE THREAD

**Issue by JianGuoHt** [vuejs/language-tools#3253]
### 打开Volar Takeover 模式时；
每一次导入vue模块内容都是添加导入
出现多行vue导入语句，导致eslint规则校验不成功以及代码重复度过高。
望解决。☕☕☕
![image](https://github.com/vuejs/language-tools/assets/48642259/d69baa5e-2d51-401b-b51d-f1c512b0261f)
![image](https://github.com/vuejs/language-tools/assets/48642259/f3dc4654-56ef-442c-8bdc-1d1ebca8be48)

### 没有打开Volar Takeover 模式时：
![image](https://github.com/vuejs/language-tools/assets/48642259/4693fdbf-e7f5-49e7-970f-b84651aae84a)
![image](https://github.com/vuejs/language-tools/assets/48642259/3826d82a-452a-4cd1-aaaa-42bc2dbeac54)

**Comment by F-OlO-Y** [comment]
#2747

**Comment by so1ve** [comment]
Duplicate of #2747
