### ISSUE TITLE
vue-tsc 1.6.5: leave-active-class does not exist in type TransitionProps

### ISSUE THREAD

**Issue by akarmes** [vuejs/language-tools#3255]
Package versions:
- vue-tsc 1.6.5
- typescript 5.1.3
- vue 3.3.4

After updating typescript 5.0.4 => 5.1.3, vue-tsc shows following error for Transition attributes:

```txt
error TS2345: Argument of type '{ name: string; leaveActiveClass: string; "leave-active-class": string; }' is not assignable to parameter of type 'TransitionProps'.
  Object literal may only specify known properties, and '"leave-active-class"' does not exist in type 'TransitionProps'.

3     <Transition name="saving" leave-active-class="foobar">
```

Related code looks this way:
```
<template>
  <Teleport to="body">
    <Transition name="saving" leave-active-class="foobar">
  ...
```

**Comment by fanckush** [comment]
same problem

**Comment by vieruuuu** [comment]
bump

**Comment by jd-solanki** [comment]
Hi @johnsoncodehk 

I'm also getting a similar error and I realized that this is because vue-tsc now complains if prop is in kebab-case. @akarmes @fanckush try converting prop name to camelCase and probably error will get resolved. However, I have eslint setup and it auto converts the prop to kebab-case.

**Comment by jd-solanki** [comment]
With kebab-case:
![image](https://github.com/vuejs/language-tools/assets/47495003/c026e618-ae98-4d57-ba89-809320622f28)

With camelCase (no error):
![image](https://github.com/vuejs/language-tools/assets/47495003/8e295741-b949-43d2-b2ed-c990c4947936)

**Comment by QiuFeng54321** [comment]
Seems like generic components have this issue as in #3256 .
