### ISSUE TITLE
v1.8.10 Generics: defineComponent missing type overload definition when importing a script setup generic component

### ISSUE THREAD

**Issue by Chuuone** [vuejs/language-tools#3257]
Importing a child component defined using <script setup lang="ts" generic="T extends Record<string, unknown>">
into a component defined using <script lang="ts"> and defineComponent() will cause typing issue specified below.

**Example breakdown**
Define a child component
// TableComponent.vue
```
<script setup lang="ts" generic="TRow extends DataType = DataType">
```
Create a parent component defined using 
MainComponent.vue
```
<script lang="ts">
import TableComponent from "TableComponent.vue";

defineComponent({components: {TableComponent});
</script>
```
**The typing issue**
![Screenshot 2023-06-07 095116](https://github.com/vuejs/language-tools/assets/38732807/f9e5f9f2-8bd0-4ac3-b073-424e105fe289)

**Comment by Chuuone** [comment]
#2709 Seems to be a reoccurrance of this problem

**Comment by so1ve** [comment]
Not sure why, but I can't reproduce it now.

**Comment by Chuuone** [comment]
> Not sure why, but I can't reproduce it now.

I just tried it in v.1.8.11 in case it was fixed there. Unfortunately isn't.

Are you reproducing in stackblitz or vscode? I've found the issue is not reproducible in stackblitz.

**Comment by so1ve** [comment]
In vscode. This is my reproduction: https://github.com/so1ve/language-tools/tree/fix/issue-3257. Am I doing something wrong?

**Comment by Chuuone** [comment]
Your parent component seems to have a script setup **<script setup lang="ts">** and export defineComponent() all in one. In my example we just use defineComponent on parent and setup generic in child. :)

Is using both valid or a mistake?

**Comment by so1ve** [comment]
![](https://github.com/vuejs/language-tools/assets/58381667/94c55530-120e-4c22-b6e0-4a4f9d859e21)![](https://github.com/vuejs/language-tools/assets/58381667/e167f8b6-6aec-4c20-9a48-f1c2fc88f10d)
![](https://github.com/vuejs/language-tools/assets/58381667/100a5095-7c3a-44e7-9b4b-db8f7d87a348)

:(

**Comment by Chuuone** [comment]
Alright, that is odd. Well i am using ts 5.2.2 and Volar 1.8.11. I think i need to try to fork your test and see if it behaves then in case something in my project is throwing things off.

Out of curiosity, are shims defined in your test?

`
declare module "*.vue" {
	import type {DefineComponent} from "vue";

	const component: DefineComponent<{}, {}, any>;

	export default component;
  }
  `

**Comment by so1ve** [comment]
No :D You don't need this if you enable take over mode.

**Comment by Chuuone** [comment]
Think i need some help with the fork. I forked the project, checked out your branch fix/issue-3257 

Ran npm i
`
npm i 
`

The problem is, there is no type hinting going on whatsoever. Note how i am using a **Comp** thats not defined, and things do not hint.

![Screenshot 2023-09-18 083023](https://github.com/vuejs/language-tools/assets/38732807/b688dbb5-c69b-4214-aebe-a6acbc9bab70)

**Comment by Chuuone** [comment]
I think i figured it out. The error happens with this Emit definition. (Defined in child component)

Here is a minimal reproduction.

```Comp.d.ts
<script setup lang="ts" generic="TRow extends DataType = DataType">
import type {DataType} from "./Comp";

export type Emits = {
	"on-change-active-sort-field": [activeSortHeading: Record<string, unknown> | null];
}

defineEmits<Emits>();
</script>
```

**Comment by so1ve** [comment]
Thanks @Chuuone, this reproduction works 👍
