### ISSUE TITLE
Can't define variables in inline event handler: "Property does not exist on type"

### ISSUE THREAD

**Issue by scscgit** [vuejs/language-tools#3258]
When defining a variable like this:
```vue
@click="() => {
  const x = 1
  if (x === 1) {
  }
}"
```
it yields two errors:
* `'x' is declared but its value is never read. ts(6133)`
* `Property 'x' does not exist on type 'MyComponent'. ts(2339)`

The code using such variable **works correctly**, and I've been using this syntax since Vue 2 with **Vetur**. After migrating to Vue 3 with **Volar**, this type safety and inference in VS Code fails.

![image](https://github.com/vuejs/language-tools/assets/3118390/7ea4db94-af91-41b5-add1-b381d4337383)

**Comment by so1ve** [comment]
Notes:

When using `script setup` only, everything is good
When using `script lang="ts"`, only `'x' is declared but its value is never read. ts(6133)`
When using `script setup lang="ts"`, `'x' is declared but its value is never read. ts(6133)` and `Property 'x' does not exist on type '...'. ts(2339)`
