### ISSUE TITLE
更新最新版的VSCode之后，插件版本变成了1.2.0

### ISSUE THREAD

**Issue by WangJincheng4869** [vuejs/language-tools#3262]
![image](https://github.com/vuejs/language-tools/assets/41162158/2607738c-7649-41a9-ba86-4acb1336f2b7)
```
版本: 1.79.0 (user setup)
提交: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
日期: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by longshihui** [comment]
i have same problem, i select to latest version, but it always use 1.2.0

**Comment by longshihui** [comment]
vscode downgrade to 1.78.2 and volar downgrade to 1.6.4, the plugin is work

**Comment by xunmi1** [comment]
Duplicate https://github.com/vuejs/language-tools/issues/3198, you can opt-in to the latest pre-release channel again.
