### ISSUE TITLE
volar 功能失效

### ISSUE THREAD

**Issue by webarn** [vuejs/language-tools#3265]
vscode版本：
版本: 1.79.0
提交: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
日期: 2023-06-07T14:29:00.206Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 20.6.0

volar 发布版无效，切换至预览版也是无效

都是any类型，无提示。检测不到任何错误，只有语法高亮的功能。

<img width="450" alt="image" src="https://github.com/vuejs/language-tools/assets/23495159/9fabf19e-6a8b-4386-8276-f64afcd57944">
typescript版本为：5.1.3

**Comment by WangJincheng4869** [comment]
我也有同样的问题，此插件已经不可用

**Comment by zouyaoji** [comment]
+1

**Comment by fan19900404** [comment]
同样有这个问题，我怀疑是typescript5.1.3版本问题，我把typescript切换到 4.16版本，就恢复正常了

**Comment by 1464691115** [comment]
> 同样有这个问题，我怀疑是typescript5.1.3版本问题，我把typescript切换到 4.16版本，就恢复正常了 ![image](https://user-images.githubusercontent.com/9610241/244847377-b295b3c9-7c9c-4baf-bf97-d11809133db4.png) ![image](https://user-images.githubusercontent.com/9610241/244847361-c326faf3-d0e5-41e0-ba3f-7a36b84ce5f3.png)

感谢！

**Comment by Mutueye** [comment]
Same here. Downgrade typescript to 5.0.4 fixes the problem.

**Comment by segevfiner** [comment]
The plugin isn't working for me either with VS Code 1.79.0 which defaults to TypeScript 5.1.3. Using the workspace version of 5.0.4 fixes it. So likely the plugin isn't compatible with TypeScript 5.1.3.

**Comment by so1ve** [comment]
Duplicate of #3268
