### ISSUE TITLE
Component type is missing

### ISSUE THREAD

**Issue by JohMun** [vuejs/language-tools#3268]
I have just created a project with vite `npm create vite@latest`:

The type of the component is always `any`:

![image](https://github.com/vuejs/language-tools/assets/20238661/3e408c87-da48-42d1-9bbc-6165462d3de9)

**Comment by JavanShen** [comment]
同样的问题

**Comment by zhazhazhu** [comment]
我也是

**Comment by jesspinklet** [comment]
Same here, it's really annoying .

**Comment by zhazhazhu** [comment]
I haven't found a solution yet. I'm helpless.

**Comment by xmatthias** [comment]
https://github.com/vuejs/language-tools/discussions/3234 seems to be related.

I've not had this with vscode versions < 1.79.0 - but encountered it with 1.79.x insiders - and since updating vscode stable a few minutes ago, also on stable.

**Comment by eimigueloliveir** [comment]
I have the same problem, I have the most stable version of vs code (1.79.0) and the most current version of the extension

**Comment by longshihui** [comment]
same problem, what happen?

**Comment by xue-lei** [comment]
same problem

**Comment by hopkins385** [comment]
Same problem.

I'm using pre-realease of Volar & TypeScript Volar Plugin (but switching back to stable doesnt help either)
Volar v1.7.11

VSCode
Version: 1.80.0-insider
Commit: 6cd5ac180a6362b45b415a624f62173caf7428a1
Date: 2023-06-09T18:51:41.233Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by tobiasdalhof** [comment]
I can confirm this issue

```
Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by so1ve** [comment]
FYI to solve this issue temporarily, install typescript@5.0 in your workspace and switch to it:

![image](https://github.com/vuejs/language-tools/assets/58381667/7498c2f4-6bd5-4cc0-99b1-f8d91c965c43)
![image](https://github.com/vuejs/language-tools/assets/58381667/b36bde8d-c50a-4346-846c-821763b20bad)

The new version of vscode ships typescript@5.1 which breaks the type.

**Comment by YornQiu** [comment]
This issue occurs every few version updates. It's a really long-term issue.

**Comment by l406054531** [comment]
github上已经不提供typescript@5.2以下的版本下载了。。。怎么搞

**Comment by 1071125093** [comment]
same problem

**Comment by hansonfang** [comment]
same here

**Comment by so1ve** [comment]
I did some investigations and found the reason: the type `__VLS_GlobalComponents` defined in `__VLS_types.d.ts` cannot be automatically loaded in typescript 5.1.

**Comment by so1ve** [comment]
Just found the reason: [Link](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBA+jBqAZAyjAkgZwIIDsQB4AVAPigF4oAjAe2oBsIBDHKCAD2AhwBMMoAKQqw5deUHBABuEAE5QA-FGAyArtABcUAGaM6GCAEoFS1Ru279AbgBQoSLAQoYABQCWAYwDWAOWrBcBFgANFAAQqQUcEiomAH4WKTsnDx8ymrGoVCaWDbWAPR5UAACwBgAtK4A5jjUMhC24NCM5FCuALZgtcD8AOSSaj0GAHQA4nTUlLoAwtQd1BI4pfmFUFAAevLWDfZRTmMT07OdC6Xky6vrmwCQBcWlFdW19Ve7qG5evv54+O2dMt19AbDfaTOgzOYnDAhADeAF9iFs7NBXjAQYcIVxSgAmM63VYbaw3QolcpVGp1Qko94+PxxZggGHw6xAA)

Unresolved any is no longer "any" ≧ ﹏ ≦

**Comment by so1ve** [comment]
Filed an issue: https://github.com/microsoft/TypeScript/issues/54630

**Comment by sereneinserenade** [comment]
I updated my vscode to May 2023 version, same started happening for me, downgraded to `April 2023 (version 1.78)` version and it works again. ¯\_(ツ)_/¯

**Comment by so1ve** [comment]
> I updated my vscode to `May 2023 version`, same started happening for me, downgraded to `April 2023 (version 1.78)` version and it works again. `¯\_(ツ)_/¯`

Because the latest VSCode ships typescript 5.1.3
