### ISSUE TITLE
Unable to focus on Issues currently

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#3271]
[About 200 new issues have been added in the last month](https://www.repotrends.com/vuejs/language-tools), which is big way beyond my load. At the same time I'm working on some major backlogs to avoid blocking 2.0. Here are the ones related to this repo:

- [x] #3148
- [x] TS 5.1.3 compatible
  - #3274
  - #3277
- [x] #3151
- [x] #3264
- [x] #3221
- [x] #3159
- [x] #2524
- [x] #2496

I expect it will take two months to clear the current backlog (not all from this repo), so for existing issues, it may not be processed within two months. If an issue is very important to you, please consider spending a day or two to debug and try to open a PR. Issues with PRs will be processed with the highest priority.

**Please don't urged, since I use "Recently updated" to view issues in reverse order, which actually brings issues down to the lowest order.**

**Comment by wenfangdu** [comment]
Understandable, you've done well.

**Comment by so1ve** [comment]
About ts 5.1.3: #3274

**Comment by ModyQyW** [comment]
Thanks for your great work!

**Comment by laterdayi** [comment]
Thanks for your great work!

**Comment by andrewcourtice** [comment]
Thanks for all of your great work @johnsoncodehk!

**Comment by johnsoncodehk** [comment]
I will deal with the backlog of issues in two weeks.
