### ISSUE TITLE
Props autosuggestions not working

### ISSUE THREAD

**Issue by Lesnock** [vuejs/language-tools#3276]
Props autosuggestions are not working anymore.

Example:

A.vue:

![image](https://github.com/vuejs/language-tools/assets/19783675/6b929504-1f7f-4048-ac83-7c733131e94a)

B.vue:

![image](https://github.com/vuejs/language-tools/assets/19783675/576e7ecd-69e1-4af8-85c7-24fc54229832)

Look how "test" is not showing in the options list.

Even the "missing required prop" is not working anymore with typescript:

![image](https://github.com/vuejs/language-tools/assets/19783675/350cc07f-4e9e-40bf-871b-d3e7cf733159)

Earlier I was able to see the available options for a prop using a typescript Interface, but now, it does not work too...

**Comment by Lesnock** [comment]
Well, I rolled back my typescript to version 5.0.4 and it worked it!

**Comment by so1ve** [comment]
#3277 #3274 Please wait for the next release
