### ISSUE TITLE
Property checking for strongly typed custom elements

### ISSUE THREAD

**Issue by steveworkman** [vuejs/language-tools#3285]
Following up on https://github.com/vuejs/language-tools/issues/2562

That issue, and https://github.com/vuejs/language-tools/tree/master/packages/vscode-vue#usage shows how to register HTML elements with Volar.

When we do that it resolves the tags but it doesn't check the properties - any way to do that?

**Comment by rchl** [comment]
You were told to use

```ts
declare module 'vue' {
  export interface GlobalComponents {
    McButton: McButton;
  }
}
```

and you had issue with `McButton` not type-checking props? I suppose it depends on how `McButton` is typed. You should provide more information.

**Comment by rchl** [comment]
We still don't know what `@orgname/mds-components-utils` is and how it's typed. But it looks like it might not be vue specific typing which would be a problem.

We'd need a complete example project to see exactly what's happening.

**Comment by steveworkman** [comment]
OK, I've got a minimal reproduction repo based on the vite/vue/lit template https://github.com/steveworkman/vue-typings-issue-lit. I've tried this with our internal components and get the same issues

1) The element is always incorrectly typed

<img width="923" alt="Screenshot 2023-07-12 at 22 37 02" src="https://github.com/vuejs/language-tools/assets/994905/b8415d37-6e38-41e5-818a-ec8d9038b791">

It appears to be expecting all properties to be included on the element, including public methods like `render` and click events.

2) It doesn't pick up properties from the class for autocomplete, so without either guessing correctly or looking at the docs, we can't see what the properties are.

<img width="750" alt="Screenshot 2023-07-12 at 22 37 36" src="https://github.com/vuejs/language-tools/assets/994905/d7cfdc0c-178d-45df-8930-90b251de9109">

The good news is that if you do mis-type something, then it picks it up - but the rest of the warnings go away for that element

<img width="1190" alt="Screenshot 2023-07-12 at 22 37 15" src="https://github.com/vuejs/language-tools/assets/994905/f61daafb-79cd-46b7-a330-6f1574d9d141">

I appreciate this isn't quite the same issue I came in with, because this does work is certain scenarios. Let me know how else I can help wit this.

/cc @justinfagani from the Lit team if he or the team knows of IDE & framework integration issues

**Comment by augustjk** [comment]
There are similar issues when trying to add to `JSX.IntrinsicElements` for getting custom element type support in JSX.

A quick and dirty solution is to use `Partial` so maybe something like

```ts
declare module 'vue' {
  export interface GlobalComponents {
    McButton: Partial<McButton>;
  }
}
```

It's not the best solution since it makes everything optional and the "internal" methods still show up but at least won't error.

I'm not sure if this would work but maybe you could try removing internals with something like

```ts
declare module 'vue' {
  export interface GlobalComponents {
    McButton: Omit<McButton, keyof LitElement>; // or whatever base class whose properties you don't want showing up
  }
}
```

**Comment by rchl** [comment]
I'm not an expert but it kinda feels like the Lit components should provide types that are compatible with types that Vue's own `defineComponent` function ends up producing.

Not sure it's in scope of Volar's to support that natively as those don't have much to do with standard Vue components. Those seem to be a web components with a custom render function for Vue support.
