### ISSUE TITLE
1.7.3 syntax highliting non deterministacally breaks in VS Code

### ISSUE THREAD

**Issue by minht11** [vuejs/language-tools#3288]
I am using Volar Pre release 1.7.2/1.7.3 and syntax highliting started to break randomly, sometimes restarting volar/ts helps sometimes it doesn't it never is deterministic what code specifically triggers highliting to break. In stable i do not experience those issues.

https://github.com/vuejs/language-tools/assets/8914032/faadbaeb-899b-4df5-93c0-4c680f5de1a9

**Comment by JoCa96** [comment]
I have this issue with version `v1.8.1` and unfortunately it makes the extension unusable for me.
Is there anyway to see logs or errors for the extension?
