### ISSUE TITLE
Props typing issue

### ISSUE THREAD

**Issue by Rusinas** [vuejs/language-tools#3293]
I have a pretty simple component with this code:
```
<script lang="ts" setup>
type Control = {
  title: string,
  id: string,
}

interface DataCardInputProps {
  buttonText: string,
  controls: Control[]
}

withDefaults(defineProps<DataCardInputProps>(), {
  buttonText: 'Edit',
  controls: [
    {
      title: 'Edit',
      id: 'edit'
    },
    {
      title: 'Delete',
      id: 'delete'
    },
  ]
})
</script>
```
But I got this weird error: 
![image](https://github.com/vuejs/language-tools/assets/42975143/03e7a084-6c98-49dd-97ae-177dee6b20cb)

<details>
  <summary>Error text</summary>
Type '{ title: string; id: string; }[]' is not assignable to type '(props: DataCardInputProps) => Control[]'.
  Type '{ title: string; id: string; }[]' provides no match for the signature '(props: DataCardInputProps): Control[]'.ts(2322)
DataCardTriggerMenu.vue(34, 3): The expected type comes from property 'controls' which is declared here on type 'InferDefaults<DataCardInputProps>'
</details>

Not sure what I am doing wrong, so I think it may be a bug.

**Comment by Rusinas** [comment]
I am stupid, it is supposed to be:
```
controls: () => ([ ... ])
```

Why I forgot about this 😭

**Comment by so1ve** [comment]
So... If your issue has been resolved, consider closing this issue?
