### ISSUE TITLE
Scss parsing issue with @apply #{important}

### ISSUE THREAD

**Issue by riderx** [vuejs/language-tools#3296]
https://stackblitz.com/edit/github-gdkixd-ptbywd

The issue is not visible in stackblitz but if you download the project and open with VSCode you should see the error as well

<img width="1027" alt="CleanShot 2023-06-15 at 19 30 30@2x" src="https://github.com/tailwindlabs/tailwindcss/assets/4084527/ea34e3d6-67bf-47a2-88f0-611ce41a24d4">

**Describe your issue**

scss display one error but all compile properly. I'm not sure here was the right place to post

From here: https://github.com/tailwindlabs/tailwindcss/issues/11434

**Comment by so1ve** [comment]
Can you disable all plugins except volar and check if the issue persists?

**Comment by so1ve** [comment]
Can you disable all plugins except volar and check if the issue persists

**Comment by riderx** [comment]
Sorry, I did bissect with VScode, and I found it was Volar, i should have said it .
<img width="1728" alt="CleanShot 2023-06-17 at 16 25 16@2x" src="https://github.com/vuejs/language-tools/assets/4084527/3767c0e1-d504-4a04-86b8-74866207816d">

**Comment by asvishnyakov** [comment]
I have exactly the same issue. Do you have any suggestions?

**Comment by so1ve** [comment]
@asvishnyakov Hi! Could you please check if this is valid scss syntax? (I'm afk now)

**Comment by asvishnyakov** [comment]
@so1ve yes it is and even well-known issue: https://tailwindcss.com/docs/functions-and-directives#apply (at the end):

> Note that if you’re using Sass/SCSS, you’ll need to use Sass’ interpolation feature to get this to work:

```scss
.btn {
  @apply font-bold py-2 px-4 rounded #{!important};
}
```

**Comment by johnsoncodehk** [comment]
The correct reporting location is https://github.com/microsoft/vscode-css-languageservice.

**Comment by riderx** [comment]
@johnsoncodehk can you give a bit more detail ?
I’m not sure to understand how this is connected do volar use css language service ?

**Comment by johnsoncodehk** [comment]
It's used by `@vue/language-service` -> `volar-service-css`(https://github.com/volarjs/services/blob/master/packages/css/index.ts).
