### ISSUE TITLE
1.80 代码高亮错误

### ISSUE THREAD

**Issue by HignPoint** [vuejs/language-tools#3297]
版本: 1.77.3
提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
日期: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
沙盒化: Yes

Vue Language Features (Volar) V1.80 + TypeScript Vue Plugin (Volar) v1.80
![20230617151200939](https://github.com/vuejs/language-tools/assets/128672886/16a06ce5-2376-421e-b2c7-c0c4e719b307)

退回到 Vue Language Features (Volar) V1.80 + TypeScript Vue Plugin (Volar) v1.6.5 显示正常

**Comment by tjx666** [comment]
那就暂时先用 takeover mode 吧
