### ISSUE TITLE
Volar/Nuxt3 - custom components not properly recognised or highlighted

### ISSUE THREAD

**Issue by EllipticElysium** [vuejs/language-tools#3299]
I created a new nuxt3 app but my custom components are not being correctly highlighted, and hovering / cmd+click does nothing at all.
<img width="343" alt="image" src="https://github.com/vuejs/language-tools/assets/67951653/ecba0237-5966-440d-878c-a65372184435">
<img width="385" alt="image" src="https://github.com/vuejs/language-tools/assets/67951653/e3bc19ab-c1b2-477c-a2d6-29f3b86be78e">

expected:
custom components should be highlighted (green iirc)
hovering over a component should show the component type
cmd+click on a custom component should open the component file

**Comment by so1ve** [comment]
Try upgrading volar to 1.8.0?

**Comment by EllipticElysium** [comment]
@so1ve already using 1.8.0
<img width="752" alt="image" src="https://github.com/vuejs/language-tools/assets/67951653/1e886484-413c-4809-ac1b-b67f65e709b1">

**Comment by so1ve** [comment]
Well... Have you started the dev server or run `nuxt prepare`?

**Comment by EllipticElysium** [comment]
have just tried both, still the same :(
done npm install, run the app and everything is wroking okay, is just this that's not working it seems

**Comment by so1ve** [comment]
Could you please share a minimal reproduction? 🤔 Thanks

**Comment by EllipticElysium** [comment]
i have made my repo public (temporarily) you can see it here - https://github.com/EllipticElysium/ElysiumVentura
is that okay or do you need something else?

**Comment by so1ve** [comment]
Thanks, I'll check it later

**Comment by EllipticElysium** [comment]
@so1ve 
okay, i was doing some experimenting and found something very interesting, it seems the issue happens as soon as i add a script tag to the file
<img width="545" alt="image" src="https://github.com/vuejs/language-tools/assets/67951653/d6f4abef-9fc0-4bb2-acc0-216e79aeb97c">
<img width="280" alt="image" src="https://github.com/vuejs/language-tools/assets/67951653/9c07d2cc-5c6a-4114-be78-4341e7c1ba9d">


I just tried creating a brand new project and same thing happened exactly
pnpm dlx nuxi init test
pnpm install
<open app.vue, add empty script tag>
<img width="251" alt="image" src="https://github.com/vuejs/language-tools/assets/67951653/7e9716d9-793d-409d-8052-9b3c0919ac15">

**Comment by EllipticElysium** [comment]
have also just tried disabling every extension and only enabling volar, still the exact same happening on the brand new project
I'm very confused, as I can't see anyone else having this issue when i google it, but is so easy to reproduce

I'm on an m1 macbook pro 16" with the latest os (Ventura 13.4)
running the latest version of vscode (installed via homebrew)
<img width="345" alt="image" src="https://github.com/vuejs/language-tools/assets/67951653/49118c5a-4351-4f50-a702-cb7f2662994f">

**Comment by Fanoflix** [comment]
@EllipticElysium I think its an issue with the latest Volar and Vue Typescript plugin versions. Syntax highlighting is also broken on SFCs in Vue3 Project's `<script setup lang="ts">`.

**Comment by larrasu** [comment]
Have you tried enabling [Take Over Mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode)?

**Comment by EllipticElysium** [comment]
@larrasu still the same unfortunately 😔

**Comment by johnsoncodehk** [comment]
In order to define a valid component, `export default` is required, please try

```html
<script>
export default { };
</script>
```

or use `<script setup>`

```html
<script setup></script>
```

**Comment by EllipticElysium** [comment]
@johnsoncodehk that's worked, thanks! :)

**Comment by EllipticElysium** [comment]
anyone who come to this later, the repo is now private again, sorry!

**Comment by mgiraldo** [comment]
i just started having this problem recently. tried downgrading to previous versions of volar with no success... tried an extension bisect also... my script tags have a default export but all my custom components have now the same color as regular html tags. if i remove/comment the script section of my components they are properly color hightlighted:

<img width="721" alt="image" src="https://github.com/vuejs/language-tools/assets/133020/cf24af3b-5cd6-4114-9dbb-44dc42e5f72b">

<img width="721" alt="image" src="https://github.com/vuejs/language-tools/assets/133020/35f81f40-c036-4e25-aca4-afa219ab7d8f">

**Comment by so1ve** [comment]
@mgiraldo Please open a new issue with minimal reproduction, thanks!

**Comment by mgiraldo** [comment]
done: #3620
