### ISSUE TITLE
Nuxt3 global component do not have props type

### ISSUE THREAD

**Issue by baixiaoyu2997** [vuejs/language-tools#3304]
https://stackblitz.com/edit/nuxt-starter-p28a3j?file=pages%2Findex.vue

i can't see any type notice on `y-test` component, and i already use takeover mode

<img width="493" alt="image" src="https://github.com/vuejs/language-tools/assets/9149999/deb1914c-99f1-45c5-9c70-86e63f76825e">

**Comment by so1ve** [comment]
Duplicate of #3188

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/nuxt/nuxt/pull/26541
