### ISSUE TITLE
volar can't show props comments with the prop which has default value?

### ISSUE THREAD

**Issue by ideagay** [vuejs/language-tools#3307]
i use vue-tsc to generate .d.ts，some prop has default value like showClose prop，then in vscode， the volar can‘t show the 'showClose' comments
<img width="535" alt="image" src="https://github.com/vuejs/language-tools/assets/4416844/cab9609c-086c-4986-ad13-e56803beb0a0">
<img width="914" alt="image" src="https://github.com/vuejs/language-tools/assets/4416844/071e9c77-e055-4762-beff-030b27270707">
this is the problem of vue-tsc or volar?

**Comment by johnsoncodehk** [comment]
This is a type issue with defineComponent, if the latest version still doesn't work, please report it to Vue core.
