### ISSUE TITLE
volar is broken after updates

### ISSUE THREAD

**Issue by aenzenith** [vuejs/language-tools#3308]
I'm using Vue 3.3.4 with Laravel. After the last update, my editor throws in series of errors which are contains these messages;
`"The Vue Syntactic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information."` and `"The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information."`

So that, my solution was rollback to v1.6.5.

**Comment by so1ve** [comment]
#3282

**Comment by johnsoncodehk** [comment]
Duplicate of #3282
