### ISSUE TITLE
Generic inference doesnt work with PropType

### ISSUE THREAD

**Issue by Fuzzyma** [vuejs/language-tools#3311]
This issue references a discord discussion: https://discord.com/channels/793943652350427136/1109024933402640456

As of now, vues compiler cannot handle complex types for generics. So a component like this doesnt work correctly:

```vue
<script lang="ts">
type SwitchByBoolean<T extends boolean, V> = false extends T ? V : V[];
</script>

<script lang="ts" setup generic="T extends boolean, V extends SwitchByBoolean<T, string>">
const props = defineProps<{
  modelValue?: V;
  multiple?: T;
}>();
```

This component accepts a string array if multiple is true, otherwise it accepts only a string.

Since vue cant analyze the types properly, it will not cast the props.

e.g. usually when writing this:

```vue
<MyCompoennt boolean-flag />
```

It will result in `props.booleanFlag === true`. However, in the above example, `multiple` would be an `empty string`.

The solution would be to use `PropType`:

```vue
<script setup lang="ts">
const props = defineProps({
  modelValue: {
    type: [String, Array] as PropType<V>,
  },
  multiple: {
    type: Boolean as PropType<T>,
    default: false,
  },
});
</script>
```

This correctly enforces the boolean flag. However, type inference is broken now.
The types dont enforce the array-string / string

**Comment by so1ve** [comment]
IMO it's a vue core problem

**Comment by johnsoncodehk** [comment]
Closed due to unable to reproduce in latest version.

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk can you please also add a test for only passing "multiple" without true or false? And the check if it is cast to "true" correctly or to an empty string? Because that was the problem I had

Could you show me the full expected test code? Thanks.

**Comment by Fuzzyma** [comment]
Usage as Boolean prop:

```vue
<template>
	<HelloWorld :multiple :modelValue="['a']" />
        <HelloWorld :modelValue="a" />
        <!-- @vue-expect-error -->
	<HelloWorld :modelValue="['a']" />
	<!-- @vue-expect-error -->
	<HelloWorld :multiple :modelValue="'a'" />
</template>

<script lang="ts" setup>
import HelloWorld from './component.vue'
</script>
```

Component maybe with extra check:

```vue
<script lang="ts">
type SwitchByBoolean<T extends boolean, V> = false extends T ? V : V[];
</script>

<script lang="ts" setup generic="T extends boolean, V extends SwitchByBoolean<T, string>">
const props = defineProps<{
	modelValue?: V;
	multiple?: T;
}>();

// not sure how to produce a testfailure
expect(typeof props.modelValue).toBe('boolean')
</script>
```

The extra expect is neccessary because vue is casting boolean props to true/false depending on if there are present or not.
However, with generic prop types, vue is not able to figure out the PropType of `modelValue` and will use its default behavior (so it will be undefined or an empty string instead)

**Comment by Fuzzyma** [comment]
@johnsoncodehk tagging you because I am not sure if you are notified about closed issues
