### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by beny996** [vuejs/language-tools#3314]
Auto import of components now adds import statement in template, instead of script part of a file.

**Comment by beny996** [comment]
![Screenshot from 2023-06-26 16-02-11](https://github.com/vuejs/language-tools/assets/94617004/6fd6488b-a6f6-4813-86c4-e994bd05ba1a)

**Comment by so1ve** [comment]
I cannot reproduce it 👀 Does tags' order matter? @beny996

**Comment by beny996** [comment]
No, it doesn't. Start typing the components name, when autocomplete kicks in, press tab/enter and it gets imported in template. The component is being registered like it should be, inside of components. As you can see in the picture. Also, i noticed that now when i use autocomplete, it imports it with kebab case, in the template part. It used to be <AppButton /> and now its <app-button/>. @so1ve

**Comment by so1ve** [comment]
Thanks, I'll check it.

**Comment by beny996** [comment]
You need more info or we can change label? @so1ve

**Comment by so1ve** [comment]
Oops, sorry for the delay :(

**Comment by beny996** [comment]
Any updates? @so1ve

**Comment by beny996** [comment]
[Screencast from 07.07.2023. 15:58:05.webm](https://github.com/vuejs/language-tools/assets/94617004/3b3e6c46-4019-452b-af03-cf0f3e0b7da6)

**Comment by so1ve** [comment]
That's pretty weird, I still cannot reproduce it in my machine. Maybe we need Johnson to look into this.

**Comment by beny996** [comment]
Maybe we do. :smile: @so1ve

**Comment by tkat** [comment]
Same here. Worked correctly up to version 1.6.4. 

Issue seems to occur only with components that use the Options API. It appears to work fine in the same project when using components that utilize the Composition API.

**Comment by so1ve** [comment]
I still cannot reproduce this problem, but I can reproduce another one:

![](https://github.com/vuejs/language-tools/assets/58381667/a6a4a316-d84e-4636-b4b3-fe185f6ebb12)

**Comment by beny996** [comment]
This seems to be fixed, as i'm not experiencing the bug anymore. Maybe we can close it? @so1ve

**Comment by so1ve** [comment]
@beny996 If you are sure this issue has been fixed, feel free to do so :)
