### ISSUE TITLE
Volar interferes with VS Code's hex color swatches

### ISSUE THREAD

**Issue by ffxsam** [vuejs/language-tools#3315]
I ran a VS Code extension bisect and identified Volar as the root cause of this issue.

When a project loads up, I can see that I initially have color swatches next to all hex colors, but once Volar loads, they disappear. See below.

https://github.com/vuejs/language-tools/assets/12532733/b04e5639-381f-4bad-8985-a2294e4411b0

**Comment by johnsoncodehk** [comment]
This may be an issue with VSCode, please report it to VSCode. Because the Vue langauge server only provides color infos through the LSP, the Vue extension will not actively push this.
