### ISSUE TITLE
Cannot find type definition file for

### ISSUE THREAD

**Issue by gewisser** [vuejs/language-tools#3317]
Hi, guys!

Something broke after the update. I don't know where to look for the problem

![image](https://github.com/vuejs/language-tools/assets/5417292/7643c0c7-2fad-462c-99c9-0f5c1c484a4e)
![image](https://github.com/vuejs/language-tools/assets/5417292/d5f9ced1-feaf-4b54-9ba4-12a3cef846a8)

**Comment by so1ve** [comment]
Could you please check which version introduced this regression?

**Comment by christhofer** [comment]
@so1ve For me it's only on 1.8.1 trying to `npm run build`
reverting back to 1.8.0 solves the issue.

**Comment by gewisser** [comment]
> Could you please check which version introduced this regression?

i doubt it is `vue-tsc`. Most likely some kind of dependency.

I had `"vue-tsc" version: "^1.6.5"`
Since the **last update** of `package-lock.json` it has been working.

Now if I just **delete** `package-lock.json` and `node_modules` and run `npm install` with version `"vue-tsc": "^1.6.5"` , this kind of error appears

**Comment by christhofer** [comment]
Tried 1.8.3, still getting the same error:

```
error TS2688: Cannot find type definition file for ''.
  The file is in the program because:
    Entry point for implicit type library ''


Found 1 error.
```

Here's my dependencies, in case this is caused by incompatibilities with certain package(s).
<details>
  <summary>Dependencies</summary>

  ```json
  "dependencies": {
    "@headlessui/vue": "^1.7.14",
    "@sentry/vue": "^7.57.0",
    "axios": "^1.4.0",
    "clipboard-copy": "^4.0.1",
    "date-fns": "^2.30.0",
    "dompurify": "^3.0.4",
    "easymde": "^2.18.0",
    "firebase": "^9.23.0",
    "highcharts-vue": "^1.4.2",
    "pinia": "^2.1.4",
    "radash": "^11.0.0",
    "sortablejs": "^1.15.0",
    "sortablejs-vue3": "^1.2.9",
    "v-money": "^0.8.1",
    "v-money3": "^3.24.0",
    "vue": "^3.3.4",
    "vue-cropperjs": "^5.0.0",
    "vue-router": "^4.2.2",
    "vue3-easymde": "^1.0.1"
  },
  "devDependencies": {
    "@gradin/tailwindcss-scrollbar": "^3.0.1",
    "@gradin/tailwindcss-skeleton-screen": "^1.0.2",
    "@types/dompurify": "^3.0.2",
    "@types/node": "^20.3.3",
    "@types/vue-cropperjs": "^4.1.2",
    "@typescript-eslint/eslint-plugin": "^5.60.1",
    "@typescript-eslint/parser": "^5.60.1",
    "@vitejs/plugin-vue": "^4.2.3",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.44.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "eslint-plugin-vue": "^9.15.1",
    "postcss": "^8.4.24",
    "postcss-import": "^15.1.0",
    "rollup-plugin-visualizer": "^5.9.2",
    "stylelint": "^15.9.0",
    "stylelint-config-standard": "^33.0.0",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.1.6",
    "vite": "^4.3.9",
    "vue-tsc": "^1.8.0"
  }
  ```
</details>

**Comment by rchl** [comment]
And how does your `tsconfig.json` look like?

**Comment by christhofer** [comment]
@rchl does it matter?
Is there a breaking change between 1.8.0 to 1.8.1 involving the tsconfig?

Here's mine:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "useDefineForClassFields": true,
    "moduleResolution": "Node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "lib": [
      "ESNext",
      "DOM"
    ],
    "skipLibCheck": true,
    "baseUrl": "./src",
    "paths": {
      "@/*": [
        "*"
      ]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./src/types"
    ]
  },
  "vueCompilerOptions": {
    "jsxTemplates": false,
    "narrowingTypesInInlineHandlers": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

**Comment by christhofer** [comment]
> i doubt it is `vue-tsc`. Most likely some kind of dependency.
> 
> I had `"vue-tsc" version: "^1.6.5"` Since the **last update** of `package-lock.json` it has been working.
> 
> Now if I just **delete** `package-lock.json` and `node_modules` and run `npm install` with version `"vue-tsc": "^1.6.5"` , this kind of error appears

@gewisser 
in package.json, having "^1.6.5" and do `npm install` will install the latest v1, which is 1.8.1, or now it's 1.8.3
unless you change it to just "1.6.5", then it will install 1.6.5 exactly.

**Comment by rchl** [comment]
tsconfig.json configuration affects everything that Volar does.
Providing as much information as possible can help in figuring out what the issue is.
Even better if you would provide a repo that reproduces.

**Comment by christhofer** [comment]
Tried to figure out the file / config that causes this issue.
Found out the issue is using `typeRoots` property on `tsconfig.json`

`npm run build` using vue-tsc@1.8.0    works
`npm run build` using vue-tsc@1.8.1+  error

Here is the reproduction https://github.com/christhofer/repro-vuetsc-issue-3317

```sh
git clone https://github.com/christhofer/repro-vuetsc-issue-3317.git
cd repro-vuetsc-issue-3317
npm install
npm run build
```

**Comment by gewisser** [comment]
> > i doubt it is `vue-tsc`. Most likely some kind of dependency.
> > I had `"vue-tsc" version: "^1.6.5"` Since the **last update** of `package-lock.json` it has been working.
> > Now if I just **delete** `package-lock.json` and `node_modules` and run `npm install` with version `"vue-tsc": "^1.6.5"` , this kind of error appears
> 
> @gewisser in package.json, having "^1.6.5" and do `npm install` will install the latest v1, which is 1.8.1, or now it's 1.8.3 unless you change it to just "1.6.5", then it will install 1.6.5 exactly.

\+ 
Then the last version that works for me is 1.7.14

**tsconfig.json**
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["ESNext", "DOM"],
    "skipLibCheck": true,
    "paths": {
      "~/*": ["src/*", "./src/*"],
      "~shared/*": ["src/common/shared/*"],
      "~common/*": ["src/common/src/*"]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.vue",
    "node_modules/**/*.d.ts"
  ],
  "references": [{ "path": "./tsconfig.node.json" }]
}

```
**tsconfig.node.json**
```json
{
  "compilerOptions": {
    "composite": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```

**Comment by aoor9** [comment]
I'm encountering the same issue after upgrading Nuxt from v3.6.5 to v3.7.1

Node: v18.17.1
OS: Ubuntu 22.04
vue-tsc: 1.8.10
Typescript: 5.1.6
![Schermata del 2023-09-06 14-51-42](https://github.com/vuejs/language-tools/assets/94787322/3338732d-6261-4251-8575-a933a94dc23d)

**Comment by aoor9** [comment]
> Interesting! Tried yarn and pnpm, they don't have this issue. Seemed this issue is npm-specific

Is it because you have `typeCheck` disabled? Anyway I found more details?

**Comment by so1ve** [comment]
@aoor9 No, I just run the `build` script. PNPM and Yarn works, but npm fails.

**Comment by aoor9** [comment]
Something wrong with my tsconfig.json?

```
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "skipLibCheck": true,
    "typeRoots": ["./@types", "./node_modules/@types"],
    "baseUrl": "./"
  },
  "exclude": ["node_modules"],
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node"
  }
}
```

**Comment by ysya** [comment]
> Interesting! Tried yarn and pnpm, they don't have this issue. Seemed this issue is npm-specific

Nope, also have same issue with pnpm 8.10.2.

**Comment by liana-p** [comment]
same issue
