### ISSUE TITLE
Remove space inside double curly braces in vue template 

### ISSUE THREAD

**Issue by mirko77** [vuejs/language-tools#3319]
I have the opposite problem mentioned in #2350 

Volar (1.8.1) always add spaces in templates, from {{value}} to {{ value }} no matter what I do

```

"typescript.format.insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": false,
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
"vue.autoInsert.bracketSpacing": false

```
<img width="599" alt="Screenshot 2023-06-23 at 13 05 34" src="https://github.com/vuejs/language-tools/assets/1233305/20b36622-858b-4ff7-baf1-ac03452e796b">

<img width="701" alt="Screenshot 2023-06-23 at 13 05 50" src="https://github.com/vuejs/language-tools/assets/1233305/e9445f38-5a39-4611-bdab-01f803d92ed5">

**Comment by so1ve** [comment]
I cannot reproduce it. Could you please share a video? Thanks!

**Comment by mirko77** [comment]
https://github.com/vuejs/language-tools/assets/1233305/ff8bbaa7-2b79-4497-bbe5-8406b9fd71be

**Comment by so1ve** [comment]
Ah, I see. You mean volar will add a space when you save the file right? But I'm not sure if this is caused by volar. Have you installed prettier?

**Comment by mirko77** [comment]
I have prettier installed but the default formatter is Volar for `.vue` files

**Comment by so1ve** [comment]
Volar currently does not respect this setting when formatting. I'm not sure whether this is a bug or intended behavior, so we may need Johnson to take a look into this :(

**Comment by mirko77** [comment]
Thanks. It is a pain since every time I save a `.vue` it will reformat it so I end up with many unintentional changes in my commits.

**Comment by johnsoncodehk** [comment]
The virtual code used for formatting `{{value}}` is `1 +value+ 1`. TS will insert spaces around the `+` symbol. You need to check whether the TS settings of VSCode can change this behavior.
