### ISSUE TITLE
vue-component-meta: Invalid component prop types when using options api + a prop with a default function

### ISSUE THREAD

**Issue by adamDilger** [vuejs/language-tools#3323]
When importing a component written with Options Api, which has a prop with a `default()` function, the props shown are incorrect. It looks like all the Array methods are shown as props instead (`concat`, `indexOf` etc)

e.g.

```
export default defineComponent({
    data() {
        return {
            dataOne: "Hello World From Data"
        }
    },
    props: {
        propOne: String,
        propTwo: {
            type: String,
            default() {
                return '';
            }
        }
    },
});
```

Example here:

https://play.vuejs.org/#eNrtVU1v2zAM/SuaLmmBJD7k1mUF2q3DtkNbrAV68UWw6VitLQmSnA8E/u+jZNmx0yQ7BcOAGgZskU/UI/lob+mNUtNlBfSKzk2iubLEgK3UdSx4qaS25KssFcm0LMloGrmFg48+D/y3GtgbF4sBrjWewL9wm39jlt1kFvSjlsocjPAe1sacRw1ppIsLC6UqmAVcETL3xBWiJ1LAl5g+CIgpiTwU3Z8mE+JebM4NwdvkcuVSYH4PsRsFBLSWekyYSAcIrdmGlGBzmRrCDIYAv8m4eJPJ7viuLj0azyu5R8M9eUZSzPDi0h+kIOEZh5Qwl3ETe9ww9ZTIQgKevGKbYyceqGyfQ66hLcY86spGx9SaRIqML6avRgoUxdZFjmmCoXkB+kFZLoWJ6RXxHudjRSFXv7zN6grGrT3JIXk7YH81a2eL6aMGA3qJRDqfZXoBtnHfPd3DGt87ZynTqkD0CedvMLKoHMcGdluJFGn3cJ7tTy9FLNOzuVtbEKZNyhF1yNrjY4oyc1U9lvqO7mw68/tiUWMV2zHZTdVunrYkhYwLHxe7ISypG9H702KKqo4FrD0Wkawq/LO/4yIQCIoJK3dpnF0t+pYWh+p3BfkBmD95kbpIyXd3qhNJTHd4zMA/QsG89LqMW4sP9mQ1VjDgWg+qe4B2lxulA3B3RRG5lxa9QnbJZpVIfAffccLiXp4eepyClC/Dq1/ms+vtNnCu63mE6wCMGuRQ//sfro8O/qWDIcFhEnvJjNynum8PFP9hbw//Us7c7f+kFSFsN5uuTiGlwR+JrLCIR8b2zMI+s1bqPxH73t4=

I've drilled down the issue to this line here https://github.com/vuejs/language-tools/blob/9a89c2d7cc5f875794c4c054c91731ce0281d7b1/packages/vue-component-meta/src/index.ts#L276 , so it may be a typescript issue?

We've fixed this issue in our codebase by moving the `data` function below the `props` object, which seems to fix the typing.

Thanks!

**Comment by johnsoncodehk** [comment]
This is a type issue of defineComponent, please report it to Vue core repo.

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5bwC+c6UBcA5AG4CuqNA3AFBsDGRAzvPuDgBeFBmx4CkYjAAUCNnEUoAhjGUyAlIgVLdUVDAZQs23WaXJVygPI4AXHABEACVQAbNxDgB1aG+RwAGJUIHAAIlaOOuak0XCkADRxYFRgPA7y5oopEGC2qA4AyjBQ2ADmSVlwOWAAKgDuEBlxVTAAnmAFcMWlWBUtWWjoygxuslqZVVn6hsa0rAMxi-FxiWykGuxsAPTbcAACMDwAtKgAHp2cMKdQVFBsMjj1cAJgmhoAdAAkNTwfbqg+jAABbsIA
