### ISSUE TITLE
Volar 1.8 no response and high CPU & RAM usage in vue2 project

### ISSUE THREAD

**Issue by SwingCosmic** [vuejs/language-tools#3325]
I  have a large Vue 2.7 + Typescript project and upgrades Volar to 1.8.2, VSCode to 1.79.2. 
Volar 1.6.x and 1.7.x  takes ~30 seconds for linting and syntax highlighting first time, but volar 1.8 takes more than 2 minutes and still no response.

In task manager, one of the volar plugin processes uses ~25%(>1 core) CPU and 2200MB+ memory(`--max-old-space=4096`) , never decreases usage.Normally CPU cost should decrease to 0 if VSCode is inactive and project initialized.

Downgrade Volar to 1.6.4 works well.

The output of `Vue Semantic Server` in VSCode: 
```
[Trace - 14:37:07] Sending request 'textDocument/inlayHint - (6)'.
[Trace - 14:37:08] Sending request 'textDocument/codeLens - (7)'.
[Trace - 14:37:08] Sending request 'textDocument/semanticTokens/range - (8)'.
[Trace - 14:37:08] Received response 'volar/client/tsconfig - (2)' in 58636ms.
[Trace - 14:37:09] Sending request 'textDocument/hover - (9)'.
[Trace - 14:37:10] Sending notification '$/cancelRequest'.
```

No outputs like `Received response 'textDocument/hover - (22)' in 53ms.`

**Comment by SwingCosmic** [comment]
It does sent response , but very very very slow...

![image](https://github.com/vuejs/language-tools/assets/20746516/871bb461-fb61-461b-9c7c-e8d54dadb311)

**Comment by eiqli-zhao** [comment]
Me too！

**Comment by filipbatur** [comment]
Same issue here, vue@2.6.11

**Comment by cinderisles** [comment]
can confirm downgrade to 1.6.4 from 1.8 fixes the issue. didnt try any other versions

**Comment by filipbatur** [comment]
Downgrade to 1.6.2 on vue@2.6.11 fixed the issue for us

**Comment by lallenfrancisl** [comment]
I am experiencing this too, volar has become unusable now

vscode: 1.80.0
vue-typescript-plugin: 1.8.4
typescript: 4.8.4
vue: 3.3.4

**Comment by mounir-ul** [comment]
Me too!

**Comment by mounir-ul** [comment]
Same issue

**Comment by phoenix-oes** [comment]
I don't have a repro, I'm just confirming that Volar 1.8.19 is using nearly **4GB of RAM** on my machine

![volarram](https://github.com/vuejs/language-tools/assets/102561886/4c3f5c26-7aec-4d35-9ec6-932efb74a9b1)

vscode: 1.83.1
vue: 2.7.14

`Vue Semantic Server` does not show any output.

**Comment by daraHK88** [comment]
I love vue but volar uses 8 gigabyte of ram and it's so slow. is there any alternative?

**Comment by johnsoncodehk** [comment]
Closed due to lack of repro.
