### ISSUE TITLE
volar code action on save is slow

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#3326]
![image](https://github.com/vuejs/language-tools/assets/41773861/62192f68-b755-448b-9036-d6a9ebe061a3)

![image](https://github.com/vuejs/language-tools/assets/41773861/3ef2ddce-9511-4bb7-8e88-4088ca8a2178)

After set `"vue.codeActions.enabled": false`, the save operation became very fast.
Seems there is no way to check the vue code action costs now.

After I test, I found if the ts types is resolved completed, the volar code actions would be fast.
Seems the volar code action rely on ts type info...

```
Volar version: v1.8.1
Take Over Mode: yes
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by johnsoncodehk** [comment]
After remote investigation to the project, the project is loading 7xx vue files outside the current directory, resulting in TS high overhead. External vue files are no longer automatically parsed after 1.8.2.

**Comment by rchl** [comment]
Would you mind clarifying how did those external files ended up being referenced and parsed? Specific project configuration or plain bug in directory traversal?

**Comment by eugene-makarov** [comment]
@johnsoncodehk  What is the recommended way to "parse external files"? This change broke our monorepo config and we are getting these errors


```
// packages/webapp/tsconfig.app.json
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["*.vue", "env.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.json", "src/**/*.ts"],
  "exclude": ["src/**/__tests__/*", "node_modules"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@common/*": ["../common/src/*"],
      "@webapp/*": ["../webapp/src/*"]
    }
  }
}
```

After 1.8.2
![image](https://github.com/vuejs/language-tools/assets/99220593/8033a424-83b5-48cb-ad0d-e5aa3d6cc5b8)

**Comment by jmroon** [comment]
@johnsoncodehk bumping the above question, as this is a dealbreaker for a monorepo setup.

**Comment by tjx666** [comment]
I had been staying at 1.8.1 for long time...

**Comment by MatthewAry** [comment]
Just a suggestion, could an option be added to prevent volar from engaging on a save action? I can't find a setting for this.
