### ISSUE TITLE
v1.8.2 - Different tsconfig.json setup

### ISSUE THREAD

**Issue by bianpratama** [vuejs/language-tools#3328]
Version 1.8.2 brought breaking changes on how files are included.

Before the update this is my `tsconfig.package.json`:

```json
{
  "extends": "./tsconfig.json",
  "include": [
    "./@package/index.ts",
  ],
  "compilerOptions": {
    "outDir": "../build/typings",
    "removeComments": false,
    "declaration": true,
    "declarationDir": "build/typings",
    "emitDeclarationOnly": true,
    "noEmit": false
  }
}
```

After update, I need to include all Vue files using glob pattern. And if I also have any Vue files that I don't want to export, e.g. Vue files for demo/Storybook purposes. Then, I need to exclude using glob pattern.

```json
{
  "extends": "./tsconfig.json",
  "include": [
    "./@package/index.ts",
    "./@package/**/*.vue" // Added
  ],
  "exclude": [
    "./@package/**/stories/*.vue" // Added
  ],
  "compilerOptions": {
    "outDir": "../build/typings",
    "removeComments": false,
    "declaration": true,
    "declarationDir": "build/typings",
    "emitDeclarationOnly": true,
    "noEmit": false
  }
}
```

Is this the expected config setup, to include and exclude specific files?

**Comment by johnsoncodehk** [comment]
Yes this is the expected configuration for the current version.

It seems that in the past you were relying on index.ts indirection reference to automatically include .vues (Even if it may not be under `./@package/`), is this the behavior you expected?

**Comment by rchl** [comment]
@johnsoncodehk this is the kind of case I was thinking of when asking the https://github.com/vuejs/language-tools/issues/3326#issuecomment-1608004987 question.

I'm not sure what's the exact case here but if the `index.ts` references the vue files then shouldn't that automatically get included in the project (even if `node_modules` are by default excluded in tsconfig)? That would be the case with plain `.ts` files at least so it would seem to me that volar should attempt to behave the same if possible. And if not then maybe the previous behavior is needed?

(just asking questions here. haven't investigate this myself or know exactly what's the issue...)

**Comment by bianpratama** [comment]
@johnsoncodehk 
Yes, we use `index.ts` for barrel file to references all components that need be bundled. And all of our components are inside the `@package` folder.

Each component folder exported with an `index.ts`:
```typescript
export { default as NeonAvatar } from './NeonAvatar.vue'
export { default as NeonAvatarRandom } from './NeonAvatarRandom.vue'
```
<details><summary>Folder Structure</summary>
<img width="561" alt="Screenshot 2023-06-27 at 15 04 21" src="https://github.com/vuejs/language-tools/assets/7423087/5fc56c92-d4d3-4c0c-8557-d56aa4189591">
</details> 

<details><summary>Entrypoint index.ts</summary>
<img width="559" alt="Screenshot 2023-06-27 at 15 06 29" src="https://github.com/vuejs/language-tools/assets/7423087/aecef43d-da52-49c2-96a7-732c68d72e9b">
</details> 

I expect that all Vue components that are referenced leading to main `index.ts` is automatically included, just like `.ts` or `.js` files, and what @rchl  said above. For now, the recommended `tsconfig` setup is fine for me, as it improves the performance 🚀

**Comment by fdc-viktor-luft** [comment]
This is especially problematic and different from TS file inclusions in Mono-Repo-Setups.

For instance I have to add all `*.vue` files from included packages of the mono repo in all TS-Configs that include these packages. I don't have to do this for the `*.ts` files. But it could be also related to the fact that the "skipLibCheck" doesn't work as in TS.

**Comment by ipcjs** [comment]
Has the issue been fixed?
