### ISSUE TITLE
1.8.2 crashes in Sublime Text

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#3330]
Tried 1.8.2 in ST and gotten:

```
LSP-volar: /Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/@volar/language-core/out/virtualFiles.js:33
LSP-volar:                 const virtualFile = language.createVirtualFile(fileName, snapshot, languageId);
LSP-volar:                                              ^
LSP-volar: 
LSP-volar: TypeError: language.createVirtualFile is not a function
LSP-volar:     at Object.updateSource (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/@volar/language-core/out/virtualFiles.js:33:46)
LSP-volar:     at syncVirtualFiles (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/@volar/language-core/out/languageContext.js:53:34)
LSP-volar:     at Object.get (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/@volar/language-core/out/languageContext.js:34:17)
LSP-volar:     at sync (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/@volar/typescript/out/languageServiceHost.js:87:49)
LSP-volar:     at Object.get (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/@volar/typescript/out/languageServiceHost.js:75:13)
LSP-volar:     at Object.createLanguageService (/usr/local/workspace/artist/artist-web-artist-portal/node_modules/typescript/lib/typescript.js:169190:38)
LSP-volar:     at /Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/volar-service-typescript/out/index.js:87:100
LSP-volar:     at Object.createLanguageService (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/typescript-auto-import-cache/out/index.js:14:25)
LSP-volar:     at /Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/volar-service-typescript/out/index.js:87:30
LSP-volar:     at services.typescript (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.17.1/server/node_modules/@vue/language-service/out/languageService.js:36:63)
```

Let me know if you need more info or it's an obvious issue to you.

**Comment by so1ve** [comment]
@meanspa, @ToyYan, @rchl You are using macos right?

**Comment by johnsoncodehk** [comment]
Do you have `vueCompilerOptions.experimentalAdditionalLanguageModules`? Its API is updated, you may need to update your code.

**Comment by rchl** [comment]
Yes, I do use it in this project.

I guess no need to complain about:
 - semantic versioning not being followed (for the `@volar/language-core` package)
 - lack of proper changelog that would mention the breaking change
 - lack of migration instructions

I suppose it's all obvious to you and you just don't have resources to improve those thing...?

**Comment by johnsoncodehk** [comment]
Of course you can complain, experimental stuff is indeed designed to break at any time, normally it should be documented, I just didn't realize that these APIs were exposed by `experimentalAdditionalLanguageModules`.

**Comment by rchl** [comment]
Yeah, I realize it's experimental but at least from the perspective of `@volar/language-core` it should have been a major, breaking release. And if that would be followed then maybe it would be a reminder when upgrading dep in language server that it can have breaking implications.

**Comment by so1ve** [comment]
I think a minor is enough because it's still experimental, like vue's Reactivity Transform syntax sugar. But yeah, I agree, users seldom read changelog. Thus they are not possible to know there is a breaking change in a patch release. We should show a message when startup.

**Comment by johnsoncodehk** [comment]
`@volar/language-core` is not designed as a user-oriented dependency, I should digest breaking changes in `vuejs/language-tools`, `@volar/language-core` APIs are exposed by `experimentalAdditionalLanguageModules` and the breaking is accidental.

In the final analysis `@volar/*` is still unstable, its version should be 0.x instead of 1.x, but it cannot start from 0.x due to inheriting `vuejs/langauge-tools` version number. So it won't follow semantic versioning, otherwise it might already be at a version greater than 10.x when stable.

**Comment by rchl** [comment]
You say that `@volar/language-core` is not meant for public consumption but then it ties into `experimentalAdditionalLanguageModules` which is much easier to work with when using the types from the package.

Also you could follow semantic versioning for `@volar/language-core`, even if it's meant to be internal.

But no hard feelings and I acknowledge that it was just an oversight.
