### ISSUE TITLE
volar v.1.8.0版本 @volar-plugins/vetur 无效导致element-ui的提示无效

### ISSUE THREAD

**Issue by aslrz-club** [vuejs/language-tools#3334]
已经修改配置如下
module.exports = {
  services: [require("@volar-plugins/vetur").default()],
};
看@volar-plugins/vetur这个版本的包还是2.0.0

**Comment by so1ve** [comment]
Please provide a minimal reproduction

**Comment by aslrz-club** [comment]
初始化一个项目：npm init vue@2 只选择eslint和prettier

**Comment by aslrz-club** [comment]
初始化一个项目: npm init vue@2 只选择eslint和prettier

**Comment by aslrz-club** [comment]
初始化一个项目: npm init vue@2 只添加eslint和prettier
添加element-ui: pnpm add element-ui
添加plugin vetur: pnpm add @volar-plugins/vetur -D
添加配置volar.config.js:
```
module.exports = {
services: [require("@volar-plugins/vetur").default()],
}
```
在App.vue里面添加el-button看看有没有提示 还反馈一个bug 在vscode(mac和win) 安装别的版本没有版本选择的那个下拉

**Comment by johnsoncodehk** [comment]
This package is renamed, can you try https://www.npmjs.com/package/volar-service-vetur?

**Comment by so1ve** [comment]
没有下拉框是网络问题，你得等一会儿

**Comment by aslrz-club** [comment]
it·s ok
