### ISSUE TITLE
Crashing in VSCode - "The Vue Semantic Server server crashed 5 times in the last 3 minutes"

### ISSUE THREAD

**Issue by meanspa** [vuejs/language-tools#3336]
After updating to 1.8.2 Volar started crashing. Downgrading to 1.8.1 fixes it. 

**Some details:**
- VScode 1.79.2
- I'm not using Typescript
- Tried re-installing Volar, didn't help

**Error Message:**
`The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`

**Output:**
`TypeError: Cannot read properties of undefined (reading 'package.json') at Object.h [as fileExists] (/Users/myusername/.vscode/extensions/vue.volar-1.8.2/dist/server.js:77:1416) at Proxy.x (/Users/myusername/.vscode/extensions/vue.volar-1.8.2/dist/server.js:76:37698) at Object.fileExists (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:139762:40) at host.fileExists (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:116036:43) at Object.fileExists (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:119567:30) at getPackageJsonInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:40352:33) at loadNodeModuleFromDirectory (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:40184:47) at nodeLoadModuleByRelativeName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:40058:14) at tryResolve (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:39991:27) at nodeModuleNameResolverWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:39925:38)`

**Comment by zhuiyue132** [comment]
坐等修复

**Comment by DanMelnikov** [comment]
The same problem
VS code 1.78.2
Volar 1.8.2

**Comment by PrajjwalArora08** [comment]
The same problem
VS code 1.78.2
Volar 1.8.2

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/b1344bf65c01f55872e0b0a17c767cfbae6893e0

**Comment by xuchao996** [comment]
restart
