### ISSUE TITLE
`Property button does not exist on type IntrinsicElements`

### ISSUE THREAD

**Issue by andrewheumann** [vuejs/language-tools#3337]
Since Volar 1.8.0, I have been getting typescript errors in my code for built-in html tags like `button` and `label`: 
![image](https://github.com/vuejs/language-tools/assets/31935763/83d54e26-ee7b-4f74-8bd1-8121b394747e)

Reverting to 1.6.5 appears to fix the issue.

A few project-specific details that may or may not be relevant:
- Project is Vue 2 (2.6.12)
- Issue occurs in components that are class style (with `vue-class-component`) or with composition api (`export default defineComponent(...)`)
- I am utilizing "takeover mode," and have disabled the builtin typescript support for this project
- using typescript `4.5.5`

**Comment by rchl** [comment]
Can you provide a project that reproduces?

**Comment by andrewheumann** [comment]
It turns out this was due to a bug in one of our packages: https://github.com/NightCatSama/vue-slider-component/issues/639. Updating the package to `latest` resolved the issue.
