### ISSUE TITLE
在大组件情况下，和 codeium 扩展一起启用时会导致cpu占用飙升

### ISSUE THREAD

**Issue by zcf0508** [vuejs/language-tools#3339]
Type: <b>Bug</b>

同时安装 codeium 和 volar/vetur 

Extension version: 1.8.3
VS Code version: Code - Insiders 1.80.0-insider (Universal) (4649b5333370139d161e7b5d4f78ca13741efa35, 2023-06-28T08:04:23.178Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 13, 11|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id e99baee6-2eab-4531-a0bd-a5f7bf8c2979|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
i26e3531:30769768
gsof1:30771514
e440d664:30776459
pythonnosmt12:30773574
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
e537b577:30772214
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by so1ve** [comment]
Try disabling vetur?

**Comment by zcf0508** [comment]
Only one of them will be enabled separately. 

`codeiem + volar` or `codeiem + vetur`
