### ISSUE TITLE
Functional Components not allowing inherited attributes

### ISSUE THREAD

**Issue by mklein994** [vuejs/language-tools#3340]
When I run `vue-tsc` on a functional component that has e.g. a `class=""` attribute on it, I get an error[^1]:

```
src/App.vue:9:33 - error TS2345: Argument of type '{ stuffAndThings: number; class: string; }' is not assignable to parameter of type '{ stuffAndThings: number; }'.
  Object literal may only specify known properties, and 'class' does not exist in type '{ stuffAndThings: number; }'.

9   <FooBar :stuff-and-things="7" class="demo" />
                                  ~~~~~
```

I suspect something changed that makes it not account for attributes that are inherited normally, namely `class`, `style`, and `onXXX` event listeners (see [docs](https://vuejs.org/guide/extras/render-function.html#functional-components)). The demo has more details, but here's the gist of it:

Demo: [CodeSandbox](https://codesandbox.io/p/github/mklein994/functional-component-demo/draft/long-firefly?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljghh8cl000b206ewn7b5zgt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljghh8cl000d206ezc3irvld%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljghh8cl000b206ewn7b5zgt%2522%253A%257B%2522id%2522%253A%2522cljghh8cl000b206ewn7b5zgt%2522%252C%2522activeTabId%2522%253A%2522cljgis2fz03b7206en3rmue5e%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FFooBar.ts%2522%252C%2522id%2522%253A%2522cljgiqj940072206e775pw8t4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522cljgis2fz03b7206en3rmue5e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljghh8cl000d206ezc3irvld%2522%253A%257B%2522id%2522%253A%2522cljghh8cl000d206ezc3irvld%2522%252C%2522activeTabId%2522%253A%2522cljghhqhh00md206e1ld8r4yt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljghhfug00c8206eqhaq3y3j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cljghhld300h4206ekkp44huu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522cljghhqhh00md206e1ld8r4yt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cljghhs7c000pfpi86nb2057j%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

```ts
// src/FooBar.ts

import { h } from "vue";

function FooBar(props: { stuffAndThings: number; }) {
  return h("div", `Made it: ${props.stuffAndThings}`);
}

FooBar.props = {
  stuffAndThings: {
    type: Number,
    required: true,
  },
};

export default FooBar;
```

```vue
<!-- src/App.vue -->

<script setup lang="ts">
import FooBar from "./FooBar.ts";
</script>

<template>
  <FooBar :stuff-and-things="7" class="foo-bar" />
</template>

<style scoped>
.foo-bar {
  color: blue;
}
</style>
```

> **Note** The demo shows a few other ways of defining a functional component, but they all have roughly the same error message.

---

P.S.

@johnsoncodehk Thank you for all your hard work on this project! I understand that there's been [a large increase in issues](https://github.com/vuejs/language-tools/issues/3271) recently, so it's all good, don't bend over backwards on this one ☺️. I want to encourage you (and others working on this project), that it's tools like this that make Vue and its ecosystem so enjoyable to use. To me, this language server is a gold standard that other frameworks should try to emulate. Keep up the good work! 🚀

[^1]: The line numbers may be a bit off, but the message is the same.

**Comment by so1ve** [comment]
Similar: #3318, #3301

**Comment by Ctepan** [comment]
Here is an my example with functional component and component with generic in `<script setup>`
https://stackblitz.com/edit/vitejs-vite-hddkhg?file=src%2FFComponent.ts

**Comment by rchl** [comment]
> Demo: [CodeSandbox](https://codesandbox.io/p/github/mklein994/functional-component-demo/draft/long-firefly?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljghh8cl000b206ewn7b5zgt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljghh8cl000d206ezc3irvld%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljghh8cl000b206ewn7b5zgt%2522%253A%257B%2522id%2522%253A%2522cljghh8cl000b206ewn7b5zgt%2522%252C%2522activeTabId%2522%253A%2522cljgis2fz03b7206en3rmue5e%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FFooBar.ts%2522%252C%2522id%2522%253A%2522cljgiqj940072206e775pw8t4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522cljgis2fz03b7206en3rmue5e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljghh8cl000d206ezc3irvld%2522%253A%257B%2522id%2522%253A%2522cljghh8cl000d206ezc3irvld%2522%252C%2522activeTabId%2522%253A%2522cljghhqhh00md206e1ld8r4yt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljghhfug00c8206eqhaq3y3j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cljghhld300h4206ekkp44huu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522cljghhqhh00md206e1ld8r4yt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cljghhs7c000pfpi86nb2057j%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Can't be opened

**Comment by sherif414** [comment]
i normally make my functional components using arrow functions so i can anotate them with `FunctionalComponent` interface imported from `vue`

```
import type { FunctionalComponent } from 'vue'

const MyComponent: FunctionalComponent = (props) => {
    // 
}

**Comment by johnsoncodehk** [comment]
Hi! first of all thank you for your encouragement, you really send me energy.

This can be solved by defining a functional component via `defineComponent()`, which add `AllowedComponentProps`, `VNodeProps` to props type.

```ts
import { h, defineComponent } from "vue";

const FooBar = defineComponent(
  (props: { stuffAndThings: number; }) => {
    return h("div", `Made it: ${props.stuffAndThings}`);
  }
)
```

**Comment by daydaystar** [comment]
Expect to solve

**Comment by so1ve** [comment]
@daydaystar https://github.com/vuejs/language-tools/issues/3340#issuecomment-1640365304

**Comment by johnsoncodehk** [comment]
Closed due to unable to reproduce in latest version.
