### ISSUE TITLE
Wrong highlighting for namespaced components

### ISSUE THREAD

**Issue by Shyam-Chen** [vuejs/language-tools#3341]
Ref: https://vuejs.org/api/sfc-script-setup.html#namespaced-components

![image](https://github.com/vuejs/language-tools/assets/13535256/c34eb367-e7aa-426c-9edc-c1961921469a)

**Comment by so1ve** [comment]
Ref:  #2605

**Comment by Shyam-Chen** [comment]
The issue is a bit different; the closing tag of the label isn't highlighted.

<img width="514" alt="image" src="https://github.com/vuejs/language-tools/assets/13535256/f9b64286-db44-40e1-878a-02f2a5216fa8">

<img width="282" alt="image" src="https://github.com/vuejs/language-tools/assets/13535256/a9666674-3dec-470a-8913-6858a06b1a29">

**Comment by cheese-git** [comment]
Same issue here
