### ISSUE TITLE
Single word component names are not registered as being used

### ISSUE THREAD

**Issue by asekularaclf** [vuejs/language-tools#3342]
I hope I'm reporting the bug in the appropriate place. As the title suggests: when I import a component whose name is a single word (`Loader.vue` for example) for some reason it's not recognized as a component used in the template (`<loader />`) but the TS believes it's being used as a type instead. Please check the screenshot provided.

<img width="854" alt="Screenshot 2023-06-29 at 13 17 28" src="https://github.com/vuejs/language-tools/assets/137810444/59de2e44-d05f-49d1-be40-3daa0e82785f">
<img width="590" alt="Screenshot 2023-06-29 at 13 21 57" src="https://github.com/vuejs/language-tools/assets/137810444/56422733-dc52-4a13-9cd2-37ab5b27eb7c">

**Comment by so1ve** [comment]
Hi @asekularaclf 👋  I cannot reproduce this problem 😢 Could you please share your tsconfig?

**Comment by asekularaclf** [comment]
Of course @so1ve , here it is:
```
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "compilerOptions": {
    "composite": true,
    "strict": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "allowJs": true,
    "outDir": "dist",
    "checkJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "resolveJsonModule": true,
    "types": ["vite/client"],
    "paths": {
      "@/*": ["src/*"],
      "@tests/*": ["tests/*"]
    },
    "lib": ["ES2021", "DOM", "DOM.Iterable"]
  },
  "include": [
    "src/**/*.js",
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "env-override.d.ts"
  ],
  "exclude": ["node_modules", "dist"]
}
```
