### ISSUE TITLE
Component types are no longer detected from components in local Nuxt 3 layer

### ISSUE THREAD

**Issue by stilesdev** [vuejs/language-tools#3346]
Using Volar 1.8.0 - 1.8.3, prop and emit types are no longer detected from components located in a Nuxt 3 layer. No type errors are displayed when using incorrect types, and autocomplete is not able to complete prop or event names on these components.

This happens both with Takeover mode and the separate TypeScript extension, but downgrading to Volar 1.6.5 fixes the issue.

Possibly related to #3188, but that issue made no mention of Nuxt layers, and I'm only seeing this issue on components coming from a Nuxt layer. Types for components in the same Nuxt app are detected fine.

Minimal reproduction: https://github.com/stilesdev/repro-volar-nuxt-layers

In the reproduction, `packages/layer` is a minimal Nuxt layer with a single component, and `packages/app` is a normal Nuxt app which extends the layer by relative path in `nuxt.config.ts`.
![image](https://github.com/vuejs/language-tools/assets/1377201/71f93de4-3db9-4358-bb63-fc2a55d0952e)

Steps to reproduce:
1. Clone the linked project, `cd repro-volar-nuxt-layers/packages/app`, `pnpm install`, `pnpm dev`
2. Open the project in VSCode and open `packages/app/app.vue`. See that only the prop on the component from the Nuxt app is reporting a type error. Both components are identical and should be reporting the same error here:
![image](https://github.com/vuejs/language-tools/assets/1377201/2b007a26-59d5-4bae-b360-30e941bc84c9)
Hovering over the component from the layer shows no prop types:
![image](https://github.com/vuejs/language-tools/assets/1377201/a152ae34-771b-4192-98e1-e569d8895c34)
Hovering over the prop on this component, it appears to be inferring the type from usage:
![image](https://github.com/vuejs/language-tools/assets/1377201/16444eec-b3f0-4f26-8494-29f783435b16)
4. Downgrade Volar to 1.6.5, reload VSCode, see type error reported properly on both components.
![image](https://github.com/vuejs/language-tools/assets/1377201/8114c09c-6fb6-44b7-9e9c-9cc3fbe06241)

**Comment by agenordebriat** [comment]
Updating `packages/app/tsconfig.json` to:
```json
{
  "extends": "./.nuxt/tsconfig.json",
  "include": [
    ".nuxt/nuxt.d.ts",
    "**/*",
    "../layer/**/*"
  ],
}
```

Fixes the issue.

**Comment by stilesdev** [comment]
Agreed, that works great as a workaround. I'll close this in favor of nuxt/nuxt#21877. Thanks!
