### ISSUE TITLE
Why show diff result in the latest version ?

### ISSUE THREAD

**Issue by sharefe-demo** [vuejs/language-tools#3348]
Hi，i got puzzle about the diff volar version.

Prev volar version:
![Component](https://github.com/vuejs/language-tools/assets/49937673/d729b2c0-f4a7-4aff-a11a-b88a0cb50d55)
![volar](https://github.com/vuejs/language-tools/assets/49937673/c1854f20-a983-41ff-b736-fa861ff003ec)

Latest volar version:
![Component](https://github.com/vuejs/language-tools/assets/49937673/58c40da6-052d-4a6c-8d46-e3a542256954)
![volar](https://github.com/vuejs/language-tools/assets/49937673/24a6f417-1da1-4ead-9909-26e715fd16b0)

The 1.0.9 version could show the right event-parameter type, but it is fail in the latest version (1.8+). What should i do to fix this problem ?

Demo code repo: https://github.com/sharefe-demo/volar-types-demo

**Comment by johnsoncodehk** [comment]
cc @so1ve

**Comment by so1ve** [comment]
`type ObjectEmitsOptions = Record<string, ((...args: any[]) => any) | null>;`

**Comment by KazariEX** [comment]
Close this issue as the reproduction repo has become invalid. If it still happens in the latest version, feel free to open a new issue.
