### ISSUE TITLE
类型“{}”上不存在属性“defaultProps”

### ISSUE THREAD

**Issue by githublmy** [vuejs/language-tools#3354]
![image](https://github.com/vuejs/language-tools/assets/35590555/8116e2f9-3d96-4348-8e9b-4b08fa848867)
![image](https://github.com/vuejs/language-tools/assets/35590555/4df56c1e-873d-46cd-b135-964238701bc7)

所有文件都提示 错误，   1.8.3

**Comment by so1ve** [comment]
Please provide a minimal reproduction 😂

**Comment by so1ve** [comment]
Maybe you forgot to install the dependencies
