### ISSUE TITLE
can't infer the component type from v1.8.2

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#3358]
![image](https://github.com/vuejs/language-tools/assets/41773861/fe59b64b-2ccf-47bb-b72d-290e1e41ce23)

1. `git clone git@github.com:tjx666/mono.git`
2. `pnpm install`
3. install volar extension v1.8.3, this issue is from v1.8.2
4. open file [./apps/client/src/app.vue](./apps/client/src/app.vue)
5. hover over `Button` in template block, can't infer the `Button` type
6. downgrade to v1.8.1 will work

repository: https://github.com/tjx666/mono

```
Volar: v1.8.2
Take Over Mode: Yes
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

## Temporary Solution

downgrade volar to v1.8.1

![image](https://github.com/vuejs/language-tools/assets/41773861/53b00f6a-06f0-4e31-8a80-4c3b170fd730)

**Comment by icyfe** [comment]
have the same problem help~

**Comment by so1ve** [comment]
As a temporary solution, you can set an alias in your tsconfig.json.

**Comment by so1ve** [comment]
Ref: #3346

**Comment by tjx666** [comment]
> > Breaking changes
> > no longer parse vue files outside tsconfig include option to avoid TS performance concerns (#3326)
> 
> Caused by this breaking change again... I guess we have to revert this change because it causes a lot of unnecessary problems

@johnsoncodehk Maybe we should revert the fix if it can't be fixed imediatelly, the type issue is more serious. The code actons problem can be temporaly fixed by just disable it.

**Comment by akittas** [comment]
The changes in 1.8.2 additionally break the ability to run `vue-tsc` for individual files. (because it needs the "include" for tsconfig and tsconfig is not available when running tsc for specific files).
I also think this change should be reverted

**Comment by so1ve** [comment]
@tjx666 Try upgrade volar to latest version, does it work now?

**Comment by tjx666** [comment]
@tjx666 @johnsoncodehk latest versions v1.8.8 works

**Comment by tjx666** [comment]
check here: https://github.com/vuejs/language-tools/issues/3328
