### ISSUE TITLE
volar插件导致vscode的editorOverviewRuler.selectionHighlightForeground属性失效

### ISSUE THREAD

**Issue by wyyx50** [vuejs/language-tools#3359]
我通过editorOverviewRuler.selectionHighlightForeground属性来设置vscode右侧滚动条所选内容相关的标记颜色，未安装volar时可以生效，但是安装volar后就不生效了

**Comment by so1ve** [comment]
Any reproduction? Could you please share your vscode config? `editorOverviewRuler.selectionHighlightForeground` does not seem to be a valid vscode setting item.

**Comment by wyyx50** [comment]
> 有复制品吗？可以分享一下你的 vscode 配置吗？`editorOverviewRuler.selectionHighlightForeground`似乎不是有效的 vscode 设置项。


> 有复制品吗？可以分享一下你的 vscode 配置吗？`editorOverviewRuler.selectionHighlightForeground`似乎不是有效的 vscode 设置项。

你好，这是我的vscode设置：
```
"workbench.colorCustomizations": {
        "editor.selectionBackground": "#616263",
        "editor.selectionHighlightBorder": "#FFF000",
        "editor.selectionHighlightBackground": "#00000000",
        "editor.wordHighlightBackground": "#00000000",
        "editor.findMatchBorder": "#FFF000",
        "editor.findMatchHighlightBorder": "#FFF000",
        "editorOverviewRuler.findMatchForeground": "#1EC163",
        "editorOverviewRuler.selectionHighlightForeground": "#1EC163"
    }
```

**Comment by wyyx50** [comment]
> 有复制品吗？可以分享一下你的 vscode 配置吗？`editorOverviewRuler.selectionHighlightForeground`似乎不是有效的 vscode 设置项。

Please reply to me once you see it. I am looking forward to your resolution of this issue

**Comment by so1ve** [comment]
I have no idea about this, nor a solution. Please don't ping anyone directly.
