### ISSUE TITLE
Volar does not respect @value of css-modules

### ISSUE THREAD

**Issue by modelair** [vuejs/language-tools#3362]
i want to import classes to my SFC, but inline styles not respects @value, 
otherwise using style-file separately from SFC works! why? 

my-component.vue (not works) 
```html 
<script setup lang="ts">
import { useCssModule } from 'vue'

const $style = useCssModule()
</script>

<style module lang="scss">

  @value textbox, wrapper from "./textbox.shared.module.css"; /* Volar: Unknown at rule @value */

</style>
```

my-component.vue + my-component.module.scss (works) 
```html 
<script setup lang="ts">
import $style from './my-component.module.scss'
</script>
```

```css
@value textbox, wrapper from "./textbox.shared.module.css";

.textbox {
...
}
```

also, it's must work with import @value from SFC directly.
how to share classes? 
using scss files separately from sfc breaks vite hot-reload, any changes in style files makes full-reload of page. it's terrible.

**Comment by johnsoncodehk** [comment]
This question has nothing to do with Vue language tools, please ask in Vue Discord server.
