### ISSUE TITLE
Files like composables, utils etc... not recognized when created - restart of vue server needed (Nuxt 3)

### ISSUE THREAD

**Issue by SoundFractures** [vuejs/language-tools#3369]
Have been using the Volar extension in VS Code for quite some time now. But recently, I discovered that whenever I create a new composable for example, and try to use it in my component, it's not recognized (at least not in my code - IntelliSense).

After some research, I figured out that I need to manually restart the Volar: Vue Server so that my composable is recognized and I can see its methods and stuff.

Is anybody having any similar issues? Never have I had to manually restart the server to re-index the project files

Here is an example:

Create a new composable under /composables
![Screenshot 2023-07-05 at 11 05 43](https://github.com/vuejs/language-tools/assets/60104141/c74bab12-2248-42be-ba74-1cfb6cd8c5cc)

The composable is not recognized
![Screenshot 2023-07-05 at 11 04 54](https://github.com/vuejs/language-tools/assets/60104141/87aeb3d1-c4c5-411f-a5fa-ee06e0072a81)

Restarting Volar: Vue server
![Screenshot 2023-07-05 at 11 06 10](https://github.com/vuejs/language-tools/assets/60104141/6acfd9c0-017d-4eda-8721-71819e479318)
And now it works
![Screenshot 2023-07-05 at 11 06 32](https://github.com/vuejs/language-tools/assets/60104141/34243bc5-50a9-4b69-9733-9115515fad05)

Any input will be much appreciated.

**Comment by uros-5** [comment]
Is your Nuxt Dev server active ?

**Comment by SoundFractures** [comment]
> Is your Nuxt Dev server active?

Yes. I haven't noticed any difference running the dev server or not.

**Comment by meguoe** [comment]
Yes, I often encounter this kind of problem too

**Comment by davidmatter** [comment]
+1
Also: If I create a new vue component (SFC), import suggestions in the component's script part only work after I manually add one import.

**Comment by latte03** [comment]
+1

**Comment by sktm4a1** [comment]
> +1 Also: If I create a new vue component (SFC), import suggestions in the component's script part only work after I manually add one import.

 I have the same problem

**Comment by johnsoncodehk** [comment]
Should be fixed in master branch.

Refs: https://github.com/vuejs/language-tools/issues/4167#issuecomment-2025925828
