### ISSUE TITLE
WebStorm project error: "Volar: Object is possibly 'null'."

### ISSUE THREAD

**Issue by Juraj-Masiar** [vuejs/language-tools#3370]
Hello,
My WebStorm recently updated and is now using "Volar", version 1.6.5. 
But now I'm getting weird error reported `"Volar: Object is possibly 'null'."` which makes no sense - also my TypeScript compiler can correctly compile the code without any errors.

I've simplified the code to this:
```ts
async function transitionToGroup(original: HTMLElement) {
  const originalDialSize = original.querySelector('#dials > .dial').getBoundingClientRect();
  return undefined;
}
```
Which is then reported as this:
![image](https://github.com/vuejs/language-tools/assets/6358971/2f89ddf2-7fb0-41a8-8cfa-78a5edfa025e)

**Comment by rchl** [comment]
The place where it reports an error doesn't seem right but the result of `original.querySelector('#dials > .dial')` can be `null` technically you have a potential issue there.

**Comment by Juraj-Masiar** [comment]
OMG!
You are right, it's the query selector result error and it disappears when I use bang `original.querySelector('#dials > .dial')!.getBoundingClientRect();`

In that case, this is wrong error marking, it should underline the whole function call, not just the variable name.
Is this still Volar issue or should I report it WebStorm?

**Comment by so1ve** [comment]
Can you reproduce it in vscode?

**Comment by Juraj-Masiar** [comment]
I'm not expert on VS Code so I can't tell if it's setup correctly but after installing Volar it seems to work as expected:
![image](https://github.com/vuejs/language-tools/assets/6358971/7392c480-dac9-49f6-a361-3a6b8b2ac1ed)

Same error, but correct error highlight.
So I guess I'm reporting it to WebStorm :(
