### ISSUE TITLE
具名插槽提示期望0个参数，但得到一个参数

### ISSUE THREAD

**Issue by 0x1f57** [vuejs/language-tools#3371]
![image](https://github.com/vuejs/language-tools/assets/102740967/2f0338ad-cccb-45c5-b313-ad5fa23bd7a3)
使用的Webstorm，Volar版本1.6.5

vue-tsc 检查报错如下
![image](https://github.com/vuejs/language-tools/assets/102740967/45b1e6d9-902f-4534-bf95-db3450ef0773)

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by 0x1f57** [comment]
> Could you please provide a minimal reproduction?
如下：
![image](https://github.com/vuejs/language-tools/assets/102740967/b6c40758-d977-4f47-9250-48bd6f6b044e)
`<script setup lang="ts">
defineSlots<{ content(): any }>()
</script>

<template>
  <div class="hello-world">
    <slot name="content" />
  </div>
</template>
`

**Comment by 0x1f57** [comment]
```typescript
defineSlots<{ content(props: {}): any }>()
```
当我给该函数声明给定`props`参数为`{}`则错误消失
