### ISSUE TITLE
`ComponentCustomProperties` in `vue` module not recognized

### ISSUE THREAD

**Issue by lzurbriggen** [vuejs/language-tools#3372]
the vue documentation recommends [declaring custom component properties in the `vue` module](https://vuejs.org/api/utility-types.html#componentcustomproperties), like this:

```ts
declare module 'vue' {
  interface ComponentCustomProperties {
    $gettext: MyType
  }
}
```

however the language server reports usages in templates as errors (`Property '$gettext' does not exist on type  '{ $: ComponentInternalInstance; ...`).

declaring them in `@vue/runtime-core` still works, and is the way e.g. `vue-router` does it:

```ts
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
     $gettext: MyType
  }
}
```

i know the [vue language tools readme](https://github.com/vuejs/language-tools/tree/master/packages/vscode-vue#usage) mentions `@vue/runtime-core` regarding global components, but there's not really any other documentation regarding this, so i'd rather follow the vue docs.

i think this broke with the latest release.

versions:
- vue language features/vue-tsc: 1.8.4
- vue: 3.3.4
- typescript: 5.1.6

**Comment by so1ve** [comment]
#3107 Weird...

**Comment by watchingfun** [comment]
I'm having the same problem, it's weird, is the documentation wrong or is this a pending bug,
https://cn.vuejs.org/guide/typescript/options-api.html#augmenting-global-properties

**Comment by watchingfun** [comment]
> I'm having the same problem, it's weird, is the documentation wrong or is this a pending bug, https://cn.vuejs.org/guide/typescript/options-api.html#augmenting-global-properties

It is normal to use `declare module 'vue'` in vscode, and it is normal to change it to `declare module '@vue/runtime-core'` in webstrom.

**Comment by johnsoncodehk** [comment]
Close Since this question has nothing to do with language tools, please ask the TS question in the Vue Discord server.

**Comment by saifahn** [comment]
Sorry, I haven't looked into this in detail yet, but could it have something to do with vue-tsc using `@vue/runtime-core` instead of `vue`?

**Comment by GurovDmitriy** [comment]
I also get the same error when running type checking until you replace vue with @vue/runtime-core in the declaration

https://github.com/GurovDmitriy/be-boilerplate-stack
in vue-playground template find declare $mq: PluginBreakpoints

**Comment by cristianTalero** [comment]
1. you have to install it: `pnpm add -D @vue/runtime-core`

2. In the `.d.ts` file import the interface:
`import { ComponentCustomProperties } from '@vue/runtime-core'`
4. Add the declaration:
`declare module "@vue/runtime-core" {
    interface ComponentCustomProperties {
        route:  typeof ziggyRoute;
    }
}`
4. If it necessary and you use vscode, reload the TS Server and reload window with `Ctrl+Shift+P`

**Comment by so1ve** [comment]
You don't have to install it, nor `import { ComponentCustomProperties } from '@vue/runtime-core'`

**Comment by cristianTalero** [comment]
Yeah, but in my case only the instalation, the import was necesary, because when I remove it, I get the linter error again, I'm not sure why
