### ISSUE TITLE
组件引用问题

### ISSUE THREAD

**Issue by akFace** [vuejs/language-tools#3373]
### 组件引用问题
非驼峰写法会爆红，之前的版本不会的

如图
![image](https://github.com/vuejs/language-tools/assets/22288837/81f080a8-53c5-4ecf-8f1b-37c34d8e3ab0)

此方法爆红
```vue
<template>
  <div>
    <nav-bar></nav-bar>
  </div>
</template>
<script lang='ts' setup>
import { reactive, ref } from 'vue';
import navBar from '@/components/system/navBar.vue'
</script>
<style lang="scss" scoped>

</style>
```

-----
这种写法才正常
```vue
<template>
  <div>
    <navBar></navBar>
  </div>
</template>
<script lang="ts" setup>
import { reactive, ref } from "vue";
import navBar from "@/components/system/navBar.vue";
</script>
<style lang="scss" scoped></style>

```

**Comment by so1ve** [comment]
![image](https://github.com/vuejs/language-tools/assets/58381667/1dd2dae3-ca5f-4d3b-8f1e-7a1f5a0fc35f)
¯\_(ツ)_/¯

**Comment by so1ve** [comment]
Could you please show that error message?

**Comment by akFace** [comment]
> Could you please show that error message?

![image](https://github.com/vuejs/language-tools/assets/22288837/a249755c-b9b3-4c43-be71-9aff17986eda)
