### ISSUE TITLE
TS(2339) Property 'foo' does not exist on type '...' in `serverPrefetch`

### ISSUE THREAD

**Issue by strokirk** [vuejs/language-tools#3375]
Using `vue@2`, the `serverPrefetch` function doesn't get the correct type inference. 

For example, this component:

```
<template>
  <div :class="bar" @click="foo"></div>
</template>
<script>
export default {
  async serverPrefetch() {
    this.foo();
    this.bar = 'baz'
  },
  mounted() {
    this.foo();
    this.bar = 'baz'
  },
  data() {
    return {
      bar: 'bar'
    };
  },
  methods: {
    /** @returns {number} */
    foo() {
      return 1
    }
  }
};
</script>
```

Gives the following TS(2339) errors:

```
Property 'foo' does not exist on type 'Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>'.
Property 'bar' does not exist on type 'Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>'.
```

I have the latest version of Volar installed, and TypeScript takeover mode is enabled.

**Comment by rchl** [comment]
It looks like an issue in Vue 2.7 types.

The `this` is explicitly typed in a way that doesn't include data properties, methods, etc: https://github.com/vuejs/vue/blob/49b6bd4264c25ea41408f066a1835f38bf6fe9f1/types/options.d.ts#L213

Same as `beforeCreate` which I guess doesn't have access to any component properties unlike `serverPrefetch`.
