### ISSUE TITLE
Unexpected "any" type when components with generics and combined emits.

### ISSUE THREAD

**Issue by FlareZh** [vuejs/language-tools#3379]
When a component with generics(even they are not unused), and its generic type of defineEmits is combined by "&", the first-match's type of the first emit type will be "any" in the parent component if there aren't any other match which has the same type with it.

e.g.
The return type of update:modelValue in parent component is "any". If I change any other emits type to "string" or I change the position of update:modelValue in StoreEmits or PanelEmits, it would become "string".
![image](https://github.com/vuejs/language-tools/assets/22744623/1e1896dd-f11d-4ead-86dc-791f886c94fc)

[Minimal repo](https://play.vuejs.org/#eNqVU01vm0AQ/SsrVBVbskFVekKO5bbyoT2kUR31xIXAmGyyX9odiKvI/72zrMHETq2UA2Jm3puPx8xL9MWYpG0gyqIFgjSiQFjmitGz2ICAElmwGFs1pqJoJnUF4nchGrjOo1IrpwUkQteTD9CCwmkeDQwLUrfw0yAn2GX0cpGGelR9kY5aIdOVlhtkolA1JUGXR8wBNoaiXBptkR1a3VotWZwcMvm5Yp8t8AkdzYhNTWx5nTw6rWjqF1/edyYNF2APveZRxrqIjxVC6OcfnQ9tA7PeXz5A+fSG/9HtvC+Pbi04sC3k0RDDwtaAIbze3MCOvocgKdsIQl8I/gISsPE9BtjXRlXU9gjXdfu9k4Wr+s6tdwjK9UP5Rj1y3+HziCT6dmH0Y7tXyVXHy9WeVDwK7Bcn6JvbwBr9pt7V/a3eqEGB5SVB7gJi6V/4xwDboLawlhwdu6YmDoSJKiRkLD7bv3jGjkbGHFqaeJqxVvPqlPxqFYmow1fGVCPvwf6DVVTV/1JcJ817WHv/Gma/LRSIfvaREB/PhSgFL59uaPIh/aXs/uiQASWjxBVsuQqZF8eKy8m0R3vc5E2p409xhzreExm0C+EE57IwJzcVAq8XijYmLO4DonFZmpaVIhqV4a1NFGCqjExXBEtto5BLmFdarmj7ks9pxR2O3Qk4Ob+3+pmujJKMjsDzu9OzcwuqAutP5H1lT2jj0iehs/LDgez/Av0Bz3k=)

**Comment by johnsoncodehk** [comment]
This is a known limitation where past implementations were unable to infer things larger than 4 species (See #60), now resolved by #3379!

**Comment by so1ve** [comment]
#3585?
