### ISSUE TITLE
Automatic completion of file names issue when import files

### ISSUE THREAD

**Issue by star-reader** [vuejs/language-tools#3382]
I just found there is an issue when importing files in .vue files.
When trying to import some file in .vue files,<b> the automatic completion of file names speed is so slow</b>,
for example:
```js
import use3DPath from '@/hooks/map/use3DPath'
```
 after typed "@/", it will takes about 2~5 seconds to show the file list, however in other mode, it's normal.
![image](https://github.com/vuejs/language-tools/assets/75555433/2b7b0af1-f151-4379-9d56-93b2b0a42e9b)
![image](https://github.com/vuejs/language-tools/assets/75555433/624e5d91-3122-402b-9afe-8fdcc895100c)

**Comment by star-reader** [comment]
In my old computer I've already found that issue(in Vue2 with vetur it's normal). I thought it's beacuse my computer's poor performance. After I changed to a new computer, volar still has this issue

**Comment by johnsoncodehk** [comment]
Resolved by #3788.
