### ISSUE TITLE
Global component definitions not recognized when `declare module 'vue'` is defined twice in different files

### ISSUE THREAD

**Issue by innocenzi** [vuejs/language-tools#3383]
I'm not sure if the title is the actual explanation of the issue, but that's what I found out while debugging.

Basically, I want to use `unplugin-auto-import` and `unplugin-vue-components` in the same project. I generate their `.d.ts` in a directory, eg. `.types`. 

The issue appears when `unplugin-auto-import` uses the `vueTemplate` option. When enabled, it declares `ComponentCustomProperties` in a `declare module 'vue'`. When this is the case, global components are no longer detected (marked as `unknown`).

**Reproduction:**
- Clone https://github.com/innocenzi/volar-issue-3383
- Run `nr dev` to generate types
- Go to `src/App.vue` in VSCode, see that `<HelloWorld>` is `unknown`
- Go to `.test/auto-imports.d.ts`, remove the entire `declare module 'vue'` block under `// for vue template auto import`
- Restart Volar, and see that `<HelloWorld>` is now properly recognized

```
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.79.2 Chrome/108.0.5359.215 Electron/22.5.7 Safari/537.36

Volar: 1.8.4
```

**Comment by so1ve** [comment]
#3372

**Comment by innocenzi** [comment]
Workaround for me was to put the `auto-imports.d.ts` last in `tsconfig.json`.

**Comment by BTBMan** [comment]
I noticed that it always detects the first `declare module 'vue'`, I think it should detect all of it.

**Comment by rchl** [comment]
You have to make sure that your declaration is evaluated after the original one. So just reference the original one above yours by importing relevant module. Or otherwise adjust the order of loading.

**Comment by BTBMan** [comment]
I've adjusted the file order of the tsconfig include field to fix it, This way is so Weird!!!🤔

**Comment by phil668** [comment]
Is there any progress？still exists this problem
