### ISSUE TITLE
CSS reference count dissapears on save causing random scrolling

### ISSUE THREAD

**Issue by VasilVerdouw** [vuejs/language-tools#3387]
## How to reproduce

(`"vue.codeLens.enabled"` has to be true or not changed inside of `settings.json`)

1. Create any vue file while having this extension installed.
2. Write some CSS and use it in the template.
3. Note that it now displays amount of references above each piece of written css.
4. Save the file while having the css with references above them on screen. If autosave is enabled it will likely also work to just change something inside of the file. 
5. The save caused the references to disappear for a moment and then reappear. This causes VS Code to randomly scroll the document you're working in if there are reference counters above wherever you're working. The more reference counters are above wherever you are inside of the file, the more VS Code will move things around.

## Problem

Saving the file a lot(especially autosave) and/or working inside of a file with a lot of css are both almost impossible because VS Code keeps randomly moving the text around.

### Expected behavior

I would expect for the reference counters to not disappear but just keep the old numbers while they're updating. Another option would be for them to dissapear but keep their height (EG: become transparent.).

### Temporary 'solution'

1. Open `settings.json`
2. Add this line `"vue.codeLens.enabled": false,`
3. Reference counters are now no longer being displayed at all

**Comment by johnsoncodehk** [comment]
This is controlled by VSCode and not by the Vue extension. However, the references codeLens feature has been temporarily removed.
