### ISSUE TITLE
v1.84  Unable to recognize component type

### ISSUE THREAD

**Issue by yang1206** [vuejs/language-tools#3388]
<img width="827" alt="SCR-20230710-qxgy" src="https://github.com/vuejs/language-tools/assets/28709596/b358d221-2669-49d8-8504-2e4bcb51c868">

> 1.84
<img width="685" alt="SCR-20230710-qxbv" src="https://github.com/vuejs/language-tools/assets/28709596/4186dfdb-9f8b-4382-bc26-9a709530a263">

> 1.65

<img width="910" alt="SCR-20230710-ratl" src="https://github.com/vuejs/language-tools/assets/28709596/531e51d0-2be0-4111-9f63-39c717aa0d62">

**Comment by so1ve** [comment]
Please provide a minimal reproduction.

**Comment by yang1206** [comment]
https://github.com/yang1206/volar_3388

**Comment by so1ve** [comment]
Similar to #3372 #3107. I'll try to fix it in next few days

**Comment by yang1206** [comment]
thanks

**Comment by johnsoncodehk** [comment]
Regarding the fact that the repro case link has expired.
