### ISSUE TITLE
插件bug

### ISSUE THREAD

**Issue by wang123get** [vuejs/language-tools#3395]
当我输入大括号时，右边会多生成一个括号。
电脑系统：windows 11
vsocde：1.80.0
volar：1.8.4
![xx](https://github.com/vuejs/language-tools/assets/84189486/ac4a9e31-8063-4cbd-9c7b-2d18421c6966)

**Comment by so1ve** [comment]
Could you please post a video?

**Comment by so1ve** [comment]
Duplicate of #1717
