### ISSUE TITLE
TS Error on props when using Generic SFC

### ISSUE THREAD

**Issue by KieranSunshine** [vuejs/language-tools#3405]
I created a fresh repo using ```npm init vue@latest``` the repo can be found here, [vue-generic-test](https://github.com/KieranSunshine/vue-generic-test/).

The problematic file is [src/components/GenericComponent.vue](https://github.com/KieranSunshine/vue-generic-test/blob/main/src/components/GenericComponent.vue)

When I try to access a prop I'm my IDE shows the following error:
![image](https://github.com/vuejs/language-tools/assets/33720106/416b67e0-7f5b-4eed-b0d0-ee41486d18ba)

If I remove the usage of the generic from props, the error goes away.

Apologies if this is already a known issue, or if I'm just being dumb. Let me know if I can provide any more information.

To be clear I'm using VS code, volar 1.8.5, typescript 5.0.4, vue 3.3.4, vue-tsc 1.8.5.

**Comment by KieranSunshine** [comment]
Seems like this might be a duplicate of #3204?

**Comment by lmiller1990** [comment]
I'm having the same issue. I just tried generics for the first time.

Oddly enough, not working:

```html
<script lang="ts" setup generic="T extends ListItem">
export interface ListItem {
  id: string;
  title: string;
}

const props = defineProps<{
  items: T[];
}>();
</script>

<template>
  <ul>
    <li v-for="item of props.items" :key="item.id">{{ item.title }}</li>
  </ul>
</template>
```

But... not working. All I did was change `T` to `T[]`.

```html
<script lang="ts" setup generic="T extends ListItem">
export interface ListItem {
  id: string;
  title: string;
}

const props = defineProps<{
  item: T;
}>();
</script>

<template>
  <ul>
    {{ item.title }}</li> 
  </ul>
</template>
```

**Comment by marcianos** [comment]
I also use vue in version **3.3.4** and **1.8.10** version of volar. I try to create a generic component but I receive an error message: 
`Property 'name' does not exist on type '[{ type: PropType<T>; required: true; }] extends [Prop<infer V, infer D>] ? unknown extends V ? IfAny<V, V, D> : V : { type: PropType<T>; required: true; }'`

```vue
<template>
  <p>{{ animal.name }}</p>
</template>

<script setup lang="ts" generic="T extends Animal">
export interface Animal {
  name: string;
}
const props = defineProps<{
  animal: T;
}>();
</script>
```

Array works as mentioned in the comment above. But I need it also for a single generic object.
