### ISSUE TITLE
`@vue/language-plugin-pug` / `@volar/vue-language-plugin-pug` Causes Syntax Errors When Using Multiline Escapes in Pug

### ISSUE THREAD

**Issue by Aleksbgbg** [vuejs/language-tools#3406]
As the title suggests, using either of these plugins will cause multiline escapes in pug to be unusable, as shown below:

![image](https://github.com/vuejs/language-tools/assets/31630318/25cc7dae-a686-4231-8090-6dbcd6a74130)

This is valid Pug syntax. A bunch of TypeScript errors are generated by `vue-tsc`:
![image](https://github.com/vuejs/language-tools/assets/31630318/deaa89a8-4a18-4c65-bc60-b952c44f4fce)

**Comment by davidmatter** [comment]
Are you still having this issue with the latest version?
