### ISSUE TITLE
Volar not respecting .eslintrc.js rules

### ISSUE THREAD

**Issue by Joebayld** [vuejs/language-tools#3407]
So I created a new VueJS 3 project, and set my rules to the recommended ones. See rules below: 
```
  'extends': [
    'plugin:vue/vue3-recommended',
    'eslint:recommended',
    '@vue/eslint-config-typescript/recommended',
  ]
````

What I'm finding is that in the source code editor, warnings are showing for the new rules, but when I use Volar to fix them, nothing happens. If I run `vue-cli-service lint`, it fixes it but then if I fix everything via Volar it defaults to older rules. Is this normal? Is there a way to make sure Volar is reading the rules from ..eslintrc.js? 

Here's a screenshot of a rule that won't format: 
<img width="514" alt="image" src="https://github.com/vuejs/language-tools/assets/9399317/e782b55d-57c5-4be1-90fa-227dd0f626c1">

But if I fix it via the `vue-cli-service lint`, it works. 
<img width="514" alt="image" src="https://github.com/vuejs/language-tools/assets/9399317/24f2003e-7421-4988-8a5f-9baf1763649d">

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by xiaoxiangmoe** [comment]
Volar does not include ESLint.
You should use https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
