### ISSUE TITLE
 Vue Language Features (Volar) appear  '' Property 'xxx' does not exist on type '{}'"

### ISSUE THREAD

**Issue by ocean0hai** [vuejs/language-tools#3408]
I reinstalled Vue Language Features (Volar) and the following situation occurred. I switched to another version and reinstalled it, but there was no solution online.
![bug图片](https://github.com/vuejs/language-tools/assets/112957126/b78c19d0-85ee-4ec9-bf43-c6877c742399)
![image](https://github.com/vuejs/language-tools/assets/112957126/1f4bd095-b113-464c-9f43-30ac6bf50b68)

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by tobiasklemp** [comment]
I have the same issue with a fresh install of https://github.com/nvim-lua/kickstart.nvim
**Volar:** 1.8.5
**Nvim:** 0.9.1
**OS:** Win 11

**Nuxt project used:** https://github.com/tobiasklemp/nuxt-example

In app.vue diagnostics show "Property 'bla' does not exist on type '{}'." on line 12.

Never encountered this on my usual nvim setup although the setup is pretty similar.

**Comment by so1ve** [comment]
@tobiasklemp Works on my machine 🤔 Maybe you forgot installing dependencies
![image](https://github.com/vuejs/language-tools/assets/58381667/043d946f-8e76-427b-903e-1188e54aa18d)

**Comment by so1ve** [comment]
@tobiasklemp More info?

**Comment by so1ve** [comment]
Solution: install the dependencies
