### ISSUE TITLE
deprecated variables does not have strikethrough when used in `<template>`

### ISSUE THREAD

**Issue by sapphi-red** [vuejs/language-tools#3409]
![image](https://github.com/vuejs/language-tools/assets/49056869/e721b5bd-548b-4a3a-aeb8-e81b49b2dd9a)
Deprecated variables have strikethrough if it's in `<script>`, but it doesn't if it's in `<template>`.

Reproduction: https://github.com/sapphi-red-repros/vue-language-tools-deprecate-in-template-repro

Vue language tools version: v1.8.5

**Comment by vinodkola1337** [comment]
I updated Vue-Official plugin to the latest version (2.0.19), but I am still able to reproduce this issue.

![image](https://github.com/vuejs/language-tools/assets/24287012/fe2b7dd5-198d-45aa-adf3-e11f596c5b0e)


Am I using a wrong version of the extension?

**Comment by so1ve** [comment]
Those issues are not identical and you may open a new feature request
