### ISSUE TITLE
Automatic aligns the code incorrectly when writing code

### ISSUE THREAD

**Issue by asylbek23** [vuejs/language-tools#3410]
`<script>
  export default {
    data() {},
  };
</script>` 
into
`<script>
  export default {
  data() { },
methods: {}
  };
</script>`

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction and show the steps to reproduce?

**Comment by asylbek23** [comment]
When saving, the code is formatted using prettier

сб, 15 июл. 2023 г. в 17:31, Ray ***@***.***>:

**Comment by so1ve** [comment]
> Please provide minimal reproduction
