### ISSUE TITLE
Cannot identify methods and computed properties in vs code

### ISSUE THREAD

**Issue by nowshad-hossain-rahat** [vuejs/language-tools#3412]
Visual Studio Code's Vue (Volar) extension not showing details of methods and computed properties when I hover over my cursor on the method call or computed property call. Here's the screenshot

![image](https://github.com/vuejs/language-tools/assets/65206853/199adac2-a3ed-4e54-aaa1-30a37ffa2acf)

and even when I hover over a state variable returning by the data() method inside of a method that also showing any type for that variable and clicking Ctrl + Left Click also not taking me to the declaration

Please help me fix this :(

Tried chat gpt to get fixes, didn't work, tried reinstalling Volar extension, restarting vs code, disabling other vue extensions, nothting is working

**Comment by so1ve** [comment]
Please provide a minimal reproduction 🤲

**Comment by nowshad-hossain-rahat** [comment]
> Please provide a minimal reproduction palms_up_together

what else you need to know maam? :)

**Comment by so1ve** [comment]
😂 You can provide a repository using create-vue which contains this file.

**Comment by nowshad-hossain-rahat** [comment]
> joy You can provide a repository using create-vue which contains a demo project that includes this file. Sometimes errors are related to your project configuration and we cannot reproduce it from a piece of code.

oh, sorry, the project is huge, and private, so can't share all of em, but will that be helpful if i share the config files or package.json?

**Comment by nowshad-hossain-rahat** [comment]
> You can create a fresh project, then put the problematic files into it, and delete the unnecessary parts inside it.
> 
> https://antfu.me/posts/why-reproductions-are-required#how-to-create-a-minimal-reproduction

actually the problem i am facing in every vuejs project i have, i created them with vue-cli create command, so the problem is not specific to this project, i just shown the screenshot to show the problem

**Comment by rchl** [comment]
Then provide such project so someone can check it and rule out this being a project-specific issue. In that case you should probably investigate things outside of the project like your editor configuration.

**Comment by heyakyra** [comment]
**Edit: Solutions found! https://github.com/vuejs/language-tools/discussions/5629#discussioncomment-14447960**

Interesting, I am hitting something similar where computed properties are misunderstood as `() -> ActualType` instead of `ActualType` resulting in errors like `Argument of type '() => ActualType' is not assignable to parameter of type 'ActualType'`

There also seems to be trouble understanding instance methods, which may be the underlying cause of another issue I am hitting: https://github.com/vuejs/eslint-plugin-vue/issues/2925

This is my `tsconfig.json`: 

```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "jsx": "preserve",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "verbatimModuleSyntax": true,
    "types": ["node", "vue", "vitest/globals"],
    "allowJs": true,
    "checkJs": true,
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.vue",
    "**/*.js",
  ],
  "extends": [
    "@vue/tsconfig/tsconfig.dom.json",
    "@vue/tsconfig/tsconfig.lib.json"
  ],
  "exclude": ["node_modules", "types", "dist"]
}
```

Not sure about a minimal reproduction yet, but will try
