### ISSUE TITLE
`v-if` type narrow in `v-for` with array `index` access

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/language-tools#3413]
Reproduction:
https://stackblitz.com/edit/vitejs-vite-tqrdhd?file=src%2FApp.vue

This is a simplified use case, but it will illustrate the issue.

[TS Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYwuArjApgEwDRxRYBmcAvnMVGnAOQBu6WtAUC8AHbZTECGyWOABUovDgGdi0EACUs49ABt4CFnDggsMABYQcALjjiYUTgHM4AHzgcligNxqj2MIeOmOF67cUOnMYBhFLDcTc0cyNgB6KJQ0MExcFlQJeD4AaywAQSgoABFeGF44AF5CEgAed3MAbQBdAD4AChraAEZaAloAJk66AGY+2gAWIYBWWjqASkdkiFS4jGwcOQVlUsWE5YqRMUlpVaUYeuamqdKGpwzs3IKigDp6XkUme5BeMCamwKwQc5KGnAmqp1OpNDo9IYfiA8E51MYsK46MMxgA2TpwuABIIhOgAdgAHABODHqMhTKYsGZsFg5UQATyaYym92IwF8TXoEGAODgAAYWVIoABRfjaL4AfQInBwWAAHv9AaonDFhNpgOI4AB3ea0eA6qDpAg4JhYiBwOm8ek7Bo1WwgABGWCgdTgnGIztwZuETmApCaqCWuEOykezyYNRl8rqby0uhw5xBoMDW2D8iOYZeWEjHFlcpj4PjmNVoNLZfLFYAegB+JyRNjqVUAZV49EEMHNxWw4DgT1MvAdwW17MU2ugRrgTuQvHQ4nb2nb9LAgm0vE1TqwHDdHA9uS9zyIvBw9IIC44AhQYkngg4vFyEC1SUbsQdmCxC6ItE1HHNWqtcAASUvLccHNBRkG0d9zE1Tg4AAA3oABaIU4KxX4wEUQosBVWIAAkHzgUDALHQ07wgdBczdGBa3UFJjDQnsyhTRIVnTUMnizHM8zqBs3X9bswFjCEE0QTEBKEotSxLOAazrFhyRYIA) 

Well.. I know it's not a compiler issue, since typescript itself doesn't allow this either, but how do I work it out? Since `v-for` template is not allowing me to create temporary variable for narrowing the type... I really don't want to go `JSX`, is there any alternative way?

My code:
`App.vue`
```vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import MyComponent from './components/MyComponent.vue';

interface TransformResult {
  method: string | null;
  step: string | null;
  title: string;
}

const fakeArrData = ref<string[]>(['1', '2', '3', '4', '5']);

const result = computed<TransformResult[]>(() =>
  fakeArrData.value.map((item) => ({
    method: item,
    step: '456',
    title: '789',
  }))
);
</script>

<template>
  <template v-for="(_, index) in fakeArrData">
    <!-- This won't work -->
    <MyComponent v-if="result[index].method" :method="result[index].method" />

    <!-- This won't work either -->
    <template v-if="result[index].method">
      <MyComponent :method="result[index].method" />
    </template>
  </template>
</template>
```
`MyComponent.vue`
```vue
<script setup lang="ts">
defineProps<{
  method: string;
}>();
</script>

<template>
  <span>{{ method }}</span>
</template>
```
![Snipaste_2023-07-17_16-49-31](https://github.com/vuejs/language-tools/assets/45784210/355ea646-61a4-4c08-8024-e595c40b32d0)

**Comment by so1ve** [comment]
I guess we have nothing to do here because typescript doesn't allow this usage... You can report to TypeScript :)

**Comment by xsjcTony** [comment]
@so1ve Yeah I see.. but is there any workarounds or hacky way to do so?
If in `jsx`, I can basically do something like
```tsx
return fakeArrData.map((_, index) => {
  const temp = result[index];
  return temp.method && <MyComponent method={temp.method} />
})
```
But I'm not really a fan of using `jsx` in vue...

**Comment by so1ve** [comment]
@xsjcTony 

```vue
<MyComponent v-if="result[index].method" :method="result[index].method!" />
```

**Comment by xsjcTony** [comment]
🤣Well. I guess I'll go with that. Con is another `// eslint-disable-next-line`
