### ISSUE TITLE
`// @ts-nocheck` cannot work after `vue-tsc@1.8.5` 

### ISSUE THREAD

**Issue by sxzz** [vuejs/language-tools#3414]
<img width="643" alt="image" src="https://github.com/vuejs/language-tools/assets/6481596/46be8bad-873f-4928-a0ff-ae139e2c84f8">

`ts-expect-error` and `ts-ignore` works normally, but `ts-nocheck` don't.

Relate https://github.com/sxzz/vue-macros/pull/426

**Comment by so1ve** [comment]
Maybe related to Vue Macros' volar plugin?

**Comment by sxzz** [comment]
No related to macros. Try to open anyone Vue file, and make a TS error.
<img width="358" alt="image" src="https://github.com/vuejs/language-tools/assets/6481596/15836386-7b39-48ce-a225-b2fdb4747074">

**Comment by so1ve** [comment]
Thanks, that makes sense. Possibly related: #3365.
