### ISSUE TITLE
In monorepo, components from package are not typed

### ISSUE THREAD

**Issue by Suniron** [vuejs/language-tools#3415]
Hey,

I have a monorepo where i have a Nuxt 3 app and an ui package to store some shared components between apps.

The typing of those components not works, so all components have "any" as defined on fly.

I made a monorepo to reproduce the problem: https://github.com/Suniron/nuxt3-turborepo-template

If i downgrade `vue-tsc` to 1.6.5 the type checking from CLI is repaired but not in vscode (I'm using take over mode + volar)

**Comment by Suniron** [comment]
Same with ts server + Typescript Vue Plugin (latest extensions versions).

All members of my team have this problem also

**Comment by jmroon** [comment]
This appears to not be an issue in Webstorm with Volar. I get missing required props errors in Webstorm, but not in VSCode.

**Comment by teleskop150750** [comment]
Does not work if you use a version greater than 1.8.1

vue-tsc: 1.8.1

![image](https://github.com/vuejs/language-tools/assets/62594983/3eac52bd-f233-44e9-ae0e-f9a04331d92c)

vue-tsc: >=1.8.2

![image](https://github.com/vuejs/language-tools/assets/62594983/0aef8789-7a21-4a9d-ac89-52a863b2cbfd)


[monorepo](https://github.com/teleskop150750/vue-tsc)

**Comment by Suniron** [comment]
Solved, many thanks !!!! 🥲

**Comment by jmroon** [comment]
This seems like the clear culprit:

![image](https://github.com/vuejs/language-tools/assets/36086006/e9e76569-9ac4-4e06-8cf7-7067c03a3de2)

**Comment by jmroon** [comment]
Here's an example way to sidestep this. 

I have a vue app in my `apps/my-app` dir. My libs are in `libs`. I can add this to the tsconfig.json within my-app:

```json    
"../../libs/**/*.vue",
    "../../libs/**/*.ts"
```
