### ISSUE TITLE
Types exported from a Vue file in a monorepo package are not found in the importing package with the TypeScript Vue Plugin (Non-takeover mode)

### ISSUE THREAD

**Issue by segevfiner** [vuejs/language-tools#3419]
### Steps to Reproduce
1. Have VS Code with the "Vue Langauge Features (Volar)" & "TypeScript Vue Plugin (Volar)" extensions installed
2. Clone https://github.com/segevfiner/vue-typescript-plugin-issue
3. `pnpm i`
4. `pnpm -C packages/a build`
5. `code .`
6. Open `packages/b/composables/foo.ts`.

There will be no real type for `Foo` in non-takeover mode using the TypeScript Vue Plugin, and the incorrect assignment will not be flagged in VS Code. If you run `pnpm type-check` in `packages/b` it will flag the assignment. This doesn't happen in take over mode. It seems like something isn't working in this case in the TypeScript server plugin. Weird, cause I remember this used to work.

Using VS Code 1.80.1
Volar 1.8.5
Happens with either VS Code's builtin TypeScript 5.1.6 or with the workspace TypeScript 5.0.4

**Comment by johnsoncodehk** [comment]
Thanks for the report!

**Comment by Suniron** [comment]
This error seems to be like mine https://github.com/vuejs/language-tools/issues/3415

But it's not solved for me :(

I've created a reproduction repo here https://github.com/vuejs/language-tools/issues/3415
