### ISSUE TITLE
No typescript checks on `<template>` expressions

### ISSUE THREAD

**Issue by pikax** [vuejs/language-tools#3421]
Any js expression on the template does not get checked.

```vue
<template>
  <input :key="thisPropertyDoesNotExists">
  <template v-for="test in []" :key="thisPropertyDoesNotExists"
        :random-invalid-attribute="aslokdjhaskd askdj aslkdj askjdh asodjklasd">
  </template>
</template>
```
[playground](https://play.vuejs.org/#eNqNUT1PwzAQ/SuWZ1qGblFB4qMDDKUCNsxg4mvjxLEt3zmkqvrfsROldEAVy539Pqz35AO/837eReAFXxK03kiCW2EZW2rrI7Gigf2N4FRp3ATnIdD+0QGuHa16jYSCj+rJy7rZ1oXsACSmLfv4FPwfr7AiSKtcO9O2k0armSQK+isSJJ9E4xpVVxIbxfKo0zTjampVpeVU3RiJaspzfVbm7MKvOGHp7Fbv5jU6m2ofsl7w0rVeGwgvnrSzKVHBBiZz0hj3/TxgFCJcTXhZQdn8gdfYZ0zwTQCE0IHgJ45k2AGN9OptDX06n8jWqWiS+gL5CuhMzBlH2X20KsU+0w1pn1rvAmm7e8dVT2BxKpWDZuVx0Aue/v7hQvXfuIv5YvAJe+THH08YwJM=)

The above code get's converted to 
```js
const __sfc__ = {};
import { openBlock as _openBlock, createElementBlock as _createElementBlock, renderList as _renderList, Fragment as _Fragment } from "vue"
function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock(_Fragment, null, [
    (_openBlock(), _createElementBlock("input", { key: _ctx.thisPropertyDoesNotExists })),
    (_openBlock(), _createElementBlock(_Fragment, null, _renderList([], (test) => {
      return (_openBlock(), _createElementBlock(_Fragment, { key: _ctx.thisPropertyDoesNotExists }, [], 64 /* STABLE_FRAGMENT */))
    }), 64 /* STABLE_FRAGMENT */))
  ], 64 /* STABLE_FRAGMENT */))
}
__sfc__.render = render
__sfc__.__file = "src/App.vue"
export default __sfc__
```

The Fragment is rendered with `key: _ctx.thisPropertyDoesNotExists`, other properties are ignored (AFAIK).

**Comment by so1ve** [comment]
#329, we need to add these bindings to a "usage list" so they can get checked.
