### ISSUE TITLE
自动导入的问题

### ISSUE THREAD

**Issue by rendaoer** [vuejs/language-tools#3422]
新建一个vite vue ts项目

如果我的script标签开始和结束在同一行时，自动导入就会失败。
```
<script setup lang="ts"></script>
```

如果是换了一行就可以导入成功
```
<script setup lang="ts">
</script>
```

演示视频：

https://github.com/vuejs/language-tools/assets/46780118/cf8209ef-7ebc-424c-bc9f-c54ba1b8d4c6

**Comment by so1ve** [comment]
Closed in favor of #3432
