### ISSUE TITLE
Resolve completion item time should be improved

### ISSUE THREAD

**Issue by isidorn** [vuejs/language-tools#3423]
Hi VS Code PM here 👋 

On the VS Code side we investigate the time it takes for various language extension to resolve completion items (the time it takes from user selecting an item in the suggest widget until it is ready). And we found that Volar is second slowest extension.

Could we investigate if there are some perf fixes to be done in this area.

So 90% of the users completion resolving is done only in 160ms.

Thank you 🙏 

![Screenshot 2023-07-19 at 12 05 51](https://github.com/vuejs/language-tools/assets/1926584/67a64309-13ce-464c-bed4-bdce008498d5)

**Comment by johnsoncodehk** [comment]
Hi, thanks for contacting me, I'd be more than happy to investigate it, but it lacks context. Would you mind reaching out to me on Discord for a deeper chat? My discord id is johnsoncodehk#0495, thanks!

**Comment by isidorn** [comment]
Thanks for providing more details. Let me answer your questions:

1. No big change between 1.8.5 and 1.8.4
![Screenshot 2023-07-19 at 17 25 13](https://github.com/vuejs/language-tools/assets/1926584/4588ccd2-3681-47f2-b14e-42910a5b3970)


2. Here's the data with typescript and vetur
![Screenshot 2023-07-19 at 16 44 05](https://github.com/vuejs/language-tools/assets/1926584/062b5f3f-4fa0-4673-bb4e-7a39d451cea2)

Here's astro-build.astro-vscode

![Screenshot 2023-07-19 at 17 26 38](https://github.com/vuejs/language-tools/assets/1926584/8b24ba15-aac6-426c-af46-868e0cb1649c)

**Comment by johnsoncodehk** [comment]
> 2. "Improper use of TS" overhead

I would like to correct a bit, this has a big effect on `provideCompletionItems` but seems almost no effect on `resolveCompletionItem`.

Thanks for the data! I'll schedule a time to investigate it in depth.

**Comment by johnsoncodehk** [comment]
Hi @isidorn! We fixed a certain performance issue on the Volar side (https://github.com/volarjs/volar.js/pull/66) and it may be related. Could you share the data of `vue.volar` 1.8.15 and 1.8.16 and see if any differences?

**Comment by isidorn** [comment]
@johnsoncodehk great that you worked on improving the performance.

Overall no big changes. I no longer have the query to look per extension version - apologies.

![Screenshot 2023-10-12 at 17 48 16](https://github.com/vuejs/language-tools/assets/1926584/8ce1e383-0952-4e28-8b5c-1e66384736c0)

**Comment by johnsoncodehk** [comment]
Don't worry, thanks for your help! The problem will be solved in 2.0 anyway, because TS completion will be based on TS Plugin instead of our own LSP server to avoid duplicate TS overhead.
