### ISSUE TITLE
Empty props object causes unnecessary type error

### ISSUE THREAD

**Issue by scottbedard** [vuejs/language-tools#3430]
## Reproduction

Create a component with an empty `props` object,

```ts
export default defineComponent({
  props: {}
})
```

https://play.vuejs.org/#eNrFUj1PwzAQ/SuWl4JUkqFbCZUoqhAMgIDRS0iuwcWxLdspQVX+O2c7STtAYUFMuY/nu/cub0cvtU62DdA5zRzUWuQOFkwSkpV8GwIMl3lJUkz69FqpmGOcRliWHjzG1BaGa0dELqsLRp1lFOu81so4siMlrLmEK4W5BOlIR9ZG1WSCPCYjzC+N5STF2JPcNwOFoeuTvs0ktAGAK/JGhO/hqpOdZ10MqZ2TUCB+2zRGfpqPOia7U68salnQKeoolFzzKtlYJfFi4S2jfhwXYO6140qi1nEqo7kQ6v021JxpoN+Bb16hePuivrGtrzH6YMCC2QKjY8/lpgIX26unO2gxHpu1KhuB6CPNR7BKNJ5jhC0bWSLtA1xgexNOzGX1bFetA2kHUZ5ouEzAM4on94f9Tvqe7iyZDRfFK/Y/85jjEPI37jr/rUW0Udq7o5uSNCXZGUEC7iOWiXrZQOG8P3DeaBAmUdzgxWPqBof9ozzUJNVParpPcwBkWA==

## Expected result

The component should render normally, and no type errors should occur

## Actual result

The following error is thrown

```
Argument of type '{}' is not assignable to parameter of type '({ [x: number]: string; readonly length: unknown; readonly concat: unknown; readonly join: unknown; readonly slice: unknown; readonly indexOf: unknown; readonly lastIndexOf: unknown; readonly every: unknown; readonly some: unknown; readonly forEach: unknown; ... 28 more ...; onVnodeUnmounted?: VNodeMountHook | VNode...'.ts(2345)
```

## Additional context

This is easy to side-step by simply removing the `props` object, but adds friction to things like resolving merge conflicts and component refactoring.

**Comment by so1ve** [comment]
Thanks, this is a vue core issue. https://github.com/vuejs/core/issues/8825
