### ISSUE TITLE
generic component  emits type is any with vue3.3 short defineEmits

### ISSUE THREAD

**Issue by beliefgp** [vuejs/language-tools#3431]
when not use generic, emit type is right

`test.vue`:
![image](https://github.com/vuejs/language-tools/assets/12657964/8f100399-31a6-45b2-81fc-37ba6b96269f)
![image](https://github.com/vuejs/language-tools/assets/12657964/e8a8baf9-c30a-4840-8da8-9e9d26d49d03)

when use generic, emit type is any

`test.vue`:
![image](https://github.com/vuejs/language-tools/assets/12657964/cf398cd3-3b74-4c24-becd-4e2742144b9a)
![image](https://github.com/vuejs/language-tools/assets/12657964/1cb47886-2e15-434f-a9ad-ea8e4683b810)

but, when use generic and old declaring, emit type is right
![image](https://github.com/vuejs/language-tools/assets/12657964/b207eba0-309d-416c-b35d-fc963bdc4486)
![image](https://github.com/vuejs/language-tools/assets/12657964/a89e115f-7c9d-4fd7-8a76-6a8707f7c7a3)

 

vue: 3.3.4
volar: 1.8.5
typescript: 4.9.5
vscode: 1.80.1

**Comment by so1ve** [comment]
Currently this is a limitation, please see #3196.

**Comment by chengyongjiu** [comment]
I also encountered such a problem

**Comment by so1ve** [comment]
Does it work now? I tested it locally, it works as expected
