### ISSUE TITLE
Cannot auto-import when script block's start tag and end tag is in the same line

### ISSUE THREAD

**Issue by so1ve** [vuejs/language-tools#3432]
![](https://github.com/vuejs/language-tools/assets/58381667/a6a4a316-d84e-4636-b4b3-fe185f6ebb12)

**Comment by so1ve** [comment]
Duplicate of #3422

**Comment by rchl** [comment]
I would think that we should prefer English reports over ones written in other languages, even if reported later.

**Comment by so1ve** [comment]
Duplicate of #232
