### ISSUE TITLE
Import declaration conflicts with local declaration

### ISSUE THREAD

**Issue by sxzz** [vuejs/language-tools#3433]
Reproduction: https://play.vuejs.org/#eNp9UclOwzAQ/RXLl16qVKi30iKx9AAHQMDRlyidpC6ObXnGbaQo/87YUcMi1Jv9FvvNm17eel8cI8iVXGMVtCeBQNELU9pmoyShkjfK6ta7QKIXJ037B6jLaAjFIOrgWjErFgRIs2tl14vxEbbwhaD1piTgmxD9X/OQ5JNEzvmvytlaN8UBneVAfbIpWbnWawPhxZN2lvOsRGYSVxrjTk8ZoxBhfsarPVSf/+AH7BKm5GsAhHAEJSeOytAAjfT2/Rk6Pk9k63bRsPoC+QboTEwZR9ldtDuO/UOX0z7mKrVtPnDbEVg8D5WCJuWQ9UryVu4vjP4dd1kss0/ZIbXIqygIuT/o8tK4VKTf3W/ElRy+APfsqcI=

https://github.com/vuejs/language-tools/blob/e55641bd7756ef132d6024e5f49881ade9d9de8c/packages/vue-language-core/src/generators/script.ts#L466

Should not import all macros, instead on-demand

**Comment by so1ve** [comment]
I guess we can rename them to `__VLS_macroName`?
