### ISSUE TITLE
Support Typescript: Restart TS Server

### ISSUE THREAD

**Issue by ThimoDEV** [vuejs/language-tools#3438]
![image](https://github.com/vuejs/language-tools/assets/68739517/d81de9f4-5425-494e-8c7a-dbdf5d52dbe9)

Without using takeover mode or in a react project I can use ctrl + shift + P  and click restart typescript server to fix typescript when it isn't tracking types properly anymore.

Is it possible to also have this option in takeover mode or as a new feature?

**Comment by so1ve** [comment]
You can run `Volar: Restart Vue Server` instead

**Comment by ThimoDEV** [comment]
Thank you!
