### ISSUE TITLE
The Component Tag does not support IntelliSense for events of standard HTML Tag

### ISSUE THREAD

**Issue by zgliubo** [vuejs/language-tools#3439]
such as '@click' completionItem

The component has no events completionItems
![image](https://github.com/vuejs/language-tools/assets/53201513/35038caa-8e13-404a-8160-601aef32a8b5)
The div is ok
![image](https://github.com/vuejs/language-tools/assets/53201513/7c83f844-94c7-4712-b577-05225e748cc9)

**Comment by Kcko** [comment]
I can confirm, that i have same incorrect behavior. (Latest version of VSCode & Vetur)
