### ISSUE TITLE
vue-tsc: Generic Components with await in script setup

### ISSUE THREAD

**Issue by HugeLetters** [vuejs/language-tools#3440]
I've seen there are other issues with generic components which I've also faced but haven't seen this one mentioned.
Having a generic doesn't allow to use top-level `await` - I would assume the problem is most likely more general than specifically top-level await, something with `tsconfig` maybe?

Error: **'await' expressions are only allowed within async functions and at the top levels of modules.**
![image](https://github.com/vuejs/language-tools/assets/119697239/6627fa38-3668-4872-905f-35d764c0e960)

No error
![image](https://github.com/vuejs/language-tools/assets/119697239/df4d1c15-ea80-40ac-aa7c-2256840f50bc)

```shell
- Operating System: Windows_NT
- Node Version:     v20.1.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.9
- Builder:          vite
- User Config:      modules, build, tailwindcss, googleFonts, devtools, experimental, alias
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.2, nuxt-quasar-ui@2.0.4
- Build Modules:    -
```
```json
"devDependencies": {
      "@nuxt/devtools": "^0.7.0",
      "@nuxt/eslint-config": "^0.1.1",
      "@nuxtjs/eslint-module": "^4.1.0",
      "@nuxtjs/google-fonts": "^3.0.2",
      "@types/node": "^20.4.4",
      "@typescript-eslint/eslint-plugin": "^6.1.0",
      "@typescript-eslint/parser": "^6.1.0",
      "eslint": "^8.45.0",
      "eslint-plugin-nuxt": "^4.0.0",
      "eslint-plugin-vue": "^9.15.1",
      "nuxt-quasar-ui": "^2.0.4",
      "vue-tsc": "^1.8.6"
   },
   "dependencies": {
      "@nuxtjs/tailwindcss": "^6.8.0",
      "@quasar/extras": "^1.16.5",
      "@trpc/client": "^10.35.0",
      "@trpc/server": "^10.35.0",
      "autoprefixer": "^10.4.14",
      "nuxt": "^3.6.5",
      "postcss": "^8.4.27",
      "quasar": "^2.12.3",
      "tailwindcss": "^3.3.3",
      "trpc-nuxt": "^0.10.6",
      "typescript": "^5.1.6",
      "zod": "^3.21.4"
   }
```

**Comment by jovobe** [comment]
@so1ve this fix works for VSCode, but not for WebStorm. I'm on 2023.2.1 and still get the

> Vue:  await  expressions are only allowed within async functions and at the top levels of modules.

error.

<img width="928" alt="Screenshot 2023-08-25 at 10 44 43" src="https://github.com/vuejs/language-tools/assets/1265894/86c919a1-0710-4750-918f-dcf15a0b2f1a">

I installed the latest @vue/language-server (1.8.8) globally and used this instead of the bundled 1.8.2 version in WebStorm (see screenshot).

Other maybe relevant data:
```
- Operating System: Darwin (macOS 13.5.1 (22G90))
- Node Version:     v20.5.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      devtools, modules, runtimeConfig, supabase, typescript, ui
- Runtime Modules:  @nuxthq/ui@2.7.0, @nuxtjs/supabase@1.0.2, @vueuse/nuxt@10.3.0
- Build Modules:    -
```
```JSON
  "devDependencies": {
    "@iconify-json/mdi": "^1.1.54",
    "@nuxt/devtools": "latest",
    "@nuxthq/ui": "^2.7.0",
    "@nuxtjs/supabase": "^1.0.2",
    "@types/node": "^18.17.6",
    "@vueuse/core": "^10.3.0",
    "@vueuse/nuxt": "^10.3.0",
    "better-supabase-types": "^2.6.1",
    "nuxt": "^3.6.5",
    "supabase": "^1.86.2",
    "typescript": "^5.1.6",
    "vue-tsc": "^1.8.8"
  }
```

**Comment by so1ve** [comment]
@jovobe Maybe you should report to jetbrains. They have to update volar to include this fix.
