### ISSUE TITLE
strictTemplates errors on class, id, @click

### ISSUE THREAD

**Issue by Doeke** [vuejs/language-tools#3443]
In some situations type checking fails on basic attributes and events when `strictTemplates: true`

In this repro link I demonstrate 3 different issues (run `npx vue-tsc`):

https://stackblitz.com/edit/vitejs-vite-avohbf?file=src%2FApp.vue

- Adding `id=".."` to component tag sometimes causes `Object literal may only specify known properties, and 'id' does not exist in type ...`
- Adding `class=".."` is not allowed in some cases for example with Transition/TransitionGroup and causes `Object literal may only specify known properties, but 'class' does not exist in type 'TransitionProps'`
- Adding `@click="onClick"` is not allowed on component tags (but only if there are no props defined?) and causes `Type '{ onClick: any; }' has no properties in common with type`

The first two (id and class) can be worked around by adding `dataAttributes: ["id", "class"]` to tsconfig. For `@click` errors a workaround seems to be to define one or more props on the tag.

**Comment by davidmatter** [comment]
This one seems to be resolved in 2.x. Feel free to create a issue if you're still having issues, thanks!

**Comment by cooper667** [comment]
I'm still seeing the 3rd case:

```
Adding @click="onClick" is not allowed on component tags (but only if there are no props defined?) and causes Type '{ onClick: any; }' has no properties in common with type
```

Adding a redundant prop still works as a workaround.

```
├─┬ vue-tsc@2.0.29
│ ├─┬ @vue/language-core@2.0.29
│ │ └── typescript@5.5.4
```

**Comment by davidmatter** [comment]
Can you be more specific about the 3rd point? Can you reproduce on https://play.vuejs.org/?

**Comment by cooper667** [comment]
<img width="436" alt="image" src="https://github.com/user-attachments/assets/f274c045-3781-455e-a930-51eb946b0ebc">

Line 19 is an error, 20 and 21 are not.

```
src/App.vue(19,4): error TS2559: Type '{ onClick: any; }' has no properties in common with type '{ readonly msg?: string | undefined; key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; ... 7 more ...; style?: unknown; }'.
```

https://stackblitz.com/edit/vitejs-vite-bukhvb?file=src%2FApp.vue

**Comment by KazariEX** [comment]
It works on my machine with latest version of `vue`. Maybe you just need to update deps?

**Comment by davidmatter** [comment]
Same, @Doeke please share more information about your setup (open a new issue to get inspired by a good issue template).

**Comment by cooper667** [comment]
Yea, bumping vue fixes that stackblitz

Still have the local issue, but i'll make a new issue when I can replicate in a useful way

**Comment by Doeke** [comment]
> Same, @Doeke please share more information about your setup (open a new issue to get inspired by a good issue template).

Done:

https://github.com/vuejs/language-tools/issues/4699

Hope this is enough information, would really like to be able to use the `strictTemplates` feature for our project

**Comment by phil294** [comment]
This is only fixed for TS components `lang="ts"`. JS ones still suffer from the same problem. I've updated your stackblitz repro and made a new issue here: #5420
