### ISSUE TITLE
Tag and SCSS auto complete and suggestions not working

### ISSUE THREAD

**Issue by panagiotisTB** [vuejs/language-tools#3444]
For some reason, I'm not getting any suggestions.
Did I miss breaking changes?

![CleanShot 2023-07-25 at 08 22 53](https://github.com/vuejs/language-tools/assets/12424632/7edeba51-be88-4810-bec7-4044c6496e11)

**Comment by panagiotisTB** [comment]
Not sure how to reproduce this. Started developing a new site and "found it like this". Tried going back a couple versions, with no success.

**Comment by so1ve** [comment]
🤔Could you please try extension bisect? Have you installed volar?

**Comment by panagiotisTB** [comment]
@so1ve, thanks for the quick response. I could not find anything with bisect.
These are my installed extensions. I had more, but removed the ones I don't need before creating an issue.

- Auto Rename Tag
- CSS Peek
- Fig
- Night Owl
- Prettier - Code formatter
- Vue Language Features (Volar)

**Comment by so1ve** [comment]
@panagiotisTB Thanks for you reply. Is the highlight correct?

**Comment by panagiotisTB** [comment]
Hey @so1ve, here you go:

`[Trace - 9:01:34 AM] Sending request 'initialize - (0)'.
[Trace - 9:01:34 AM] Received response 'initialize - (0)' in 430ms.
[Trace - 9:01:34 AM] Sending notification 'initialized'.
[Trace - 9:01:34 AM] Sending request 'vue/parseSfc - (1)'.
[Trace - 9:01:34 AM] Sending request 'volar/client/tsconfig - (2)'.
[Trace - 9:01:34 AM] Sending notification 'textDocument/didOpen'.
[Trace - 9:01:34 AM] Sending request 'vue/detectTagCasing - (3)'.
[Trace - 9:01:34 AM] Received request 'client/registerCapability - (0)'.
[Trace - 9:01:34 AM] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 9:01:34 AM] Sending request 'textDocument/codeAction - (4)'.
[Trace - 9:01:34 AM] Sending request 'textDocument/documentLink - (5)'.
[Trace - 9:01:34 AM] Sending request 'textDocument/inlayHint - (6)'.
[Trace - 9:01:34 AM] Received request 'workspace/configuration - (1)'.
[Trace - 9:01:34 AM] Sending response 'workspace/configuration - (1)'. Processing request took 0ms
[Trace - 9:01:34 AM] Received request 'client/registerCapability - (2)'.
[Trace - 9:01:34 AM] Sending response 'client/registerCapability - (2)'. Processing request took 0ms
[Trace - 9:01:34 AM] Sending notification 'workspace/didChangeWorkspaceFolders'.
[Trace - 9:01:34 AM] Received request 'client/registerCapability - (3)'.
[Trace - 9:01:34 AM] Sending response 'client/registerCapability - (3)'. Processing request took 1ms
[Trace - 9:01:34 AM] Received response 'vue/parseSfc - (1)' in 97ms.
[Trace - 9:01:34 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:34 AM] Sending request 'textDocument/documentLink - (7)'.
[Trace - 9:01:34 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:34 AM] Sending request 'textDocument/documentLink - (8)'.
[Trace - 9:01:35 AM] Sending request 'textDocument/codeLens - (9)'.
[Trace - 9:01:36 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:36 AM] Sending request 'textDocument/codeAction - (10)'.
[Trace - 9:01:38 AM] Sending request 'textDocument/documentHighlight - (11)'.
[Trace - 9:01:38 AM] Sending request 'textDocument/codeAction - (12)'.
[Trace - 9:01:38 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:39 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:39 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:39 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:39 AM] Sending request 'volar/client/autoInsert - (13)'.
[Trace - 9:01:39 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:39 AM] Sending request 'textDocument/codeLens - (14)'.
[Trace - 9:01:40 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:40 AM] Sending request 'textDocument/inlayHint - (15)'.
[Trace - 9:01:40 AM] Sending request 'textDocument/documentLink - (16)'.
[Trace - 9:01:40 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:40 AM] Sending request 'textDocument/completion - (17)'.
[Trace - 9:01:40 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:41 AM] Sending request 'volar/client/autoInsert - (18)'.
[Trace - 9:01:41 AM] Sending request 'textDocument/codeAction - (19)'.
[Trace - 9:01:41 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:41 AM] Sending request 'textDocument/codeLens - (20)'.
[Trace - 9:01:42 AM] Sending request 'textDocument/inlayHint - (21)'.
[Trace - 9:01:42 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:42 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:42 AM] Sending request 'volar/client/autoInsert - (22)'.
[Trace - 9:01:42 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:42 AM] Sending request 'textDocument/codeLens - (23)'.
[Trace - 9:01:42 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:42 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:42 AM] Sending request 'volar/client/autoInsert - (24)'.
[Trace - 9:01:43 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:43 AM] Sending request 'textDocument/codeLens - (25)'.
[Trace - 9:01:43 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:43 AM] Sending request 'textDocument/completion - (26)'.
[Trace - 9:01:43 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:43 AM] Sending request 'volar/client/autoInsert - (27)'.
[Trace - 9:01:43 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:43 AM] Sending request 'volar/client/autoInsert - (28)'.
[Trace - 9:01:43 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:01:43 AM] Sending request 'volar/client/autoInsert - (29)'.
[Trace - 9:01:43 AM] Sending request 'textDocument/codeAction - (30)'.
[Trace - 9:01:44 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:44 AM] Sending request 'textDocument/codeLens - (31)'.
[Trace - 9:01:44 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:44 AM] Sending request 'textDocument/inlayHint - (32)'.
[Trace - 9:01:45 AM] Sending request 'textDocument/documentLink - (33)'.
[Trace - 9:01:52 AM] Sending request 'textDocument/inlayHint - (34)'.
[Trace - 9:01:53 AM] Sending notification '$/cancelRequest'.
[Trace - 9:01:53 AM] Sending request 'textDocument/inlayHint - (35)'.
[Trace - 9:01:59 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:02 AM] Sending request 'vue/parseSfc - (36)'.
[Trace - 9:02:02 AM] Sending request 'volar/client/tsconfig - (37)'.
[Trace - 9:02:02 AM] Sending request 'vue/detectTagCasing - (38)'.
[Trace - 9:02:03 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:03 AM] Sending request 'textDocument/codeLens - (39)'.
[Trace - 9:02:03 AM] Sending request 'textDocument/documentHighlight - (40)'.
[Trace - 9:02:03 AM] Sending request 'textDocument/codeAction - (41)'.
[Trace - 9:02:03 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:03 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:03 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:03 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:03 AM] Sending request 'volar/client/autoInsert - (42)'.
[Trace - 9:02:04 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:04 AM] Sending request 'volar/client/autoInsert - (43)'.
[Trace - 9:02:04 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:04 AM] Sending request 'volar/client/autoInsert - (44)'.
[Trace - 9:02:04 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:04 AM] Sending request 'volar/client/autoInsert - (45)'.
[Trace - 9:02:04 AM] Sending request 'textDocument/codeAction - (46)'.
[Trace - 9:02:04 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:04 AM] Sending request 'textDocument/codeLens - (47)'.
[Trace - 9:02:05 AM] Sending request 'textDocument/inlayHint - (48)'.
[Trace - 9:02:06 AM] Sending request 'textDocument/documentLink - (49)'.
[Trace - 9:02:07 AM] Sending request 'textDocument/codeAction - (50)'.
[Trace - 9:02:07 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:07 AM] Sending notification 'textDocument/didSave'.
[Trace - 9:02:07 AM] Sending notification 'workspace/didChangeWatchedFiles'.
[Trace - 9:02:15 AM] Sending request 'vue/parseSfc - (51)'.
[Trace - 9:02:15 AM] Sending request 'volar/client/tsconfig - (52)'.
[Trace - 9:02:15 AM] Sending request 'vue/detectTagCasing - (53)'.
[Trace - 9:02:15 AM] Sending request 'textDocument/codeAction - (54)'.
[Trace - 9:02:15 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:15 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:15 AM] Sending request 'textDocument/codeLens - (55)'.
[Trace - 9:02:16 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:16 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:16 AM] Sending request 'volar/client/autoInsert - (56)'.
[Trace - 9:02:16 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:16 AM] Sending request 'textDocument/codeLens - (57)'.
[Trace - 9:02:17 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:17 AM] Sending request 'textDocument/inlayHint - (58)'.
[Trace - 9:02:17 AM] Sending request 'textDocument/documentLink - (59)'.
[Trace - 9:02:17 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:18 AM] Sending request 'textDocument/completion - (60)'.
[Trace - 9:02:18 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:18 AM] Sending request 'volar/client/autoInsert - (61)'.
[Trace - 9:02:18 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:18 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:18 AM] Sending request 'volar/client/autoInsert - (62)'.
[Trace - 9:02:18 AM] Sending request 'textDocument/codeAction - (63)'.
[Trace - 9:02:18 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:18 AM] Sending request 'textDocument/codeLens - (64)'.
[Trace - 9:02:19 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:19 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:19 AM] Sending request 'volar/client/autoInsert - (65)'.
[Trace - 9:02:19 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:19 AM] Sending request 'volar/client/autoInsert - (66)'.
[Trace - 9:02:19 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:19 AM] Sending request 'volar/client/autoInsert - (67)'.
[Trace - 9:02:19 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:19 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:19 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:19 AM] Sending request 'volar/client/autoInsert - (68)'.
[Trace - 9:02:20 AM] Sending request 'textDocument/codeAction - (69)'.
[Trace - 9:02:20 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:20 AM] Sending request 'textDocument/codeLens - (70)'.
[Trace - 9:02:20 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:20 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:20 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:20 AM] Sending request 'textDocument/completion - (71)'.
[Trace - 9:02:20 AM] Sending request 'volar/client/autoInsert - (72)'.
[Trace - 9:02:20 AM] Sending request 'textDocument/codeAction - (73)'.
[Trace - 9:02:20 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:20 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:20 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:20 AM] Sending request 'textDocument/completion - (74)'.
[Trace - 9:02:21 AM] Sending request 'volar/client/autoInsert - (75)'.
[Trace - 9:02:21 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:21 AM] Sending request 'textDocument/codeLens - (76)'.
[Trace - 9:02:22 AM] Sending request 'textDocument/inlayHint - (77)'.
[Trace - 9:02:22 AM] Sending request 'textDocument/documentLink - (78)'.
[Trace - 9:02:24 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:24 AM] Sending request 'volar/client/autoInsert - (79)'.
[Trace - 9:02:24 AM] Sending request 'textDocument/codeAction - (80)'.
[Trace - 9:02:24 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:24 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:24 AM] Sending request 'volar/client/autoInsert - (81)'.
[Trace - 9:02:24 AM] Sending request 'textDocument/codeAction - (82)'.
[Trace - 9:02:24 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:24 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:24 AM] Sending request 'volar/client/autoInsert - (83)'.
[Trace - 9:02:25 AM] Sending request 'textDocument/codeAction - (84)'.
[Trace - 9:02:25 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:25 AM] Sending request 'textDocument/codeLens - (85)'.
[Trace - 9:02:25 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:25 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:25 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:25 AM] Sending request 'textDocument/completion - (86)'.
[Trace - 9:02:25 AM] Sending request 'volar/client/autoInsert - (87)'.
[Trace - 9:02:25 AM] Sending request 'textDocument/signatureHelp - (88)'.
[Trace - 9:02:25 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:25 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:25 AM] Sending request 'textDocument/completion - (89)'.
[Trace - 9:02:26 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:26 AM] Sending request 'textDocument/signatureHelp - (90)'.
[Trace - 9:02:26 AM] Sending request 'volar/client/autoInsert - (91)'.
[Trace - 9:02:26 AM] Sending request 'textDocument/codeAction - (92)'.
[Trace - 9:02:26 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:26 AM] Sending request 'textDocument/codeLens - (93)'.
[Trace - 9:02:27 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:27 AM] Sending request 'textDocument/inlayHint - (94)'.
[Trace - 9:02:27 AM] Sending request 'textDocument/documentLink - (95)'.
[Trace - 9:02:27 AM] Sending notification 'textDocument/didChange'.
[Trace - 9:02:27 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:27 AM] Sending request 'volar/client/autoInsert - (96)'.
[Trace - 9:02:27 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:27 AM] Sending request 'textDocument/signatureHelp - (97)'.
[Trace - 9:02:27 AM] Sending request 'textDocument/codeAction - (98)'.
[Trace - 9:02:27 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:27 AM] Sending request 'textDocument/codeLens - (99)'.
[Trace - 9:02:28 AM] Sending request 'textDocument/inlayHint - (100)'.
[Trace - 9:02:29 AM] Sending request 'textDocument/documentLink - (101)'.
[Trace - 9:02:30 AM] Sending notification '$/cancelRequest'.
[Trace - 9:02:30 AM] Sending request 'textDocument/inlayHint - (102)'.
[Trace - 9:03:07 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:07 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:07 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:07 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:07 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:07 AM] Sending notification 'textDocument/didOpen'.
[Trace - 9:03:07 AM] Sending request 'vue/parseSfc - (103)'.
[Trace - 9:03:07 AM] Sending request 'volar/client/tsconfig - (104)'.
[Trace - 9:03:07 AM] Sending request 'vue/detectTagCasing - (105)'.
[Trace - 9:03:07 AM] Sending request 'textDocument/codeAction - (106)'.
[Trace - 9:03:07 AM] Sending request 'textDocument/documentLink - (107)'.
[Trace - 9:03:07 AM] Sending request 'textDocument/inlayHint - (108)'.
[Trace - 9:03:07 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:07 AM] Sending request 'textDocument/codeLens - (109)'.
[Trace - 9:03:08 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:08 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:08 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:16 AM] Sending request 'vue/parseSfc - (110)'.
[Trace - 9:03:16 AM] Sending request 'volar/client/tsconfig - (111)'.
[Trace - 9:03:16 AM] Sending request 'vue/detectTagCasing - (112)'.
[Trace - 9:03:16 AM] Sending request 'textDocument/codeAction - (113)'.
[Trace - 9:03:16 AM] Sending request 'textDocument/documentLink - (114)'.
[Trace - 9:03:16 AM] Sending request 'textDocument/inlayHint - (115)'.
[Trace - 9:03:16 AM] Sending notification '$/cancelRequest'.
[Trace - 9:03:17 AM] Sending request 'textDocument/codeLens - (116)'.
`

**Comment by so1ve** [comment]
I can't find any problem from the logs 😅 So sorry, I can't solve your problem now. Please wait for Johnson to look into this 😥

**Comment by panagiotisTB** [comment]
@so1ve I went ahead and created a new project, since I was just starting off with that. Seemingly, the issue was project specific. Not sure why though. I guess we can close this. If it should reoccur, I'll make sure to reopen it :)

Thanks again for trying! 🙏

**Comment by johnsoncodehk** [comment]
Closed due to inactivity.
