### ISSUE TITLE
adding <script setup> to component with <script> creates error

### ISSUE THREAD

**Issue by Leni-Vienne** [vuejs/language-tools#3449]
This is a very minor bug with a simple workaround.
Adding a <script setup> tag (and closing it) to a component that already has a <script> tag will create an 'error' (in red) on the original script tag that says : 
`JSX element 'script' has no corresponding closing tag". ts(17008)`
![image](https://github.com/vuejs/language-tools/assets/71212417/b7c81049-37e4-4786-8ced-862ebfac20e3)
A simple cut and paste on the first two lines will solve the problem. This error only occurs when typing manually the tag <script setup>, not on pasting it.

I'm using the 24th of july version of the extension, and there is no typescript in my project, only JS

**Comment by so1ve** [comment]
![](https://github.com/vuejs/language-tools/assets/58381667/f7219ae0-e14f-4dd9-ac39-ced6d04b977c)
