### ISSUE TITLE
Property '...' does not exist on type 'Ref<...>' when returning refs from setup function

### ISSUE THREAD

**Issue by nils4cosee** [vuejs/language-tools#3451]
We have the following setup:  vite, vue 2.7, vue-tsc.
When we are using the comosition API, `vue-tsc` fails to unref properties returned by the setup function correctly.

For example, for this component, `vue-tsc` complains:

```vue
<template>
  <div>
    Range: {{range.min}} - {{range.max}}
  </div>
</template>

<script lang="ts">
import Vue, {ref} from "vue";
export default Vue.extend({
  name: "App",
  setup() {
    const range = ref({min: 0, max: 10})
    return {
      range
    }
  }
})
</script>
```

```
src/App.vue:3:20 - error TS2339: Property 'min' does not exist on type 'Ref<{ min: number; max: number; }>'.

3     Range: {{range.min}} - {{range.max}}
                     ~~~

src/App.vue:3:36 - error TS2339: Property 'max' does not exist on type 'Ref<{ min: number; max: number; }>'.

3     Range: {{range.min}} - {{range.max}}

```

If we write the same component in `script setup`-style, there are no problems, but we cannot do that, because our `jest` version
does not support this yet.

We have a reproduction-repo at https://github.com/nils4cosee/vue2-tsc-error-reproduction

We would be grateful for any help.

**Comment by so1ve** [comment]
@nils4cosee Does vue 2.7 automatically unwrap refs on vue instances? If so, there might be a bug in vue's types.

**Comment by rchl** [comment]
Not sure what's the Vue team's official stance on it but I'm fairly sure that `Vue.extend` are kind of a legacy types. You should be using `defineComponent` which doesn't have issues with that code.


```vue
<template>
    <div>
        Range: {{ range.min }} - {{ range.max }}
    </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
    name: 'App',
    setup() {
        const range = ref({ min: 0, max: 10 })
        return {
            range,
        }
    },
})
</script>
```

**Comment by so1ve** [comment]
@rchl Yeah, after discussion with @sxzz I figured out we should use `defineComponent` here

**Comment by sxzz** [comment]
Yes. For Vue 2 with Composition API, we prefer to use `defineComponent`. That's also why we introduced a new API.

**Comment by nils4cosee** [comment]
I am not sure if it will solve all our problems, but it is a huge leap forward. Thanks for the tip.

I noticed however that "defineComponent" has trouble inferring types, when there is a "setup" and a "data" method. But this is a relatively simple migration, so I don't see a problem there.

I will close this issue.
