### ISSUE TITLE
v1.8.7 possible missing library after updating

### ISSUE THREAD

**Issue by Rotinx** [vuejs/language-tools#3453]
Able to downgrade back down to v1.8.6 in the mean time.

![image](https://github.com/vuejs/language-tools/assets/39930952/79809c97-4ca9-44f7-b232-fe8c1f5c8c4d)

Let me know if you need more information.

**Comment by TiagoRibeiro25** [comment]
same

**Comment by johnsoncodehk** [comment]
Thanks for the report! Fixed by https://github.com/vuejs/language-tools/commit/05da2c2670d15d3dd42d8e90cfe6e824a4c37bcb.
