### ISSUE TITLE
False ts(1261) error message

### ISSUE THREAD

**Issue by G-Jasser** [vuejs/language-tools#3457]
## Issue:
![False error](https://github.com/vuejs/language-tools/assets/123377848/e0fd5272-ab9b-4a0f-b4f1-7466491cbdd1)
False TS(1261) error message displayed in VS Code
## Steps to reproduce:
![step1](https://github.com/vuejs/language-tools/assets/123377848/fc43c5f3-1acd-40d8-aa5e-1f0e77f5ee7a)
![step2](https://github.com/vuejs/language-tools/assets/123377848/21bec9ae-96e5-48f6-a782-04f6936a5efe)
![step3](https://github.com/vuejs/language-tools/assets/123377848/98f0da6e-85cb-43bd-8d35-fd82bfac38d4)
### Temporary solution:
For anyone who is looking for a solution, reverting to Volar 1.8.6 fixed it for me.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved by now. If not, feel free to create a new one.
