### ISSUE TITLE
Throwing ERROR(vue-tsc) from an external library

### ISSUE THREAD

**Issue by AlanLes** [vuejs/language-tools#3458]
Hello, after updating `vue-tsc` to `1.8.8` in one of the projects, I'm having problems with it throwing an error from an external library. When the project runs with vite, the `vue-tsc` throws an error from the [external open-source component-library](https://github.com/infermedica/component-library). This library is based on a different `vue-tsc` version, but I think it shouldn't be an issue (it's an external library after all), should it? I think the `skipLibCheck` flag in the `tsconfig.json` should do the job, but for some reason it doesn't.

The tsconfig in the project is the following:
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "allowJs": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "noImplicitAny": true,
    "jsx": "preserve",
    "lib": [
      "esnext",
      "dom",
      "dom.Iterable"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "verbatimModuleSyntax": true,
    "importHelpers": true,
    "experimentalDecorators": true,
    "baseUrl": "./",
    "paths": {
      "@/*": [
        "src/*"
      ],
      "@customization/*": [
        "customization/*"
      ]
    },
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "ESNext",
    "types": [
      "vitest/globals",
      "vite/client"
    ],
    "useDefineForClassFields": true
  },
  "include": [
    "src/**/*",
    "tests/**/*",
    "e2e/**/*",
    "stories/**/*",
    "scripts/**/*",
    "customization/**/*",
    "**/*.ts.vue",
    ".eslintrc.js",
    "vite.config.ts",
    "playwright.config.ts",
    "vite-plugins/*.ts"
  ]
}
```

**Comment by becbaile-te** [comment]
I am seeing this too. `skipLibCheck` is true and `node_modules` is in the excludes array, but I am still seeing errors related to node_modules.

```
> npx vue-tsc --project tsconfig.gen-dts.json --noEmit

node_modules/vue-slider-component/lib/utils/control.ts:554:22 - error TS6133: 'pos' is declared but its value is never read.

554     dotsPos.forEach((pos, i) => {
                         ~~~


Found 1 error in node_modules/vue-slider-component/lib/utils/control.ts:554
```

**Comment by AlanLes** [comment]
Yeeep, but I have those for the `.vue` files (which are obviously not `.ts` files), so what in this case?

**Comment by so1ve** [comment]
I'm not sure if we can avoid this behavior: https://github.com/vuejs/language-tools/blob/master/packages/vue-tsc/bin/vue-tsc.js#L15-L17

Volar needs to patch tsc to include `.vue` files so they can get typechecked, which leads to this error

**Comment by desprit** [comment]
I have no direct imports from the `node_modules` but still have that same issue in turbo monorepo.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
