### ISSUE TITLE
[Feature Request] Some way to ignore certain tokens like `<<<`

### ISSUE THREAD

**Issue by brc-dd** [vuejs/language-tools#3459]
VitePress provides a `<<< @/filepath` syntax to [import code snippets](https://vitepress.dev/guide/markdown#import-code-snippets). But with volar it shows `Illegal tag name. Use '&lt;' to print '<'. vue(12)`. Which is technically right, but I need some way to skip checking for this.

**Comment by so1ve** [comment]
@brc-dd More thoughts: can vite press parse these code:
```md
< // Un closed tag
<<

</foo> // missing open tag
```
?

If so, I think we should support them as well

**Comment by brc-dd** [comment]
It can parse the first two, but not the third. Although, using them like that is not recommended. People should use `&lt;` or `{{ '<' }}` instead if they want to render `<`
