### ISSUE TITLE
indent is increased after every save

### ISSUE THREAD

**Issue by hdrodel** [vuejs/language-tools#3471]
I have the problem, that every time i save and my code gets formatted, one of the lines is indented more

https://github.com/vuejs/language-tools/assets/7040858/b45c5b43-b586-4f02-800f-d7cfbd913bb8

Edit:
If i change the code to this:
```
 @dialogClosed="() => {
        try {
          passedItem.reset();
        } catch (err) { }
        passedItem = Object.assign({}, new Purchase());
        reload();
      }
        "
```
The problem does not exist.

**Comment by so1ve** [comment]
Hi @hdrodel, IMO your usage is incorrect. Can vue accept a bunch of statements as the event handler?

**Comment by hdrodel** [comment]
> Hi @hdrodel, IMO your usage is incorrect. Can vue accept a bunch of statements as the event handler?

Well it seems like it worked. I agree that the initial solution might not have been very clean but I believe it should have shown as an error with a red underline or something but not look like everything is fine but cause the indent to malfunction

**Comment by so1ve** [comment]
I guess the syntax error in virtual file is not mapped to the vue sfc file. I'll check later

**Comment by so1ve** [comment]
I don't think we should fix the format problem since the code is invalid.

**Comment by andradedanilo** [comment]
I have been experiencing this issue as well when using Volar as formatter.

https://github.com/vuejs/language-tools/assets/58144404/99b84f15-a8d6-434b-8c91-28f5fb55f766

**Comment by so1ve** [comment]
@andradedanilo Please open a new issue for that.

**Comment by so1ve** [comment]
@andradedanilo Please open a new issue for that.

**Comment by johnsoncodehk** [comment]
Fixed in v2.
