### ISSUE TITLE
[Feature Request] VitePress markdown support in vue-tsc

### ISSUE THREAD

**Issue by skirtles-code** [vuejs/language-tools#3472]
Volar in VS Code already supports type checking VitePress markdown files via `vue.server.vitePress.supportMdFile`. I'd like to be able to run type checking for `.md` files from the command line using `vue-tsc`.

The use case is a pre-commit hook that I'm using to run type checks prior to every commit.

**Comment by so1ve** [comment]
🤔 I guess you need to add markdown files into your `tsconfig.json`'s `include` field

**Comment by skirtles-code** [comment]
@so1ve I believe my configuration is all correct. It works fine in VS Code, but they're ignored by `vue-tsc`.

I originally asked this as a question in #3448 and Johnson suggested (not on that thread) that I should open a feature request for it.

**Comment by johnsoncodehk** [comment]
Supported by #4251
