### ISSUE TITLE
TypeScript not working on templates from VSCode 1.79 on

### ISSUE THREAD

**Issue by hugoaboud** [vuejs/language-tools#3475]
I'm using Volar `1.8.8` without `TypeScript Vue Plugin`, it's been working very well so far.

However, after updating VS Code to the latest version (1.81), I've found that template types stopped working. Installing `TypeScript Vue Plugin` didn't help.

I've downgraded it version by version and found that `1.78` works.

I'm fine using a downgraded version for now, just opening the issue to mention.

**Comment by so1ve** [comment]
Which typescript version do you use?

**Comment by hugoaboud** [comment]
Sorry for not including it sooner, its `5.1.6`.

**Comment by nekocom3745** [comment]
https://github.com/vuejs/language-tools/issues/3475#issue-1840463635

**Comment by Clemrc** [comment]
Takeover mode issue maybe ?

**Comment by polRk** [comment]
<img width="803" alt="image" src="https://github.com/vuejs/language-tools/assets/39828645/749b0a7d-2295-42e8-867f-5d0f8a7c262d">

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
