### ISSUE TITLE
Fast Fix feature(auto import) is lost in volar new version.

### ISSUE THREAD

**Issue by warmthsea** [vuejs/language-tools#3477]
Volar version 1.2.0，.vue / .ts  have fast fix (auto import) other file export function/type/data
Volar new version 1.4.0 ~ 1.8.8    lost this very useful feature，but .ts works after turning off managed mode

other issus: https://github.com/vuejs/language-tools/issues/2707

repro case: 
https://github.com/warmthsea/vitesse-lite
https://github.com/warmthsea/vitesse-lite#readme

![92ba8513f5bc6352f6a056806798051b](https://github.com/vuejs/language-tools/assets/45450994/55454a77-d16d-44db-b23d-1b10e886d695)

![image](https://github.com/vuejs/language-tools/assets/45450994/588110ba-5d7c-4eab-a1c1-7ae7742288c8)
![image](https://github.com/vuejs/language-tools/assets/45450994/86c0ec0d-0fd9-4e17-8db7-2c2d88d08535)
![image](https://github.com/vuejs/language-tools/assets/45450994/35ce8349-dc04-409d-a42a-1db90f1ee6a7)

**Comment by youkei-zzz** [comment]
what happened to johnsoncodehk?

**Comment by shakamiuu** [comment]
这个问题除了降到1.2.0还有其他解决方案吗？
我两台电脑，设置和插件都是同步的，一台上最新版本没有问题能正常提示，另一台就不行，版本降下去才能用

**Comment by warmthsea** [comment]
2.0 is support
