### ISSUE TITLE
Take over mode will broken code lens

### ISSUE THREAD

**Issue by cary-hu** [vuejs/language-tools#3482]
Hi volar team,

When I install volar in my project, and follow the [guide](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) to disable buildin TS feature, My code lens broken.
![image](https://github.com/vuejs/docs/assets/41052104/27b868ad-8486-485e-9c51-ea819f22122d)
![image](https://github.com/vuejs/docs/assets/41052104/fd2cfc6a-53b3-4c6b-b2eb-74e0f2edeaca)

Code lens will help me found the code block reference, It's very helpful.

How can I enable code lens when I using volar in my project?

**Comment by MingNeo** [comment]
I have a similar issue where the merge code lens is missing in the conflicting files of Vue.
![image](https://github.com/vuejs/language-tools/assets/4495272/61703328-2f40-4190-ba35-6dfa7dc4d783)
![image](https://github.com/vuejs/language-tools/assets/4495272/15fb55b7-cc1f-406d-aed0-5f47377189cd)

**Comment by cary-hu** [comment]
@brc-dd  Of coure using Volar typescript plugin, but in this (Guide)[https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode] telled the buildin ts language feature will cause performance issue, so I should disable ts language feature, and then, some bad thing happen, like:
- Code lens broken
- Git lens broken
- etc...
