### ISSUE TITLE
Pug class wrong underline 

### ISSUE THREAD

**Issue by abigale-dev** [vuejs/language-tools#3485]
![image](https://github.com/vuejs/language-tools/assets/83122224/fda571a9-a531-40d6-9045-937d56591a11)
![image](https://github.com/vuejs/language-tools/assets/83122224/87ef8606-b37a-4fe7-adfd-8af85e59fa27)

What's wrong? Last versions

**Comment by Ericlm** [comment]
The `div` declaration is in the script block, I think it causes the issue 🙂

**Comment by so1ve** [comment]
Duplicate of #1767
