### ISSUE TITLE
When using verbose syntax of v-model, if the argument is generic, parent will show it as `any`, reporting error

### ISSUE THREAD

**Issue by rodrigocfd** [vuejs/language-tools#3489]
When using the verbose syntax of [component v-model](https://vuejs.org/guide/components/v-model.html), when the argument is a generic parameter, the parent component won't type the argument, which will appear as `any`. Reproducible example below.

* Child component:

```vue
<script setup lang="ts" generic="T">
const props = defineProps<{
	modelValue: T;
}>();

const emit = defineEmits<{
	'update:modelValue': [value: T];
}>();
</script>

<template>
	Hi
</template>
```

* Parent component:

```vue
<script setup lang="ts">
import {ref} from 'vue';
import Child from './Child.vue';

const name = ref('Evan');
</script>

<template>
	<Child :modelValue="name"
		@update:modelValue="v => name = v" />
</template>
```

What happens:

![repro](https://github.com/vuejs/core/assets/1283868/5a08b1c6-d08b-4f59-a1c4-2ec0911549ee)

Repo with reproduction: https://github.com/rodrigocfd/vue-bug-generic

**Comment by davidmatter** [comment]
@johnsoncodehk This was fixed in 1.8.14 https://github.com/vuejs/language-tools/commit/5febf2694e80621a7b852464edc76b74f73a5cb6
