### ISSUE TITLE
Unhelpful output / outdated errors / tsconfig.tsbuildinfo not cleaned up

### ISSUE THREAD

**Issue by stefaneg** [vuejs/language-tools#3490]
This issue is regarding vue-tsc. I hope this is the correct place to report this.

This is a randomly occurring issue which I have now seen a couple of times. The issue is threefold as I see it:

- vue-tsc is reporting errors on an old state of the code.
- Output from compiler that is unhelpful/confusing.
- Retaining an outdated temporary file.

The output looks like this. Note the lack of source file information.

![image](https://github.com/vuejs/language-tools/assets/140227/e37b2af6-5040-455b-bad2-0146355eed8c)

Changing the source code and removing these errors had no effect on this output. vue-tsc continued to output these errors until  I manually deleted tsconfig.tsbuildinfo

Version info:

    "vue": "3.3.4",
    "vue-tsc": "1.6.5"

**Comment by johnsoncodehk** [comment]
2.0 has improved the related situation. If you still encounter this problem, please reopen an issue and provide a repro case, htnka.
