### ISSUE TITLE
File path suggestions duplicate with path-autocomplete

### ISSUE THREAD

**Issue by niaodan2b** [vuejs/language-tools#3492]
Not sure if this should be a feature request, but is there a way to disable Volar's path suggestions?

Like we can disable VSCode's built-in path suggestions with `javascript.suggest.paths: false` and `typescript.suggest.paths: false`, which is required when using path-autocomplete extension to avoid duplication. Can we have similar settings in Volar?

One workaround to this is disabling path-autocomplete for *.vue files, leaving only Volar's suggestions, which is not quite what I want because I need the customizability of path-autocomplete (folder trailing slash, file extensions, etc)

![](https://i.imgur.com/vxhSoWr.png)

**Comment by so1ve** [comment]
IMO you should disable the path complete extension, since vscode already handles path complete...
