### ISSUE TITLE
Malfunction upon creating a new Vue SFC.

### ISSUE THREAD

**Issue by CHIBX** [vuejs/language-tools#3494]
In my Nuxt application, whenever I create a new component during development, all the features that come with Volar, including the Intesllisense simply stop working until I reload my workspace.

**Comment by DouglasAR01** [comment]
+1. I have the same issue but only when I create a new page.

**Comment by davidmatter** [comment]
Tracking in https://github.com/vuejs/language-tools/issues/4424
