### ISSUE TITLE
Events defined with short `defineEmits` form lose their documentation

### ISSUE THREAD

**Issue by rijenkii** [vuejs/language-tools#3495]
When using `defineEmits` with the new short form, all events lose their documentation.

Example of code that is working as expected (long emits form):
```vue
<script setup lang="ts">
const emit = defineEmits<{
  /** Event docstring. */
  (e: "event"): void;
}>();

emit("event");
</script>
```
Hover tooltip contents:
```
const emit: (e: "event") => void
Event docstring.
```

Example of code that is not working as expected (short emits form):
```vue
<script setup lang="ts">
const emit = defineEmits<{
  /** Event docstring. */
  "event": [],
}>();

emit("event");
</script>
```
Hover tooltip contents:
```
const emit: (evt: "event") => void
```

[playground](https://play.vuejs.org/#eNq1kTFPwzAQhf/K6aa2qlKhbqGtBCgDDICAjWOokmtwSWzLdkKlKv+dc6qmDKhi6WT7vWff57s93libtA1jigufO2UDeA6NhWqtyyVh8IQr0rnRPgDXKsASCt4ozZkc/GJPGmA2mUDWsg5QmNwHp3SZwGQWrRGnQMjRJByn0BpVXJPuVqOxLKTjk6NTQLTF7MCxwqlUl8IbVSZbb7Qg9tUIc1NbVbF7skEJGGEKvRO9dVWZ74deC67h6VHPPzn/+kPf+l3UCJ8de3YtEw5eWLuSBSva2esj72Q/mLUpmkrSZ8wX9qZqIuMhdtvoQrB/5Xra+9oaF6Rpbz7bBdb++KkIGpNdnyeUOd2d+foJd57M+3vSaOlivHN1ySEP80vh/UNY/zXd7gcMKdBB). Hover mouse cursor above `emit("event")`.

**Comment by so1ve** [comment]
Shouldn't this be a Vue core issue?

**Comment by rijenkii** [comment]
Actually yes, this is reproducing even in typescript playground. Feel free to close this issue, I will open a new in vuejs/core later.
