### ISSUE TITLE
[feature request] Add button in VSCode status bar to restart Vue Language Server

### ISSUE THREAD

**Issue by angelhdzmultimedia** [vuejs/language-tools#3499]
### Discussed in https://github.com/vuejs/language-tools/discussions/3498

<div type='discussions-op-text'>

<sup>Originally posted by **angelhdzmultimedia** August 22, 2023</sup>
Hi.

Is there a VSCode extension, or an option in Volar extension, to have a button to restart Vue language server in the status bar?

For restarting TypeScript language server I simply click this icon in the status bar:

![image](https://github.com/vuejs/language-tools/assets/10191085/ae477852-f128-40e5-b7fc-05d13df39dbe)
</div>

**Comment by so1ve** [comment]
Recommended by Johnson: https://marketplace.visualstudio.com/items?itemName=YuTengjing.reload-can-solve-any-problems
