### ISSUE TITLE
volar.config.js in not read if not in root folder

### ISSUE THREAD

**Issue by grofzero** [vuejs/language-tools#3501]
hi,

We have a project with frontend and backend folder. Volar.config.js is in the frontend folder, but it has no effect when I open the whole project in VS Code. When I open the frontend folder only, it's working.
Is there a way to specify where volar.config.js is located?

thanks,
Kornel

**Comment by so1ve** [comment]
As a workaround: create a `volar.config.js` in your root folder and re-export the actual config.

**Comment by so1ve** [comment]
Ah, there is a `vue.server.configFilePath` config. @grofzero Could you try it?

**Comment by grofzero** [comment]
@so1ve Thank you, it's working🎉

**Comment by so1ve** [comment]
Let's close this issue :)
