### ISSUE TITLE
Volar high CPU utilization

### ISSUE THREAD

**Issue by RMFogarty** [vuejs/language-tools#3502]
As soon as Volar is enabled it immediately starts using very high CPU. This is not an issue unless I'm on my laptop and it will very quickly drain the battery. Regardless of what I'm doing if VS code is open it will pin the CPU and also high memory usage. Makes it extremely difficult to do Vue development while using a laptop.

<img width="956" alt="image" src="https://github.com/vuejs/language-tools/assets/10094132/546d9ee4-89d6-4d59-9970-e4086fcb43fb">

I've tried enabling volar.lowPowerMode although it either doesn't appear to be doing anything or I've not set it in the right place. 

Workspace VSCode settings:
`{
	"folders": [
		{
			"path": ".."
		}
	],
	"settings": {
		"volar.format.initialIndent": {

			"html": true
		},
		"volar.lowPowerMode": true,
	},
}`

Visual Studio
Version: 1.81.1 (Universal)
Electron: 22.3.18
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0

**Comment by rodrigocfd** [comment]
Does enabling Takeover Mode help?

* https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode

**Comment by RMFogarty** [comment]
Takeover mode did not help. I've also just disabled the Volar TS plugin and just using the regular one to ensure that was not causing the issue. Thanks

**Comment by boernard** [comment]
I'm experiencing the same issue on my M2

VSCode Version: 1.82.2 (Universal)
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

**Comment by VivianWang1993** [comment]
I have this problem too. Is there any solution?

**Comment by isuoge** [comment]
I have this problem too.

**Comment by WhiteSage** [comment]
I had to go back to Vetur, as the high CPU usage makes the Volar extension unusable on my laptop :(

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
