### ISSUE TITLE
volar code suggest list exception,

### ISSUE THREAD

**Issue by zogwosh** [vuejs/language-tools#3507]
I have to manually trigger suggest to display it properly, and I often need to trigger suggest multiple times to see the real suggest list.
before the trigger
![image](https://github.com/vuejs/language-tools/assets/128657331/a648f3ad-7c51-4a80-98db-7b07b62db702)
after the trigger
![image](https://github.com/vuejs/language-tools/assets/128657331/0fa6f918-30ea-467e-8be8-1472d241f6a3)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
