### ISSUE TITLE
Volar can't find the added files

### ISSUE THREAD

**Issue by zogwosh** [vuejs/language-tools#3508]
When I add a new vue file, volar has no way to find him.
![image](https://github.com/vuejs/language-tools/assets/128657331/91348ff7-09b1-4014-9b68-675fa8d32d01)
![image](https://github.com/vuejs/language-tools/assets/128657331/0edc02c6-ac98-41c1-b891-fba3786055fd)
![image](https://github.com/vuejs/language-tools/assets/128657331/a59c80bd-634d-4730-83e6-04ce433a7ef6)
I have to reload to find the added files.

**Comment by destroytoday** [comment]
+1 Whenever I add a new file, I need to manually restart Volar to get it to recognize the file.

**Comment by abcRede** [comment]
Same here in our end

**Comment by so1ve** [comment]
Are you using typescript-vue-plugin or takeover mode? Ref: #3555

**Comment by zogwosh** [comment]
@so1ve  Does takeover mode and typescript-vue-plugin affect the language server's support for vue files? In fact, I have encountered such issues with both takeover mode and typescript-vue-plugin.

**Comment by Little-Frog-233** [comment]
how to solve this problem?
