### ISSUE TITLE
Volar truncates typing errors to single line

### ISSUE THREAD

**Issue by jrsun** [vuejs/language-tools#3515]
For some reason, Vue Language Features (Volar) refuses to show details of any type errors. It will only show that types are incompatible, but it will not drilldown into the properties to say why.

![image](https://github.com/vuejs/language-tools/assets/3927424/2ee946b1-cbb0-4ca8-8513-9414e6ef32b8)

**File content (same in .vue and .ts files):**

    interface Bar {
      field: string;
    }
    interface Foo {
      field: string | undefined;
    }
    
    function processBar(f: Bar) {
      return f;
    }
    
    const foo: Foo = { field: 'foo' };
    processBar(foo);

**Expected behavior (.ts file)**

* Typechecking shows *why* `Foo` is unassignable to parameter of type `Bar`.

&#x200B;

    Argument of type 'Foo' is not assignable to parameter of type 'Bar'.
      Types of property 'field' are incompatible.
        Type 'string | undefined' is not assignable to type 'string'.
          Type 'undefined' is not assignable to type 'string'.

**Actual behavior (.vue file)**

* Typechecking only shows *that* the types are incompatible

&#x200B;

    Argument of type 'Foo' is not assignable to parameter of type 'Bar'.
      Types of property 'field' are incompatible.

I'm completely at a loss and I feel like I must be doing something dumb here.

**Comment by cdauth** [comment]
I am also running into this and it makes understanding errors very hard.

Notably, in non-takeover mode, VSCode shows the TypeScript errors properly for TypeScript files, but in takeover mode, they are cut off like in the reproduction example.

**Comment by KermanX** [comment]
This has been fixed in v2.
