### ISSUE TITLE
Extra space padding in html attributes when casting templates

### ISSUE THREAD

**Issue by athoma13** [vuejs/language-tools#3516]
Consider the following vue template:
```
<template>
   <my-component>
         <template #namedslot="i: Foo">
         </template>
    </my-component>

    <input v-model=" abc ">
</template>
<script setup lang="ts">
   import { ref } from 'vue';

   interface Foo {}
   const abc = ref('hello')
</script>
```
(where my-component is any component with a named slot)

The fact that I cast i to Foo and then format the document will introduce extra space around 'abc' below.
Remove the cast i.e. change from `#namedslot="i: Foo"` to `#namedslot="i"` and the extra space goes away.

**Comment by so1ve** [comment]
Closed by #3573
