### ISSUE TITLE
(neovim) the removed function in typescript file won't be deleted in suggestion until a new file is created

### ISSUE THREAD

**Issue by ogios** [vuejs/language-tools#3521]
# Process

https://github.com/vuejs/language-tools/assets/96933655/b51c4029-fefb-4cc3-b046-be6bf18d113e

in the video, i first add a function called `sussybot()` in `hubs.ts`, and the suggestion works in the `App.vue`.
then i delete it and get back to `App.vue`, the function's suggestion is still there, but with an error aside of it:
```
[TS Error] Error: Debug Failure. False expression: Should not run 'collectAutoImports' when faster path is available via `data`
```
then i create a new file called `new.ts` and add a function called `you()`
head back to `App.vue`, the `sussybot()` suggestion is gone

# Env
i'm currently using `NVIM v0.9.1` with `NvChad`.
lsp: volar takeover mode ( disabled `tsserver` ), and i've searched through https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/ , set everything available in `capabilities.workspace`'s `dynamicRegistration` to `true`.

but still, it raise this warning:
```
[WARN][2023-08-31 12:42:07] ...lsp/handlers.lua:137	"The language server volar triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

here's my nvim config file:
https://github.com/ogios/nvim-config-nvchad

**Comment by so1ve** [comment]
#1274?

**Comment by ogios** [comment]
I found another

> #1274?

@so1ve i don't think it's related to this error, i know there maybe some restricts especially set for `node_modules`.
but this happens in a normal workspace

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in 2.x. If not, feel free to create a new one.
