### ISSUE TITLE
(neovim) The exports added in an existing file or a file created under an existing directory can be detected. However, the exports of a newly created file under a newly created directory cannot.

### ISSUE THREAD

**Issue by ogios** [vuejs/language-tools#3522]
I don't know if the title explains well of what i means.
I felt strange about this.

# Process

https://github.com/vuejs/language-tools/assets/96933655/1afb27e2-dde5-4e5c-ae22-868e664f8f1c

i first create a new dir and a new file `api/ttst/ttst.ts`, and then export a function called `ccttst()`.
head back to `App.vue`, no suggestions provided.
then i create a new file under an existing dir `api/test.ts`, and export a funtion called `aattst()` .
now is the weird part, in `App.vue`, suggestions shows both of them and can auto import them as well

how can i fix this

#3521

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in 2.x. If not, feel free to create a new one.
