### ISSUE TITLE
[Performance]: Huge performance downgrade since 1.8.1

### ISSUE THREAD

**Issue by mattersj** [vuejs/language-tools#3531]
Just for context: I have a really large project with over 3000 components and more than 30 private npm packages with even more components.
Once I started working on this project I noticed that Volar is completely unusable and it takes like ~3-5 minutes to just get initialized in a **single** file, and when you switch to another file you have to wait the same amount of time to get any autocompletion or useful information on hover except "Loading...", so I temporarily switched to WebStorm because I thought that it's too much for Volar to handle.

Today I decided to play around with Volar's versions and see if there's a difference in how much time it takes to get initialized in a file, and yes, there's a **huge** difference between version 1.8.0 and everything above it: the first one takes like ~10-15 seconds for cold start and then around ~1-3 seconds for autocompletion/hovers in **any** file, but everything above 1.8.0 takes literally **no less than 3 minutes** and this is not just a cold start, this is the time it needs for **every single file**!

Demo: https://www.youtube.com/watch?v=nTug5j6oF0E

Since we know the exact version things went wrong I suppose that this information should be enough to measure performance between the two but if you need more information/logs - just let me know and I'm going to collect everything you need to debug this issue.

P.S.
 * I tried to disable all extension but nothing has changed.
 * In TS files everything works almost instantly.

```
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0
```

**Comment by so1ve** [comment]
Possible related commits: https://github.com/vuejs/language-tools/commit/289aceef28386f76c427ae500e8eb26d65001fce, https://github.com/vuejs/language-tools/commit/5d5fc89edd2897b5eb2a143524a1f04775cffda3

Nice report! 👍

**Comment by mwkcoding** [comment]
This has gotten even worse in v2

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in the latest 2.x. If not, feel free to create a new one.
