### ISSUE TITLE
strictTemplates fails to report unknown components

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/language-tools#3539]
I think `strictTemplates: true` used to report unknown components used in a template (or am I mistaken?).

Using vue-tsc v1.8.10, the following component does not report any errors, even if `<Hello>` does not exist.

```vue
<script setup lang="ts">
import { ref } from 'vue'

const msg = ref('Hello World!')
</script>

<template>
  <Hello :msg="msg"></Hello>
</template>
```

[Stackblitz](https://stackblitz.com/edit/github-v4xybq?file=src%2FApp.vue)

[Playground](https://play.vuejs.org/#eNp9UMFOwzAM/RWTS0GatsNuVYcEaBJwAASTuORStW7JSJMocUelqv+O07IC0rRLFL/3/PzsXtw4tzy0KFKRhcIrRxCQWgc6N/VGCgpSXEujGmc9QQ8eKxig8raBhNsSaaQprAkETahhE/nL5B61tvBuvS4vkitpstVkzUZcEDZO54RcAWSTNuVunsYvj8tWI8h8tprFYsFZeFKl6uU+WMOB+2ggRWEbpzT6Z0eKk0iRwshELmefr8cRI9/i4ogXH1h8nsD3oYuYFC8eA/oDSjFzlPsaaaK3b0/Y8X8mG1u2mtVnyFcMVrcx4yS7bU3Jsf/oxrQP46mVqXdh2xGacFwqBo3KYdRLwee/O7P6b9z1cj2PCORVQbufq/73lWYQwzdhyK8p)

**Comment by so1ve** [comment]
Does it work in v1.8.9?

**Comment by cexbrayat** [comment]
I don't know, I had to disable strictTemplates for a while because of https://github.com/vuejs/language-tools/pull/3487

But I tried quickly in the stackblitz repro, and it doesn't look like it worked in v1.8.9

**Comment by so1ve** [comment]
This problem is introduced in https://github.com/vuejs/language-tools/commit/376352ae816fcfa41ed82b52ccc6a649ad16ea79. It doesn't seemed to be related to #3487

**Comment by IceBlizz6** [comment]
@cexbrayat 
Just discovered this issue myself, seems like my team has been without strict template type support for months.
I narrowed down the version.

This was working in 1.8.3 and then it does not work in 1.8.4

**Comment by IceBlizz6** [comment]
@so1ve 
Do you know how to solve this?
or do you know if we can get someone to take a look at it?

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/pull/3717 wip
