### ISSUE TITLE
Alias '@/' not working

### ISSUE THREAD

**Issue by MeikelLP** [vuejs/language-tools#3543]
I looked at many many posts and issues and all do the same thing as me but I'm unable to get this working properly.

I'm using Webstorm `2023.2.1` with the Vue Language Server `1.8.8` (latest as of now)

This is what I get in my `./src/router/index.ts`

![image](https://github.com/vuejs/language-tools/assets/11669846/51cc8fc2-1850-4918-a079-2bc0595b79d4)

Both files obviously exist. But only the relative path can be resolved by the IDE, both work when using the app.
I'm using typescript.

`tsconfig.json`
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json"
}
```

`vite.config.js`
```js
import {defineConfig} from 'vite'
import {fileURLToPath} from 'node:url'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  ...
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
```

This started happening after switching everything to typescript. This was (and still) is the biggest reason why I never wanted to switch to typescript. (IDE) support is still very buggy/unstable to this date imo

**Comment by so1ve** [comment]
```json
{
	"extends": "@vue/tsconfig/tsconfig.dom.json",
	"compilerOptions": {
		"paths": {
			"@/*": ["src/*"],
		}
	}
}
```

**Comment by MeikelLP** [comment]
@so1ve as expected this does not work:
![image](https://github.com/vuejs/language-tools/assets/11669846/29bc77a3-609e-47b1-b070-71ebd48d3d42)

I tried
```json
"@/*": ["./src/*"]
```

```json
"@/*": ["src/*"]
```

Both times I restarted the Vue language server in WebStorm

**Comment by so1ve** [comment]
set `"rootDir": "."`?

**Comment by MeikelLP** [comment]
Still not working:

```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "rootDir": ".",
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"],
    }
  }
}
```

**Comment by so1ve** [comment]
I reopened this issue because it is still not resolved. But I don't think this issue is related to this repo. Could you please provide a minimal reproduction?

**Comment by MeikelLP** [comment]
I created the following repo: https://github.com/MeikelLP/vue-paths

I stripped out everything not necessary from the original project.

I get the same errors. I assume it's due to mixing JS + TS?

**Comment by so1ve** [comment]
Thanks for this reproduction 👍 I'll check it later

**Comment by yaegassy** [comment]
@MeikelLP Try adding `"allowJs": true` to `tsconfig.json`

```jsonc
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "compilerOptions": {
    "allowJs": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

**Comment by MeikelLP** [comment]
This works. Although the error message was not really helpful for me.

**Comment by so1ve** [comment]
Thanks @yaegassy!
