### ISSUE TITLE
Generic SFC component inside render function is missing type hint

### ISSUE THREAD

**Issue by marcianos** [vuejs/language-tools#3544]
I have created a SFC component `Test.vue`:
```vue
<template>
  <div>
    {{ animal }}
  </div>
</template>

<script setup lang="ts" generic="T extends Animal">
import { PropType } from "vue";

export interface Animal {
  name: string;
}
defineProps({
  animal: {
    type: Object as PropType<T>,
    required: true,
  },
});
</script>
```

In my other component I try to use: `h(Test, { })` but the type hint to use animal inside object is missing.

**Comment by marcianos** [comment]
Could also be related to [this issue](https://github.com/vuejs/language-tools/issues/3405#issuecomment-1710379877)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in the latest 2.x. If not, feel free to create a new one.
