### ISSUE TITLE
Clickable parameter hints doesn't work

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#3545]
I want to try the new ts editor feature: [Clickable parameter hints](https://code.visualstudio.com/updates/v1_82#_clickable-parameter-hints), but when takeover mode enable, this doesn;t work.

When I enable vscode builtin typescript extension(just not takeover mode), that works.

```
TypeScript:5.2.2
Volar: v1.8.10
Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:08:29.670Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by so1ve** [comment]
Please report to https://github.com/volarjs/services

**Comment by tjx666** [comment]
@so1ve @johnsoncodehk 貌似你们应该有权限可以 transfer issue

**Comment by so1ve** [comment]
我只有这个仓库的write access
