### ISSUE TITLE
Vue Language Features 最新版本无法使用@后的建议提示

### ISSUE THREAD

**Issue by mxm646690173** [vuejs/language-tools#3551]
Vue Language Features 最新版本无法使用@后的建议提示

 vsCode最新的1.82, TypeScript Vue Plugin (Volar),最新的1.8.10, 

当我把 Vue Language Features的版本降低至1.8.8 的时候, 使用 @*** , 可以正确的出现
![image](https://github.com/vuejs/language-tools/assets/57613270/d122259e-dd7b-4757-8a7e-456a53db7614)

使用最新的1.8.10 的时候, 没有上述的提示,其他基础环境不变

**Comment by so1ve** [comment]
I can't reproduce.

**Comment by mxm646690173** [comment]
非常抱歉,我漏掉了一个环境,我是使用nuxt3 创建的项目下,在nuxt3 创建的项目下,把Vue Language Features 更新至最新的1.8.10,会知道这个问题的出现, 通过vue cli 创建的项目并没有这个问题

**Comment by so1ve** [comment]
Install the dependencies and run dev script

**Comment by mxm646690173** [comment]
我该怎么做? 我直接npm i , 并且 npm run dev , 但是还是没有提示, 包括使用最新的8.11

**Comment by so1ve** [comment]
Please provide a minimal reproduction. https://antfu.me/posts/why-reproductions-are-required
