### ISSUE TITLE
Slot return value should restict type of components 

### ISSUE THREAD

**Issue by tobiasdiez** [vuejs/language-tools#3552]
According to https://github.com/vuejs/core/pull/7982#issuecomment-1493923997, the each slot definition can be a function whose return value should restrict what components can be put in that slot. By default, its `any` or `VNode[]` which is not restricting anything, but one should be able to specify a certain component.

For example, the `restrict` slot of a component defined with
```ts
defineSlots<{
    default(props: { foo: string; bar: number }): any,
    restict(props: { data: string }): typeof Button[]
  }>()
```
should only allow Buttons as children.

[Playground](https://play.vuejs.org/#eNqlVE2P0zAQ/Ssjc2iRoga0t2waCZY9wIFd0d7qHtJk0rokdmQ7ZVcl/52xnW4/VBYBkSLZM28879nP3rMPbTvZdcgSlppCi9aCQdu1UOdyPeXMGs4yLkXTKm1hDxqrCD5hJSTeKQpKlDaC8jIwq5U18+cWoYdKqwZG1GPEJZeFksbC3UbUJUwvC8cpzAGfLMrSgLFayDX8BNk1K9TZuNWqNQmRaMw6gfkt1MJYGiyW0L+Faebp2U5LGPvpyHcZUfLY+DHX1OdK5z2XQJ9xxBN4WG2xsJCbo5J0QIArzbvaHvlUSiUD3VtY5ToZKFPnBHL5HB0qNRoripPKMrf5odSjLXVSVdifNMSzxTLU91kUDofkXUoNukhrEBvHjvvFOaX7PoLX/tHofH6mnZb8Z/WH2r/T73SHyp4smMbBnzSkicWmrXOLNANIg3o/ptkhB2+GfuTj0CoC1FoRM2/qwCktxS6bbVRHhgxZI2SBQGEQBqQiG9S1+oFlGjvo0CQ+ZxCfUPg/OuFqJORxwr3jDBJncxov3i8Jd4UpQV+YDnuZxn6ZP5I9ybCILjtdkkqsJ1ujJL0I3vGcFWQgUaN+aK2gS8QZnVxYmDO/NV98zOoOB6dTzQaL71fiW/PkYpw90mag3iFnLzmb6zXakL6ffaV34CTZqLKrCf1K8hsaVXeOY4B97GRJtE9wnu1n/5bRJs3NvXtqzEGUI+qQvcdzRk+Wuzu/k36kezO58XVc9qz/Bfcbwwc=) which also shows that type interference/restriction for children is not working.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in the latest 2.x. If not, feel free to create a new one.
