### ISSUE TITLE
function with return value / undefined is not typed correctly

### ISSUE THREAD

**Issue by hi-reeve** [vuejs/language-tools#3553]
in the current version
when a function return undefined or value using ref is not correctly typed

<img width="939" alt="image" src="https://github.com/vuejs/language-tools/assets/45350572/fb23f904-dbf6-49af-8ffe-bfd1de5aa5bc">

**Comment by so1ve** [comment]
Report it to https://github.com/vuejs/core, though this is more likely caused by your wrong usage
