### ISSUE TITLE
[vue-component-meta] `getComponentMeta` gives empty data

### ISSUE THREAD

**Issue by lsdsjy** [vuejs/language-tools#3566]
The reproduction repo below is generated by create-vue. Then I try to get meta of `src/components/HelloWorld.vue`, and it returns empty data:
```
{ type: null, props: [], events: [], slots: [], exposed: [] }
```

## Reproduction:
https://github.com/lsdsjy/reprod-vue-component-meta-vue3

## Steps:
Run `pnpm install && npx tsx ./gen-component-meta.ts`

## Packages:
vue-component-meta@1.8.11
vue@3.3.4

**Comment by Dschungelabenteuer** [comment]
FWIW this appeared in `v1.810`
