### ISSUE TITLE
IntelliSense for Fallthrough Attributes 

### ISSUE THREAD

**Issue by Zercerium** [vuejs/language-tools#3568]
IntelliSense / Autocompletion for Fallthrough Attributes would be nice.

For example if you write a Wrapper `CustomSelect` around a LibraryComponent `Select` and the `Select` has the prop `label`.
If you type `<Select la ` the auto completion will show you `label` as a suggestion, also you can just get a list of all accepted props with IntelliSense

Now if you type `<CustomSelect la` nothing will show up and there is no IntelliSense

```vue
//File CustomSelect.vue
<template>
    <Select/>
</template>
```

**Comment by metkm** [comment]
This is probably what Vue lacks the most right now.
