### ISSUE TITLE
Why this close annotation is marked with red?

### ISSUE THREAD

**Issue by cnSchwarzer** [vuejs/language-tools#3570]
![image](https://github.com/vuejs/language-tools/assets/29846655/51d1f8ce-e734-4cd5-9ca0-593ea0cf56ca)

I use:
![image](https://github.com/vuejs/language-tools/assets/29846655/ef729fca-3be2-4e62-82d8-123a00326dbe)

**Comment by andraaspar** [comment]
Because `<span></span>` is [the correct way](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span) to close a span.
> **Tag omission:** None, both the starting and ending tag are mandatory.

**Comment by cnSchwarzer** [comment]
Thanks, first known

**Comment by cnSchwarzer** [comment]
However, jsx is not regulated by html spec anyway...
