### ISSUE TITLE
#region folding in VSCode

### ISSUE THREAD

**Issue by SufyanDahalan** [vuejs/language-tools#3571]
I noticed that when having the language set to vue in the bottom bar in VSCode the `#region`, `#endregion` do not fold and/or are not recognized. Setting the language to TSX would get it to work, but would make the syntax highlighting freak out.

Is this easy to fix/develop? 
I'll be happy to contribute if anyone can guide me on this feature.

**Comment by johnsoncodehk** [comment]
Works for me in latest version. If you still have this problem, please describe how to reproduce it.
