### ISSUE TITLE
 ERROR [vue-tsc] Found 0 errors. Watching for file changes.

### ISSUE THREAD

**Issue by imcm7** [vuejs/language-tools#3579]
Why is error if no errors found?

```
ERROR
[vue-tsc] Found 0 errors. Watching for file changes.
```

I use `vue-tsc`.

https://github.com/imcm7/nuxt-db

**Comment by so1ve** [comment]
Please provide a minimal reproduction

**Comment by imcm7** [comment]
@so1ve https://github.com/imcm7/nuxt-db

**Comment by Anoesj** [comment]
I agree that if there are 0 errors, the log could be a regular `console.log`, as Vite shows `console.error` with an "ERROR" label:
![image](https://github.com/user-attachments/assets/dec12c33-9d74-4393-88ae-55f6bc9287ab)

This is a `tsc` "issue" though, so I'll create a new issue upstream.

**Comment by GaborTorma** [comment]
Are there any solution for this issue? Why closed it?
