### ISSUE TITLE
[Feature request] Type narrowing for `$event`

### ISSUE THREAD

**Issue by innocenzi** [vuejs/language-tools#3582]
Currently `$event` is properly typed as an `Event`, and its `target` as an `EventTarget`. This is expected.

```html
<input
	type="text"
	@input="filter.apply(($event.target as HTMLInputElement).value)"
/>
```

However, I wonder if it would be possible for Volar to forcibly set `$event`'s type to `Event & { target: HTMLInputElement }` when used in an `input` element?

```html
<input
	type="text"
	@input="filter.apply($event.target.value)"
/>
```

**Comment by so1ve** [comment]
This should be fixed in vue core
