### ISSUE TITLE
[Feature] Support specify typescript sdk by settings

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#3583]
## Problem

For now, when toggle the typescript sdk, will not modify any settings in settings.json:

![image](https://github.com/vuejs/language-tools/assets/41773861/35deb24e-c80d-4829-9f7b-b83508ada81c)

## Expect

Add a new setting:

```json
{
    "vue.typescriptSdk": "node_modules/typescript/lib"
}
```

when the value is empty string, use the vscode builtin typescript.

## Versions

```
Volar: v1.8.13
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T06:00:27.244Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by so1ve** [comment]
FYI Volar 2.0 will no longer require takeover mode thus every typescript setting should be respected

**Comment by tjx666** [comment]
When will the 2.0 land?

**Comment by so1ve** [comment]
I don't know, but you can still use `typescript.tsdk`
