### ISSUE TITLE
use prettier-eslint

### ISSUE THREAD

**Issue by code-farmer-i** [vuejs/language-tools#3584]
I want to use prettier-eslint to format javaScript or typescript, currently this is how I do it, but it's not working

volarPlugins/prettier-eslint.js
```js
const prettierEslint = require('prettier-eslint');

module.exports = function () {
  return {
    format (document) {
      if (!['typescript', 'javascript'].includes(document.languageId)) return;

      const formattedText = prettierEslint(document.getText());

      if (formattedText === document.getText()) return [];

      return [
        {
          range: {
            start: document.positionAt(0),
            end: document.positionAt(document.getText().length)
          },
          newText: formattedText
        }
      ];
    }
  };
};
```

volar.config.js
```js
module.exports = {
  plugins: [require('./volarPlugins/prettier-eslint')]
};
```

**Comment by so1ve** [comment]
@code-farmer-i Please checkout: https://github.com/volarjs/services/blob/master/packages/prettyhtml/src/index.ts

**Comment by code-farmer-i** [comment]
Is prettier used as the default formatting tool?
https://github.com/volarjs/services/tree/master/packages/prettier

**Comment by so1ve** [comment]
No, the default formatter is `prettyhtml`

**Comment by code-farmer-i** [comment]
I mean the default formatting tool for the code in the script tag, not the code in the template tag

**Comment by code-farmer-i** [comment]
> No, the default formatter is `prettyhtml`

I mean the default formatting tool for the code in the script tag, not the code in the template tag

**Comment by so1ve** [comment]
It uses the formatter provided by typescript

**Comment by code-farmer-i** [comment]
> It uses the formatter provided by typescript

Got it, thank you very much for your answer
