### ISSUE TITLE
Language server does not work with Bun

### ISSUE THREAD

**Issue by usagi-flow** [vuejs/language-tools#3586]
On a machine with [Bun](https://bun.sh) and without Node/NPM installed, the language-server doesn't work.

My editor receives the following errors:
```
2023-09-23T17:16:09.740 helix_lsp::transport [ERROR] vuels <- InternalError: Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in node_modules/typescript/lib/
2023-09-23T17:16:09.740 helix_lsp [ERROR] failed to initialize language server: protocol error: InternalError: Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in node_modules/typescript/lib/
```

The `@vue/language-server` package is installed globally, as well as `@vue/typescript` (I also tried `typescript`).

According to the log, the editor sends the following request to the language server:
<details><summary>Details</summary>
<pre lang="json">
{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "capabilities": {
      "general": {
        "positionEncodings": [
          "utf-8",
          "utf-32",
          "utf-16"
        ]
      },
      "textDocument": {
        "codeAction": {
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": [
                "",
                "quickfix",
                "refactor",
                "refactor.extract",
                "refactor.inline",
                "refactor.rewrite",
                "source",
                "source.organizeImports"
              ]
            }
          }
        },
        "completion": {
          "completionItem": {
            "deprecatedSupport": true,
            "insertReplaceSupport": true,
            "resolveSupport": {
              "properties": [
                "documentation",
                "detail",
                "additionalTextEdits"
              ]
            },
            "snippetSupport": true,
            "tagSupport": {
              "valueSet": [
                1
              ]
            }
          },
          "completionItemKind": {}
        },
        "hover": {
          "contentFormat": [
            "markdown"
          ]
        },
        "inlayHint": {
          "dynamicRegistration": false
        },
        "publishDiagnostics": {
          "versionSupport": true
        },
        "rename": {
          "dynamicRegistration": false,
          "honorsChangeAnnotations": false,
          "prepareSupport": true
        },
        "signatureHelp": {
          "signatureInformation": {
            "activeParameterSupport": true,
            "documentationFormat": [
              "markdown"
            ],
            "parameterInformation": {
              "labelOffsetSupport": true
            }
          }
        }
      },
      "window": {
        "workDoneProgress": true
      },
      "workspace": {
        "applyEdit": true,
        "configuration": true,
        "didChangeConfiguration": {
          "dynamicRegistration": false
        },
        "executeCommand": {
          "dynamicRegistration": false
        },
        "inlayHint": {
          "refreshSupport": false
        },
        "symbol": {
          "dynamicRegistration": false
        },
        "workspaceEdit": {
          "documentChanges": true,
          "failureHandling": "abort",
          "normalizesLineEndings": false,
          "resourceOperations": [
            "create",
            "rename",
            "delete"
          ]
        },
        "workspaceFolders": true
      }
    },
    "clientInfo": {
      "name": "helix",
      "version": "23.05 (e44a0889)"
    },
    "initializationOptions": {
      "typescript": {
        "tsdk": "node_modules/typescript/lib/"
      }
    },
    "processId": 21764,
    "rootPath": "/home/user/Projects/xpc-client/flight-app",
    "rootUri": "file:///home/user/Projects/xpc-client/flight-app",
    "workspaceFolders": [
      {
        "name": "flight-app",
        "uri": "file:///home/user/Projects/xpc-client/flight-app"
      }
    ]
  },
  "id": 0
}
</pre>
</details>

**Comment by johnsoncodehk** [comment]
Please track for https://github.com/oven-sh/bun/issues/4511
