### ISSUE TITLE
[Question] Is there any solutions to wrap attributes only when wrap automatic?

### ISSUE THREAD

**Issue by s3xysteak** [vuejs/language-tools#3587]
now:
```
<ExampleComponent class="test" @click="handleClick" :data="data"/>
```

request to be:
```
<ExampleComponent class="test" @click="handleClick" :data="data"/>
```

_No need to wrap attributes when the code is not long enough to wrap automatic._

now:
```
<ExampleComponent class="test" @click="handleClick" :data="data" :data-source="dataSource" :loading="onLoading" :attr1="attr1" :attr2="attr2" />
```

request to be:
```
<ExampleComponent 
    class="test" 
    @click="handleClick"
    :data="data" 
   :data-source="dataSource"
    :loading="onLoading"
    :attr1="attr1"
    :attr2="attr2" 
   />
```

_Wrap attributes when the code is long enough to wrap automatic._

**Comment by meguoe** [comment]
配合prettier使用

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/issues/1078 Volar now uses `vscode-html-languageservice`, which doesn't automatically wrap these attributes. Please use prettier if you want to wrap them.

**Comment by s3xysteak** [comment]
> #1078 Volar now uses `vscode-html-languageservice`, which doesn't automatically wrap these attributes. Please use prettier if you want to wrap them.

Could I format code in `<template></template>` by Prettier, but still use Volar to formatter other code? I really love the style of Volar.
I tried it in VsCode. Here is my setting.json
```
  "[vue]": {
    "editor.defaultFormatter": "Vue.volar"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```
But it does not work. It seems to only work on the file with the .html suffix.
