### ISSUE TITLE
[Bug] The type definition of props is missing in the template.

### ISSUE THREAD

**Issue by zcf0508** [vuejs/language-tools#3592]
volar version : 1.8.14

```vue
<script setup>
const props = defineProps({
  msg: String
})
</script>

<template>
  {{ msg }}  <!-- msg is undefined -->
  {{ props.msg }}  <!-- this is ok -->
</template>
```

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

![image](https://github.com/vuejs/language-tools/assets/58381667/c8a9a0c1-b95d-47d6-892e-dc2ae85c2654)

**Comment by zcf0508** [comment]
Sorry. I forgot to add more information.

I use `vue 2.7.14` and `setup script` with `js`, but I set `checkJs` to `true` in `jsconfig.json`.

And I test `setup script` with `ts`, the type definitions are all right.

**Comment by zcf0508** [comment]
If I downgrade the version of volar to 1.8.13, everything will be normal.

**Comment by so1ve** [comment]
```vue
<script setup>
const props = defineProps({
  msg: String
})
</script>

<template>
  {{ msg }}  <!-- msg is undefined -->
  {{ props.msg }}  <!-- this is ok -->
</template>
```

You mean this?

**Comment by zcf0508** [comment]
Yes! And I use vue2.
