### ISSUE TITLE
defineEmit now cannot infer event types at tsx

### ISSUE THREAD

**Issue by tetezi** [vuejs/language-tools#3594]
version    **1.8.14**

defineEmit now  cannot  infer event types at tsx
![1695714396861](https://github.com/vuejs/language-tools/assets/76197961/debb439d-a5ce-48b2-a118-dbccc547c739)

previous version   **1.8.13**
![1695714537045](https://github.com/vuejs/language-tools/assets/76197961/f773ecaa-a11d-41e9-bb56-2c23b2561c3b)

**Comment by so1ve** [comment]
I can't reproduce this, could you please provide a minimal reproduction?

**Comment by tetezi** [comment]
like this？ I'm  a newbie，I'm not sure that's what you need。
[stackblitz](https://stackblitz.com/edit/github-mszkwn?file=src%2Fcomponents%2Findex.tsx)

**Comment by so1ve** [comment]
@tetezi Yes a stackblitz demo works, thanks

**Comment by so1ve** [comment]
![image](https://github.com/vuejs/language-tools/assets/58381667/80f0365b-8fbd-4ac6-b34d-fbaf3d0e1294)

I still cannot reproduce this problem :(

**Comment by tetezi** [comment]
I don't know... Even if just  create a  new vue project in the 1.8.14. it's  breakdown too. But when I roll back the version to  1.8.13 it will work fine.... 
(。・＿・。)ﾉI’m sorry~ Do I need to close the issue ?

**Comment by cooper667** [comment]
I have a similar issue, will create a reproduction

**Comment by so1ve** [comment]
Thanks @cooper667, a reproduction can help us debug.

**Comment by cooper667** [comment]
My issue was https://github.com/vuejs/language-tools/issues/3615 rather than this!

**Comment by davidmatter** [comment]
Closing this one due to inactivity. If this is still an issue in version 2.x, feel free to create a new issue, thanks!
