### ISSUE TITLE
VSCode: Bad / Better intellisense

### ISSUE THREAD

**Issue by Kcko** [vuejs/language-tools#3597]
Hi.

I'm having a bit of a problem with bad hinting in Vue.js files. 

For example, I write a property, and I want it to hint a list of all available datatypes (I know roughly which ones they are, but it doesn't hint anything, or shows a nonsensical list)

Video: http://remotefiles.rjwebdesign.cz/f/20230926-161339.mp4

Does it not do that or is something wrong with me?

It's related, but all hints, I have to help him a lot and write almost all of it for him (he could do this and detect it no?

**Comment by so1ve** [comment]
Do you mean: only provide valid vue datatypes, such as `String`, `Boolean`?

**Comment by so1ve** [comment]
Because technically we can pass any value to it, but vue will warn in your runtime code.

**Comment by Kcko** [comment]
ok thx
