### ISSUE TITLE
Required prop hint appears for a native HTML `<button>`

### ISSUE THREAD

**Issue by DamianGlowala** [vuejs/language-tools#3606]
(Reproduction steps apply to Nuxt 3 with auto imports enabled.)

1. Create a component `Button.vue`
2. Paste the following content:
```
<template>
    <button type="button">

    </button>
</template>

<script setup lang="ts">
defineProps<{
    ripple: boolean;
}>();
</script>
```
3. Observe how the `ripple!` hint appears for a native HTML button:
![image](https://github.com/vuejs/language-tools/assets/48835293/2ec097ce-b4a4-45de-ac6b-24132ef39cac)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
