### ISSUE TITLE
Intellisense isn't working properly in monorepo setup

### ISSUE THREAD

**Issue by remvn** [vuejs/language-tools#3609]
**Reproduction:** [repo](https://github.com/remvn/nuxt-intellisense-issue)
**Volar version:** v1.8.15

This problem also appears in a yarn monorepo setup. I have already tried uninstalling all extensions (except 2 volar extensions).

### When open as a whole monorepo in vscode:
![image](https://github.com/vuejs/language-tools/assets/34063162/e4b51ce5-c235-4879-a9bc-e7a7c1979246)
![image](https://github.com/vuejs/language-tools/assets/34063162/5463abaa-ab0f-4f5a-bb6f-57c97281f8fc)

### When open as a single repo in vscode: (right-click nested folder in ./packages, `Open with vscode`)
![image](https://github.com/vuejs/language-tools/assets/34063162/3e97d39b-c795-4228-b765-eff5504777e4)
![image](https://github.com/vuejs/language-tools/assets/34063162/793ce336-e185-4864-8cd5-281a55474ca7)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
