### ISSUE TITLE
Generic components throwing errors since v1.8.14

### ISSUE THREAD

**Issue by filipbekic01** [vuejs/language-tools#3615]
Generic components started throwing errors once we update from 1.8.13 to 1.8.14 verison.

The problem is, emit type is not inherited from props generic type. In next example, emit is supposed to be `string` type but turns to be `any` now:

<img width="660" alt="image" src="https://github.com/vuejs/language-tools/assets/16108768/7ca982cc-e2c0-4faf-9c1d-535cd6bfbd8c">

...

<img width="519" alt="image" src="https://github.com/vuejs/language-tools/assets/16108768/4b598552-12a1-479e-8f0a-35160a837478">

...

<img width="669" alt="image" src="https://github.com/vuejs/language-tools/assets/16108768/4069ed0f-2043-468b-b7f2-59cb3fc63207">

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by filipbekic01** [comment]
https://github.com/filipbekic01/vue-issue-3615

**Comment by filipbekic01** [comment]
Running `npm run type-check` will log the error

**Comment by filipbekic01** [comment]
https://github.com/filipbekic01/vue-issue-3615

- npm i
- npm run type-check

**Comment by filipbekic01** [comment]
I guess we can update `need info` tag to something else, like bug if you like? It's really stopping us from moving from 1.8.13 version since our build pipelines are failing.

**Comment by so1ve** [comment]
@filipbekic01 Hi, first of all thanks for this report. However, the author of Vue Language Tools, Johnson, is busy with some other priority projects, and my laptop is still being repaired and no other contributors are willing to fix this issue, so we haven't actually checked where this issue came from or checked your repro yet (sorry!). So we haven't changed this label yet. Once someone has viewed your reproduction, the tag will be removed.

**Comment by filipbekic01** [comment]
No need to sorry at all, I completely understand your position. Just wanted to make sure the issues tab is not turning into graveyard 😄 Thanks for quick reply.

**Comment by so1ve** [comment]
![image](https://github.com/vuejs/language-tools/assets/58381667/184136f9-9100-4dd8-9205-6fe596d1d528)

I can't reproduce you problem, which version of volar are you using?
