### ISSUE TITLE
Property checking of dynamically imported component

### ISSUE THREAD

**Issue by frankykubo** [vuejs/language-tools#3616]
I want to dynamically initialize federated component with `defineAsyncComponent` method and provide prop typings.

```
<script setup lang="ts">
    interface Props {
        testProp: string,
    }

    const ComponentTest1: DefineComponent<Props> = defineAsyncComponent(() => import('remote_app/Button'));
    let ComponentTest2: DefineComponent<Props>;
    const Bar = defineAsyncComponent<DefineComponent<Props>>(
        () => import('remote_app/Button') as any,
    );
</script>

<template>
    <ComponentTest1 />
    <ComponentTest2 />
</template>
```

What happens is quite interesting. Both components register that a prop is missing:
![image](https://github.com/vuejs/language-tools/assets/50501921/a4c00b35-bfb9-4858-9bde-1dc743670c53)

When I start writing the attribute, I have intellisense only for the `ComponentTest2` component:
![image](https://github.com/vuejs/language-tools/assets/50501921/00ebe929-d607-49ee-8135-28b95b720997)

For `ComponentTest1`, there is no type-checking happening. 
![image](https://github.com/vuejs/language-tools/assets/50501921/5a4fe6ba-9bbd-4d2f-8678-3ff1972ed54b)

Why is that? Is this fixable?

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by frankykubo** [comment]
Same scenario happens even when I am importing a local .vue component:

```
const Navbar = defineAsyncComponent(() =>
  import('@/components/includes/Navbar.vue'),
);
```

Inside **Navbar.vue**, I have props defined like this (just for an example):

```
withDefaults(defineProps<{bookOptions?: string[]}>(), {
  bookOptions: undefined,
});
```

Interesting is that it looks like typescript **within script setup** can see the props (see image, I got some sort of intellisense):

![image](https://github.com/vuejs/language-tools/assets/50501921/0695d20d-eb51-4e9d-8e95-e1609ace5b6f)

But in template, it remains the same, no intellisense provided.
