### ISSUE TITLE
Auto-import suggestions are not provided for package.json "exports" wildcard paths

### ISSUE THREAD

**Issue by delaneyb** [vuejs/language-tools#3618]
Repro: [repro.zip](https://github.com/vuejs/language-tools/files/12800719/repro.zip)

https://github.com/vuejs/language-tools/assets/18545667/a5a772a2-e4a3-491c-8ab2-eca4ead0d1c0

With https://github.com/microsoft/TypeScript/pull/55815, we see auto-import suggestions for files matched through wildcard paths in "exports" of dependencies' package.json files.

Upon disabling built in typescript server and enabling Volar however so it runs in takeover mode, these import suggestions seem to disappear, regardless of what TypeScript version is in use.

My suspicion is Volar internally is using some slightly different tsconfig settings to those in my tsconfig.json to produce intellisense results. For example, it seems you need to use a tsconfig.json compilerOptions setting such as module: "nodenext" or "node16" in order for package.json "exports" to be parsed and used for auto-import suggestions under standard built in typescript language server.

**Comment by KermanX** [comment]
Closing this issue because it is likely to have been fixed in v2. Feel free to re-open this issue if the problem still happens
