### ISSUE TITLE
Volar: custom components not properly recognised or highlighted in non-TS files

### ISSUE THREAD

**Issue by mgiraldo** [vuejs/language-tools#3620]
see #3299 

For Typescript-enabled projects when a component does not use `setup` the code coloring of custom components is not displayed (they show up as regular HTML tags). I created an [example repository](https://github.com/mgiraldo/vue-color-issue) where I just created a new project with `npm create vue@latest` and these options:

```✔ Add TypeScript? … Yes
✔ Add JSX Support? … No
✔ Add Vue Router for Single Page Application development? … No
✔ Add Pinia for state management? … No
✔ Add Vitest for Unit Testing? … No
✔ Add an End-to-End Testing Solution? › No
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … No
```

<img width="492" alt="image" src="https://github.com/vuejs/language-tools/assets/133020/5e40ae15-0da9-4941-9367-036013f76079">

Then I did a minor change to `.eslintrc.cjs` to use `kebab-case` in `vue/component-name-in-template-casing` and also in `src/components/App.vue` so that it does not use `setup`:

```html
<script>
import HelloWorld from './components/HelloWorld.vue'
import TheWelcome from './components/TheWelcome.vue'

export default {
  components: {HelloWorld, TheWelcome}
}
</script>
```

I would expect code coloring to be the same in both situations.

This is the result before the change:
<img width="824" alt="image" src="https://github.com/vuejs/language-tools/assets/133020/d78e5fd5-1e3f-4ba5-b190-1ee0f255c6bb">

This is after the change:
<img width="824" alt="image" src="https://github.com/vuejs/language-tools/assets/133020/de638eec-6f43-411b-b2f5-6ff6d35be35b">

**Comment by so1ve** [comment]
Should be fixed by #3600
