### ISSUE TITLE
When using the style attribute alone in JSX, there is an issue with HTML tag parsing

### ISSUE THREAD

**Issue by wufeiwua** [vuejs/language-tools#3627]
The highlighting does not work, and it looks like the end tag has not been correctly recognized. However, everything is normal after removing the `style` or adding a `class` attribute in front, even if it is empty.
![image](https://github.com/vuejs/language-tools/assets/36214311/b47b4e73-9406-432d-b330-1dde36e2582e)

**Comment by so1ve** [comment]
@eric-2d I remember that neovim seems to provide code highlighting through tree-sitter?

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
