### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Tiddler-Shuishui** [vuejs/language-tools#3635]
![Snipaste_2023-10-07_16-43-16](https://github.com/vuejs/language-tools/assets/44565876/d0d36bd8-5eb9-481d-8b76-4ff85d5b1da3)

**Comment by XBIsland** [comment]
It may be a problem with the project typescript version.
Temporarily downgrading the version to 1.18.5 can solve the problem
![image](https://github.com/vuejs/language-tools/assets/36447895/22a6ffc9-68c8-4cff-ac06-23747c34a1c0)

**Comment by MiiZZo** [comment]
I faced the same problem, volar 1.8.16 is completely not working in my project. 1.8.15 version works fine.

**Comment by SadBoxx** [comment]
Volar 1.8.16 cannot perform formatting code operations on my vscode

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

If yes, please paste your VSCode info by executing the `Help: About` command in VSCode and click "Copy".
If no, please provide a repro case so that we can investigate.

**Comment by MiiZZo** [comment]
@johnsoncodehk ,
1) I have two plugins for version 1.8.16:
![image](https://github.com/vuejs/language-tools/assets/58049702/6751d056-943e-475f-9acb-49cc8ab558eb)

2) I have takeover mode: 
![image](https://github.com/vuejs/language-tools/assets/58049702/438cf9dd-28f9-473b-af89-a74349f72290)

3) When i open app.vue from your volar-starter. Volar doesn't reconize HelloWorld as a component (It must be green.)
![image](https://github.com/vuejs/language-tools/assets/58049702/5de437d5-4ea2-4535-9f9c-f8d275e54cea)

4) Also there are no volar settings in vscode bottom bar (like camelCase or kebab-case for component and props)
![image](https://github.com/vuejs/language-tools/assets/58049702/1f5c6864-338a-4e43-b1fe-cdc7342ad81e)

5) When i try to run any volar command like restart vue server i got this error:
![image](https://github.com/vuejs/language-tools/assets/58049702/bcf3de62-ec19-4969-871d-10e9f8fd3443)

6) My vscode info:
Version: 1.80.2 (user setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

7) Volar 1.8.15 works well in this project.

**Comment by JerryChan31** [comment]
I met this as well, and "runtime status" tab says `Uncaught Errors (1): The language client requires VS Code version ^1.82.0 but received version 1.79.0`.

downgrading volar to 1.8.15 fixes the problem, and I'm trying to upgrade vscode to 1.82.0 to see if it's work.

**Comment by JerryChan31** [comment]
> I met this as well, and "runtime status" tab says `Uncaught Errors (1): The language client requires VS Code version ^1.82.0 but received version 1.79.0`.
> 
> downgrading volar to 1.8.15 fixes the problem, and I'm trying to upgrade vscode to 1.82.0 to see if it's work.

Upgraded to VSCode 1.83.0 and volar 1.8.16 still doesn't work.
