### ISSUE TITLE
defineExpose type check bug

### ISSUE THREAD

**Issue by Tarrowren** [vuejs/language-tools#3637]
vue-tsc@1.8.16
![image](https://github.com/vuejs/language-tools/assets/35626141/19dff482-a8ae-4104-9552-6fa3e00bb6c9)

**Comment by so1ve** [comment]
This is not a language-tools issue, please report to https://github.com/vuejs/core.

**Comment by johnsoncodehk** [comment]
This appears to be a regression introduced by https://github.com/vuejs/language-tools/commit/c7b95892971cdc0d54f7945162198f5f89a6b74f.
