### ISSUE TITLE
`<component />` custom event parameter type inference error

### ISSUE THREAD

**Issue by DimplesY** [vuejs/language-tools#3640]
When binding custom events to the ` <component /> ` component, the type inference results in `unknown[]`, while Vue's built-in events are inferred as `any[]`.

![VaOnjSE440](https://github.com/vuejs/language-tools/assets/51285767/ff9ed95d-cade-4e78-9f02-b726cccc5eff)

![img_v2_e409b8b2-d227-49b6-a504-4832f88f8f5g](https://github.com/vuejs/language-tools/assets/51285767/8b795790-c932-4caa-84b7-d33a7dc366a4)

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by DimplesY** [comment]
> Could you please provide a minimal reproduction?

I am unable to replicate the issue as you described in a new project.
