### ISSUE TITLE
Renaming a file does not update imports

### ISSUE THREAD

**Issue by andraaspar** [vuejs/language-tools#3646]
**Repo:** https://github.com/andraaspar/vue-lang-tools-rename-issue

VS Code 1.83.0

The only extensions installed are:

1. TypeScript Vue Plugin (Volar) v1.8.18
2. Vue Language Features (Volar) v1.8.18

I have created a new project using `yarn create vue` and answered `Yes` only to `TypeScript`.

I have the following 3 files:

`renameMe.ts`
```ts
export function renameMe() {
  return 'Hello World!'
}
```

`ThenCheckMe.vue`
```vue
<script setup lang="ts">
import { renameMe } from './renameMe';
</script>

<template>
  {{renameMe()}}
</template>
```

`thenCheckMeToo.ts`
```ts
import { renameMe } from './renameMe';

export function thenCheckMeToo() {
  return renameMe()
}
```

I right click `renameMe.ts` and select `Rename...`, and make it `renameMe2.ts`.

## If TypeScript and JavaScript Language Features is enabled

`ThenCheckMe.vue` becomes:
```vue
<script setup lang="ts">
import { renameMe } from './renameMe';

</script>

<template>
  {{renameMe()}}
</template>./renameMe2
```
**❌ Note the import did not change, but the new file name was appended to the final line.**

`thenCheckMeToo.ts` becomes:
```ts
import { renameMe } from './renameMe2';

export function thenCheckMeToo() {
  return renameMe()
}
```
**✅ This is correct.**

## If TypeScript and JavaScript Language Features is disabled (takeover mode)

`ThenCheckMe.vue` becomes:
```vue
<script setup lang="ts">
import { renameMe } from './renameMe';

</script>

<template>
  {{renameMe()}}
</template>
```
**❌ Note the import did not change.**

`thenCheckMeToo.ts` becomes:
```ts
import { renameMe } from './renameMe';

export function thenCheckMeToo() {
  return renameMe()
}
```
**❌ Note the import did not change.**

**Comment by mor-o** [comment]
Still an issue

**Comment by johnsoncodehk** [comment]
For the first case fixed by https://github.com/volarjs/volar.js/commit/d4fbbd7d9cbbbdd8b12981b7ce05da85b2e24c3e.

The second case may be due to your `vue.updateImportsOnFileMove.enabled` setting not being enabled, which will be enabled by default in the next version.

Thanks for the report!
