### ISSUE TITLE
VSCode: wrong code highlighting in code diff view (.vue files)

### ISSUE THREAD

**Issue by AlexMarlow25** [vuejs/language-tools#3652]
Hi! If you open some vue file in source control to see code changes, you'll always see broken code highlighting on the left side (before editing). On the right side everything is fine.
I've found some issue in VSCode repo, maybe it will helps (https://github.com/microsoft/vscode/issues/162313#issuecomment-1289565096)

<img width="658" alt="image" src="https://github.com/vuejs/language-tools/assets/22071237/8d2170ce-222b-4433-9a67-f877147c9988">
<img width="738" alt="image" src="https://github.com/vuejs/language-tools/assets/22071237/d11e5bd2-aab5-4533-a6a1-068e702847b7">

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
