### ISSUE TITLE
Extension doesn't recognize import is used in template when pug is used. 

### ISSUE THREAD

**Issue by jjtippetts** [vuejs/language-tools#3659]
VsCode Extension does not recognize that imports are used in the template when Pug is used. This only happens when Pug is used. 

![image](https://github.com/vuejs/language-tools/assets/45724546/01fbab8f-31ed-48d3-8934-9595692aed19)

**Comment by jjtippetts** [comment]
Figured out that you need to install @vue/language-plugin-pug plugin and add it to your jsconfig.json file. 
{
 	"vueCompilerOptions": {
 		"plugins": ["@vue/language-plugin-pug"]
 	}
 }

**Comment by JayPuff** [comment]
Seems like this work around doesn't work for newly released v2.0 of language tools at the moment
