### ISSUE TITLE
 In Volar TakeOver mode, updateImportsOnFileMove not works.

### ISSUE THREAD

**Issue by runminlook** [vuejs/language-tools#3663]
settings.json
```json
  "typescript.updateImportsOnFileMove.enabled": "always",
  "javascript.updateImportsOnFileMove.enabled": "always",
```

In Volar TakeOver mode, updateImportsOnFileMove not works.

**Comment by so1ve** [comment]
Take over doesn't read these setting, so this is working as intended. Please wait for volar 2.0 which no longer requires take over mode.

**Comment by so1ve** [comment]
Duplicate of #2490
