### ISSUE TITLE
defineEmits 不支持 generic 泛型吗（Does defineEmits not support generic generics?）

### ISSUE THREAD

**Issue by WangJincheng4869** [vuejs/language-tools#3675]
我尝试以下写法（I try the following writing:）：
```vue
<script setup lang="ts" generic="T">
defineOptions({
  name: 'SpPaginationTable',
});
const props = withDefaults(defineProps<{
  /**
   * 表格数据
   */
    data?: T[];
    showSummary: boolean
}>(), {
  showSummary: false
});

defineEmits<{
  /**
   * 当选择项发生变化时会触发该事件
   */
  selectionChange: [selection: T[]];
}>();

const tableData = ref<TicketDTO[]>([]);
</script>
```
使用这个组件：（Using this component:）
```vue
<sp-pagination-table
    :form-model="searchForm"
    v-model:current-page="searchForm.pageNum"
    v-model:page-size="searchForm.pageSize"
    :total="total"
    :loading="loading"
    :data="tableData"
    @query="doSearch"
    @selectionChange="tableSelectChange"
  >
</sp-pagination-table>
```

会有以下报错信息（The following error message will be displayed）：
![image](https://github.com/vuejs/core/assets/41162158/28b43ae7-42e2-455c-b15d-28a5699e5204)

![image](https://github.com/vuejs/language-tools/assets/41162158/48cf0423-8b04-49d9-bd6c-40cec388d2f7)

```
"vue-tsc": "^1.8.19"
"vue": "^3.3.4",
```

**Comment by so1ve** [comment]
What is `sp-pagination-table`?

**Comment by WangJincheng4869** [comment]
> What is `sp-pagination-table`?

是我自己写的组件，里面有类似以下代码片段（I wrote the component myself, which contains code snippets similar to the following）

```ts
<script setup lang="ts" generic="T">
const props = withDefaults(defineProps<{
     /**
     * 表格数据
     */
     data?: T[];
    showSummary: boolean
}>(), {
  showSummary: false
});

defineEmits<{
  /**
   * 当选择项发生变化时会触发该事件
   */
  selectionChange: [selection: T[]];
}>();

const tableData = ref<TicketDTO[]>([]);
</script>
```

**Comment by so1ve** [comment]
```diff
const props = withDefaults(defineProps<{
  /**
   * 表格数据
   */
    data?: T[];
-   showSummary: boolean
+   showSummary?: boolean
}>(), {
  showSummary: false
});
```

**Comment by so1ve** [comment]
Please provide your full usage including `script` block.

**Comment by WangJincheng4869** [comment]
> ```diff
> const props = withDefaults(defineProps<{
>   /**
>    * 表格数据
>    */
>     data?: T[];
> -   showSummary: boolean
> +   showSummary?: boolean
> }>(), {
>   showSummary: false
> });
> ```
请问这个样式是如何做到的？（May I ask how this style is made?）
![image](https://github.com/vuejs/language-tools/assets/41162158/bd070452-ea63-41d6-a570-b72eb4d5f9ed)

**Comment by so1ve** [comment]
```markdown
\`\`\`
+ xxx
- xxx
\`\`\`
```
