### ISSUE TITLE
Error when casting slot's binded object

### ISSUE THREAD

**Issue by galimovkirill** [vuejs/language-tools#3681]
<img width="831" alt="image" src="https://github.com/vuejs/language-tools/assets/55671052/7633f149-1d38-4505-a36c-28f5e9d686fe">

https://play.vuejs.org/#eNqdU01PIzEM/Sve7GEunfbArVuQ9qOH5QAIuBEkwoxpA5kkSjylqJr/jpPplFYChLjF9rPz8vyyEb+9H69aFFMxi1XQniAitf5EWt14Fwj+usbDQ3ANFONJChK8+CXtbNI3MJQDwsYbRcgRwCzh8onPQwV+Eq7pWIoN1IoUdFKcwOxHWcI8Vsoj3Cn7cgdLDAhlue0G+JewOk5hM/R128GTwzszuUyGgzT2ayxARejPU4gUtF3c3GZu3yTQc9+riZGgWDn7oBfjx+gsS71JeCkqxmuD4dyTdjZKwXf0o6VQxrjn05yj0OJoyFdLrJ7eyT/GdcpJcREwYlihFLsaqbBA6svzqzN+/16xcXVrGP1J8RKjM23i2MP+tLZm2nu4zPZ/NgwLeB3na0Ibh0clognZZbwUbKAk1UdPf6N7ND7KfdJ2rOJgvuTVA+VZ+1qvdgvjMBpHYFWDvOi0bylgVd5rWx/ajy3MwGHGpB9ysFYOt9/CKLtI05jr7ovwViP1447hplgiy1CMoHh2wdTFbbIWe3rvq4juFQLVHIM=

**Comment by so1ve** [comment]
https://play.vuejs.org/#eNqdU01PIzEM/Sve7GEunfbArVtW2o8e4AAIuBEkwoxpA5kkSjylqJr/jpPplFYChLjF9rP9/GJvxB/vx6sWxVTMYhW0J4hIrQej7OJYCopS/JZWN94Fgn+u8fAQXAPFeJKMlFr8knY26ZMZygZh440iZAtglnD5xe8hAj8J18T1N1ArUtBxF5j9KEuYx0p5hDtlX+5giQGhLLfZAP8TVscpbIa8blt4ctgzk8tkvkqAa+bXFCIFbRc3t5nUNztDkmQXECPWsXL2QS/Gj9FZFnuTwFJUDNYGw7kn7SxrzQ36ulIoY9zzafZRaHE0+KslVk/v+B/jOvmkuAgYMaxQil2MVFgg9eH51RmPvhdsXN0aRn8SvMToTJs49rC/ra2Z9h4usz3Ja8LqXcf5mtDGYahENCG7jJeC1ybp9NHob3SPxkc5T9qOVRxWLm3rgewsfK1Xu99iMxpHYFWDaYnzSLAq77WtD5eOF5eBQ41JX+TgT9ncHsbeSfRHwlH+1Uh9uWO4KZbIMhQjKJ5dMHVxCyoCb/LegYjuFeaRHjw=
