### ISSUE TITLE
Why volar add a `import type`?

### ISSUE THREAD

**Issue by fkworld** [vuejs/language-tools#3684]
**Versions**
- vscode 1.83.1
- vscode plugin: Vue Language Features (Volar) 1.8.19
- vscode plugin: TypeScript Vue Plugin (Volar) 1.8.19

**Reproduction**
Takeover mode. In create-vue cli project.

1. Add aaa-bbb-ccc.vue file
```vue
<template>
  <div></div>
</template>
```

2. Write `aaa` codes in App.vue file, vscode will show import suggestions
![image](https://github.com/vuejs/language-tools/assets/11092123/9d402625-7615-409d-94c9-26f63662e3e3)

3. Press `Enter`, vscode will add a line `import type`
![image](https://github.com/vuejs/language-tools/assets/11092123/60558da0-9e61-46c9-b73c-f6d64f89fc30)

4. Press `Command + Z`, will undo `import type` line

6. Delete the letter `a`, and rewrite the letter `a`, vscode will show import suggestions again

7. Press `Enter`, vscode will add a line, but just `import`
![image](https://github.com/vuejs/language-tools/assets/11092123/5b25848d-743a-426c-8dc2-18cda45ad52b)

**Screen record**

![Untitled](https://github.com/vuejs/language-tools/assets/11092123/30b5bcd0-ac0e-4f27-b0d3-4c2965ec20b0)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
