### ISSUE TITLE
vscode extension overrides syntax highlighting in code block

### ISSUE THREAD

**Issue by Yokozuna59** [vuejs/language-tools#3694]
Hi there,

I'm currently working on a VSCode extension that supports syntax highlighting, but the [Vue Language Features (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.volar) extension overrides the highlighting in the markdown code block.

When the extension is disabled/uninstalled:

![image](https://github.com/vuejs/language-tools/assets/87622592/2ef3df97-1b2d-4385-a03a-7d17226ee231)

When the extension is enabled with inspect:
![image](https://github.com/vuejs/language-tools/assets/87622592/416c3848-1e5b-4d86-be14-ccacf1314837)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
