### ISSUE TITLE
SCSS variable autocomplete gets two `$` prefix instead of one

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/language-tools#3695]
In a SCSS file, if I autocomplete a variable name, then change the variable, autocomplete work correctly.
![2023-10-30 11 24 08](https://github.com/vuejs/language-tools/assets/17392251/9b27cba3-95b2-49df-8dea-f7fff50509cd)

In a Vue file, if I autocomplete a variable name, then change the variable, the autocomplete will add the `$` prefix even if it's already present leading to a double `$$` before the variable name.
![2023-10-30 11 21 42](https://github.com/vuejs/language-tools/assets/17392251/4674537b-aa90-48d9-8b78-14466204582f)

**Comment by mrleblanc101** [comment]
This seems to be a conflict betweent `SCSS IntelliSense` (vscode-scss) and Volar.
Let me know if I should open this in vscode-scss repo instead.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
