### ISSUE TITLE
Effect on markdown autocompletion

### ISSUE THREAD

**Issue by SummCoder** [vuejs/language-tools#3699]
After I enable the plugin-Vue Language Features (Volar), I find that when I write a ***.md** file, normally I type the `ˋ` symbol, which will help me automatically complete a `ˋ` , but not now.The same problem also occurs when I type **```**.

**Comment by KermanX** [comment]
This is intended IMO. See https://github.com/vuejs/language-tools/blob/3e6e45c1d53dbd5f19d18233475d7249e4630205/extensions/vscode/languages/markdown-language-configuration.json#L32-L41
