### ISSUE TITLE
Vue Language Features 存在@后面的提示bug

### ISSUE THREAD

**Issue by mxm646690173** [vuejs/language-tools#3701]
当打开vue3 项目文件夹不是位于工作区的第一位的时候, 会出现 @后的建议提示 不出现的bug, 把当前无法提示的项目文件夹,调整至当前工作区的第一位的时候, 神奇的事情就发生了, @后面的建议提示 又自己出现了,经过测试,发现是由于每个项目下面都存在不同的tsconfig.json 文件导致的, 当我把tsconfig.json 删除后 , 不管他在工作区的什么位置, 都能正常提示

volar 的版本为1.8.22

由于我存放了多个vue项目, 当中有 nuxt 项目,  会用到不同的tsconfig.json ,并且不能删除相应的 tsconfig.json 所以请问这个问题我该如何解决

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/issues/3551#issuecomment-1716924398

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
