### ISSUE TITLE
Conflict between props and component model

### ISSUE THREAD

**Issue by jods4** [vuejs/language-tools#3703]
Assume that your component has some internal state called `test` of type `A`.
The bug reproduces both when you declare `let test: A` in script setup, or `return { test: <A>null }` in classic setup.

Assume that your component also exposes a props named `test` of some other type `B`.

Now let's access `test` in the template.

At runtime, Vue will give priority to the _state_ `test`, and will fallback to the props `test` only when no such state exists.
In other word, the visible properties in the template behave like `{ ...Props, ...State }`, the latter overriding keys with the same name from the former.

It seems like Volar combines props and state differently, more like: `Props & State`.
So in IDE, `test` appears to be typed as `A & B`. This is incorrect because it should be just `A`.

That leads to false errors when assigning such members, or combining incompatible types.
For example, if you try this with types `string` and `number`, `test` appears to be `never`.

[Playground reproduction](https://play.vuejs.org/#eNp9kT9vAjEMxb9K5IVWQjCwoQP1jxjaoUVtRy/XwxyhOSdKHIqE7rvXdxTaATEl8Xt++Tk5wH0Io10mmEKRqmiDmESSg3El1zMESQhz5BWtLdMy+pCKgxFKMjWcm0+Kpp3f3CIjO5JfIUm0XJuZQdhYBORifIzWID0INcGVQnoyprAcspi7funu0wTtHGzIOT9AMGO1FeNzDwwVqfK8tvVomzwr96HLQah8E6yj+BrEelbsqemVTis17Pu5r0nMNDzVqw1VXxfq27TvagjLSInijhDOmpSxJjnKi/cX2uv+LDZ+lZ26r4hvlLzLHePR9pB5pdj/fD3tUxN8FH3Hj7TYC3E6DdWBds629yPo5z1eGf0PdzKa9H3ILbQ/xFinKQ==)

![image](https://github.com/vuejs/language-tools/assets/3832820/243a4057-64a7-4336-aa7e-bef9f2fce782)

**Comment by so1ve** [comment]
This is a vue type issue: https://play.vuejs.org/#eNp9kcFOwzAMhl/FymWbNBWh3caGBGgHOABiHH2ZOrdkdE6UpNvQ1HfHSdV2QsAlcezf1vc7Z3VnbXaoSc3VwudO2wCeQm2h2nC5RBU8qltkvbfGBTjDlgrN9GDkzcQBGiic2cNIRoxukJFzwz5AFMDyp3p8Rgawzlg/hxQDFMb0MUD4sjSHdXCayzbXxKuZxjOBjSed2snT8dCbJl1fdiE3kwQ1ZjompkkmKuTFVetVnKmpeBToQpfZzhuWRaSJqHLR64rciw1aTKHqOVFtqsocn1IuuJoSXur5oPzzl/zOn2IO1asjT+5AqPpa2LiSQlterZ/pJHFf3JttXYn6n+IbeVPVkbGV3de8FewLXaJ9TF8oe333q1Mg9p2pCDosGZV8ZVzVX9YH3Fk269asmm85Ab8X

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
