### ISSUE TITLE
TS6059 .vue files in monorepo

### ISSUE THREAD

**Issue by nathan-de-pachtere** [vuejs/language-tools#3713]
Hi,

I'm facing a strange issue with VSCode. It throws a TS6059 error only when I hit save. And If I have two same imports, only one of them going to be good ... and apps are actually working.

![ts6059-vscode-issue](https://github.com/vuejs/language-tools/assets/6233770/1659973f-26d1-4453-8a3e-7147fcb24301)

**Behavior:**
- no error when opening the file
- no error when editing
- error when saving
- apps are actually working properly (cause all the imports are fine) just typescript language service doing weird stuff
- if I open the same repo in PHPStorm I have another error 'Vue Cannot find Module ...'
- If I go back with Typescript language default service from builtin vscode only got error when import same files 2 times inside the same package.
- When using default Typescript service language (so got the default and the volar one running) the error show up depending on the first file I open. If I open Component1.vue first, then Component2.vue gonna have the TS6059 error on the same import. Telling me it's included via import in Component1.vue.

I already checked everything about my tsconfig.json files : rootDir sutff, refrences, etc ...

So I don't know how to handle that, cause is very annoying to have that error on every import.

Don't even know if it's an issue with Volar Typescript language service or VSCODE or another stuff. But seems to be that Volar (takeover) typescript service is not handling correctly.

My project is a Moonrepo with 4 projects running with Vue.js 3 and ~20 libs sharing code (.ts / .vue/.json) between projects. With Yarn workspaces.

And again my apps are running fine and building properly without error. It's just so messy and annoying to code with false positive error in the IDE.

**Comment by nathan-de-pachtere** [comment]
@johnsoncodehk Any idea of what's happening ?

**Comment by nathan-de-pachtere** [comment]
Here a reproducer : https://github.com/nathan-de-pachtere/monorepo-ts-vue-test

**Comment by nathan-de-pachtere** [comment]
Still have this issue, any help from someone ?

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
