### ISSUE TITLE
Generic vue types break depending how props are accessed in template.

### ISSUE THREAD

**Issue by minht11** [vuejs/language-tools#3714]
Generic vue types break depending how props are accessed in template.
Lets take component like this, it all works fine:
```vue
<script lang="ts">
export const customFormatter = (num: number) => `${num * 3}!!!`
export type FormatNumber<T> = (num: T) => string;
</script>

<script lang="ts" setup generic="T extends number, Formatter extends FormatNumber<T>">
const props = defineProps<{
	value: T,
	formatter: Formatter
}>()
</script>

<template>
	{{ value }} {{ props.formatter(props.value) }}
</template>
```
Now take the same component and instead use prop directy inside template without props. like this:
```vue
<script lang="ts">
export const customFormatter = (num: number) => `${num * 3}!!!`
export type FormatNumber<T> = (num: T) => string;
</script>

<script lang="ts" setup generic="T extends number, Formatter extends FormatNumber<T>">
defineProps<{
	value: T,
	formatter: Formatter
}>()
</script>

<template>
	{{ value }} {{ formatter(value) }}
</template>
```
And you will get This expression is not callable. Type 'unknown' has no call signatures.
<img width="614" alt="Screenshot 2023-11-07 at 00 54 05" src="https://github.com/vuejs/language-tools/assets/8914032/d59c81a7-f43a-4116-b81d-2ff6a315efed">

**Comment by so1ve** [comment]
Related https://github.com/vuejs/language-tools/issues/3651 https://github.com/vuejs/core/pull/9418

**Comment by KazariEX** [comment]
It works well with the latest version. If it still happens, fell free to open a new issue.
