### ISSUE TITLE
Discriminated unions doesn't work when the discriminator is wrapped in a Ref

### ISSUE THREAD

**Issue by UfukUstali** [vuejs/language-tools#3715]
## Why this doesn't work?
Typescript (currently) doesn't look any further than the direct decendants of an object to discriminate a union. (Click [here](https://github.com/microsoft/TypeScript/issues/18758) for a more through explanation.)
As a consequence of this when the discriminating factor is a Ref (which happens very commonly) the discriminated union doesn't work.

The above mentioned [issue](https://github.com/microsoft/TypeScript/issues/18758) is open since 2017 and this is still the case. In light of this fact I would like to ask if it would be possible to implement a vue specific feature in volar where it would look inside of direct decendant Refs along with direct decendants for a discriminating factor.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
