### ISSUE TITLE
[Volar + Typescript] Types checking does not work

### ISSUE THREAD

**Issue by KuroBayashi** [vuejs/language-tools#3716]
### Actual

1.  Create a new projet:
```shell
> pnpm create vite .
name: vuets
framework: Vue
variant: Typescript

> pnpm install
> pnpm run dev
```
2. Install VSCode extensions: Volar + Typescript Plugin
3. Disable VSCode extension: Typescript Features
4. Reload VSCode
5. Update `./src/App.vue`, line 14
```vue
  <HelloWorld :msg="{ title: 123 }" />
```

### Expected

I expected VSCode to show me an error on `msg` since in `./src/components/HelloWorld.vue` it is defined as 
```ts
defineProps<{ msg: string; }>();
```

However, i don't get any error, `<HelloWorld>` tooltip is shown as `(property) HelloWorld: any` , even `pnpm run dev` works without any issue, and I can access the page which now renders 
```html
<h1 data-v-e17ea971="">{ "title": 123 }</h1>
```

### Details

- VSCode is up-to-date
- Takeover mode seems to work: "5.2.2 (takeover)" is shown at the bottom right of VSCode.
- I have enabled/disabled all my settings.json
- I tried to uninstall/reinstall both extensions
- I don't have any other extension enabled
- I have tried the same things on 2 computers (Windows 10 / ArchLinux)

**Comment by so1ve** [comment]
Reopen your vscode?

**Comment by KuroBayashi** [comment]
> Reopen your vscode?
> 
> ![image](https://user-images.githubusercontent.com/58381667/281247961-e9d8f0c4-ba65-466d-9d5f-7035cc77af8d.png)
> 
> Install your dependencies first, then reopen your vscode.

Thanks, I already tried "every" possible combination (enable/disable extensions, re-open project folder, re-open VSCode between each steps, ...).

But, just in case it was a problem about cache or something, this morning I did a full clean install:

1.  Created a new Arch VM
2. Installed strict minimum (AwesomeWM for a desktop env, Firefox, VSCode and Node).
3. Started VSCode to install extensions, disable builtin, and checked settings.json:
![image](https://github.com/vuejs/language-tools/assets/8939088/8b9cf2b1-e99d-4c1a-a0b2-1a37db06275e)
![image](https://github.com/vuejs/language-tools/assets/8939088/2c58aed2-e07d-4965-b8a8-c3b8c827fe94)
![image](https://github.com/vuejs/language-tools/assets/8939088/d319831a-4340-4c04-89e4-3691a6a54cab)
4. Closed VSCode 
5. Created a new project like previously:
```shell
pnpm create vite VueTs
...
cd VueTS
pnpm install
pnpm run dev
```
6. Opened VSCode, then open VueTS folder
7. Modified App.vue
![image](https://github.com/vuejs/language-tools/assets/8939088/dfbb0a77-fe42-4b62-b4e2-4cfda7099b0f)
![image](https://github.com/vuejs/language-tools/assets/8939088/b1ca8f83-61bb-4b70-9fac-5970edeb9408)
8. Again, Takeover seems to be enable, but no errors at all
![image](https://github.com/vuejs/language-tools/assets/8939088/06caced3-628f-4314-bf84-2cd970329b53)

I am sorry, I really feel like I am missing something "obvious", but I do not know what it is ... Read the Vue / Vite docs multiple times, searched on Google / SO, but nothing.

**Comment by so1ve** [comment]
Could you please provide your environment info, such as Node.js version, Vue Language Tools version and your reproduction demo?

**Comment by KuroBayashi** [comment]
### Windows 10 Setup

- VSCode (About)
```
Version: 1.84.1 (user setup)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:59.022Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```
- VSCode (Extensions)
```
Vue Language Features (Volar): v1.2.0
TypeScript Vue Plugin (Volar): v1.8.22
```
- Node
```shell
> node -v
v18.16.0
```

### Arch Linux Setup

- VSCode (About)
```
Version: 1.84.1
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:31.181Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.8-arch1-1
```
- VSCode (Extensions)
```
Vue Language Features (Volar): v1.2.0
TypeScript Vue Plugin (Volar): v1.8.22
```
- Node
```shell
> node -v
v21.1.0
```

### Demo 

I tried another approach to install, using `create-vue`,  with the following steps:

1. Install
```shell
> pnpm create vite VueTS
.local/share/pnpm/store/v3/tmp/dlx-3452  |   +1 +
.local/share/pnpm/store/v3/tmp/dlx-3452  | Progress: resolved 1, reused 1, downloaded 0, added 1, done
✔ Package name: … vue-ts
✔ Select a framework: › Vue
✔ Select a variant: › Customize with create-vue ↗
.local/share/pnpm/store/v3/tmp/dlx-3511  |   +1 +
.local/share/pnpm/store/v3/tmp/dlx-3511  | Progress: resolved 1, reused 1, downloaded 0, added 1, done

Vue.js - The Progressive JavaScript Framework

✔ Package name: … vue-ts
✔ Add TypeScript? … Yes
✔ Add JSX Support? … No
✔ Add Vue Router for Single Page Application development? … Yes
✔ Add Pinia for state management? … Yes
✔ Add Vitest for Unit Testing? … Yes
✔ Add an End-to-End Testing Solution? › Playwright
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … Yes

Scaffolding project in /home/kurobayashi/VueTS...

Done. Now run:

  cd VueTS
  pnpm install
  pnpm format
  pnpm dev

> pnpm install
Packages: +365
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 388, reused 363, downloaded 2, added 365, done

dependencies:
+ pinia 2.1.7
+ vue 3.3.8
+ vue-router 4.2.5

devDependencies:
+ @playwright/test 1.39.0
+ @rushstack/eslint-patch 1.5.1
+ @tsconfig/node18 18.2.2
+ @types/jsdom 21.1.5
+ @types/node 18.18.9 (20.9.0 is available)
+ @vitejs/plugin-vue 4.4.1
+ @vue/eslint-config-prettier 8.0.0
+ @vue/eslint-config-typescript 12.0.0
+ @vue/test-utils 2.4.1
+ @vue/tsconfig 0.4.0
+ eslint 8.53.0
+ eslint-plugin-vue 9.18.1
+ jsdom 22.1.0
+ npm-run-all2 6.1.1
+ prettier 3.0.3
+ typescript 5.2.2
+ vite 4.5.0
+ vitest 0.34.6
+ vue-tsc 1.8.22

Done in 1m 24s
```
2. Modify `App.vue`
```vue
<HelloWorld :msg="{ hi: 'hello' }" />
```
3. Run `type-check`
```shell
> pnpm run type-check

> vue-ts@0.0.0 type-check /home/kurobayashi/VueTS
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

src/App.vue:11:19 - error TS2322: Type '{ hi: string; }' is not assignable to type 'string'.

11       <HelloWorld :msg="{ hi: 'hello' }" />
                     ~~~~

Found 1 error in src/App.vue:11

 ELIFECYCLE  Command failed with exit code 2.
```

As we can see, the error is detected, but neither VSCode nor `pnpm run dev`  is giving me any feedback (exactly like shown in the previous comments).

Is there any additional dependency required to make the extensions work ? I just followed the Vite / Vue documentation, then the README generated.

Thanks for your help btw, appreciate it.

**Comment by so1ve** [comment]
Could you please try disable `TypeScript Vue Plugin` and upgrade `Vue Language Features` to v1.8.22?

**Comment by KuroBayashi** [comment]
Thank you! 

Switching `Vue Language Features` to `pre-release version` which is shown as `v1.8.23` instead of `release version` which is shown as `v1.2.0` made TS works. Can't believe it was that simple... 
I have not touched `Typescript Vue Plugin` since it does not have a `pre-release version`, just switching `Vue Language Features` did it.

Nevertheless, I don't understand why it is not the default version when installing the extension. Thought switching to `pre-release` was more like a `nightly build` (meaning get latest features, but bug expected), but afterwards, switching from `v1.2.0` to `v1.823`  seems to be a huge gap.

Thank you again for your help. 

Please, let me know if you need any more information (maybe to fix it, if it is an unexpected behavior).

**Comment by so1ve** [comment]
Actually vscode is expected to install `v1.8.23` by default, not sure why it is instaling `1.2.0` :( Please see https://github.com/vuejs/language-tools/issues/3198

Installing both `Typescript Vue Plugin` and `Vue Language Features` is unwise; they both provide support for `.vue` files, so using them together may cause unexpected bugs.

This issue seemed to be resolved, please let me know if you have any questions!

**Comment by KuroBayashi** [comment]
Yes, the issue is resolved for me, so it can be closed.

Just for the sake of it, I tried to uninstall `Vue Language Features`, and `.vue` does not work anymore, so I guess it still be required. Then even after reinstalling it, `v1.2.0` is still the default, and still have to switch to `pre-release version` to get `v1.8.23`. 

Looks like it is a VSCode marketplace issue.

**Comment by so1ve** [comment]
Yes, this is an upstream VSCode marketplace issue, please track it at https://github.com/vuejs/language-tools/issues/3198.

Closing, have a good day!
