### ISSUE TITLE
Strict templates should report unknown events

### ISSUE THREAD

**Issue by IceBlizz6** [vuejs/language-tools#3718]
Strict templates reports unknown components and unknown props.
I would also like it to report unknown events.

```
<router-link
    to="/contact"
    @eventDoesNotExist="doSomething"
>
    Text here
</router-link>
```

In this example vue-tsc should report an error which states that eventDoesNotExist is not defined on router-link.

**Comment by IceBlizz6** [comment]
@so1ve 
I would love for this to get some attention, but i also suspect that there are many other more important issues.
I wanted to look into the possibility of fixing this myself, but have not touched this code base before.
Would you be able to give me some pointers on where in this code base that i could start in order to fix this?

**Comment by so1ve** [comment]
You can install the `Volar labs` extension then you can inspect the generated virtual code in your sidebar.

**Comment by so1ve** [comment]
![image](https://github.com/vuejs/language-tools/assets/58381667/7b01385c-4bf6-454a-aef6-7d5692770ee8)
I've tested locally and this seemed to work

**Comment by IceBlizz6** [comment]
> tested locally and this seemed to work

Thanks a lot!
Are you planning to merge this into the next version?

**Comment by so1ve** [comment]
Sorry, I couldn't explain it clearly. I mean vue-tsc has currently reported unknown events (with `strictTemplates: true` 💦

**Comment by IceBlizz6** [comment]
I tested it now,
you're right, this actually works when no props are present.
And then it stops working when props are assigned.

So it seems like the current behavior is bugged.

**Comment by IceBlizz6** [comment]
Maybe we should remove the 'enhancement' tag,
replace it with a tag indicating that this is a bug.

**Comment by IceBlizz6** [comment]
I'd hate to bump this again, but would be great if someone could look into this bug.
It's an important feature and it's broken.
We have a working reproduction.
Is there anything else i can provide?

**Comment by IceBlizz6** [comment]
Hey @so1ve 
Did you figure out a solution here?

**Comment by so1ve** [comment]
Unfortunately I didn't, my solution breaks vue 2.7 tests.
