### ISSUE TITLE
[Vue 2.7] event type becomes unknown when type is too long

### ISSUE THREAD

**Issue by kingyue737** [vuejs/language-tools#3719]
Reproduction: https://github.com/kingyue737/vue2-event-type

Firstly, run `pnpm install`

Hover on `@click:date` of `<v-calendar>` in `src/App.vue`, and you will find the type is correct:
![image](https://github.com/vuejs/language-tools/assets/40021217/76e754c8-e0e8-4bfe-8efa-b2dd69f99010)

Then uncomment from line 2712 to 2755 in `src/vuetify.d.ts`, and hover the above again. Type of parameters of the event handler becomes unknown:
![image](https://github.com/vuejs/language-tools/assets/40021217/5b2a77b1-9241-44e8-b0d7-006b00035b0c)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.

**Comment by kingyue737** [comment]
Fixed confirm
