### ISSUE TITLE
Extra white space characters in the tag at the end of template can cause code highlighting exceptions in script and style

### ISSUE THREAD

**Issue by KroMiose** [vuejs/language-tools#3722]
Extra white space characters in the tag at the end of template can cause code highlighting exceptions in script and style.
This happens anywhere that contains `</template>`.

This is a normal status:

![image](https://github.com/vuejs/language-tools/assets/57167362/e374e901-df3f-4810-9c7d-1eb5a32a041c)

The code in script and style highlights the exception when I add a white space character

![image](https://github.com/vuejs/language-tools/assets/57167362/ab8a98a2-8566-4f90-8507-8e9e301aeea5)

Reproduce code

```vue
<template>
  <template>
    <div>
      <h1>{{ text }}</h1>
    </div>
  </template >
</template>

<script setup>
import { ref } from "vue";

const text = ref("Hello World");
</script>

<style lang="scss" scoped>
h1 {
  color: red;
}
</style>
```

**Comment by so1ve** [comment]
![image](https://github.com/vuejs/language-tools/assets/58381667/4d7c69c7-3c3b-4a01-9617-33a87883df7c)

🤔

**Comment by KroMiose** [comment]
![image](https://github.com/vuejs/language-tools/assets/57167362/e4fa7392-5ce6-4784-bd93-31e8614846df)

Vue v0.12.0
Vue Language Features (Volar) v1.8.17
Vue VSCode Snippets v3.1.1

I tried to disable the `vue` extension, and the problem seemed to disappear 😖

**Comment by so1ve** [comment]
Yes please disable the `Vue` extension (at least not using with Volar together), because VueDX is designed for Vue 2
