### ISSUE TITLE
`@vue-ignore`d attributes in generic components are copied in type declarations

### ISSUE THREAD

**Issue by mtorromeo** [vuejs/language-tools#3723]
There is an odd issue where `@vue-ignored` attributes in props of generic components are copied in the exported type declarations, causing huge `.d.ts` files and the attributes actually not being recognized as valid when using the components.

You can inspect the output in the file `dist/components/MyCompo.vue.d.ts` in the linked reproduction, and see that it contains all `InputHTMLAttributes` copied in the props.

Instead, in `dist/App.vue.d.ts, which is not generic, the output is fine.

Reproduction: [StackBlitz](https://stackblitz.com/edit/vitejs-vite-paglg1?file=dist%2Fcomponents%2FMyComp.vue.d.ts&view=editor)

**Comment by so1ve** [comment]
This is not about `@vue-ignore`. Any imported type will have this issue

**Comment by KazariEX** [comment]
This issue has been resolved in the current version.
