### ISSUE TITLE
when i use vue3 ref to get dom，volar's derivation a strange bug occurred

### ISSUE THREAD

**Issue by xhcoding1998** [vuejs/language-tools#3725]
when i use vue3 ref to get dom，volar's derivation a strange bug occurred，The following is my demo example：

When I use el.value as condition of if statement, it works fine：

```
 // correct derivation
  const payNode: Ref<HTMLElement | null> = ref(null)
  onMounted(() => {
    if(payNode.value) {
      payNode.value.style.padding = '0px'
    }
  })
```

But when I const use "el.value" as "condition" and then used "condition" as the condition of the if statement, it gave an error message

```
//  wrong derivation
  const payNode2: Ref<HTMLElement | null> = ref(null)
  onMounted(() => {
    const condition = payNode2.value
    if(condition) {
      payNode2.value.style.padding = '0px'   // error：  "payNode2.value" may be "null".
    }
  })
```

![image](https://github.com/vuejs/language-tools/assets/64572846/1a55d5c2-4c0d-4bf8-ac43-8b05c2f1bc0f)

**Comment by so1ve** [comment]
This is a typescript limitation.

https://www.typescriptlang.org/play?#code/DYUwLgBAhghAXBA3hAZgezQgdgVwLYBGIAThAD4S7DAQC+AUPQMZpYDOkBEAvNAHTo0jAJYoIACgIBKJPQjz+gvmDQBRAB4AHViCxhhUYPQZA
