### ISSUE TITLE
[ADVICE] default as import of defineComponent() has broken typing

### ISSUE THREAD

**Issue by michealroberts** [vuejs/language-tools#3726]
I just wanted to understand an issue I am seeing, I'm 99% sure it is not Volar throwing any tricks but just wanted to understand the overall reason why a `defineComponent` is being typed as any.

We have a monorepo setup => whereby the package in question is reliant on vue-demi, the defined component is like:

```ts
const Background = defineComponent({
  name: 'Background',
  compatConfig: { MODE: 2 }
  props: {
    ///...all the props
  },
  setup(props: BackgroundProps, { slots }) {
    //...all the setup

    return () => h(
      // ...some rendered element
    )
  },
})

export default Background
```

This is then exported from the package's entrypoint as:

```ts
export { default as Background } from './Background'
// ... other exports here
```

It's the same if I use the export default directly:

```
export default defineComponent({ ... })
```

However, the imported type from a corresponding package seems to be "any":

![Screenshot 2023-11-10 at 12 25 05](https://github.com/vuejs/language-tools/assets/84131395/8b2e0095-fe0e-4d03-8e64-19c581b78f9f)

Does anyone know a trick or something I could do to get this working correctly? 🤔

**Comment by so1ve** [comment]
Hello @michealroberts, are you using javascript not typescript?

**Comment by michealroberts** [comment]
@so1ve Hey Ray. TypeScript => the @vue-flow/background package is compiled to js but has the exported types, it's just that they imports are not typed in any way ...

**Comment by so1ve** [comment]
Ah - I see. This is actually a display issue, if you try access some properties such as `Background.xxx` it should be typed correctly.

**Comment by michealroberts** [comment]
@so1ve But on the template, we don't get any type inference from Volar at all. We don't see what props are required or what props are possible ...

**Comment by so1ve** [comment]
Which version are you using? `1.8.22` or `1.8.23`?

**Comment by michealroberts** [comment]
`1.8.22` ...

**Comment by michealroberts** [comment]
I basically see this:

![Screenshot 2023-11-10 at 15 13 29](https://github.com/vuejs/language-tools/assets/84131395/2e8f8659-cc6f-48b1-a6b5-4f838ddeaa0d)

**Comment by so1ve** [comment]
Someone told me that `1.8.23` will work, could you please give it a try? Just click `install pre-release`

**Comment by michealroberts** [comment]
Hey Ray, damn - still no luck. The repo uses “shamefully-hoist”, and we’re mixing Vue major versions. Could this be the issue?

**Comment by so1ve** [comment]
Mixing Vue major versions could be the root cause - could you please provide a minimal reproduction to help us investigate? Thanks a lot!

**Comment by michealroberts** [comment]
@so1ve Sure -> this MR here on this branch should be enough to investigate: https://github.com/bcakmakoglu/vue-flow/pull/1188

Let me know if you need anything else ...

**Comment by michealroberts** [comment]
Hey @so1ve - apologies for bugging, but I wondered if you managed to look at this?

**Comment by so1ve** [comment]
Sorry, missed your reply 🥹 I'll check it now

**Comment by so1ve** [comment]
![image](https://github.com/vuejs/language-tools/assets/58381667/434f47ca-fd99-4842-af5d-2ad539fb5af8)

Everything is working fine on my side 🤔

**Comment by michealroberts** [comment]
Cool, is that inside the project? Looks to be working well ...

**Comment by so1ve** [comment]
I simply cloned the repository, checkout your PR, and then build the types.

I use Vue Language Tools 1.8.23

**Comment by michealroberts** [comment]
@so1ve Could you double check this for me, I'm not convinced because the current master branch works but that PR doesn't. I am using Vue Language Tools 1.8.23 pre-release and I have built the types but I am not seeing any type hints at all.
