### ISSUE TITLE
Support for Vue's `.prop` modifier shorthand syntax

### ISSUE THREAD

**Issue by GrantGryczan** [vuejs/language-tools#3727]
![image](https://github.com/vuejs/language-tools/assets/14056899/4590233a-fb83-4438-af4d-8d6cf04df67b)

![image](https://github.com/vuejs/language-tools/assets/14056899/c6ae5a14-e438-4f9e-8e6d-66cdae727e44)

Even though both of the above are [functionally](https://github.com/vuejs/vue/issues/7582) [equivalent](https://vuejs.org/api/built-in-directives.html#v-bind), in VS Code the latter doesn't get syntax-highlighted, it doesn't get IDE autocomplete, and it doesn't get covered by Vue's ESLint plugin.

Note: TypeScript (in Volar takeover mode, haven't tested otherwise) does still check the contents though, at least.

![image](https://github.com/vuejs/language-tools/assets/14056899/82259f9a-6360-4a4f-b045-7f0305440f02)

**Comment by so1ve** [comment]
Where is the upstream rfc / implementation PR?

**Comment by GrantGryczan** [comment]
@so1ve It was added in this commit: https://github.com/vuejs/vue/commit/d2902ca8ec5fd184fe81479fea1318553fdb8323

**Comment by so1ve** [comment]
Thanks! This seems to be a Vue 2-only feature.

**Comment by GrantGryczan** [comment]
> Thanks! This seems to be a Vue 2-only feature.

@so1ve As linked in my original issue, [it's in the Vue 3 documentation](https://vuejs.org/api/built-in-directives.html#v-bind). Also, I've tested it to work in Vue 3.

**Comment by so1ve** [comment]
I see 👍

**Comment by so1ve** [comment]
Completion and diagnostics should work normally, but the syntax highlighting is broken if I understand correctly?

**Comment by GrantGryczan** [comment]
Completion is not working. I only noted that type checking works.

**Comment by so1ve** [comment]
I've double checked this issue - completion is working for mem only the highlighting is broken. I've a PR to fix this issue: #3729
