### ISSUE TITLE
Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { style?: unknown; class?: unknown; ref?: VNodeRef | undefined; key?: string | number | symbol | undefined; ref_for?: boolean | undefined; ... 6 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined; }; ... 10 more ...; $watch<T extends string | (...'.ts(2339)

### ISSUE THREAD

**Issue by Nick-Hopps** [vuejs/language-tools#3735]
I can affirm the `$t` method of vue-i18n has been registered onto app.config.globalProperties:

![image](https://github.com/vuejs/language-tools/assets/16911282/aa2d6610-907e-46d0-9997-d431c381fb40)

looks like volar fail to load type file for vue-i18n:

![image](https://github.com/vuejs/language-tools/assets/16911282/9abdb982-c03a-4946-a361-12c6d24c04bf)

I try to add types manually to tsconfig.app.json, but still not working:

![image](https://github.com/vuejs/language-tools/assets/16911282/3464669a-6a54-495e-bb4c-a2e5c6cb400c)

add declaration also useless:

![image](https://github.com/vuejs/language-tools/assets/16911282/bba57f45-cf37-4c19-9a80-a8a8ae77d402)

- vue: 3.3.4
- vue-i18n: 9.2.2
- volar: 1.8.22
- vue-tsc: 1.8.22

**Comment by so1ve** [comment]
Does `declare module 'vue'` work?

**Comment by Nick-Hopps** [comment]
> Does `declare module 'vue'` work?

yes, it works, but why?

**Comment by dhavalt091** [comment]
I am having same issue. With `$t` and with `$18n` as well.

**Comment by Nick-Hopps** [comment]
> I am having same issue. With `$t` and with `$18n` as well.

same issue, change to `declare module 'vue'` solve it temporarily, but still not the expected bahavior.

**Comment by Nick-Hopps** [comment]
vue-i18n: 9.8.0, volar: 1.8.24, problem remains

**Comment by dhavalt091** [comment]
Strange thing is if i put empty script tag then it works.
```
<script setup>
</script>
```

**Comment by Nick-Hopps** [comment]
> Does `declare module 'vue'` work?

I have figured it out, it is because I have a monorepo installed with vue@3.2.47, the mian version I'm using is vue@3.3.4, and  package '@vue/runtime-core' under root node_moudles belongs to 3.2.47 and 'vue/node_modules/@vue/runtime-core' is what 3.3.4 really using. That's the reason why `declare module 'vue'` is working.

**Comment by Barry-Flynn** [comment]
[vue-i18n 使用 $t 导致的 Typescript 报错问题](https://blog.csdn.net/qq_40147756/article/details/142067597)

手动添加类型声明文件，给 `ComponentCustomProperties` 添加 `$t` 属性即可。目录 `src/vue-i18n.d.ts`

```typescript
/* eslint-disable */
import Vue from "vue";
declare module "@vue/runtime-core" {
	export interface ComponentCustomProperties {
		$t: (key: string, ...args: any[]) => string;
	}
}
```

**Comment by intellild** [comment]
上面的解决不了的话，可以试试这个
If you are looking for a workaround, try this 
https://nuxt.com/blog/v3-13#vue-typescript-changes
