### ISSUE TITLE
volar Vue language features无法离线安装

### ISSUE THREAD

**Issue by zhouyaxi** [vuejs/language-tools#3737]
Vue language features在Ubuntu18.04中无法离线安装，使用code --install-extension Vue.volar-1.8.23.vsix 命令进行安装时会报错
permisson denied，open ‘/usr/share/code/bin/Volar-1.8.23.vsix’

**Comment by so1ve** [comment]
This is a VSCode issue, try using `sudo` or report it to https://github.com/Microsoft/vscode
