### ISSUE TITLE
When using vue@2.6.14 + @vue/composition-api, Volar cannot recognize custom components.

### ISSUE THREAD

**Issue by curlykay** [vuejs/language-tools#3738]
Reproduction: https://github.com/curlykay/volar-test.git

environment
macos 13.4.1
vscode 1.84.2 
vue 2.6.14
volar 1.8.23
@vue/composition-api 1.7.2

The minimal repo built with @vue/cli (Vue + TypeScript), using Volar in 'takeover mode'.
<img width="389" alt="image" src="https://github.com/vuejs/language-tools/assets/35558285/3a873a20-2161-41b8-ac64-04269486c949">
<img width="347" alt="image" src="https://github.com/vuejs/language-tools/assets/35558285/77975978-e452-4c4b-9b7f-c1b98707523a">

I followed the steps in 'Setup for Vue 2' from https://marketplace.visualstudio.com/items?itemName=Vue.volar completely to set up the repository. I added "@vue/composition-api" and developed components using defineComponent. However, after restarting VSCode, Volar recognizes the component as '(property) HelloWorld: unknown'.
<img width="574" alt="image" src="https://github.com/vuejs/language-tools/assets/35558285/fa447d96-a5df-4f8e-94a8-230b2fc983ce">
Do I need to add anything else?

**Comment by so1ve** [comment]
Maybe vue 2.6 should stay on Vetur...?

**Comment by rchl** [comment]
Is there are reason that you are not using Vue 2.7/

**Comment by curlykay** [comment]
> Maybe vue 2.6 should stay on Vetur...?

Vetur does not support TS 5.0, and that's been my frustration.https://github.com/vuejs/vetur/issues/3689#issue-1661676579

**Comment by curlykay** [comment]
> Is there are reason that you are not using Vue 2.7?

I plan to upgrade to Vue 2.7, but some parts of vue-property-decorator are incompatible with Vue 2.7. So, I intend to use 'Vue 2.6' with '@vue/composition-api' as an interim solution. This way, I can continue working with the Composition API while addressing compatibility issues and transitioning to Vue 2.7.

**Comment by curlykay** [comment]
I might have been a bit eager, and for that, I apologize. However, the responses I've received seem to lack clarity.
So, did I do something wrong, or does Volar indeed not support intelligent prompt for components with this combination ('vue@2.6.14' + '@vue/composition-api')?

**Comment by so1ve** [comment]
I do think so - Volar only supports Vue 2.7+ and 3.0+, otherwise you should use Vetur. Vetur's support for TS 5.0 is a Vetur issue, not Volar's.

**Comment by curlykay** [comment]
Thank you for your response. The mention of Vetur's incompatibility with TS 5.0 was just to explain why I'm not using Vetur for Vue@2.6. If it caused you any inconvenience, I apologize.
Perhaps the VSCode Marketplace description for Vue 2 compatibility operations needs to specify its relevance for Vue@2.7, to prevent further confusion among users like me.
<img width="808" alt="image" src="https://github.com/vuejs/language-tools/assets/35558285/1b7c68f3-c496-4494-818f-7838cc549398">
Volar is a magnificent creation. Thank you for your dedication.

**Comment by zhangyahan** [comment]
This is a bit strange. I am using Vue:>=2.6.14<2.7 and @ Vue/composition app: ^ 1.7.2 and Volar: v1.8.26, which are currently working normally.
![image](https://github.com/vuejs/language-tools/assets/46292088/f3e54bad-3451-4590-a006-848c081373f0)
Are you missing a certain configuration?

**Comment by curlykay** [comment]
> 这有点奇怪。我正在使用 Vue：>=2.6.14<2.7 和 @ Vue/composition app： ^ 1.7.2 和 Volar： v1.8.26，它们目前工作正常。 ![图像](https://private-user-images.githubusercontent.com/46292088/292674765-f3e54bad-3451-4590-a006-848c081373f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzExNDgsIm5iZiI6MTcwMzQzMDg0OCwicGF0aCI6Ii80NjI5MjA4OC8yOTI2NzQ3NjUtZjNlNTRiYWQtMzQ1MS00NTkwLWEwMDYtODQ4YzA4MTM3M2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE1MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNzk1MDMxNDQ2NDJkMDBjNmI1MDU0MjA0Yjc1NjhiN2RkNjQ4MTBlMTdjMzJlMDMyNzRmNjQ2NzAxZThhYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e2bNakKxVJAd8AJ-FfXHIXyIB0zjaDIuw32ohZ3os5k)您是否缺少某个配置？

 Could you please give me a repo? This is my repo: https://github.com/curlykay/volar-test.git, I reconfirmed that there is no display prompt.

**Comment by zhangyahan** [comment]
@curlykay I don't know why, this project is also in the same situation in my pc. I have switched from Volar to Vetur due to some issues. Because I understand a truth that when something is difficult at the beginning, it must be choosing the wrong direction.

**Comment by curlykay** [comment]
@zhangyahan  I also switched back to Vetur, but when I upgrade Vue to Vue2.7+ in the project, I will continue to try Volar. Its Template Intelligence Sensing is the feature I need.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
