### ISSUE TITLE
Code highlighting error with Type Assertion such as  "as any"

### ISSUE THREAD

**Issue by dongwa** [vuejs/language-tools#3742]
Just a simple example here with volar v1.8.22:

![image](https://github.com/vuejs/language-tools/assets/38457491/11068296-4cef-40f0-b642-8679b74a458c)
![image](https://github.com/vuejs/language-tools/assets/38457491/5b20ba16-572c-4451-96c7-b7ec85360405)

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/656
