### ISSUE TITLE
Using Neovim with TypeScript in Vue files, the LSP is unable to update information.

### ISSUE THREAD

**Issue by zlxbuzz** [vuejs/language-tools#3749]
When I change the utility function 'a', the 'a' function in TypeScript files updates in real-time, but in Vue files, it doesn't. I have to use 'lsprestart' to update it again."
LspLog: 
```bash
 [WARN][2023-11-22 17:00:53] ...lsp/handlers.lua:137 "The language server volar triggers a registerCapability handler despite dynamicRegistration se
      t to false. Report upstream, this warning is harmless"
```

https://github.com/vuejs/language-tools/assets/13307888/c4b16151-82f7-43d2-823a-c0587fc05c2d

**Comment by manavkush** [comment]
I'm having the same issue. With the same warning.

**Comment by CofCat456** [comment]
It works for me. Which version of Volar are you using?


https://github.com/vuejs/language-tools/assets/93901409/7d2029e4-cdeb-402a-b2ab-fe57f494a091

**Comment by johnsoncodehk** [comment]
This is expected, you will receive updates in the vue file when you save the ts file, because the vue language server does not synchronize unsaved file changes in ts files.

**Comment by manavkush** [comment]
My bad, the error was related to my lsp configuration. Working all good. Thanks!!
