### ISSUE TITLE
高亮显示的颜色有问题？

### ISSUE THREAD

**Issue by xuxchao** [vuejs/language-tools#3752]
如图所示：没有什么代码但是高亮特别奇怪。直接导致了整个高亮不可用
![image](https://github.com/vuejs/language-tools/assets/28293069/9db3f481-bbbe-48a4-85a7-364780a142af)

**Comment by so1ve** [comment]
Any reproduction?

**Comment by yoyo837** [comment]
maybe related with https://github.com/vuejs/language-tools/issues/3753

**Comment by Shyam-Chen** [comment]
![image](https://github.com/vuejs/language-tools/assets/13535256/555ae247-6d86-405f-889a-652798f4a455)
