### ISSUE TITLE
Vue Language Features (Volar) Non-latest version installed by default

### ISSUE THREAD

**Issue by yoyo837** [vuejs/language-tools#3753]
This will lead to problems such as no difference in the highlight color of custom components equivalent to native html tag. Is there something wrong with the Volar latest tag in vscode marketplace?

![image](https://github.com/vuejs/language-tools/assets/6134547/f2194fd6-0cd1-4c77-b0da-84ff37eca889)

**Comment by yoyo837** [comment]
Sorry for not looking for duplicate issues before open this.

**Comment by so1ve** [comment]
Never mind :)
