### ISSUE TITLE
1.8.24 shows new errors

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#3763]
Starting from 1.8.24, a new errors are shown like:

```
[vue-tsc] app/components/requests-chart.vue:3:10 - error TS2339: Property 'ClientOnly' does not exist on type '{}'.
[vue-tsc]
[vue-tsc] 3         <client-only>
[vue-tsc]            ~~~~~~~~~~~
[vue-tsc]
```

I don't have time to investigate now and can't share the project but I can look into creating a repro at some point later.

**Comment by rchl** [comment]
Actually it's likely due to:

> fix(language-core): strictTemplates fails to report unknown components (https://github.com/vuejs/language-tools/issues/3539)

which is technically correct but feels like a breaking change since it was not working like that for ages...

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
