### ISSUE TITLE
`ComponentSlots<>` doesn't work with generic components (`FunctionalComponent` in general?)

### ISSUE THREAD

**Issue by pinguet62** [vuejs/language-tools#3764]
Hello 🖖

## Sample

```vue
<template>
  <div>
    <slot name="child" />
  </div>
</template>

<script lang="ts" setup generic="T">
</script>
```
`ComponentSlots<typeof Sample>` always return `{}`.

## Generics

For generic components (`<script setup lang="ts" generic="...">`) Vue processor generate a `FunctionalComponent`.
And `ComponentSlots<typeof MyGenericComponent>` always returns `{}`.

## Fix

The original implementation of `ComponentSlots` is 
```typescript
export type ComponentSlots<T> =
	T extends new () => { $slots: infer S; } ? NonNullable<S> :
	T extends (props: any, ctx: { slots: infer S; }, ...args: any) => any ? NonNullable<S> :
	{};
```
If I change by adding `attrs` & `emit` fields in context:
```typescript
export type ComponentSlots<T> =
	T extends new () => { $slots: infer S } ? NonNullable<S> :
	T extends (props: any, ctx: { slots: infer S; attrs: any; emit: any }, ...args: any) => any ? NonNullable<S> :
	{}
```
it works

## ComponentEmit

Probably same error with `ComponentEmit`.

**Comment by so1ve** [comment]
Feel free to open a new PR :)

**Comment by pinguet62** [comment]
Hello @so1ve
Ok I will create the PR in few minutes 👍
