### ISSUE TITLE
Dynamic component shows error for props with kebab-case

### ISSUE THREAD

**Issue by dvdmlln** [vuejs/language-tools#3765]
Hi,

since 1.8.24 Volar shows an error when using a dynamic component with an imported component object and a kebab-case required prop.

Example:
`FooBar` component has a required prop `fooBar`. The following leads to an error `Property 'fooBar' is missing in type`.
```
<template>
  <component :is="FooBar" :foo-bar="text"></component>
</template>

<script>
import { FooBar } from '#components'
</script>
```

Best regards
David

**Comment by rchl** [comment]
https://github.com/vuejs/language-tools/pull/3750 is likely related.

**Comment by rchl** [comment]
Actually my testing shows that it works the same in both 1.8.22 and 1.8.24 so maybe I'm missing something. Can you provide a repo that reproduces this issue? It looks like the type of FooBar or the project configuration might be relevant.

**Comment by rchl** [comment]
FYI: I've been testing with this since your example doesn't produce any errors in the project I've been using:

```vue
<template>
	<component :is="Foo" :stoke-width="123" />
</template>

<script setup lang="ts">
import { defineComponent } from 'vue';

const Foo = defineComponent({
	props: {
		strokeWidth: { type: String, required: true },
	}
});
</script>
```

This produces and error in both Volar versions.

![Screenshot 2023-11-30 at 22 31 23](https://github.com/vuejs/language-tools/assets/153197/9b346a10-abbf-4f3f-a8d4-016a4c1d8b4f)

**Comment by dvdmlln** [comment]
I've set up an reproduction repo here: https://github.com/dvdmlln/vue-tsc-dynamic-component-props
Running `npm run type-check` produces an error. Setting vue-tsc to fixed version 1.8.22 does not produce an error.

**Comment by throrin19** [comment]
Same problem here, it works fine in 1.8.22 and no more in 1.8.24

**Comment by WangJincheng4869** [comment]
May I ask, when can this fatal bug be fixed?

**Comment by gangsthub** [comment]
> #3750 is likely related.

Also https://github.com/vuejs/language-tools/issues/3255
