### ISSUE TITLE
[Bug] volar does not work properly in vue files in monorepo

### ISSUE THREAD

**Issue by niuiic** [vuejs/language-tools#3767]
```
git clone https://github.com/niuiic/vue-fusion
pnpm i
```

In `packages/components/src/App.vue`

![image](https://github.com/vuejs/language-tools/assets/63799565/89962575-0e93-4e99-8c0b-664a872d4ba3)
![image](https://github.com/vuejs/language-tools/assets/63799565/dc5a4974-dd1e-4ee9-85bd-7e2e9ae8a470)
![image](https://github.com/vuejs/language-tools/assets/63799565/0b728e1a-8b2d-463e-ad14-0b07679e1740)

**Comment by rchl** [comment]
This is an eslint error and not a volar error. You'll get the same when running eslint manually with something like `pnpm eslint --ext .vue ./packages/components/src/App.vue`.

So what do you mean exactly by "does not work properly"?

**Comment by niuiic** [comment]
`x` is a string. What is `x.defineEmits`?

**Comment by rchl** [comment]
You need to include *.vue pattern in tsconfig `includes`. Like `src/**/*.vue` or such.

**Comment by niuiic** [comment]
Sorry, my mistake.
