### ISSUE TITLE
volar auto-formatting - Condition operator interfere with the identification of the HTML tag end

### ISSUE THREAD

**Issue by LiuChuYu** [vuejs/language-tools#3772]
![image](https://github.com/vuejs/language-tools/assets/16636236/b1ac964f-9f52-4e6d-88ce-01a7873b862c)

```html
<template>
  <div>
    {{ here < 1 ? is : it }} </div>
</template>
```

The condition operator will interfere with the identification of the HTML tag end when using Volar’s auto-formatting feature.

Vue Language Features (Volar)
v1.8.24

**Comment by KermanX** [comment]
Cannot be reproduced in the latest version
