### ISSUE TITLE
Toggle comments not working at startup

### ISSUE THREAD

**Issue by bapman81** [vuejs/language-tools#3776]
When I try to toggle line comments in a .vue file, nothing happens.

It is not working either by using the keyboard shortcut or using the menu (Edit --> Toggle Line Comment).

Also not working when using "Toggle Block Comment".

However it starts working when I switch to a pure JavaScript file and come back to the .vue file! Sometimes switching to another .vue file also makes it working but not systematically.

It used to work before and the only thing I changed was to update to macOS Sonoma (14) from Ventura (13) but I cannot be sure it is coming from it.

VSC info:

Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

Volar: 1.8.24

**Comment by movy** [comment]
This is a recurring problem, and I just encountered it again with the latest version of VSCode and extension, please check for regressions. Thanks, @bapman81 , switching language mode to JS and back to Vue helps, but we cannot live like this! 

Version: 1.107.1 (Universal)
Commit: 994fd12f8d3a5aa16f17d42c041e5809167e845a
Date: 2025-12-17T14:15:14.850Z
Electron: 39.2.3
ElectronBuildId: 12895514
Chromium: 142.0.7444.175
Node.js: 22.21.1
V8: 14.2.231.21-electron.0
OS: Darwin x64 23.6.0

**Comment by LuSrackhall** [comment]
> This is a recurring problem, and I just encountered it again with the latest version of VSCode and extension, please check for regressions. Thanks, [@bapman81](https://github.com/bapman81) , switching language mode to JS and back to Vue helps, but we cannot live like this!
> 
> Version: 1.107.1 (Universal) Commit: 994fd12f8d3a5aa16f17d42c041e5809167e845a Date: 2025-12-17T14:15:14.850Z Electron: 39.2.3 ElectronBuildId: 12895514 Chromium: 142.0.7444.175 Node.js: 22.21.1 V8: 14.2.231.21-electron.0 OS: Darwin x64 23.6.0


Yes, this happens on macOS.
From time to time, the toggle comment shortcut stops working inside the <style> section of .vue files.
I rarely (or almost never) encounter this issue on Windows.

**Comment by mmMrz** [comment]
Yes, as of now, July 24, 2026, this bug still exists.
Also, I found a simple solution: manually write an  comment once, then click Ctrl+/, and it works normally.
