### ISSUE TITLE
Optional props are incorrectly typed in `<template>`

### ISSUE THREAD

**Issue by DrJume** [vuejs/language-tools#3779]
Optional props in Vue 3 are not optional anymore on the resolved `props` value from `defineProps`: 
- vuejs/core#6421

Additionally, Vue 3 casts optional boolean props to only type `boolean`, because of https://vuejs.org/guide/components/props.html#boolean-casting.

The only correct way to allow `undefined` for a boolean prop is to manually set it as a default with `withDefaults`. (see reproduction `components/BooleanWithUndefined.vue`)

This should also reflect in the `<template>`.

[Link to reproduction](https://codesandbox.io/p/devbox/volar1-incorrect-prop-type-in-template-p5w97j?file=%2Fsrc%2Fcomponents%2FReproduction.vue%3A8%2C23&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpsl4yua00073b6hc2mxt7vx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpsl4yua00023b6hwv3y4nb0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpsl4yua00043b6hylr7vqar%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpsl4yua00063b6hp0m51z46%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpsl4yua00023b6hwv3y4nb0%2522%253A%257B%2522id%2522%253A%2522clpsl4yua00023b6hwv3y4nb0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpt3s30900023b6gja4y9fof%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FReproduction.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpt3s30900023b6gja4y9fof%2522%257D%252C%2522clpsl4yua00063b6hp0m51z46%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpsl4yua00053b6hd2wxc5e1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpsl4yua00063b6hp0m51z46%2522%252C%2522activeTabId%2522%253A%2522clpsl4yua00053b6hd2wxc5e1%2522%257D%252C%2522clpsl4yua00043b6hylr7vqar%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpsl4yua00033b6h3kbb51dm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%255D%252C%2522id%2522%253A%2522clpsl4yua00043b6hylr7vqar%2522%252C%2522activeTabId%2522%253A%2522clpsl4yua00033b6h3kbb51dm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by johnsoncodehk** [comment]
It will fix in Vue 3.5 via vuejs/core#10801.
