### ISSUE TITLE
Incorrect type inference when you define slot element in v-for loop

### ISSUE THREAD

**Issue by nkeyy0** [vuejs/language-tools#3787]
I'm trying to implement a table with dynamic slot names that are based on the column names, but I am faced with an issue with types in the `v-for` loop inside the template. For some reason the result type of the value is inferred as `never`, but if we do the same in the typescript we get a different type. Looks like it's an issue in the template type inferring.

[Link to repro](https://play.vuejs.org/#eNp9lG1P2zAQgP/KLZoUkFoqwbcsRdomJrFJbALEF1KJNLmEgGNbthNadfnvO5/7EsZGv9Q+38tzb9lEn7U+6TuMkii1hWm0A4uu0yByWc+zyNksOs9k02plHGzg7kqVOAGDFQxQGdVCTNZxJjPp1hrhNl8KvFYvMIdNJgGsy11nE4g7+SzVi4zhN8SNBG1UbdBavpdKYvzJq2vTFJiA7NolGpYIVddYJrBUSmAuSTb4YIWS1oHz0W6KR2xzCngfh2jxBGJ25A/BPl5AboGNyMPImFCT/0Mz2GQEdsqXHZMzHb7isUI5S15KrBqJN/6Wbu5/4Boo5Wdcq+oQi3geChRi+nFDCsPDIoEjWyhNUTZ9Ljr63+l6D4vhGObnof7D+dExpZHJ2YwcV2h8asZgQUlRE3Y0zOwhiIjJ7mMOGGqzYA/cNA8439O85hwetkqcDan5C72zw78gWG9LItbglNra3vl8Llaa5Fjeesk8+OPMMpnOwuzRpNHFYatF7pBvAGnZ9NBPK2VoHgnO13LU+CyChKThjYcV6Jd+mE7hmzJgVYs0rrlVZOUjNxYk9mgmsOxcGOF2DZr4PV7Tk4aDR+qOU7BE36a39NPpLowvAyQyb5EARhWkshEX99Fv0baYhEepkgmbpzPKLJw87eXbTvoS7oKFUNtIhz6Ow5yO/aezUR2jCW0yTUXV1CdPVApad5508qRa3Qg0P7VraGqyiMYv5JZFuRDq5TvL/Kjz7LPNIxbP/5A/2ZWXZdEvWm00PcHt31xuanTh+eLmCld03j+2quwEab/zeI1Wic4zBrUvnSwJe6THtJf8oWpkfWsvVg6l3SUVdhVgYP0soq/W13dSP+CenZyxHS16NPwBcjDExQ==)

**Comment by nkeyy0** [comment]
When I use the `as` operator in the `defineSlots` mapped type it isn't asserted to type I want to and remains the `key`, not `cell-${key}`. How can I handle such a case?

**Comment by so1ve** [comment]
Seemed to be a typescript limitation: https://www.typescriptlang.org/play?#code/DYUwLgBAZg9jCEAuCAKFBDZBvCA3dwAriMgHaEC2ARiAE4DcEAvgJQQC8AfHjAJYAmbAD6oM2PAWLIARIVIBrUjADupaRBHTepCAAdaMAOa0QAZ1PrN-GKRDTGrDt1x9BG0Zgg58REhCpwoOikDmxcPAIsAFBRsDAoWFEAkD5SEADk6VGsQA

**Comment by nkeyy0** [comment]
Hmm, yeah. Looks like it is. I found an issue in the TS repo related to this behavior, but looks like it can be fixed by using generics. You can find [more info in this PR](https://github.com/microsoft/TypeScript/pull/47109#issue-1077307680). And I fixed my repro according to the suggested solution in the TS PR. You can see [my fix here](https://play.vuejs.org/#eNp9U11r2zAU/St3YuAW4gTaN88JbKMPXaAbbdlLHIhjX7tuZElIctKQ+b/vSopb74P6xdL9Oueee3Vin5Wa7jtkCUtNoRtlwaDtFPBc1POMWZOxRSaaVklt4QQ/72SJE9BYQQ+Vli1ElB1lIhP2qBAe8y3He3mAOZwyAWBsbjuTQNSJnZAHEcEviBoBSstaozH+XkqB0ScXrnRTYAKia7eovYXLusYyga2UHHNBtv5PsAcurUmXgC8WRWlgh0dZvfJYOCKrJR6BQJeQG9gUyHn88US2frNO4MIUUhHmaZ/zjv5D5mq57i9hvggtr9YetpDCWLAet3jCNqfyqyg0GU0g8vzdIdCO1g7RJxHxUTLVf0P6Ryuvx2Skx5W/DFJY3eFZhlDSOAmoSolVI86CjLT5S5HFxSWRSWdh3DRculhsFc8t+htAWjZ72MeV1LQClO7EGzWdMUjIGnx+P4C+1NGAROQtkmeQmSL6jUvw8rqNGvQlz5qSiQjl+RrpjHDD6UMcw62oUDv5tMaChHMjt1JCHIcYj3eG82herTHW1bh+Oht1ySa02qRe1dTTZyMF7b+fAVWSrWo46u/KNqRuxmg1QoMZyzmXh2/e5obgp+JznrDY/cf+bF6cLWM/aNdR74ncq8/mukYb3DcPd7S+I2cry45T9DvOezSSd45jCPvSiZJoj+I821v/chtRP5ob90LM0FTYIoDex2eMnvHXd1p/o3s9vfZ5tIKs/w1gi28x) I'm just thinking about can it be fixed directly in the Vetur, or should it be applied in the user's code?

**Comment by KermanX** [comment]
Assuming thatline 33 in the reproduction link has a missing `[key]`:
```
    <slot :name="`cell-${key}`" :value="tableRow[key]"></slot>
                                                ^^^^^
```
, I think this is a TS limitation. We can't fix this on Vue's side.
