### ISSUE TITLE
Renaming import with alias not work

### ISSUE THREAD

**Issue by vanarok** [vuejs/language-tools#3794]
I try to rename file: `@/components/component.vue` with action and the server returns the error: `you cannot rename a module via a global import`.

project tsconfig:
```
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "@/components/*": ["./src/components/*"]
    },
    "noEmit": true
  },
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue", "@/**/*.vue"],
  "exclude": ["src/**/__tests__/*"]
}
```

`../components/component.vue` - renamed without error

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
