### ISSUE TITLE
typescript vue plugin not available on open-vsx marketplace

### ISSUE THREAD

**Issue by SLepUbIn** [vuejs/language-tools#3799]
I'm trying to follow official docs : https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode

which states that we need to use 2 extensions : 
- vue language features (volar) available here on open-vsx : https://open-vsx.org/extension/Vue/volar
- typescript vue plugin

But for the second one the only plugin that appears in search is outdated : https://open-vsx.org/extension/johnsoncodehk/vscode-typescript-vue-plugin

Is it possible to have an up to date version of the second one ?

**Comment by so1ve** [comment]
Please track https://github.com/vuejs/language-tools/discussions/3789. After 2.0 the `typescript vue plugin` will be deprecated.
