### ISSUE TITLE
Existing code mangled by volar format on save

### ISSUE THREAD

**Issue by neontuna** [vuejs/language-tools#3804]
We have a fairly large existing VueJS code base and have been using Vetur in VSCode for a while.  After switching to Volar I've noticed numerous issues with format on save making weird changes to the indentation of files and even more concerning its essentially mangling code by inserting spaces in the middle of variables and random new lines.  I've tried to figure out what settings are doing this but I can't find documentation on what Volar is using for linting/formatting out of the box.

Here's an example on an existing file.

![Screen Recording 2023-12-14 at 9 04 54 AM](https://github.com/vuejs/language-tools/assets/7414827/51f24b01-7adb-4317-8bda-586aee906e1b)

VueJS verson 3.2.31
VSCode version 1.85.1

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction? Are you using eslint / prettier?

**Comment by neontuna** [comment]
We are not using eslint or prettier.  I'm not sure how to provide a reproduction - haven't done that before with a VS Code extension.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
