### ISSUE TITLE
Autocompletes for external Vue components results in kebab-case, despite settings

### ISSUE THREAD

**Issue by ffxsam** [vuejs/language-tools#3805]
See video below. I've set Volar so that tags use "autoPascal", yet when I use IntelliSense to auto-import the component, it uses kebab:

https://github.com/vuejs/language-tools/assets/12532733/e0be9a96-57b7-4145-b8a0-214018bb54aa

**Comment by Shyam-Chen** [comment]
I won't encounter this issue; it's due to my VS Code configuration.

<img width="491" alt="image" src="https://github.com/vuejs/language-tools/assets/13535256/d7f5f045-6674-4786-930f-323d756d445b">

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
