### ISSUE TITLE
vue-component-meta: document improve

### ISSUE THREAD

**Issue by peterroe** [vuejs/language-tools#3807]
When I create a vue project:
```bash
$ pnpm create vue
# ...
$ pnpm i vue-component-meta
```

Then I create a new file `index.ts` just same as [vue-component-meta guild](https://github.com/vuejs/language-tools/tree/master/packages/component-meta#guide-)

I run the file use `tsx`

```bash
$ tsx index.ts
```

I get a error:

```ts
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Could not find main source file
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.10.0
```

I did't know why I get the error. And I can't find any solution to solve it.

---
Last I find（try to debug source code） I should add `*.vue` file to tsconfig.json. （the default template created by `create-vue` did'n provide it!）

```diff
{
  "compilerOptions": {
    "lib": [
      "esnext",
      "dom"
    ],
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "skipLibCheck": true,
    "allowJs": true,
    "jsx": "preserve",
    "baseUrl": "."
  },
-  "include": []
+  "include": ["./src/*.vue"]
}
```

So. Should we flag this caveat in the documentation?

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
