### ISSUE TITLE
Format issue using volar

### ISSUE THREAD

**Issue by shankhadevpadam** [vuejs/language-tools#3809]
https://github.com/vuejs/language-tools/issues/3275

I face this same issue in my vue project. Every time I format code using Volar more and more spaces are generated.

**Comment by so1ve** [comment]
Please provide a minimal reproduction.

**Comment by shankhadevpadam** [comment]
Vue: 3.0.11
Volar: 1.8.25
Prettier: 10.1.0

**Comment by so1ve** [comment]
This is not a `reproduction`. https://antfu.me/posts/why-reproductions-are-required
