### ISSUE TITLE
Vue Element Syntax Error with Arrow Functions Involving Strings

### ISSUE THREAD

**Issue by UnRealSKY** [vuejs/language-tools#3810]
Using arrow functions within Vue elements and utilizing strings inside them leads to an error, regardless of whether backticks(`), single quotes('), or double quotes(") are used.

![image](https://github.com/vuejs/language-tools/assets/45959865/9da7256f-dd76-4517-931f-207545daa3a2)
![image](https://github.com/vuejs/language-tools/assets/45959865/38495eea-3f99-48ef-9d26-9937e1f8e2f4)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
