### ISSUE TITLE
vue2 and @vue/ composition-api cross-component props type-checking not work

### ISSUE THREAD

**Issue by zhangyahan** [vuejs/language-tools#3813]
I defined a prop of type `string` using `PropType` in the component
![image](https://github.com/vuejs/language-tools/assets/46292088/5fb7d7f6-c2d0-4b51-a7be-a62648a0f8b7)
But when I pass in a value of type 'number' when using it, there is no error message displayed.
![image](https://github.com/vuejs/language-tools/assets/46292088/82d5ede5-49f5-40ec-a6d3-69da0efcbf31)
![image](https://github.com/vuejs/language-tools/assets/46292088/24a51f1b-a250-426f-bf1e-a57d7655e1e9)

Volar: 1.8.25
Vue: 2.6.14
@vue/runtime-dom: ^3.3.13
@vue/composition-api: ^1.7.2

Do you have any suggestions that can help me?

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by zhangyahan** [comment]
Sure, I'll upload a minimal reproduction later

**Comment by rchl** [comment]
Have you enabled `strictTemplates` like in https://github.com/vuejs/language-tools/blob/master/test-workspace/tsc/vue3_strictTemplate/tsconfig.json ?

**Comment by zhangyahan** [comment]
@rchl Thank you, this setting solves the issue of my cross component props type checking not work
