### ISSUE TITLE
在新建.vue 文件后 volar 插件不生效

### ISSUE THREAD

**Issue by yyqxjwxy** [vuejs/language-tools#3816]
Type: <b>Bug</b>

体现为 vue 组件不变色，相关组件props 提示失效等

Extension version: 1.8.26
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:16.874Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.61GB free)|
|Process Argv|--crash-reporter-id 6345dae2-f81b-45de-af97-1fdb3fac8057|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2:30926735
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by so1ve** [comment]
Please provide a minimal reproduction.

**Comment by yyqxjwxy** [comment]
> Please provide a minimal reproduction.

The specific steps are as follows: create a new folder -> create a new .vue file -> write an existing Vue component.
like this
![image](https://github.com/vuejs/language-tools/assets/17972392/7c7a256c-7f7e-49bb-9637-8649f8406e44)

**Comment by yyqxjwxy** [comment]
@so1ve

**Comment by so1ve** [comment]
No. This is not a reproduction.

https://antfu.me/posts/why-reproductions-are-required-zh

**Comment by oissevalt** [comment]
I have a similar problem and this is how it's triggered: https://github.com/vuejs/language-tools/issues/3837

**Comment by skyfish-1024** [comment]
@yyqxjwxy Have you solved this problem？

**Comment by yyqxjwxy** [comment]
> @yyqxjwxy Have you solved this problem？

not yet

**Comment by xakoy** [comment]
same. 

It's been bothering me for months. Every time need to Develop:Reload Window VsCode.

![Uploading image.png…]()

**Comment by xakoy** [comment]
> > @yyqxjwxy Have you solved this problem？
> 
> not yet

@yyqxjwxy 试试这个，我试了解决了几个月困恼的问题。

set `typescript.tsserver.experimental.useVsCodeWatcher` to `false`

https://github.com/vuejs/language-tools/issues/4424

**Comment by so1ve** [comment]
See https://github.com/vuejs/language-tools/issues/4424#issuecomment-2147318765
