### ISSUE TITLE
Commenting <use> tag doesn't work as expected

### ISSUE THREAD

**Issue by Reund0** [vuejs/language-tools#3823]
I am using Vue3 (JS format) and I am experiencing a bug with the Volar VSCode extension. When I try to comment the line that includes `<use>` in the following code snippet, the code becomes like this:

![image](https://github.com/vuejs/language-tools/assets/52788288/81afe95b-2ae4-43f9-91a2-33246d36f960)

However, if I comment the `<svg>` line first and then comment the `<use>` line, the code works as expected.

**Expected Behavior**

The code should be able to handle commenting the <use> line without being broken.

**Actual Behavior**

When I comment the <use> line, the code doesn't display correctly.

**Steps to Reproduce**

- Open a Vue3 (JS format) project in VSCode.
- Insert the following code snippet into the project:

```js
<svg class="icon w-4 h-4 stroke-3 ml-2">
  <use href="'/icons-def.svg#chevron-right'"></use>
</svg>

```

- Comment the line that includes `<use>`

**Expected Fix**

The Volar VSCode extension should be updated to handle commenting the <use> line.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
