### ISSUE TITLE
Template variables exposed in `<script lang="ts">` (without `setup`) do not exist on type `{}`

### ISSUE THREAD

**Issue by rijenkii** [vuejs/language-tools#3826]
[playground](https://play.vuejs.org/#eNp9kT9PAzEMxb+KlYVWqsrQ7WgrAeoAAyBgzHK6c68pOSfKn/akU747TqqWDsCU2O9n+T15FPfWzg8RRSWWvnHKBtA1dSspgpdiLUn11rgAI7S4VYSPhmtCCpBg60wPNzx8IwmHgjFUR13ea3gygscQbQWTKazWwHXvuwqk2KHWZgZH43QrRZpCmt5JWt6evPB+LgL2VtcBuQIYyyiklKkrRczYcWNoq7r53hviQGPmpWjYhdLoXm1QhjhVBUXJWs3bj8+lF1zE2bnf7LD5+qW/90PuSfHm0KM7oBQXLdSuw3CSNx8vOPD/IvamjZrpf8R39EbH7PGEPURq2fYVV9w+lYMo6j79ZghI/hwqG81kKrwUfJh8gL+i/9hdzBdlTlIS6RvRW7Da)

```vue
<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({ setup: () => ({ msg: "hello, world"}) });
</script>

<template>
  {{ msg }}
</template>
```

When hovering over `{{ msg }}`, following error appears:
```
Property 'msg' does not exist on type '{}'. ts(2339)
```

EDIT: When `lang="ts"` is changed to `lang="js"`, type of `msg` in template becomes `string`.

**Comment by so1ve** [comment]
![Uploading image.png…]()

**Comment by rijenkii** [comment]
:thinking: 
I think I caught a bug on the playground, as I currently have two open tabs, with identical code. One has the error, one does not:
![image](https://github.com/vuejs/language-tools/assets/5338332/c1e00ae1-2b12-40df-8a45-883b83c7c980)
![image](https://github.com/vuejs/language-tools/assets/5338332/2266a6e6-9506-46b4-8b05-199515900452)
After reloading the faulty page type fixed itself.
