### ISSUE TITLE
Syntax highlighting on GitHub doesn't work for vue when optional chaining is used

### ISSUE THREAD

**Issue by hfhchan-plb** [vuejs/language-tools#3827]
This issue exists in @vuejs/vue-syntax-highlight. See https://github.com/vuejs/vue-syntax-highlight/issues/217 for description of the bug.

**Comment by Juicetan** [comment]
+1 this has been bugging me quite a bit

**Comment by davidmatter** [comment]
@johnsoncodehk should linguist point to the tmlanguage definition of this repo? Seems https://github.com/vuejs/vue-syntax-highlight is 5 years behind. @hfhchan-plb @Juicetan feel free to create a PR at https://github.com/vuejs/vue-syntax-highlight to update it with https://github.com/vuejs/language-tools/blob/master/extensions/vscode/syntaxes/vue.tmLanguage.json

**Comment by yuichkun** [comment]
> @johnsoncodehk should linguist point to the tmlanguage definition of this repo? Seems https://github.com/vuejs/vue-syntax-highlight is 5 years behind. @hfhchan-plb @Juicetan feel free to create a PR at https://github.com/vuejs/vue-syntax-highlight to update it with https://github.com/vuejs/language-tools/blob/master/extensions/vscode/syntaxes/vue.tmLanguage.json

FYI: I made a [PR](https://github.com/github-linguist/linguist/pull/7086) on linguist and it's approved now. They won't ship it until the next release though
