### ISSUE TITLE
Support for Vue v3.4 v-bind shortand syntax 

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/language-tools#3830]
In Vue v3.4, it is possible to write:

```vue
<script setup>
import { ref } from 'vue'

const disabled = ref(true)
</script>

<template>
  <button :disabled>Log in</button>
</template>
```

But `vue-tsc` throws with:

```
error TS2322: Type '{}' is not assignable to type 'Booleanish | undefined'.

26       <button :disabled>Log in</button>
                 ~~~~~~~~~

  ../node_modules/.pnpm/@vue+runtime-dom@3.4.0-rc.3/node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:411:5
    411     disabled?: Booleanish;
            ~~~~~~~~
    The expected type comes from property 'disabled' which is declared here on type 'ButtonHTMLAttributes & ReservedProps'
```

See the repro on the [playground](https://play.vuejs.org/#eNqNUU1PwkAQ/SubXtSEdk3wRJCghoPGqFGPeyntAIvdj8xOgYT0vzttASuo8bY7783Mm/e20Y33yaqEaBANQ4bakwhApR8pq413SGIrEGaiEjN0Rpwx9UxZZTNnA4lch3RaQC6ua9I5YQkXyg5lO4ln8IfA+CIl4J8Qw2lJ5KwY7DtHj24uNLe0AJOGstMR9aJWRmxSnyyDsyx0W09SOyCoaCCaSl1jefVfRQsiHwZSZrnlthwKvcLEAknrjRwzTWJpSRuIc2fG/eQquYwxS/qShVEXSyCYeIpuHQB5kop6nV2SiyvAGMHmgID/3X3UdrL/CD/RUEuolK3YHgocxUzPj8zJnPG6AHz2pDmqbyalReHWD02tTuxwULaA7OOH+jJs2sNeEBplHRMoxTlQC0/enmDD7wNoXF4Wu0B+AV8huKKsNba029LmLLvDa9TeN1lrO38Pkw2BDfujaqGNGw2/CeXuj9O/5PaT/sHF6hMtaAZK)

**Comment by bodograumann** [comment]
Yes please. To be honest I am a bit disappointed that this was released as a new stable feature with [barely](https://github.com/vuejs/vue-eslint-parser/issues/212), [any](https://github.com/vuejs/eslint-plugin-vue/issues/2355) support in the tooling.

In addition to the problem noted above, there are more errors, when using multi-word identifiers. E.g. `<button :is-disabled>` is interpreted as `<button v-bind:is-disabled="is-disabled">` by vue-tsc, instead of `<button v-bind:is-disabled="isDisabled">`.

**Comment by yoshi-pi** [comment]
Even without TypeScript, I'm getting an error message like **v-bind is missing expression. vue(34).** Does language-tools generate this error? If it does, could you please fix it?
<img width="789" alt="スクリーンショット 2024-01-12 16 02 27" src="https://github.com/vuejs/language-tools/assets/19358565/abb16ca9-845a-4a7a-93c8-64a4cc5cacd6">

**Comment by so1ve** [comment]
Because our support for v-bind shorthand has not landed yet.

**Comment by AndrewBogdanovTSS** [comment]
Hi guys, any update on this one?

**Comment by kevsommer** [comment]
Are there any new updates on this? It looks like PR #3831 should be able to solve this. Can we expect it to to be merged soon?

**Comment by so1ve** [comment]
I've implemented the basic functionality, but the mappings (highlight) are inaccurate. I can pack a vsix bundle if you need.

**Comment by rocketdv** [comment]
Any update on this?

**Comment by razvaniacob** [comment]
Still nothing?

**Comment by EyalRazNadiv** [comment]
this is, literally, the only thing that prevents me from using this feature :/

**Comment by yakir-reznik** [comment]
Would really love to see this fixed. ✌️

**Comment by JoniLieh** [comment]
Finally working, Version 2.0 supports this, no more takeover-mode needed either, uninstall Volar :)

**Comment by liuzw2579** [comment]
support camelCase, not support kebab-case
![image](https://github.com/vuejs/language-tools/assets/30503937/257e50ca-c3cf-4441-85ab-c8bff84af7f6)
![image](https://github.com/vuejs/language-tools/assets/30503937/63790c6c-9a5d-4c9e-b562-4f61ff5af310)

**Comment by benkroeger** [comment]
because you can not have kebab-case variable names in JavaScript

**Comment by liuzw2579** [comment]
> because you can not have kebab-case variable names in JavaScript

but this can run in .vue

![image](https://github.com/vuejs/language-tools/assets/30503937/aa9d5343-fe3f-4dfb-922e-3615a1f97c6d)
![image](https://github.com/vuejs/language-tools/assets/30503937/d379594b-fc6b-40a4-abf6-92bb644eee0e)

**Comment by benkroeger** [comment]
vue shorthand is meant to bind your variables with their own name... thus, in shorthand you can only use valid javascript variable names. if you want to use kebab attributes, you can not use shorthand...

**Comment by reneroth** [comment]
> because you can not have kebab-case variable names in JavaScript

It actually does work, vue converts it internally. I do agree though that it's... not optimal 🥴

**Comment by liuzw2579** [comment]
> > vue shorthand is meant to bind your variables with their own name... thus, in shorthand you can only use valid javascript variable names. if you want to use kebab attributes, you can not use shorthand...
> 
> It actually does work, vue converts it internally. I do agree though that it's... not optimal 🥴

eslint plugin vue rule recommend attribute hyphenation 

https://eslint.vuejs.org/rules/attribute-hyphenation.html

![image](https://github.com/vuejs/language-tools/assets/30503937/73c81909-aba1-462c-9a8e-c4076f9de840)
