### ISSUE TITLE
Custom components broken with vue-tsc/language tools since v1.8.24

### ISSUE THREAD

**Issue by jfrs** [vuejs/language-tools#3832]
I've just noticed while starting a new project that local components are all typed as `(property) Test: any` and no type checking is done.
I can still click on the component to go to its definition, but even using non imported components does not raise any errors.  Third party components like Vuetify are fine. 

I tracked it to v1.8.24, v1.8.22 is working as expected.

Minimal reproduction repo https://github.com/jfrs/test-repro, `pnpm i && pnpm build`.

**Comment by angelov-a** [comment]
Having the same issue. It's caused by
```
"noPropertyAccessFromIndexSignature": true,
```

**Comment by ole-thoeb** [comment]
This is really bad for event handlers. Because of this `vue-tsc` fails with `Parameter 'e' implicitly has an 'any' type.` when using an arrow function.
```vue
<CustomComponent @customEvent="e => {}"/>
                               ^ error... 
```

**Comment by johnsoncodehk** [comment]
@jfrs I no longer have access to https://github.com/jfrs/test-repro so can't add a test case for this, it would be nice if you could submit a PR to add a test at https://github.com/vuejs/language-tools/tree/master/test-workspace/tsc/vue3.

**Comment by johnsoncodehk** [comment]
Yes it should be https://github.com/vuejs/language-tools/tree/master/test-workspace/tsc/noPropertyAccessFromIndexSignature.
