### ISSUE TITLE
Not ignoring vue inside nested code blocks in markdown

### ISSUE THREAD

**Issue by brc-dd** [vuejs/language-tools#3833]
Try something like this in a markdown file:

`````
````md
```html
<ul>
  <li v-for="todo in todos" :key="todo.id">
    {{ todo.text }}
  </li>
</ul>
```
````
`````

<img width="1121" alt="image" src="https://github.com/vuejs/language-tools/assets/40380293/226934d4-bf2c-418e-ae73-f6d62a62acf7">

Working fine with one-level code blocks.

I'm on `vue-tsc@1.8.27`

**Comment by so1ve** [comment]
Straightforward to fix :)
