### ISSUE TITLE
model.value does not exist on type 'abc'. ts(2339) (vue 3.4.3 - VSCode)

### ISSUE THREAD

**Issue by hoanghadu** [vuejs/language-tools#3835]
I am using a new API defineModel of vue 3.4.3 with an ref Object. In the child component, the VSCode Volar indicate that `Property 'value' does not exist on type 'ProductInOrder' . ts(2339) `

Parent:
```
<script setup lang="ts"
import type { ProductInOrder } from '~/types/product-in-order'
const newCustomProductInOrder = ref({} as ProductInOrder)
</script>
<template>
<div>
<ProductCustom v-model="newCustomProductInOrder" />
</div>
</template>
```

ProductCustom component:
![test](https://github.com/vuejs/language-tools/assets/5095333/f67604a3-f7d4-452a-9e11-89ca0d40d86f)

VS code, Volar v1.8.27, nuxt 3.9.0, vue 3.4.3

**Comment by so1ve** [comment]
What is `ProductInOrder`

**Comment by vaemusic** [comment]
maybe you shuld use 
```js
const model = defineModel<ProductInOrder>()
```

**Comment by hoanghadu** [comment]
> ```js
> <ProductInOrder>
> ```

It's an interface

```js
export interface ProductInOrder {
  name: string
  img: string
  url: string
  price: number 
  ...
  }
```

**Comment by hoanghadu** [comment]
> maybe you shuld use
> 
> ```js
> const model = defineModel<ProductInOrder>()
> ```

Thank you, but it still doesn't work

**Comment by so1ve** [comment]
Yes you should use https://github.com/vuejs/language-tools/issues/3835#issuecomment-1873594056
