### ISSUE TITLE
Component Highlight Matching Issue 

### ISSUE THREAD

**Issue by xinxinhe1810** [vuejs/language-tools#3842]
<img width="394" alt="image" src="https://github.com/vuejs/language-tools/assets/25220472/a4d3f303-d704-4892-80b7-41fc69e4edeb">

The next token obtained by the `html/languageService` scanner for the `s-c-feature` is `2`.  

https://github.com/microsoft/vscode-html-languageservice/blob/1030c1eef51438cb674482338bf4ddfbb1fc4289/src/parser/htmlScanner.ts#L189C13-L189C13)s://github.com/microsoft/vscode-htm`-`a  uageservice/blob/1030c1eef51438cb674482338bf4ddfbb1fc4289/src/parser/htmlScanner.ts#L189C13-L189C13

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
