### ISSUE TITLE
Error message in<view>tag prompt in vscode editor

### ISSUE THREAD

**Issue by gulang12** [vuejs/language-tools#3843]
Open the file using the vscode editor and receive an error message
![Snipaste_2024-01-08_21-23-39](https://github.com/vuejs/language-tools/assets/26455814/9d5265c2-d936-47e1-a9f0-86928a450ff7)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
