### ISSUE TITLE
Pug support missing

### ISSUE THREAD

**Issue by FeatureSpitter** [vuejs/language-tools#3852]
Dear Volar team,

I couldn't find a way to have Pug working with Volar and Vuejs 3 in VSCode.

The autocomplete doesn't work with Pug, I've tried multiple plugins and none did the trick.

I was wable to have syntax highlighting etc. But the autocomplete with Pug is far worse than the one with Html.

What am I missing? Or there really is no way to take leverage of Volat's autocomplete with Pug?

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/tree/master/packages/language-plugin-pug

**Comment by FeatureSpitter** [comment]
> https://github.com/vuejs/language-tools/tree/master/packages/language-plugin-pug

Doesn't work with auto complete. Compare the auto complete you get with html.

**Comment by Rekwian** [comment]
Hello, support doesn't work in vscode for me too.
var and import are not recognized in `<template>`, but inside `<script>`, yes.
I uninstalled the Volar plugin and can't reinstall it. So I have to work without model recognition :'(.

![image](https://github.com/vuejs/language-tools/assets/31690329/a3ed1915-e3c4-4ffa-a45d-ebfec09956dd)

**Comment by hard25670559** [comment]
Here is my current emergency plan:

1. Open Visual Studio Code.
2. Locate your tsconfig.json file.
3. In the tsconfig.json file, find and remove the vueCompilerOptions.plugins parameter.
4. Check if the highlighting works successfully.
5. If not, reload the Visual Studio Code window.

tsconfig.json
```json
{
  "vueCompilerOptions": {
  },
  .....
}
```

**Comment by Rekwian** [comment]
@hard25670559 
> Here is my current emergency plan:
> 
>     1. Open Visual Studio Code.
> 
>     2. Locate your tsconfig.json file.
> 
>     3. In the tsconfig.json file, find and remove the vueCompilerOptions.plugins parameter.
> 
>     4. Check if the highlighting works successfully.
> 
>     5. If not, reload the Visual Studio Code window.
> 
> 
> tsconfig.json
> 
> ```json
> {
>   "vueCompilerOptions": {
>   },
>   .....
> }
> ```

Not work for me :(

**Comment by grandsong** [comment]
I updated @vue/language-plugin-pug to the latest version 2.0.6, and my VS Code handles pug codes well now.

**Comment by johnsoncodehk** [comment]
Pug template is supported via @vue/language-plugin-pug (including autocomplete), if it doesn't work for you it's usually probably a project configuration issue, if you provide a reproduction we will look into it.
