### ISSUE TITLE
Strange formatter bug

### ISSUE THREAD

**Issue by Vap0r1ze** [vuejs/language-tools#3854]
I came across this snippet that causes the `<code>` children *and* closing tag (`</code>`) to increase in indendation **each** format
```vue
<template>
    <code style="display:flex;max-width:20em;text-wrap:nowrap">
        <span>Stuff</span>
    </code>
</template>
```

I'm on Windows with Volar `v1.8.27` and I'm also using the same versioned typescript plugin

**Comment by andriasmelianus** [comment]
Hi, i encountered this bug too.
As the alternative, we can use ESlint as described in this article: https://dev.to/tao/adding-eslint-and-prettier-to-nuxt-3-2023-5bg, meanwhile they fixing this.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
