### ISSUE TITLE
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements'

### ISSUE THREAD

**Issue by init-center** [vuejs/language-tools#3856]
After creating the project with `pnpm create vite my-vue-app --template vue-ts`,install `@vitejs/plugin-vue-jsx`：
```json
{
  "name": "test-vue",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.3.11"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.5.2",
    "@vitejs/plugin-vue-jsx": "^3.1.0",
    "typescript": "^5.2.2",
    "vite": "^5.0.8",
    "vue-tsc": "^1.8.25"
  }
}
```
```js
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), vueJsx()],
})
```
write jsx to get the following error:

<img width="899" alt="image" src="https://github.com/vuejs/language-tools/assets/21151034/d479f976-09e8-4692-bfce-63aebfea5ff3">

Volar version: v1.8.27

How can I solve this problem?

**Comment by xWTF** [comment]
It's caused by

**Comment by so1ve** [comment]
You should add `vue/jsx` to your tsconfig.

**Comment by init-center** [comment]
> According to the [vue guide](https://vuejs.org/guide/extras/render-function.html#jsx-type-inference), it's caused by this change:
> 
> > Starting in Vue 3.4, Vue no longer implicitly registers the global JSX namespace
> 
> Add these lines to your `tsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "jsx": "preserve",
>     "jsxImportSource": "vue"
>   }
> }
> ```

Thank you for your help.

**Comment by eric-gitta-moore** [comment]
The issue with `JSX.IntrinsicElements` has been resolved, but another problem has emerged.

```
Type '{ className: string; }' is not assignable to type 'HTMLAttributes & ReservedProps'.
  Property 'className' does not exist on type 'HTMLAttributes & ReservedProps'.ts(2322)
```

![Image](https://github.com/user-attachments/assets/c22358bf-793f-49e8-a5e2-daed4a810078)

It can be seen that the `class` property is defined, but `className` is not.

```tsx
// file: /node_modules/.pnpm/@vue+runtime-core@3.5.13/node_modules/@vue/runtime-core/dist/runtime-core.d.ts
/**
 * Default allowed non-declared props on component in TSX
 */
export interface AllowedComponentProps {
    class?: unknown;
    style?: unknown;
}
```
