### ISSUE TITLE
Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by woodbrettm** [vuejs/language-tools#3858]
Hi there:

Following up from #1816. I just started a new test project for digging into Nuxt. And I'm getting the heap limit allocation failed errors as well. I'm using docker on WSL2.

One thing I noticed is without setting `vue.server.maxOldSpaceSize` in `settings.json`, the size of memory usage it would get up to is around 4GB before failing, I'm guessing that might be some defaults.

Edit: Using Vscode

Thanks to @harrikauhanen for the note on `vue.server`, not `volar.vueserver...`

I changed the settings to `vue.server.maxOldSpaceSize: 8096` to see if that would do it. At first it worked. But I saw memory usage grow over the course of 10-15 seconds until all 8GB were used up.

My entire WSL2 instance was using up 11GB of RAM total before the vue semantic server started crashing : (

```shell
<--- Last few GCs --->

[1013:0x5b087c0]    66033 ms: Mark-sweep 8089.2 (8235.2) -> 8084.5 (8238.7) MB, 1626.7 / 0.0 ms  (average mu = 0.755, current mu = 0.141) allocation failure; scavenge might not succeed
[1013:0x5b087c0]    68810 ms: Mark-sweep 8093.7 (8239.7) -> 8088.5 (8242.5) MB, 2727.0 / 0.0 ms  (average mu = 0.506, current mu = 0.018) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7d990 node::Abort() [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 2: 0xa88a17  [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 3: 0xd76390 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 4: 0xd76737 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 5: 0xf540d5  [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 6: 0xf6654d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 7: 0xf40c9e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 8: 0xf42057 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 9: 0xf234ba v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
10: 0x12ea97f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
11: 0x1727339  [/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
[Error - 1:57:51 AM] Server process exited with signal SIGABRT.
[Info  - 1:57:51 AM] Connection to server got closed. Server will restart.
true

```

**Comment by woodbrettm** [comment]
I restarted a new project, and I think the issue was folders like node_modules weren't excluded. Working fine now.

**Comment by cernymatej** [comment]
@woodbrettm I am currently facing the same issue. How exactly did you find out which files to exclude?
Nuxt already generates excludes for `node_modules` 😕
```json
  "exclude": [
    "../node_modules",
    "../../../node_modules",
```

**Comment by woodbrettm** [comment]
@cernymatej IIRC I simply regenerated a project from scratch and it worked the second time without issue for some reason, and hadn't had a problem since. Though I'm not using Nuxt much atm. Did you try using wildcards? `**/node_modules/**`, or `**/node_modules`? Only thing I can think of.

**Comment by cernymatej** [comment]
I see. Well, this started happening in quite a big project of mine like 2-3 weeks ago.
I have tried multiple ways of excluding node_modules and couldn't see any difference. The only thing that helped was increasing the memory limit to 8GB. However, I'm not very happy about this workaround as I know it worked fine before.

Thank you for your reply!
