### ISSUE TITLE
Volar adds closing HTML tags in an infinite loop

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuejs/language-tools#3862]
Hello,

Very often when I cut the closing tag and then paste it - Volar will go crazy and start adding the same closing tag in an infinite loop.

Please see (and listen) detailed reproduction video here:

https://github.com/vuejs/language-tools/assets/7756211/0e17bbeb-ca36-4708-815a-99ff6450efcd

The project itself is bare-bone `npm create vue@latest` with JSX.

All other extensions were disabled.

I'm using Vue.volar v1.8.27
In VS Code:
Version: 1.86.0-insider (user setup)
Commit: 0b571a26e213bf1ec6266e37152ced80c006bd1e
Date: 2024-01-18T05:36:10.559Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
