### ISSUE TITLE
Neovim: Volar format code auto add space between script and template tags

### ISSUE THREAD

**Issue by hoanghoa12345** [vuejs/language-tools#3863]
Hi there,

I use Vue-language-server (volar) on **Neovim**, if I try to format code using **Volar** it auto adds a new line between the template tag and the script tag, which auto increments if I continue formatting code.

![image](https://github.com/vuejs/language-tools/assets/44923253/f181bd13-4d74-405c-b52a-73d758f0e1df)

```bash
 vue-language-server volar
      ⚡ Explore high-performance tooling for Vue.
      
      installed version 1.8.27                                 
      homepage          https://github.com/johnsoncodehk/volar 
      languages         Vue                                    
      categories        LSP                                    
      executables       vue-language-server.cmd  
```
Here are some info:
Volar version: v1.8.27
Neovim version: v0.9.2
Windows 10

How can I solve this problem?

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.

**Comment by hoanghoa12345** [comment]
I updated to version 2.0.26, and the issue has been fixed. If I format code, no new line is added. Thanks @davidmatter !
