### ISSUE TITLE
Highlighting is not working well with lang="ts"

### ISSUE THREAD

**Issue by tzk-hoey** [vuejs/language-tools#3864]
![with-ts](https://github.com/vuejs/language-tools/assets/34564166/7ee2bd03-cd41-4c8d-b6f6-218433ededfd)

![without-ts](https://github.com/vuejs/language-tools/assets/34564166/cb6172fa-fd5e-48a5-beaf-790534ffd4e9)

**Comment by so1ve** [comment]
Please post your full component.

**Comment by tzk-hoey** [comment]
> Please post your full component.

Actually, I don't think it is caused by my code. It just happens to every project I open with VSCode, even those I've just created.

While the highlighting in *.ts files and the other features in *.vue files are working normally.

The typescript version is 5.3.3, volar takeover mode. VSCode and the extensions are up to date. No further configurations.

an exemple of component
```vue
<script lang="ts" setup>
import TestFoo from './test-foo.vue'
const widgets = new Map<string, any>()
widgets.set('foo', TestFoo)
const config = [
  {
    vertex: [2, 4, 5, 7],
    name: 'foo'
  },
  {
    vertex: [4, 8, 10, 12],
    name: 'foo'
  }
]
</script>

<template>
  <div class="ctmzbgrid-frame">
    <div class="ctmzbgrid-wrapper">
      <component
        v-for="elem in config"
        :key="elem.name + '-' + elem.vertex.join('-')"
        :is="widgets.get(elem.name)"
        :style="{
          gridArea: elem.vertex.join(' / ')
        }"
      ></component>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.ctmzbgrid-frame {
  .ctmzbgrid-wrapper {
    display: grid;
    grid: {
      template-columns: repeat(12, 1fr);
      template-rows: repeat(12, 1fr);
    }
    width: 100%;
    height: 100%;
  }
}
</style>
```

**Comment by so1ve** [comment]
![image](https://github.com/vuejs/language-tools/assets/58381667/7d51f380-f4d8-4ef9-96e1-33b65e5af40e)

Sorry, but I can't reproduce on my machine

**Comment by AisonSu** [comment]
In fact, I encountered the same issue before, and I made the following attempts:
1. Opened the code of other projects, such as JD's nutui, but Volar's code highlighting did not work.
2. Closed all extensions and only opened Volar, yet Volar's code highlighting still did not work.
3. Rolled back to a previous version of Volar, but the code highlighting did not work.
4. Updated my VSCode or rolled back the VSCode version, but Volar's code highlighting still did not work.
5. Changed my Node.js version, but Volar's code highlighting did not work.
6. Changed to a different computer and repeated the above steps.
In the end, I found that the Extension I should disabled was "TypeScript and JavaScript Language Features," not "TypeScript Language Basics."

**Comment by tzk-hoey** [comment]
> In fact, I encountered the same issue before, and I made the following attempts:
> 
> 1. Opened the code of other projects, such as JD's nutui, but Volar's code highlighting did not work.
> 2. Closed all extensions and only opened Volar, yet Volar's code highlighting still did not work.
> 3. Rolled back to a previous version of Volar, but the code highlighting did not work.
> 4. Updated my VSCode or rolled back the VSCode version, but Volar's code highlighting still did not work.
> 5. Changed my Node.js version, but Volar's code highlighting did not work.
> 6. Changed to a different computer and repeated the above steps.
>    In the end, I found that the Extension I should disabled was "TypeScript and JavaScript Language Features," not "TypeScript Language Basics."

Great, case closed. I don't even know there is a separated TypeScript built-in, with all the docs talking about searching @builtin javascript.
