### ISSUE TITLE
Latest volar LSP version crashes on neovim. Installed with mason

### ISSUE THREAD

**Issue by ynsssss** [vuejs/language-tools#3868]
neovim version: 0.9.5
volar version: 1.8.27
OS: ubuntu 20.04
LspLog error: 
`[ERROR][2024-01-20 14:14:40] .../vim/lsp/rpc.lua:734	"rpc"	"/home/yunus/.local/share/nvim/mason/bin/vue-language-server"	"stderr"	"/home/yunus/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/language-server/node.js:63\n                    return fs.readFileSync((0, exports.uriToFileName)(uri), { encoding: encoding ?? 'utf-8' });\n                                                                                                  ^\n\nSyntaxError: Unexpected token '?'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/yunus/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/out/nodeServer.js:3:16)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n`
I saw similar issue at https://github.com/vuejs/language-tools/issues/1978 . but I did not see any solution there.

**Comment by so1ve** [comment]
I'm not familiar with neovim. Does `mason.nvim` use node.js? What's your node.js version?

**Comment by ynsssss** [comment]
node version is 21.5.0, mason uses npm to install some packages(volar also).

**Comment by so1ve** [comment]
I'm not sure about what happened, but it seemed that your node.js doesn't understand `??` token. Can mason select which node.js to use?

/cc @yaegassy

**Comment by ynsssss** [comment]
Ok, turned out mason used apt's nodejs(v12) library instead of node v21.5.0 installed with nvm. Updated node manually, that fixed the issue. Ty
