### ISSUE TITLE
The code prompt is repeated several times in the vue file

### ISSUE THREAD

**Issue by OuZuYu** [vuejs/language-tools#3871]
Like this
The HTML file is normal, only the Vue file has issues.
I disabled all the other plugins and the problem still persists

![image](https://github.com/vuejs/language-tools/assets/26338853/d48bc515-f939-4284-a20c-7aaae7c9de00)
![image](https://github.com/vuejs/language-tools/assets/26338853/6b7575c6-3749-4a38-967e-63ef3cf8a71a)

My vscode version is 1.85.2
![image](https://github.com/vuejs/language-tools/assets/26338853/b12580c3-f154-4723-8a91-f5d3b7ced037)
![image](https://github.com/vuejs/language-tools/assets/26338853/46666bf7-4d91-4374-aa38-87765bd89047)

**Comment by ker264** [comment]
Same thing. For me it appears in App.vue, but works fine in different component in same project (HelloWorld.vue)
![image](https://github.com/vuejs/language-tools/assets/31769387/3f59d843-c604-4ea5-abbc-f47e8c6fd98f)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
