### ISSUE TITLE
VSCode plugin: Eager autocompletion on functions results in double parenthesis

### ISSUE THREAD

**Issue by jakeparis** [vuejs/language-tools#3873]
When I type a known function, the plugin is automatically adding parenthesis. For example if I type
`console.log(`
I end up with
`console.log(()`
because the plugin is automatically adding the parenthesis. I am _not_ typing a `tab` or `enter` key. I simply type the function name and the next key I type is `(`. 

I only experience this in .vue files. 
I have experienced this on any built-in function like `console.debug` or `window.addEventListener`, but not on my own functions (even in the same file). 

There's really no point to this behavior, as typing a `tab` or `enter` key will _also_ autocomplete the parenthesis, and is much more expected. 

Could you either fix this bug, or, if this intended, please provide a way to disable this behavior? This slows me down _so much_. 

I already have the **Auto Insert Parenthesis** setting turned _off_.
I should also note that I am _not_ using TypeScript.

**Comment by so1ve** [comment]
2.0 will fix this issue. The root cause is v1.x not respecting `typescript/javascript.*` settings.
