### ISSUE TITLE
Cannot refactor in monorepo

### ISSUE THREAD

**Issue by baixiaoyu2997** [vuejs/language-tools#3876]
[test DEMO](https://codesandbox.io/p/devbox/z678p2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrsnnz3k00063b6hr9pfju1h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrsnnz3j00023b6h8gnopdwo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrsnnz3k00033b6h88nmws40%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrsnnz3k00053b6hra6ntfre%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrsnnz3j00023b6h8gnopdwo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsnnz3j00013b6h1sh0mtiw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrsnnz3j00023b6h8gnopdwo%2522%252C%2522activeTabId%2522%253A%2522clrsnnz3j00013b6h1sh0mtiw%2522%257D%252C%2522clrsnnz3k00053b6hra6ntfre%2522%253A%257B%2522id%2522%253A%2522clrsnnz3k00053b6hra6ntfre%2522%252C%2522activeTabId%2522%253A%2522clrsnsk4000433b6hj9exc6er%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrsnsk4000433b6hj9exc6er%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrsnnz3k00033b6h88nmws40%2522%253A%257B%2522id%2522%253A%2522clrsnnz3k00033b6h88nmws40%2522%252C%2522activeTabId%2522%253A%2522clrsnsfk5002h3b6hem1ziepv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clrsnsfk5002h3b6hem1ziepv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

when i refactor code in `packages/deorderbook-base/composables/useTest.ts`,  change `cc` to `dd`
![image](https://github.com/vuejs/language-tools/assets/9149999/d01e8996-6464-4439-b35a-1bbf04376c29)
code in `app.vue` not change
![image](https://github.com/vuejs/language-tools/assets/9149999/cbf3c31d-26eb-4316-b0c4-6ce7920aa231)

i'm using tokerover mode, and `volar` version is `v1.8.27`

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
