### ISSUE TITLE
Nuxt3 with monorepo, when run typecheck, packages tsconfig is not respected

### ISSUE THREAD

**Issue by baixiaoyu2997** [vuejs/language-tools#3878]
## Describe
When I run typecheck in the home package in monorepo, it displays type errors in the sdk package, which seems like vue-tsc has not read the tsconfig file in sdk, or vue-tsc should not verify the types in sdk?
![image](https://github.com/vuejs/language-tools/assets/9149999/f8bf211e-72cf-478c-b9c9-d6c736841759)

## Reproduce
[demo](https://codesandbox.io/p/devbox/youthful-payne-mxc7j9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrugkfpp00073b6hqim044sb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrugkfpp00023b6ht8cj6ywf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrugkfpp00043b6h1v39eoni%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrugkfpp00063b6hgfolut5f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrugkfpp00023b6ht8cj6ywf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrugkfpo00013b6h396llqvw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrugkfpp00023b6ht8cj6ywf%2522%252C%2522activeTabId%2522%253A%2522clrugkfpo00013b6h396llqvw%2522%257D%252C%2522clrugkfpp00063b6hgfolut5f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrugkfpp00053b6hv7nuzbxp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clrugkfpp00063b6hgfolut5f%2522%252C%2522activeTabId%2522%253A%2522clrugkfpp00053b6hv7nuzbxp%2522%257D%252C%2522clrugkfpp00043b6h1v39eoni%2522%253A%257B%2522id%2522%253A%2522clrugkfpp00043b6h1v39eoni%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrugmgtx006l3b6hy6kndesl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrugmh0k0071dph8cilidtmq%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrugmgtx006l3b6hy6kndesl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

run `pnpm home typecheck`

**Comment by xjccc** [comment]
Try change this config in `nuxt.config.ts`

```
export default defineNuxtConfig({
  extends: ['@test/sdk']
})
```
