### ISSUE TITLE
Volar Labs 2.0 doesn't work with Volar

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#3880]
Volar Labs v2.0.0
Vue Language Features (Volar) v1.8.27

![Screenshot 2024-02-01 at 13 40 06](https://github.com/vuejs/language-tools/assets/153197/ef0d5568-ba00-4291-a340-5f518268cae7)

**Comment by so1ve** [comment]
It works with main branch.

**Comment by rchl** [comment]
Sure but the latest released versions of both extensions don't work with each other. It's possibly to force Volar Labs to older version but is there really no better way of handling it (on the vscode extension side, I suppose)?

**Comment by so1ve** [comment]
Vue Language Tools v1.8.27 uses volar.js v1 but Vue Language Tools v2 uses volar.js v2. So they are not compatible with each other

**Comment by rchl** [comment]
I get your point but vscode is not like npm where you get to decide whether to upgrade to next major version or not. It just updates automatically and breaks thing. One thing is that it's a breaking change for the user and also it's not clear  why it broke since there is no notes or anything that say that it's not compatible with VLT 1.x. There is this message that says that it's not compatible which you can see if you make the panel width very wide but it can be missed easily.

That said, I get that it's a power user extension and maybe it's not that important that it breaks without warning but I still wanted to point it out in case there are better ways of handling it.

I don't know vscode extensions ecosystem but I though that there might be some ways for extensions to indicate compatibility with other extensions to make it more obvious that there is incompatibility and how it could be resolved. If nothing can be improved then feel free to close this issue.

**Comment by so1ve** [comment]
Oh, got your point.

> some ways for extensions to indicate compatibility with other extensions

This doesn't happen on VSCode side. https://github.com/vuejs/language-tools/commit/fc48ce6d10818bda3f86b4dd7abd3eb54c7a878a#diff-3c2b2dc57146f5d52dc996ede798d28b5e6163dcd75762900a25803398a099edL149 Volar uses its own way to indicate the compatible Volar Labs version

**Comment by rchl** [comment]
I suppose there are more important things to work on.
