### ISSUE TITLE
Neovim: Does Volar not provide suggestions for Vue's template?

### ISSUE THREAD

**Issue by chaozwn** [vuejs/language-tools#3884]
Currently, Volar works very well on Neovim, but for some reason, component completion suggestions in HTML only appear for components that are imported in the setup.

https://github.com/vuejs/language-tools/assets/51357674/ce688ef8-56b8-4fce-81f7-ae6fe6abcd2b

**Comment by KermanX** [comment]
Does this bug still happen in the latest version?

**Comment by DrWalrus1** [comment]
I still have this issue, has a solution been found?

**Comment by RayGuo-ergou** [comment]
I remembered this have been resolved long time ago, @DrWalrus1 can you confirm your LSP is up to date.

Here's the screenshot using `2.1.10`

![image](https://github.com/user-attachments/assets/1098dac1-bf75-466e-a5b0-c8fab4b6151c)

**Comment by DrWalrus1** [comment]
@RayGuo-ergou 
Can confirm I am working with `2.1.10`

Heres a screenshot
<img width="1331" alt="Screenshot 2024-12-09 at 12 35 14 pm" src="https://github.com/user-attachments/assets/36809a73-712e-4c77-a7fb-e0d682cd83e8">


Would you also be able to send you lspconfig settings for volar and ts_server as well? I'm new to setting this stuff up so it could be config too

**Comment by chaozwn** [comment]
> @RayGuo-ergou Can confirm I am working with `2.1.10`
> 
> Heres a screenshot <img alt="Screenshot 2024-12-09 at 12 35 14 pm" width="1331" src="https://private-user-images.githubusercontent.com/50015267/393666219-36809a73-712e-4c77-a7fb-e0d682cd83e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTE2OTYsIm5iZiI6MTczMzcxMTM5NiwicGF0aCI6Ii81MDAxNTI2Ny8zOTM2NjYyMTktMzY4MDlhNzMtNzEyZS00Yzc3LWE3ZmItZTBkNjgyY2Q4M2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAyMjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5Y2Q5YzFlZTIzNjRhYzM5MDI5ODU0MWVhYTVmZmU5YjdlZmVlNTM2NjI3YmEzMWI3NzRkZmI5NmI1ZjgxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wiLWMdhuLzhxPjicDwMGTnaKYzMm1rZNlc47ccyOgo4">
> 
> Would you also be able to send you lspconfig settings for volar and ts_server as well? I'm new to setting this stuff up so it could be config too

The reality is that volar is working very well.

**Comment by chaozwn** [comment]
> @RayGuo-ergou Can confirm I am working with `2.1.10`
> 
> Heres a screenshot <img alt="Screenshot 2024-12-09 at 12 35 14 pm" width="1331" src="https://private-user-images.githubusercontent.com/50015267/393666219-36809a73-712e-4c77-a7fb-e0d682cd83e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTE2OTYsIm5iZiI6MTczMzcxMTM5NiwicGF0aCI6Ii81MDAxNTI2Ny8zOTM2NjYyMTktMzY4MDlhNzMtNzEyZS00Yzc3LWE3ZmItZTBkNjgyY2Q4M2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAyMjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5Y2Q5YzFlZTIzNjRhYzM5MDI5ODU0MWVhYTVmZmU5YjdlZmVlNTM2NjI3YmEzMWI3NzRkZmI5NmI1ZjgxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wiLWMdhuLzhxPjicDwMGTnaKYzMm1rZNlc47ccyOgo4">
> 
> Would you also be able to send you lspconfig settings for volar and ts_server as well? I'm new to setting this stuff up so it could be config too


https://github.com/user-attachments/assets/ab770290-6032-479e-aa1d-fc3217f6088f

**Comment by DrWalrus1** [comment]
Hi all, I must apologise, after taking a look at @RayGuo-ergou nvim config I have realised a few key mistakes in my own config. I have fixed them and now I have it working successfully. 

I'm going to link my config here in case any poor soul runs into the same situation and wants something to compare notes this
https://github.com/DrWalrus1/nvim-config/blob/649b2ec07fccb4f721066e44d17ba6ed62fab282/lua/plugins/lspconfig.lua#L195-L244

**Comment by KazariEX** [comment]
The problem should be caused by HTML completion triggered by `<` which resulted in TS completion not being triggered. It requires us to manually trigger completion after `<xxx`.

**Comment by RayGuo-ergou** [comment]
Happy to see your issue resolved.

@KazariEX I think this issue can be closed.

**Comment by AdamGaskins** [comment]
> The problem should be caused by HTML completion triggered by `<` which resulted in TS completion not being triggered. It requires us to manually trigger completion after `<xxx`.

@KazariEX I'm having this same issue. When I type my code normally, its just giving me HTML suggestions:

<img width="221" height="103" alt="Image" src="https://github.com/user-attachments/assets/a61622cc-4339-41ea-b2f0-0ede8c3aa951" />

However if I complete the brackets <>, I will get TS options (including components not imported in this file yet):

<img width="318" height="105" alt="Image" src="https://github.com/user-attachments/assets/fdf0b505-1163-43cc-8f12-9773683e2e2d" />

How did you resolve this?

**Comment by rrrrando** [comment]
I have the same issue almost. At first blink shows me components that are already imported. After i close the list and trigger it again i get the whole list. .Looks like it's the same in Vscode.
