### ISSUE TITLE
vue-tsc can't process component, when defineModel uses a Generic

### ISSUE THREAD

**Issue by max-zinn** [vuejs/language-tools#3886]
# Minimal Example

https://github.com/max-zinn/vue-tsc-minimal-example

# Description

I have a component that has a Generic `T` (see `src/GenericComponent.vue`), which defines the model based on that with `defineModel<T>();`. When I do that, I get an error from the template, that `items` does not exist anymore, but they are declared in `defineProps<Props>()`.

When I use `defineModel<string>();` (See `src/GenericComponent_working-example.vue`) everything works as expected.

I am not entirely sure if this issue is caused by volar or vue-tsc but any help is highly appreciated. I doubt its an issue on vue because the application works normally, its only the vue-tsc that complains about this.

# Error Message

```
☁  vue-tsc-minimal-example [main] ⚡  npm run vue-tsc                                    

> vue-tsc-minimal-example@1.0.0 vue-tsc
> vue-tsc --noEmit

src/GenericComponent.vue:3:24 - error TS2339: Property 'items' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{} & EnsureNonVoid<{ [K in keyof Pick<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Props & { modelValue?: T | undefined; }>, { ...; }>, DefaultKeys<...>>]: InferPropType<...>; }>> & Omit<...>; ... 10 more ...; $watch<T extends string | ((...args: any) =>...'.
  Property 'items' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{} & EnsureNonVoid<{ [K in keyof Pick<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Props & { modelValue?: T | undefined; }>, { ...; }>, DefaultKeys<...>>]: InferPropType<...>; }>> & Omit<...>; ... 10 more ...; $watch<T extends string | ((...args: any) =>...'.

3     <li v-for="item of items" :key="`${item}`">
                         ~~~~~


Found 1 error in src/GenericComponent.vue:3

```

**Comment by so1ve** [comment]
Pretty weird, this issue only occurs on vue-tsc, not the vscode plugin :)

**Comment by max-zinn** [comment]
Tbh I didn't test it on VSCode. I use Webstorm and afaik it doesn't have a volar plugin. So I rely on the terminal output. And even if webstorm would've a plugin, we have vue-tsc integrated into our build pipelines.

I don't have any deep knowledge of the codebase but can only offer to have a look into the issue once I have time for that before you guys have :)

**Comment by so1ve** [comment]
> it doesn't have a volar plugin

But you may configure it to use volar: https://blog.jetbrains.com/webstorm/2023/05/webstorm-2023-2-eap2/

**Comment by rchl** [comment]
The reason it works in vscode and not vue-tsc is that in vscode volar uses Typescript bundled with vscode (which is at 5.x.x right now) while `vue-tsc` will use 4.9.5 version from the project dependencies.

Not sure if it's still a bug in "volar" or usage of TS 5.x is a requirement for this to work...

**Comment by so1ve** [comment]
Great catch! I'd like to suggest adding `typescript.tsdk` to vscode's settings or upgrade your workspace's typescript version.

**Comment by max-zinn** [comment]
Thanks @rchl, upgrading typescript to 5.x worked. We previously had a dependency that required us to stay at 4.9.5 but it's resolved and after upgrading to 5, everything works perfectly. Thank you very much :)
