### ISSUE TITLE
Props not recognized by intellisense (options API)

### ISSUE THREAD

**Issue by mauromascarenhas** [vuejs/language-tools#3888]
## Issue

As the title states, props are not being recognized by intellisense in options API (data and computed are still working as expected). Thus, no suggestion or type inference is made.

### Prop being treated as "any"

![Screenshot showing that the "id" prop is being treated as type "any"](https://github.com/vuejs/language-tools/assets/7539096/9c3402cd-e99d-4f48-a26d-5ae212d0d8a7)

### Prop is not recognized/recommended by intellisense

![Screenshot showing that the "id" prop is not being recognized by the intellisense](https://github.com/vuejs/language-tools/assets/7539096/dbe33b7f-ea7c-4d90-8f39-1f8fa5de347f)

### Prop is part of "this"

![Screenshot showing that the "id" prop is being recognized as owned by the current object instance](https://github.com/vuejs/language-tools/assets/7539096/d82153fc-bd38-4bbf-a274-ee9f16b069d4)

## Steps to reproduce

By using the following code (used About view from project initialization as a base), it is possible to notice that the **id** prop is not recognized ([link to playground](https://play.vuejs.org/#eNp9U01v2zAM/SuETgmWz3Un1wvWDT1sh7ZYc/TFtRhbnSwZkpw6MPzfRym24wxrgSCW+B7FRz6pZXdVtTrWyCIWOywrmTrcJQog5uIImUyt/Zqw9EXXLmEBIKjY7vaFsEC/VEEAoUpzjNeE9BxK392BFXQkgkPr6K9xEbRtWOwp8pwGsOvitWe/m6jq8gVNSBX8Sdb2UV1nDat4PWmBtjYzonK0psO0cdACx4NQ+EPTXqFy0MHB6BISRiNI2K3PwiZwiZnWMnynGbPWF6yMriwJOksWfFwCuFOFETwEyYsh2B8WweYc6fynCzBPXTqbt2DQ1UZ5iRTw04lIVcKgu+2JGUmoHV5qjbOYpDuyZSU4fILtkEeSrub9L3uoRzlUbgk2sGgYU5UlukLzS8tS53TO2HOoOuwyrayWuPKcXs/iutScBn0ZQ6I6H4jXo13eOneS3sVvJXKRwqwUavkmuCsi2G4+f6ma+VnK6nz7eimeVaDIC5redrM5Fn0hLixdi1MEB4lNH0ulyNVS0I2htjKyFk1AvJ6gplfAFsxZ6ukg8tWr1YpeSqiWMO+IkGgeKyeo54SN46EXI6V++xViztTYO0E5BWZ//hN/tY2PJezJoEVzJANGzKUmR3p+Hr5/fiA3J2Cpee3t+gD8jeRH7TWead9rxUn2hBfU/gyPRKh8b+8bh8oOTXmhl6sQ3op/D++1fpF7s7oZJsq6v/wxc8k=)):

```html

<template>
  <div class="about">
    <h1>This is an about page</h1>
    <div>A simple test text: {{ textTestSample }}</div>
    <div>A simple test number: {{ idPlusOne }}</div>
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    id: {
      type: Number,
      default: 0
    }
  },
  data(){
    return {
      dataTest: ""
    };
  },
  computed: {
    idPlusOne(){ return this.id + 1; },
    textTestSample(){ return this.dataTest + " - sample"; }
  },
  methods: {
    log(){
      console.log(this.id, this.dataTest);
    }
  }
});
</script>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
```

## Environment

- OS: `Windows 11`;
- IDE: `VS Code 1.86.1`;
- TS: `5.3.2` (it does not matter wheter it is running under takeover mode or not);
- VLF + TS Plugin: `1.8.27`.

**Comment by so1ve** [comment]
Seemed to be a vue core issue. https://github.com/vuejs/core/issues/9296
