### ISSUE TITLE
Types aren't properly loaded into environment until watcher runs

### ISSUE THREAD

**Issue by danielroe** [vuejs/language-tools#3890]
When starting vue-tsc or Volar, types are not fully resolved and errors can't be checked until the first watch event occurs.

**Reproduction**: https://stackblitz.com/edit/github-dhpjw5?file=app.vue,package.json

To reproduce, open `app.vue` (while `vue-tsc --watch` is running) and edit the file, even just adding a comment would do. (This also works if you edit or create another file in the project.)

Possibly linked? https://github.com/vuejs/language-tools/issues/1274

**Comment by szvest** [comment]
I spotted this issue in Twitch. I believe it is linked to #1077 . 

**Reproduction with error** : [https://stackblitz.com/edit/github-dhpjw5-5rd1r8?file=env.d.ts](url)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
