### ISSUE TITLE
`@update:modelValue` resolves correctly, whereas `@update:model-value` is any

### ISSUE THREAD

**Issue by DamianGlowala** [vuejs/language-tools#3900]
I am using a Vue component with a simple two-way data binding:

```
const modelValue = defineModel<string>({ required: true })
```

When I use the component and declare an event listener on it (`@update:model-value`), the type is `any`. Tried changing it to `@update:modelValue` and, surprisingly, it works!

There's a https://eslint.vuejs.org/rules/v-on-event-hyphenation.html rule which warns about the correctly resolved variant, hence I would much rather keep the hyphenated convention.

**Comment by so1ve** [comment]
Works on my machine, could you please provide a more detailed reproduction?

![image](https://github.com/vuejs/language-tools/assets/58381667/6b6ac3bf-fe95-40f5-92cc-5382975d0f71)

**Comment by DamianGlowala** [comment]
I'll verify with latest v2 and report back, this might be no longer the case :) thanks for looking into this!

**Comment by davidmatter** [comment]
Closing this one due to inactivity. Feel free to create a new issue if you're still having issues with the latest version, thanks!
