### ISSUE TITLE
Duplicated items in suggestion list for prop values in `<template>`

### ISSUE THREAD

**Issue by romansp** [vuejs/language-tools#3922]
I'm seeing 4 copies of the same entry in the prop values suggestion list in `<template>`. See attached screenshot:

Repro steps:
1. Create fresh Vue project via `create-vue` with TypeScript support.
2. Upgraded all packages to the latest.
3. Open `App.vue` and open suggestion list for `:msg` prop for `<HelloWorld />` component.

<img width="1049" alt="image" src="https://github.com/vuejs/language-tools/assets/3474842/86a731e7-f08f-4641-8551-29d1deffbae7">

Environment:
* VS Code v1.87.0
* MacOS v14.2.1
* vue v3.4.21
* Vue.volar extension v2.0.0

**Comment by letstri** [comment]
I have the same issue but only with 1 copy of each prop
<img width="285" alt="image" src="https://github.com/vuejs/language-tools/assets/13253748/3a103a2d-4051-4d27-a11a-b0b63b3ac1b3">

**Comment by iamwxq** [comment]
same issue
