### ISSUE TITLE
No hover popups and suggestions are broken

### ISSUE THREAD

**Issue by mattersj** [vuejs/language-tools#3923]
I've tested the new version on a project with ~5000 files written in plain Composition API (without <script setup>) and it seems like neither suggestions nor hover type popups work in my case.

Hover (props are typed and it had worked before):
<img width="157" alt="image" src="https://github.com/vuejs/language-tools/assets/28510814/dc07b289-b8c7-4ae1-802f-1e4c3926bec1">

Autocompletion works the same way both in template and script showing me some internal stuff and nothing related to an actual type:
<img width="499" alt="image" src="https://github.com/vuejs/language-tools/assets/28510814/29fad837-97fc-45af-ab06-613e8efa6afc">

Worth mentioning that this can only be reproduced in *.vue files, .*ts files are fine.

**Comment by mattersj** [comment]
One more thing: there's an error at the end of the file (right after closing <style> tag) with a lot of similar internal codegen errors:
<img width="581" alt="image" src="https://github.com/vuejs/language-tools/assets/28510814/2b48bc75-c772-4f02-a77f-055c83392067">

**Comment by johnsoncodehk** [comment]
I haven't been able to reproduce the issue yet, but just in case, check if you have disabled the "TypeScript Vue Plugin (Volar)", which may cause conflicts with 2.0.

**Comment by mattersj** [comment]
@johnsoncodehk That's the first thing I did during updating, I only have the new Vue - Official extension updated to the latest 2.0.2 version right now.
I've also tested how it works on other projects of different sizes and there are the same errors at the end of the file, even if I create a new file and start writing some basic stuff it gives me 0 suggestions right away - even for built-in objects like `Math`.
<img width="604" alt="image" src="https://github.com/vuejs/language-tools/assets/28510814/cafc9884-9ec0-43ce-87ad-af31a8975a07">

What's interesting though, is that among those errors at the end of the file I can see actual errors from my code and if I fix all of them the red squiggly line may disappear (but if the template has at least 1 expression it'll be still there - `Block-scoped variable '__VLS_3' used before its declaration.ts-plugin(2448)`)

Here's the output I can see right after reloading the window:
```
[Vue Named Pipe Client] Error: connect ECONNREFUSED /tmp/vue-tsp-6155
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/vue-tsp-6155'
}
[Vue Named Pipe Client] Error: connect ECONNREFUSED /tmp/vue-tsp-6155
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/vue-tsp-6155'
}
[Vue Named Pipe Client] Error: connect ECONNREFUSED /tmp/vue-tsp-6155
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/vue-tsp-6155'
}
```

**Comment by johnsoncodehk** [comment]
See #3942
