### ISSUE TITLE
After upgrading to version 2, the vue3 syntax prompt is gone.

### ISSUE THREAD

**Issue by freeala** [vuejs/language-tools#3926]
![e971c3f788425bbdf886cc6271760b2](https://github.com/vuejs/language-tools/assets/39516160/f2545b36-14f8-44ba-ae05-8859f7e18522)
![b0d2983962d42877e8ddef693df251a](https://github.com/vuejs/language-tools/assets/39516160/a42d969a-3136-496f-bed5-89e3c1dc7fb2)

**Comment by lechenc** [comment]
.value自动补全也没了

**Comment by moheng233** [comment]
Remove the `TypeScript Vue Plugin (Volar)` plugin and re-enable built-in Typescript language support.
删除`TypeScript Vue Plugin (Volar)`插件, 并重新打开内置的Typescript语言支持。

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
