### ISSUE TITLE
[Vue Named Pipe Client] pipeFile not found

### ISSUE THREAD

**Issue by zyhnbyyds** [vuejs/language-tools#3928]
Vue - Official 2.0.0

vue-tsc 2.0.1

computer: windows11

![image](https://github.com/vuejs/language-tools/assets/83394286/97cdfdf0-82d6-4d3b-b04c-761684b9df83)

**Comment by skywalker512** [comment]
I have the same issue. I found that when running the 

```
fs.writeFileSync(`\\\\.\\pipe\\vue-tsp-table.json`)
```

method on Windows, it throws an error.

(I am not familiar with Windows named pipes. Shouldn't this be placed in the tmp directory of Windows instead of a named pipe here?)

I debugged it and confirmed this problem with the TypeScript Language Server.

![image](https://github.com/vuejs/language-tools/assets/12960906/e1f7ca82-421c-47f8-894b-6f72e45f7ec8)

**Comment by zyhnbyyds** [comment]
@skywalker512 不太清楚什么问题

**Comment by zyhnbyyds** [comment]
等官方解决吧😂

**Comment by johnsoncodehk** [comment]
I don't use windows, can you help me try this version to see if it fixes the problem?

[volar-2.0.1-72e38d52.vsix.zip](https://github.com/vuejs/language-tools/files/14468404/volar-2.0.1-72e38d52.vsix.zip)

**Comment by RunningCoderLee** [comment]
I'm having the same issue

```shell
[Vue Named Pipe Client] Error: connect ECONNREFUSED /tmp/vue-tsp-73891
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/vue-tsp-73891'
}
[Vue Named Pipe Client] Error: connect ECONNREFUSED /tmp/vue-tsp-73890
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/vue-tsp-73890'
}
[Vue Named Pipe Client] pipeFile not found
```

my OS is macos 14.2.1 (23C71)

**Comment by skywalker512** [comment]
> I don't use windows, can you help me try this version to see if it fixes the problem?
> 
> [volar-2.0.1-72e38d52.vsix.zip](https://github.com/vuejs/language-tools/files/14468404/volar-2.0.1-72e38d52.vsix.zip)

I have tested it, there should be no issues now.

**Comment by zyhnbyyds** [comment]
![image](https://github.com/vuejs/language-tools/assets/83394286/18743be5-d934-4cb5-88a4-de74592bf03f)
I up to 2.0.2, still get some error in output

**Comment by zyhnbyyds** [comment]
@johnsoncodehk

**Comment by goper-leo** [comment]
- Disable/Uninstall `TypeScript Vue Plugin`
- Re-enable vscode builtin `TypeScript and JavaScript Language Features`
- Restart

**Comment by RunningCoderLee** [comment]
> * Disable/Uninstall `TypeScript Vue Plugin`
> * Re-enable vscode builtin `TypeScript and JavaScript Language Features`
> * Restart

The issue still exist
