### ISSUE TITLE
Issue with Pug template v2.0.0 - never read warning

### ISSUE THREAD

**Issue by juzser** [vuejs/language-tools#3930]
Seem likes the new version has not been compatible with template using pug yet?
I'm using the components and methods on template but it's still showing unused warnings. 

<img width="566" alt="Screenshot 2024-03-02 at 14 05 23" src="https://github.com/vuejs/language-tools/assets/5735071/e7ecc8f3-4b4a-4848-9dec-ad3acd36e3a3">
<img width="605" alt="Screenshot 2024-03-02 at 14 05 30" src="https://github.com/vuejs/language-tools/assets/5735071/9a880e37-d55a-414f-8c60-37783f68f939">

**Comment by JayPuff** [comment]
I thought I was going crazy from running into the same issue after having set up my typescript/linting within our pug templates last week and having no issue. Unfortunate timing I guess.

Yeah, seems like it's a language tools v2.0 issue on composition API components, whether `lang="ts"` is on or not

**Comment by richardsimko** [comment]
Option clicking on references in the template also no longer works, could be related.

**Comment by JayPuff** [comment]
> Option clicking on references in the template also no longer works, could be related.

Yeah likely the same issue, same for hovering over script variables in the template which would usually give type info

**Comment by fengjac** [comment]
Same issue

**Comment by JayPuff** [comment]
2.0.5 does not resolve the issue with the `never read` warning for me, even after re-installing the extension and rebooting vscode.

Has anyone managed to get it to work for them?

I have this in my `tsconfig.json`:

```
"vueCompilerOptions": {
    "plugins": [
      "@vue/language-plugin-pug"
    ]
  }
```

**Comment by fardolieri** [comment]
Have you made sure to be on the latest version of @vue/language-plugin-pug? That fixed the problem for me.

`npm i -D @vue/language-plugin-pug@latest`

**Comment by JayPuff** [comment]
Yep that worked, thank you so much :tada:

**Comment by juzser** [comment]
Updated to `@vue/language-plugin-pug` 2.0.21  but still occur..
