### ISSUE TITLE
Extension “TypeScript and JavaScript Language Features” not found

### ISSUE THREAD

**Issue by HammCn** [vuejs/language-tools#3932]
The extension “Vue - Official v2.0.2” throws a warning message that

> Takeover mode is no longer needed in version 2.0. Please enable the "TypeScript and JavaScript Language Features" extension.

But there's no extension called "TypeScript and JavaScript Language Features" in vscode extension market:

<img width="564" alt="image" src="https://github.com/vuejs/language-tools/assets/16929327/80d5d727-b105-40e5-b4df-5b47b8483c53">

<img width="639" alt="image" src="https://github.com/vuejs/language-tools/assets/16929327/f5ccb76f-c445-4892-a534-302abd255228">

**Comment by RayGuo-ergou** [comment]
TypeScript and JavaScript Language Features is not an extension, it's natively in vscode.

You can use this [reference](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) to revert it.

**Comment by HammCn** [comment]
> Maybe just use `@builtin typescript` as search query
> 
> ![image](https://private-user-images.githubusercontent.com/33137074/309461299-c03b274b-8b1e-458a-b69b-3060db77a485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODgyNTIsIm5iZiI6MTcwOTM4Nzk1MiwicGF0aCI6Ii8zMzEzNzA3NC8zMDk0NjEyOTktYzAzYjI3NGItOGIxZS00NThhLWI2OWItMzA2MGRiNzdhNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDEzNTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MWIzNDhlMjY1MjcxZTYwMTIwMjBiNGVhYzE0Y2NmNjZkODI1MTc4ZmZlNWYwOThkNGU4YTQwODJhNGY4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZyATlyRZnvW12TBT9tssT3wUHW5d1gsnoyBjS8FHB0)

OK, got it. thanks.

**Comment by rmacuna** [comment]
Once I activate this again I'm having issues with my nuxt 3 autoimports

**Comment by omanfathurrahman** [comment]
> Once I activate this again I'm having issues with my nuxt 3 autoimports

same

**Comment by mmasoudih** [comment]
> Once I activate this again I'm having issues with my nuxt 3 autoimports

same

**Comment by f4cker** [comment]
same, TS/JS language server has crashed

**Comment by harveyLXH** [comment]
same, TS/JS language server has crashed

**Comment by harveyLXH** [comment]
Reduced version available to V1.8.24

**Comment by harveyLXH** [comment]
> Reduced version available to V1.8.24缩减版本适用于 V1.8.24

![image](https://github.com/vuejs/language-tools/assets/28383928/1d25efc2-48c8-4513-979d-366d3dc50a06)

**Comment by zedo-san** [comment]
I downgraded to v1.8.27 and it now works again.

**Comment by harveyLXH** [comment]
<img width="635" alt="image" src="https://github.com/vuejs/language-tools/assets/28383928/22b30c12-df44-493a-8ce9-d11f7609d205">
update V2.0.5, it works aggin.

**Comment by aote777** [comment]
我内置ts插件一直是 启用 状态。这个插件也提示去启用
![企业微信截图_17236050767565](https://github.com/user-attachments/assets/337de096-a070-4320-b620-fe771699037e)

**Comment by aote777** [comment]
> 我内置ts插件一直是 启用 状态。这个插件也提示去启用 ![企业微信截图_17236050767565](https://private-user-images.githubusercontent.com/53163966/357671880-337de096-a070-4320-b620-fe771699037e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDY4MTYsIm5iZiI6MTcyOTAwNjUxNiwicGF0aCI6Ii81MzE2Mzk2Ni8zNTc2NzE4ODAtMzM3ZGUwOTYtYTA3MC00MzIwLWI2MjAtZmU3NzE2OTkwMzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNWNhYjA5MTJhNzVlM2YzMjQxMTc2NmJlMmFlNmFkZWRjNWVjMzQxZDFiZTVhMTE4ZTBmOGUzNTI3NmYxMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LcBOGo1iwSY31AU-nsKanyj69ICJLozkdfz_tGkys_w)

我的问题解决了。我是因为以前用vetur插件 弄了很多设置在 vscode setting.json文件 然后一直同步着，估计是冲突了。我直接把整个设置文件 setting.json 全删了 然后保存重启 ， 就不会提示 哪个Takeover 错误了。并且 ts 类型提示也可以用了

**Comment by harveyLXH** [comment]
好的，谢谢
&nbsp;


harve
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月15日(星期二) 晚上11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vuejs/language-tools] Extension “TypeScript and JavaScript Language Features” not found (Issue #3932)














  
我内置ts插件一直是 启用 状态。这个插件也提示去启用 
  
我的问题解决了。我是因为以前用vetur插件 弄了很多设置在 vscode setting.json文件 然后一直同步着，估计是冲突了。我直接把整个设置文件 setting.json 全删了 然后保存重启 ， 就不会提示 哪个Takeover 错误了。并且 ts 类型提示也可以用了
