### ISSUE TITLE
In this function, syntax highlighting for constants only works correctly at a specific scroll level.

### ISSUE THREAD

**Issue by mybearworld** [vuejs/language-tools#3935]
The following code:
```vue
<script setup lang="ts">












const loadingMore = ref(false);
const loadMore = async () => {
  if (loadingMore.value) {
    return;
  }
  loadingMore.value = true;
  const page =
    newPostsAmount.value < 1
      ? 1
      : Math.floor(newPostsAmount.value / POSTS_PER_REQUESTS) + 1;
  const postsToRemove =
    newPostsAmount.value <= -25
      ? 0
      : newPostsAmount.value < 0
        ? POSTS_PER_REQUESTS + (newPostsAmount.value % POSTS_PER_REQUESTS)
        : newPostsAmount.value % POSTS_PER_REQUESTS;
  const response = await getResponseFromAPIRequest(
    requestURL + `&page=${page}`,
    {
      auth: true,
      schema: postsSchema,
    },
  );
  if ("status" in response) {
    await dialogStore.alert(t("loadMoreFail", { status: response.status }));
    return;
  }
  const newPosts = response.autoget.slice(postsToRemove);
  posts.value.push(...newPosts);
  newPostsAmount.value += newPosts.length;
  loadingMore.value = false;
  stopShowingLoadMore.value = response.pages === page;
};
</script>

<template>{{}}</template>
```
Looks like this when not scrolled:
![image](https://github.com/vuejs/language-tools/assets/130385691/1886fad2-771f-4aaa-8e21-93f0d9ba5f49)
But like *this* when scrolled:
![image](https://github.com/vuejs/language-tools/assets/130385691/439c8826-52fc-44c8-b216-0b46685b2629)

More new lines require more scrolling to get the constants to appear correctly.

I've tried removing several statements, and they all caused this not to happen, and to always highlight the constants properly (assuming the mustaches are present, #3934).

**Comment by johnsoncodehk** [comment]
Thanks for such a good reproductions!

**Comment by raphael-yapla** [comment]
This bug is still happening for me on v2.0.19 on big files, when the const gets out of view the syntax highlighting disappears.

Here's the modified code to reproduce it:

<details>

```vue
<script setup lang="ts">
  const loadingMore = ref(false);






















































  loadingMore.value = false
};
</script>

<template>{{}}</template>
```
</details>

When not fully scrolled:

![image](https://github.com/vuejs/language-tools/assets/112508250/31adc059-c89f-44dd-b8d1-c9115b2c3b8d)

When fully scrolled:

![image](https://github.com/vuejs/language-tools/assets/112508250/49400064-6882-4023-8588-67dab081cfc3)
