### ISSUE TITLE
Typescript and vue intellisense not working

### ISSUE THREAD

**Issue by cristiano-matchday** [vuejs/language-tools#3936]
Hi - Since I started using this instead of Volar, my typescript and vue intellisense stopped working.

Also, all my vue files result in error, when they are squeaky clean.

<img width="870" alt="image" src="https://github.com/vuejs/language-tools/assets/134049463/1c45c235-2356-4ad1-92a3-122630f910d0">

Any suggestion? I use Vite boilerplate.

**Comment by yingside** [comment]
Yes, me too, upgraded Vue - Official v2.0.2, typescript doesn’t work anymore

**Comment by wuhaohuang** [comment]
+1
<img width="1081" alt="image" src="https://github.com/vuejs/language-tools/assets/19322584/b3871ddf-155e-46db-8abe-3f65e132d426">

**Comment by wuhaohuang** [comment]
> Hi - Since I started using this instead of Volar, my typescript and vue intellisense stopped working.
> 
> Also, all my vue files result in error, when they are squeaky clean.
> 
> <img alt="image" width="870" src="https://private-user-images.githubusercontent.com/134049463/309468813-1c45c235-2356-4ad1-92a3-122630f910d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNzkzNzMsIm5iZiI6MTcwOTM3OTA3MywicGF0aCI6Ii8xMzQwNDk0NjMvMzA5NDY4ODEzLTFjNDVjMjM1LTIzNTYtNGFkMS05MmEzLTEyMjYzMGY5MTBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMTMxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDZiZmViMDE0OTVkMTQ4MTgwZWQzZDE2ZTkzZTY4YTg4MzFjZDUxOWY0MTFmMGNmMWJlN2RhYjcxMjU5N2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.js4AxobCXVwZvadqNaAFqQvda5rczzf7E5eRkLJbsZU">
> Any suggestion? I use Vite boilerplate.

My current solution is to downgrade Vue - Official back to 1.8.27, start Volar, and disable the automatic upgrade of the vscode plug-in, and it will work.

**Comment by cristiano-matchday** [comment]
That worked for me.

**Comment by hungify2022** [comment]
I don't have any issues like it.
Could you try to run `Developer: reloading window` in vscode?


![CleanShot 2024-03-02 at 19 31 02@2x](https://github.com/vuejs/language-tools/assets/126773143/e687ae8d-aa99-4f36-866b-c5691e395f93)
Read notification bottom

**Comment by larserikfinholt** [comment]
Reloading windows causes it to ask for volar again. Is the Volar needed in v2.0.2 as shown in the image?

![image](https://github.com/vuejs/language-tools/assets/1328417/1c50e0f1-ee49-4e01-8e6e-6898376f3bca)

**Comment by cristiano-matchday** [comment]
> I don't have any issues like it. Can you try running 'Developer: reloading window' in VScode and read the notification box?
> 
> Note:
> 
> * `Vue.vscode-typescript-vue-plugin` no need to install
> * Enable `TypeScript and JavaScript Language Features`
> 
> ![CleanShot 2024-03-02 at 19 31 02@2x](https://private-user-images.githubusercontent.com/126773143/309473276-e687ae8d-aa99-4f36-866b-c5691e395f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODU4NDEsIm5iZiI6MTcwOTM4NTU0MSwicGF0aCI6Ii8xMjY3NzMxNDMvMzA5NDczMjc2LWU2ODdhZThkLWFhOTktNGYzNi04NjZiLWM1NjkxZTM5NWY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMzE5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTZjNTZjNzE5MjdiMDVlOTIzN2UxMDg3ZWJhOWNlM2Q2OTY3MTdlMzFiYmVhNDA5ZjI5OTRiODRjYTVkOTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DNuFw6amzVJd2Iu1flIg-PpG7rwi7hHXsCpUeJEMdR0)

I reloaded my window a bajillion times and removed the volar stuff. I don't have that plugin you are referring to either.
About Enable TypeScript and JavaScript Language Features - they are

**Comment by wuhaohuang** [comment]
> I don't have any issues like it. Can you try running 'Developer: reloading window' in VScode and read the notification box?
> 
> Note:
> 
> * `Vue.vscode-typescript-vue-plugin` no need to install
> * Enable `TypeScript and JavaScript Language Features`
> 
> ![CleanShot 2024-03-02 at 19 31 02@2x](https://private-user-images.githubusercontent.com/126773143/309473276-e687ae8d-aa99-4f36-866b-c5691e395f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTM5NDksIm5iZiI6MTcwOTM5MzY0OSwicGF0aCI6Ii8xMjY3NzMxNDMvMzA5NDczMjc2LWU2ODdhZThkLWFhOTktNGYzNi04NjZiLWM1NjkxZTM5NWY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxNTM0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWU3YzQ3ODEzZDE4OWQ5YjNjOWQ0YjA4YzUwMTdjYTYxYWVhZDFkZDZmMjI2YzNmYTM4ZGMzNTczYTdiZTI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mH90w3C9fNVZenoExPArD_emzBKvTvkFzx_sQapUVrc)

I re-upgraded to the latest 2.0.2 and disabled Vue.vscode-typescript-vue-plugin in the workspace. I also tried restarting typescript server and vscode, but it still doesn't work, and this message pops up.

<img width="910" alt="image" src="https://github.com/vuejs/language-tools/assets/19322584/58631310-c302-48cf-9b74-e4b10450dd42">

Then I disabled the styled-component plug-in, and it reported an error and crashed.

<img width="506" alt="image" src="https://github.com/vuejs/language-tools/assets/19322584/cf71c44b-d23f-4ad6-bcf8-28ad067d1e9c">

**Comment by rmacuna** [comment]
Same here. Typescript no longer works and my vscode can't find any definition types for my components

**Comment by HamasakiBrain** [comment]
1. Remove **TypeScript Vue Plugin (Volar)**
2. Install **Vue - Official**
3. Enable **TypeScript and JavaScript Language Features** in Plugins > Search - `@builtin typescript`

Its resolved for me.

**Comment by Tekilian** [comment]
I tried many ways mentioned above but it dosn't work
however , disabling styled component extension in my workplace has resolved my problem

**Comment by pzgz** [comment]
same here, after upgrading to `2.0.2`, even tried to uninstall and reinstall Vue - Official plugin, still got TS service crashed 5 times issue:

![CleanShot 2024-03-03 at 02 24 53@2x](https://github.com/vuejs/language-tools/assets/529486/d977a014-e86b-4a81-a834-c8f64618ccb1)

**Comment by pzgz** [comment]
Well, code - insiders version is working for now, might be a workaround before we got fix

**Comment by ElYaiko** [comment]
> same here, after upgrading to `2.0.2`, even tried to uninstall and reinstall Vue - Official plugin, still got TS service crashed 5 times issue:
> 
> ![CleanShot 2024-03-03 at 02 24 53@2x](https://private-user-images.githubusercontent.com/529486/309493296-d977a014-e86b-4a81-a834-c8f64618ccb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MTYxMTIsIm5iZiI6MTcwOTQxNTgxMiwicGF0aCI6Ii81Mjk0ODYvMzA5NDkzMjk2LWQ5NzdhMDE0LWU4NmItNGE4MS1hODM0LWM4ZjY0NjE4Y2NiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQyMTQzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTNmZjAzNjNlZjU2ZGM0YWVjZWE2ZTk0OTdmYzY0MDU4Y2YwYWJkZmJhNmQ4MGUzOTA4NmZjNTE0YjdhNjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vKfz_Sqh0jG6pXCimu2cDYvetnzPnjovRmo9S4fECLk)

I'm having the same issue, it makes the JS/TS Language server crash from version `2>`

I have VSCode 1.87.

**Comment by johnsoncodehk** [comment]
See #3936

**Comment by WayneDT** [comment]
> #3942 was of no help to me
I don't use the "Svelte extension"

I am still facing extremely slow intellisence with my vue typescript project. what is the recommended solution?
Do I downgrade to the previous version and install the deprecated volar extension?

**Comment by RedskyThirty** [comment]
Same problem for me. Since I ununstalled Volar and use Vue Official, I lost the autocomplete on components, interfaces, etc.
VSCode was a very good IDE for Vue but now, it's very debatable. This is the problem with software that requires multiple plugins to work the way you want...
I really hope that this will be fixed soon.

**Comment by ebisbe** [comment]
Not sure if it's related but I got the message `Cannot find moduel X or it's types declarations.` other than that everything works. It's annoying because I miss most of the TS features with all my personal files.

**Comment by aryankarim** [comment]
installed `TypeScript Vue Plugin (Volar)` again. cuz auto imports not working with the `Vue Official`

**Comment by biantris** [comment]
I got this same error and the “temporary” solution was to downgrade the version of ``Vue Official`` from `v2.1.4` to `v2.0.28`

Note: my project uses Vue 2 ( maybe it should interfere somehow )

**Comment by Jacob-P-Busby** [comment]
I'm using @vue/language-server in Helix, and I have a similar problem, template and emmet autocompletion work fine, but I won't get completion or warning in typescript code

**Comment by mraveux** [comment]
The issue is still present. Since a couple of week I do not get errors anymore in vue templates. Everything is typed "any" even if it doesn't exist, or is completely wrong. I could not have the extension enabled that it would be the same.

**Comment by dsasko** [comment]
> Can you try running 'Developer: reloading window' in VScode

Reloading the window worked for me. Thanks!
Before the reload I wouldn't get the type popup or proper type inference.

**Comment by OliverGrimsley** [comment]
I have had this issue with intellisense / code completion / typescript in my VScode on and off again since "Vue Official" took over for Volar. Sometimes restarting VScode got it working, sometimes restarting the extension host etc. But today, it just stopped and refused to work, I even restarted the entire computer, nothing worked.

I changed Hybrid mode to false, it said extensions had an error (but exit code 0??) and then magically, all my intellisense in typescript and vue code components, pinia stores etc worked (Vue 3)

![Image](https://github.com/user-attachments/assets/a760f840-c91c-4767-beaa-781b156df1b8)

Current versions: VSCode 1.96.4, Vue Official 2.2.0

**Comment by KromDaniel** [comment]
I dropped my project with vue just because of this, vscode integration is fully broken
