### ISSUE TITLE
Vue Language Server Crashes in VSCode + Nuxt

### ISSUE THREAD

**Issue by madebyfabian** [vuejs/language-tools#3937]
I have a larger Nuxt 3 app running at `3.10.3`. Since today (updated the VSCode extension to `2.0.2`) the plugin crashes and I get this:

```bash
["[...dynamicSlug]","RouterView","RouterLink","StoryblokComponent","StoryblokRichtextImage","StoryblokRichtextLink","StoryblokImg","StoryblokRichtextContainer","PageArticle","PageAuthor","PageSerpSeo","AccordionItem","ArticleAccordionSection","ArticleButtonLink","ArticleCallout","ArticleChecklist",... 
(SHORTENED) "modalInjectionKey","navigateTo","nextTick","onActivated","onBeforeMount","onBe[Error - 12:07:58] Server process exited with code 1.
[Error - 12:07:58] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

in the output logs.

The long array contains all of my component names and various other auto-imports (I shortened it for the sake of simplicity).

Not sure how to provide a reproduction, but I am happy to do.

**Comment by hopkins385** [comment]
same here 
```
[Info  - 15:05:30] Connection to server got closed. Server will restart.
true
undefined:1
...
[Error - 15:05:30] Server process exited with code 1.
[Error - 15:05:30] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
package.json
```
    "nuxt": "^3.9.3",
    "typescript": "^5.3.3",
```
System:
```
Node: v21.1.0
MacOS: 14.1.2
```

**Comment by realityfilter** [comment]
Same here. Additional output before error message reads:

```
[Vue Named Pipe Client] Error: connect ECONNREFUSED /tmp/vue-tsp-54831
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/vue-tsp-54831'
}
```

**Comment by handanyolak** [comment]
Is there any update on this?

**Comment by ydnikolaev** [comment]
got same today

- downgrade Vue Official to v1.8.27, 
- re-enable Volar, 
- turn on Takeover mode 

works fine

**Comment by maprangsoft** [comment]
> got same today
> 
> * downgrade Vue Official to v1.8.27,
> * re-enable Volar,
> * turn on Takeover mode
> 
> works fine

i use nuxt 3 and use auto import after extension update to latest auto import not working downgrade dont work for me.
![Screen Shot 2567-03-03 at 14 06 09](https://github.com/vuejs/language-tools/assets/25447955/038d510f-93d0-4577-8969-a7f934a1d73c)

**Comment by baikov** [comment]
same error... returned Takeover mode

**Comment by maprangsoft** [comment]
> > got same today
> > 
> > * downgrade Vue Official to v1.8.27,
> > * re-enable Volar,
> > * turn on Takeover mode
> > 
> > works fine
> 
> i use nuxt 3 and @pinia/nuxt use auto import after extension update to latest auto import not working downgrade dont work for me. ![Screen Shot 2567-03-03 at 14 06 09](https://private-user-images.githubusercontent.com/25447955/309532256-038d510f-93d0-4577-8969-a7f934a1d73c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDE0ODAsIm5iZiI6MTcwOTU0MTE4MCwicGF0aCI6Ii8yNTQ0Nzk1NS8zMDk1MzIyNTYtMDM4ZDUxMGYtOTNkMC00NTc3LTg5NjktYTdmOTM0YTFkNzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA4MzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OTUxOTJjYmUyOGUwYTU4YTIwODA4NGYwY2I0YTNlMmIyYmJjNzk5NzA3NDA3ZTdmYTFmZDEzYTBiNWJiZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGrMNyU56LoSIlWSBnEcvzWPV8dFiv8PCoMLxqCXI9o)

in my case i found node_modules folder in ~/ i test delete folder node_modules and run nuxt project again auto import is working
problem has resolved. ^__^
