### ISSUE TITLE
How to jump to css definition

### ISSUE THREAD

**Issue by ljlsasuke** [vuejs/language-tools#3938]
Previously I was able to quickly jump to the css definition by reference, but now it doesn't
past

![image](https://github.com/vuejs/language-tools/assets/102413422/685eba4f-f043-45da-a709-058ce4736c01)

now
![image](https://github.com/vuejs/language-tools/assets/102413422/ab438359-1c18-4642-b2db-603ec87c6bd1)
![image](https://github.com/vuejs/language-tools/assets/102413422/ba350e67-7dd6-4b36-9608-385c312beecd)

**Comment by so1ve** [comment]
[小](https://github.com/vuejs/language-tools/issues/3986)

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/issues/3986
