### ISSUE TITLE
unexpected format result with newline in vue/html files since version 2.0.0

### ISSUE THREAD

**Issue by zhaojjiang** [vuejs/language-tools#3943]
## Steps to reproduce

```json
// .vscode/settings.json
{
  "[vue]": {
    "editor.defaultFormatter": "Vue.volar"
  },
}
```

```vue
<!--  -->
<script setup lang="ts">
</script>

<template>
  <router-view v-slot="{ Component, route }">
    <keep-alive>
      <component :is="Component" v-if="route.meta.keepAlive" />
    </keep-alive>
    <component :is="Component" v-if="!route.meta.keepAlive" />
  </router-view>
  <template></template>
  <template></template>
  <template></template>
  <div>
    <template></template>
  </div>
</template>
```
### format result before extension version 2.0.0

![image](https://github.com/vuejs/language-tools/assets/39524531/bfd8bd4b-0426-4af5-98b1-3f1e9b51d8a4)

### format result since extension version 2.0.0

![image](https://github.com/vuejs/language-tools/assets/39524531/89041796-6b1b-4f6e-a788-feecfd669a4b)

## problem

the newline between comment and script is unexpected, so is newline between template, and template in div

**Comment by sowth** [comment]
same problem, need help!
