### ISSUE TITLE
"Delete all unused imports" doesn't make sense in ".vue" files

### ISSUE THREAD

**Issue by Litrix2** [vuejs/language-tools#3946]
![image](https://github.com/vuejs/language-tools/assets/107967147/dc3978fb-1d4b-4e4c-b7b7-6051c63a35a4)
Removing single declaration is still effective.

**Comment by Litrix2** [comment]
# vscode
Version: 1.87.0 (system setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by JasKang** [comment]
same

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
