### ISSUE TITLE
"Trigger parameter hints" doesn't make sense in ".vue" files

### ISSUE THREAD

**Issue by Litrix2** [vuejs/language-tools#3948]
![image](https://github.com/vuejs/language-tools/assets/107967147/9aa44a80-3e18-4d16-b3fe-5cbe7ba202cf)

# vscode
Version: 1.87.0 (system setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by zengxj0v0** [comment]
After upgrading to 2.0, use the shortcut key `editor.action.triggerParameterHints` in <script lang="ts" setup>. There is no parameter prompt. After returning to 1.8+, the parameter information can be displayed.
![Uploading 1709541980016.jpg…]()

**Comment by zengxj0v0** [comment]
After upgrading to 2.0, use the shortcut key `editor.action.triggerParameterHints` in <script lang="ts" setup>. There is no parameter prompt. After returning to 1.8+, the parameter information can be displayed.

**Comment by BARNZ** [comment]
Same issue for me as well - `Trigger parameter hints` no longer appears to be working correctly

Whats weird in this example is it knows where to find the function (Go to definition works fine) and when suggesting the function during autocomplete you can even see the parameters coming through:

![image](https://github.com/vuejs/language-tools/assets/2202345/f90cdab1-2521-477c-80a4-9535c4d05d02)

But for some reason you can no longer trigger parameter hints manually when inside the function parenthesis (nothing happens):

![image](https://github.com/vuejs/language-tools/assets/2202345/b14e710e-aa16-4b95-bdfd-ad72aea8d6f3)

This is just plain old js in a .vue file.

Appears to be a regression, works just fine in 1.8

**Comment by zengxj0v0** [comment]
I found a solution. Setting `vue.Hybrid` Mode to false in the `Vue Official` plug-in can trigger parameter prompts in .vue and .ts files.
![image](https://github.com/vuejs/language-tools/assets/47970578/3ff3066f-f03f-438a-a14b-303f68cdd3d6)
![image](https://github.com/vuejs/language-tools/assets/47970578/7506d1ce-a959-4d86-a897-ad88f65ad7c7)
![image](https://github.com/vuejs/language-tools/assets/47970578/60200641-5d6b-4a2b-aeab-263a29dbc147)
