### ISSUE TITLE
cna't format tsx correctly in vue  file

### ISSUE THREAD

**Issue by coader** [vuejs/language-tools#3949]
`const a = <div>a</div>`
should be format to` <div>a< /div>` when save

**Comment by coader** [comment]
is there any way to rollback to old version?

**Comment by weiquanju** [comment]
I also encountered this kind of problem。My volar is the latest version `2.0.3`

**Comment by coader** [comment]
nothing happens after click 'install another version'

**Comment by so1ve** [comment]
@coader Check you network.
