### ISSUE TITLE
Vue+TS crashes when vue.volar is upgraded to 2.0

### ISSUE THREAD

**Issue by yingside** [vuejs/language-tools#3953]
Two days ago vue.volar was upgraded to v2.0, and Vue+TS kept reporting errors. 
I thought maybe it was being repaired, 
but now it is v2.0.3, and the problem still exists.
```
"All destructured elements are unused."
"Block-scoped variable '__VLS_8' used before its declaration."
"'__VLS_8' is declared here."
"Variable '__VLS_8' is used before being assigned."
......
```
<img width="818" alt="iShot_2024-03-04_00 07 19" src="https://github.com/vuejs/language-tools/assets/9816360/bb450396-6096-43bc-b549-82aa64f8d0e6">

This is a brand new vue+ts project created through vite

I have used many methods：
1.Remove TypeScript Vue Plugin (Volar)
2.Install Vue - Official
3.Enable TypeScript and JavaScript Language Features in Plugins > Search - @builtin typescript

Yes, I ended up having to delete vs code and even clear the plugins. But it still has no effect。

This problem occurs on my MAC computer：
mac: Apple M2 Pro
macOS: 14.2.1 (23C71)
node: 18.19.0

**But when I open VS Code on a window computer and upgrade vue.volar to 2.0.3, there are no problems.**

**Comment by flmthink** [comment]
I have the same problem on my Windows computer。
![image](https://github.com/vuejs/language-tools/assets/40061566/7cbc3004-55f7-4e66-910a-2c27b6addb16)

**Comment by MostafaElGamal** [comment]
Im having the same issue
![image](https://github.com/vuejs/language-tools/assets/30895073/573c04b0-9ad9-4a6f-8c1c-80d86a3d30e1)

**I solved by downgrade the `vue-official` version to 1.8.27 **

![image](https://github.com/vuejs/language-tools/assets/30895073/6b70fd90-b438-403a-9f12-2cdbf7ffe3b3)

**Comment by rayadaschn** [comment]
I'm having this problem too, On my macBook, I can't install the other versions directly, so I can also do it offline, and then disable automatic updates! [vscode offline install](https://marketplace.visualstudio.com/items?itemName=Vue.volar)
<img width="959" alt="image" src="https://github.com/vuejs/language-tools/assets/115447518/e14b5089-530a-4500-b49f-57653b574173">

![image](https://github.com/vuejs/language-tools/assets/115447518/36c50e6c-7ead-4e84-9634-e8824f86c9ba)

**Comment by lin52025iq** [comment]
+1

**Comment by ifzm** [comment]
+1

**Comment by ifzm** [comment]
I need to return the plugin to install these two versions to avoid errors
Vue - Official v1.8.27
TypeScript Vue Plugin (Volar) v1.8.27

**Comment by hanosong** [comment]
+1

**Comment by huanlirui** [comment]
+ 1

**Comment by OPBR** [comment]
+1

**Comment by ddzy** [comment]
回退到`1.8.27`版本即可
![1](https://github.com/vuejs/language-tools/assets/33921398/27f2fc94-54d8-4a62-ad40-aa788524c886)
![2](https://github.com/vuejs/language-tools/assets/33921398/931713c4-964d-45d8-9387-e4155edca1c5)

**Comment by komorebi920** [comment]
+1

**Comment by JulianRomana** [comment]
+1

**Comment by johnsoncodehk** [comment]
Duplicate of #3942

**Comment by pawelmiklas** [comment]
+1

**Comment by Bowske** [comment]
_**VSCode temporary fix**_

You might want to rollback to the previous version of Vue - Official. To do so, open `Extensions` tab -> click on the little cogwheel icon under `Vue - Official` extension -> select `Install another version` and choose the one that works for you (1.8.27 for me)

![image](https://github.com/vuejs/language-tools/assets/53983669/95b89d03-21e1-4338-80fb-fafc65030647)

**Comment by daniilgri** [comment]
Why the issue is closed if it's still working laggy on the newest version?

**Comment by harryyaprakov** [comment]
@daniilgri They closed it, because it is a duplicate of another issue and is now tracked there.

**Comment by emartinez-dev** [comment]
+1

**Comment by danbarbarito** [comment]
I am still seeing this issue..

**Comment by so1ve** [comment]
> I am still seeing this issue..

This issue has been marked as resolved for two years. Please open a new issue if you still encounter this problem.
