### ISSUE TITLE
2.0+ incorrectly applies wrapping to <script> tag if "html.format.wrapAttributes": "force-aligned" enabled

### ISSUE THREAD

**Issue by andrewheumann** [vuejs/language-tools#3954]
My project uses `"html.format.wrapAttributes": "force-aligned".` As of `v1.8.27`, this worked fine — it applied in the `<template>` and did not affect the script tag. As of 2.0.3, if this setting is enabled, the vue formatter forces very strange wrapping + indenting, trying to wrap the `<script>` tag itself, and producing incorrect indenting:
![image](https://github.com/vuejs/language-tools/assets/31935763/1221ced7-2782-4659-a73a-514ac84b02f3)

If I disable the `force-aligned` setting, then this behavior does not happen in the script tag (but I lose my aligned attributes in the `<template>`) 

I will be stuck using `v1.8.27` until this is resolved.

**Comment by DeepJoyPo** [comment]
same :( 
I try to downgrade to v1.8.x. But the format behavior is still wrong.

**Comment by DeepJoyPo** [comment]
> same :( I try to downgrade to v1.8.x. But the format behavior is still wrong.

After multiple reinstalls and downgrades, it finally works.

**Comment by YuChao-Li** [comment]
Same problem

**Comment by andrewheumann** [comment]
This appears to be fixed as of the latest Vue Language Tools release.
