### ISSUE TITLE
更新到最新版本的 Vue - Official 版本后，初始化 JS/TS 语言服务会崩溃

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [vuejs/language-tools#3957]
## 描述
在更新到最新版本 `Vue - Official v2.0.3`  版本后，重启 `VSCode` 会提示 `JS/TS` 语言服务启动崩溃的问题。

## 环境与版本号
macOS: 14.2.1 (23C71)
CPU：M3 Max
VSCode：1.87.0 (Universal)

## 截图
<img width="460" alt="image" src="https://github.com/vuejs/language-tools/assets/51957438/670552e0-bdf0-4049-9543-79da7d37aaf0">

**Comment by Yann-Qiu** [comment]
同样碰到这个问题

**Comment by norsl** [comment]
我也是，一大早类型提示全无😂

**Comment by CavinHuang** [comment]
同样问题 m2

**Comment by sertceps** [comment]
一样，先降级了

**Comment by Yann-Qiu** [comment]
> 一样，先降级了

降级有用吗？ 我试着降了好像没用诶

**Comment by CLDXiang** [comment]
> > 一样，先降级了
> 
> 降级有用吗？ 我试着降了好像没用诶

先降到 ^1.8 就行了

**Comment by norsl** [comment]
> > 一样，先降级了
> 
> 降级有用吗？ 我试着降了好像没用诶

降到1.8.27的版本

**Comment by CavinHuang** [comment]
> > > 一样，先降级了
> > 
> > 
> > 降级有用吗？ 我试着降了好像没用诶
> 
> 降到1.8.27的版本

vue - official 降级到1.8

**Comment by CavinHuang** [comment]
> > 一样，先降级了
> 
> 降级有用吗？ 我试着降了好像没用诶

vue - official 降级到1.8

**Comment by acegank** [comment]
我特么无语了，都不做测试的吗，直接就发了

**Comment by HandsomeHan515** [comment]
怎么个修复法，下午更新了一版，还是有问题

**Comment by 317883224** [comment]
![image](https://github.com/vuejs/language-tools/assets/38280216/2cd95468-1b70-41f6-8b00-93f78e115c4a)
都是这样配置的吗，我改成不需要tsconfig.app.json的方式的可以了

**Comment by XiaoDaiGua-Ray** [comment]
更改配置有效吗？我这边马上去试一下。

**Comment by QAQLC** [comment]
单文件组件报这种错误，可是项目中没有这个vue文件
![image](https://github.com/vuejs/language-tools/assets/57053220/3ee8d3f4-e375-4130-b9a6-54a964ed8ce8)

**Comment by k644606347** [comment]
> 怎么个修复法，下午更新了一版，还是有问题

@HandsomeHan515   
安装1.8.27或以下版本试试

![](https://github.com/vuejs/language-tools/assets/6951527/aa444525-9524-439d-a3cc-58063fa1514d)

**Comment by JSluowen** [comment]
> > 怎么个修复法，下午更新了一版，还是有问题
> 
> @HandsomeHan515  安装1.8.27或以下版本试试
> 
> ![](https://private-user-images.githubusercontent.com/6951527/309724889-aa444525-9524-439d-a3cc-58063fa1514d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTEwMDQsIm5iZiI6MTcwOTU1MDcwNCwicGF0aCI6Ii82OTUxNTI3LzMwOTcyNDg4OS1hYTQ0NDUyNS05NTI0LTQzOWQtYTNjYy01ODA2M2ZhMTUxNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTExMTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFmNTE1M2JmM2YxMzY4YzAzOWVkYTllMTY5OTdiN2I0NGFkYTFlYmU5MDZhMTQ2NzEwYjJlZWRhZTBkOTE5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CDYSTtEuhO20-xaSJa5O2C5FmrW2Y7DH-6ABQJKpmjo)

为什么点击安装另一个版本没有反应呀？求问是怎么操作的

**Comment by norsl** [comment]
> > > 怎么个修复法，下午更新了一版，还是有问题
> > 
> > 
> > @HandsomeHan515  安装1.8.27或以下版本试试
> > ![](https://private-user-images.githubusercontent.com/6951527/309724889-aa444525-9524-439d-a3cc-58063fa1514d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTEwMDQsIm5iZiI6MTcwOTU1MDcwNCwicGF0aCI6Ii82OTUxNTI3LzMwOTcyNDg4OS1hYTQ0NDUyNS05NTI0LTQzOWQtYTNjYy01ODA2M2ZhMTUxNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTExMTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFmNTE1M2JmM2YxMzY4YzAzOWVkYTllMTY5OTdiN2I0NGFkYTFlYmU5MDZhMTQ2NzEwYjJlZWRhZTBkOTE5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CDYSTtEuhO20-xaSJa5O2C5FmrW2Y7DH-6ABQJKpmjo)
> 
> 为什么点击安装另一个版本没有反应呀？求问是怎么操作的

点了后等一会，不要动，获取版本信息慢

**Comment by JSluowen** [comment]
> > > > 怎么个修复法，下午更新了一版，还是有问题
> > > 
> > > 
> > > @HandsomeHan515  安装1.8.27或以下版本试试
> > > ![](https://private-user-images.githubusercontent.com/6951527/309724889-aa444525-9524-439d-a3cc-58063fa1514d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTEwMDQsIm5iZiI6MTcwOTU1MDcwNCwicGF0aCI6Ii82OTUxNTI3LzMwOTcyNDg4OS1hYTQ0NDUyNS05NTI0LTQzOWQtYTNjYy01ODA2M2ZhMTUxNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTExMTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFmNTE1M2JmM2YxMzY4YzAzOWVkYTllMTY5OTdiN2I0NGFkYTFlYmU5MDZhMTQ2NzEwYjJlZWRhZTBkOTE5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CDYSTtEuhO20-xaSJa5O2C5FmrW2Y7DH-6ABQJKpmjo)
> > 
> > 
> > 为什么点击安装另一个版本没有反应呀？求问是怎么操作的
> 
> 点了后等一会，不要动，获取版本信息慢

现在点击确实没有反应了，有其他办法能够安装历史版本嘛

**Comment by JSluowen** [comment]
可以选择了，等了估计2分钟左右才出现版本选择

**Comment by CH-122** [comment]
> 单文件组件报这种错误，可是项目中没有这个vue文件 ![image](https://private-user-images.githubusercontent.com/57053220/309669283-3ee8d3f4-e375-4130-b9a6-54a964ed8ce8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTc1MTcsIm5iZiI6MTcwOTU5NzIxNywicGF0aCI6Ii81NzA1MzIyMC8zMDk2NjkyODMtM2VlOGQzZjQtZTM3NS00MTMwLWI5YTYtNTRhOTY0ZWQ4Y2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAwMDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNzZjZjMyODI0YmFlN2Q3ZGJiZDc5ZTFjNjYxZDZjMWQ1MjM5YmQ1YjA1ZjVlZmI4NzI0MjAwM2VlMzdlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzI9h-15hkTABimKtAyv3krdrPpEcoFmtQBPkjVCIKg)

同样的问题，捣鼓了一下午都没好，文件报红好难受啊

**Comment by CH-122** [comment]
> > 怎么个修复法，下午更新了一版，还是有问题
> 
> @HandsomeHan515  安装1.8.27或以下版本试试
> 
> ![](https://private-user-images.githubusercontent.com/6951527/309724889-aa444525-9524-439d-a3cc-58063fa1514d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTc1MTcsIm5iZiI6MTcwOTU5NzIxNywicGF0aCI6Ii82OTUxNTI3LzMwOTcyNDg4OS1hYTQ0NDUyNS05NTI0LTQzOWQtYTNjYy01ODA2M2ZhMTUxNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDAwNjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM2NDUyYzc1YzlkNWM4MDQ4YWI2OGYxYjU4OWMxMTQ5MDg1YzIzMDYzMzgyM2U1ZmI2MzcyOGY0YjAzYjMxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hd9x2V2vLRyveb199welkwryOtBD7iLnK3Y5FuFZk2M)

安装 1.8.27 以下的版本可行

**Comment by xiongchen2012** [comment]
按cmd点击跳转也失效了，感觉这波升级有点崩。
有没有migration guide之类的文档可供参考吗？

**Comment by XiaoDaiGua-Ray** [comment]
最后发现，只需要降级就可以了，别用 `2.x` 版本

**Comment by obj-Rui** [comment]
今天还没解决吗

**Comment by norsl** [comment]
最新的2.0.5可以更新了

**Comment by CH-122** [comment]
> 最新的2.0.5可以更新了

刚试了下最新的还是不行，不知道是不是我的其他配置有问题

**Comment by XXXLeoh** [comment]
> 最新的2.0.5可以更新了

最新的还是不行，我还是装回1.8.27好的

**Comment by CavinHuang** [comment]
不慌，1.8可以满足开发就行，放弃2.x的

**Comment by 15257988874** [comment]
遇到同样的问题，卸载相关的插件，重装了也没用，目前只能降到1.8。

**Comment by ysfscream** [comment]
This is a very urgent issue, I hope the official website can fix it as soon as possible, currently unable to use Vue files in vscode very well.

**Comment by dadaguai-git** [comment]
+1 
只能降级处理

**Comment by superficialcyf** [comment]
我倒是没崩，就是所有检查都一动不动，对的错误全是一个样，只能从2.0.5降级到1.8.27

**Comment by XiaoDaiGua-Ray** [comment]
@so1ve  这边尝试降级虽然可以有正常的类型提示，但是偶尔也会触发服务崩溃问题（重启又会恢复，不像 `2.x` 那样直接完全无法使用。

**Comment by jincdream** [comment]
需要开全局代理，然后回退版本。

**Comment by zhoubhin** [comment]
> @so1ve 这边尝试降级虽然可以有正常的类型提示，但是偶尔也会触发服务崩溃问题（重启又会恢复，不像 `2.x` 那样直接完全无法使用。

我这边降级到2.0基本上没遇到崩溃的问题了，或者直接降到1.8.27，我的是Intel版Mac

**Comment by ye001226** [comment]
降级使用1.8.27就好使了，最新版2.0.6不行

**Comment by xiaolin0088** [comment]
实测更新到^1.8可用 =！=

**Comment by zuiaizengdada** [comment]
> 降级使用1.8.27就好使了，最新版2.0.6不行

我还是不行啊

**Comment by qiaozhu** [comment]
平常恨不得3天2版，这个问题都这么久了 还没解决吗

**Comment by johnsoncodehk** [comment]
> 平常恨不得3天2版，这个问题都这么久了 还没解决吗

這是 VSCode 的 bug 不是我們的 bug，置頂貼跟 changelog 都早就給出解決方案，這樣都弄不來就去用 v1。

**Comment by johnsoncodehk** [comment]
Duplicate of #3962

**Comment by ayedaren** [comment]
我是真的服了 vue的生态越搞越差 天天被这些小毛病搞得烦的要死

**Comment by viogel4** [comment]
怎么vue现在这么烂了？

**Comment by viogel4** [comment]
连提示都没有了。国内程序员的水平一言难尽。

**Comment by so1ve** [comment]
如果你碰到了bug，请开一个新的issue并带上相关日志、环境信息来反馈，而不要在一个已经关闭数月的issue底下回复。

**Comment by Yan2603** [comment]
> > 怎么个修复法，下午更新了一版，还是有问题
> 
> @HandsomeHan515  安装1.8.27或以下版本试试
> 
> ![](https://private-user-images.githubusercontent.com/6951527/309724889-aa444525-9524-439d-a3cc-58063fa1514d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzE4OTUsIm5iZiI6MTczMTU3MTU5NSwicGF0aCI6Ii82OTUxNTI3LzMwOTcyNDg4OS1hYTQ0NDUyNS05NTI0LTQzOWQtYTNjYy01ODA2M2ZhMTUxNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMDgwNjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQwYTk3NzhkMzQ0YzMzMTMyMDAyYTNlZWVlNzFjZTg3MGM1NmI3MDJkYWI0ZmJmMzQ5OWM2OGUxMzY1OTMxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UJUpqZgUeaIvMUwAWY8oOW5XmX4oj5C0_IADJiB22VI)

666，学到了
