### ISSUE TITLE
在 vue-official 中，组件注册为 PascalCase 时，使用 kebab-case 将不能被找到

### ISSUE THREAD

**Issue by lin52025iq** [vuejs/language-tools#3958]
```vue
<template>
    <el-config-provider :locale="zhCn" :button="{ autoInsertSpace: true }">
        <router-view />
    </el-config-provider>
</template>

<script setup lang="ts">
import zhCn from 'element-plus/dist/locale/zh-cn.min.js'
</script>
```
![image](https://github.com/vuejs/language-tools/assets/87741822/b9a3e66a-7fc1-4af6-a902-2a2e539e02fc)

![image](https://github.com/vuejs/language-tools/assets/87741822/10a41969-dfc3-4447-a27e-0e1f0cb28b93)

**Comment by wowsummer** [comment]
+1

**Comment by partiality** [comment]
+1

**Comment by QAQLC** [comment]
降级吧

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: Please let us know if you're still encountering this issue. Otherwise kindly close this one, thanks!
