### ISSUE TITLE
Vue - Official  still uses the vue3 template rules for template syntax validation when specifying vue2.7+ templates.

### ISSUE THREAD

**Issue by curlykay** [vuejs/language-tools#3959]
project envs:
vue : 2.7.16
Vue - Official : 2.0.3

In vue 2.7 `<template>` cannot be keyed,but Vue - Official  now warns:
<img width="747" alt="image" src="https://github.com/vuejs/language-tools/assets/35558285/e21ab3ba-7ca1-4a44-8e12-8dece7998b8f">

The vueCompilerOptions.target has been configured in tsconfig.json to 2.7
<img width="427" alt="image" src="https://github.com/vuejs/language-tools/assets/35558285/afd8bd38-4ce1-4676-aeff-f46352626591">

**Comment by c0lt** [comment]
This worked in 1.8 and makes it hard to use the extension now as it shows "errors" in many files and you don't really know if a file really has an error without checking it.

**Comment by jhxxs** [comment]
> Seems to be fixed in 2.0.7. I don't get the errors anymore. Thanks!

still exsits in 2.0.7

**Comment by adrienWeiss** [comment]
confirmed here that 2.0.7 fixes that false positive error in particular. I will report any other, if any

**Comment by jhxxs** [comment]
> confirmed here that 2.0.7 fixes that false positive error in particular. I will report any other, if any

but why do I still get this error🥲

**Comment by whitexie** [comment]
> > confirmed here that 2.0.7 fixes that false positive error in particular. I will report any other, if any
> 
> but why do I still get this error🥲

turn off hybrid mode.
<img width="763" alt="image" src="https://github.com/vuejs/language-tools/assets/30469146/b528f8b4-81bf-4f3a-ae60-d715f165379e">

**Comment by BB-000** [comment]
Took me way too long to fix this... Eventually I found `vueCompilerOptions`.

Even now I know about it, I cannot easily find info anywhere in the repo / docs about this..! Only way I found it was by trawling through issues... 

There should really be a note about this / Vue 2 support somewhere easier to find...

And then it took me ages to work out why it wasn't working - turning off Hybrid mode made it work. (I'm not even using typescript..!)

**Comment by so1ve** [comment]
Sorry for all theinconvenience, we will improve our document soon

**Comment by JerryinCN** [comment]
version 2.1.10 still get this error🥲🥲🥲Is there a simple and effective way to solve this problem?🥲🥲🥲

**Comment by mikerockett** [comment]
I know 2.x is dead, but not sure if the maintenance burden is high enough to warrant exclusion of 2.7 from allowed values:

<img width="824" height="216" alt="Image" src="https://github.com/user-attachments/assets/c0df14e7-7f7a-4e52-87ee-23cbba1cc9e8" />

Some projects just cannot upgrade…

How can I exclude this warn from VSC?

**Comment by KazariEX** [comment]
@mikerockett You can open a PR to add it back.

**Comment by mikerockett** [comment]
@KazariEX I suppose that putting 2.7 back as an allowed target would not solve the underlying issue, which means https://github.com/vuejs/language-tools/commit/aaa1c68eab41b53a62a11767c7a290ac84e61626 would need to be reverted in full, and I suppose that is just not worth it (hence my question of maintenance burdens). Will just ignore the IDE warns.
