### ISSUE TITLE
jsx代码保存后自动格式化报错

### ISSUE THREAD

**Issue by Mr-Groundhog** [vuejs/language-tools#3964]
![bug](https://github.com/vuejs/language-tools/assets/95111093/24d3e2dd-0b54-4ef3-9d56-b8a7780e3f3a)

**Comment by Mr-Groundhog** [comment]
目前解决的方法是降级降到1.8.27是正常的

**Comment by Mr-Groundhog** [comment]
还有就是不使用vue自带的格式化

**Comment by so1ve** [comment]
lang="jsx'

**Comment by johnsoncodehk** [comment]
Duplicate of #3949
