### ISSUE TITLE
watch 类型错误

### ISSUE THREAD

**Issue by rczdgbg** [vuejs/language-tools#3965]
watch 类型错误

![image](https://github.com/vuejs/language-tools/assets/38928451/dfeb6005-7161-4a6d-aef8-251c05160edf)
s实际是一个number类型才对

**Comment by so1ve** [comment]
Please provide your full code

**Comment by davidmatter** [comment]
Closing this one due to inactivity. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!
