### ISSUE TITLE
Issues encountered when using vue-official

### ISSUE THREAD

**Issue by imddc** [vuejs/language-tools#3968]
In the latest version 2.04, using vue-official 
1. cannot correctly display the component type
2. there is an error: "all destructured elements are unused"

**Comment by imddc** [comment]
![image](https://github.com/vuejs/language-tools/assets/88233704/4fe5d83d-c84e-4e92-99c7-aab9db62ebbe)

**Comment by johnsoncodehk** [comment]
Duplicate of #3942
