### ISSUE TITLE
Using extensing under VS Code Run/Debug does not work.

### ISSUE THREAD

**Issue by cabal95** [vuejs/language-tools#3976]
This might be related to #3928 in that it might be a windows only issue, I won't be able to test on Linux for a couple days. The named pipe JSON file never seems to be created when the extension is executed from inside VS Code - like when you are trying to develop and/or debug the extension.

The named pipe JSON file is created when the extension is used normally. But if I delete it from my AppData folder and then run the extension under VS Code development, it does not get re-created.

I tried setting a VS Code breakpoint in `startNamedPipeServer` but it never seems to resolve the breakpoint, even after attaching to the language server. So there must be some other piece I would need to attach to in order to step through that code.

I am assuming this named pipe issue is why it can't contact the language server and thus why everything comes up red.

![image](https://github.com/vuejs/language-tools/assets/1119863/a4a1798a-da65-4a4c-bdba-531b859e6235)

Note: This was discovered while trying to debug custom extensions being broken in the 2.x release. I will open a new issue for that and see if I can debug that further under Linux.

**Comment by Ilanaya** [comment]
Experiencing the same issue on the windows machine. Everything works fine on the linux.

[Minimal reproduction repo](https://github.com/Ilanaya/volar-starter)
- Step to reproduce:
Preconditions: windows machine
1. `Launch Client`
2. Open reproduction repo in opened window
3. Open any `vue` file

- Actual result:
![image](https://github.com/vuejs/language-tools/assets/74474615/2a31c2fb-93f9-4af1-bd44-cce12baa4d6a)

- Expected result:
No errors

**Comment by DanielViberg** [comment]
This might be the cause for my issues on linux:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

Using vim as client:
![image](https://github.com/vuejs/language-tools/assets/27137435/8ec9c207-f3da-4b5a-b1f0-73543ff02c7c)

**Comment by cabal95** [comment]
@Ilanaya I re-tested this today, 2024-03-31, from master branch and I am unable to reproduce this now. Can you verify if you are still having this same issue? If not I'll close this.

**Comment by Ilanaya** [comment]
@cabal95 yep, you can close

**Comment by cabal95** [comment]
Closing as unable to replicate now so it may have been fixed or was related to something to else.
