### ISSUE TITLE
2.0+ Error in template in nuxt.js not flagged in Vscode

### ISSUE THREAD

**Issue by mmoore99** [vuejs/language-tools#3979]
After upgrading to 2.0+ referencing an undeclared variable in the template of a nuxt.js app does not get flagged. See the screen captures below. The first screen capture is with 1.8.27 installed and shows correctly that recipe2 is an error. The second is with 2.0.4 installed. Note that on the second screen capture "recipe2" is not flagged even though it is not defined in the script. To reproduce just create the default nuxt.js project and make the minor changes to app.vue shown in the screen captures.

![image](https://github.com/vuejs/language-tools/assets/45022/ed825415-647d-4669-b0f0-044f01a9cb99)

![image](https://github.com/vuejs/language-tools/assets/45022/2cd2b680-b6af-44a6-a7e1-e5c2a3e13bf4)

**Comment by davidmatter** [comment]
Is this still an issue in the latest version?
