### ISSUE TITLE
Broken link in VSCode extension readme

### ISSUE THREAD

**Issue by luc122c** [vuejs/language-tools#3980]
The [readme](https://github.com/vuejs/language-tools/blob/3793058ce0205849c6159ba6070ada232c071937/extensions/vscode/README.md?plain=1#L189) and [changelog](https://github.com/vuejs/language-tools/blob/3793058ce0205849c6159ba6070ada232c071937/CHANGELOG.md?plain=1#L988) both point to [https://github.com/vuejs/language-tools-plugins](https://github.com/vuejs/language-tools-plugins). Either the repository is private, or the link is incorrect, as I get a 404 error when trying to visit the page.

**Comment by so1ve** [comment]
The link is incorrect.

**Comment by luc122c** [comment]
@so1ve I'm happy to open a PR if you could tell me what the correct link is please.

**Comment by so1ve** [comment]
Unfortunately I don't know which link is related :(
