### ISSUE TITLE
[Bug Report] No CSS class reference on verson 2.0.4

### ISSUE THREAD

**Issue by floyd-li** [vuejs/language-tools#3986]
Hi there, i upgrade this plugin to 2.0.4 and found the css class reference function is broken. 
someone have any idea?
- 2.0.4
![CleanShot 2024-03-05 at 09 08 58@2x](https://github.com/vuejs/language-tools/assets/16473062/7d9f7f77-93f5-4f2d-867d-f5b18d2c581a)

- and 1.8.x
<img width="969" alt="image" src="https://github.com/vuejs/language-tools/assets/16473062/c8c3a443-3ee7-40ad-a6fc-47870f3b2e36">

**Comment by rayadaschn** [comment]
Downgrade to 1.8.27 for now ==> [#3942](https://github.com/vuejs/language-tools/issues/3942)

**Comment by Nick742037091** [comment]
> Downgrade to 1.8.27 for now ==> [#3942](https://github.com/vuejs/language-tools/issues/3942)

How to downgrade ?

**Comment by rayadaschn** [comment]
Maybe you could read this, Issue [#3953](https://github.com/vuejs/language-tools/issues/3953#issuecomment-1975499100)

**Comment by gegoune** [comment]
Please stop suggesting downgrading on every other issue (not calling names, not suggesting that you do that, but as while collective), it generates a lot of noise for subscribers.
This issue, and many others, specifically target latest release and issues within that release. Reverting back to other version makes no sense here and does not help fixing those issues.

**Comment by YamadaAoi** [comment]
I don't want to downgrade, but I have no choice because the issue still exists after 10 versions have passed
