### ISSUE TITLE
The use of "as" assertion in SFC's template results in code highlighting and errors

### ISSUE THREAD

**Issue by fuxichen** [vuejs/language-tools#3989]
vscode Version: 1.87.0
Vue - Official Version: 2.0.4
No other extensions have been enabled

Using the as of ts in the template to assert types resulted in code highlighting and errors
![image](https://github.com/vuejs/language-tools/assets/17411462/7846fed7-dae5-4474-adca-a2869a039b2c)

![image](https://github.com/vuejs/language-tools/assets/17411462/9c70c433-3f1a-4ef4-af91-189aa36fea20)

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/520
