### ISSUE TITLE
Using  2.0+ version in vue 2.7 project reports error about ts-plugin

### ISSUE THREAD

**Issue by AfireHong** [vuejs/language-tools#3992]
![image](https://github.com/vuejs/language-tools/assets/51915214/b9506de4-6989-493a-ab4b-6b8edb9acf63)

demo: https://github.com/AfireHong/VLS-error-demo

**Comment by Finki007** [comment]
Same for me

**Comment by jwolinsky** [comment]
same

**Comment by kkarasek** [comment]
same for Vue 3 + other errors when Volar for TS got deprecated

<img width="965" alt="image" src="https://github.com/vuejs/language-tools/assets/30701167/ad927ce1-c2f7-4b01-ae44-a0eb73acefae">

**Comment by so1ve** [comment]
Duplicate of #3942
