### ISSUE TITLE
Option click in pug broken in 2.0+

### ISSUE THREAD

**Issue by richardsimko** [vuejs/language-tools#3996]
As mentioned here: https://github.com/vuejs/language-tools/issues/3930#issuecomment-1977283126

While 2.0.5 fixes the "not used" issue it doesn't fix the Cmd/option click to go to definition from a pug template. This worked in 1.8.27.

Hovering to get context is also broken, in 1.8.27 hovering over a function shows a tooltip with type info:

<img width="318" alt="image" src="https://github.com/vuejs/language-tools/assets/1245031/ce5df3ad-adcb-4732-a49e-fb1e5b38be66">

in 2.0+ it does nothing

Both of the above work with plain HTML templates in 2.0+ but not with Pug.

**Comment by richardsimko** [comment]
Hovering to get context is also broken, in 1.8.27 hovering over a function shows the following tooltip:

<img width="318" alt="image" src="https://github.com/vuejs/language-tools/assets/1245031/ce5df3ad-adcb-4732-a49e-fb1e5b38be66">

in 2.0+ it does nothing

**Comment by JayPuff** [comment]
For me 2.0.5 does not even solve the 'never read' problem actually, while still having  the same issues you are having (No validation on ts within pug template, no hover tool tips with type info)

I have this in my `tsconfig.json` as well since it was required before language tools v2.0:

```
"vueCompilerOptions": {
    "plugins": [
      "@vue/language-plugin-pug"
    ]
  }
```

**Comment by JayPuff** [comment]
@richardsimko Check out the recent comment on the task you linked, I fixed this issue by updating `@vue/language-pug-plugin` to the latest version

**Comment by richardsimko** [comment]
That resolved the other issue but not this one for me.

**Comment by richardsimko** [comment]
It seems like the TS Volar plugin is causing the issue (Since it's been deprecated in 2.0). Disabling that fixed the problem.

**Comment by boid-com** [comment]
I'm also seeing this issue, the only intellisense that is working is hovering templates but any variables/props are ignored.
