### ISSUE TITLE
代码能够运行，编辑器爆红

### ISSUE THREAD

**Issue by Hao1617** [vuejs/language-tools#4000]
使用slot-scope时 编辑器爆红 该怎么调
![image](https://github.com/vuejs/language-tools/assets/56282383/95564273-74f7-4ee1-bcd4-f233a73e4f10)

**Comment by MarkSky** [comment]
After updated vue-tsc to 2.0.5, all pinia function get errors: ts-plugin(2339), ts(2339), ts(2769)!

**Comment by Hao1617** [comment]
> 将 vue-tsc 更新到 2.0.5 后，所有 pinia 函数都会出现错误：ts-plugin(2339)、ts(2339)、ts(2769)！

我应该将Vue - Official切换到哪个版本

**Comment by qhl123456** [comment]
> > 将 vue-tsc 更新到 2.0.5 后，所有 pinia 函数都会出现错误：ts-plugin(2339)、ts(2339)、ts(2769)！
> 
> 我应该将Vue - Official切换到哪个版本

切换到1.8.7可以正常使用

**Comment by Hao1617** [comment]
> > > 将 vue-tsc 更新到 2.0.5 后，所有 pinia 函数都会出现错误：ts-plugin(2339)、ts(2339)、ts(2769)！
> > 
> > 
> > 我应该将Vue - Official切换到哪个版本
> 
> 切换到1.8.7可以正常使用

感谢

**Comment by Ttou** [comment]
同样的问题，看来目前只能先降级了

**Comment by Hao1617** [comment]
> 相同的问题，目前看来只能先降级了
![image](https://github.com/vuejs/language-tools/assets/56282383/17edf0e2-58b8-4e7b-a839-719fc2113d13)
没有1.8.7版本了

**Comment by so1ve** [comment]
Please provide a reproduction

**Comment by so1ve** [comment]
@Hao1617 1.8.27

**Comment by davidmatter** [comment]
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!
