### ISSUE TITLE
Vue-Official DON'T support vue-property-decorator ???

### ISSUE THREAD

**Issue by tanyioO** [vuejs/language-tools#4003]
error says: 
类型“CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>”上不存在属性“formData”。ts-plugin(2339)

**Comment by so1ve** [comment]
Yes
