### ISSUE TITLE
JS/TS 语言服务已立即崩溃 5 次。不会重新启动该服务。 

### ISSUE THREAD

**Issue by zhenhua001** [vuejs/language-tools#4004]
JS/TS 语言服务已立即崩溃 5 次。不会重新启动该服务。 这可能是由以下其中一个扩展提供的插件引起的: Vue.volar 请在针对 VS Code 提交问题之前尝试禁用这些扩展。

报这个错误 重新安装插件Vue - Official和重新安装vscode都不行

**Comment by zhenhua001** [comment]
系统 mac

**Comment by zyhnbyyds** [comment]
add old version 1.8.27

**Comment by xfchenju** [comment]
This extension is deprecated. Use the Vue - Official extension instead.

**Comment by MWanGxC** [comment]
M1 pro, 退回2.0以下的版本就好了

**Comment by GalensGan** [comment]
回退版本也不是办法呀，有哪位大佬发现是什么原因吗？
