### ISSUE TITLE
pkg:2.0.5 In big project, it is very slow to show the prompts. pkg:1.8.27 show smoothly

### ISSUE THREAD

**Issue by zyhnbyyds** [vuejs/language-tools#4005]
In large projects(about dozens to hundreds of pages.), the plugin's prompts are very slow, and I'm not sure if something is blocking it. The IDE's prompts take about 5 seconds, without any errors appearing. If there are errors, it will freeze for a long time. I downgraded the version to 1.8.27, and everything is running smoothly, with timely prompts as well.😫

I test a init project, it works well.

**Comment by IVanMissAya** [comment]
I also encountered the same situation

**Comment by sinpor** [comment]
The performance is good after I downgraded to `2.0.4`.

**Comment by hotdogc1017** [comment]
Me too

**Comment by stormzhangbx** [comment]
I encountered the same situation too, downgrade to 2.0.4 will ok.

**Comment by parox2014** [comment]
Me too

**Comment by yuqibin** [comment]
同，代码提示出来太慢了 ，已卸载

**Comment by GabrielHangor** [comment]
Can confirm that 2.0.4 works fine, issue is with 2.0.5

**Comment by medvesekg** [comment]
I had the same issue, reverting to 2.0.4 solved it.

**Comment by pm0u** [comment]
Same here. I was also occasionally getting TS warnings that `"Type instantiation is excessively deep and possibly infinite"` when creating types for Pinia stores. The error no longer is popping up and the speed is greatley improved in 2.0.4

**Comment by niaodan2b** [comment]
In my case (project with 2700+ files in /src), v2.0.4 already slower than v1.8.27 (1 sec vs instant), and v2.0.5 is much more slower (10+ sec).
So maybe not purely 2.0.5 issue?

**Comment by so1ve** [comment]
In the preview feedback thread(https://github.com/vuejs/language-tools/discussions/3789) we've received positive comments that the performance got a great improvement, however 2.0.5 upgraded volar.js and that may cause a performance regression.

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4024
