### ISSUE TITLE
There are so many questions that I don’t know where to start.

### ISSUE THREAD

**Issue by lxccc812** [vuejs/language-tools#4007]
Including but not limited to the following issues：

Tags such as <script> and <template> cannot be folded normally
![image](https://github.com/vuejs/language-tools/assets/110974969/6cf9e583-a2bd-446d-97cd-9accf612f780)
![image](https://github.com/vuejs/language-tools/assets/110974969/e7e692bf-8bfd-4a07-8b72-4a0adc31b2b0)
No folding sign

H5 tag prompt is too slow. When a function name is declared in <template> but the function is not declared in <script>, no error message appears.
Error messages are delayed. The vue file needs to be reloaded to prompt normal errors.

The component cannot be recognized, and the vue file needs to be reloaded to solve the problem.

Vue - Official: v2.0.5
VsCode: February 2024 (version 1.87)

**Comment by so1ve** [comment]
Please track the folding issue at https://github.com/vuejs/language-tools/issues/4023.
