### ISSUE TITLE
在过去5分钟内，js/ts语言服务崩溃了5次

### ISSUE THREAD

**Issue by manbill** [vuejs/language-tools#4015]
![企业微信截图_81e2cc84-7275-49e1-83c2-f49b4bb3f3b9](https://github.com/vuejs/language-tools/assets/17213454/38f2f55a-0b22-4c3b-84eb-a62bd1f72056)
Type: <b>Bug</b>

运行ts的项目，.vue文件

Extension version: 2.0.5
VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (4.43GB free)|
|Process Argv|--crash-reporter-id 0408dfd2-256d-4fa8-905e-d1f7c03fdacd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30973843
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by RainMeoCat** [comment]
嘗試將版本回滾到1.8.27可以解決這個問題

**Comment by a1burning** [comment]
现在1.8.27版本弃用了

**Comment by manbill** [comment]
目前还可以安装，能正常运行了，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月6日(周三) 晚上6:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vuejs/language-tools] 在过去5分钟内，js/ts语言服务崩溃了5次 (Issue #4015)




 
现在1.8.27版本弃用了

**Comment by parox2014** [comment]
退回到2.0.4可以工作

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/3957
