### ISSUE TITLE
升级后，ts文件内无法使用ctrl+/快捷键注释代码

### ISSUE THREAD

**Issue by siren-H** [vuejs/language-tools#4018]
在ts文件和vue文件的script中都无法用快捷键ctrl+/注释代码，在html中可以正常使用快捷键注释代码

**Comment by siren-H** [comment]
![snipaste_20240306_174020](https://github.com/vuejs/language-tools/assets/74636071/446f001c-2c48-4a2f-82b4-186597fa52b6)
我的快捷键设置是没问题的，并且在html文件内也能正常使用

**Comment by meesii** [comment]
同样的问题，需要重启vscode才可以注释。

**Comment by lucidkodo** [comment]
restarting both vscode and my mac don't work.

**Comment by siren-H** [comment]
![snipaste_20240307_105319](https://github.com/vuejs/language-tools/assets/74636071/614ecedb-fa3b-4c3b-9b7e-98e9b63b5c9f)
尝试回退到其他issue中推荐的1.8.27版本，仍旧无法注释

**Comment by s3xysteak** [comment]
这似乎是github copilot的bug，在你使用ctrl + enter打开copilot的建议，再回到原来的页面后，ctrl + /就会失效。使用ctrl + \打开新窗口然后关闭就能解决这个问题

**Comment by siren-H** [comment]
将vscode快捷键恢复默认设置，卸载重装插件，并重启vscode之后解决了。
猜测确实像三楼朋友说的那样，刚开始只要重启vscode就好了，但由于这个问题出现的时候我先重新配置了一遍快捷键，导致重启大法反而不生效，恢复默认快捷键之后反而好了

**Comment by johnsoncodehk** [comment]
The Vue extension does not change the shortcut key behavior, please submit an issue to VSCode and be sure to describe how to reproduce.
