### ISSUE TITLE
v2.0.5，每个.vue文件在VSCode都报错

### ISSUE THREAD

**Issue by linyxria** [vuejs/language-tools#4021]
Variable '__VLS_23' is used before being assigned.ts-plugin(2454)
Block-scoped variable '__VLS_23' used before its declaration.ts-plugin(2448)

所有文件都是类似这样的报错

**Comment by so1ve** [comment]
Duplicate of #3942

**Comment by linyxria** [comment]
禁用 vscode-styled-components 这个扩展解决了我的问题

**Comment by codeflyA** [comment]
> 禁用 vscode-styled-components(组件) 这个扩展解决了我的问题

谢谢 起效了
