### ISSUE TITLE
升级到这个插件后，代码提示变得超级慢，大概有3秒的延迟才弹出代码建议框

### ISSUE THREAD

**Issue by seifenk** [vuejs/language-tools#4030]

**Comment by abb-uu** [comment]
metoo

**Comment by wen403** [comment]
vscode还时不时崩溃，希望赶快优化吧，开发体验下降了
![image](https://github.com/vuejs/language-tools/assets/67454874/5d8c0d07-fcb3-4177-989e-38ff9f04e900)

**Comment by MoScl** [comment]
我也是，降低版本或者禁用掉 就可以了，找了一天，才发现是vue的插件，从此对官方的插件失去了信任

**Comment by ImmutableTS33** [comment]
对的，代码提示有延迟很不舒服，一开始以为是电脑后台开太多东西了，看了下内存占用就50%左右。而且新版标签颜色也变红了。目前回退到1.8.27就正常

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4024
