### ISSUE TITLE
升级插件后插件功能延时巨高(3秒以上)，且导致VC卡顿甚至卡死，旧版本还不支持回退...

### ISSUE THREAD

**Issue by 734275083DW** [vuejs/language-tools#4031]

**Comment by 3octaves** [comment]
试下开vpn来获取历史版本列表

**Comment by warmthsea** [comment]
如果你要退回，请检查自己的网络，或者点击（安装另一个版本..）后等待

![image](https://github.com/vuejs/language-tools/assets/45450994/50aa1a58-b537-42c5-bdc9-678c7a13a745)

**Comment by siren-H** [comment]
> 如果你要退回，请检查自己的网络，或者点击（安装另一个版本..）后等待
> 
> ![image](https://private-user-images.githubusercontent.com/45450994/310728220-50aa1a58-b537-42c5-bdc9-678c7a13a745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Nzk4NjEsIm5iZiI6MTcwOTc3OTU2MSwicGF0aCI6Ii80NTQ1MDk5NC8zMTA3MjgyMjAtNTBhYTFhNTgtYjUzNy00MmM1LWJkYzktNjc4YzdhMTNhNzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyNDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OTE0Yzk3ZjllMWI0NWM2ZjQwYWU0MDMxNTdhZmRiYTc0YmM0ZWM2YjVjODVjNGE5MWJhN2RkNzQ2NzBkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YarJPlcwwM8WrZ4WDOUEc8hLEGVe_pFH9EozgUWXBa0)

点击选择安装另一个版本之后，没有弹出任何界面，但其他插件是可以正常选择版本的

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4024
