### ISSUE TITLE
插件快点更新回之前的

### ISSUE THREAD

**Issue by 16050500134xc** [vuejs/language-tools#4032]
明明volar那么好用为啥弃用它更新新的插件，自动联想贼卡，整段自动折叠没了，模板定位css功能也没了，更新的什么锤子

**Comment by warmthsea** [comment]
1、这次更新是 Volar 大版本更新，深度集成 TS，修复或者解决了以前非常多问题，.vue文件也更接近.ts 的体验
2、大规模的用户涌入，在未发布前不可能会都一一解决或者测到（例如我这里基本没有什么问题，但是有些用户可能会出现卡死等情况）
3、如果你的问题现在没有解决，你可以翻issus寻找解决方案，或者你可以选择降回 1.8.27 版本
4、请理解并尊重OSS社区

**Comment by 16050500134xc** [comment]
怎么降回 1.8.27 ？用回Volar提示该插件已被弃用强制更新到了Official

**Comment by warmthsea** [comment]
> 怎么降回 1.8.27 ？用回Volar提示该插件已被弃用强制更新到了Official

https://github.com/vuejs/language-tools/issues/4031#issuecomment-1982234947
