### ISSUE TITLE
如果vscode中，代码提示很慢，可以通过以下方式解决。

### ISSUE THREAD

**Issue by swift-fs** [vuejs/language-tools#4034]
我查找了一天的问题，定位到是插件版本问题，插件版本低于2.0.5时，问题迎刃而解。
如何安装其它版本插件：
1. 打开vscode的扩展界面
2. 安装vue - official
3. 在卸载按钮下拉有其它版本可下载
4. 禁用插件自动更新。

![image](https://github.com/vuejs/language-tools/assets/77133741/645ee205-09be-41ae-bf6a-de24cc92d12b)

**一定要禁用插件自动更新**
**期待下个版本可以得到修复**

**Comment by eiinu** [comment]
遇到了相同的问题。
2.0.5 版本代码提示非常慢，2.0.4 版本正常。

**Comment by Psilocine** [comment]
thanks，降级2.0.4重启 vsc，得到缓解

**Comment by gitdoit** [comment]
已经退回, 只是单纯的想知道是什么原因导致的

**Comment by wangxiaoming-1997** [comment]
最好退回1.87,点击样式跳转的功能也没了

**Comment by TkJiangBo** [comment]
昨天装了一个插件,今天提示非常卡,排查半天原来是你小子更新了

**Comment by so1ve** [comment]
Fixed by https://github.com/vuejs/language-tools/commit/dd76471bd93b990404c8507e00584be7d87cde87

**Comment by changzhengithub** [comment]
真的服了，从Volar更新到Vue-Official然后ts提示全没了，文件全部报错，更新不测试一下吗
