### ISSUE TITLE
The folded area will automatically expand when typing codes

### ISSUE THREAD

**Issue by tsdd** [vuejs/language-tools#4035]

**Comment by tsdd** [comment]
I hope I can use volar instead of this new vscode plugin

**Comment by warmthsea** [comment]
If it currently affects you a lot, you can choose to return to version 1.8.27.
https://github.com/vuejs/language-tools/issues/4031#issuecomment-1982234947

**Comment by warmthsea** [comment]
> I hope I can use volar instead of this new vscode plugin

This is not a new plugin, it just changed the nickname.

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4023
