### ISSUE TITLE
在过去 5 分钟内，JS/TS 语言服务崩溃了 5 次。 这可能是由以下其中一个扩展提供的插件引起的: Vue.volar 请在针对 VS Code 提交问题之前尝试禁用这些扩展。

### ISSUE THREAD

**Issue by Zhang-Wei-666** [vuejs/language-tools#4036]
在过去 5 分钟内，JS/TS 语言服务崩溃了 5 次。 这可能是由以下其中一个扩展提供的插件引起的: Vue.volar 请在针对 VS Code 提交问题之前尝试禁用这些扩展。

![image](https://github.com/vuejs/language-tools/assets/37876877/52526104-1c35-4cef-abf6-cf490be4d554)

![image](https://github.com/vuejs/language-tools/assets/37876877/b9fa7ee0-7523-4af3-b2b6-98ad9955e190)

**Comment by ms-mayya** [comment]
Upgrade TypeScript plugin to:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next
might resolve the issue.
For me, it seems to work fine.

**Comment by ms-mayya** [comment]
But, intellisense is still slow(3s)

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/3962

**Comment by hervey0424** [comment]
> Upgrade TypeScript plugin to: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next might resolve the issue. For me, it seems to work fine.

very ok

**Comment by frankie-zeng** [comment]
> But, intellisense is still slow(3s)

slow tool, any workaroud way to speed up it.
