### ISSUE TITLE
Issues after upgrade to v2

### ISSUE THREAD

**Issue by angelhdzmultimedia** [vuejs/language-tools#4037]
Disabled **TypeScript Vue Plugin** as per the deprecation notification.
Now lost Vue highlighting in SFC, and the `Volar Restart Language Server` is lost in command palette.

Downgraded from 2.0.5 to 2.0.4 and same issue. What now? 💚💙🩵🔥

**Comment by so1ve** [comment]
> Volar Restart Language Server is lost in command palette

We've migrated to TS Plugins and there's no language server.

> Now lost Vue highlighting in SFC

Have you installed the `Vue - Official` (vue.volar) plugin?

**Comment by angelhdzmultimedia** [comment]
### Solved

It solved after a system shutdown. I didn't manage to solve it just by restarting VSCode. Updated back to 2.0.5.

### New Question (related to original question)
Now my question is where's the Volar Restart Language Server command? It's missing.
![image](https://github.com/vuejs/language-tools/assets/10191085/4ceefb4f-dd09-4665-89c9-f8cbaa1f2696)

How to restart Volar language server now when something is not working?

**Comment by so1ve** [comment]
> How to restart Volar language server now when something is not working?

Currently not possible I think?
