### ISSUE TITLE
V.2.0.6 - Long wait time to see vue-tsc output

### ISSUE THREAD

**Issue by DNeosphere** [vuejs/language-tools#4046]
Hi :)
I have node ^20 version installed, vue-tsc 2.0.6.

I am having to wait more than 6 minutes to see a result when I run this command `npx vue-tsc --noEmit` 

When I build the Vue app, the vue-tsc command works as expected :s. Is there something different in the way that vite executes the command when building?

Is it something wrong with my configuration?

**Comment by brc-dd** [comment]
Vite doesn't run vue-tsc while building. Is the issue with v1.8 of vue-tsc too? Can we reproduce this on any public repo?

**Comment by johnsoncodehk** [comment]
Close as no response.
