### ISSUE TITLE
Return deletes the line above... in v2, but ok in v1.8.27

### ISSUE THREAD

**Issue by midlantica** [vuejs/language-tools#4047]
Type: <b>Bug</b>

I'll have some code:
let emitSwitchView = (view) => {
  selectedBtn.value = view
  emits('switch-view', view)
};

Cursor I-beam at end of line 2, hit return and it does this, literally removing code!?:
let emitSwitchView = (view) => {

    emits('switch-view', view)
  };

Turning off the Vue - official extension does fix that problem, but now ALL of my code is white... 

Help! 

Extension version: 2.0.6
VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 6, 5|
|Memory (System)|32.00GB (1.56GB free)|
|Process Argv|--crash-reporter-id 144b3b17-81ef-4e23-a8e1-ac1d61824d10|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30981707
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by midlantica** [comment]
I figured out I could install and older version an tried it... Issue in v2, but ok in v1.8.27.

**Comment by etellep** [comment]
I was having the same issue. Disabled all my extensions aside from this one and it was still happening. Reverting to v1.8.27 resolved the issue for me as well.

**Comment by so1ve** [comment]
Should work fine now?

**Comment by davidmatter** [comment]
Closing this one due to inactivity. Feel free to create a new issue if you're still having issues with the latest version, thanks!
