### ISSUE TITLE
Incorrect Union Types Suggestions in Vue + TypeScript Project in VSCode

### ISSUE THREAD

**Issue by matvejs16** [vuejs/language-tools#4053]
When working on a Vue + TypeScript project in VSCode, I've noticed that the union types suggestions are not working correctly. I have defined a union type for a component's props, but when I try to use component in the code and providing there props, there is no suggestion that I'm doing something wrong, the suggestions for the props don't mind if I will remove ``quantity`` or ``sum`` prop.

How it should work:
```vue
<smallCard // syntax error giving info that prop `sum` or `quantity` should be defined
    :icon="'uil uil-euro-circle'"
    :link="'/admin/sales'" />
```

Also in case I provide ``sum`` prop:
```vue
<smallCard // syntax error giving info that prop `prev_quantity` should not be here
    :sum="32"
    :prev_quantity="860"
    :icon="'uil uil-euro-circle'"
    :link="'/admin/sales'" />
```

Code: [Example](https://play.vuejs.org/#eNq1VN9v0zAQ/lcsvxSkLUEMIRRlRTDtAR5gAh4toZBcizfHNva5dCr537lzSNeyddKk7aFS7/vux3e+u2zkO++LVQJZyTq2QXsUETD5ubK69y6Q2TfGnDWhE4vgejErSoSIZ67PcTNl63IMpBAyEHpvGgSyhKhvgtkUovqVGosar0+VPHmp5D/UB1h9v5vSrbOEzJI2gn7H2q6cbqnu5GC0vWKHsul6bUsXOgiRaFE+SMLj18lNxdRT0JvXLw4WghTccatDaw4Xi42Be2s9QZma5rwdpTySGCnjQi+Ly+gsrcuGcyjZ0iJoA+GzR+1sVLISmWGORLrfHzOGIcHRhLc/ob26A7+Ma8aUvAgQIaxAyS2HTVgCjvT510+wpv9bsnddMuR9D/kFojOJNY5u75PtSPaOX1b7IS+9tstv8XyNYOPUFAtlzyH7K0m7zzdwqPUbuSfFqxyn7MCvuHM7fHN758KT9Y2dbzbCB+djwfMRw0AXxvB/MyFz92KFaeyShokkhFi89iC4krNg8YLTidNR33QAlbCp/wEhd7R3gm/3KF6lSkQM9CwZYFkTQG2JP2NeWsLbKQl8WDZujFwijm9AojtYaAu5hXq/o/mz5zvfHzn8Ba5jmGo=)

Using:
``Vue - Official`` - v2.0.6

**Comment by matvejs16** [comment]
Anyone can help with this?

**Comment by KermanX** [comment]
This is not related to the Vue language tools. It seems that the Vue compiler can't analyze union prop types correctly. Please open an issue in https://github.com/vuejs/core. Thanks!
