### ISSUE TITLE
Language server critical regression from 2.0.5 to 2.0.6

### ISSUE THREAD

**Issue by aentwist** [vuejs/language-tools#4054]
## Actual

Hi, I am facing some critical language server issue on 2.0.6. It was a very mysterious issue, so after seeing 2.0.6 is a new release I decided to regress to 2.0.5, which does not have this problem as it turns out.

I'm not sure what information is needed, if any, but I am willing to provide the required details.

![repro](https://github.com/vuejs/language-tools/assets/46688047/34cff34a-7bbb-4eca-a89d-ffdbebc2c3a2)

## Expected

Language server works; installing 2.0.5 and reloading does this

###### Volar (vue.volar)

2.0.6

###### VSCode

```
Version: 1.87.1 (user setup)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:36.258Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```

###### Remote

WSL Deb 12

**Comment by aentwist** [comment]
My colleagues do not seem to be having this issue but it is consistent for me. Feedback appreciated

**Comment by NothingEverWorks** [comment]
Same issue for me in Nuxt. Vue highlighting is not working in 2.0.6.

![image](https://github.com/vuejs/language-tools/assets/109553594/4a0f9ce5-078e-4864-90f1-b0564d624fb1)

The fix is to revert back to Vue - Official 2.0.5

**Comment by pm0u** [comment]
Just upgraded to 2.0.6 this morning on a vue/webpack project and am not seeing this issue.

I have a separate vue/nuxt project that seems to have lost all typing for any imported components or nuxt builtins though.

```
    "nuxt": "^3.10.3",
    "vue": "^3.4.19",
```

**Comment by aentwist** [comment]
Not Nuxt related I'm on Vue / Vite (Rollup)

**Comment by pm0u** [comment]
Got it - in my case it was due to #3942 - having the styled-components extension installed.

disabling `styled-components.vscode-styled-components` resolved, does not seem to be Vue extension version related. I was able to use v2.0.6 once I disabled.

**Comment by so1ve** [comment]
[Should ](https://github.com/vuejs/language-tools/pull/4119)
