### ISSUE TITLE
No suggestions for Components Props

### ISSUE THREAD

**Issue by mhzsam** [vuejs/language-tools#4059]
hi 
one important problem is when i migrate from Volar & Vetur  to this i did not seen any suggestions  for Components  props

**Comment by anegelya** [comment]
Same here. Downgraded to `v1.8.27`

**Comment by mhzsam** [comment]
thank you very much. the problem solved - why new version does not have this feature??

**Comment by lovesnsfi** [comment]
I have the same problem, how can I solve it?

**Comment by so1ve** [comment]
@mhzsam This is a bug. So I reopened this issue.

**Comment by mhzsam** [comment]
> I have the same problem, how can I solve it?

I downgrade to v1.8.27 and all things its OK

**Comment by hansonfang** [comment]
I've downgraded to 1.8.27 but still no intelliense for `*.vue` files, even I wrote the wrong import path intentionally it didn't give any error:
<img width="643" alt="image" src="https://github.com/vuejs/language-tools/assets/22868119/cc96378f-52f8-4d57-894e-b007af1ab07b">

**Comment by so1ve** [comment]
Let's track at https://github.com/vuejs/language-tools/issues/4074 since it is more detailed.

**Comment by so1ve** [comment]
Ugh they are not the same :(

**Comment by Sandros94** [comment]
Are there any logs that I could provide to be useful to debug this?

This issue has been affecting the DX of [`@nuxt/ui` (issue #1501)](https://github.com/nuxt/ui/issues/1501) since volar `2.0`

**Comment by Sandros94** [comment]
With `2.0.10` locally defined components do seem to be correctly resolved, while dep ones still aren't.

**Comment by manchenkoff** [comment]
I also noticed weird behavior, maybe it will help, for example, I use Nuxt UI, and in `.nuxt/components.d.ts` it resolves only `client` components:

```
// works fine
'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']

// doesn't work
'UModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
```

Extension version - 2.0.10
Nuxt UI version - 2.15.2

**Comment by UfukUstali** [comment]
> I also noticed weird behavior, maybe it will help, for example, I use Nuxt UI, and in `.nuxt/components.d.ts` it resolves only `client` components:
> 
> ```
> // doesn't work
> 'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
> 
> // works fine
> 'UModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
> ```
> 
> Extension version - 2.0.10 Nuxt UI version - 2.15.2

Form what I could figure out the reason Modals.client.vue works is because in the built source code it doesn't have an accompanying `.vue.d.ts` file.

I came to this conclusion because any component that when built is split into `.vue` and `.vue.d.ts` files seems to have their types broken while the ones that are split as `.mjs` and `.d.ts` files are still working.

Then I tried writing a component myself in application code both with `MyComp.vue` and `MyComp.vue.d.ts`, when I do that `MyComp.vue` file seems to take precedence, only when the `MyComp.vue` file is deleted does the type system fallback to the `MyComp.vue.d.ts` file and display the types correctly. 

This still doesn't explain why the types would be `any` though when the component lives inside a package instead of application code or does this makes sense for some reason I'm not aware of.

Even though this doesn't definitively explain the stuation with `UModals` it does seem related. So I wanted to offer my two cents.

**Comment by manchenkoff** [comment]
Yep, with 2.0.14 it seems fixed

**Comment by Sandros94** [comment]
I only now had time to upgrade from `2.0.10` to `2.0.17` and can also confirm it seems to be fixed.

Tested with Nuxt:
- local components
- remote components (layers via path, git and npm)
- npm components

**Comment by kingyue737** [comment]
Not fully fixed. Directly typing `ctrl-J` will give suggestions, but if I type some characters, the extension fail to give any suggestion.

![image](https://github.com/vuejs/language-tools/assets/40021217/4cb89c68-f826-4b63-a85a-11df50a4edb0)

![image](https://github.com/vuejs/language-tools/assets/40021217/f2d9fdc3-f221-4dfe-bf2b-1a289428fd0b)

**Comment by Sandros94** [comment]
@kingyue737 I might be wrong, but it seems to me an extension conflict. Could you quickly test disabling all the extension but `Vue - Official`?

(I also imagine your `ctrl+j` being a custom binding)

**Comment by kingyue737** [comment]
My bad, not `ctrl+j`, it is `ctrl+space` which is the default keybinding for triggering suggestions. It does work currently but a little strange.  I need to wait 1 ~ 2 seconds (which seems much longer than v1.8.27) before the extension gives suggestions automatically. If I press `ctrl+space` to manually trigger suggestions before this "1~2 seconds", it will show "no suggestions":

1. Wait for suggestions (Work):
![bug1](https://github.com/vuejs/language-tools/assets/40021217/0e5b3981-1cb1-45ae-8efd-ef95f86c1e0d)


2. Trigger suggestions manually (Not work):
![bug2](https://github.com/vuejs/language-tools/assets/40021217/109d2bde-c637-4513-a2fe-e36d7a588347)


I will investigate whether it is related to extension conflict or the mode of `Vue - Official`

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: Please let us know if you're still encountering this issue. Otherwise kindly close this one, thanks!
