### ISSUE TITLE
Strange situation after 2.0 where syntax highlighting and scrolling go together

### ISSUE THREAD

**Issue by lvzhenbo** [vuejs/language-tools#4062]
I want to use a GIT image to illustrate the problem, please pay attention to the color (in order to prevent the interference of third-party themes, I have switched to vscode's built-in theme)
![动画](https://github.com/vuejs/language-tools/assets/32427677/4407935b-60fd-4901-98b6-418401bb1fbe)

**Comment by mybearworld** [comment]
Is this #3935?

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/3935
