### ISSUE TITLE
`CTRL` + `click` can't go to define in `.vue` files on HTML tag attribute

### ISSUE THREAD

**Issue by tsdd** [vuejs/language-tools#4064]

**Comment by lovesnsfi** [comment]
downgrade to 1.8.27

**Comment by whitespacecode** [comment]
Having the same issue. 
Got a depreciation warning for the [Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)
So i installed the Vue - Official and nothing works ?!

Thank you @lovesnsfi. By downgrading cmd + click works again

**Comment by PeakJ** [comment]
fixed in 2.0.7, just upgrade

**Comment by whitespacecode** [comment]
> fixed in 2.0.7, just upgrade

Nope, still doesn't work.

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: If you're still encountering issues, please provide a minimal reproduction. Otherwise kindly close this one, thanks!
