### ISSUE TITLE
Since version 2, HTML tags inside Vue component template are not foldable

### ISSUE THREAD

**Issue by Tamas-hi** [vuejs/language-tools#4069]
As the title say, here is a screenshot. On line 97 I can't fold the content, and I can't do it for any of the HTML tag.

![image](https://github.com/vuejs/language-tools/assets/36476318/e7dc344d-e2ab-4f18-bedc-c867b8c2c306)

**Comment by davidmatter** [comment]
I've looked into this one. This doesn't seem to be an issue anymore in the latest version. Feel free to create a new issue if you're still having problems, thanks!
