### ISSUE TITLE
Semantic Tokens are misplaced with language-plugin-pug

### ISSUE THREAD

**Issue by CS-Birb** [vuejs/language-tools#4070]
Pug performance with the latest language-tools and language-plugin-pug is great, but the new semantic tokens handling seems to be misapplied.

A few visual examples:

In pug
![image](https://github.com/vuejs/language-tools/assets/5267414/1b19ab84-4e0a-4518-91a9-ab6c9e3d9a91)

vs HTML
![image](https://github.com/vuejs/language-tools/assets/5267414/aaef1a00-768b-4db7-9161-9122ec03a962)

To try and create a minimal reproduction, I've generated the `vue-ts` vite template and converted the two components to pug templates.
https://stackblitz.com/edit/vitejs-vite-f7dgtx

In HTML we have the `HelloWorld` component highlighted as expected.
![image](https://github.com/vuejs/language-tools/assets/5267414/0b158003-9d08-4747-b34c-96d2ea2afb9a)

While in pug the semantic token is instead applied over the `div` and `a` tags.
![image](https://github.com/vuejs/language-tools/assets/5267414/29a69e18-5332-4e7f-8560-c4afc1280d57)

---

Win10
Vscode 1.87.1
@vue/language-plugin-pug 2.0.6

**Comment by fengjac** [comment]
Same issue.
The color of component name should be green

Vscode 1.87.2
@vue/language-plugin-pug 2.0.6
Vue.volar 2.0.6

![image](https://github.com/vuejs/language-tools/assets/20239780/91ecc8d8-8f86-405e-a9a8-860842edadf4)
