### ISSUE TITLE
v2.0.0 - v2.0.6 shows every object property for Typescript intellisense (VS Code)

### ISSUE THREAD

**Issue by michaelangeloio** [vuejs/language-tools#4073]
I'm not sure if this is a Vue, VSCode, or TS Language Server issue, but I thought I'd post it here for visibility. 

https://github.com/vuejs/language-tools/assets/55844504/855769ba-8cb2-4973-9c13-65bcdb6d21a0

TLDR; any time you wish to get Intellisense autocomplete (ctrl + space on mac, or using dot notation), it shows every object property available (including the DOM type, it seems). 

Repro steps: simply create a new typescript project via `npm create vue@latest`, and install the latest Vue language server (`2.0.6` at the time of posting this issue). 

This definitely makes the extension unusable. 

**Temporary solution**: downgrade below 2.0.0.

**Comment by RiESAEX** [comment]
Duplicate of #4039

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4039
