### ISSUE TITLE
I found a really disgusting problem. Once the string in curly braces is formatted, it wraps itself.

### ISSUE THREAD

**Issue by zhanghengxin** [vuejs/language-tools#4088]
I found a really disgusting problem. Once the string in curly braces is formatted, it wraps itself.

![image](https://github.com/vuejs/language-tools/assets/24197448/a49a8e9f-271f-4ebb-9549-ff2ed4bb92d0)

formated：
![image](https://github.com/vuejs/language-tools/assets/24197448/b84d1312-a962-4713-8570-d61c851a2af6)

**Comment by johnsoncodehk** [comment]
We will not handle this rude issue, please respect the open source community and maintainers.
