### ISSUE TITLE
`<style>` completions and html custom data completions not provided in some cases

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#4092]
I have a project that provides completions for the `class` attribute using [custom data](https://github.com/rchl/vue-completions-bug/blob/main/test.html-data.json) format. Volar provides those completions (`aaa`) when class attribute value is empty or after a space but not when there is already a character inserted (even if it matches the completion).

Here is a screencast (it's supposed provide both `aaa` and `aaa-local` in both cases:

https://github.com/vuejs/language-tools/assets/153197/79774956-cd1c-4b05-82e8-ac89d094e943

Note also the inconsistent behavior with providing component-local `aaa-scoped` completion. It's provided when the custom data completions are not provided and vice-versa.

Note2: In the 2.0.6 version the component-local classes are not suggested at all which seems like a separate bug. I've made the video using 1.x version.

Steps:
1. Clone repo: https://github.com/rchl/vue-completions-bug
2. install dependencies
3. Open `App.vue`
4. Trigger completions within the `class` attribute when value is
 a) empty
 b) "a"

The issue is most likely around https://github.com/volarjs/volar.js/blob/15cf7fd2940938fb47c33a1db98d0173168064ee/packages/language-service/lib/languageFeatures/complete.ts#L150-L154 where it exits early and doesn't ask services for completions.

**Comment by rchl** [comment]
@johnsoncodehk what is the logic for determining which service returns the `mainCompletion` supposed to be in https://github.com/volarjs/volar.js/blob/15cf7fd2940938fb47c33a1db98d0173168064ee/packages/language-service/lib/languageFeatures/complete.ts#L169 ? It feels a bit random that it's set to URI of the current virtual document based on whichever service returns completions first. It seems to result in completions being omitted.

**Comment by rchl** [comment]
Not setting the `cache.mainCompletion` so that the caching logic is never used makes things work as expected in this case at least. I suppose it might result in some duplicates, at least according to the comments in the code, but I'm not sure how to trigger that case. None of the tests fail either with that change.

Is the old Volar repo, before being split into separate repos, available somewhere? As it is now it's impossible to blame the lines and find the reasoning for any change since the history was lost during the transition.

**Comment by johnsoncodehk** [comment]
This issue mixes several problems.

1. `parseCssClassNames` did not capture `aaa` in the following code.

```css
.aaa,
.bbb {
  color: blue;
}
```

This was fixed in https://github.com/vuejs/language-tools/commit/3be60c650b6bbea52ee6d315e6314b931d84701d#diff-f24244b7d2c995ef747db56b1010b8f4a484b8c458f6fe93d7db3d8691e7fe9aR3.

2. TS virtual code prevents HTML completion because its embedded level is deeper than HTML virtual code. This is solved by setting `completion.isAdditional = true`.

3. `class=""` does not trigger completion, this is solved by generating additional virtual code.
