### ISSUE TITLE
[OPTIMIZE] There are times when automatic code completion doesn't work. 

### ISSUE THREAD

**Issue by LYU-Ning** [vuejs/language-tools#4101]
When I write a div, I pop up the div prompt but when I click on it, it doesn't complete it.  
I am currently using Vue-Office .
Volar has also been shut down.

**Comment by so1ve** [comment]
你直接发中文吧

**Comment by brc-dd** [comment]
Most likely that emmet not working issue.

**Comment by LYU-Ning** [comment]
> 你直接发中文吧，有点搞不明白你碰到了什么bug，等下我翻译一下
> 
> 只需用中文发送即可。我不明白你遇到了什么错误。我稍后会翻译它。

您好 是这样子的 

事情的起因：
我发现volar 此扩展已弃用 请改用 Vue - Official扩展 。于是去下载了这个扩展 ，并且禁用了原本的 volar 拓展 。

问题的描述：
我发现在创建模板语法的时候，如下图
![image](https://github.com/vuejs/language-tools/assets/53300024/ab28ce17-ccfc-443c-9449-4c4e181b66c0)
原本使用它的提示会出现 对应的 <div></div>
但实际的效果 却是原封不动 依旧是 div 

虽然不知道是否为Vue - Official 插件的问题  但是查阅了一些资料 认为这个可以尝试来提交一下问题反馈 来看看是否能得到有所帮助的信息  多谢啦~

**Comment by ntnyq** [comment]
Emmet 没起作用

**Comment by LYU-Ning** [comment]
> Most likely that emmet not working issue (#3998)

Thank you~~~

**Comment by LYU-Ning** [comment]
> Emmet 没起作用

多谢~~笔芯~

**Comment by LYU-Ning** [comment]
最为简单的解决办法：
查阅了很多资料，尝试了很多其中的方法，发现了一个极其简单的方法，就是将Vue - Official的版本可以降低为1.8.X的最新版本，虽然会有点迭代前的问题，但是确实修复了上述提到的问题~
感谢各位大佬的帮忙~~

The simplest solution:
After consulting a lot of information and trying many methods, I found an extremely simple solution, which is to downgrade the version of Vue - Official to the latest version 1.8.X. Although there may be some issues from the previous iteration, it indeed fixes the problems mentioned above.
Thanks to all the experts for your help~~

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/3998
