### ISSUE TITLE
Wrong types on import from Pinia

### ISSUE THREAD

**Issue by Rusinas** [vuejs/language-tools#4109]
![image](https://github.com/vuejs/language-tools/assets/42975143/5b40107f-f694-488a-b934-f25aff60aca5)
![image](https://github.com/vuejs/language-tools/assets/42975143/a05392df-9111-4016-b1c6-b05522e4c9cd)
![image](https://github.com/vuejs/language-tools/assets/42975143/1fd309e1-103f-4500-b2e4-4f8392a57429)

You can see a lot of errors here, but in fact there is none. But for some reason vue plugins thinks that `feeds` variable has 
this weird type:
![image](https://github.com/vuejs/language-tools/assets/42975143/3649c3da-6aca-4dc4-afc1-256931d33206)

This application is new and was created using `npm init vue@latest` command, but this behavior can be found even in old apps, which previously did work fine.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, please create a new issue with a minimal reproduction.
