### ISSUE TITLE
Sass language server support

### ISSUE THREAD

**Issue by niksy** [vuejs/language-tools#4111]
Is there a possibility of integrating [standalone Sass language server](https://github.com/wkillerud/some-sass/tree/main/packages/language-server#readme) for `<style lang="scss">` blocks?

It seems like it has much better support for Sass-specific features.

There is a [VSCode extension](https://github.com/wkillerud/some-sass/tree/main/vscode-extension#readme) which should provide this support, but if Volar is used as LSP server for other editors, there doesn’t seem to be way to achieve this.

**Comment by transtone** [comment]
can use stylelint: https://github.com/ota-meshi/stylelint-config-recommended-vue
