### ISSUE TITLE
Should the plugin name be updated to Vue.Official?

### ISSUE THREAD

**Issue by you-hengh** [vuejs/language-tools#4113]
![image](https://github.com/vuejs/language-tools/assets/34816426/8d419cc2-5636-4094-97ab-eaacf3c15f11)

Should the plugin name be updated to Vue.Official?

**Comment by johnsoncodehk** [comment]
This is the id, not the name, and the id cannot be changed unless the current extension is deprecated and a brand new extension is released. But this will cause more damage, because many places recognize the vue.volar id to do something (including VSCode extensions recommended setup).
