### ISSUE TITLE
[bug] `Vue › Complete › Casing: Tags = kebab` 失效了

### ISSUE THREAD

**Issue by WangJincheng4869** [vuejs/language-tools#4114]
目前的版本是 `2.0.6`，发现当设置 `Vue › Complete › Casing: Tags = kebab` 时不生效，提示的还是 `pascal`
![image](https://github.com/vuejs/language-tools/assets/41162158/b8b2f6e0-8836-4c23-b403-2df4eaa825e6)

## 这是提示效果
![动画 (2)](https://github.com/vuejs/language-tools/assets/41162158/977149a3-b691-4771-a8f4-d2049d6870fe)

之前会有一个 Vue 后缀的提示，只要回车就会转换为设置的 `kebab` 模式。

### PS：这个插件的提示目前还是有些卡，比如新建 vue 文件之后。

![动画](https://github.com/vuejs/language-tools/assets/41162158/3e6d5ba4-492a-478b-8814-32306b07b04d)

**Comment by KermanX** [comment]
抱歉我们无法复现该问题。请升级至最新版本，若问题仍然存在，请提供最小复现代码。谢谢！

**Comment by WangJincheng4869** [comment]
> 抱歉我们无法复现该问题。请升级至最新版本，若问题仍然存在，请提供最小复现代码。谢谢！

最新版本依旧存在此问题，这是最小的复现 https://github.com/WangJincheng4869/fanKuiWenJian/tree/main/packages/element-plus


下面这个动图是操作录屏

![动画](https://github.com/user-attachments/assets/78514630-b3dc-4015-a2bc-0684ac17a607)

**Comment by KermanX** [comment]
Let's track #4693.
