### ISSUE TITLE
【性能】关于 `v2.0.6` 卡顿一些问题

### ISSUE THREAD

**Issue by WangJincheng4869** [vuejs/language-tools#4115]
1. 目前基本可以确定就是这个插件导致 `VSCode` 的卡顿，我尝试禁用插件之后就不卡了，下面有动图的示例。
2. 如果提示 js 相关的问题卡顿我可以理解，但是用户代码片段也卡（我记得之前的版本最起码用户代码片段是不卡的）
3. 当我新建一个 vue 文件之后生成模板代码是非常常用的操作，卡十几二十秒其实有些离谱了。
4. 我发现卡顿的时候下面的 ts 引擎貌似在重载。

![动画](https://github.com/vuejs/language-tools/assets/41162158/72a0f72d-c0f1-4903-8b45-a4477c26bfef)

**Comment by latte03** [comment]
我的19款 macbook 卡顿严重🥲。时间越长就越严重。甚至连上下滑动都费劲

**Comment by WangJincheng4869** [comment]
> 安裝 https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next 可以解決問題嗎？

无法解决

![image](https://github.com/vuejs/language-tools/assets/41162158/c5d82d03-5b37-43c6-906f-59a28de37730)

**Comment by transtone** [comment]
非常卡顿。动不动就是正在加载，打个 `div` 按 tab 也要提示一下“正在加载” 。
2.0.6 好歹还会先补全再`正在加载`，`class=`之后马上补全成 `class=""`
2.0.7 干脆加载完了再补全，只能手动打引号，不然就等上8-10秒。

**Comment by zliyou** [comment]
还是回退一下版本吧

**Comment by xiaoxiangmoe** [comment]
我好像没能复现这个问题，朋友们，你们有没有开源的可复现的仓库啊 QAQ

**Comment by renqian805** [comment]
> 我好像没能复现这个问题，朋友们，你们有没有开源的可复现的仓库啊 QAQ

复现仓库地址：https://github.com/renqian805/vue3-project

在 vue 文件里面保存东西特别慢，在 ts 等其他文件中就很正常

**Comment by co2color** [comment]
template写<div>，期待情况是自动补</div>，然而现在需要等待3-5秒才能补上。。。v2.0.7

**Comment by co2color** [comment]
template写<div  ，期待补/div，v2.0.7起码要等3-5秒才能补上。

**Comment by a2734961** [comment]
> template写<div ，期待补/div，v2.0.7起码要等3-5秒才能补上。

还好还好，我比你快2秒~~~ 卡的一批 以前volar 没一点问题，自从改了Vue - Official vue文件代码提示异常的慢。

**Comment by anle1222** [comment]
我的也很卡

**Comment by WangJincheng4869** [comment]
@johnsoncodehk 这个开源项目也可以复现卡顿的问题
https://github.com/pure-admin/pure-admin-thin
https://github.com/pure-admin/vue-pure-admin

如果文件越多那么卡顿会越严重，第二次提示会变快，但是已经没有了意义。并且切换文件后同样的关键字又会变慢

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk 这个开源项目也可以复现卡顿的问题 [pure-admin/pure-admin-thin](https://github.com/pure-admin/pure-admin-thin) [pure-admin/vue-pure-admin](https://github.com/pure-admin/vue-pure-admin)

問題跟這裡無關，這是 element-plus 文件太多導致的，之前分享過（https://twitter.com/johnsoncodehk/status/1685487130985066496），可以考慮給 element-plus 提 PR 改進。

另外如果未啟用 Hybrid Mode 也可以嘗試啟用以提高性能。

**Comment by johnsoncodehk** [comment]
> 貌似目前所有的主流UI库都有相同的问题

不是，圖表裡跟 vanilla 比較接近的都沒有問題。

**Comment by WangMingHua111** [comment]
> > template写<div ，期待补/div，v2.0.7起码要等3-5秒才能补上。
> 
> 还好还好，我比你快2秒~~~ 卡的一批 以前volar 没一点问题，自从改了Vue - Official vue文件代码提示异常的慢。
我也是 以前volar 没一点问题

**Comment by WangMingHua111** [comment]
> > template写<div ，期待补/div，v2.0.7起码要等3-5秒才能补上。
> 
> 还好还好，我比你快2秒~~~ 卡的一批 以前volar 没一点问题，自从改了Vue - Official vue文件代码提示异常的慢。

我也是一样的情况

以前volar 没一点问题

**Comment by WangJincheng4869** [comment]
@WangMingHua111 如果你用了 element-plus 可以升级一下新版本，他们在 在这个 [PR #16111](https://github.com/element-plus/element-plus/pull/16111) 中进行了改进。
