### ISSUE TITLE
vscode里的vue-official每次一开项目就提示JS/TS语言服务崩溃，其它所有的vue插件我都已经卸载

### ISSUE THREAD

**Issue by steveny-l** [vuejs/language-tools#4120]
![WechatIMG551](https://github.com/vuejs/language-tools/assets/8047672/7c16ae94-6631-42d5-8f68-a7dd768a6b42)
![WechatIMG552](https://github.com/vuejs/language-tools/assets/8047672/fdfd1a23-7d3b-4e12-b13a-c64b3448d49a)
![WechatIMG553](https://github.com/vuejs/language-tools/assets/8047672/50705712-0feb-4be0-bf7d-1fb08b0636fc)

现在vue-official各种小毛病
1、偶发性的vue代码全变蓝色，不提示
2、偶发性的点击import文件不跳转
3、等等。。。

建议：
能不能把旧的TypeScript Vue Plugin (Volar)不要废弃不能用，旧的用的没有啥毛病，让用户自己去选择用哪个吧，不想继续更新TypeScript Vue Plugin (Volar)没问题的，先让开发人员能有能用的舒畅的

**Comment by wcz0** [comment]
same

**Comment by bzw1204** [comment]
> ![WechatIMG551](https://private-user-images.githubusercontent.com/8047672/314293812-7c16ae94-6631-42d5-8f68-a7dd768a6b42.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDE1NDYsIm5iZiI6MTcxMDkwMTI0NiwicGF0aCI6Ii84MDQ3NjcyLzMxNDI5MzgxMi03YzE2YWU5NC02NjMxLTQyZDUtOGY2OC1hN2RkNzY4YTZiNDIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDIyMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI5OTIwOWQ4ZDBmNDQ1YTRmZThjMmM0MjdjNmY0MTE5ZTYzZjgxZjAwZGM5NzQ2YmZhNGQ3OGEyZjZhNjIzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2yPtj5B3S2tHiCHkDZwqPX-8aRlNIO1E6Gy5qjknnds) ![WechatIMG552](https://private-user-images.githubusercontent.com/8047672/314294125-fdfd1a23-7d3b-4e12-b13a-c64b3448d49a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDE1NDYsIm5iZiI6MTcxMDkwMTI0NiwicGF0aCI6Ii84MDQ3NjcyLzMxNDI5NDEyNS1mZGZkMWEyMy03ZDNiLTRlMTItYjEzYS1jNjRiMzQ0OGQ0OWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDIyMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdmZjkyOTFlZjgxNGI3YWZhM2RlZWRlZmZjNDAxNzE1OTEwZGUzZmIyMDQ3OWNjMmZkN2NiMjdkM2M4ODYyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xpALtp5rvcn8UHkGexJygUemLsf6QwWoFfH1UlkTbP4) ![WechatIMG553](https://private-user-images.githubusercontent.com/8047672/314312453-50705712-0feb-4be0-bf7d-1fb08b0636fc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDE1NDYsIm5iZiI6MTcxMDkwMTI0NiwicGF0aCI6Ii84MDQ3NjcyLzMxNDMxMjQ1My01MDcwNTcxMi0wZmViLTRiZTAtYmY3ZC0xZmIwOGIwNjM2ZmMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDIyMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZkMTU0MWYwM2I1NTdmMDg3NDYzMGE1ZDkyYjIwMjJkOTlhODAzYTg4ZmNiYWQ0MzljM2Y0NDAwYzE5Y2U3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CQnAZ-OOsIL7OrJe1vSRwXQw1-j8gNcDT2PYOQKDCY4)
> 
> 现在vue-official各种小毛病 1、偶发性的vue代码全变蓝色，不提示 2、偶发性的点击import文件不跳转 3、等等。。。
> 
> 建议： 能不能把旧的TypeScript Vue Plugin (Volar)不要废弃不能用，旧的用的没有啥毛病，让用户自己去选择用哪个吧，不想继续更新TypeScript Vue Plugin (Volar)没问题的，先让开发人员能有能用的舒畅的

切换到1.8.27版本没有问题

**Comment by johnsoncodehk** [comment]
Duplicate of #3962
