### ISSUE TITLE
发个国内方便的支付方式吧

### ISSUE THREAD

**Issue by rayzhao99** [vuejs/language-tools#4121]
OpenCollective需要录入银行卡信息，不太想录入。

能否提供个可以用 微信支付 or 支付宝 等方式的赞助途径？

虽然近期的Volar插件不太理想，但还是想说辛苦了，加油！

**Comment by laterdayi** [comment]
![image](https://github.com/vuejs/language-tools/assets/122137647/0bbdddf2-ec7d-406d-9794-d7c278bd0c93)
volar should be supported

**Comment by fengT-T** [comment]
Vue is popular in China, providing some more localized donation channels can get more support. For example,
[aifdian](https://afdian.net/)

**Comment by hoythan** [comment]
穷疯了才会想在 IDE 工具里直接打广告。这是什么阴间的行为

**Comment by rayzhao99** [comment]
> ![image](https://private-user-images.githubusercontent.com/122137647/315254078-0bbdddf2-ec7d-406d-9794-d7c278bd0c93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTA2NjcsIm5iZiI6MTcxMTUxMDM2NywicGF0aCI6Ii8xMjIxMzc2NDcvMzE1MjU0MDc4LTBiYmRkZGYyLWVjN2QtNDA2ZC05Nzk0LWQ3YzI3OGJkMGM5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwMzMyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmUzMGY1M2U0ZGQ3NzIwNDljYzIwZjhjOWI1ODM1NzdlZjk5NDViOTExNWVmNzVkNGYwY2Y4MGQyNjVlZmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UhCXOyItu_9ZXR06IRpAa-jyRezfHo0yOYSSc03ejYg) volar should be supported

However, any other choices?

**Comment by johnsoncodehk** [comment]
@rayzhao99 感議支持，我目前沒有國內的收款方式，我會看一下 @fengT-T 的提議。

@hoythan 這只是為了解決項目的可持續性問題，沒有必要惡言相向，並且我自己現在每月也有幾千花在贊助貢獻者上。

**Comment by jahnli** [comment]
> 穷疯了才会想在 IDE 工具里直接打广告。这是什么阴间的行为

要不你来 ？

**Comment by zliyou** [comment]
> 穷疯了才会想在 IDE 工具里直接打广告。这是什么阴间的行为

伸手党别说了吧

**Comment by johnsoncodehk** [comment]
Insiders 計劃也可以用愛發電訂閱了：https://afdian.net/a/johnsoncodehk
