### ISSUE TITLE
A syntax error in code highlighting is very annoying

### ISSUE THREAD

**Issue by asylbek23** [vuejs/language-tools#4123]
A syntax error in the code highlighting appears after a while.

**Comment by gegoune** [comment]
That is one terrible bug report. You mentioned absolutely zero details to help maintainers investigate your issue.

**Comment by asylbek23** [comment]
> That is one terrible bug report. You mentioned absolutely zero details to help maintainers investigate your issue.

What details are needed here? Initially, syntax highlighting works well and after a while some codes are highlighted in different colors like a rainbow. What's not clear here?

**Comment by so1ve** [comment]
You should provide a screenshot at least. I can't use my mind to help you reproduce this bug.

**Comment by asylbek23** [comment]
> You should provide a screenshot at least. I can't use my mind to help you reproduce this bug.
<img width="683" alt="ibkwL" src="https://github.com/vuejs/language-tools/assets/29757446/648bcff1-08a9-4a18-964a-9008965ed067">

**Comment by davidmatter** [comment]
Probably because of the `555.1k (gziped:...` fragments. Something is not right here - can you post the actual content of the component in here?

**Comment by asylbek23** [comment]
> Probably because of the `555.1k (gziped:...` fragments. Something is not right here - can you post the actual content of the component in here?

The only problem is the expansion. I downgraded the version to 1.8.27 and the problem was solved So that all the problems in the extension, in particular in version 2.0.6. Now I see that version 2.0.7 has been released. I'll try it.
