### ISSUE TITLE
[Feature] Template interpolation decorators

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#4124]
We can highlight the background color of the template interpolations, which I believe will help improve the visibility of complex templates.

Outlook:

<img width="719" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/cf295da2-2fa0-405e-b136-77b01feee02f">

**Comment by johnsoncodehk** [comment]
Implement by https://github.com/volarjs/insiders/pull/4

**Comment by mrleblanc101** [comment]
@johnsoncodehk Thansk ❤️
Approximately when can we expect this to land ?

**Comment by johnsoncodehk** [comment]
@mrleblanc101 This is temporarily available as a insiders-specific feature, see https://github.com/vuejs/language-tools/wiki/Get-Insiders-Edition.
