### ISSUE TITLE
[Feature] Drag and Drop Component Import respects tsconfig path aliases

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#4125]
When tsconfig is configured with `"paths": { "@/*": ["src/*"] }`, drag `/src/components/HelloWorld.vue` into `/src/App.vue` and it should be imported` @/components/HelloWorld.vue` instead of `./components/HelloWorld.vue`.

**Comment by newVincentFong** [comment]
I'm trying to implement this feature.
How is it supposed to access tsconfig inside a volar language service ?
I didn't find anything useful in the `context` object.
Maybe it involves some changes of `volar.js` project ?
@johnsoncodehk

**Comment by johnsoncodehk** [comment]
@newVincentFong You can start with https://github.com/vuejs/language-tools/commit/74c3e85d4dca927fbe93f8100ad4aed979734d92.

The main operations are located at https://github.com/vuejs/language-tools/commit/74c3e85d4dca927fbe93f8100ad4aed979734d92#diff-1754a4c09f9ad2611310f617ea9e28f2e060a76f8b1515158ee60c04d198a86fR12.
