### ISSUE TITLE
TS2307: Cannot find module '@/components/echarts' or its corresponding type declarations.

### ISSUE THREAD

**Issue by freeany** [vuejs/language-tools#4128]
I have installed the latest version of Vue - Official v2.0.7, the vscode version is the latest, my code is opened in vscode, everything is displayed perfectly, no errors are reported, and you can also click on the corresponding module with the mouse, but I got a lot of errors when I ran `npm run type-check`. I was confused and didn’t know the reason.

### version

-  vue-tsc: 1.8.27
-  typescript: @5.3.3

### `npm run type-check`
-  ` "type-check": "vue-tsc --build --force --traceResolution",`

<img width="1412" alt="image" src="https://github.com/vuejs/language-tools/assets/47732430/0914abf9-d975-4cf8-8b19-a0a776dd6f10">

**Comment by davidmatter** [comment]
What does your tsconfig look like?

**Comment by freeany** [comment]
> What does your tsconfig look like?


<img width="736" alt="image" src="https://github.com/vuejs/language-tools/assets/47732430/dccf2e85-a7dc-4d8c-b426-397946b76a5f">



<img width="923" alt="image" src="https://github.com/vuejs/language-tools/assets/47732430/b550f09d-fabf-4211-8a0c-83c2d0a87116">


<img width="973" alt="image" src="https://github.com/vuejs/language-tools/assets/47732430/24115ec5-3529-44cc-a26a-9d64210410ea">

**Comment by freeany** [comment]
> What does your tsconfig look like?

Thanks for your reply, strangely cannot find module dom api

<img width="1137" alt="image" src="https://github.com/vuejs/language-tools/assets/47732430/68360f9e-ee83-4fda-996d-bc60b6d1047d">

**Comment by davidmatter** [comment]
Try this for your type-check script:
`vue-tsc --noEmit -p tsconfig.app.json --composite false`

**Comment by davidmatter** [comment]
Also: you're still on vue-tsc 1.8.27. Try to upgrade to the latest version (same version as the vscode vue ext).

**Comment by freeany** [comment]
> Also: you're still on vue-tsc 1.8.27. Try to upgrade to the latest version (same version as the vscode vue ext).

I upgraded vue-tsc to the latest version, and then changed the "type-check" script to: "vue-tsc --noEmit -p tsconfig.app.json". solved this problem. thanks
