### ISSUE TITLE
Update to 2.0.7

### ISSUE THREAD

**Issue by CharnaceRegis** [vuejs/language-tools#4130]
Since 2.0.7,

[Error - 17:06:43] Client Vue: connection to server is erroring.
write EPIPE
[Error - 17:06:43] Client Vue: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 17:06:43] Client Vue: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 17:06:43] Client Vue: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 17:06:43] Client Vue: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 17:06:43] Server process exited with signal SIGBUS.
[Error - 17:06:43] Connection to server got closed. Server will not be restarted.

Apple M1 - 16Go 
I've downgraded to 2.0.6

**Comment by dcartwright07** [comment]
After upgrading to 2.0.7, I also got errors in VSCode output console.
```
[Error - 12:08:36 PM] Server process exited with signal SIGBUS.
[Info  - 12:08:36 PM] Connection to server got closed. Server will restart.
true
[Error - 12:08:37 PM] Server process exited with signal SIGBUS.
[Info  - 12:08:37 PM] Connection to server got closed. Server will restart.
true
[Error - 12:08:37 PM] Server process exited with signal SIGBUS.
[Info  - 12:08:37 PM] Connection to server got closed. Server will restart.
true
[Error - 12:08:38 PM] Server process exited with signal SIGBUS.
[Info  - 12:08:38 PM] Connection to server got closed. Server will restart.
true
[Error - 12:08:39 PM] Server process exited with signal SIGBUS.
[Error - 12:08:39 PM] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
I also downgraded to 2.0.6 and the extension stopped crashing.

**Comment by johnsoncodehk** [comment]
Will the problem still occur if you enable `vue.server.hybridMode` in VSCode settings?

@dcartwright07 Since the error message is different, I'm not sure if you have the same issue.

If anyone can help me debug this issue via remote desktop, please contact me in the Vue discord server.

**Comment by claylevering** [comment]
> Will the problem still occur if you enable `vue.server.hybridMode` in VSCode settings?
> 
> @dcartwright07 Since the error message is different, I'm not sure if you have the same issue.
> 
> If anyone can help me debug this issue via remote desktop, please contact me in the Vue discord server.

Pinged you in paid and trying to find you in discord but unsure where to find you in `Vue Land`

**Comment by madcodelife** [comment]
> After upgrading to 2.0.7, I also got errors in VSCode output console.
> 
> ```
> [Error - 12:08:36 PM] Server process exited with signal SIGBUS.
> [Info  - 12:08:36 PM] Connection to server got closed. Server will restart.
> true
> [Error - 12:08:37 PM] Server process exited with signal SIGBUS.
> [Info  - 12:08:37 PM] Connection to server got closed. Server will restart.
> true
> [Error - 12:08:37 PM] Server process exited with signal SIGBUS.
> [Info  - 12:08:37 PM] Connection to server got closed. Server will restart.
> true
> [Error - 12:08:38 PM] Server process exited with signal SIGBUS.
> [Info  - 12:08:38 PM] Connection to server got closed. Server will restart.
> true
> [Error - 12:08:39 PM] Server process exited with signal SIGBUS.
> [Error - 12:08:39 PM] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
> ```
> 
> I also downgraded to 2.0.6 and the extension stopped crashing.

I got same issue.

**Comment by drylint** [comment]
> Will the problem still occur if you enable `vue.server.hybridMode` in VSCode settings?
> 
> @dcartwright07 Since the error message is different, I'm not sure if you have the same issue.
> 
> If anyone can help me debug this issue via remote desktop, please contact me in the Vue discord server.

It still occur after enabled `vue.server.hybridMode` in VSCode settings.

**Comment by drylint** [comment]
When enabled `vue.server.hybridMode`, It reports another error repeatedly. @johnsoncodehk 

```bash
service 2 crashed on file:///Users/......./***.vue?virtualCodeId=script_ts No service provide typescript/languageService

......repeatedly
```

**Comment by johnsoncodehk** [comment]
> What did you do to Diagnose this issue?

I currently have no clue as to how this problem occurs, I need to identify where the error is being thrown first.

If you want to try debugging: https://github.com/vuejs/language-tools#contribution-guide

> When enabled `vue.server.hybridMode`, It reports another error repeatedly. @johnsoncodehk
> 
> ```shell
> service 2 crashed on file:///Users/......./***.vue?virtualCodeId=script_ts No service provide typescript/languageService
> 
> ......repeatedly
> ```

You can ignore it, it's just harmless logs.

**Comment by dcartwright07** [comment]
@johnsoncodehk When `vue.server.hybridMode` is enabled, the extension does not crash. I am no longer getting the errors in the output console. 

I am not sure if this helps but I did get the same error message as @CharnaceRegis. The error messages I posted earlier was after I click to view the error log. 

<img width="472" alt="Screenshot 2024-03-20 at 10 15 46 PM" src="https://github.com/vuejs/language-tools/assets/13526857/5c61fd79-2fd4-433c-9923-c46914ec68e2">

**Comment by juzser** [comment]
I get the same issue.

<img width="470" alt="Screenshot 2024-03-21 at 15 13 23" src="https://github.com/vuejs/language-tools/assets/5735071/651d0413-6aad-48d4-a5bc-67d9cdb19b10">

**Comment by Shyam-Chen** [comment]
Fix this issue using VS Code v1.88.0.

**Comment by CharnaceRegis** [comment]
I agree with that. Insiders version of vscode

**Comment by johnsoncodehk** [comment]
Possibly due to the reintroduction of the full language server in #4119, the issue mentioned in #3962 has spread to the Vue language server in some form, I will update the version required by the extension when VSCode 1.88 is released.

**Comment by filipbekic01** [comment]
It's crazy how annoying this bug can be.

**Comment by Mert75** [comment]
> It's crazy how annoying this bug can be.

you can still rollback to the previous release and have it working again

**Comment by MichaelGitArt** [comment]
> hybridMode

It's okay with hybridMode.

Or almost okay. The server runs okay, but there are some service crashes. But it's okay with it
<img width="1324" alt="image" src="https://github.com/vuejs/language-tools/assets/34610289/bf15f532-6626-400a-9681-c29453bcabb4">

**Comment by ningyf** [comment]
The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: Vue.volar. Please try disabling these extensions before filing an issue against VS Code.

It aways cause this error since 2.x. I downgrade to v1 to fix this issue.

The vscode output logs:
2024-03-22 10:34:35.207 [info] Starting TS Server
2024-03-22 10:34:35.207 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-22 10:34:35.207 [info] <syntax> Forking...
2024-03-22 10:34:35.207 [info] <syntax> Starting...
2024-03-22 10:34:35.207 [info] <semantic> Forking...
2024-03-22 10:34:35.207 [info] <semantic> Starting...
2024-03-22 10:34:37.902 [error] TSServer exited. Code: null. Signal: SIGBUS

**Comment by Lakphy** [comment]
I got the same issue. Do I have to downgrade the plugin or upgrade vscode to solve it? I have not received the vscode 1.88 update yet.

```
[Error - 16:51:28] Server process exited with signal SIGBUS.
[Info  - 16:51:28] Connection to server got closed. Server will restart.
true
[Error - 16:51:30] Server process exited with signal SIGBUS.
[Info  - 16:51:30] Connection to server got closed. Server will restart.
true
[Error - 16:51:32] Server process exited with signal SIGBUS.
[Info  - 16:51:32] Connection to server got closed. Server will restart.
true
[Error - 16:51:33] Server process exited with signal SIGBUS.
[Info  - 16:51:33] Connection to server got closed. Server will restart.
true
[Error - 16:51:34] Server process exited with signal SIGBUS.
[Error - 16:51:34] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

```

**Comment by OlaAlsaker** [comment]
Using [VS Code Insiders](https://code.visualstudio.com/insiders/) fixed the issue for me.

**Comment by Nagell** [comment]
Here similar situation. Directly after starting VSC and opening a Vue file. 

<details>
<summary>log preview - click to open</summary>

```
[Error - 10:37:39 AM] Server process exited with signal SIGBUS.
[Info  - 10:37:39 AM] Connection to server got closed. Server will restart.
true
[Error - 10:37:39 AM] Server process exited with signal SIGBUS.
[Info  - 10:37:39 AM] Connection to server got closed. Server will restart.
true
[Error - 10:37:40 AM] Server process exited with signal SIGBUS.
[Info  - 10:37:40 AM] Connection to server got closed. Server will restart.
true
[Error - 10:37:41 AM] Server process exited with signal SIGBUS.
[Info  - 10:37:41 AM] Connection to server got closed. Server will restart.
true
[Error - 10:37:42 AM] Server process exited with signal SIGBUS.
[Error - 10:37:42 AM] The Vue server crashed 5 times in the last 3 minutes.
```

</details>

Setup:

- MacOS: 14.4
- VSC: v1.87.2
  - Version: 1.87.2 (Universal)
  - Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
  - Date: 2024-03-08T15:21:31.043Z
  - Electron: 27.3.2
  - ElectronBuildId: 26836302
  - Chromium: 118.0.5993.159
  - Node.js: 18.17.1
  - V8: 11.8.172.18-electron.0
  - OS: Darwin arm64 23.4.0
- freshly created Profile with only Two plugins:
  - ESLint: 2.4.4
  - Vue-Official: 2.0.7

**Comment by ilyakamens** [comment]
Also happening to me.

**Comment by Shyam-Chen** [comment]
> https://github.com/microsoft/vscode/issues/208302

VS Code v1.88 scheduled for release on 4/4.

**Comment by mrleblanc101** [comment]
Shouldn't this be reverted in a 2.0.8. Then the next 2.0.9 could bump the min version of VS Code to 1.88. Then user of both 1.87 and 1.88 would have a working plugin ?

**Comment by LcpMarvel** [comment]
```
rejected promise not handled within 1 second: Error: Request volar/client/tsconfig failed with message: Invalid file name
extensionHostProcess.js:144
stack trace: Error: Request volar/client/tsconfig failed with message: Invalid file name
    at handleResponse (/Volumes/lcp/git_repos/language-tools/node_modules/.pnpm/vscode-jsonrpc@8.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
    at handleMessage (/Volumes/lcp/git_repos/language-tools/node_modules/.pnpm/vscode-jsonrpc@8.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
    at processMessageQueue (/Volumes/lcp/git_repos/language-tools/node_modules/.pnpm/vscode-jsonrpc@8.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/Volumes/lcp/git_repos/language-tools/node_modules/.pnpm/vscode-jsonrpc@8.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at processImmediate (node:internal/timers:476:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by khgs2411** [comment]
2.0.8 has the same problem.
If vscode 1.88 fixes this issue, then this release schedule for the extension is utterly baffling...why release a broken product?

**Comment by ipid** [comment]
Same here on MacBook Pro 2023, M2 Pro, macOS 14.2.1

**Comment by johnsoncodehk** [comment]
> 2.0.8 has the same problem. If vscode 1.88 fixes this issue, then this release schedule for the extension is utterly baffling...why release a broken product?

This is an unpredictable error that occurs in random projects and environments. It was not occur in self-test and 3 months alpha test.

To be honest, it's not fair to blame the extension for Node bugs. We could not anticipate that the Node version of the stable VSCode bundled would be unstable.

Closed since VSCode 1.88 has been released.

**Comment by masawik** [comment]
installing an earlier version (2.0.6) fixed it

![image](https://github.com/vuejs/language-tools/assets/56366545/ea225387-4727-4214-9b15-3767639be96e)

**Comment by LcpMarvel** [comment]
> installing an earlier version (2.0.6) fixed it
> 
> ![image](https://private-user-images.githubusercontent.com/56366545/321564817-ea225387-4727-4214-9b15-3767639be96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjYzNTMsIm5iZiI6MTcxMjgyNjA1MywicGF0aCI6Ii81NjM2NjU0NS8zMjE1NjQ4MTctZWEyMjUzODctNDcyNy00MjE0LTliMTUtMzc2NzYzOWJlOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA5MDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMmRlNTIwNWVhYzkxOGQyZjkwOTc4ODI3ODRiYTlmZjliNDhhOTc3MDEwOTgwMTIzZWY1ZTQ1NWJkODYwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3YpSNhK3V2o1Efl0GcUg_3wmqekSC4iHbgBc0UwiSsM)

Download the latest https://code.visualstudio.com/.
