### ISSUE TITLE
[Feature] Automatically enable Hybrid Mode

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#4131]
Hybrid Mode can be disabled after 2.0.7 and is disabled by default. We can detect and automatically enable it under specific conditions to improve performance.

Automatic activation should meet the following conditions:

1. ~~VSCode version >= 1.88~~ This will be the installation condition for the extension
2. ~~No other extensions with TS plugin are installed~~ Only the TS plugin extensions in the whitelist are installed
3. TS version >= 5.3

**Comment by catgoose** [comment]
What about neovim?

**Comment by segevfiner** [comment]
Might want to also consider having a whitelist of known TS server plugins that will not prevent automatic activation. Intellicode is pretty common for example due to Microsoft pushing it in many extension packs. And I also have the MDX one installed and working fine.

**Comment by johnsoncodehk** [comment]
@segevfiner good point, will do it.
