### ISSUE TITLE
[bug] template tag autocomplete delay

### ISSUE THREAD

**Issue by transtone** [vuejs/language-tools#4133]
after upgrade to `2.0.7`, when type `class=` in `<div ></div>`, it will wait a long time to autocomplete `class=""`。

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4115

**Comment by transtone** [comment]
> Duplicate of #4115

两个问题好吧。这个是自动补全和加载提示列表的顺序问题，那个是加载提示列表的速度问题。

**Comment by transtone** [comment]
seems fixed in `v2.0.10`.
