### ISSUE TITLE
[Feature] Reactions visualization

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#4138]
Refs https://github.com/HalfdanJ/svelte-reactions, https://twitter.com/halfdanj/status/1658166562660941824

**Comment by rchl** [comment]
Just based on the gif it looks to me like the standard [document highlight](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight) that just highlights references of the current variable.

Possibly in some other cases it does a bit extra but I feel like it could be easily confused for document highlights if implemented.

**Comment by mrleblanc101** [comment]
I think he is talking about the green line highlight and not the gray variable highlight.
![preview](https://github.com/vuejs/language-tools/assets/17392251/d2b6aaf2-48f6-494a-ac8f-45f2b4d0d6b2)

**Comment by rchl** [comment]
Right, I see.

**Comment by johnsoncodehk** [comment]
Implement by https://github.com/volarjs/insiders/pull/5

https://github.com/volarjs/insiders/assets/16279759/94f1e354-2859-4f5e-ab04-52f6b82f3e08
