### ISSUE TITLE
`Auto Insert: Bracket Spacing` doesn't work with multiple cursor

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/language-tools#4140]
It work with a single cursor:
![2024-03-21 17 02 02](https://github.com/vuejs/language-tools/assets/17392251/c0403d3d-1349-4953-b988-a462e6b2cd12)

It does not work with multiple cursor:
![2024-03-21 17 02 34](https://github.com/vuejs/language-tools/assets/17392251/3fba8739-4d9b-437f-b8c0-bf22a55fce4e)

Only the first cursor will get the space around the brackets and all other cursor will be lost which is kind of annoying.

**Comment by asylbek23** [comment]
> It work with a single cursor: ![2024-03-21 17 02 02](https://private-user-images.githubusercontent.com/17392251/315645541-c0403d3d-1349-4953-b988-a462e6b2cd12.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU1NDEtYzA0MDNkM2QtMTM0OS00OTUzLWI5ODgtYTQ2MmU2YjJjZDEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWNmN2U1M2IxNTQwZmYzZjU2ZTg5YzQyYTc2OGQ0Yzg2MDBiZjdmNGU4ZTU3MGExZTZlMTM1Mjg5NjI5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RdLWQtR6DV5VjJTvgSFd2iQ9yOaWu74PZWQomKBenok) [ ![2024-03-21 17 02 02](https://private-user-images.githubusercontent.com/17392251/315645541-c0403d3d-1349-4953-b988-a462e6b2cd12.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU1NDEtYzA0MDNkM2QtMTM0OS00OTUzLWI5ODgtYTQ2MmU2YjJjZDEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWNmN2U1M2IxNTQwZmYzZjU2ZTg5YzQyYTc2OGQ0Yzg2MDBiZjdmNGU4ZTU3MGExZTZlMTM1Mjg5NjI5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RdLWQtR6DV5VjJTvgSFd2iQ9yOaWu74PZWQomKBenok) ](https://private-user-images.githubusercontent.com/17392251/315645541-c0403d3d-1349-4953-b988-a462e6b2cd12.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU1NDEtYzA0MDNkM2QtMTM0OS00OTUzLWI5ODgtYTQ2MmU2YjJjZDEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWNmN2U1M2IxNTQwZmYzZjU2ZTg5YzQyYTc2OGQ0Yzg2MDBiZjdmNGU4ZTU3MGExZTZlMTM1Mjg5NjI5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RdLWQtR6DV5VjJTvgSFd2iQ9yOaWu74PZWQomKBenok) [ ](https://private-user-images.githubusercontent.com/17392251/315645541-c0403d3d-1349-4953-b988-a462e6b2cd12.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU1NDEtYzA0MDNkM2QtMTM0OS00OTUzLWI5ODgtYTQ2MmU2YjJjZDEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWNmN2U1M2IxNTQwZmYzZjU2ZTg5YzQyYTc2OGQ0Yzg2MDBiZjdmNGU4ZTU3MGExZTZlMTM1Mjg5NjI5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RdLWQtR6DV5VjJTvgSFd2iQ9yOaWu74PZWQomKBenok)
> 
> It does not work with multiple cursor: ![2024-03-21 17 02 34](https://private-user-images.githubusercontent.com/17392251/315645798-3fba8739-4d9b-437f-b8c0-bf22a55fce4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU3OTgtM2ZiYTg3MzktNGQ5Yi00MzdmLWI4YzAtYmYyMmE1NWZjZTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzBkNWIwY2NhNWI3NjhkY2I5NjIzOGY1ZjEwZjc2ZjY1MDgxMmQ1MDU1YzI2ZmM0YjM3YzVjZTg3YTMwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91CvvzxTdP0Q7A1ycTB_lCmWatgpzCSTKun5Kf7OUcE) [ ![2024-03-21 17 02 34](https://private-user-images.githubusercontent.com/17392251/315645798-3fba8739-4d9b-437f-b8c0-bf22a55fce4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU3OTgtM2ZiYTg3MzktNGQ5Yi00MzdmLWI4YzAtYmYyMmE1NWZjZTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzBkNWIwY2NhNWI3NjhkY2I5NjIzOGY1ZjEwZjc2ZjY1MDgxMmQ1MDU1YzI2ZmM0YjM3YzVjZTg3YTMwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91CvvzxTdP0Q7A1ycTB_lCmWatgpzCSTKun5Kf7OUcE) ](https://private-user-images.githubusercontent.com/17392251/315645798-3fba8739-4d9b-437f-b8c0-bf22a55fce4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU3OTgtM2ZiYTg3MzktNGQ5Yi00MzdmLWI4YzAtYmYyMmE1NWZjZTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzBkNWIwY2NhNWI3NjhkY2I5NjIzOGY1ZjEwZjc2ZjY1MDgxMmQ1MDU1YzI2ZmM0YjM3YzVjZTg3YTMwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91CvvzxTdP0Q7A1ycTB_lCmWatgpzCSTKun5Kf7OUcE) [ ](https://private-user-images.githubusercontent.com/17392251/315645798-3fba8739-4d9b-437f-b8c0-bf22a55fce4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA0NzcsIm5iZiI6MTcxMTEwMDE3NywicGF0aCI6Ii8xNzM5MjI1MS8zMTU2NDU3OTgtM2ZiYTg3MzktNGQ5Yi00MzdmLWI4YzAtYmYyMmE1NWZjZTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzBkNWIwY2NhNWI3NjhkY2I5NjIzOGY1ZjEwZjc2ZjY1MDgxMmQ1MDU1YzI2ZmM0YjM3YzVjZTg3YTMwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91CvvzxTdP0Q7A1ycTB_lCmWatgpzCSTKun5Kf7OUcE)
> 
> Only the first cursor will get the space around the brackets and all other cursor will be lost which is kind of annoying.

This error has been around for a long time

**Comment by asylbek23** [comment]
This error has been around for a long time

**Comment by so1ve** [comment]
@asylbek23 Dude, no one has reported this problem before. Sending "this error has been around for a long time" here won't help it get fixed.

**Comment by asylbek23** [comment]
> @asylbek23 Dude, no one has reported this problem before. Sending "this error has been around for a long time" here won't help it get fixed.

Dude, this error did not appear when Volar was worked. Also, now that I have downgraded the Vue version to 1.8.27, the error does not appear.

**Comment by asylbek23** [comment]
> @asylbek23 Dude, no one has reported this problem before. Sending "this error has been around for a long time" here won't help it get fixed.

Your answer too

**Comment by mrleblanc101** [comment]
@so1ve I wonder if I could open this as a Feature Request for vscode.
Currently this need to be implemented per language, but curly space is pretty standard accros all templating language.
VS Code could even support spacing for `{% %}`, `{# #}` and all the other variation 🤔

**Comment by so1ve** [comment]
But I'd like to know if the vscode are willing to implement this feature. They don't add spaces inside `import {/*here*/} from "";`.

Anyway, this is still a bug that we are not handling multiple cursors well. We'll fix it.

**Comment by mrleblanc101** [comment]
True, I guess I'm used to prettier doing it on save, which is does for Vue too, but it's nice to have it on type.

**Comment by johnsoncodehk** [comment]
I think this problem cannot be solved directly on the Vue language tools side, it requires changing Volar's auto insertion logic.
