### ISSUE TITLE
在win11系统上， v2.0.7 在保存代码时经常很慢

### ISSUE THREAD

**Issue by wcldyx** [vuejs/language-tools#4142]
![image](https://github.com/vuejs/language-tools/assets/26700595/08df6463-c235-42c0-8a00-5858b6bfc3c1)

**Comment by tiantianliulang** [comment]
+1

**Comment by code95278** [comment]
+1，是真的卡，希望官方修复一下

**Comment by Ttou** [comment]
我发现用ts取不到组件类型，之前是可以的

<img width="462" alt="image" src="https://github.com/vuejs/language-tools/assets/4298437/37f7f343-ce34-4f63-aa21-741024c07750">

**Comment by buqiyuan** [comment]
https://github.com/buqiyuan/vue3-antdv-admin/blob/271f63f5b762ca17cca2596845d6ac30705c99d1/.vscode/settings.json#L6-L8

在官方修复前，可以暂时在 `.vscode/settings.json` 中添加如下配置试试：
```json
  "vue.server.maxOldSpaceSize": 4096,
  "vue.server.hybridMode": true,
  "typescript.tsserver.maxTsServerMemory": 4096,
```

**Comment by FUNKAKIT** [comment]
至今都无法Ctrl+左键跳转到方法里

**Comment by Ttou** [comment]
> 我发现用ts取不到组件类型，之前是可以的
> 
> <img alt="image" width="462" src="https://private-user-images.githubusercontent.com/4298437/316241497-37f7f343-ce34-4f63-aa21-741024c07750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDM3MDIsIm5iZiI6MTcxMTU0MzQwMiwicGF0aCI6Ii80Mjk4NDM3LzMxNjI0MTQ5Ny0zN2Y3ZjM0My1jZTM0LTRmNjMtYWEyMS03NDEwMjRjMDc3NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTI0MzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M5YmJhNWI3NjgwMWYyZWQ0NDk4YjUyZDE0MGIwNmU5ZjM2OGZhNGUwNTNiY2RmM2EzNDhhYmZhZjQ0YTRkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I6JUEDUsPfIX7EnBbPH5smlFJiYS1xU4QtCcDQHSe-Q">

升级到 VSCode 1.88 可以修复该问题，等发版即可

**Comment by Yilimmilk** [comment]
+1,me too

**Comment by Yilimmilk** [comment]
+1, 我是把插件降到2.0.4版本就好了

**Comment by Yilimmilk** [comment]
> https://github.com/buqiyuan/vue3-antdv-admin/blob/271f63f5b762ca17cca2596845d6ac30705c99d1/.vscode/settings.json#L6-L8
> 
> 在官方修复前，可以暂时在 `.vscode/settings.json` 中添加如下配置试试：
> 
> ```json
>   "vue.server.maxOldSpaceSize": 4096,
>   "vue.server.hybridMode": true,
>   "typescript.tsserver.maxTsServerMemory": 4096,
> ```

谢谢，确实可以解决

**Comment by johnsoncodehk** [comment]
Please try VSCode 1.88.
