### ISSUE TITLE
Feature Request: Add Configuration Option to Exclude Packages from Code Suggestions

### ISSUE THREAD

**Issue by zogwosh** [vuejs/language-tools#4145]
Could you please add an option to exclude certain packages from code suggestions? Some irresponsible packages offer thousands of exported items, which significantly slow down the editor's performance. For example, date-fns is one of these packages.

**Comment by so1ve** [comment]
Does typescript have such configuration?

**Comment by lisonge** [comment]
It looks related to https://github.com/microsoft/TypeScript/pull/49578

**Comment by zogwosh** [comment]
@lisonge  thanks, I have added settings in my VSCode to exclude postcss and date-fns, and now I feel much better. This configuration does not work in
