### ISSUE TITLE
F2 when used on a tag in `<template>` renames components globally in Nuxt

### ISSUE THREAD

**Issue by remonke** [vuejs/language-tools#4149]

**Comment by so1ve** [comment]
I'm not sure if we should handle this case :eyes:

**Comment by remonke** [comment]
I mean can't F2 work the same way with regular tags and custom components? I was used to F2 changing the tag on the selected element, not changing the component name globally.

**Comment by so1ve** [comment]
Do you mean linked edit?

**Comment by remonke** [comment]
Okay, here's what I mean. I click F2 on tag to rename it.
[Uploading Screencast_20240408_105448.webm…]()

**Comment by remonke** [comment]
[Screencast_20240408_105448.webm](https://github.com/vuejs/language-tools/assets/102010617/c76c868f-da55-4a4c-bd1a-e32e59db5cb0)

Here's what happens when using F2 on a tag

**Comment by so1ve** [comment]
Just edit them directly, don't use F2.

**Comment by remonke** [comment]
Sure, but can you perhaps make this an opt-out feature? Or make it so that it only works when a component is explicitly imported? (without auto-imports it works fine)

**Comment by KazariEX** [comment]
This issue has been resolved in latest version.
