### ISSUE TITLE
When tab completing a component, it is imported as `undefined`

### ISSUE THREAD

**Issue by codymikol** [vuejs/language-tools#4151]
When in a `<template>`, if I start to type the name of one of my components and tab complete it, it will be auto-imported, but it will try to pull undefined from the component

```javascript
import undefined from './DoopTextInput.vue';
```

**Comment by so1ve** [comment]
I can't reproduce this, could you please provide a minimal reproduction?

**Comment by codymikol** [comment]
I'll try to get a repro today, Its happening to a specific project, but not others. I'll try to narrow down why.

**Comment by codymikol** [comment]
Just going to close this, I'll reopen if I can get a simple repro
