### ISSUE TITLE
typescript-language-features not work 

### ISSUE THREAD

**Issue by zjtakato** [vuejs/language-tools#4152]
# Version Infos
os：macos m3pro v14.3.1
vscode：v1.87.2
typescript-language-features： v1.0.0
Vue - Official：v2.0.7

[Error]: The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: Vue.volar. Please try disabling these extensions before filing an issue against VS Code.

**Comment by zernonia** [comment]
Could be related to https://github.com/vuejs/language-tools/issues/4130

**Comment by johnsoncodehk** [comment]
Duplicate of #4130
