### ISSUE TITLE
创建新文件并导入这个文件的时候会提示项目必须列出所有文件，或使用 "include" 模式

### ISSUE THREAD

**Issue by miraclemada** [vuejs/language-tools#4153]
当我创建一个新的vue文件时候 在页面中导入这个组件 编辑器会提示我
test.vue不在项目 "/tsconfig.app.json" 的文件列表中。项目必须列出所有文件，或使用 "include" 模式
当我重启vscode 文件提示正常

 "vue": "^3.4.21"
Vue - Official v2.0.7
TS :5.3.2

**Comment by miraclemada** [comment]
考虑到最新版本默认关闭了 Hybrid Mode 降级到2.0.6版本 恢复正常

**Comment by miraclemada** [comment]
考虑到这个版本默认关闭了Hybrid Mode 模式 打开后错误消失 新增文件可以正常监测到

**Comment by whiteQueen01** [comment]
解决了吗？

**Comment by davidmatter** [comment]
Closing this one due to inactivity. Feel free to create a new issue if you're still having issues with the latest version, thanks!
