### ISSUE TITLE
Lack of VNode Lifecycle Events

### ISSUE THREAD

**Issue by DaniilIsupov** [vuejs/language-tools#4154]
![image](https://github.com/vuejs/language-tools/assets/23086234/2014db25-b2b1-4d3f-ba2d-4fff55a6eb60)

details of functionality can be found in `Vue 3 Migration Guide`
https://v3-migration.vuejs.org/breaking-changes/vnode-lifecycle-events.html

**Comment by so1ve** [comment]
It seemed to be an upstream issue. Vue core's type definitions are not updated.

![image](https://github.com/vuejs/language-tools/assets/58381667/e722a1a5-5b15-4877-b1dc-f81c8344bea3)

**Comment by davidmatter** [comment]
Closing this one due to inactivity. Feel free to create a new issue if you're still having issues with the latest version, thanks!
