### ISSUE TITLE
Using defineEmits breaks $props type definition

### ISSUE THREAD

**Issue by piotrjoniec** [vuejs/language-tools#4155]
It seems that whenever defineEmits is used in a typescript component, it breaks the ability to extract its props in outside files.

Reproduction URL:
https://github.com/piotrjoniec/language-tools-4155-reproduction

Let's take this example component:

```vue
<template>
  <div></div>
</template>

<script setup lang="ts">
defineProps<{
  label: string;
  size: "sm" | "md" | "lg";
}>();
</script>
```

Then try to extract its properties in a different file. The result is correct:
```ts
import { ComponentInstance } from "vue";
import TestComponent from "./TestComponent.vue";

let props: ComponentInstance<typeof TestComponent>["$props"];

/* Result: ✔
let props: Partial<{}> & Omit<{
    readonly label: string;
    readonly size: "sm" | "md" | "lg";
} & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...>, never>
*/
```

Now let's add defineEmits to the component:
```vue
<template>
  <div></div>
</template>

<script setup lang="ts">
defineProps<{
  label: string;
  size: "sm" | "md" | "lg";
}>();

defineEmits(["event"]);
</script>
```

And this time extracting props produces this strange result:
```ts
import { ComponentInstance } from "vue";
import TestComponent from "./TestComponent.vue";

let props: ComponentInstance<typeof TestComponent>["$props"];

/* Result: ❌
let props: {
    $: ComponentInternalInstance;
    $data: {};
    $props: Partial<{}> & Omit<{
        readonly label: string;
        readonly size: "sm" | "md" | "lg";
        onEvent?: ((...args: any[]) => any) | undefined;
    } & ... 4 more ... & {
        ...;
    }, never>;
    ... 198 more ...;
    readonly wrap: <T>(value: T | T[]) => T[];
} & ... 7 more ... & Omit<...>
*/
```

It seems to include all global types from my project and also other vue properties which shouldn't be there.

I think that in this case it's possible to use `ComponentInstance<typeof TestComponent>["$props"]["$props"]` to get the actual props, but that doesn't seem like the intended behavior.

**Tested on:**
volar: 2.0.7
vue-tsc: 2.0.7
vue: 3.4.21
typescript: 5.4.3

**Comment by davidmatter** [comment]
I've looked into this one. This doesn't seem to be an issue anymore in the latest version. Feel free to create a new issue if you're still having problems, thanks!
