### ISSUE TITLE
vue模板文件双引号里面如果出现单引号，会导致后面的模板标签无法识别，js也没法格式化

### ISSUE THREAD

**Issue by dhj2020** [vuejs/language-tools#4161]
![image](https://github.com/vuejs/language-tools/assets/11954087/3d43c326-81f8-4387-b99c-7df3a1086e10)
![image](https://github.com/vuejs/language-tools/assets/11954087/a7d7cb34-dd26-41b0-93ee-ff02935eb0f6)

vue模板文件双引号里面如果出现单引号，会导致后面的模板标签无法识别，js也没法格式化，禁用后，启用vetur插件显示正常
![image](https://github.com/vuejs/language-tools/assets/11954087/2e610a4f-e204-48ba-8e6c-b1d7534932b0)
![image](https://github.com/vuejs/language-tools/assets/11954087/9c116d24-506b-45af-86d5-556b25e0d5ab)

**Comment by HendrikJan** [comment]
Google translate:

> If a single quotation mark appears in the double quotation marks in the vue template file, the template tag behind it will not be recognized, and JS will not be able to format it

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem, please provide minimal reproduction.
