### ISSUE TITLE
Vue - Official restart command

### ISSUE THREAD

**Issue by aryankarim** [vuejs/language-tools#4164]
Sometimes the Vue - Official reacts very slow or doesn't even react. If we have a restart extension just like Volar did, it would be really helpful.

**Comment by so1ve** [comment]
Just use `Restart tsserver`

**Comment by aryankarim** [comment]
> Just use `Restart tsserver`

I've tried, it doesn't work.

**Comment by adamrybak** [comment]
I used Volar restart regularly, having this back would be great.

**Comment by so1ve** [comment]
Unfortunately it is impossible to implement this feature as a separate command - since v2 we run volar as a typescript language plugin, and language server is handled by typescript itself.

**Comment by adamrybak** [comment]
I experience errors when I create new .vue files. Previously I would just reload the language server and all was good. Now I need to reload VSCode entirely.

**Comment by aryankarim** [comment]
@johnsoncodehk Thank you. It works fine right now.

For those who still have struggle, you should enable hybrid mode in the vscode settings.
