### ISSUE TITLE
custome block isn't highlighted

### ISSUE THREAD

**Issue by xcchcaptain** [vuejs/language-tools#4166]
i used **unplugin-vue-router** to generate route for app，**unplugin-vue-router**  use custome block 'route' to add meta info for the router.
but the block isn't highlighted
![image](https://github.com/vuejs/language-tools/assets/5080022/51940f38-31c7-43b6-ba40-9af2c16bcfff)

**Comment by KermanX** [comment]
It works on my machine (`Volar v2.0.21`, `Vue 1.90.1`):

<img width="300" src="https://github.com/vuejs/language-tools/assets/63178754/dd75229f-d41e-49ec-9298-a1fe92356dd4">

<details>
<summary> code </summary>

```vue
<script setup>
import { ref } from 'vue'
const content = ref('hello world')
</script>

<template>
	<main>
		{{ content }}
	</main>
</template>

<route lang="json">
{
	"a":1
}
</route>
```

</details>
