### ISSUE TITLE
VSCode cannot resolve Nuxt Auto Imports in a new/renamed file

### ISSUE THREAD

**Issue by kingychiu** [vuejs/language-tools#4167]
In my current vscode setup, Nuxt and vue typescript is working fine. But when I rename or create a file, the type and resolution wont work on that new file only. Any ideas?

Project/Folder Setup, it is under a workspace:
```
/app-backend
/app-frontend
/app-frontend/tsconfig.json # This refs /app-frontend/.nuxt/tsconfig.json
```

I found that in the existing file, tsconfig is found:
![Screenshot 2024-03-28 at 12 10 11 PM](https://github.com/vuejs/language-tools/assets/11500136/108e97bd-c4a9-4a4c-b978-8cc51d3908b0)

But in a new file, no tsconfig is found:
![Screenshot 2024-03-28 at 12 10 33 PM](https://github.com/vuejs/language-tools/assets/11500136/b3ce26e3-1ec0-49b2-8e52-cf52708e5c39)

For example, let's say I have a composable named useABC
VSCode can auto-suggest this when I type useAB only on an existing file.

AutoImport is working on an existing file:
![Screenshot 2024-03-28 at 11 49 55 AM](https://github.com/vuejs/language-tools/assets/11500136/ae371370-da35-4114-bb28-407033fd1258)

After renaming, the resolution becomes different:
![Screenshot 2024-03-28 at 11 50 54 AM](https://github.com/vuejs/language-tools/assets/11500136/be10aa11-d4c3-40cc-8f22-424e3f4b2118)

After restarting the entire VSCode, it will work again. Since now the vue restart command is removed (https://github.com/vuejs/language-tools/issues/4164), only restarting VSCode can resolve the issue.

**Comment by davidmatter** [comment]
You can execute the "Reload Window" command. No need to restart VSCode. I have the same problem in a conventional Vue3 project, without nuxt, in 2.0.7.

**Comment by johnsoncodehk** [comment]
This problem should be fixed in the master branch, here are the relevant commits:

- https://github.com/volarjs/volar.js/commit/6d7a54218a545553e55f27255878accb0c1b731e
- https://github.com/volarjs/volar.js/commit/17d1fa2f4086025ca14dd5a1e773eb3da36261f5
- https://github.com/volarjs/volar.js/commit/baf5a99d15b8e14cf638bef8217bcccf0d4cfee5

We need to wait for VSCode 1.88 to be released before we can update the extension. You can use 1.8.27 for now.

**Comment by johnsoncodehk** [comment]
The restart command was re-add by #4174.
