### ISSUE TITLE
 Nuxt built-in and auto imported components typed as unknown

### ISSUE THREAD

**Issue by ThomasBerne** [vuejs/language-tools#4170]
I use nuxt 3 and Vue Official 2.X+

Built-in and auto imported components are typed as unknown : 

![image](https://github.com/vuejs/language-tools/assets/23033483/84ed764d-c098-44eb-b100-ba1137350822)

Even though they are in the .nuxt/components.d.ts

![image](https://github.com/vuejs/language-tools/assets/23033483/1818c84a-e4e5-4b16-9a2a-7b0f4f88f8c2)

Imported by the .nuxt/tsconfig.json 

![image](https://github.com/vuejs/language-tools/assets/23033483/868251ed-3be6-4057-b736-e36942920b80)

.nuxt/tsconfig.json extended by my project tsconfig.json

![image](https://github.com/vuejs/language-tools/assets/23033483/634bf37a-b919-4867-808e-e86fbe997249)

**Comment by johnsoncodehk** [comment]
1. Are you using 2.0.7?
2. If yes, is Hybrid Mode enabled?

**Comment by ThomasBerne** [comment]
I have tried using. 2.6, 2.7 and insider versions. What is the hybrid mode ? I don't think I use It. I'm all on vue 3.

**Comment by so1ve** [comment]
I can confirm this issue with a fresh [nuxt content starter](https://content.nuxt.com/).

**Comment by ThomasBerne** [comment]
Thank you @so1ve I tried a reproduction with a fresh nuxt 3 install but it works like a charm.

**Comment by ThomasBerne** [comment]
Activing or desactiving the hybrid mode doesn't change anything on my side.

**Comment by johnsoncodehk** [comment]
@ThomasBerne I tried using nuxt-typed-router with a newly created project but could not reproduce the problem, can you see if there is any difference?

https://github.com/johnsoncodehk/issue-4170-repro

**Comment by ThomasBerneHCSE** [comment]
Indeed i cannot reproduce either with only the nuxt typed router package. This must be a collision of nuxt packages I guess. I'll try to reproduce it.

**Comment by ThomasBerneHCSE** [comment]
I successfully reproduced adding vuetify and nuxt typed router to a clear nuxt install : 
https://github.com/ThomasBerneHCSE/issue-4170-repro

I used npm as the default package manager.

**Comment by ThomasBerneHCSE** [comment]
You can see the problem in the pages/[id]/index.vue

**Comment by johnsoncodehk** [comment]
I tried locally and in Codespace but couldn't reproduce (using npm).

<img width="596" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/f1d7e2d4-beb0-4a3a-9c0f-84048bdf530d">

**Comment by ThomasBerneHCSE** [comment]
Like if vuetify was overwriting GlobalComponents definition. But only when it is installed alongside of the nuxt-typed-router package.

**Comment by johnsoncodehk** [comment]
Confirmed. 👍

**Comment by johnsoncodehk** [comment]
I think this problem needs to be solved by Nuxt, currently Nuxt generates GlobalComponents as:

```ts
declare module 'vue' {
	export interface GlobalComponents {
		Test: (typeof import('../components/Test.vue'))['default'];
	}
}
```

To avoid types being overwritten in the npm node_modules structure, it should probably be generated as:

```ts
export interface _GlobalComponents {
	Test: (typeof import('../components/Test.vue'))['default'];
}

declare module '@vue/runtime-core' {
	export interface GlobalComponents extends _GlobalComponents { };
}

declare module '@vue/runtime-dom' {
	export interface GlobalComponents extends _GlobalComponents { };
}

declare module 'vue' {
	export interface GlobalComponents extends _GlobalComponents { };
}
```

@danielroe can you or someone take up this issue? Thanks.
