### ISSUE TITLE
command 'volar.vue.findAllFileReferences' not found

### ISSUE THREAD

**Issue by ReySun** [vuejs/language-tools#4171]
### issue desc: 
1. select vue file and right click, choose 'Find File References'.
2. vscode throw warning 「command 'volar.vue.findAllFileReferences' not found」,and it not works.
<img width="475" alt="iShot_2024-03-28_16 50 24" src="https://github.com/vuejs/language-tools/assets/20747990/c2f72e2e-12fa-4c8b-8a04-7bc435f885cf">

### env:
1. macOS 14.3.1
2. vscode 1.87.2
3. Vue - Official 2.0.7

### remark:
reinstall another 「Vue - Official」version，such as v1.8.27, it works ok.
<img width="612" alt="image" src="https://github.com/vuejs/language-tools/assets/20747990/1008f88d-70a6-4bd2-982c-6f92eff1002f">

**Comment by athoma13** [comment]
Not sure if it's related but when I try 'right click' -> 'Find File References' on any vue file. I get:

'Find file references failed. Unknown file type.'
source: Typescript and Javascript Language Features...

**Comment by ReySun** [comment]
I solved the problem, steps:
1. update `vscode@1.88.0` and `vue - Official@2.0.10`
2. open vscode `keyboard shortcuts `, search `findFileReferences` and delete `volar.vue.findAllFileReferences `
3. restart vscode and **always open a file**, then right click
