### ISSUE TITLE
VSCode Extension overrides eslint/prettier settings

### ISSUE THREAD

**Issue by jdmr** [vuejs/language-tools#4173]
The VSCode extension (Vue Official) is overriding rules that I have setup with eslint/prettier for my project. I had to set the semi rule to true, because this extension adds semicolons to all the imports, even though I have them off on the eslint/prettier settings. The other thing is doing is with an import of a long list of types it's sending it all the way to left, and eslint/prettier complain about it because it doesn't have aligned properly. Is there a way that we can turn off this extension's styling rules?

**Comment by djom202** [comment]
> The VSCode extension (Vue Official) is overriding rules that I have setup with eslint/prettier for my project. I had to set the semi rule to true, because this extension adds semicolons to all the imports, even though I have them off on the eslint/prettier settings. The other thing is doing is with an import of a long list of types it's sending it all the way to left, and eslint/prettier complain about it because it doesn't have aligned properly. Is there a way that we can turn off this extension's styling rules?

The same issue

**Comment by WalkAlone0325** [comment]
The same issue

**Comment by RayGuo-ergou** [comment]
There seems having a race condition. You must have all three formatting running ( lsp, eslint and prettier). 

You can fix this by disable `editor.formatOnSave` for vue files, eslint does not emit format event to the client to format your code thus eslint would still work without `editor.formatOnSave` off.

**Comment by djom202** [comment]
Thank you, @RayGuo-ergou! Following your comment I disabled editor.formatOnSave for all files, and others extensions in order to discard if any extension was causing this, except **Vue - Official** and Sublime text Keymap that I need to work, and in this case and the problem still occurs, so when I disabled the Vue - Official, I lost all highlighting however the issue is no longer there.

**Comment by RayGuo-ergou** [comment]
> I tried your solution, but it's not working for me.

Not work as in language server still format your code or eslint does not work?

**Comment by jdmr** [comment]
As in eslint formats first, but then the plug-in formats it ignoring the
eslint rules. The race condition is still happening

**Comment by RayGuo-ergou** [comment]
I have tried your config and it works fine for me, better to make sure it's disabled in setting's UI. If this is successfully configured, then it may formatted by other formatters.  

![image](https://github.com/vuejs/language-tools/assets/33137074/4899a638-b0cd-4f18-92bb-b219eebbdbcf)

**Comment by jdmr** [comment]
Hmm. I have it disabled on the settings and it still doesn't work for me.
![Screenshot 2024-04-01 at 11 39 11 AM](https://github.com/vuejs/language-tools/assets/148428/6fa14c6b-676a-4cbb-aae4-076057b94eed)

Here's a [video of what happens when I save](https://nextcloud.swau.edu/index.php/s/bjzys7WJageDaWX)

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/vuejs/language-tools/assets/33137074/1ad8d6c8-c593-4ba7-beea-0673e0431dff)

I think there's another formatter running on file save. Here's the result if i only let vue language server format my code, and i did see an option to configure this.

**Comment by jdmr** [comment]
A warning started showing up after an update that says something along the lines of vue-official conflicting with the deno extension. Disabled the deno plugin for the workspace, and auto-formatting works again :)
