### ISSUE TITLE
vue-tsc execution is very, very slow compared to 1.8.0

### ISSUE THREAD

**Issue by RJQingHuan** [vuejs/language-tools#4177]
Thank you for your work. I love vue3.

**Comment by RJQingHuan** [comment]
https://github.com/RJQingHuan/test-vue-tsc.git

run packages/admin check

**Comment by skywalker512** [comment]
I also found this issue in our internal project, especially with element-plus. resolveModuleNamesWorker many times longer did it take to use a compared to tsc

The following is the data of a simple project that only references element-plus, which has been greatly improved. Thank you for your efforts. @johnsoncodehk 

- after: pnpm vue-tsc  13.58s user 1.10s system 142% cpu 10.269 total
- before: pnpm vue-tsc  41.12s user 4.71s system 117% cpu 38.894 total
