### ISSUE TITLE
Initialization is slow, each initialization takes about three minutes. Opening a new file will also be initialized for a long time

### ISSUE THREAD

**Issue by RJQingHuan** [vuejs/language-tools#4183]
![image](https://github.com/vuejs/language-tools/assets/53939074/e7ec102b-26eb-4883-8d6d-8db049ffb59c)

**Comment by RJQingHuan** [comment]
https://github.com/RJQingHuan/test-vue-tsc.git

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/89e8e785f51a1633e003fafa1f351f6e63fed161.
