### ISSUE TITLE
Toggle comments not working in style area

### ISSUE THREAD

**Issue by joy-yu** [vuejs/language-tools#4187]
The issue is very similar to the case https://github.com/vuejs/language-tools/issues/3776.
But it only fails in style area.

VSCode Version: 1.87.2
Vue - Official: v2.0.8

https://github.com/vuejs/language-tools/assets/9348314/443a98cd-5666-4ebb-a5d4-2a1bb8f2ef39

**Comment by pedrodgcouto** [comment]
The same is happening to me on the <script> area as well.

**Comment by davidmatter** [comment]
Verified that this one has been fixed in the lastest 2.x versions.
