### ISSUE TITLE
Hybrid Mode 导致js/ts崩溃

### ISSUE THREAD

**Issue by RanierYu** [vuejs/language-tools#4191]
每当打开 Hybrid Mode 就会发生如下情况
<img width="695" alt="image" src="https://github.com/vuejs/language-tools/assets/62528887/e575a456-4b28-4b4d-a481-ebccbc4fdcd4">

**Comment by so1ve** [comment]
Do you have a `tsconfig.json` file? Could you please list your vscode extensions?

**Comment by RanierYu** [comment]
Created using vite
tsconfig.json 
``` json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ],
  "compilerOptions": {
    "strict": false,
    "strictNullChecks": false
  }
}
```

<img width="878" alt="image" src="https://github.com/vuejs/language-tools/assets/62528887/f69288a1-f130-4d03-b451-644f7b77acd6">

**Comment by johnsoncodehk** [comment]
Can you reproduce the issue on VSCode Insiders?

**Comment by RanierYu** [comment]
> Can you reproduce the issue on VSCode Insiders?

Yes, I will have this problem once I upgrade to version 2.x. I don’t know if it is a problem with my local software environment.

**Comment by johnsoncodehk** [comment]
1. Will installing https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next solve the problem?
2. Please share the TS server log with the `TypeScript: Open TS Server log` command.

**Comment by RanierYu** [comment]
I'm a novice and can't understand 🥹
[tsserver.log](https://github.com/vuejs/language-tools/files/14832145/tsserver.log)

**Comment by AlaricWeb** [comment]
![image](https://github.com/vuejs/language-tools/assets/161679330/9dc5ea82-a789-4020-b70b-1cbb4a293e6e)

**Comment by johnsoncodehk** [comment]
Please update to VSCode 1.88. If the problem still exists, please open a new issue and provide a reproduction link.
