### ISSUE TITLE
最新版本 typescript alias 似乎不生效

### ISSUE THREAD

**Issue by AlaricWeb** [vuejs/language-tools#4192]
提示错误

**Comment by AlaricWeb** [comment]
![image](https://github.com/vuejs/language-tools/assets/161679330/0e5a8e5e-76dc-4908-9bf3-429ddb85aa14)

**Comment by davidmatter** [comment]
I assume these issues have been stabilized in the latest 2.x versions. If you're still encountering problems, please create a new issue. Best case: Provide an example project that we can look into, thanks!
