### ISSUE TITLE
安装2.0.7及以上版本好像无效？

### ISSUE THREAD

**Issue by Saiyan-hl0408** [vuejs/language-tools#4193]
不报错、不提示补全reactive、ref声明的对象数据
回退至2.0.6-2.0.0恢复正常
图1、图2为2.0.7版本测试，没有报错，也没有对象属性补全(我甚至认为插件完全没有生效？)
图3为回退至2.0.6恢复正常
![屏幕截图 2024-04-02 162903](https://github.com/vuejs/language-tools/assets/57097895/6ebf662f-5e4c-4c8e-aa92-748517225fd0)
![屏幕截图 2024-04-02 162925](https://github.com/vuejs/language-tools/assets/57097895/c3e7720e-630e-4d0d-abe3-dcc194db0e65)
![屏幕截图 2024-04-02 163106](https://github.com/vuejs/language-tools/assets/57097895/89c62c40-6470-4df0-8d9d-2dbe2faf210d)

**Comment by lingcha** [comment]
并且没有导入的组件变成了
![1712047941864](https://github.com/vuejs/language-tools/assets/29124405/00615e55-61bd-4a90-94d6-3e0bd1d15457)
也不报错了。

**Comment by JakeLaoyu** [comment]
+1

**Comment by johnsoncodehk** [comment]
Please update to VSCode 1.88.
