### ISSUE TITLE
@vue-expect-error does not seem to work in the language-tools tsc tests

### ISSUE THREAD

**Issue by tinco** [vuejs/language-tools#4203]
For example in the file `test-workspace/tsc/vue3/v-bind-require-object/main.vue` the code is:

```
<script setup lang="ts">
const foo = 1;
</script>

<template>
	<!-- @vue-expect-error -->
	<div v-bind="foo"></div>
</template>
```

To expect that `foo = 1` makes the tsc fail. The error is succesfully repressed, so that works well. However if you change the code to `foo = {}`, like so:

```
<script setup lang="ts">
const foo = {};
</script>

<template>
	<!-- @vue-expect-error -->
	<div v-bind="foo"></div>
</template>
```

Then I would expect the test suite to fail because of there no longer being an error. Instead neither vscode, nor running:

```
 pnpm run test packages/tsc
```

Gives any error.

If I remove the `<!-- @vue-expect-error -->` then the code properly typechecks with `foo = {}` and properly fails with `foo = 1`.

**Comment by so1ve** [comment]
You should use `pnpm run test tsc`, since `vitest packages/tsc` doesn't match any tests.

**Comment by tinco** [comment]
hi! that makes no difference for me, still same result:

![image](https://github.com/vuejs/language-tools/assets/22532/cb52015f-71f6-4970-a1fe-35ff51d98427)

**Comment by tinco** [comment]
I can't figure out how to debug this, how do you get it to print the generated typescript?

**Comment by so1ve** [comment]
Cool! Seemed to be a bug.

**Comment by tinco** [comment]
I'm sorry I'm having a lot of trouble debugging this. In the tsc package it says:

```
require('../index.js').run();
```

But if I add `console.log` to `index.ts` in that directory it doesn't affect the test output even though if I add `console.log`'s to `vue-tsc.js` that does print. I don't understand where that `index.js` is supposed to be, or how it's generated and how I trigger regeneration.

Do you have any pointers to how to debug things in this project?

**Comment by tinco** [comment]
I suppose I missed the build step. Still awkward that I can't figure out where the results of the build step actually go, but I guess that's a mystery for the ages.

I did figure out that this was already broken in v2.0.0. Now I'm struggling to get v1.8.7 to build.

**Comment by tinco** [comment]
Ok I don't know why I struggled with that at first, but `pnpm install` and then `pnpm build` worked just fine. I can confirm that things used to work in v1.8.27. So something went wrong during the v2.0.0 upgrade, which I suppose was a big change.

**Comment by tinco** [comment]
Alright, `git bisect` tells me:


```
tinco@tinco-aero-dev language-tools % git show tinco@tinco-aero-dev language-tools % git bisect good
72d3c6c4074c2761fe9e760538bccb16ad543539 is the first bad commit
commit 72d3c6c4074c2761fe9e760538bccb16ad543539
Author: Johnson Chu <johnsoncodehk@gmail.com>
Date:   Wed Dec 6 22:03:24 2023 +0800

    refactor(langauge-core): codegen based on Generator (#3778)

 packages/language-core/src/generators/script.ts    |  964 +++++-----
 packages/language-core/src/generators/template.ts  | 1946 +++++++++-----------
 packages/language-core/src/generators/utils.ts     |   19 +-
 packages/language-core/src/plugins/vue-tsx.ts      |  115 +-
 packages/language-core/src/types.ts                |    2 +
 packages/language-core/src/utils/transform.ts      |   72 +-
 packages/language-service/src/helpers.ts           |    4 +-
 .../src/plugins/vue-toggle-v-bind-codeaction.ts    |    6 +-
 8 files changed, 1541 insertions(+), 1587 deletions(-)
```

But that's a huge commit so I don't think it's much help unfortunately.
