### ISSUE TITLE
【疑惑】怎么动不动，就弃用扩展了？

### ISSUE THREAD

**Issue by juntaosun** [vuejs/language-tools#4205]
首先，感谢Vue的付出和努力！
做为一名Vue粉，最近的扩展升级体验不太友好啊！

前景提要：
之前一直用 TypeScript Vue Plugin (Volar) 挺好的。
过完年，在打开 VScode 就突然变灰！（此扩展已弃用。请改用 [Vue - Official]扩展。）

新版体验：
满心欢喜安装后，谁知道这个新扩展的头疼 Bug 。列举如下：
（1）新创建的 ts  类，居然不识别，vue中无法提示自动导入。必需重启 vscode 后正常。
（2）新创建的 vue 文件，概率性不识别，vue中无法提示自动导入。必需重启 vscode 后正常。
（3）vue 中的 import 有时还报错不识别（明明路径正确）。必需重启 vscode 后正常。
（4）从此，经常重启 vscode 成了开发常态 ，头疼也犯了...
（5）我甚至怀疑是 vscode 出了BUG，还重装了 vscode 。

---

版本：Vue - Official  v2.0.8
Language Support for Vue

A，重现步骤一（如图）：
![00](https://github.com/vuejs/language-tools/assets/22288197/666c43a8-fa39-4f32-b459-ae24b697d459)
任意新建 Test.ts 类，在 App.vue 输入 Test ，表现为不识别（ 无代码提示，无法提示导入）。

B，重现步骤二（如图）：
![11](https://github.com/vuejs/language-tools/assets/22288197/e89012c6-7269-43a2-8c39-49568bb325cd)
重启 VScode 后，在 App.vue 输入 Test ，可以看到正常识别，可以提示自动导入。

---

让我身边的Vue开发小伙伴们，最为吃惊的是：
TypeScript Vue Plugin (Volar) 截止下载量：2,148,055 。
要知道，惊人的数字背后，是无数开发者的认可和支持。

![11111](https://github.com/vuejs/language-tools/assets/22288197/8aaf07e0-4de4-4dea-bc93-29c9f796b9a3)

个人建议：
升级和改名，相信你们也是为了做的更完善和更好。
但同时，（请尽可能的保留）原来（旧的插件）项目，让开发者有（自由选择）和（过渡时间）。
而不是强制弃用和停用，让 “2,148,055” 这么多人，一窝蜂体验新版本的BUG（在所难免）。
当然随着时间的推移和努力，BUG终将会被消灭，只是这个操作不太友好啊。

最后，能否恢复 TypeScript Vue Plugin (Volar)  的下载呢？再次感谢对Vue的付出和努力！

**Comment by wjw020206** [comment]
可以恢复下载
按 `Ctrl+P` 或者 `Command+P` 输入如下指令就可以下载了
```
ext install Vue.vscode-typescript-vue-plugin
```

**Comment by wlonghaha** [comment]
新版本确实很多问题（特别是windows），如混合模式下提示（html标签，vue指令）慢，高亮错误，cpu狂转，ts server重启，关了混合模式高亮错误，代码自动展开，提示重复（每一个变量重复提示3遍）
回到1.8.27版本，工作区启用takeover模式（拓展搜索@builtin typescript，第一个禁用工作区），ts文件import vue文件红线，加下vue文件ts类型

**Comment by wjw020206** [comment]
> > 可以恢复下载 按 `Ctrl+P` 或者 `Command+P` 输入如下指令就可以下载回弃用的 TypeScript Vue Plugin (Volar)
> > ```
> > ext install Vue.vscode-typescript-vue-plugin
> > ```
> 
> 尝试使用该命令安装了，但 vscode 弃用的扩展似乎（无法工作）。 不仅“设置“里找不到，而且 vue 文件代码全白。 ![33](https://private-user-images.githubusercontent.com/22288197/319478281-5ebbdf3c-be2f-49dc-8368-c2a859527506.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTUyMTcsIm5iZiI6MTcxMjIxNDkxNywicGF0aCI6Ii8yMjI4ODE5Ny8zMTk0NzgyODEtNWViYmRmM2MtYmUyZi00OWRjLTgzNjgtYzJhODU5NTI3NTA2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA3MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNDg2MzkxOThlOTk1NjZkY2U0NmViYjA1NDAwZGYxMTgxNjE5YjZlNTRiZGYxMWI5YWE1ZTQ1N2YwNjc5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCQK_Lij1FawAI55zJ0ryblVBgOUfOvtrbDNkLV62_k)
> 
> 只能重新装回 （ Vue - Official ） ，等待后边版本修复了。

不能只装这个插件，这个插件只是TS服务，Vue - Official也要装，Vue - Official才是提供语法高亮的主体，不过你可以安装回1.8.27版本，我目前的组合就是TypeScript Vue Plugin (Volar) + Vue - Official 1.8.27的组合，开发没什么影响

**Comment by wjw020206** [comment]
目前看官方的描述似乎只有等VSCode 发布了1.88版本之后 Vue - Official2.x 的版本才能正常使用了

**Comment by wjw020206** [comment]
VS Code v1.88 计划于 4 月 4 日(也就是今天)发布，到时候再看看 Vue - Official 2.x 能否正常使用吧

**Comment by johnsoncodehk** [comment]
Please update to VSCode 1.88.
