### ISSUE TITLE
Regression: properties erroneously reported as possibly null

### ISSUE THREAD

**Issue by Cherry** [vuejs/language-tools#4209]
With the following contrived `example.vue` file:
```vue
<script setup lang="ts">
type Bar = {
	id: string;
} | null;

type Example = {
	foo: {
		bar: Bar;
	};
	doSomething(id: string): void;
};
const example: Example = {
	foo: {
		bar: {
			id: '123',
		},
	},
	doSomething(id: string) {
		console.log(id);
	},
};
</script>
<template>
	<button
		v-if="example.foo.bar"
		type="button"
		v-on:click="example.doSomething(example.foo.bar.id)"
	>
		{{ example.foo.bar.id }}
	</button>
</template>

```

`vue-tsc@2.0.7` reports no errors.
`vue-tsc@2.1.0` reports: `'__VLS_ctx.example.foo.bar' is possibly 'null'. [Ln 27, Col 35]`

Given that this is wrapped in a `v-if="example.foo.bar"`, I wouldn't expect this to ever be null.

**Comment by Cherry** [comment]
Specifically, it seems to be due to the bump of volar. Here's a minimal reproduction:

- See branch `main` for working in `vue-tsc@2.0.7` and older `volar`
- See branch `2.1.0` for erroring in `vue-tsc@2.1.0` and newer `volar`

https://github.com/Cherry/volar-erroneous-null-repro

Run `npm run test` in each branch to see the issue.

**Comment by sid-6581** [comment]
I have the same issue. `v-if` doesn't narrow the type for events anymore in 2.0.10.
