### ISSUE TITLE
windows下提示慢，折叠代码高亮错误，import代码自动展开

### ISSUE THREAD

**Issue by wlonghaha** [vuejs/language-tools#4210]
版本: 1.88.0 (user setup)
提交: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
日期: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19044

https://github.com/vuejs/language-tools/assets/33210369/fa037b87-31a3-4393-92a1-7d58561822cd

**Comment by FUNKAKIT** [comment]
我刚切回Mac，确实没有卡顿的问题，似乎确实是Windows环境下才有的问题

**Comment by Mutter45** [comment]
我这也是呢，好像切到2.0.5版本就好了，更好版本代码折叠一直有问题

**Comment by yulin96** [comment]
我也遇到了相同的问题，windows下建议出现的慢
1.8.27版本在类似<div c></div> 输入c的时候也可以很快出现建议，2.0.12需要等待一会才会出现
![Recording 2024-04-11 at 11 07 24](https://github.com/vuejs/language-tools/assets/40719410/7c2b99f5-d8f2-4a83-b632-bb23ae3fca75)

mac下基本就是实时的，不太清楚是不是配置的问题

**Comment by cvpv** [comment]
我也有这个问题，在windows下面提示词出来非常慢
