### ISSUE TITLE
html.format.wrapAttributes configuration is invalid for vue file

### ISSUE THREAD

**Issue by satrong** [vuejs/language-tools#4212]
My vscode config:
```json
{
  "html.format.wrapAttributes": "preserve-aligned"
}
```

but, here override the configuration of vscode (`wrapAttributes` is always `'auto'`):

https://github.com/vuejs/language-tools/blob/fd5c4a5c2c3879610f75565fce58fb98a91dc7ef/packages/language-service/lib/plugins/vue-sfc.ts#L36-L45

Is there any other way besides using a third-party plugin to make my vscode configuration take effect?

**Comment by johnsoncodehk** [comment]
In next release you can use `"vue.format.wrapAttributes": "preserve-aligned"`.

**Comment by satrong** [comment]
👍
