### ISSUE TITLE
Clicking on a CSS class name in the template does not scroll to the definition and no uses are listed in the style section

### ISSUE THREAD

**Issue by angelov-a** [vuejs/language-tools#4216]
Before it was possible to Cmd+click on a CSS class in the `<template>` section and it would scroll to the corresponding definition in the `<style>` tag.

In the `<style>` tag for each definition there were listed uses with links to the `<template>`.

These two functionalities have stopped working after the Official Vue plugin release.

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/3986
