### ISSUE TITLE
Name component popup modal while using Microsoft LiveShare in VS Code

### ISSUE THREAD

**Issue by richmondjoy** [vuejs/language-tools#4217]
There was an issue filed with LiveShare that seems to be stemming from the Vue-Official extension starting with v2.0. See issue here: (https://github.com/microsoft/live-share/issues/5031)

Our team is not seeing the issue after reverting the Vue-Official extension to v1.8.27.

**Comment by johnsoncodehk** [comment]
As I know we don't have a way to avoid this problem, but I just added the `vue.codeActions.askNewComponentName` setting in https://github.com/vuejs/language-tools/commit/6e77c36c0c5419a0dc1da918556cd3afec91f299. You can disable it to completely avoid input box.
