### ISSUE TITLE
File Explorer "Find File References" not working for .vue SFC

### ISSUE THREAD

**Issue by ludwig801** [vuejs/language-tools#4221]
### Description
When **not** in hybrid mode, when right-clicking on a `.vue` file, VSCode responds with the error shown in the picture below.
Works without an issue when in hybrid mode.

![image](https://github.com/vuejs/language-tools/assets/5622673/bc620471-b7f5-4051-804e-4046ad3ca9d4)

### Expected behaviour
Actually finding the references for the SFC component.

### Environment

- OS: `Windows 11 Version 10.0.22631 Build 22631`
- VSCode: `v1.87.2` (latest)
- Vue Extension: `v2.0.10`
- Typescript: `v5.2.2`

### Additional information
Possibly related to https://github.com/vuejs/language-tools/issues/4171, but not entirely sure, hence the new issue.

**Comment by dwjohnston** [comment]
This appears to have reared it s head again. 

Version: 1.111.0 (Universal)
Commit: ce099c1ed25d9eb3076c11e4a280f3eb52b4fbeb
Date: 2026-03-06T23:06:10Z
Electron: 39.6.0
ElectronBuildId: 13330601
Chromium: 142.0.7444.265
Node.js: 22.22.0
V8: 14.2.231.22-electron.0
OS: Darwin arm64 25.2.0

**Comment by ssipak** [comment]
Tried VSCode 1.110.1 - didn't work either. Had to downgrade VSCode to 1.109.5.
