### ISSUE TITLE
The JS/TS language service crashes

### ISSUE THREAD

**Issue by wukuang-818** [vuejs/language-tools#4222]
Type: <b>Bug</b>

JS/TS 语言服务已立即崩溃 5 次。不会重新启动该服务。 这可能是由以下其中一个扩展提供的插件引起的: bierner.lit-html, VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode, Vue.volar 请在针对 VS Code 提交问题之前尝试禁用这些扩展。
TypeScript Server Error (5.4.3) Debug Failure. False expression. Error: Debug Failure. False expression. at TextStorage.getFileTextAndSize (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177999:15) at TextStorage.reloadWithFileText (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177922:104) at TextStorage.getOrLoadText (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178033:12) at TextStorage.tryUseScriptVersionCache (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178019:12) at TextStorage.getSnapshot (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:177950:24) at ScriptInfo.getLatestVersion (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178258:22) at ConfiguredProject2.getScriptVersion (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178750:25) at f (c:\Users\aaa_w.vscode\extensions\vue.volar-2.0.10\node_modules\typescript-vue-plugin-bundle\index.js:2:30540) at t.getScriptSnapshot (c:\Users\aaa_w.vscode\extensions\vue.volar-2.0.10\node_modules\typescript-vue-plugin-bundle\index.js:2:30429) at getOrCreateSourceFileByPath (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146393:35) at Object.getOrCreateSourceFile (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146389:14) at c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146313:42 at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121822:24) at findSourceFileWorker (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124259:23) at findSourceFile (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124178:20) at processImportedModules (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124609:11) at findSourceFileWorker (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124314:7) at findSourceFile (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124178:20) at processImportedModules (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124609:11) at findSourceFileWorker (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124314:7) at findSourceFile (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124178:20) at c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124127:22 at getSourceFileFromReferenceWorker (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124096:26) at processSourceFile (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124125:5) at processRootFile (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123923:5) at c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122657:41 at forEach (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2361:22) at createProgram (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122657:5) at synchronizeHostDataWorker (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146344:15) at synchronizeHostData (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146240:7) at Object.getProgram (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146418:5) at ConfiguredProject2.updateGraphWorker (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179478:41) at ConfiguredProject2.updateGraph (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179327:32) at ConfiguredProject2.updateGraph (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:180588:24) at_ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182326:13) at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183427:26) at c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183707:64 at flatMap (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2609:17) at _ProjectService.applyChangesInOpenFiles (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183707:24) at updateOpen (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:184910:29) at c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187518:69 at IpcIOSession.executeWithRequestId (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187510:14) at IpcIOSession.executeCommand (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187518:29) at IpcIOSession.onMessage (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187560:51) at process. (c:\Users\aaa_w\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:189169:14) at process.emit (node:events:517:28) at emit (node:internal/child_process:944:14) at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Extension version: 2.0.10
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (6.46GB free)|
|Process Argv|--crash-reporter-id 547793e6-c91b-4613-a1a2-21808fe8c8ea|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by shunichio** [comment]
印象中好像经常遇到这个问题，存在好久了。

**Comment by johnsoncodehk** [comment]
In the next version you can disable the typescript plugin by setting `"vue.server.hybridMode": false`. Please refer to #4226.

**Comment by wukuang-818** [comment]
thank you !
| |
武贶
|
|
***@***.***
|
---- Replied Message ----
| From | Johnson ***@***.***> |
| Date | 4/7/2024 18:12 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [vuejs/language-tools] The JS/TS language service crashes (Issue #4222) |

In the next version you can disable the typescript plugin by setting "vue.server.hybridMode": false. Please refer to #4226.
