### ISSUE TITLE
vue-tsc 2.0.10 remove the imported type when emit .vue.d.ts

### ISSUE THREAD

**Issue by vsdeeper** [vuejs/language-tools#4224]
### version
`
"vue": "^3.4.21"
"vue-tsc": "^2.0.10"
"typescript": "~5.4.0"
`
`pnpm 8.15.5`
`node 18.19.0`

### tsconfig.json
`
{
  "extends": "@vue/tsconfig/tsconfig.lib.json",
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "auto-imports.d.ts",
    "components.d.ts"
  ],
  "exclude": ["src/**/__tests__/*", "src/App.vue", "src/main.ts"],
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ES2020",
    "moduleResolution": "Node",
    "strict": true,
    "lib": ["ESNext", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
`
### scripts
`
"type-emit": "vue-tsc -p tsconfig.json -w --declarationDir dist/types"
`
`$ pnpm type-emit`

### question
![image](https://github.com/vuejs/language-tools/assets/15762056/41acc26a-5cfd-47c1-a84f-7f23f58b3803)

![image](https://github.com/vuejs/language-tools/assets/15762056/7f22001b-648f-4d11-b8c7-3017d54da00a)

**Comment by so1ve** [comment]
Why do you expect vue-tsc to keep this import? It is not used elsewhere except a `shallowRef`.

**Comment by vsdeeper** [comment]
> Why do you expect vue-tsc to keep this import? It is not used elsewhere except a `shallowRef`.
I just try to expose the myColorPickerRef, but it can not emit .vue.d.ts, and no error message output.
![image](https://github.com/vuejs/language-tools/assets/15762056/13eaba44-760d-4ddf-8741-fb9d66120434)

**Comment by vsdeeper** [comment]
Has anyone encountered the same problem as me? This problem appeared after the vue-tsc update.

**Comment by vsdeeper** [comment]
> Why do you expect vue-tsc to keep this import? It is not used elsewhere except a `shallowRef`.

Can I expose a component instance use defineExpose?

**Comment by vsdeeper** [comment]
可以使用 defineExpose 暴露一个子组件的实例吗？发现当暴露一个子组件实例时，无法输出 .vue.d.ts.
