### ISSUE TITLE
升级到2.0.10后，导致JS语言服务崩溃

### ISSUE THREAD

**Issue by shunichio** [vuejs/language-tools#4225]
开发者你好，今天复工以后将vscode设计到最新版1.88.0（windows），插件也升级到了最新版本2.0.10，然后就出现了下图的错误，希望可以修复一下，谢谢。

![image](https://github.com/vuejs/language-tools/assets/23553358/303dfde4-c2b2-4a71-a8b9-693d89e05e5a)

**Comment by ovensi** [comment]
直接降级到2.0.6解决问题

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4222
