### ISSUE TITLE
vue-ignore does not work anymore

### ISSUE THREAD

**Issue by ig-onoffice-de** [vuejs/language-tools#4232]
I have a vue component, which uses `@vue-ignore`. 
The build worked fine with version `2.0.10` but it reports errors with version `2.0.11`. 
Seems like the `@vue-ignore` is not working at all.

The error is the same as if I just remove the line.

**Comment by volarname** [comment]
same issue here

**Comment by ig-onoffice-de** [comment]
I still have the issue with version `2.0.13`.
The `@vue-ignore` expression is above a `<template>` tag and is used for the `slotProps`.
