### ISSUE TITLE
vscode 中组件的属性显示错误

### ISSUE THREAD

**Issue by Mr-Sang** [vuejs/language-tools#4234]
![image](https://github.com/vuejs/language-tools/assets/105386063/30eed5a1-506a-4f57-8e35-8f08b3eb3c80)

扩展版本：v2.0.11

`align`和`justify`一样都是组件的属性，但`align`并没有被正确渲染。

**Comment by KazariEX** [comment]
这是由于 `align` 是一个已弃用的 HTML 属性，语法高亮的正确与否取决于所使用的主题是否选择做出区分。

![image](https://github.com/user-attachments/assets/478d6e0c-926f-4c59-a336-5a640345d6ae)

**Comment by KermanX** [comment]
See #4510
