### ISSUE TITLE
(vscode) pug template is missing attribute tips 组件属性提示缺失

### ISSUE THREAD

**Issue by fengjac** [vuejs/language-tools#4235]
```
"@vue/language-plugin-pug": "^2.0.11",
"pug": "^3.0.2",
Vue - Official: v2.0.10
```

It can show attribute tips in normal template. 常规的 template 是可以正常提示

![image](https://github.com/vuejs/language-tools/assets/20239780/e41256f5-e113-47c9-bf17-ff9ac1699a0c)

But it does not work in pug template. 但是用 pug template 就没有了提示

![image](https://github.com/vuejs/language-tools/assets/20239780/fec33b99-6249-4222-a680-e2573d633176)

**Comment by hc-chumak** [comment]
i have same problem from v2.0 :/

**Comment by zaxlct** [comment]
I have same problem from v2.0.14

**Comment by wongsuksiri** [comment]
Indeed, the old version of Volar worked correctly, but the current Vue/language tools cannot perform in the same way. Unfortunately, I cannot install Volar as it has been deprecated.

@johnsoncodehk

**Comment by itzaks** [comment]
Same issue here. Component props are not respected in the autocomplete at the moment.

**Comment by shadowdreamer** [comment]
Same issue :(

**Comment by antonySee** [comment]
It is already June 15th, and the latest version 2.0.21 still has this problem.
