### ISSUE TITLE
Word wrap in the middle of string constante

### ISSUE THREAD

**Issue by ericjamesbye7** [vuejs/language-tools#4236]
Hello hello
Context : This extension is the only one formatter I have on my VSCode.
Could be great to have only one.

For the following code, when I format (Shift+Alt+F), the string is cut and the build is KO.
```
<span>
    {{ getT("You can also enable or disable this functionality by editing the personal settings on the Users page.") }}
</span>
```
And formatted :
```
<span>
    {{ getT("You can also enable or disable this functionality by editing the personal settings on
                        the Users page.") }}
</span>
```
FYI, the **_getT_** function translate and do several things with the input string.

My settings workspace file contains these options:
```
"html.format.wrapAttributes": "auto",
"html.format.wrapLineLength": 0,

```
Maybe I do something wrong but cutting a constant is not perfect; if you have any idea.
Thx

Regards
EJB

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce the problem. Can you share your full VSCode settings and extension list?

**Comment by ericjamesbye7** [comment]
Hello
I use now another extension: had to hurry for a fast delivery.
Regards
EJB
