### ISSUE TITLE
2.0以上的版本，是不是有性能问题？ 代码提示异常缓慢

### ISSUE THREAD

**Issue by a2734961** [vuejs/language-tools#4239]
回退到1.8.27问题得到解决。

开始我还以为是我的电脑内存不足了！

这问题什么时候能解决啊，都不敢自动更新了！

**Comment by frankie-zeng** [comment]
慢

**Comment by yd-coder** [comment]
+1 看之前关闭的issues说修复了 结果新版本插件还是很慢

**Comment by frankie-zeng** [comment]
要转用webstorm吗

**Comment by so1ve** [comment]
在这抱怨是没有用的，最好能提供一个可以复现性能问题的repo或者提供tsserver的日志。

**Comment by frankie-zeng** [comment]
提供哪些log，ts server的log，vue server log 要么，log开到什么级别，我来提供。

**Comment by frankie-zeng** [comment]
@so1ve 有这么多人出现这个问题，能发给个排除list呢

**Comment by so1ve** [comment]
先打开一个vue文件，然后打开一个ts文件，使用`Typescript: Open tsserver log`指令看看

**Comment by frankie-zeng** [comment]
[tsserver.log](https://github.com/vuejs/language-tools/files/14926949/tsserver.log)
![keil](https://github.com/vuejs/language-tools/assets/43364599/b5a909db-7322-4643-a4d9-1c9f564810cc)
一个log，一个gif

**Comment by yd-coder** [comment]
> +1 看之前关闭的issues说修复了 结果新版本插件还是很慢

更新到最新2.0.11和回退到1.8.27两种都正常了

**Comment by kabutoa** [comment]
确实很卡，体验很差

**Comment by renowan** [comment]
> > +1 看之前关闭的issues说修复了 结果新版本插件还是很慢
> 
> 更新到最新2.0.11和回退到1.8.27两种都正常了

I crash in 2.0.11

**Comment by Ttou** [comment]
碰到一个问题，将 hybridMode 设为 false，重启VSCode，当打开的第一个文件时 ts 不是 vue 时，vue里的代码提示会显示两个，重启 VSCode 后又好了，重启 Vue 和 TS servers 无法解决问题

<img width="680" alt="image" src="https://github.com/vuejs/language-tools/assets/4298437/fddb00df-e4a3-453f-8473-d4bb063e3a58">

**Comment by coding997** [comment]
我的压根就没提示了，法克

**Comment by AnotiaWang** [comment]
今天也遇到了，代码不显示提示，并且有一个 `Code Helper (Plugin)` 进程占满一个 CPU 核心。使用 VS Code 的扩展二等分确认是此插件的问题（并且 VS Code 重载时没法 kill 掉这个插件，导致二等分到最后 CPU 接近占满）

暂时不知道怎么复现

Extension version: 2.0.10
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:28:09.495Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|13, 11, 6|
|Memory (System)|32.00GB (5.51GB free)|
|Process Argv|--crash-reporter-id 33f2db18-d6d2-4571-bcf7-5ce1184f51fc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AnotiaWang** [comment]
我这里似乎不是 Vue Official 的问题，是 UnoCSS 的（详见上方 mention 的来源）

**Comment by guygubaby** [comment]
> 我这里似乎不（完全）是 Vue Official 的问题，也有 UnoCSS 的（详见上方 mention 的来源） 禁用 UnoCSS，启用 Vue Official，启动 VS Code 时也会短暂地占用一定 CPU 和大量内存，但过十几秒后问题消失

UnoCSS 我切回 0.58.9 版本就好很多了，神奇

**Comment by zhougangnb** [comment]
> > 我这里似乎不是（完全）是 Vue 官方的问题，也有 UnoCSS 的（参见上面提到的来源）禁用 UnoCSS，启用 Vue 官方，启动 VS Code 时同时短暂地占用 CPU 和大量内存，但过十几秒后问题消失
> 
> UnoCSS 我切回 0.58.9 版本就好了，神奇

这个方法是管用的

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/unocss/unocss/commit/8e615ab5e4ed6042a4b833425bab879383cab899.

**Comment by sicraf** [comment]
禁用Hybrid模式
