### ISSUE TITLE
The JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by tomi** [vuejs/language-tools#4240]
I am getting the following error with the Vue - Official v2.0.10 extension with the https://github.com/n8n-io/n8n repository

> The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: Vue.volar. Please try disabling these extensions before filing an issue against VS Code.

Tried with:
- `Vue › Server: Hybrid Mode` : `false` --> Still crashes
- `Vue › Server: Hybrid Mode` : `auto` --> Still crashes
- `Vue › Server: Hybrid Mode` : `true` --> Still crashes

VSCode version:

```
Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:09.495Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by Colory** [comment]
> I have the same issue, all extensions disabled except Vue.
> 
> The issue happens on a fresh created vue project
> 
> Plugin version: 2.0.12
> 
> VSCode version: Version: 1.88.0 Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c Date: 2024-04-03T13:28:09.495Z Electron: 28.2.8 ElectronBuildId: 27744544 Chromium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19-electron.0 OS: Darwin arm64 23.4.0

switch hybrid mode to false can help you.
the setting is `vue.server.hybridMode`

**Comment by masawik** [comment]
Installing earlier version (2.0.6) of vue extension fixed it for me

**Comment by cdenadai** [comment]
The only thing that solved for me was use the 1.87v from codium. I can't find Microsoft vscode on older versions for ubuntu.

**Comment by tkane2000** [comment]
I went back to v1.8.27 to fix the issue.

**Comment by johnsoncodehk** [comment]
I can't reproduce the error in https://github.com/n8n-io/n8n. Please try updating to v2.0.12, if it still crashes, you can configure `"vue.server.hybridMode": false` to completely disable the TS plugin (only applicable to >= 2.0.11).

**Comment by EwenQuim** [comment]
Still got this error with the latest versions of VSCode and Vue extension

<img width="459" alt="image" src="https://github.com/vuejs/language-tools/assets/46993939/1b8ae367-ea02-46da-8de2-daacc64ea212">

**Vue**
```
v2.0.12
```

**VSCode**

```
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by vincerubinetti** [comment]
Okay, I'm having this problem, but strangely, only in a React project (I use both Vue and React heavily at my job). In a Vue project, it's fine. 

```
The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: Vue.volar. Please try disabling these extensions before filing an issue against VS Code.
```

Setting `hybridMode` to `false` fixed it for me (in React, TS doesn't crash anymore, and I still have type safety in Vue).
