### ISSUE TITLE
expand selection 功能失效问题

### ISSUE THREAD

**Issue by CaiSijian** [vuejs/language-tools#4247]
vue-official版本2.0.12
vscode版本 1.88.0
出现expand selection（即ctrl+alt+rightArrow快捷键）失效的问题，用不了这个快捷键很难受
bug具体表现为
在vue文件里面快捷键选中异常，与在ts文件中的效果不一致。

**Comment by davidmatter** [comment]
Closing this one due to lack of a minimal reproduction. Feel free to create a new discussion or a new issue if you’re still having problems, thanks!
