### ISSUE TITLE
Vue-Official对.nvue文件支持吗

### ISSUE THREAD

**Issue by m13886695261** [vuejs/language-tools#4251]
我最近使用uniapp在vscode开发 uniapp是有.nvue文件的 我尝试在File.Associations配置*.nvue_____vue但是依然无效
想问问插件支持吗 应该怎么配
 
![aaaaa](https://github.com/vuejs/language-tools/assets/44693057/c4ff41f7-21cd-46b0-8822-a3e6340e53db)

**Comment by so1ve** [comment]
Set `vue.server.additionalExtensions`

**Comment by m13886695261** [comment]
> Set `vue.server.additionalExtensions`

![bbb](https://github.com/vuejs/language-tools/assets/44693057/b785d624-b2f5-49b9-b67d-a606141a1235)
在提问前我已经尝试过了 但还是不行 是我配的有问题吗

**Comment by so1ve** [comment]
只需要一个nvue

**Comment by m13886695261** [comment]
> 只需要一个nvue
还是不行哦 是因为我用了ts吗 我已经试过了重装插件以及重启vscode

![cccc](https://github.com/vuejs/language-tools/assets/44693057/94cd0337-cd2a-4ccc-bb31-e55452c4e9ca)
![dddd](https://github.com/vuejs/language-tools/assets/44693057/a7206c4d-fa8f-49d2-90e5-1f66f1462587)

**Comment by so1ve** [comment]
先去掉associations

**Comment by m13886695261** [comment]
> Member

![1](https://github.com/vuejs/language-tools/assets/44693057/80ddad2e-fc10-42f0-94a6-204a699f3745)
![2](https://github.com/vuejs/language-tools/assets/44693057/b793413a-4b20-4e7b-92e4-ffa7f267678f)
![3](https://github.com/vuejs/language-tools/assets/44693057/68b3fb8d-87ff-4408-943e-cf4f21ade936)

这是我的全部设置 但是还是不行 依旧是重新安装插件以及重启vscode

**Comment by m13886695261** [comment]
@so1ve 还在吗 bro 可以帮我看看吗:)

**Comment by Es-Rell** [comment]
我也遇到了 插件回退到1.+版本可以解决

**Comment by m13886695261** [comment]
> 我也遇到了 插件回退到1.+版本可以解决

只有这个方法吗 不晓得这不是bug啊 总觉得是配置问题
如果是bug我还是希望反馈一下  在下个版本能修复这个问题
不然咱这写uniapp的咋整

**Comment by m13886695261** [comment]
> > 我也遇到了 插件回退到1.+版本可以解决
> 
> 只有这个方法吗 不晓得这不是bug啊 总觉得是配置问题 如果是bug我还是希望反馈一下 在下个版本能修复这个问题 不然咱这写uniapp的咋整

Vue officer回退到v1.8.27 可以解决这个问题 
1.associations添加*.nvue------vue
2.Additional Extensions添加nvue

相同配置v2.0.14有问题 回退v1.8.27就没问题
我看上去像是个bug 希望官方能修复这个问题

**Comment by edwinhuish** [comment]
@m13886695261 市场上已经没有低于 2.0.6 的版本，请问如何回退1.8.27？

**Comment by Es-Rell** [comment]
> @m13886695261 市场上已经没有低于 2.0.6 的版本，请问如何回退1.8.27？

市场上没有，在vscode插件栏点插件设置图标 点选择另一个版本 有1.8.27，但估计下次更新就没有了

**Comment by censujiang** [comment]
现在还是依旧会出现这种问题

**Comment by ZeroPointJi** [comment]
看控制台是 ts-plugin 报的错, 2.X以上默认开启 Hybird Mod , 把这个选项改成 false 并把插件更新到最新版本就可以了

![Image](https://github.com/user-attachments/assets/e7848aad-9b4a-40ed-ad1d-52e0443a1842)

**Comment by cxm19881208** [comment]
> 看控制台是 ts-plugin 报的错, 2.X以上默认开启 Hybird Mod , 把这个选项改成 false 并把插件更新到最新版本就可以了
> 
> ![Image](https://github.com/user-attachments/assets/e7848aad-9b4a-40ed-ad1d-52e0443a1842)

牛逼牛逼。有效。
虽然感觉关了这个不是太好，没其它办法了。

**Comment by imluyu** [comment]
1. 我是看了 #4321，修改了tsconfig.json

<img width="553" height="240" alt="Image" src="https://github.com/user-attachments/assets/0ff8bc3f-1d34-479c-bb18-041a5950bfa8" />

2. 然后在vue.server 修改配置增加 include languages 增加一个nvue。

<img width="684" height="258" alt="Image" src="https://github.com/user-attachments/assets/0ed57d6a-bfd6-4b13-b051-ddb5613e2d56" />

3. 然后在files.associations增加 *.nvue------vue

<img width="978" height="341" alt="Image" src="https://github.com/user-attachments/assets/77790459-2c44-4444-b691-f97af816be68" />
