### ISSUE TITLE
 Error: ENOENT: no such file or directory, stat '/Users/a/Downloads/nuxt/node_modules/typescript/lib/typescript.js'

### ISSUE THREAD

**Issue by phpmac** [vuejs/language-tools#4252]
Error: ENOENT: no such file or directory, stat '/Users/a/Downloads/nuxt/node_modules/typescript/lib/typescript.js'

**Comment by so1ve** [comment]
Where does this error from?

**Comment by davidmatter** [comment]
Closing this one due to inactivity. Feel free to create a new issue if you're still having issues with the latest version, thanks!
