### ISSUE TITLE
F2 重命名问题

### ISSUE THREAD

**Issue by yulin96** [vuejs/language-tools#4257]
当我使用f2重命名inject注入的值时会出现错误（可能存在概率性）

当出现错误时，也会导致页面其他变量的重命名出现错误
![Recording 2024-04-12 at 11 01 45](https://github.com/vuejs/language-tools/assets/40719410/88b462fc-378f-4668-970b-28b1c79789e9)

代码：
[f2-error.zip](https://github.com/vuejs/language-tools/files/14953507/f2-error.zip)

Vue - Official v2.0.12

版本: 1.88.1 (user setup)
提交: e170252f762678dec6ca2cc69aba1570769a5d39
日期: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22635

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/f0aad5d7d0e86e414a602c1afe84dcf9eb5ac78b
