### ISSUE TITLE
vueCompilerOptions.strictTemplates option dosen't seem to work in TSX

### ISSUE THREAD

**Issue by ltxhhz** [vuejs/language-tools#4258]
I had restart vue and ts servers.

![image](https://github.com/vuejs/language-tools/assets/51697596/c6f5b4b6-653c-47ce-b093-6fabf8fae112)

dependencies
![image](https://github.com/vuejs/language-tools/assets/51697596/d4b20211-10c4-4a1b-89fe-3f6e27bae585)

While it is possible to eliminate the reporting of errors by using the method of modifying the d.ts file in #1077, this does not make sense.

**Comment by so1ve** [comment]
This is the TypeScript behavior, we cannot change it.

**Comment by ltxhhz** [comment]
> This is the TypeScript behavior, we cannot change it.

got it🙏

**Comment by mazhewei** [comment]
Same issue.
