### ISSUE TITLE
Slow autocomplete

### ISSUE THREAD

**Issue by onurusluca** [vuejs/language-tools#4264]
https://github.com/vuejs/language-tools/assets/51825926/3c26dd66-cab8-41d4-83b8-23a08e83e29d

Autocomplete used to appear instantly. Now it take 2~3 seconds sometimes more. I haven't changed anything or did any customizations. 
Happens on all versions from the lates v2.0.12 to 1.8.27
Mostly happens with template only, script is fine, css is a bit slow but normal I guess.

**Comment by ephemeral108** [comment]
try to disable prettier extension, it worked for me.

**Comment by onurusluca** [comment]
This was resolved with v2.0.14 update in my machine.

**Comment by davidmatter** [comment]
Is this one still an issue with the latest 2.x?

**Comment by Flashantik** [comment]
> Is this one still an issue with the latest 2.x?
Yes! And it is a big problem..
We have a large project (with nuxt, ~4k components), autocomplete is terrible everywhere, both script and template


https://github.com/user-attachments/assets/5f55ee2f-0d16-43e2-b613-8340b3dce6e8

macOS m1 Sonoma 14.1, VSC Version: 1.92.0.

list of extensions 
- vue.volar@2.0.28
- skyboost.nuxt-3-goto@0.0.2
- dbaeumer.vscode-eslint@3.0.10
- csstools.postcss@1.0.9
- cpylua.language-postcss@1.1.0
- bradlc.vscode-tailwindcss@0.12.6

**Comment by onurusluca** [comment]
Seems to be resolved. Closing.
