### ISSUE TITLE
Vue official crashes every time

### ISSUE THREAD

**Issue by cesargmzdev** [vuejs/language-tools#4266]
Extension continuously crashes and auto restarts, with no intellisense and autocompletions

**Comment by minyoung90** [comment]
mee too

**Comment by yuantongkang** [comment]
me too

**Comment by anle1222** [comment]
me too

**Comment by bosens-China** [comment]
me too

**Comment by abarke** [comment]
me too Vue - Official v2.0.10 - language server keeps restarting

**Comment by codymikol** [comment]
Can any of you give more information / logs / configuration / editor ?

**Comment by abarke** [comment]
Here are the logs with a few things stripped out: [ts-server-logs.zip](https://github.com/vuejs/language-tools/files/15164824/ts-server-logs.zip)

I solved the problem in the mean time by simply cloning the project into a new folder. Now everything works.

**Comment by davidmatter** [comment]
I assume these issues have been stabilized in the latest 2.x versions. If you're still encountering problems, please create a new issue. Best case: Provide an example project that we can look into, thanks!
