### ISSUE TITLE
Downloading Vue-Official failed, as did installing other versions of Vue-Official using vsix

### ISSUE THREAD

**Issue by zkf990305** [vuejs/language-tools#4268]
Hello dear @johnsoncodehk and team!

`I had a problem with Visual Studio Code. When installing the Vue-Official plug-in, a message is displayed indicating that the plug-in is incompatible with the code version.`

## Problem screenshot

![Snipaste_2024-04-15_11-28-23](https://github.com/vuejs/language-tools/assets/61091575/ffde768c-aa47-4b1a-a5dd-dda11c23007d)

![image](https://github.com/vuejs/language-tools/assets/61091575/ede8cd15-c358-4b35-8647-5a2ade757dee)

## Environment Information
* Operating System:  Windows 10 
* Visual Studio Code Version: 1.81.1
  版本: 1.81.1 (user setup)
  提交: 6c3e3dba23e8fadc360aed75ce363ba185c49794
  日期: 2023-08-09T22:22:42.175Z
  Electron: 22.3.18
  ElectronBuildId: 22689846
  Chromium: 108.0.5359.215
  Node.js: 16.17.1
  V8: 10.8.168.25-electron.0
  OS: Windows_NT x64 10.0.22631
* Vue - Official Plugin Version: 2.0.12

Tried to reinstall Visual Studio Code. I tried searching online resources but did not find a solution.

**Comment by Tingfenghhh** [comment]
应该是你VScode版本太低了
