### ISSUE TITLE
Rename Symbol functionality is broken (in some cases)

### ISSUE THREAD

**Issue by ffxsam** [vuejs/language-tools#4281]
This only occurs in .vue files, as far as I can tell.

In most cases, when I hit F2, it works as expected:

![CleanShot 2024-04-19 at 19 12 39](https://github.com/vuejs/language-tools/assets/12532733/21db1493-8666-48d2-b68a-855e4d0b315d)

But on some symbols, this pops up when I hit F2:

![CleanShot 2024-04-19 at 19 12 47](https://github.com/vuejs/language-tools/assets/12532733/a281ec0b-30c4-4bc7-8b13-e8ac46c4a2f1)

I'm on the latest version, v2.0.12.

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/f0aad5d7d0e86e414a602c1afe84dcf9eb5ac78b

**Comment by ffxsam** [comment]
@johnsoncodehk Thank you!!
