### ISSUE TITLE
Visual Studio Code - vue.volar extension - JS/TS language service cannot be started successfully

### ISSUE THREAD

**Issue by nico-sth** [vuejs/language-tools#4285]
When loading/opening a non-Vue project (e.g. NextJS [React]) with the Visual Studio Code `vue.volar` extension installed (v2.0.10+) I get the following error message:

![Screenshot 2024-04-22 at 10 09 05](https://github.com/vuejs/language-tools/assets/142964844/5fadebf3-1805-4f4b-a895-aeff86271b1d)

Downgrading `vue.volar` to v2.0.6 or disabling the extension altogether fixes this issue. Loading a Vue project (e.g. Nuxt) does not experience this issue.

**Comment by abarke** [comment]
Still an issue in v2.0.14

This problem is really effecting DX... no type completion and refactoring of types is really bad. Productivity down 80%.

**Comment by davidmatter** [comment]
Closing this one as many things have changed in the latest 2.x versions. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!
