### ISSUE TITLE
2.0以后的版本都无法使用nvue开发

### ISSUE THREAD

**Issue by Es-Rell** [vuejs/language-tools#4287]
尝试配置过`files.associations`
以及![image](https://github.com/vuejs/language-tools/assets/29221830/5abdb3b0-f31b-402d-83d0-a4ceb3fd5da1)
均无法识别爆红
目前只能回退插件到1.87版本

**Comment by m13886695261** [comment]
有关于nvue问题 看上去是个bug 希望官方能修复一下
https://github.com/vuejs/language-tools/issues/4251

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4251

**Comment by Es-Rell** [comment]
> Duplicate of #4251

相同的问题并没有解决啊
