### ISSUE TITLE
v2.0.11 and later, In typescript files, importing .vue files yields "Cannot find module" error

### ISSUE THREAD

**Issue by michaeldaw** [vuejs/language-tools#4288]
In v2.0.11 and later, any typescript file that attempts to import a .vue file results in the error message in the following screenshot:
`Cannot find module <module> or it's corresponding type declarations`

The most obvious case of this happening is in the main.ts when attempting to import App.vue in a default project. However, it happens in any .ts file.

Reverting back to 2.0.10 fixes the issue. The error starts occurring in 2.0.11.
<img width="680" alt="image" src="https://github.com/vuejs/language-tools/assets/8949148/315c4fe9-d86a-4864-8211-b4a83c4dd61a">

**Comment by johnsoncodehk** [comment]
When opening a Vue project file in a new VSCode window, do you see the following message?
<img width="495" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/19287d5d-f861-42aa-86e1-e043ac812eb3">

**Comment by michaeldaw** [comment]
No, not  that I can see.

**Comment by johnsoncodehk** [comment]
Can you share a screenshot from here?
<img width="535" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/72899bbc-e4f8-4614-9d49-8dab5c8545b3">

**Comment by michaeldaw** [comment]
It looks like the problem with the "Hybrid Mode" setting. It was set to False. When I set it to true, the errors were no longer occurring.
I'm going to close the issue. Thanks for taking the time to look into it. I'll keep this setting in mind if I see errors like this in the future.

**Comment by johnsoncodehk** [comment]
You can also revert it to the default "auto" to avoid compatibility issues. (See #4206)

**Comment by ypresto** [comment]
@johnsoncodehk Is this the limitation of Hybrid Mode? If so, it would be helpful if that is explicitly stated in README.

**Comment by so1ve** [comment]
@ypresto When you met this issue could you please show the panel?

![image](https://github.com/vuejs/language-tools/assets/58381667/c5753ffa-056c-41a1-85c9-2721ed343080)

I suppose this was caused by typescript not being loaded correctly in vue files and often there is no typescript version information in the panel.

**Comment by ypresto** [comment]
@so1ve 

The problem occurs when editing .ts file (not .vue file). So the panel shows TypeScript information only.
<img width="344" alt="image" src="https://github.com/vuejs/language-tools/assets/400558/8e3d4c7d-8174-4a68-a872-ac6682a17ade">

When editing .vue file, it looks correctly loaded.
<img width="314" alt="image" src="https://github.com/vuejs/language-tools/assets/400558/a54d8540-d02f-4fb3-b3c7-94d401b7eb2d">
