### ISSUE TITLE
syntax highlighting is wrong

### ISSUE THREAD

**Issue by a1mersnow** [vuejs/language-tools#4289]
```
<input
  id="one-time-code"
  v-model.trim="form.code"
  autocomplete="one-time-code"
  inputmode="numeric"
  placeholder="请输入验证码"
  class="flex-1 pr-0.75rem"
  placeholder-style="color:#E8E8E8"
  :maxlength="6"
>
```
This is what it looks like in vscode:
<img width="466" alt="image" src="https://github.com/vuejs/language-tools/assets/13799160/79873ec8-32fe-4558-bdb3-562ea61457cc">

look at the `inputmode` section

**Comment by cvpv** [comment]
i alse get this problem

**Comment by davidmatter** [comment]
Verified that this one is not an issue anymore. If you're still encountering issues, please create a new one with more information about your setup/project.
