### ISSUE TITLE
Incorrect type narrowing in closures

### ISSUE THREAD

**Issue by MellKam** [vuejs/language-tools#4293]
The type narrowing seems to be incorrect. In this example it should be the same type as the variable originally has, but for some reason it has `null`. (I have the latest version lsp extension and the latest version of vscode installed)
![image](https://github.com/vuejs/language-tools/assets/51422045/816646e0-2e92-4193-a987-085f3881852b)

A bit different, but still incorrect [reproduction in playground](https://play.vuejs.org/#eNp9Uktu2zAQvcqUG9uAa6FoV65koC0MtEV/aFJ0w40qjRQmFEmQQ1eBokvkAgFywhwhIwpOsgiy0GfmveG8N8NBfHBuc4gotiIPlVeOQJemLaSgIAUEpOh20qjOWU8wgMcGRmi87WDBZQtppNFI0G8hkFemhSswUWso0uf9hJd1vT+goW8qEBr0SykqraoLKdawXEGxg0EaANXAki4d2gZ6KIoCpJiPlGLFfSl6w8cBg1nGr+9/Tk7hH87d7m6ub4+PNONqaltZEwi60LIWlr1cfEatLfy1XtevFkzJs9kx++OAsHO6JOQIID97sxuGVDyOecZRyirjIsHhdWdr1DwjxnlIGYN59qRerHl63L5R7eY8WMPDTQ7Zt+2c0uh/OlIsT4rt7H3CSlb3/2vKkY+4PuarM6wunsmfh37KSfHLY0B/QJ7nEaPSt0gzvD/5gT3/P4CsPmpmvwD+xmB1nDTOtI/R1Cz7CS+p/ZKuBa/oNOx73m04mpqETswx8aXgq/LpBeuPct9u3qU6XqIY7wEjhuD/)

![image](https://github.com/vuejs/language-tools/assets/51422045/84c7305e-cd6f-4c6e-9ca0-612203bd943d)

**Comment by so1ve** [comment]
I can't reproduce this issue on my machine, could you please provide a full repro repository?

**Comment by MellKam** [comment]
@so1ve You can check the vue playground link. I will try to make a repo with reproduction today

**Comment by so1ve** [comment]
The type is still incorrect after I disabled the Vue extension 🤔

**Comment by MellKam** [comment]
@so1ve Yeah, it seems that this result is correct from the point of view of typescript. It was a big discovery for me. I even found how to abuse this "inference". 

```ts
let x: string | null = null;

const setX = () => x = "foo";

setX();

typeof x;
//     ^? let x: null
```

With the latest version of vscode extension, types seem to be the same as in .ts files, but the vue playground still shows wrong results. Like this one: 
![image](https://github.com/vuejs/language-tools/assets/51422045/8c1c5038-2c1e-4046-ab30-88cb3585e6eb)

[vue playground](https://play.vuejs.org/#eNqNU01v2zAM/SuETklRxIftlCUZtiADOmQfWLebMcB1GEetTAkSlbrr8t9H2siQoB1WG7At8fG9R1J+NO9CmOwzmqmZpTrawOAqaual4VQaSMg5LEpyyNBNIXG01MBvoOwczPvXm5JKGo3GMF/Ao3wzPwT0W+g0wEUBev18W9JhPBr34NpTYniQ/JdkacY2U83WE/ySjP/BZ8VQiNiWBWMbXMWoK55t7H4xK/SpuJOYuZSCxdjWNpPb5En6IToApal9G6zD+CWoA2nKVB2onvSoig2ybpVmdf0ZO/m+VCG5Tes32eE/gunOhrW9We6wvlMIx4wa7MPFBbzPtBFREBKEi+Kc8xsm77LaGdhvBvAJfeWcv79qg48sA/ueVh0jpaP/o1gPjUq2x49S9Ke/js8QVgDSpc0QfspAftXavgtn27epG+wFkcC4F+LTCteW1NtJcXq66qc85H9QTrhZ+7pyz6kP4a9VrFpkjM9BPkhDeBd9bnbLKmG6out7y/XuCNWBHgSvQ5W/Yfmimb+avO7z5NSZwx8M/yRV)

**Comment by KermanX** [comment]
> With the latest version of vscode extension, types seem to be the same as in .ts files, but the vue playground still shows wrong results. Like this one:

This is because [`compilerOptions.strictNullChecks`](https://www.typescriptlang.org/tsconfig/#strictNullChecks) is off in Vue playground. Not a Vue issue.

**Comment by MellKam** [comment]
@KermanX Thanks for explaination ❤️
