### ISSUE TITLE
代码提示错误覆盖结束括号

### ISSUE THREAD

**Issue by llk2yq** [vuejs/language-tools#4295]
很抱歉不能用英文来提问题，因为问题有点奇怪（不确定是否是这个插件的问题还是vscode的问题）：

首先输入一个`div`（或者是其它任意标签）:
![image](https://github.com/vuejs/language-tools/assets/22813922/59557255-ec7e-42c3-820e-fd4d4058b260)

然后尝试给这个div设置一个`class`:
![image](https://github.com/vuejs/language-tools/assets/22813922/9517ac2c-c503-4506-9519-5e16c4b99f0f)

这时候会出现代码提示如上图，如果在代码提示出现的时候就 **快速** 地按回车，
预期结果：
![image](https://github.com/vuejs/language-tools/assets/22813922/6a757a4c-8c0c-433e-ab0e-f4095639cb18)
实际结果（删掉或者说覆盖掉了一个`>`）：
![image](https://github.com/vuejs/language-tools/assets/22813922/d0234b20-0a96-46d1-ac37-e7fec96052a3)

经过多次测试，我发现当代码提示出现时，**立即**按回车，则很容易复现。相反，当代码提示出现时，**过几秒**再按回车，则出现这个问题的概率就小得多。
另外，此问题仅出现在`.vue`文件中，`.html`文件中不管是否启用本插件，都不会出现此问题。

环境：vscode 1.88.1   插件只装了两个，分别是中文插件，以及当前插件。

**Comment by wlonghaha** [comment]
me too

**Comment by Shyam-Chen** [comment]
時好時壞

**Comment by cvpv** [comment]
I haven't encountered this issue

**Comment by yulin96** [comment]
windows下 我也遇到了这个问题

**Comment by liweiook** [comment]
me too

**Comment by shell-well** [comment]
This problem happens all the time, and it always eats a character in the back.

**Comment by yulin96** [comment]
我几乎每天都会遇到此问题，越大型的项目遇到的情况越多，并且似乎只在windows下发生。
I run into this problem almost every day, more often with larger projects, and it only seems to happen on Windows.
![Recording 2024-07-18 at 10 45 49](https://github.com/user-attachments/assets/30456831-2856-49f4-9142-8255c166fbe2)

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: Please let us know if you're still encountering this issue. Otherwise kindly close this one, thanks!
