### ISSUE TITLE
The effect of renaming variables in ``<template>`` is unpredictable

### ISSUE THREAD

**Issue by KazariEX** [vuejs/language-tools#4297]
仅限 Hybrid Mode 模式。

1\. 所有直接来自 ``<script>`` 的变量，均无法在光标位于起始位置时重命名；在其余位置的重命名不会产生任何效果。

![image](https://github.com/vuejs/language-tools/assets/85992002/cf075bf2-c92b-4ad5-bf29-147a884dbcdd)

![image](https://github.com/vuejs/language-tools/assets/85992002/797c1588-b85d-4a6a-b68a-3739efaff590)

2\. 在 ``v-if`` 中，从变量的第 2 个字符开始，到 ``v-if`` 所在元素的标签名长度个字符后的位置对变量重命名，它将对所有该标签名的元素进行重命名，并原地打开 runtime-dom.d.ts 篡改类型定义；而在上述字符范围外的重命名不会产生任何效果。

> 在 ``v-for`` 中则是从被遍历对象的倒数第 5 个字符开始，到标签名长度 +2 个字符后的位置

![image](https://github.com/vuejs/language-tools/assets/85992002/88f0b811-464f-4139-bde9-4f72a3026f97)

![image](https://github.com/vuejs/language-tools/assets/85992002/64b93697-8b06-49cf-bfdc-791adfb9a8eb)

![image](https://github.com/vuejs/language-tools/assets/85992002/23f96bae-bc65-429d-9388-7d7e1dfce9f5)

3\. 在 ``v-for`` 中，从索引变量的最后一个字符往前推移 12 个字符，到被遍历对象的变量名长度个字符后的位置，如果范围内存在变量，则此时的重命名将对被遍历对象本身生效，除此之外在其余位置的重命名不会产生任何效果。

![image](https://github.com/vuejs/language-tools/assets/85992002/31d445b8-9d40-4ab6-9670-27db2e1871e2)

![image](https://github.com/vuejs/language-tools/assets/85992002/5cd0e921-8ff7-492b-a0e3-8c5a116819b2)

![image](https://github.com/vuejs/language-tools/assets/85992002/9549352f-d14b-4299-8346-2090afaa2de6)

**Comment by johnsoncodehk** [comment]
> 1. 所有直接来自 `<script>` 的变量，均无法在光标位于起始位置时重命名

我只能復現這個問題，其他復現不了。你能提供重現嗎？

**Comment by KazariEX** [comment]
https://github.com/KazariEX/vue-rename-demo

我禁用了除 Vue - Offical 外的所有插件，并重新安装了依赖，问题依然生效

另外我想知道 vue playground 是基于什么方式实现的，在上面并不能复现包括这个 issue 在内的很多问题

**Comment by johnsoncodehk** [comment]
我復現那個問題由 https://github.com/volarjs/volar.js/commit/803c2b34539f6f2f86f27a95425174b588fafa8c 解決了。

其他問題我還是復現不了，有可能你本地安裝了衝突的 TS plugin 插件，你用 GitHub Codespaces 打開 https://github.com/KazariEX/vue-rename-demo 可以復現嗎？

**Comment by KazariEX** [comment]
GitHub Codespaces 无法复现，但是我本地测试时禁用了其他插件，应该不会有影响才是。目前只能选择先关闭 Hybrid Mode

**Comment by johnsoncodehk** [comment]
你能讓我遠程看嗎？可以的話請在 https://discord.gg/vue 的 #language-tools channel ping 我。

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/233cb15e32f837286e683c5ad86fd8bc9ec2d66d.
