### ISSUE TITLE
Significant performance impact in VSCode

### ISSUE THREAD

**Issue by itpropro** [vuejs/language-tools#4298]
If this issue is already be worked on and tracked in #3531 or #3801 feel free to close this.
I experience a huge downgrade in VSCode performance caused by the vue language-tools. This applies to the insider version 2.0.14 as well as to the 2.0.11.
For this test I disabled every other extension in VSCode and even started with a completely new isolated instance of VSCode, but as soon as the language-tools are enabled, the performance impact is clearly visible.
### Enabled language-tools:
![Enabled](https://github.com/vuejs/language-tools/assets/15030951/f0904215-bb90-4e41-b509-6cc9d49a606d)

### Disabled language-tools:
![Disabled](https://github.com/vuejs/language-tools/assets/15030951/33a393df-f451-492a-8d80-50912b5fc83e)

This can be reproduced with every vue project, by opening it in VSCode and disabling every extension except the vue language-tools. The impact in probably different by the size of the project, but always significant.

OS: Windows 11 23H2 (22631.3447)
VSCode: 1.88.1

**Comment by johnsoncodehk** [comment]
Thanks for the clarification. The problem is that emmet completion should not be affected by TS performance, fixed by https://github.com/microsoft/vscode-html-languageservice/pull/187, https://github.com/vuejs/language-tools/commit/65d38a18081e66f04ff56547997adbaaeaf40a79.
