### ISSUE TITLE
Windows 平台卡顿，WSL2良好，希望官方定位问题

### ISSUE THREAD

**Issue by rtpacks** [vuejs/language-tools#4306]
你好，今天测试2.0.10、2.0.12 和 2.0.14三个版本，在 Windows 平台上提示信息都是卡顿的，同样的版本在WSL运行良好，Props、Script提示都很快。我需要提供什么信息才能帮助解决这个问题呢？

**设备信息**
> 处理器	12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
> 机带 RAM	40.0 GB (39.7 GB 可用)
> 版本	Windows 11 专业版
> 版本	23H2
> 安装日期	‎2023/‎2/‎13
> 操作系统版本	22631.3447

**vscode**
> 版本: 1.88.0 (system setup)
> 提交: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
> 日期: 2024-04-03T13:26:18.741Z
> Electron: 28.2.8
> ElectronBuildId: 27744544
> Chromium: 120.0.6099.291
> Node.js: 18.18.2
> V8: 12.0.267.19-electron.0
> OS: Windows_NT x64 10.0.22631

**Comment by wlonghaha** [comment]
好像说是vscode问题,估计不会解决

**Comment by wlonghaha** [comment]
https://github.com/vuejs/language-tools/issues/4227#issuecomment-2058199605

**Comment by sicraf** [comment]
> [#4227 (comment)](https://github.com/vuejs/language-tools/issues/4227#issuecomment-2058199605)

看了这个，我果断禁用了Hybrid模式，不使用tsserver来接管语言支持，卡顿啥的都没了，太丝滑了

**Comment by rtpacks** [comment]
> > [#4227 (comment)](https://github.com/vuejs/language-tools/issues/4227#issuecomment-2058199605)
> 
> 看了这个，我果断禁用了Hybrid模式，不使用tsserver来接管语言支持，卡顿啥的都没了，太丝滑了

@sicraf  你好，可以看一下你的配置文件吗？我禁用 HybridMode 后提示还是卡顿

**Comment by rtpacks** [comment]
> [#4227 (comment)](https://github.com/vuejs/language-tools/issues/4227#issuecomment-2058199605)

@wlonghaha 翻了一下，确实太奇怪。在 vscode + wsl2 上体验很好，Windows 本机不行

**Comment by sicraf** [comment]
> > > [#4227 (comment)](https://github.com/vuejs/language-tools/issues/4227#issuecomment-2058199605)
> > 
> > 
> > 看了这个，我果断禁用了Hybrid模式，不使用tsserver来接管语言支持，卡顿啥的都没了，太丝滑了
> 
> @sicraf 你好，可以看一下你的配置文件吗？我禁用 HybridMode 后提示还是卡顿

![image](https://github.com/vuejs/language-tools/assets/21838694/98dfe3df-e6cb-499a-a7fc-638f2404e6e0)

**Comment by johnsoncodehk** [comment]
@rtpacks 你可以在其他項目中復現問題嗎？例如：

- https://github.com/johnsoncodehk/volar-starter
- https://github.com/elk-zone/elk

**Comment by rtpacks** [comment]
@johnsoncodehk  


没有精准的统计时间，大概测试结果：

|                                | Windows11（Hybrid） | Windows11 | WSL2（Hybrid） | WSL2 |
| ------------------------------ | :-----------------: | --------- | -------------- | ---- |
| volta-starter                  |        极快         | 极快      | 极快           | 极快 |
| volta-starter（1k HelloWorld） |        >10s         | ~3s       | >10s           | ~3s  |

文件大小影响极大。代码接近 1k 行时，`(win | wsl) & (Hybrid:enable | Hybrid:disable)`，组件 Props 的提示都很慢。

![2024-04-27 111752](https://github.com/vuejs/language-tools/assets/97966585/1f052a71-8015-4aa5-a2cf-21b03d50247d)

**Comment by rtpacks** [comment]
The performance has improved a lot recently, thank you to the  language-tools project team.

**Comment by davidmatter** [comment]
Don't forget to rate the vscode extension https://marketplace.visualstudio.com/items?itemName=Vue.volar
