### ISSUE TITLE
Visual studio code: Hinting javascript / objects / methods doesnt work in Vue language with this Tools

### ISSUE THREAD

**Issue by Kcko** [vuejs/language-tools#4308]
Hi dear developers,

Only with this official and recommended extension, it doesn't work to suggest native JS generalities in Vue.js (language Vue)

Here are 2 short videos that demonstrate this:

This works, but I have to have Vetur installed in addition to the Vue official add-on (which is a bit weird)

-> https://bit.ly/4aMiJY2

And if I have Vetur disabled, it doesn't whisper anything from the JS.

Is this a bug or a setting?

With enabled Vetur im getting this error message -> https://bit.ly/3JDgaf8  but only this solution (Vue official + Vetur) will do what it should do - suggests javascript in Vue language

Its a little bit annoying.

Could you help me anybody?

**Comment by johnsoncodehk** [comment]
You should not enable Vetur. The issue appears to be OS related, we need to remote to your device in order to investigate the issue, if you can assist us with remote please ping me in the #language-tools channel of the [Vue Land](https://discord.gg/vue) Discord Server.

**Comment by riderx** [comment]
Did you tried to bisect?
https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
I had the same issue once, and it was an unrelated extension who was breaking.

**Comment by Kcko** [comment]
I'll try the live remote first, since it was so kindly offered, and I'll definitely check out Bisect, thanks a lot.

**Comment by riderx** [comment]
bisect takes literally 20 sec, if I could save time of someone I would do that first, to respect their time :)

**Comment by Kcko** [comment]
I wanted to see how a real professional works/debugs.
But OK I'm going to give it a try

**Comment by Kcko** [comment]
Its showed me some extension that doesn't affect it, good try but unsuccessful.

**Comment by riderx** [comment]
Thanks to have tried !

**Comment by Kcko** [comment]
Thank you very much indeed for your quick help, it was interesting to watch the professional debug and I also apologize for the lost time, but I don't remember explicitly turning it on myself.

Thanks again. 👍
