### ISSUE TITLE
v2.0.14版本没有<style>标签代码提示

### ISSUE THREAD

**Issue by 97128785** [vuejs/language-tools#4309]
![image](https://github.com/vuejs/language-tools/assets/55985719/ed70eb1f-7f90-4ef9-9a17-1f1d17f1027f)
如图，无法在.vue文件中使用emmet书写css样式

**Comment by q77763429** [comment]
我也遇到这个问题了，不知道怎么解决，现在是和Vetur插件换着用，太痛苦了

**Comment by 97128785** [comment]
> 我也遇到这个问题了，不知道怎么解决，现在是和Vetur插件换着用，太痛苦了

回退到1.8.27应该可行

**Comment by q77763429** [comment]
> > 我也遇到这个问题了，不知道怎么解决，现在是和Vetur插件换着用，太痛苦了
> 
> 回退到1.8.27应该可行

我用的是Stylus，好像所有版本对这个都不支持，其他的CSS 预处理语言都没问题，也不知道为什么不支持

**Comment by Biswangluo** [comment]
同样问题 这个官方插件怎么这么多bug 真是快服了

**Comment by yeyuqh** [comment]
> 同样问题 这个官方插件怎么这么多bug 真是快服了

没有提示应该是 Hybrid Mode 的问题，一些老项目开了这个以后完全没有提示，新项目没有这个问题。

**Comment by KermanX** [comment]
非常抱歉带来了不便。请提供尽可能小的可以复现bug的项目以供修复，非常感谢！
