### ISSUE TITLE
Missing `css` class references

### ISSUE THREAD

**Issue by Ilanaya** [vuejs/language-tools#4311]
[Reproduction repo](https://github.com/Ilanaya/volar-starter)

**Reproduction steps:**
1. Open repo
2. Open `*.vue` file

**Actual Result:** no class references in `style` block

![image](https://github.com/vuejs/language-tools/assets/74474615/3118622a-56ea-4aa1-bb2b-052d54a05da8)

Some investigation info:
1. `experimentalResolveStyleCssClasses` setting doesn't change anything
2. `result` [provideReferencesCodeLensRanges](https://github.com/vuejs/language-tools/blob/master/packages/language-service/lib/plugins/vue-codelens-references.ts#L10-L34) is always empty array. Probably codeLens ranges are calculated incorrectly or `__referencesCodeLens` wasn't set properly.

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/3986
