### ISSUE TITLE
There seems to be an issue with the type reference check for template and script (v2.0.10)

### ISSUE THREAD

**Issue by qq326943819** [vuejs/language-tools#4317]
When I perform reference checks on imported components in the template, I am unable to find the corresponding import statements in the script, which seemed feasible in previous versions (I have an impression). As follows:

![1](https://github.com/vuejs/language-tools/assets/32457006/037a8e8c-1682-4e4f-a2a1-3caa5190caa6)
![2](https://github.com/vuejs/language-tools/assets/32457006/fe9d3b6d-4263-437b-ab41-9e3a836bf0bd)
![image](https://github.com/vuejs/language-tools/assets/32457006/8a89147e-cad8-4c53-9486-89fd15b0ca18)

At the same time, a reference check was performed on the imported statement, and the search results did not match expectations:

![image](https://github.com/vuejs/language-tools/assets/32457006/206bae6c-88c6-4a34-a934-65f2a58ff4f1)

Matched some irrelevant content, and the component that should have been matched was called but not correctly found.

**Comment by johnsoncodehk** [comment]
This is a bug in <= 2.0.12, please update to 2.0.14.
