### ISSUE TITLE
Vue - official extension makes saving slow

### ISSUE THREAD

**Issue by saurabhjadhav45** [vuejs/language-tools#4318]
Type: <b>Bug</b>

Vue - official extension makes saving code in Visual Studio Code slow

Extension version: 2.0.8
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.73GB free)|
|Process Argv|--crash-reporter-id 52866b0d-3d57-4a7c-b18d-dc925c96b9f0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfnew:31000557
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31022790

```

</details>

**Comment by julianpung** [comment]
Can confirm.
It used to be fast with the Typescript Vue Plugin, but has been incredibly slow since the latest changes.

**Comment by Mehdi-Hp** [comment]
I have the same issue. VSCode's formatter goes crazy when Vue extension is active and this icon keeps shaking.
  
![CleanShot 2024-05-04 at 00 26 14@2x](https://github.com/vuejs/language-tools/assets/8641684/0d04f395-52c4-4a94-8282-11b808a0fa66)

I restart extensions host to temporarily fix it

**Comment by Mehdi-Hp** [comment]
Setting hybrid mode to this fixes it for me.

`"vue.server.hybridMode": "typeScriptPluginOnly"`

**Comment by nonafox** [comment]
> Setting hybrid mode to this fixes it for me.
> 
> `"vue.server.hybridMode": "typeScriptPluginOnly"`

Works to me too. Takes me 3hrs to find this out. Big thanks!

**Comment by davidmatter** [comment]
Is this one still an issue in the latest 2.x?
