### ISSUE TITLE
v2.0.14: Command "Write Virtual Files" does nothing

### ISSUE THREAD

**Issue by StefanFeederle** [vuejs/language-tools#4319]
Command "Vue (Debug): Write Virtual Files" does nothing.
There are no files created, no error message displayed and no console outout from Vue Language Server or TSServer.
Who can I debug this? Thanks!

OS: Win11 23H2 Bild 22631.3447
VSCODE: 1.88.1
Extension: Vue - Official v2.0.14
Typescript: 5.4.5 (Workspace)

**Comment by johnsoncodehk** [comment]
You must disable Hybrid Mode to use the write virtual files command, I will add a message box for this.

**Comment by StefanFeederle** [comment]
Awesome, it's working without hybrid mode. Thanks for the quick reply
