### ISSUE TITLE
Hybrid mode auto complete in template tag not working in neovim

### ISSUE THREAD

**Issue by RayGuo-ergou** [vuejs/language-tools#4323]
Hi, I am running hybrid mode with `2.0.14`. In template tag auto complete a variable does not work unless it was used in template tag before in neovim, but it works fine in vscode I am wondering any communication miss between `tsserver` and `vue-language-server`?

Here's better explain of the problem:

If i create a new ref and then try to use in template tag, I cannot see it in auto complete:
![image](https://github.com/vuejs/language-tools/assets/33137074/438a1576-32c5-4436-9635-781ed2223798)

However if I try to use it the second time, I got the auto completion working.

![image](https://github.com/vuejs/language-tools/assets/33137074/5baf9214-cce8-4314-8523-69c11ed2e392)

![GIF 4-29-2024 8-55-45 PM](https://github.com/vuejs/language-tools/assets/33137074/ea58e9ba-b275-4953-8028-b692205391a7)

**Comment by johnsoncodehk** [comment]
> but it works fine in vscode

I'm successfully reproducing it in VSCode and it seems to be an issue with `@vue/typescript-plugin`.
