### ISSUE TITLE
Vue Extension not watching file system for new/moved files

### ISSUE THREAD

**Issue by itamar3429** [vuejs/language-tools#4331]
When creating a new file, it's not being added to the workspace as a file,
when importing the file, it gives an error and doesn't show the file as a valid file (although it gives the file as an snippet option).
The same thing happens for moved files, the new file name doesn't seem to be acceptable for imports.

In the file itself, ts doesn't allow using path aliases.

# in the file itself
<img width="681" alt="Screenshot 2024-05-01 at 10 55 22 AM" src="https://github.com/vuejs/language-tools/assets/51875816/adf190f0-44dc-47e5-9b5b-f7c86f44b849">

# importing the file
<img width="244" alt="Screenshot 2024-05-01 at 11 00 10 AM" src="https://github.com/vuejs/language-tools/assets/51875816/08937df1-f9dc-405a-b862-62b51c7bd3f4">
<br/>
<br/>

After reloading the vscode window, the issue is fixed for the files created/moved prior to the reload.

# in the file itself
<img width="496" alt="Screenshot 2024-05-01 at 11 04 30 AM" src="https://github.com/vuejs/language-tools/assets/51875816/37a87ee8-fbb0-4da1-85e5-75eecfbe9399">

# importing the file

<img width="244" alt="Screenshot 2024-05-01 at 10 59 06 AM" src="https://github.com/vuejs/language-tools/assets/51875816/de3af65e-c113-4174-a4b3-0d82af16cfbd">

**Comment by vladyslav-mikhieiev** [comment]
I'm using wsl2 and I have the same problem. When creating a new Vue component, I cannot import it automatically by name because vscode does not see it. You have to run the Vue command: Restart Vue and TS servers every time. 😔

**Comment by itamar3429** [comment]
Hi. 
Apparently the new update to version v2.0.16 fixed all of the issues mentioned above.

Thanks to all of the vue extension team.
