### ISSUE TITLE
How to specify typescript path to volar lsp

### ISSUE THREAD

**Issue by immdevrov** [vuejs/language-tools#4332]
From [documentation](https://github.com/vuejs/language-tools?tab=readme-ov-file#none-hybrid-modesimilar-to-takeover-mode-configuration-requires-vuelanguage-server-version-207) for `hybridMode: false`:
_Make sure you have typescript installed globally or **pass the location to volar**_

How to pass typescript location to volar?

A an trying to configure neovim lsp
```
require'lspconfig'.volar.setup {
  filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
  init_options = {
    vue = {
      hybridMode = false,
    },
  },
  on_attach = on_attach,
  capabilities = capabilities
}
```

**Comment by RayGuo-ergou** [comment]
In most case `lspconfig` will do that for you, e.g. find tsdk in pwd first then find in root. see: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/volar.lua#L27

If you want to define yourself you can do

```diff
require'lspconfig'.volar.setup {
  filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
  init_options = {
    vue = {
      hybridMode = false,
    },
+   typescript:{
+     tsdk: <YOUR_PATH>
+   },
  },
  on_attach = on_attach,
  capabilities = capabilities
}
```

see: https://github.com/vuejs/language-tools/blob/d587ba044ca4a1cf795f135752aaa2c36cb66e95/packages/language-server/lib/types.ts#L4-L6

**Comment by immdevrov** [comment]
Thanks!
