### ISSUE TITLE
How to use format

### ISSUE THREAD

**Issue by ling7788** [vuejs/language-tools#4334]
How to use formatting for Vue files? 
I have enabled the settings in my configuration file, but the formatting is invalid
![image](https://github.com/vuejs/language-tools/assets/11828443/d192a77e-57d9-4b79-98b5-5900baf99ea6)

**Comment by ling7788** [comment]
![image](https://github.com/vuejs/language-tools/assets/11828443/451e71a9-22d6-41d8-8458-62e7559baccd)
nothing changed!

**Comment by cadilhac** [comment]
Same issue here. Setting Vue-Official as the formatter does not work.

**Comment by zjp-CN** [comment]
For anyone who is seeing this issue, here's the solution for me.

1. In a vue file, click the Vue button in the bottom right corner of VSCode, and select "Configure 'vue' languange based settings..." from the pop-up window. [^1]
2. Add `"editor.defaultFormatter": "Vue.volar"` in `[vue]`.



![](https://github.com/user-attachments/assets/0d313977-0ee5-4c5e-8ebb-25301aaf0ed5)
![](https://github.com/user-attachments/assets/54c6e900-a06d-4ecb-8674-9bc08e5675ec)


```json
{
    // add formatter setting for vue files
    "[vue]": {
        "editor.defaultFormatter": "Vue.volar"
    }
}
```


[^1]: Or directly open your settings.json somewhere to add the setting.
