### ISSUE TITLE
Is Vue.Volar still the recommended formatter since the new Vue - Official extension has been released?

### ISSUE THREAD

**Issue by FVolral** [vuejs/language-tools#4337]
The Vue documentation mentions two solutions for code formatting: either using the Vue - Official extension or utilizing Prettier. Previously, to utilize the formatting provided by the Volar extension in VSCode, one could do the following:

```
"[vue]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "Vue.volar"
}
```

Is `Vue.volar` still the recommended choice with the new extension? It's a bit confusing considering Volar is supposed to be deprecated. If that's still the case, I have another question: how can one reformat all the code in a project using `Vue.volar`?

**Comment by so1ve** [comment]
Yes, the new Vue - Official extension still uses `Vue.volar` as the id.

**Comment by guozhenyi** [comment]
But, in Vue - Official v2.0.16, the formatters was removed... 😭 
![vscode-vue-formatter](https://github.com/user-attachments/assets/df45b561-e539-4799-8129-1f38a18810d2)

**Comment by tsxoxo** [comment]
Just stumbled upon this in my settings.json. What's the status now? 

BTW I had a quick glance at the various READMEs of the official extension and didn't see a guide about setting up Vue with VSCode -- is there such a guide aimed at beginners? (Going through things like settings, linting, quality-of-life-features such as snippets)
