### ISSUE TITLE
使用泛型hook，ts类型推断错误 / Using generic hook, ts type inference error

### ISSUE THREAD

**Issue by zhengybo** [vuejs/language-tools#4341]
测试用例/demo
[demo.zip](https://github.com/vuejs/language-tools/files/15213808/demo.zip)

hooks.ts
![image](https://github.com/vuejs/language-tools/assets/22511317/98221619-57e0-41d9-94c4-edb6f346ea8d)

test.vue
![image](https://github.com/vuejs/language-tools/assets/22511317/9fcbc53a-d39e-4015-959e-4338714668fd)

如果在函数中使用了抛出的值 / If an thrown value is used in a function
![image](https://github.com/vuejs/language-tools/assets/22511317/47c081ed-2558-4e14-a02b-128faabbab79)
这里a会被推断为any  / Here, variable a will be inferred as any

将test 函数中的a引用注销，推断恢复 / Unregister the reference to a in the test function and infer recovery
![image](https://github.com/vuejs/language-tools/assets/22511317/79abfd66-eca1-412f-b45e-2ab698eeb5c5)

尝试去掉泛型，类型推断正常 / Attempting to remove generics, type inference is normal
![image](https://github.com/vuejs/language-tools/assets/22511317/9eaa3cc4-1cd8-47e6-94aa-b297bd6d6028)
![image](https://github.com/vuejs/language-tools/assets/22511317/decb0170-4607-4592-8e2b-5f5f29a98085)

例子最终运行结果正常，但是ts推断异常 / The final running result of the example is normal, but ts inference is abnormal

Vue - Official: v2.0.16
VSCode: v1.89.0
系统: Windows 11
框架:  vite vue3

**Comment by RayGuo-ergou** [comment]
This seems right to me. 

Have a read about scope https://developer.mozilla.org/en-US/docs/Glossary/Function

**Comment by so1ve** [comment]
What is `AnyObject`?

**Comment by zhengybo** [comment]
能复现了？

> What is `AnyObject`?

**Comment by KermanX** [comment]
I think this is not related to the Vue language tools. In plain TypeScript you can also get this error:

![image](https://github.com/vuejs/language-tools/assets/63178754/fdafadcd-5f26-4eb0-be14-68353403b040)

**Comment by johnsoncodehk** [comment]
Closed due to answered in https://github.com/vuejs/language-tools/issues/4341#issuecomment-2105660801.
