### ISSUE TITLE
V2.0.16 code folding function disabled.

### ISSUE THREAD

**Issue by CTRGKA25** [vuejs/language-tools#4342]
After disabling the  Vue - Official
plugin, the folding function can be used again
![img](https://github.com/vuejs/language-tools/assets/90240014/f13b8704-ce30-440c-8340-a3da778e3642)

**Comment by CTRGKA25** [comment]
![image](https://github.com/vuejs/language-tools/assets/90240014/9c60815e-5b6b-4f08-a247-7276e4a9ec9e)

**Comment by baizhi958216** [comment]
also:
Version: 1.89.0 (system setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by pzgz** [comment]
@CTRGKA25 Also has this issue recently....when the folding feature is gone, you will also lost features such as Symbol location, I think the Vue LSP is just stopped working, I tried to switch between inside and regualr version of vscode, all with this issue, but not able to reproducable constantly

**Comment by seraphimMM** [comment]
code folding is working under v2.0.14

**Comment by eric-g-97477** [comment]
I can confirm that it does work under 2.0.14. It broke with 2.0.15.

**Comment by seraphimMM** [comment]
Guys, fixed in 2.0.17. Now this issue can be closed.
