### ISSUE TITLE
Syntax highlight breaks when using directives/mixins on Vue2 with TS

### ISSUE THREAD

**Issue by BulatSa** [vuejs/language-tools#4349]
Hello, when i use Typescript 5.4.5 on components with `directives`/`mixins` syntax highlight breaks
Without `directives`
![image](https://github.com/vuejs/language-tools/assets/8298469/a989f48a-aa89-4ebb-b61f-a5cf8e73765c)
 With `directives`
![image](https://github.com/vuejs/language-tools/assets/8298469/ab0bca82-ac8b-4007-95cb-c341b9192cf1)

**Comment by so1ve** [comment]
This is likely a vue core issue

**Comment by davidmatter** [comment]
Are you still having this issue with the latest vue and latest language tools versions?
