### ISSUE TITLE
vue-official导致项目全部报错

### ISSUE THREAD

**Issue by hdthhh** [vuejs/language-tools#4356]
vue-official自动更新到了最新版本2.0.16，导致代码所有文件全部飘红，
尝试切换到1.8.27，禁用vetur，还是全部都是红色

![image](https://github.com/vuejs/language-tools/assets/100888871/a0908380-ad2e-4d71-8e35-c189c8978115)

**Comment by extclp** [comment]
图片太模糊了...

**Comment by hdthhh** [comment]
> 图片太模糊了...

图片只是单纯表示一下，以某个文件的飘红为例子，代表文档所有文件都这样飘红

**Comment by lukesyy** [comment]
是开启了eslint导致的吧

**Comment by Jamin-Deng** [comment]
<img width="1356" height="784" alt="Image" src="https://github.com/user-attachments/assets/94d5fa6e-110a-4867-8f6a-56d2813166aa" />
为什么align老是红色，但是代码并没错也不影响运行

**Comment by lukesyy** [comment]
> <img alt="Image" width="1356" height="784" src="https://private-user-images.githubusercontent.com/34088901/566741165-94d5fa6e-110a-4867-8f6a-56d2813166aa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM5OTY3NjEsIm5iZiI6MTc3Mzk5NjQ2MSwicGF0aCI6Ii8zNDA4ODkwMS81NjY3NDExNjUtOTRkNWZhNmUtMTEwYS00ODY3LThmNmEtNTZkMjgxMzE2NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzIwVDA4NDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZjYxMzM2NThjYmY4ZDY0OWIxNzcyNTQxZjNhMmQxMWU5YWUzY2YyZjc2MGY4MTVhNGM4NjVlZjU5YTI3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gRWoCLjxIz-yx7VgHuYbT2R160r5CWWFxGB6BIkylRc"> 为什么align老是红色，但是代码并没错也不影响运行

这是代码高亮 不喜欢换个主题就好了

**Comment by Jamin-Deng** [comment]
> > <img alt="Image" width="1356" height="784" src="https://private-user-images.githubusercontent.com/34088901/566741165-94d5fa6e-110a-4867-8f6a-56d2813166aa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM5OTY3NjEsIm5iZiI6MTc3Mzk5NjQ2MSwicGF0aCI6Ii8zNDA4ODkwMS81NjY3NDExNjUtOTRkNWZhNmUtMTEwYS00ODY3LThmNmEtNTZkMjgxMzE2NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzIwVDA4NDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZjYxMzM2NThjYmY4ZDY0OWIxNzcyNTQxZjNhMmQxMWU5YWUzY2YyZjc2MGY4MTVhNGM4NjVlZjU5YTI3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gRWoCLjxIz-yx7VgHuYbT2R160r5CWWFxGB6BIkylRc"> 为什么align老是红色，但是代码并没错也不影响运行
> 
> 这是代码高亮 不喜欢换个主题就好了



> > <img alt="Image" width="1356" height="784" src="https://private-user-images.githubusercontent.com/34088901/566741165-94d5fa6e-110a-4867-8f6a-56d2813166aa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM5OTY3NjEsIm5iZiI6MTc3Mzk5NjQ2MSwicGF0aCI6Ii8zNDA4ODkwMS81NjY3NDExNjUtOTRkNWZhNmUtMTEwYS00ODY3LThmNmEtNTZkMjgxMzE2NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzIwVDA4NDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZjYxMzM2NThjYmY4ZDY0OWIxNzcyNTQxZjNhMmQxMWU5YWUzY2YyZjc2MGY4MTVhNGM4NjVlZjU5YTI3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gRWoCLjxIz-yx7VgHuYbT2R160r5CWWFxGB6BIkylRc"> 为什么align老是红色，但是代码并没错也不影响运行
> 
> 这是代码高亮 不喜欢换个主题就好了

怎么换主题，红色我老以为他报错了

**Comment by serkodev** [comment]
See: https://github.com/vuejs/language-tools/issues/4510#issuecomment-3612672889
