### ISSUE TITLE
goto definition does not work to func or value in html tags

### ISSUE THREAD

**Issue by ahmedmelihozdemir** [vuejs/language-tools#4359]
![Ekran Resmi 2024-05-09 17 42 10](https://github.com/vuejs/language-tools/assets/96570849/03cda5bd-4ddb-492a-b725-0d5ef6e41be9)

**Comment by KermanX** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
