### ISSUE TITLE
Props break when i define data in defineComponent

### ISSUE THREAD

**Issue by ardelan869** [vuejs/language-tools#4363]
With data() defined
![image](https://github.com/vuejs/language-tools/assets/101870550/d62650db-bb02-4e70-8999-32b97d04564a)
Without data() defined
![image](https://github.com/vuejs/language-tools/assets/101870550/bfc0a633-2227-45f7-9812-f9d185d4ab7f)

```vue
<script lang="ts">
import { defineComponent } from 'vue';
import { vmin } from '@/lib/css';
import ButtonWrapper from './ButtonWrapper.vue';

export default defineComponent({
  name: 'Selection',
  components: {
    ButtonWrapper
  },
  data() {
    return {
      user: {
        id: 123456,
        name: 'ARDELAN 🐈🧶',
        picture:
          'https://www.pcgamesn.com/wp-content/sites/pcgamesn/2022/12/gta-5-dlc-los-santos-drug-wars.jpg'
      }
    };
  },
  methods: {
    vmin
  },
  props: {
    page: {
      type: String,
      default: 'selection',
      validator: (value) => {
        return typeof value === 'string';
      }
    }
  }
});
</script>
```

**Comment by ardelan869** [comment]
It also shows an error when i use the component in another one
![image](https://github.com/vuejs/language-tools/assets/101870550/161347cf-a177-4b01-bc37-71af526a5829)

**Comment by so1ve** [comment]
https://github.com/vuejs/core/issues/9296

**Comment by ardelan869** [comment]
> [vuejs/core#9296](https://github.com/vuejs/core/issues/9296)

This issue isn't similar. My problem is that all the props become unknown when i define them like this and use data() ```vue
props: {
  prop: {
      type: String,
      default: 'selection',
      validator: (value) => {
        return typeof value === 'string';
      }
  }
}
```

**Comment by Alexey-B** [comment]
@ardelan869 why did you close the issue? Did you find a solution?
I found that it is the validator that breaks the code. Just comment it and the error disappears.
The compiler doesn't complain about anything, but this is abnormal behavior.

**Comment by ardelan869** [comment]
@Alexey-B I haven't found a solution, haven't even used Vue in a long time. Thank you for the answer though.

**Comment by Alexey-B** [comment]
@ardelan869 thanks for the answer, I found another suggestion for this problem:
https://github.com/vuejs/language-tools/issues/93
