### ISSUE TITLE
2.0.14 可以格式化vue文件 更新到 2.0.15和2.0.16都无法格式化vue文件

### ISSUE THREAD

**Issue by WMSmile** [vuejs/language-tools#4366]
2.0.14 可以格式化vue文件 更新到 2.0.15和2.0.16都无法格式化vue文件

vscode版本

版本: 1.89.1 (Universal)
提交: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
日期: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 22.6.0

**Comment by July7777777** [comment]
赶紧和prettier梦幻联动把

**Comment by GuoJun-Zhang-0115** [comment]
从 2.0.14 版本后，感觉这个工具都有问题了，什么原因了？我使用的不对？

**Comment by zpc7** [comment]
最近的版本 太多问题了, 官方没有测试覆盖的吗??

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: Please let us know if you're still encountering this issue. Otherwise kindly close this one, thanks!
