### ISSUE TITLE
How to install version 2.0.2?  The optional list has become only these few

### ISSUE THREAD

**Issue by warmthsea** [vuejs/language-tools#4367]
![image](https://github.com/vuejs/language-tools/assets/45450994/48474f4f-6bb8-4eb0-b887-5541303c0e58)
![image](https://github.com/vuejs/language-tools/assets/45450994/38748266-22f2-466c-82b2-95922529043f)
![image](https://github.com/vuejs/language-tools/assets/45450994/65527ea1-1f8e-4d3b-9408-03164aea691e)

**Comment by RayGuo-ergou** [comment]
see https://github.com/vuejs/language-tools/issues/4227

It's caused by a bug on vscode.
