### ISSUE TITLE
Updating `vue.volar`  to 2.0.17, the `completionInfo` can't get information successful

### ISSUE THREAD

**Issue by zcf0508** [vuejs/language-tools#4368]
![Snipaste_2024-05-10_23-43-22](https://github.com/vuejs/language-tools/assets/21942252/bd857cdd-5f82-4310-8583-1cba4e0964f4)

![Snipaste_2024-05-10_23-43-38](https://github.com/vuejs/language-tools/assets/21942252/7da6cb46-38a3-494e-9a45-79c26bc7922b)

This situation only occurs when the cursor target in `setup` block or `setup` function of `defineComponent` and top level identifier, like `altered` and `start`. The others like `msg` and `data` are work fine.

**Comment by zcf0508** [comment]
volar 2.0.17

**not work**
![image](https://github.com/vuejs/language-tools/assets/21942252/252f405a-534e-41e0-9aaf-536393aec1e1)

**work**
![image](https://github.com/vuejs/language-tools/assets/21942252/f983b7bd-4602-4800-8f32-69dfc6d5aac3)

**Comment by zcf0508** [comment]
![image](https://github.com/vuejs/language-tools/assets/21942252/8b7ec289-e856-4301-9db8-762a5eb0b682)

![image](https://github.com/vuejs/language-tools/assets/21942252/2bc16ecf-1691-4c57-83f0-b5f6ba522309)

**Comment by zcf0508** [comment]
https://github.com/volarjs/volar.js/blob/v2.2.2/packages/typescript/lib/node/decorateLanguageService.ts#L702

When there is no return of `result.entries`, should the result be retained?

**Comment by johnsoncodehk** [comment]
@zcf0508 Could you try does this fixes the issue?
[volar-2.0.17-patch.1.vsix.zip](https://github.com/vuejs/language-tools/files/15292013/volar-2.0.17-patch.1.vsix.zip)

**Comment by zcf0508** [comment]
> @zcf0508 Could you try does this fixes the issue? [volar-2.0.17-patch.1.vsix.zip](https://github.com/vuejs/language-tools/files/15292013/volar-2.0.17-patch.1.vsix.zip)

It works fine!
