### ISSUE TITLE
v2.0.17 Reports Errors for Multiple Event Bindings

### ISSUE THREAD

**Issue by aturingmachine** [vuejs/language-tools#4369]
## Description
The following template (an excerpt) will be fine when `vue-tsc` is run using version 2.0.16, however will throw errors on 2.0.17.

```vue
<div
  @keyup.enter="handleCheck(option.value)"
  @keyup.space.prevent="handleCheck(option.value)"
>
```

Error:
```
src/components/base/base-radio-buttons.vue:14:8 - error TS1117: An object literal cannot have multiple properties with the same name.

14       @keyup.space.prevent="handleCheck(option.value)"
          ~~~~~
```

## More Info
Our codebase is Nuxt, and we run typecheck via `nuxi typecheck` which runs `vue-tsc` via `npx`. Meaning this failure popped on our GitHub Actions where the `npx` cache misses `vue-tsc` and installs `v2.0.17`, however our local environments have `v2.0.16` cached and do not report the error.

**Comment by scottbedard** [comment]
I'm running into this too, I was just about to open a ticket myself 🙂 

https://github.com/scottbedard/vue-tsc-event-listener-type-error

This appears to be a bug though, [Vue supports this syntax](https://play.vuejs.org/#eNp9kk9vwjAMxb9KlAsgoXLYTqib9kcctknbtO2YS1VMV0idKHGACfW7z0mhgIS4JX7vuT+72clHa7N1ADmVuS9dbUl4oGCFLrC6U5K8kvcKFwFLqg0KgzMkcMOR2CkUojTojYZMm2o4gKgMRgpbhWeRN/ibmw1eDK06bR/LJx0Ef5IvBI3VBQHfhMhrtIHiSYiHfYoB++5KnmtZwkmOhKykmHCjfHLSVY55QMZZ1FW29AZ5C4lQydI0ttbgPmycgZcw7dijVmhtNq+pRi7A+FAvf6FcXagv/TbWlPx04MGtQcleo8JVQJ08+36HLZ97sTHzoNl9RfwCXmWIjJ3tKeCcsU98ifalscZRjdWPn20J0B+GiqDR2Sa/kvwUnq+MfsS9yW5Tjn+bbP8B97XDtg==). Looking more at the compiled output, everything appears normal. The `keydown` listeners appear to be compiling correctly.

```js
function render(_ctx, _cache, $props, $setup, $data, $options) {
  return (_openBlock(), _createElementBlock("input", {
    onKeydown: [
      $setup.onKeydown,
      _withKeys($setup.onEnter, ["enter"])
    ]
  }, null, 32 /* NEED_HYDRATION */))
}
```
