### ISSUE TITLE
After the upgrade WeChat applet tag will report an error

### ISSUE THREAD

**Issue by no5no6** [vuejs/language-tools#4370]
vue-official  v2.0.17
vue  v3.4.21
typesciprt  v4.9.5

<img width="1072" alt="image" src="https://github.com/vuejs/language-tools/assets/5174886/1ea1fe2d-7eb5-4901-a96f-19dae2678371">

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/issues/4316

**Comment by no5no6** [comment]
It works for me. Thank you so much 🙏 @so1ve
