### ISSUE TITLE
No "Element is missing end tag" error when using hybrid mode

### ISSUE THREAD

**Issue by b-erhart** [vuejs/language-tools#4371]
## Description
In the `<template>` section of `.vue` files, I don't get "Element is missing end tag" errors by the LSP if I use volar in hybrid mode. They are displayed if hybrid mode is disabled.

Other errors like wrong variable names are displayed in both configurations.

## More Info
Volar version: `2.0.17`
Editor: Neovim with Volar integration via  [lspconfig](https://github.com/neovim/nvim-lspconfig)

### Faulty configuration (hybrid mode enabled)
```lua
local lspconfig = require('lspconfig')
lspconfig.tsserver.setup({
    init_options = {
        plugins = {
            {
                name = '@vue/typescript-plugin',
                location = '<location>',
                languages = { 'vue' }
            },
        },
    },
    filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
})
lspconfig.volar.setup({})
```
This results in:
![grafik](https://github.com/vuejs/language-tools/assets/46035805/7913b435-654a-4828-96d7-2a27073109ad)

### Working configuration (hybrid mode disabled)
```lua
local lspconfig = require('lspconfig')
lspconfig.tsserver.setup({
    init_options = {
        plugins = {
            {
                name = '@vue/typescript-plugin',
                location = '<location>',
                languages = { 'vue' }
            },
        },
    },
})
lspconfig.volar.setup({
    init_options = {
        vue = {
            hybridMode = false,
        },
    },
})
```
This results in:
![grafik](https://github.com/vuejs/language-tools/assets/46035805/0dd67f8c-5919-4613-b32a-508ecb8dcbf3)

**Comment by RayGuo-ergou** [comment]
I cannot reproduce this with same config.
![image](https://github.com/vuejs/language-tools/assets/33137074/34cf08f2-f9d1-4b1a-a104-2ca4aef4b6f3)

are you running same volar and ts plugin under same version?

**Comment by hkeidesen** [comment]
I have the same config as OP, but I don't get "Element is missing end tag" with either Hybrid mode on or off.

**Comment by RayGuo-ergou** [comment]
`hybrid` mode should not matter at all as it's purely provided by `vue-language-server`, e.g. I can get that error even without javascript support (hybrid mode on, tsserver disabled)
![image](https://github.com/vuejs/language-tools/assets/33137074/0fa0ef41-7e49-41d1-a168-e1b06a7cf140)
![image](https://github.com/vuejs/language-tools/assets/33137074/5ba1c7e9-7836-469e-8d01-5abf7947c868)

Could you check the `lspinfo` and `lsplog` to see if there has any error/warnings?

**Comment by b-erhart** [comment]
> Could you check the `lspinfo` and `lsplog` to see if there has any error/warnings?

I don't see any errors or warnings there.

---

To isolate the issue, I've created the following minimal Neovim configuration that I can reproduce the issue with:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  { "neovim/nvim-lspconfig", lazy = false },
})

local lspconfig = require("lspconfig")
lspconfig.tsserver.setup({
  init_options = {
    plugins = {
      {
        name = "@vue/typescript-plugin",
        location = "/home/b-erhart/.local/share/npm/lib/node_modules/@vue/typescript-plugin",
        languages = {"javascript", "typescript", "vue"},
      },
    },
  },
  filetypes = {
    "javascript",
    "typescript",
    "vue",
  },
})
lspconfig.volar.setup({})
```

To use this config, move your neovim config and data folders to a different location (on Linux these are `~/.config/nvim` and `~/.local/share/nvim` respectively). Then create a new `init.lua` and paste the config above. Make sure to adjust the TS plugin location.

Maybe you can reproduce the issue with this configuration (+ Volar and TS plugin version `2.0.17`) @RayGuo-ergou?

**Comment by RayGuo-ergou** [comment]
I probably know where's the issue is. I am running nightly neovim:

```
vim -v
NVIM v0.10.0-dev-3135+g7acf39dda
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```
It might be new vue-language-server uses lsp event 0.9.5 does not support yet.

Can you guys try with nightly neovim and see if the problem solved? ( download binary problem the quickest way)

**Comment by RayGuo-ergou** [comment]
>Maybe you can reproduce the issue with this configuration (+ Volar and TS plugin version 2.0.17) @RayGuo-ergou?

Lazy to do things here and there to make this config working, but I tried with `nvim.kickstater` ( should be minimal enough) and still cannot reproduce this.
![image](https://github.com/vuejs/language-tools/assets/33137074/dac9a658-f7f1-4fb1-a8a4-ceb487cb3c49)
![image](https://github.com/vuejs/language-tools/assets/33137074/9894aa70-8e1f-4d5b-9c3c-8eaa0c5be084)

My best guess as mentioned above is neovim version

**Comment by b-erhart** [comment]
Can confirm, using the nightly version of Neovim solves the issue.

**Comment by b-erhart** [comment]
Thank you very much for your support @RayGuo-ergou :)

**Comment by moliyu** [comment]
when I use `map("n", "<A-j>", "<cmd>m .+1<cr>==", { desc = "Move Down" })` to move the html block, it happens frequently
