### ISSUE TITLE
Type errors on builded library

### ISSUE THREAD

**Issue by FanilZarip** [vuejs/language-tools#4377]
Hi! I tried build library with vite-plugin-dts and without it.

Both build packages have type errors.
Package was created on last vue with npm create vue@latest

I also tried build on older vue version with  npm create vue@3.3 and library build success. It's don't have type errors when i use my own package on older version

My test repo with dts plugin
https://github.com/FanilZarip/test-lib-build/tree/lib_build_with_dts

My test repo without dts plugin
https://github.com/FanilZarip/test-lib-build/tree/build_without_dts_plugin

**Comment by RayGuo-ergou** [comment]
Seems like a typescript issue to me (tsconfig.json).

**Comment by FanilZarip** [comment]
> Seems like a typescript issue to me (tsconfig.json).

I tried updating typescript in a project created with npm create vue@3.3. Library types work.
But don't work with npm create vue@latest where tsconfig is different from tsconfig which is created in npm create with vue@3.3 tsconfig

Have you tried building a simple library with typescript types on the latest version of Vue?

**Comment by RayGuo-ergou** [comment]
I copied the tsconfig files i used to work with building an UI lib. Also you don't have to pass `--build` to build, I think it will build the references first. But your references seems only for development, e.g. testing and vite config file.

Here: https://github.com/FanilZarip/test-lib-build/compare/lib_build_with_dts...RayGuo-ergou:test-lib-build:lib_build_with_dts

**Comment by FanilZarip** [comment]
> I copied the tsconfig files i used to work with building an UI lib. Also you don't have to pass `--build` to build, I think it will build the references first. But your references seems only for development, e.g. testing and vite config file.
> 
> Here: [FanilZarip/test-lib-build@lib_build_with_dts...RayGuo-ergou:test-lib-build:lib_build_with_dts](https://github.com/FanilZarip/test-lib-build/compare/lib_build_with_dts...RayGuo-ergou:test-lib-build:lib_build_with_dts)


Hi!

I've created a library with your configs and trying to use it in a new Vue project. But there are still type errors when using it. 

My repo with test library. I pack it with npm pack and install locally from /src/local_repo
https://github.com/FanilZarip/test_use_own_library

And type errors screen.

![errors](https://github.com/vuejs/language-tools/assets/92334779/abb620c5-f859-4620-afe4-48c71228d9b5)

**Comment by RayGuo-ergou** [comment]
You are building with --build again. You should understand how it and tsconfig references works. 

I also recommend you to start a new project with vite create. 

https://vitejs.dev/guide/

**Comment by FanilZarip** [comment]
> You are building with --build again. You should understand how it and tsconfig references works first.
> 
> I also recommend you to start a new project with vite create.
> 
> https://vitejs.dev/guide/

Here I build it with your tsconfig and pack with npm pack
https://github.com/FanilZarip/test-lib-build/tree/lib_build_with_dts

Here I use this npm package and run type checking and language-tools do not show types. I create vue project with vuejs recommended way. npm create vue@latest. It is clear project with ts. And i wait that config will run well from box.

Also if I run just vue-tsc --watch, yes it is do not show any type errors. But if i use uncorrect props value type it also do not show type error. In my screen I use BaseButton with type="out" instead of "outline" and vscode and vue-tsc do not show errors for types
 
https://github.com/FanilZarip/test_use_own_library/tree/test_own_lib

**Comment by FanilZarip** [comment]
![image](https://github.com/vuejs/language-tools/assets/92334779/a0ed58d4-740e-40f4-b687-55cd40601d17)

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/vuejs/language-tools/assets/33137074/8fcf33c0-d950-4b1f-a47d-213858383b94)
![image](https://github.com/vuejs/language-tools/assets/33137074/768d054c-2c85-4d9a-bcbb-64ec958b274b)

Not really sure what you mean but all working fine on my side. ( I also used `pnpm create vue@latest` to create the project)

Maybe you missed this, in your ui lib's package.json. You need to declare where the type file is.
```diff
  "exports": {
    ".": {
+      "types": "./dist/types/index.d.ts",
      "import": "./dist/testui.es.ts",
      "require": "./dist/testui.umd.ts"
    },
    "./styles": "./dist/style.css"
  },
```

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/vuejs/language-tools/assets/33137074/5434c3d9-0753-4312-8d0e-4c80d1d072ce)
![image](https://github.com/vuejs/language-tools/assets/33137074/d97555c3-94f8-4111-9e07-ccb0c1d6b07e)

also tried your repo, works fine, guessing you just missed that part.
see: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
for more information.

**Comment by FanilZarip** [comment]
> ![image](https://private-user-images.githubusercontent.com/33137074/331524158-5434c3d9-0753-4312-8d0e-4c80d1d072ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTA2NTYsIm5iZiI6MTcxNjAxMDM1NiwicGF0aCI6Ii8zMzEzNzA3NC8zMzE1MjQxNTgtNTQzNGMzZDktMDc1My00MzEyLThkMGUtNGM4MGQxZDA3MmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA1MzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzdlZjc1ZmM2ZDk5YTkxYjU5MTNkZmJkODk2NjdiN2U5OGE2MjhhMjQzNGUzZDY4NzFhZjRkODNhODA2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gqUHKDz_cnFS13Kg84_HjtkuD5RJo0X4ScnnPuJ7n1U) ![image](https://private-user-images.githubusercontent.com/33137074/331524536-d97555c3-94f8-4111-9e07-ccb0c1d6b07e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTA2NTYsIm5iZiI6MTcxNjAxMDM1NiwicGF0aCI6Ii8zMzEzNzA3NC8zMzE1MjQ1MzYtZDk3NTU1YzMtOTRmOC00MTExLTllMDctY2NiMGMxZDZiMDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA1MzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNGNkMDk5MDQ1YzE1ZDE1NDQyN2QwMmYyNjA4OWQ2NWNmM2RkYzA4YTNkMzVmZTY0YTA0OGQxZjc3ZWMzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rQqA0v4CT-_BS9zeetbiDTPh_f3DE7o8aRXEppPdL1U)
> 
> also tried your repo, works fine, guessing you just missed that part. see: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html for more information.

Yes, You are right. It was vite-plugin-dts problem with default tsconfig


Thanks!

**Comment by FanilZarip** [comment]
https://github.com/qmhc/vite-plugin-dts/issues/323

vite-plugin-dts error explained here
