### ISSUE TITLE
Component description doesnt show up in VS Code

### ISSUE THREAD

**Issue by moritz-baecker-integra** [vuejs/language-tools#4378]
When using the <script setup> sytax with TypeScript, the description for a component won't show up when hovering over the component.

This doesn't work:
![image](https://github.com/vuejs/language-tools/assets/164020968/7913d206-b8e4-4d70-b16c-8c2efca4aa61)
![image](https://github.com/vuejs/language-tools/assets/164020968/375afae6-b9d7-4029-8ecd-fcb133884a3f)

But this does:
![image](https://github.com/vuejs/language-tools/assets/164020968/a835edd5-18d6-468a-8f5f-7965f820bb98)
![image](https://github.com/vuejs/language-tools/assets/164020968/b1db1e62-aaf1-4575-8a2d-58247263a6f6)

I would expect it to work in both cases

**Comment by so1ve** [comment]
You may use @vue-macros/volar/setup-jsdoc
