### ISSUE TITLE
vue-tsc 2.0.18: Property 'xyz' does not exist on type 'abc' when using v-for

### ISSUE THREAD

**Issue by mlankamp** [vuejs/language-tools#4386]
Error is happening when I use certain Vuetify components with a v-for loop.

Ok:
```vue
<v-chip closable />
```

Error:
```vue
<v-chip v-for="id in items" :key="id" closable>{{ id }}</v-chip>
```

vscode:
![image](https://github.com/vuejs/language-tools/assets/8513556/8cdd65cd-853e-4db7-acec-068af625cdaa)

build output:
```
> vue-tsc

src/App.vue:10:45 - error TS2339: Property 'closable' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { items: Ref<number[]>; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.

10       <v-chip v-for="id in items" :key="id" closable>{{ id }}</v-chip>
```

example: https://stackblitz.com/edit/vitejs-vite-weuexn?file=package.json,src%2FApp.vue&terminal=build

**Comment by TheDutchCoder** [comment]
This also occurs on regular components.
In our case in Nuxt 3.

The "solution "is to use `:foo="true"` instead of `foo` directly, but that's obviously not how it's supposed to work.
We'll skip this version until a fix is released.

**Comment by mlankamp** [comment]
I first noticed with Vuetify, but my example uses the stackblitz vue-ts template with an extra boolean prop to demonstrate the problem.

**Comment by robertmoura** [comment]
I'm also getting this issue. There is another issue that is strange as well. I have a component that looks like this:

`<custom-component first-second>`

Where the attribute firstSecond is a boolean prop. This is producing 2 errors:

```
Property 'first' does not exist on type ...
Property 'second' does not exist on type ...
```

**Comment by Wangijun** [comment]
I also encountered this problem
