### ISSUE TITLE
Event listeners type issues after upgrade `'($event: any) => void' is not assignable to type '() => any'`

### ISSUE THREAD

**Issue by minht11** [vuejs/language-tools#4387]
After upgrading to vue-tsc 2.0.18 events fail with error message:
```
Type '($event: any) => void' is not assignable to type '() => any'.
  Target signature provides too few arguments. Expected 1 or more, but got 0.
```
Code is nothing special
```ts
const emit = defineEmits<(e: 'submit') => void>()
```
```
@submit="handler()"
```

Verified working version 2.0.7

**Comment by Q16solver** [comment]
Yeah, might be something similar? but now inline dynamic event handlers also seem to be expecting commas instead of semi-colons, which isn't correct unlike before

![image](https://github.com/vuejs/language-tools/assets/50786287/91baece0-49b4-4ac3-84a9-6f638b3b97fe)
