### ISSUE TITLE
升级到 2.0.18后在组件上使用 v-for 会导致 style等部分属性报 ts类型错误

### ISSUE THREAD

**Issue by mxp131011** [vuejs/language-tools#4388]
升级到 2.0.18后在组件上使用 v-for 会导致 style等部分属性报错，提示不存在 style属性，即使在 原生组件如 div 上也会提示，style属性不存在！
![image](https://github.com/vuejs/language-tools/assets/31055355/283a0aa7-1fa5-42bf-b453-052c9286f15b)

![image](https://github.com/vuejs/language-tools/assets/31055355/e1500785-bad7-484e-b20d-d5fed67a2723)

**Comment by Wangijun** [comment]
我也遇到了这个问题，

**Comment by johnsoncodehk** [comment]
Duplicate of #4386
