### ISSUE TITLE
编译崩溃

### ISSUE THREAD

**Issue by shaoweb** [vuejs/language-tools#4389]
Type: <b>Bug</b>

不知道什么原因导致的崩溃

Extension version: 2.0.18
VS Code version: Code - Insiders 1.90.0-insider (Universal) (ccba2fc85c14bedeef5a72b7ebc0bde9b0e91948, 2024-05-06T08:08:04.226Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (2.73GB free)|
|Process Argv|--crash-reporter-id bfe3e451-e28e-4daf-b34d-1befa117b4f4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492:30256197
vstes627:30244334
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
impr_priority:31048137
26j00206:31048877

```

</details>

**Comment by so1ve** [comment]
Please provide more info 😅
