### ISSUE TITLE
开发微信小程序，view标签会类型错误提示

### ISSUE THREAD

**Issue by xy0908** [vuejs/language-tools#4390]
![image](https://github.com/vuejs/language-tools/assets/81454465/d48b93ed-dac8-4934-a394-e72679488e16)

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4370

**Comment by xy0908** [comment]
> #4370的重复[](https://github.com/vuejs/language-tools/issues/4370)

谢谢
