### ISSUE TITLE
How to comment tempalte code with <!-- --> ,not {{/* */}}?

### ISSUE THREAD

**Issue by 717009629** [vuejs/language-tools#4394]
After I updated vscode  vue-office extension, I comment tempalte code from  \ to {{/* */}}.
How to comment tempalte code with \,not {{/* */}}?

```
[vite] Internal server error: Error parsing JavaScript expression: Unexpected token (1:9)
  Plugin: vite:vue
  File: index.vue
  
  10 |      {{/*    */}}
     |        ^
```

**Comment by littlecxm** [comment]
same problem here it happend when I use comment shortcut the Ctrl+/ 
<img width="279" alt="image" src="https://github.com/vuejs/language-tools/assets/16154023/9e8c662d-b47f-4b06-82f9-3b83cd91a9c5">

"vue.server.hybridMode" set to `false`
