### ISSUE TITLE
Vue - Official v2.0.19 Cannot automatically complete @ events, such as click events

### ISSUE THREAD

**Issue by CTRGKA25** [vuejs/language-tools#4395]
![image](https://github.com/vuejs/language-tools/assets/90240014/87c84d31-fbc7-4777-9760-2344159fa2e8)

**Comment by christhofer** [comment]
It is working fine for me

![image](https://github.com/vuejs/language-tools/assets/13524958/19db0f70-9b3a-4e40-bd63-b57fd7b35bd3)

Plugin:
Vue - Official v2.0.19

VS Code
Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by CTRGKA25** [comment]
Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by davidmatter** [comment]
Closing this one as many things have changed in the last 2.x versions. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!
