### ISSUE TITLE
Why color styling is broken?

### ISSUE THREAD

**Issue by romanhrynevych** [vuejs/language-tools#4398]
In some components I have broked code color styling for template tag 🫠 

<img width="725" alt="image" src="https://github.com/vuejs/language-tools/assets/82209198/31fd9369-260d-4f85-89cd-0edd3d249c35">

<img width="677" alt="image" src="https://github.com/vuejs/language-tools/assets/82209198/ccdeb154-742d-4997-95a7-c5b9085d753f">

**Comment by johnsoncodehk** [comment]
This problem cannot be solved in this repo, but there is some progress: #4412
