### ISSUE TITLE
Module `@vue/runtime-core` cannot be reconized by language server

### ISSUE THREAD

**Issue by RayGuo-ergou** [vuejs/language-tools#4401]
I found this issue when working with a project uses element-plus, they use `@vue/runtime-core` to declare global components. I did some research and seems vue document also uses `vue` now ( I remembered before prefer `@vue/runtime-core`?) 

e.g. for code 

```ts
import BaseInput from '@/components/BaseInput.vue'
import BaseButton from '@/components/BaseButton.vue'
declare module 'vue' {
  export interface GlobalComponents {
    BaseInput: typeof BaseInput,
  }
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof BaseButton,
  }
}
```

![image](https://github.com/vuejs/language-tools/assets/33137074/8474316e-b979-4357-9c78-69eea45b83aa)

minimal reproduction: https://github.com/RayGuo-ergou/volar_reproduction_global_component_ts

```
Language server version: 2.0.19
```

**Comment by johnsoncodehk** [comment]
This depends on whether the module is located in the top directory of `node_modules`.

When using npm, both definitions are valid. But when using pnpm, the top directory of `node_modules` only contains `vue` and not `@vue/runtime-core`, so `declare module '@vue/runtime-core'` is invalid.

This is a solution to a different but related issue: https://github.com/vuejs/language-tools/issues/4170#issuecomment-2025528945

**Comment by RayGuo-ergou** [comment]
that makes sense, thank you!
