### ISSUE TITLE
Duplicate intellisense

### ISSUE THREAD

**Issue by Zerokkkkk** [vuejs/language-tools#4402]
![屏幕截图(1)](https://github.com/vuejs/language-tools/assets/111330412/d2284e04-c7b9-4b6f-846d-e1a383a3884b)
![屏幕截图(2)](https://github.com/vuejs/language-tools/assets/111330412/45171972-2acc-45d5-ac46-6fccdb8722d0)

**Comment by KermanX** [comment]
Please share a minimal reproduction and Vue extension's `hybrid mode` setting. Thanks!
