### ISSUE TITLE
.vscode typescript settings not respected in .vue files

### ISSUE THREAD

**Issue by pleek91** [vuejs/language-tools#4405]
I have the following settings added to my workspace `.vscode/settings.json`

```
    "typescript.tsdk": "node_modules/typescript/lib",  
    "typescript.preferences.importModuleSpecifier": "non-relative",
    "typescript.preferences.importModuleSpecifierEnding": "minimal",
    "typescript.preferences.quoteStyle": "single",
    "typescript.preferences.autoImportFileExcludePatterns": [
        "@vue/reactivity",
        "@vue/runtime-dom",
        "./dist",
        "./src/index.ts"
    ],
```

And in a `.ts` file I see a nice short list of suggestions
![image](https://github.com/vuejs/language-tools/assets/6200442/45d481e4-f927-41d7-86fe-089efcc824c1)

But in a `.vue` file the list is much different
![image](https://github.com/vuejs/language-tools/assets/6200442/e7dd25f8-922a-4f59-abb5-b11eb0e9a55a)

Not only is `autoImportFileExcludePatterns` not respected it seems the other settings are not respected either. For example, changing the value of `quoteStyle` has no effect in a `.vue` file and it does in a `.ts` file.

**Comment by so1ve** [comment]
Currently you must enable `hybridMode` to get them work

**Comment by pleek91** [comment]
I added `"vue.server.hybridMode": true,` to my settings but no change. Is there something else I need to do?

**Comment by RayGuo-ergou** [comment]
![GIF 5-21-2024 7-28-29 PM](https://github.com/vuejs/language-tools/assets/33137074/d86098da-4457-45e4-b67f-4778b69170f4)

Just had a try, even tho in code action select drop down it shows double quote, the result still in single quote.

**Comment by pleek91** [comment]
@RayGuo-ergou are the other settings working for you? Are you using hybrid mode?

**Comment by RayGuo-ergou** [comment]
Tried another setting

```json
"typescript.preferences.importModuleSpecifierEnding": "js",
```
![image](https://github.com/vuejs/language-tools/assets/33137074/f5bb3009-9a22-4bf6-ad66-f1f3ff976d0b)

I think it always use default value

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: Please let us know if you're still encountering this issue. Otherwise kindly close this one, thanks!
