### ISSUE TITLE
configuring tags?

### ISSUE THREAD

**Issue by yinkeli** [vuejs/language-tools#4406]
Sorry, I'm not familiar with volar. I'd like to know if volar supports configuring the "vetur" property of package.json to enable code hinting for tags and properties like vetur does.

```json
"vetur": {
    "tags": "tags.json",
    "attributes": "attributes.json"
  }
```

**Comment by davidmatter** [comment]
Hi, please create a proper feature request if you're missing a feature that vetur supported.
