### ISSUE TITLE
Self closing slot tag get red in child component

### ISSUE THREAD

**Issue by audelqua** [vuejs/language-tools#4411]
here is my parent component:
`
<Modal>
    <slot>im inside parent here we go</slot>
</Modal>
`
and here is my child component: 
`
<template>
    <slot />
</template>
`
here in child component **the slash** got red unexpectedly.

**Comment by RayGuo-ergou** [comment]
see https://github.com/vuejs/language-tools/issues/1317

btw self close tag does not 100% equal to normal tag like `<div /> !== <div></div>` not 100% sure about slot tho

**Comment by KazariEX** [comment]
Duplicate of #1317
