### ISSUE TITLE
vue-tsc 2.0.18/19: Cannot find name 'xyz' property when  using experimentalModelPropName config

### ISSUE THREAD

**Issue by johuhype** [vuejs/language-tools#4414]
Hello, I am using the vuetify2-component-types dev dependency.
There is a recommended setting to configure where vuetify 2 deviates from the standard value/input configuration for v-model:

        "experimentalModelPropName": {
            "input-value": {
                "v-checkbox": true,
                "v-switch": true,
                "v-chip": true,
                "v-btn": true,
                "v-list-item": true,
                "v-bottom-navigation": true
            },
            "": { "input": true },
            "value": {
                "input": { "type": "text" },
                "textarea": true,
                "select": true
            }

Pre 2.0.18, this was working as intended. Now, in 2.0.18/19 I am getting error messages from vue-tsc
![image](https://github.com/vuejs/language-tools/assets/16450706/9edf7c54-93f9-41ec-b0fe-dd4f3ad8d43b)

I can fix this a bit by putting v-model as the last thing in the template
![image](https://github.com/vuejs/language-tools/assets/16450706/cf482b17-7e84-4f37-a9b8-305267df6a4c)

But still, the tooltip descriptions / intellisense info are missing. Only, if I would remove v-model completely, they are currently appearing:
![image](https://github.com/vuejs/language-tools/assets/16450706/9d362246-c4aa-469a-b88c-d3f6f8087355)

**Comment by KermanX** [comment]
A possible workaround is replacing `input-value` with `inputValue` in your tsconfig.json

**Comment by Araxor** [comment]
> A possible workaround is replacing `input-value` with `inputValue` in your tsconfig.json

The workaround works, thanks a lot!
