### ISSUE TITLE
VS Code  IntelliSense will be lost in new created files

### ISSUE THREAD

**Issue by EsunR** [vuejs/language-tools#4424]
IntelliSense is working in existing files:

![image](https://github.com/vuejs/language-tools/assets/30311024/a69507e4-7c8d-4ba2-8db4-3581d6a7c513)

But when I create a new file (.js or .vue), vscode IntelliSense not working at all:

![image](https://github.com/vuejs/language-tools/assets/30311024/555eb1cd-c422-4e4d-9afd-74c26db8a387)

![image](https://github.com/vuejs/language-tools/assets/30311024/ee9f3845-8a9f-4b69-99ee-efc3cd9475a5)

After disable Vue - Official extension, everything is ok. So I guess that's maybe this extension question.

**Comment by gustavotoyota** [comment]
What's going on with Vue in VSCode? The official extension is unusable.

**Comment by davidmatter** [comment]
@so1ve @johnsoncodehk  
Tested in insiders and stable vscode and with/without empty profile:

* Creating a new vue file throws the following error: 
<img width="558" alt="image" src="https://github.com/vuejs/language-tools/assets/2319523/e4c13edb-74b8-4f93-851d-c61bb3648d66">

Not sure why the tsserver can't find this file. It only works after closing and reopening the file. This error has been bugging me on and off even before version 2.0. Let me know if you need more information.

**Comment by davidmatter** [comment]
Huh, it works if I add ```src/**/*.js``` to `include` in `tsconfig`. Otherwise, the tsserver can't find newly created vue files :) Might be relevant to you, @johnsoncodehk

**Comment by xakoy** [comment]
> Huh, it works if I set `typescript.tsserver.experimental.useVsCodeWatcher` to `false`. Otherwise, the tsserver can't find newly created vue files. Might be relevant to you, @johnsoncodehk

thanks. It's work.

**Comment by BTBMan** [comment]
> Huh, it works if I set `typescript.tsserver.experimental.useVsCodeWatcher` to `false`. Otherwise, the tsserver can't find newly created vue files. Might be relevant to you, @johnsoncodehk

It works on me!

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/pull/226.
