### ISSUE TITLE
VSCode `Rename Symbol` does not propagate to the template

### ISSUE THREAD

**Issue by danielwaltz** [vuejs/language-tools#4434]
Using the `Rename Symbol` feature in VSCode does not update references to the symbol inside the vue template, and the rename symbol feature is not able to be triggered from inside the template.

https://github.com/vuejs/language-tools/assets/2197883/652336a0-e206-4f62-99ac-947ecdd18852

**Comment by gustavotoyota** [comment]
Same here

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: If you're still encountering issues, please provide a minimal reproduction. Otherwise kindly close this one, thanks!

**Comment by KermanX** [comment]
Closing this issue as completed. Feel free to re-open this with a minimal reproduction. Thanks!

Also, a possible cause of this issue is `skipTemplateCodegen` set to `false` (see https://github.com/vuejs/language-tools/issues/577#issuecomment-1067144577).

**Comment by danielwaltz** [comment]
I think closing this is a good call. I dug a little deeper into why this was happening to me and turns out it was due to a keybind conflict with another VSCode extension I was using called [Abracadabra](https://marketplace.visualstudio.com/items?itemName=nicoespeon.abracadabra). It had precedence over the stock rename symbol function. After clearing that keybind, rename symbol is working as expected. User error. 😅

To others running into this, I would double check your keybindings!

Also, I apologize for not doing due diligence and creating a reproduction. I really appreciate the time and effort that goes into this extension and I should have taken the time myself to do it.
