### ISSUE TITLE
Double suggestions 

### ISSUE THREAD

**Issue by IcyFoxe** [vuejs/language-tools#4435]
Since version **2.0.17**, some code suggestions appear twice (see screenshot).
I can confirm that this issue doesn't happen in version **2.0.16** and earlier.

`app.vue`
![image](https://github.com/vuejs/language-tools/assets/48529386/f098e273-78d1-4567-9a92-83a41b1e2705)

**Comment by so1ve** [comment]
Duplicate of https://github.com/vuejs/language-tools/issues/4402
