### ISSUE TITLE
[performance]:Increasing dependencies in package.json causes performance issues.

### ISSUE THREAD

**Issue by zogwosh** [vuejs/language-tools#4437]
When I installed dependencies such as NaiveUI and the icon component library, the performance of the language server dropped significantly. Is there a way to solve this problem?

**Comment by RayGuo-ergou** [comment]
You probably include `node_modules` in your `tsconfig.json`. Try to exclude that.

**Comment by Ca-tt** [comment]
No, the problem still exists. I have a tconfig.json with this setting, but the problems don't go away. see #4580

**Comment by Ca-tt** [comment]
Hey, @zogwosh check #4580 for solution

**Comment by zogwosh** [comment]
@Ca-tt Thanks, turning off code lens helped me.🙏

**Comment by Ca-tt** [comment]
@zogwosh hey, you're welcome!
