### ISSUE TITLE
v2.0.17+版本 nvue支持异常，不显示组件，且无法cmd+左键跳转

### ISSUE THREAD

**Issue by Es-Rell** [vuejs/language-tools#4438]
### `v2.0.17`及之后的版本对nvue组件异常

`v2.0.16`

<img width="930" alt="image" src="https://github.com/vuejs/language-tools/assets/29221830/24958bdf-f910-4576-a3e2-25dd202882aa">

`v2.0.17`-`v2.0.19`

<img width="606" alt="image" src="https://github.com/vuejs/language-tools/assets/29221830/716ccaff-1067-4aa5-90c7-670165a4fa1d">

**Comment by Es-Rell** [comment]
@so1ve 大佬看看这个问题

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/pull/4321

**Comment by Es-Rell** [comment]
> #4321
按照步骤都是加了的 上述问题依然存在

![image](https://github.com/vuejs/language-tools/assets/29221830/db29ff40-f8e2-4c4b-8025-ab4f997accdb)

![image](https://github.com/vuejs/language-tools/assets/29221830/69b44f82-cb78-46c6-ba81-81ae29614278)

**Comment by Es-Rell** [comment]
@so1ve 还在吗老哥？

**Comment by Es-Rell** [comment]
> 请提供一个重现仓库，不然我们无法复现这个问题
> 
> 同时Uni-app也提供了相应的新版指南，你可以参考一下是否有遗漏

仓库：https://github.com/Es-Rell/test-uniapp.git
此项目由cli直接创建-ts/vite版本

![image](https://github.com/vuejs/language-tools/assets/29221830/669baabe-8c43-43d7-be32-0c016ddc842c)

组件显示异常，且无法跳转，但可通过属性`isBack`跳转。

**Comment by Es-Rell** [comment]
@so1ve 
`v2.0.16`
![image](https://github.com/vuejs/language-tools/assets/29221830/fb253131-42df-43b8-bd4a-e3d0a3c06827)

`v2.0.17+`
不使用中划线，用引入的名称可以跳转，但缺少`v2.0.16`版本更多的参数展示（仅通过引入名跳转到定义）
 ![image](https://github.com/vuejs/language-tools/assets/29221830/e45ca2b7-4e04-41a5-b804-ed4b11423a1d)
 
若使用中划线组件名，则无法跳转，也不展示参数等信息
![image](https://github.com/vuejs/language-tools/assets/29221830/01f59f2f-ca58-4797-9b25-94dafa12d673)

**Comment by davidmatter** [comment]
Are you still having this issue with the latest version?
