### ISSUE TITLE
Can't add in Vscode 1.79.0

### ISSUE THREAD

**Issue by mLiGuangYuan** [vuejs/language-tools#4441]
版本: 1.79.0 (Universal)
提交: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
日期: 2023-06-07T14:29:00.206Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.4.0

![image](https://github.com/vuejs/language-tools/assets/90301679/5133812b-6da0-45fc-b762-b93793785d7c)

**Comment by davidmatter** [comment]
Why not update your vscode?

**Comment by so1ve** [comment]
As @davidmatter says you should upgrade your vscode. Our minimum supported vscode version is 1.88.0.
