### ISSUE TITLE
在.vue文件中写composition没有提示

### ISSUE THREAD

**Issue by HeroZhu-Code** [vuejs/language-tools#4442]
有人写vue3碰到这情况么，composition api没有提示、不会自动导入

<img width="354" alt="25b59017313ad97a1b71d3b4720dc32" src="https://github.com/vuejs/language-tools/assets/152458753/7513ea64-ce07-4d82-ae95-5b618f98d24b">

插件版本：
<img width="456" alt="7cdcbdb8dd0a222f5d2c63be1f29a35" src="https://github.com/vuejs/language-tools/assets/152458753/e366ad0f-e28b-48c2-a757-6af8728d54fa">

**Comment by HeroZhu-Code** [comment]
换了1.8.27版本，没有上面的问题了，但是多次引入api会写多个import * from 'vue'
![image](https://github.com/vuejs/language-tools/assets/152458753/41ca7951-43e0-4345-ad3e-be39df6a328d)
![image](https://github.com/vuejs/language-tools/assets/152458753/e8b43b42-a388-4ce3-98c6-282f38a4e9d6)

**Comment by HeroZhu-Code** [comment]
这是我的vscode版本信息
![image](https://github.com/vuejs/language-tools/assets/152458753/46032ad8-d17d-470b-8092-f0a64cb3ccc6)

**Comment by Shyam-Chen** [comment]
要在專案底下

![image](https://github.com/vuejs/language-tools/assets/13535256/7fce3a1b-7b3a-4c36-9024-d37fd26de6e4)

**Comment by HeroZhu-Code** [comment]
> ![image](https://private-user-images.githubusercontent.com/13535256/336735735-7fce3a1b-7b3a-4c36-9024-d37fd26de6e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzQ3NzMsIm5iZiI6MTcxNzU3NDQ3MywicGF0aCI6Ii8xMzUzNTI1Ni8zMzY3MzU3MzUtN2ZjZTNhMWItN2IzYS00YzM2LTkwMjQtZDM3ZmQyNmRlNmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA4MDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYTNkMjdiY2M0ZGQzYTcyMjYwZjlhODVmN2NlOGVmMDBlZTU5YjA3MjFlMTI4MjZhYjBmODU0MTM3ZTcxNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iosSt_lmbtglPuxUTEa49N3Kcu0dc6pJyQ0gtiF_GZU)

您好，你用的是新版本吗，有人说新版本只有赞助后才能用是真的吗

**Comment by HeroZhu-Code** [comment]
v2.0.19版本，把混动模式关闭后，能正常提示了，但是导入不会合并

<img width="519" alt="645fa77c0e9c9fd0fd862269e406890" src="https://github.com/vuejs/language-tools/assets/152458753/4615a237-6900-4e30-99b0-e2a169b20945">

**Comment by HeroZhu-Code** [comment]
希望我的反馈对作者有价值

**Comment by davidmatter** [comment]
Hey there, as there have been many fixes in the last 2.x versions: If you're still encountering issues, please try to provide a minimal reproduction. Otherwise kindly close this one, thanks!
