### ISSUE TITLE
Major issues in type checking in VSC extension since today (v2.0.20 is broken)

### ISSUE THREAD

**Issue by stouch** [vuejs/language-tools#4453]
### Vue - Official extension or vue-tsc version

vue-tsc = ^1.8.25
official extension = 2.0.20 (BROKEN)

### VSCode version

Version: 1.90.0 (Universal)

### Vue version

^3.4.3

### TypeScript version

~5.3.0

### System Info

```shell
MacOS Sonoma
```

### Steps to reproduce

My vs code in 2.0.20 (BROKEN NO MORE TYPE CHECK ANYMORE) :
<img width="293" alt="Capture d’écran 2024-06-08 à 12 50 17" src="https://github.com/vuejs/language-tools/assets/17531455/877606cd-f862-4e4b-9453-5001371d2c2b">

and , of course (the working version), my vs code in 2.0.19 :
<img width="270" alt="Capture d’écran 2024-06-08 à 12 50 57" src="https://github.com/vuejs/language-tools/assets/17531455/082f5644-df5c-4d90-b257-b8d9e812b7d8">

**Comment by stouch** [comment]
FYI, it must be caused by https://github.com/vuejs/language-tools/commit/09267e80b68b44073fdc260d78d16aed4a6865da -> "Upgrade Volar from `v2.2.4` to `v2.3.0-alpha.14`", no?

Anyway, I revert to the 2.0.19 for this weekend

**Comment by eGust** [comment]
It spent me half hour to figure out, why suddenly my VSCode stop showing TS error messages.

**Comment by agantelin** [comment]
+1
VS Code, Windows 11
Reverting to version 20.0.19 fixed the problem.

**Comment by rodrigocfd** [comment]
I have a React project which, all of a sudden, stopped checking for errors. After uninstalling Vue extension, it started worked again. So yeah, 2.0.20 somehow breaks TypeScript everywhere, even when it's not a Vue project.

* Visual Studio Code 1.90.0
* Linux Mint 21.3

**Comment by anthonypillot** [comment]
+1. Downgrade to the `2.0.19` extension version solves the issue.

```
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by johnsoncodehk** [comment]
Thanks for the report, please try update to v2.0.21.
