### ISSUE TITLE
Terminal not showing errors when running in dev mode. No error checking in code either

### ISSUE THREAD

**Issue by philippilievski** [vuejs/language-tools#4465]
### Vue - Official extension or vue-tsc version

v2.0.21

### VSCode version

1.90.0

### Vue version

3.4.21

### TypeScript version

5.4.5

### System Info

```shell
OS: Ubuntu 22.04.4 LTS
IDE: VSCode and Nvim
Browser: Chrome Version 125.0.6422.141
```

### Steps to reproduce

1. Open terminal and create a new project:
npm create vue@latest
2. Add Typescript when asked for it
3. Run npm install in project directory
4. Start dev server by running: npm run dev
5. Purposefully generate error in code in my example i typed into Homeview.vue and save the file:
```
<script setup lang="ts">
import TheWelcome from '../components/TheWelcome.vue'
this is an error generated on purpose ; = ";";
</script>
```
6. Now the console should not show any error
![image](https://github.com/vuejs/language-tools/assets/52157275/07b322c6-47c6-4c1d-ae74-db0e998c2e1b)
7. Upon opening the application in the browser the error gets displayed (only in browser)
8. Only upon page refresh the terminal now also displays the error

### Any additional comments?

I wanted to try out Vue by creating my first application and when following the tutorial i soon realised that it is not working as expected.

I should also say that i have tried the same thing in Neovim and there it also doesn't work as explained above.
I installed LSP's in both environments.

**Comment by davidmatter** [comment]
This is a topic that rather concerns vite or the vite vue plugin - you might want to move this issue. This issue has little to do with the LSP.

**Comment by philippilievski** [comment]
Will do thank you!
