### ISSUE TITLE
infer type in template unexpectedly after v2.0.19

### ISSUE THREAD

**Issue by zcf0508** [vuejs/language-tools#4470]
### Vue - Official extension or vue-tsc version

2.0.21

### VSCode version

1.91.0-insiders

### Vue version

3.4.27

### TypeScript version

latest

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13490F
    Memory: 2.33 GB / 31.82 GB
  Binaries:
    Node: 20.14.0 - ~\.version-fox\cache\nodejs\current\node.EXE
    Yarn: 1.22.22 - ~\.version-fox\cache\nodejs\current\yarn.CMD
    npm: 10.7.0 - ~\.version-fox\cache\nodejs\current\npm.CMD
    pnpm: 9.1.4 - ~\.version-fox\cache\nodejs\current\pnpm.CMD
    bun: 1.1.12 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.1
```

### Steps to reproduce

```
"vue.server.hybridMode": true
```

update `vue.volar` to 2.0.20 or 2.0.21

---
2.0.19
![image](https://github.com/vuejs/language-tools/assets/21942252/4aba999a-99a4-4495-924a-b08d50a99097)

2.0.21
![image](https://github.com/vuejs/language-tools/assets/21942252/e6cfc0b6-a4e5-4a53-88cf-a989fa9b7f18)

### Link to minimal reproduction

https://github.com/zcf0508/chattts-webui/blob/master/pages/tasks.vue#L42

**Comment by so1ve** [comment]
Could you please try replacing `{{ tasks }}` with `{{ __VLS_ctx }}` then show me the result when you hover on it?

**Comment by zcf0508** [comment]
![image](https://github.com/vuejs/language-tools/assets/21942252/11238104-9cd8-4ea3-978e-dc44d893c1a9)

**Comment by timozander** [comment]
+1 having the same issue in a Nuxt app
