### ISSUE TITLE
The latest version is missing the ability to prompt custom components.

### ISSUE THREAD

**Issue by antonySee** [vuejs/language-tools#4472]
### Vue - Official extension or vue-tsc version

2.0.21

### VSCode version

1.90.1

### Vue version

3.4.27

### TypeScript version

4.5.4

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 2.19 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 126.0.6478.61
    Safari: 17.5
```

### Steps to reproduce

Create a new component and add properties. Introduced in another file with no attribute hint;

### Any additional comments?

In the latest version, properties of custom components are not prompted; I remember the old version has always been available, but also very useful, will greatly improve efficiency. But it seems that the latest version will not prompt! I tried to install every old version and found that it didn't work. Is there any configuration I need to change? (Figure 1 is the problematic version, Figure 2 is the desired version)
![image](https://github.com/vuejs/language-tools/assets/90954223/28a861bf-29ef-4c1a-abb5-ffd0afded05c)
![image](https://github.com/vuejs/language-tools/assets/90954223/a51bd827-84d3-412a-ba78-eb08b1ef0704)

**Comment by antonySee** [comment]
？？？

**Comment by so1ve** [comment]
We don't support ts 4.5.4
