### ISSUE TITLE
Go to definition always go to the xxx.d.ts file that has "declare module '*.vue'".

### ISSUE THREAD

**Issue by Enaium** [vuejs/language-tools#4486]
### Vue - Official extension or vue-tsc version

v2.0.21

### VSCode version

1.90.2 (user setup)

### Vue version

3.4.29

### TypeScript version

5.4.5

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 AMD Ryzen 3 3200G with Radeon Vega Graphics
    Memory: 4.49 GB / 13.93 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.68)
    Internet Explorer: 11.0.22621.3527
```

### Steps to reproduce

1. create a vue project by `yarn create vue`

![](https://github.com/vuejs/language-tools/assets/32991121/4ea78723-7d7e-4b8d-b0fd-45628398caef)

2. create a `shims.d.ts`

declare module '*.vue'

![](https://github.com/vuejs/language-tools/assets/32991121/7e4c3f62-0ccc-44df-bb2f-36368fb81b07)

3. remove the `lang=ts`

![](https://github.com/vuejs/language-tools/assets/32991121/92694d25-3f4c-4998-9eea-d3e26d2e639f)

4. reopen vscode

5. Go to definition

![](https://github.com/vuejs/language-tools/assets/32991121/5cc1e33f-e853-4a40-925a-e6bd4c9e0292)

6. Go to the `xxx.d.ts` file

![](https://github.com/vuejs/language-tools/assets/32991121/6e46a880-70c2-4847-b965-d1b4cececb8d)

### Any additional comments?

Go to definition will go to the from file when I go to definition by the from file. 

![](https://github.com/vuejs/language-tools/assets/32991121/c4d49a4b-8712-4efe-a776-c5e7cd14e3fe)

![](https://github.com/vuejs/language-tools/assets/32991121/6d6b6623-c3e7-4685-b1ed-bcb969063119)

**Comment by so1ve** [comment]
This is expected. To change the behavior just remove that shim file.

**Comment by Enaium** [comment]
> This is expected. To change the behavior just remove that shim file.

This will throw "implicitly has an 'any' type" when I build the project

**Comment by RayGuo-ergou** [comment]
Not sure if 100% related, but can you try to add export{}?

**Comment by Enaium** [comment]
> Not sure if 100% related, but can you try to add export{}?

Add to the `xxx.d.ts`?

![](https://github.com/vuejs/language-tools/assets/32991121/618eb6b8-253c-4136-8022-5f864fd453ae)

![](https://github.com/vuejs/language-tools/assets/32991121/14ec56a1-197e-4d14-9df8-75941d6d2bba)

**Comment by RayGuo-ergou** [comment]
Yeah probably not what i thought about, it might be the tsconfig, can you try to add `"allowJs": true,` in your `tsconfig.app.json`?

under `compilerOptions`

**Comment by Enaium** [comment]
> Yeah probably not what i thought about, it might be the tsconfig, can you try to add `"allowJs": true,` in your `tsconfig.app.json`?
> 
> under `compilerOptions` then remove `shim.d.ts`

Thanks
