### ISSUE TITLE
Global components lost types with typescript 5.5

### ISSUE THREAD

**Issue by KazariEX** [vuejs/language-tools#4488]
### Vue - Official extension or vue-tsc version

2.0.21

### VSCode version

1.90.0-insider

### Vue version

3.4.29

### TypeScript version

5.5.2

### System Info

```shell
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
  Memory: 20.74 GB / 31.87 GB
Binaries:
  Node: 22.0.0 - D:\Program Files\nodejs\node.EXE
  Yarn: 1.22.22 - D:\Program Files\node\node_global\yarn.CMD  
  npm: 10.8.0 - D:\Program Files\nodejs\npm.CMD
  pnpm: 9.4.0 - D:\Program Files\node\node_global\pnpm.CMD
Browsers:
  Edge: Chromium (126.0.2592.61)
  Internet Explorer: 11.0.19041.4355
```

### Steps to reproduce

直接看组件悬停提示

### Link to minimal reproduction

https://github.com/KazariEX/nuxt4-minimal

### Any additional comments?

使用 Nuxt 4 默认的 ``srcDir: "app/"`` 后，``<template>`` 内的所有组件丢失类型定义

**Comment by so1ve** [comment]
Does ts 5.4 work?

**Comment by KazariEX** [comment]
It works.

**Comment by so1ve** [comment]
https://github.com/microsoft/TypeScript/issues/58960

**Comment by 7iomka** [comment]
Same issue with all my components....
5.4 works fine

**Comment by so1ve** [comment]
Fixed by #4492. Please upgrade to 2.0.22.

**Comment by warflash** [comment]
@so1ve Is 2.0.22 published on the marketplace yet? Or do we need to sideload it from somewhere?
For me the most recent version [is 2.0.21](https://marketplace.visualstudio.com/items?itemName=Vue.volar&ssr=false#version-history)
![image](https://github.com/vuejs/language-tools/assets/22006082/c6774b93-a6ef-4876-83e3-1333d47b8e09)
Thanks!

**Comment by johnsoncodehk** [comment]
I think I executed the publish command locally, and I've seen other people have issues with releases not showing up in Marketplace, maybe it's the same issue.
https://github.com/microsoft/vscode-vsce/issues/985

**Comment by warflash** [comment]
Now 2.0.22 shows up for me and I was able to update, appreciate the quick response and fix @johnsoncodehk!
