### ISSUE TITLE
.vue file with js block comment will not fold/collapse if it's directly before an export default statement

### ISSUE THREAD

**Issue by jmalatia** [vuejs/language-tools#4496]
### Vue - Official extension or vue-tsc version

Vue - Official v2.0.22, 

### VSCode version

1.90.2

### Vue version

3.4.29

### TypeScript version

5.4.5

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
    Memory: 2.86 GB / 15.92 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 126.0.6478.114
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
```

### Steps to reproduce

In a .vue file with a javascript block comment directly before `export default`, the comment can not be folded/collapsed in vscode.  It make no difference if it's a `<script>`, `<script lang="ts">` or `<script lang="js">` tag

The below code will not fold (or offer the arrow to collapse when hovering the line):
```
<script lang="ts">
/**
 * @name 
 * @description 
 */
export default defineComponent({
    
});
</script>
```
![6](https://github.com/vuejs/language-tools/assets/5606334/9131198d-2de3-4c4d-98bf-f31f21e46ed1)

---

However, if you add a line of js code between the comment and the export, the comment will fold as expected (and offer the arrow when hovering over the line):
```
<script lang="ts">
/**
 * @name 
 * @description 
 */
const a = "";
export default defineComponent({
    
});
</script>
```
![4](https://github.com/vuejs/language-tools/assets/5606334/4b823047-7918-4871-8b32-f02520fc0e3c)

**Comment by davidmatter** [comment]
This seems to be caused by vscode. The same behavior can be found when you edit a common html file without using the vue extension. 
<img width="245" alt="image" src="https://github.com/vuejs/language-tools/assets/2319523/a9553857-13d6-48b6-a590-28c0b70a4be2">
