### ISSUE TITLE
Volar Support Vue File workspace/DidRename or workspace/WillRename in Neovim

### ISSUE THREAD

**Issue by chaozwn** [vuejs/language-tools#4500]
### What problem does this feature solve?

Now I can rename files in vscode and reference files in other vue files to synchronize the name change. However, with the same configuration, my neovim did not work at all.

<img width="970" alt="image" src="https://github.com/vuejs/language-tools/assets/51357674/fc3803d8-6076-4ebb-9441-ab90266cd7bd">

### What does the proposed solution look like?

neovim support  workspace/DidRename or workspace/WillRename

**Comment by RayGuo-ergou** [comment]
This repo does not have any neovim plugin, to achieve this you should config yourself. See how folke did it in `lazyvim/lazyvim` repo

**Comment by chaozwn** [comment]
> This repo does not have any neovim plugin, to achieve this you should config yourself. See how folke did it in `lazyvim/lazyvim` repo

From my point of view, this is the function that volar should support as an lsp. For example, tsserver can automatically modify other references when rename files are given, and volar should also support when modifying vue files.

**Comment by chaozwn** [comment]
this is vtsls server_capabilities.workspace.fileOperations.didRename
![image](https://github.com/vuejs/language-tools/assets/51357674/720ebcbf-32b7-456a-b44d-15d38c8e0130)

**Comment by chaozwn** [comment]
this is volar server_capabilities.workspace.fileOperations.didRename

![image](https://github.com/vuejs/language-tools/assets/51357674/ec6ddff7-282c-4862-bed5-25f21724f248)

**Comment by chaozwn** [comment]
> This repo does not have any neovim plugin, to achieve this you should config yourself. See how folke did it in `lazyvim/lazyvim` repo
I have found the perfect solution to use vtsls to synchronize vue files when renaming.

```lua
        vtsls = {
          on_attach = function(client, _)
            client.server_capabilities = utils.extend_tbl(client.server_capabilities, {
              workspace = {
                didChangeWatchedFiles = { dynamicRegistration = true },
                fileOperations = {
                  didRename = {
                    filters = {
                      {
                        pattern = {
                          glob = "**/*.{ts,cts,mts,tsx,js,cjs,mjs,jsx,vue}",
                        },
                      },
                    },
                  },
                },
              },
            })
end
```

**Comment by chaozwn** [comment]
> This repo does not have any neovim plugin, to achieve this you should config yourself. See how folke did it in `lazyvim/lazyvim` repo

The renaming problem is solved perfectly.
