### ISSUE TITLE
v2.0.22 Type detection failed

### ISSUE THREAD

**Issue by AAABingBing** [vuejs/language-tools#4502]
### Vue - Official extension or vue-tsc version

2.0.22

### VSCode version

1.90.2

### Vue version

3.4.21

### TypeScript version

5.5.2

### Steps to reproduce

Configure `compilerOptions. types: ["element plus/global"]` in tsconfig
Using Vue - Official v2.0.22 component type detection failed, code snippet not highlighted

Switching to v2.0.21 means everything is normal

**Comment by davidmatter** [comment]
Duplicate: https://github.com/vuejs/language-tools/issues/4501

Workaround: Add `@vue/runtime-core` as a dependency and add this to your `tsconfig.json`.
```json
  "vueCompilerOptions": {
    "lib": "@vue/runtime-core",
},
```
