### ISSUE TITLE
Missing ```css``` class references

### ISSUE THREAD

**Issue by teleskop150750** [vuejs/language-tools#4511]
### Vue - Official extension or vue-tsc version

2.0.22

### VSCode version

1.90

### Vue version

3.4.30

### TypeScript version

5.4

### Steps to reproduce

-

### Any additional comments?

Hello. Thank you for the wonderful work.

Is it possible to somehow return the amount of "reference" above the class in scoped css.

It helped a lot to quickly find unused styles.

![image](https://github.com/vuejs/language-tools/assets/62594983/21097668-383f-4015-b2a4-f9bc810f4572)

Duplicate of [#4311](https://github.com/vuejs/language-tools/issues/4311)  [#3938](https://github.com/vuejs/language-tools/issues/3938)

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/pull/4364
