### ISSUE TITLE
Typescript v-model defined types missing

### ISSUE THREAD

**Issue by matvejs16** [vuejs/language-tools#4512]
### Vue - Official extension or vue-tsc version

2.0.22

### VSCode version

1.91.0-insider

### Vue version

3.4.30

### TypeScript version

5.5.2

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 23.30 GB / 31.87 GB
Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.EXE
Browsers:
    Edge: Chromium (126.0.2592.68)
    Internet Explorer: 11.0.22621.3527
```

### Steps to reproduce

1. Create vue component file with code:
```typescript
const opened = defineModel('opened', {
    type: Boolean,
    default: true
});
```
2. Import and use in ``template`` tag created component in other vue file
```vue
<BottomSlider v-model:opened="opened"></BottomSlider>
```
3. No typescript hints for ``v-model:opened``
![image](https://github.com/vuejs/language-tools/assets/74150728/bf7fcb41-b8a8-4dff-adc5-280075319d14)

### Link to minimal reproduction

https://play.vuejs.org/#eNp9UstOwzAQ/BXLl1KpNEJwCmklinoAiYdoj75EySa4OLaxN6Goyr+zTpQSBPSWzIx3Z2f3wG+snTc18JgnCJVVKcJSaMaSlUE01UbJHBxrziuTg4qNBQ35QnAEj4Ivk2gso4dJNKpCvz5z0iLzgLUlRFbWOGQH5qBgLSucqdiE2k+O1I+2PT+Pbk3VuSSZ0JnRHlkwwBahztnFNPTtO1EPPuPoSVTIcr7zRtNohzCR4BmVkQrck0VJRQSPWccELlXKfNx3GLoaZgOevUL29ge+8/uACf7swINrQPAjh6krgeIJ9HrzCHv6PpIUZK1IfYJ8AW9UHTz2slWtc7I90nVu77rEpC63fr1H0H4YKhgNyrbTC07JhQT/G/3b7uX8qnsndEspDqn/vo1cNsttWEBI1GjQmEQBO71/plJdhtuh9sT2e+wvijaZQyE1PIQzO5v06GTWm8RPCzFdhlGQ6m4mB++1dJAPs7bT69EN8PYL6ZT3sg==

### Any additional comments?

This behaviour happens even if you don't import created component and use it as global component with this file:
```typescript
import bottomSlider from "@/components/bottomSlider.vue"

declare module 'vue' {
    export interface GlobalComponents {
        BottomSlider: typeof bottomSlider;
    }
}
```

As you can see in minimal reproduction link, there is Vue error that types are different, but typescript says nothing

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/vuejs/language-tools/assets/33137074/ea86f10b-4d0a-4858-9abc-4322fd203432)

It seems correct from your reproduction link, am i missing anything?

**Comment by so1ve** [comment]
This playground hasn't upgraded to volar 2 yet

**Comment by RayGuo-ergou** [comment]
> This playground hasn't upgraded to volar 2 yet

Can confirm that:
![image](https://github.com/vuejs/language-tools/assets/33137074/c1f4d948-d3c7-46cf-8717-1be3b14361e9)

with: language server `2.0.21`

**Comment by matvejs16** [comment]
> This playground hasn't upgraded to volar 2 yet

I used it only because there is same bahaviour like in VSCode with ``Vue - Official`` installed

**Comment by matvejs16** [comment]
> > This playground hasn't upgraded to volar 2 yet
> 
> Can confirm that: ![image](https://private-user-images.githubusercontent.com/33137074/343993987-c1f4d948-d3c7-46cf-8717-1be3b14361e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Mzc4MTIsIm5iZiI6MTcxOTUzNzUxMiwicGF0aCI6Ii8zMzEzNzA3NC8zNDM5OTM5ODctYzFmNGQ5NDgtZDNjNy00NmNmLTg3MTctMWJlM2IxNDM2MWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAxMTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NzZiMjA5MDc3YzUzN2Y4MWNjZDAwYzcwODMxMzM5MThjNWRjNTNhMjU2ZDg0NGVjYTM3YTZhMDRmMTEwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PxnEv1faRQSvpi6MkKxJv51ZIaYdGTuH8XNeHWy98Zk)
> 
> with: language server `2.0.21`

Can't get same typescript hint in VSCode with latest (v2.0.22) ``Vue - Official`` installed

**Comment by RayGuo-ergou** [comment]
As the language server works okay, I reckon it's something in your VScode configuration. There's few things you can check

1. Is the hybrid mode enabled?
2. Did you pass the correct path of typesciprt, ( or if using workspace version, is that `^5` ?)

**Comment by matvejs16** [comment]
> As the language server works okay, I reckon it's something in your VScode configuration. There's few things you can check
> 
> 1. Is the hybrid mode enabled?
> 2. Did you pass the correct path of typesciprt, ( or if using workspace version, is that `^5` ?)

1. Hybrid mode is on ``auto``
2. (Not sure what do you mean)

I can also mention that other typescript related hints/errors work as expected.
But maybe there is problem with typescript, I have installed [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) plugin in VSCode

**Comment by RayGuo-ergou** [comment]
Okay I guess `5.6` might be the issue as even minor update of typescript change lot of things.

But can you try to use this syntex to see if it works?

```vue
defineModel<boolean>('opend')
```

see: https://vuejs.org/api/sfc-script-setup.html#usage-with-typescript

**Comment by matvejs16** [comment]
> Okay I guess `5.6` might be the issue as even minor update of typescript change lot of things.
> 
> But can you try to use this syntex to see if it works?
> 
> ```ts
> defineModel<boolean>('opend')
> ```
> 
> see: https://vuejs.org/api/sfc-script-setup.html#usage-with-typescript

Yea, that worked ✅
So I will use this syntax to prevent this issue to happen again, but is it still considered as an issue?

**Comment by RayGuo-ergou** [comment]
> but is it still considered as an issue?

Maybe can keep this open? 🤔

as `defineProps` does support infer type from parameter, e.g.
```ts
defineProps({
  msg: {
    type: String,
    required: true,
  },
})
```

Consider `defineModel` is fairly new, this could be one thing to improve.

**Comment by matvejs16** [comment]
> > but is it still considered as an issue?
> 
> Maybe can keep this open? 🤔
> 
> as `defineProps` does support infer type from parameter, e.g.
> 
> ```ts
> defineProps({
>   msg: {
>     type: String,
>     required: true,
>   },
> })
> ```
> 
> Consider `defineModel` is fairly new, this could be one thing to improve.

Agree, let's keep this open.
Btw thanks for fast responses 🫡

**Comment by yinkeli** [comment]
![image](https://github.com/vuejs/language-tools/assets/86509580/3db8fa41-dd90-4321-a5c7-a1fecedcf566)
In the earlier version, the component type can be read and a code prompt is displayed. In this version, the component type cannot be read.

**Comment by RayGuo-ergou** [comment]
That's irrelevant. Tracking your issue in https://github.com/vuejs/language-tools/issues/4501
