### ISSUE TITLE
Using @ to obtain directory vscode in Vue's template template without path prompt

### ISSUE THREAD

**Issue by lcyhyl** [vuejs/language-tools#4514]
### Vue - Official extension or vue-tsc version

v2.0.24

### VSCode version

1.90.2

### Vue version

3x

### TypeScript version

5x

### Steps to reproduce

Using @ to obtain directory vscode in Vue's template template without path prompt

**Comment by davidmatter** [comment]
Hi @lcyhyl not sure what you mean
> Using @ to obtain directory vscode in Vue's template template without path prompt

Please be more specific and define what happens and what you would expect.

**Comment by lcyhyl** [comment]
expect: 
![image](https://github.com/vuejs/language-tools/assets/112603643/e7b94998-7def-437a-bffc-cad63a869e2a)
now:
![image](https://github.com/vuejs/language-tools/assets/112603643/165263d4-f572-45c5-ba2b-bce4666cdf38)

Previously, there was no need to install additional plugins to read the directory defined by @. Now, third-party plugins need to be installed to achieve this

**Comment by davidmatter** [comment]
Right, I can reproduce this one.

**Comment by so1ve** [comment]
Probably related to https://github.com/vuejs/language-tools/issues/3460

**Comment by KermanX** [comment]
Let's track #3460. There is also a workaround there.
