### ISSUE TITLE
Vue2 <template> get "any" type when using custom component

### ISSUE THREAD

**Issue by Jibacat** [vuejs/language-tools#4518]
### Vue - Official extension or vue-tsc version

2.0.24

### VSCode version

1.90.2

### Vue version

2.7.10

### TypeScript version

5.4.5

### System Info

```shell
System:
    OS: macOS 12.7.3
    CPU: (8) x64 Apple M2
    Memory: 26.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    npm: 6.14.18 - /usr/local/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 15.6.1
```

### Steps to reproduce

<img width="972" alt="image" src="https://github.com/vuejs/language-tools/assets/28664253/48adb5ac-e474-408c-98e8-23235e05cad2">

<img width="903" alt="image" src="https://github.com/vuejs/language-tools/assets/28664253/37edc1e8-2aba-455a-8be5-ef6652020923">

<img width="603" alt="image" src="https://github.com/vuejs/language-tools/assets/28664253/1457b2ea-00dd-42b2-a37c-ff39d571c99c">

I get "any" type on custom component "HelloWorld" in template.

How can I get exact type instead of "any"?

**Comment by TerrorSquad** [comment]
I have the same issue with Nuxt 3.11.2 and Typescript 5.4.5

**Comment by erwanjugand** [comment]
Same issue with Nuxt 2

**Comment by zziilii** [comment]
I have the same issue, I've been waiting for this feature for a long time, praying for it

**Comment by TerrorSquad** [comment]
> Same issue with Nuxt 2, disable `hybrid mode` fixes the problem

This worked for me.
Also, setting the hybrid mode to `typescriptPluginOnly` also worked.

So, the workaround for now is to set the setting `vue.server.hybridMode` to either `typescriptPluginOnly` or `false`.

**Comment by Jibacat** [comment]
I try to disable hybrid mode, but it seems not working for me.

**Comment by Kanade-Lu** [comment]
this issue seems use vue-property-decorator problem，if you use setup model with ts, type will work as expected.

**Comment by GabrielHangor** [comment]
> this issue seems use vue-property-decorator problem，if you use setup model with ts, type will work as expected.

True
