### ISSUE TITLE
Server crashes every time I try to make a <style>

### ISSUE THREAD

**Issue by bklik** [vuejs/language-tools#4520]
### Vue - Official extension or vue-tsc version

v2.0.24

### VSCode version

1.90.2

### Vue version

^3.4.18

### TypeScript version

^4.5.4

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 25.09 GB / 31.01 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
Binaries:
    Node: 20.15.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
Browsers:
    Chrome: 126.0.6478.126
```

### Steps to reproduce

Create a component and start typing a <style lang="scss" scoped> tag.

### What is expected?

The vscode extension doesn't crash.

### What is actually happening?

The vscode extension crashes with the above error:

TypeError: Cannot read properties of undefined (reading 'label')
    at Dte (/home/user/.vscode/extensions/vue.volar-2.0.24/dist/server.js:13571:2319)
    at Object.provideCompletionItems (/home/user/.vscode/extensions/vue.volar-2.0.24/dist/server.js:13571:1995)
    at async m (/home/user/.vscode/extensions/vue.volar-2.0.24/dist/server.js:2:48796)
    at async Object.getCompletionItems (/home/user/.vscode/extensions/vue.volar-2.0.24/dist/server.js:2:49560)
    at async /home/user/.vscode/extensions/vue.volar-2.0.24/dist/server.js:66:20287
    at async Timeout.<anonymous> (/home/user/.vscode/extensions/vue.volar-2.0.24/dist/server.js:66:26830)

Node.js v20.9.0
[Error - 2:27:59 PM] Server process exited with code 1.
[Error - 2:27:59 PM] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

### Any additional comments?

If I revert to v2.0.22 everything works as expected.

**Comment by Dedicatus546** [comment]
same problem here.

![image](https://github.com/vuejs/language-tools/assets/48575405/813f305b-1c54-4021-9883-947226d883ee)

**Comment by RayGuo-ergou** [comment]
It also happened to me when create a new vue file.

**Comment by zoo7314** [comment]
facing same issue.

**Comment by kuolun** [comment]
same issue

**Comment by ffox1055** [comment]
![Screenshot 2024-07-03 093250](https://github.com/vuejs/language-tools/assets/73806791/1a82ef8d-3f10-47dc-9902-f208e88ef0ed)

same issue

**Comment by so1ve** [comment]
Related to https://github.com/vuejs/language-tools/blob/3194078ba29d0933b250c5d5715736a5b4d7ff78/packages/language-service/lib/plugins/vue-sfc.ts#L182?

**Comment by firmianaQ** [comment]
我以为电脑问题呢 还真是插件啊

**Comment by matamune94** [comment]
Same too when add new teamplate tag
