### ISSUE TITLE
type-check shows type errors twice

### ISSUE THREAD

**Issue by Peanut4287** [vuejs/language-tools#4522]
### Vue - Official extension or vue-tsc version

2.0.24

### VSCode version

1.90.2

### Vue version

3.4.31

### TypeScript version

5.4.5

### System Info

```shell
System:
  OS: Linux 5.15 Linux Mint 21.3 (Virginia)
  CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
  Memory: 15.57 GB / 30.57 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
  npm: 10.8.1 - ~/.nvm/versions/node/v20.14.0/bin/npm
Browsers:
  Chrome: 126.0.6478.126
```

### Steps to reproduce

1. Create a new Vue project with `npm create vue@latest`
   1. `Add TypeScript?` `Yes`
   2. `Add Vitest for Unit Testing?` `Yes`
3. Add code with a type error somewhere in your code (e.g. in `main.ts`)

```typescript
const foo: number = "bar";
```

4. Call `npm run type-check`
5. Check the output

```
> vue-project-default@0.0.0 type-check
> vue-tsc --build --force

src/main.ts:16:7 - error TS2322: Type 'string' is not assignable to type 'number'.

16 const foo: number = 'bar'
         ~~~

src/main.ts:16:7 - error TS2322: Type 'string' is not assignable to type 'number'.

16 const foo: number = 'bar'
         ~~~


Found 2 errors.
```

6. Observe the error showing twice

### What is expected?

I expect the error only showing once.

### What is actually happening?

The error is showing twice.

### Any additional comments?

It seems like the problem lies somewhere in the TypeScript configuration. When using the `npm create vue@latest` command, the auto-created `tsconfig.json` looks like this

```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```

The third file `tsconfig.vitest.json` itself extends the second file

```json
{
  "extends": "./tsconfig.app.json"
}
```

If `tsconfig.vitest.json` is removed from `tsconfig.json`, the duplicate errors disappear. So something in those nested TypeScript configs leads to these duplicate errors.

**Comment by davidmatter** [comment]
@Peanut4287 That's standard behavior of typescript. e.g.: Create a typescript-only project and run

`tsc --build --dry`

[Build builds all projects referenced](https://www.typescriptlang.org/docs/handbook/compiler-options.html#:~:text=%2D%2D-,build,-boolean) in `tsconfig.json`, hence you will see the following output:
```
> tsc --build "--dry"

[12:10:24 AM] A non-dry build would build project '/Users/$USER/Code/vue-lang-tools/4522/tsconfig.node.json'

[12:10:24 AM] A non-dry build would build project '/Users/$USER/Code/vue-lang-tools/4522/tsconfig.app.json'
```
