### ISSUE TITLE
syntax highlighting problem when use four <>

### ISSUE THREAD

**Issue by Kanade-Lu** [vuejs/language-tools#4524]
### Vue - Official extension or vue-tsc version

2.0.19

### VSCode version

1.90.2 (Universal)

### Vue version

3.4.31

### TypeScript version

5.5.3(latest)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 102.17 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 7.33.7 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 16.5.1
```

### Steps to reproduce

![image](https://github.com/vuejs/language-tools/assets/48433677/d8cc6c4b-6695-46cf-a242-21abb289fde1)

### What is expected?

not warning

### What is actually happening?

when use four <> , syntax highlighting will warning

### Link to minimal reproduction

https://play.vuejs.org/#eNqNUcFKAzEQ/ZWQSxVKi9RT2S5UqVAPWqo3IxK20zU1m4TJ7FpZ9t+d3draghRzyrw3eXlvppbTEAZVCXIsk5ihCSQiUBmE1S6fKElRyVQ5UwSPJGqBoDMyFYhGrNEXosdve8w7AlzrDMSdx2JOUCxLC6JWTrlGucy7SAIZimJy0EgWGslomywh87hKIqFxef9E4uU1TdOLurk8EfmPyhRRfyXHWqz0I5UMd1k5GRdMB6sJuEqGR4Xsc3z+dW3ywSZ6xzPiQEIomfkiGAv4GMiwKyXHbVTBR0ltrf+87zDCEvp7PHuH7OMPfBO3LabkAiECVqDkgSONOdCOnj09wJbvB7LwKw51llxC9LZsPe7abkq3YttHfZ3bebddntpznG0JXNyHao22nU3XryQv+/ZM9F+7o8F19463z1N8qwBbTR4gE4PRlWy+Ab+O14I=

**Comment by so1ve** [comment]
Could you please list your vscode extensions?

**Comment by Kanade-Lu** [comment]
> Could you please list your vscode extensions?

antfu.unocss@0.61.0
asciidoctor.asciidoctor-vscode@3.3.1
be5invis.vscode-custom-css@7.2.2
christian-kohler.path-intellisense@2.9.0
dakshmiglani.hex-to-rgba@1.0.0
dariofuzinato.vue-peek@1.0.2
dbaeumer.vscode-eslint@3.0.10
donjayamanne.githistory@0.6.20
eamodio.gitlens@15.1.0
ecmel.vscode-html-css@2.0.10
esbenp.prettier-vscode@10.4.0
formulahendry.auto-rename-tag@0.1.10
gruntfuggly.todo-tree@0.0.226
kisstkondoros.vscode-codemetrics@1.26.1
lokalise.i18n-ally@2.12.0
ms-ceintl.vscode-language-pack-zh-hans@1.91.2024070309
ms-vscode.js-debug-nightly@2024.7.317
mxsdev.typescript-explorer@0.4.2
nondanee.vsc-netease-music@0.0.44
pbkit.vscode-pbkit@0.0.7
pucelle.vscode-css-navigation@1.14.1
sdras.vue-vscode-snippets@3.1.1
simonhe.common-intellisense@0.1.48
simonsiefke.svg-preview@2.8.3
vscode-icons-team.vscode-icons@12.8.0
vue.volar@2.0.19
whensunset.chatgpt-china@8.7.8
withfig.fig@0.0.7
wowbox.code-debuger@1.0.0
yoavbls.pretty-ts-errors@0.5.4
yxl.cloudmusic@9.22.0

**Comment by johnsoncodehk** [comment]
Thanks for the report, but this issue can also be reproduced in .ts files, so this is an upstream issue. Please report it upstream.
