### ISSUE TITLE
Please keep my region state as it is, do not unfold it unexpected

### ISSUE THREAD

**Issue by tsdd** [vuejs/language-tools#4530]
### Vue - Official extension or vue-tsc version

2024-07-05, 09:03:05

### VSCode version

1.91.0

### Vue version

3.3.11

### TypeScript version

4.5.5

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 6.28 GB / 15.73 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
```

### Steps to reproduce

1. unfold template
2. type something in setup area
3. the folded template now is unfold

### What is expected?

keep it as it is

### What is actually happening?

i do not know what to write

**Comment by davidmatter** [comment]
Can't reproduce. Please update your typescript version, define which extension version you're on, and add a more complete description how to reproduce this issue. Please also include a list of installed extensions when you create a new issue
