### ISSUE TITLE
"Go to definition" No Support static resources (png、svg...)

### ISSUE THREAD

**Issue by fuxichen** [vuejs/language-tools#4533]
### Vue - Official extension or vue-tsc version

v2.0.6

### VSCode version

1.91.0

### Vue version

latest

### TypeScript version

latest

### Steps to reproduce

1. visit a website https://github.dev/johnsoncodehk/volar-starter
2. edit `tsconfig.json`、 `vite.config.ts` Configure aliases "@".
![image](https://github.com/vuejs/language-tools/assets/17411462/950db781-230f-440e-8030-2909ba095db9)
![image](https://github.com/vuejs/language-tools/assets/17411462/3e9e1177-7273-4897-8c69-714e0d318d98)
3. edit `app.vue`
```diff
- import HelloWorld from './components/HelloWorld.vue'
+ import HelloWorld from '@/components/HelloWorld.vue'
+ import iconLogo from '@/assets/logo.png'
```
![image](https://github.com/vuejs/language-tools/assets/17411462/1b4daddb-12b7-440f-a926-e9e8f16e8717)

4. Use 'Ctrl'+'left mouse button' or 'F12' to click on two reference paths separately

`.vue` Correctly go to defined position. but `.png`  redirected to ` client.d.ts`

### What is expected?

`. png ` Jump and open file resources

### What is actually happening?

"Go to definition" No Support static resources (png、svg...)

**Comment by so1ve** [comment]
What is client.d.ts

**Comment by fuxichen** [comment]
> What is client.d.ts

vite/client.d.ts。 It is in the vite npm package

**Comment by so1ve** [comment]
I'd argue this is typescript's behavior. You may re produce this issue in a .ts file

**Comment by fuxichen** [comment]
> I'd argue this is typescript's behavior. You may reproduce this issue in a .ts file

But I found that the '.vue' file to jump definition is implemented by the 'Vue - Official' plug-in. Only by enabling the plug-in can the '.vue' file definition be jumped. typescript should only handle '.ts' files

**Comment by RayGuo-ergou** [comment]
> typescript should only handle '.ts' files

Your assumption is wrong see https://www.typescriptlang.org/docs/handbook/modules/reference.html

**Comment by so1ve** [comment]
We follow typescript's behaviors. We don't modify them. If you still jumps to `client.d.ts` in a typescript file, it's not our fault then.

BTW this is how typescript's `declare module` works as reference by @RayGuo-ergou
