### ISSUE TITLE
type check on component props when route params are used as props

### ISSUE THREAD

**Issue by michaelcozzolino** [vuejs/language-tools#4547]
### What problem does this feature solve?

i have the following route:
```
{
        path:      'path/:param,
        name:      'name',
        component: () => import('MyComponent.vue'),
       props: true,
 },
```
 in MyComponent.vue 
```
<script setup lang="ts">
interface Props {
      param: string
}

</script>
```
I would like that if you are trying to have a type param that is different from string, a tsc error will be shown.

same behaviour in case a callback is given to props.

so that 

```
<script setup lang="ts">
interface Props {
      param: number
}
</script>
```

is not allowed when props: true

### What does the proposed solution look like?

The type of the props of the Component should be checked if the props in the specific route is set to true or it has a callback

**Comment by davidmatter** [comment]
Check https://router.vuejs.org/guide/advanced/typed-routes
