### ISSUE TITLE
Missing support for `[]`-enclosed lists in SCSS styles

### ISSUE THREAD

**Issue by Atulin** [vuejs/language-tools#4584]
### Vue - Official extension or vue-tsc version

Webstorm 2024.2 Beta

### VSCode version

None

### Vue version

2.6.14

### TypeScript version

5.4.5

### System Info

```shell
❯ bunx envinfo --system --binaries --browsers

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 4.36 GB / 15.95 GB
  Binaries:
    Node: 21.6.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.18 - ~\.bun\bin\bun.EXE
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.19041.4355
```

### Steps to reproduce

```vue
<style lang="scss">
@use "sass:list";

.selector {
    $colors: "#69ffae", "#1ae5b5", "#5193da", "#9f6cda", "#dac669", "#d48943";
    color: list.nth($colors, 2);

    $colors: ["#69ffae", "#1ae5b5", "#5193da", "#9f6cda", "#dac669", "#d48943"];
    color: list.nth(["#69ffae", "#1ae5b5", "#5193da", "#9f6cda", "#dac669", "#d48943"], 2);
}
</style>
```

### What is expected?

No errors

### What is actually happening?

Errors
![image](https://github.com/user-attachments/assets/ba99f0fa-3399-44da-9c06-7a9da51f3c61)
![image](https://github.com/user-attachments/assets/0f4721d1-e4a3-4b9c-b075-57d5c2722ee0)

### Any additional comments?

Webstorm issue: https://youtrack.jetbrains.com/issue/WEB-68090/SCSS-vue-language-server-2.0.22-missing-support-for-enclosed-lists

**Comment by johnsoncodehk** [comment]
This needs to be supported by https://github.com/microsoft/vscode-css-languageservice, this problem can be reproduced in *.scss files, you need to request this feature from upstream, thanks.

**Comment by Atulin** [comment]
Will do 👍
