### ISSUE TITLE
Intellisense based on template.

### ISSUE THREAD

**Issue by s3xysteak** [vuejs/language-tools#4597]
### What problem does this feature solve?

Improve DX. User will have automatical intellisense. For example:

before
```vue
<script setup>
import type { CompRenderFunc } from 'xxx-ui'

const renderFunc: CompRenderFunc  = ({ /** intellisense! */ }) => {
  return /** intellisense! */
}
</script>

<template>
  <Comp :render-func />
</template>
```

after
```vue
<script setup>
const renderFunc = ({ /** intellisense! */ }) => {
  return /** intellisense! */
}
</script>

<template>
  <Comp :render-func />
</template>
```

### What does the proposed solution look like?

Maybe `unplugin-auto-import` will be helpful.

**Comment by so1ve** [comment]
It's not possible. In ts you can't do:

```ts
const foo = (props) => {}

bar(foo) // Can't infer props' type from this usage
```

**Comment by s3xysteak** [comment]
Sorry for my ambiguous words. I mean, we have already got a `Comp` component, and we have the type declaration of `bar`. Like:
```vue
<script setup lang="ts">
// Comp.vue

defineProps<{
  bar: (data: number) => string
}>()
</script>

<template>
  <div />
</template>
```

When we use it, maybe there is some way to achieve like that:

```vue
<script setup>
import Comp from './Comp.vue'

const bar = (data /** intellisense - number */) => {
  return /** intellisense - string */
}
</script>

<temlpate>
  <Comp :bar />
</template>
```

It is just like below in `ts`:

```ts
// first we have a type declaration of bar 
function bar (foo: (data: number) => string) {}

// so we can have intellisense when we use it
bar((/** intellisense */) => { return /* intellisense */  })
```

**Comment by so1ve** [comment]
I know what you mean, but your two code examples have different semantics. The first defines the function separately, while the second passes it directly as an anonymous function as a parameter.

**Comment by s3xysteak** [comment]
Thanks for your answers, that is a pity 😢.
