### ISSUE TITLE
Incorrect syntax highlighting when using object literals

### ISSUE THREAD

**Issue by yoyo837** [vuejs/language-tools#4605]
### Vue - Official extension or vue-tsc version

2.0.28

### VSCode version

1.91.1

### Vue version

2.x

### TypeScript version

None

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 184.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - /opt/homebrew/opt/node@18/bin/node
    npm: 10.7.0 - /opt/homebrew/opt/node@18/bin/npm
    pnpm: 9.5.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
```

### Steps to reproduce

```vue
<OrderList
  :order-info="{
    actions: [],
  }"
/>
```

### What is expected?

The lines which that after `actions: [],` syntax highlighting should works correctly.

### What is actually happening?

The lines which that after `actions: [],` syntax highlighting is incorrect.

**Comment by yoyo837** [comment]
![image](https://github.com/user-attachments/assets/04bc5824-a89b-40f7-b621-468a9125f1d2)

---

![image](https://github.com/user-attachments/assets/a0307fee-32da-41e4-8099-e39d6fb7e27b)

**Comment by KermanX** [comment]
Cannot be reproduced on my machine.

**Comment by yoyo837** [comment]
[index.vue.zip](https://github.com/user-attachments/files/16388497/index.vue.zip)

Please help to check this source file.

**Comment by KermanX** [comment]
Sorry, I still cannot reproduce it. Try disabling all plugins except "Vue - Official" and see if this still happens.

**Comment by yoyo837** [comment]
I confirmed that it was broken by the [WindiCSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=voorjaar.windicss-intellisense) plugin. Earlier, because [WindiCSS](https://github.com/windicss/windicss) stopped maintenance, we had migrated our code to [Tailwindcss](https://github.com/tailwindlabs/tailwindcss), but forgot to uninstall the plugin.
