### ISSUE TITLE
template中组件属性类型提示经常失效

### ISSUE THREAD

**Issue by FeiFanLiang** [vuejs/language-tools#4616]
### Vue - Official extension or vue-tsc version

2.0.26

### VSCode version

1.90.2

### Vue version

3.4.29

### TypeScript version

5.2.2

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M3
    Memory: 74.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 8.15.8 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.185
    Safari: 17.4
```

### Steps to reproduce

在项目运行一段时间后，template中的组件属性提示功能就会失效，必须重启vscode才能恢复正常，尝试过安装旧版本仍然没有解决问题，vscode中安装的扩展包括unocss，vue，eslint和prettier和stylelint

### What is expected?

在正常情况下
![image](https://github.com/user-attachments/assets/8c9d91e1-c118-420f-9804-5cf38820f817)

### What is actually happening?

在运行一段时间后,
<img width="865" alt="image" src="https://github.com/user-attachments/assets/b4621eeb-d4b2-4bd5-8b66-edc1b3edbfb8">
这个时候必须重启vscode窗口自动提示才会继续生效

**Comment by johnsoncodehk** [comment]
Please make sure to update the extension to the latest version before opening an issue. (Currently 2.0.28)

**Comment by FeiFanLiang** [comment]
> Please make sure to update the extension to the latest version before opening an issue. (Currently 2.0.28)

I have updated to the latest version and am waiting for confirmation if this problem will occur again, btw I have tried switching multiple extension versions which did not fix this problem

**Comment by VictorRibeiroKCX** [comment]
It started happening on `2.0.28`. I downgraded to `2.0.26` and props are correctly loaded. Weird that in `2.0.28` started showing this problem out of nowhere, no matter if I regenerate node_modules, restart VSCode or TS server, props are not loaded.

**Comment by FeiFanLiang** [comment]
> It started happening on `2.0.28`. I downgraded to `2.0.26` and props are correctly loaded. Weird that in `2.0.28` started showing this problem out of nowhere, no matter if I regenerate node_modules, restart VSCode or TS server, props are not loaded.

Not sure if it's due to other extension conflicts? But I've tried to keep only the minimum extensions, some extensions are essential for development
