### ISSUE TITLE
Inlay hints for destructured props

### ISSUE THREAD

**Issue by KazariEX** [vuejs/language-tools#4622]
### What problem does this feature solve?

Reactive Props Destructure 语法糖可能对理解变量是否为 prop 带来额外的心智负担

### What does the proposed solution look like?

在解构的 prop 变量前添加 `props.` 的嵌入提示有助于解决这个问题

![image](https://github.com/user-attachments/assets/5b99a3a7-919a-453c-b9c2-8e80758daf6f)

**Comment by szulcus** [comment]
How can I enable it?

**Comment by KazariEX** [comment]
`setting.vue.inlayHints.destructuredProps`.
