### ISSUE TITLE
Ignored errors in template

### ISSUE THREAD

**Issue by Fir3st** [vuejs/language-tools#4627]
### Vue - Official extension or vue-tsc version

vue-tsc 1.8.27

### VSCode version

-

### Vue version

3.4.14

### TypeScript version

5.2.2

### System Info

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 12.51 GB / 15.57 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 21.7.3 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.5.0 - /usr/bin/npm

System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 86.13 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 9.1.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.74
    Edge: 127.0.2651.74
    Safari: 17.4.1

### Steps to reproduce

- create SFC
- add <template>
- make any TS-related error (for example, type mismatch)

### What is expected?

- highlight the error

### What is actually happening?

- nothing happens, the IDE doesn't highlight any error 

### Any additional comments?

I work on a Mac and everything works fine. However, my colleague works on Windows (the project runs on WSL2 and docker) and her IDE completely ignores any TS-related errors presented in <template> tag. For example:

```
cell.column.columnDef.meta.responsiveFullWidth ? 'col-start-1 col-end-3' : 'justify-between'
```

It gives me `Vue: Property responsiveFullWidth does not exist on type ColumnMeta<DataObject, unknown>`. But on Windows, there is no error and the error is raised when she tries to build the project. We have tried using different node.js versions, different IDEs (PHPstorm, WebStorm, VSCode, PHPStorm EAP with the newest version of language-tools). When any error is presented in <script> tag, IDE correctly highlights the error, but not in <template> tag.

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by davidmatter** [comment]
This is about 1.8.27 - please update your extension, typescript and vue
