### ISSUE TITLE
`vue-tsc` does not read sub `tsconfig.json` file

### ISSUE THREAD

**Issue by Barbapapazes** [vuejs/language-tools#4630]
### Vue - Official extension or vue-tsc version

2.0.21

### VSCode version

1.91.1

### Vue version

3.4.34

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 61.88 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.3.0 - ~/.nvm/versions/node/v20.15.1/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.185
    Safari: 17.5
```

### Steps to reproduce

Hello,

The `vue-tsc` tool does not seems to read sub `tsconfig.json` file.

You can create a new Nuxt project, add a server endpoint and import something from `#imports`. `nuxi typecheck` will fail because of `#imports`.

related to https://github.com/nuxt/cli/issues/455

### What is expected?

I expect sub `tsconfig.json` are read and used.

### What is actually happening?

Actually, only the root (where `vue-tsc` starts) is read.

### Link to minimal reproduction

https://github.com/Barbapapazes/nuxt-typecheck

**Comment by davidmatter** [comment]
Hi, I can reproduce your issue but it seems this is not (directly) related to vue-tsc. Please check with nuxt to resolve this.
