### ISSUE TITLE
『Decorators are not valid here』 on methods 

### ISSUE THREAD

**Issue by woden0415** [vuejs/language-tools#4631]
### Vue - Official extension or vue-tsc version

v2.0.28

### VSCode version

Version: 1.91.1

### Vue version

^2.7.0

### TypeScript version

null

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 42.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 127.0.6533.88
    Edge: 125.0.2535.51
    Safari: 16.3
```

### Steps to reproduce

this is demo repositories   

```
git clone https://github.com/woden0415/test.git
cd test
npm i
npm run dev
```

the code can running normally
![image](https://github.com/user-attachments/assets/284a7574-084e-4d10-9b2b-b0b67a3fbbb1)
![image](https://github.com/user-attachments/assets/409aaf12-753c-4767-b953-bcb7cf81dc87)

but the ts check failed
`Decorators are not valid here.ts-plugin(1206)`
![image](https://github.com/user-attachments/assets/07b021c1-94bc-4080-ae29-373d03f64f9f)

![image](https://github.com/user-attachments/assets/43b15edb-a62b-48d7-8559-1099f4d1e5ab)

### What is expected?

ts check pass

### What is actually happening?

ts check fail

### Link to minimal reproduction

https://github.com/woden0415/test.git

**Comment by Pentadome** [comment]
Decorators can only be used on classes and their members

**Comment by davidmatter** [comment]
As @Pentadome mentioned, this is a syntax issue and has nothing to do with this repo. If you need further information on how to use decorators, refer to https://www.typescriptlang.org/docs/handbook/decorators.html
