### ISSUE TITLE
Intellisense can only work in PascalCase when component name using PascalCase   

### ISSUE THREAD

**Issue by Jasonyou-boy** [vuejs/language-tools#4637]
### Vue - Official extension or vue-tsc version

2.0.28

### VSCode version

1.91.1

### Vue version

3.4.31

### TypeScript version

5.6.0

### System Info

```shell
windows 11
```

### Steps to reproduce

empty

### What is expected?

when component name using kebab-case,intellisence can work in tow ways.but when component name using PascalCase,intellisence can't word in kebab-case

### What is actually happening?

intellisence can work in all ways when component name using PascalCase

### Any additional comments?

intellisence can work in all ways when component name using PascalCase

**Comment by RayGuo-ergou** [comment]
You are able to config that. See https://github.com/vuejs/language-tools/blob/master/extensions/vscode/src/config.ts#L41
