### ISSUE TITLE
Vuetify components that are added via .use are not loaded

### ISSUE THREAD

**Issue by gleb-bread** [vuejs/language-tools#4658]
### Vue - Official extension or vue-tsc version

2.0.28

### VSCode version

1.91.1

### Vue version

3.2.13

### TypeScript version

4.5.5

### Steps to reproduce

1. Create object Vuetify and export. It is possible without aliases, default, theme fields
![photo_2024-08-07_09-53-59](https://github.com/user-attachments/assets/1a666dd2-e72d-410d-90ca-b7161f5ac621)
2. Add an object using the API.use in the vue app
![image](https://github.com/user-attachments/assets/137a98dc-b3d3-4f96-a210-9c749607f2dd)

### What is expected?

Loading all fields, slots and props for a component
![image](https://github.com/user-attachments/assets/cd77254f-cee7-4891-bd0d-50fa95141a26)

### What is actually happening?

In component not found components from vuetify.
![image](https://github.com/user-attachments/assets/7c5f2a95-9e64-4d6d-aff9-df6ab411a0f6)

**Comment by gleb-bread** [comment]
I use vue-cli 5.0.0 as an app build

**Comment by so1ve** [comment]
We cannot analyze such code since they are executed at runtime. You should import vuetify's d.ts file.

**Comment by KermanX** [comment]
Can you reproduce this in Vuetify's starter project (created via `npm create vuetify@latest`)?

**Comment by douglasg14b** [comment]
Is there actual specific guidance here?

It's easier to rollback this plugin version on updates than it is to be regularly trying to discover how to fix a new issue, like this one...
