### ISSUE TITLE
The code color changes after dynamic rules are used

### ISSUE THREAD

**Issue by Lastcall9** [vuejs/language-tools#4665]
### Vue - Official extension or vue-tsc version

latest Virsion

### VSCode version

1.92.0

### Vue version

3.4。34

### TypeScript version

not TS useJS

### Steps to reproduce

![image](https://github.com/user-attachments/assets/984bf2ab-9627-441a-91a9-c7c9792dcbcf)
When I use dynamic rules in teamplate，the code color turned.

### What is expected?

color return to normal

### What is actually happening?

When I use dynamic rules in teamplate，the code color turned.

**Comment by KazariEX** [comment]
Could you provide a minimal reproduction?

**Comment by Lastcall9** [comment]
Can I describe in Chinese？
我只要在不管任何的teamplate里面的n-form-item里加入多行的 :rules:{xxxxx} 从这行开始往下面的所有代码都会变色 而不是正确的高亮 经过我的尝试2.0.18版本的vue-official是正常的 往后就都不行了 我在前端交流群里说过这个问题 大家也有这个现象 如果需要复现明天我弄个demo

**Comment by Lastcall9** [comment]
All I had to do was add multiple lines to the n-form-item in any teamplate :rules:{xxxxx} From this line on all the code below will change color instead of being properly highlighted. After my attempt version 2.0.18 vue-official is normal, it won't work I talked about this in the front end group and you have this phenomenon and if you need to replicate it I'll do a demo tomorrow

**Comment by Lastcall9** [comment]
virsion 2.0.28 
![image](https://github.com/user-attachments/assets/590525bd-1edb-48b0-acb1-f4dbffea5ae2)
virsion 2.0.18
![image](https://github.com/user-attachments/assets/60a8e009-c0b4-45b1-b510-04923dd245e2)
code:<template>
  <CommonPage>
    <div
      :rule="{
        required: true,
        message: `请输入规格${index + 1}的规格名称`,
        trigger: ['input', 'blur'],
      }"
    >
      11
    </div>
  </CommonPage>
</template>

<script setup>
console.log(123);
</script>

<style lang="scss" scoped></style>

**Comment by KazariEX** [comment]
你可以使用 markdown 语法把代码直接粘贴在评论里

**Comment by Lastcall9** [comment]
### Template
```html
<template>
  <CommonPage>
    <div
      :rule="{
        required: true,
        message: `请输入规格${index + 1}的规格名称`,
        trigger: ['input', 'blur'],
      }"
    >
      11
    </div>
  </CommonPage>
</template>

呃 就是很简单的任何一个元素用动态规则然后有多行的话就全变色了

**Comment by KazariEX** [comment]
无法复现……可以尝试禁用除 Vue - Offical 外的所有插件再看看吗？

**Comment by Lastcall9** [comment]
emm我卸载了一堆vue相关的插件确实不变色了 可能是某个代码提示插件跟vueofficial冲突了 抱歉 我再排查一下
