### ISSUE TITLE
vue-tsc failed to infer generic types of custom directives within templates

### ISSUE THREAD

**Issue by mon-jai** [vuejs/language-tools#4682]
### Vue - Official extension or vue-tsc version

Same as playground

### Vue version

3.5.0-beta.1

### TypeScript version

 5.6.0-beta

### Steps to reproduce

```vue
<template>
  <!--
    vue-tsc failed to infer type of T
    Type '(newUser: User) => void' is not assignable to type '(newValue: { id: number; }) => void'.
      Types of parameters 'newUser' and 'newValue' are incompatible.ts(2322)
  -->
  <div v-example="[user, setUser]"></div>
</template>

<script lang="ts" setup>
import { ref } from "vue";

type User = {
  id: number;
  name: string;
};

const user = ref<User>({ id: 0, name: "User" });

function setUser(newUser: User) {
  user.value = newUser;
}

const vExample = {
  mounted<T extends { id: number }>(
    _elContainingTbody: HTMLElement,
    _binding: { value: [T, (newValue: T) => void] }
  ) { },
};

// T is inferred correctly by TypeScript
vExample.mounted(
  document.createElement("div"),
  { value: [user.value, setUser] }
)
</script>
```

### What is expected?

vue-tsc should infer the type of T correctly in the template.

### What is actually happening?

```
Type '(newUser: User) => void' is not assignable to type '(newValue: { id: number; }) => void'.
  Types of parameters 'newUser' and 'newValue' are incompatible.ts(2322)
````

### Link to minimal reproduction

[Playground link](https://play.vuejs.org/#eNp9U8tu2zAQ/JUtL7YBS06T9qIoBtrAQFv0hUbtJQoCWlq5TCVSICklRqB/7y5lx05R5CKBy33MzA4fxbu2jfsORSJSj01bS4/LXAOkr6KI/wB0G3lXQCVVjSV4A0pXaMFvWwRTQTamZXycTDXe/3RoE+DvDC6W0BtVTkA50MaDdE5ttFzXyI1Ci1DzS9YdJvAIqkxAd80a7TkMh/p4HDKOcTy2lVY26NE6mOyGTkDqMpxCOzpaJLCFaVrpFc2MvZuenp2ezrhbFI1ES9VDH+GDJPZ4kYvrjlrNwaHnnje5WKYLyqHkdHEkER1dYVXroZZ6Q3Xe5YKrupZuVdMa64mPxQoGqKxpIBckZS7OuTYw5/5wAY8M44g3HzVxS8B5q/SGAkMoKox2HhgeVVHjlBssp6NoJ/NdUS44TFiGWaiqOl14ZfSe0b8rCuO5adyzatR6l8BzD2P71ajQHnBjOu2xTDPAB4+6dM+WB8NyOq7sFutLo71Umqhka1NuE/iQffm8qrFB7ee7rLXSJSWwBQKMBK6zORxZI3syww0QLABCDgOVj9osFpCxyYI3Lfm0MPQrfL2F9Ta45ipsK9d7IvGOQcBZmqJjOHFhkfa7AzfNBW0+F7OA8oDsoNbBJwyKfJUuRleQB8ScPEHiVWoT3zmj6Y0F5XLBjqTHZL+1vBjyDdEedciFrGtz/ynEvKUB+3jxG4s//4nfuQeO5eK7RcLRk8Oe7ry0G/Tj9erqKy3q6LIxZVdT9guXP9CZumOMY9r7TpcE+ygvoP0YzM7rdSv2gtuTegaUzVwEMBzmKG+Pb+hZXL6gyIHFWfwm1NHSSdzbnh4/ZZOuZ/Hb+CRao5fxazH8BTHEnRw=)

**Comment by KermanX** [comment]
This is a possible improvement. I thought of some methods, but was stuck on why TypeScript can't resolve types like `((a:number)=>number) | ((a:number)=>number)`. ([playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBA4lC8UoB8oCgD0GlQHoH40BjAewDsBnYKADwC4oAKRgQzrIFcBbAIwgCcAlPAB8nXgMFJUzNuL5DR8yUkScANuoCEaGowCMgtEA))

**Comment by mon-jai** [comment]
@KermanX In the example you provided, `f` is actually inferred as `never`.

You can verify this by hovering over `type F` here: [playground](https://www.typescriptlang.org/play/?ssl=5&ssc=5&pln=1&pc=1#code/MYewdgzgLgBAZgLhgCmQQyWArgWwEYCmATgJQwC8AfDNvsWQD4rqa6GkXW3tnk1YAbAQEIAUKKgBPAA4EYAMQowpskHHji4yAIwlRQA)

**Comment by mon-jai** [comment]
It seems that type annotation has no effect in this case: `null!` is always inferred as `never` in TypeScript. You’re essentially telling the compiler that "this is `null`, but also not `null` at the same time".

**Comment by mon-jai** [comment]
@KermanX In the example you provided, `f` is actually inferred as `never`. You can verify this by hovering over `type F` here: [playground](https://www.typescriptlang.org/play/?ssl=5&ssc=5&pln=1&pc=1#code/MYewdgzgLgBAZgLhgCmQQyWArgWwEYCmATgJQwC8AfDNvsWQD4rqa6GkXW3tnk1YAbAQEIAUKKgBPAA4EYAMQowpskHHji4yAIwlRQA).

It seems that type annotation has no effect in this case: `null!` is always inferred as `never` in TypeScript. You’re essentially telling the compiler that "this is `null`, but also not `null` at the same time".

However, `((a: number) => number) | ((a: number) => number)` works as expected. You just need to initialize the variable with something that matches the type (e.g. `null! as any`).

**Comment by KermanX** [comment]
> It seems that type annotation has no effect in this case: `null!` is always inferred as `never` in TypeScript. You’re essentially telling the compiler that "this is `null`, but also not `null` at the same time".
> 
> However, `((a: number) => number) | ((a: number) => number)` works as expected. You just need to initialize the variable with something that matches the type (e.g. `null! as any`). ([playground](https://www.typescriptlang.org/play/?ssl=1&ssc=74&pln=1&pc=62#code/MYewdgzgLgBAZgLhgCmQQyWArgWwEYCmATgJQwC8AfDNvsWQD4rqa6GkXW3tnk1YAbAQEIYaCGLABPAFAy4yAIwkgA))


Thanks a lot! Adding `as any` works. However, in the first playground link, hovering `f` shows `const f: ((a: number) => number) | ((a: number) => number)` instead of `never`, which seems a TypeScript bug.

**Comment by mon-jai** [comment]
> However, in the first playground link, hovering `f` shows `const f: ((a: number) => number) | ((a: number) => number)` instead of `never`, which seems a TypeScript bug.

Reported at: https://github.com/microsoft/TypeScript/issues/59626
