### ISSUE TITLE
2> version not working with helix

### ISSUE THREAD

**Issue by ElYaiko** [vuejs/language-tools#4683]
### Vue - Official extension or vue-tsc version

-

### VSCode version

-

### Vue version

3.4.29

### TypeScript version

5.4.0

### System Info

```shell
System:
    OS: Linux Fedora 40 (Forty)
    CPU: (8) arm64 unknown
    Memory: 1.85 GB / 7.37 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    bun: 1.1.23 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: beta
```

### Steps to reproduce

1. Open editor (helix)
2. Open vue project
3. LS not working as expected

### What is expected?

LS to work

### What is actually happening?

Using `@vue/language-server` version 2> with helix-editor and [default configuration](https://github.com/helix-editor/helix/blob/e46cedfc267c7651462f92a1b822de439c0024a8/languages.toml#L1265) doesn't work, but when downgrading to version 2< (1.8.27) it works.

I also tried using helix-editor [recommended config](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#vue) (typescript plugin), but doesn't work well.

**Comment by RayGuo-ergou** [comment]
You need both `tsserver` and `vue-language-server` in v2, see https://github.com/vuejs/language-tools/issues/4376#issuecomment-2109440806.

**Comment by ElYaiko** [comment]
> You need both `tsserver` and `vue-language-server` in v2, see [#4376 (comment)](https://github.com/vuejs/language-tools/issues/4376#issuecomment-2109440806).

Already tried this config too, it interprets the whole doc as Typescript.

**Comment by RayGuo-ergou** [comment]
If tsserver apply typescript sytnex in entire vue file, to me seem you did not set up the plugin properly. Can you double check the vue plugin path

**Comment by ElYaiko** [comment]
> If tsserver apply typescript sytnex in entire vue file, to me seem you did not set up the plugin properly. Can you double check the vue plugin path

Ok now it works, I had to write the full absolute path, instead of `~/`

Also, is there a way to highlight/underline components in `<template>` like in VSCode?

**Comment by RayGuo-ergou** [comment]
Yes custom components highlight can be achieved by semanticTokensProvider. Not sure if helix supports that.

VsCode: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-provider

Neovim: https://github.com/neovim/neovim/pull/21100

**Comment by ElYaiko** [comment]
> Yes custom components highlight can be achieved by semanticTokensProvider. Not sure if helix supports that.
> 
> VsCode: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-provider
> 
> Neovim: [neovim/neovim#21100](https://github.com/neovim/neovim/pull/21100)
> 
> disabled: ![image](https://private-user-images.githubusercontent.com/33137074/357762066-588484d9-d6d2-4944-acae-0c7a5693a61b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDM0NzMsIm5iZiI6MTcyMzY0MzE3MywicGF0aCI6Ii8zMzEzNzA3NC8zNTc3NjIwNjYtNTg4NDg0ZDktZDZkMi00OTQ0LWFjYWUtMGM3YTU2OTNhNjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEzNDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOWViODI2ZGU0YmExMmNjYWZhODE4YjM3MDk3N2Q3MWZlMGNhZDBiMDY3YTRiNTM3YTM3NGM4NzU2Yzc0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VGIMQiw1nAKPIIZYTuiiGA4tSXBCpc6wp38PvqHYnmY)
> 
> enabled: ![image](https://private-user-images.githubusercontent.com/33137074/357762160-3990be42-414f-4103-ae8d-48ab7e6507ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDM0NzMsIm5iZiI6MTcyMzY0MzE3MywicGF0aCI6Ii8zMzEzNzA3NC8zNTc3NjIxNjAtMzk5MGJlNDItNDE0Zi00MTAzLWFlOGQtNDhhYjdlNjUwN2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEzNDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1M2I3MzlhYzM0ZmM1MDdhYmVlZTViMTQzNTAzNDdkMjAzMzExOGQyYTI3YzQ4Y2QwNzEwZGQzZDk5NjYxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i4fVDlfosmpNIreGcAdfw8AtpQ_24_FnCwBuTCSLMmw)

It seems they don't: https://github.com/helix-editor/helix/pull/6102

Thanks for the help anyways.
