### ISSUE TITLE
Hybrid Mode: typeScriptPluginOnly not working correctly

### ISSUE THREAD

**Issue by mycak** [vuejs/language-tools#4694]
### Vue - Official extension or vue-tsc version

2.0.28

### VSCode version

1.92

### Vue version

3.4.27

### TypeScript version

5.0.2

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 129.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.1/bin/npm
    Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
```

### Steps to reproduce

vue.server.hybridMode set to typeScriptPluginOnly

### What is expected?

hybridMode disabled and typeing works correctly. 

### What is actually happening?

![Screenshot 2024-08-14 at 11 09 44](https://github.com/user-attachments/assets/0d4cbe82-0796-4025-a030-30a479369807)
![Screenshot 2024-08-15 at 20 03 16](https://github.com/user-attachments/assets/8a65b831-85be-4b9a-8bf7-2b7cda0fc0a5)

Im getting information about only boolean value possible.
Any other extension which can has impact.

Types for example from vuetify table items are not inherited.

### Any additional comments?

Works properly with volar 1.8.27

**Comment by KazariEX** [comment]
In fact, the incorrect type of `vue.server.hybridMode` is just a warning, and its value will be passed correctly.

> Types for example from vuetify table items are not inherited.

Could you describe about this?

**Comment by mycak** [comment]
for instance:
types for items passed to parent are recognized correctly
![Screenshot 2024-08-16 at 09 10 27](https://github.com/user-attachments/assets/a7269c02-1f3b-4d65-a6d3-43cc0a8fd61d)

But inside it the type for single item changes to 'any':
![Screenshot 2024-08-16 at 09 10 35](https://github.com/user-attachments/assets/0504d789-3e35-431a-afd1-54d29dd2b6e3)

On different device with similar setup types are visible :(
