### ISSUE TITLE
行内标签输入@后没有相应方法的提示 

### ISSUE THREAD

**Issue by lukesyy** [vuejs/language-tools#4697]
### Vue - Official extension or vue-tsc version

v2.0.28

### VSCode version

1.92.2

### Vue version

2.7.14

### TypeScript version

no

### Steps to reproduce

行内标签输入@符号时提示相关方法选择

### What is expected?

行内标签输入@符号时提示相关方法选择
现在的:
![image](https://github.com/user-attachments/assets/34208425-5b2f-4c88-ab32-c2852b3a53df)
期望的:
![image](https://github.com/user-attachments/assets/c1a39410-9053-4bd6-9a42-c97496827426)

### What is actually happening?

行内标签输入@符号时提示相关方法选择

**Comment by KermanX** [comment]
请提供尽可能精简的可以复现故障的代码，谢谢！

**Comment by lukesyy** [comment]
可以直接用若依的项目测试 
![image](https://github.com/user-attachments/assets/85fc124f-0cb9-45c0-bef0-0ee33be600e1)

https://gitee.com/y_project/RuoYi-Vue

**Comment by KazariEX** [comment]
Bump your `vue` to 2.7 and add tsconfig.json with:

```json
{
  "vueCompilerOptions": {
    "target": 2.7
  }
}
```
