### ISSUE TITLE
行内标签 V 字符匹配问题

### ISSUE THREAD

**Issue by lukesyy** [vuejs/language-tools#4698]
### Vue - Official extension or vue-tsc version

v2.0.28

### VSCode version

1.92.2

### Vue version

2.7.14

### TypeScript version

no

### Steps to reproduce

![28e77e5f9a9512d41adfe18e80790be6](https://github.com/user-attachments/assets/b0aa8cc8-5e07-496c-a52d-f3f1ec1085ea)

### What is expected?

输入 V 展示列表

### What is actually happening?

输入 V 展示列表

**Comment by KermanX** [comment]
Sorry I cannot reproduce this problem on my machine. Please provide a minimal reproduction. Thanks!

**Comment by lukesyy** [comment]
经过测试是因为 https://marketplace.visualstudio.com/items?itemName=oibit.element-ui-helper 插件冲突导致
