### ISSUE TITLE
Type is inferred as `{}` when all props are optional (target >= 3.5)

### ISSUE THREAD

**Issue by KazariEX** [vuejs/language-tools#4704]
### Vue - Official extension or vue-tsc version

2.0.28

### VSCode version

1.92.0-insider

### Vue version

3.5.0-beta.2

### TypeScript version

5.5.4

### Steps to reproduce

![image](https://github.com/user-attachments/assets/b840c16f-987d-46c8-ba5a-0079f7771665)

### What is expected?

N/A

### What is actually happening?

N/A

**Comment by daflyinbed** [comment]
I'm encountering a similar issue with TypeScript@5.6.2, vue-tsc@2.1.6, and Vue@3.5.4. The type is inferred as {} even though all props are required. Go back to vue@3.4.38 fixed my problem
