### ISSUE TITLE
can not start language-server cause `TypeError: server.watchFiles is not a function`

### ISSUE THREAD

**Issue by CSNight** [vuejs/language-tools#4707]
### Vue - Official extension or vue-tsc version

2.0.24~2.0.29

### VSCode version

webstorm 2024.2

### Vue version

3.4.35

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.95 GB / 15.73 GB
  Binaries:
    Node: 20.13.1 - D:\Libaray\NodeJs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.2 - D:\Libaray\NodeJs\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 116.0.5845.141
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.19041.4355
```

### Steps to reproduce

npm i @vue/language-server and start it cause error
```
~\AppData\Roaming\npm\node_modules\@vue\language-server\lib\initialize.js:48
            fileWatcher = server.watchFiles(['**/*.{' + [...watchingExtensions].join(',') + '}']);
                                 ^

TypeError: server.watchFiles is not a function
    at updateFileWatcher (C:\Users\chens\AppData\Roaming\npm\node_modules\
@vue
\language-server\lib\initialize.js:48:34)
    at C:\Users\chens\AppData\Roaming\npm\node_modules\
...
```

### What is expected?

after check the package i installed , i found that the error cause code line should be write like
```
 fileWatcher = server.fileWatcher.watchFiles(['**/*.{' + [...watchingExtensions].join(',') + '}']);
```
is there any wrong when build release?

### What is actually happening?

the server can not start

**Comment by johnsoncodehk** [comment]
This is caused by upgrading `@vue/language-server` `2.4.0-alpha.18` to `2.4.0-alpha.19` in node_modules. Can you confirm that upgrading to `2.4.0-alpha.20` can solve it?

**Comment by CSNight** [comment]
already change to 2.4.0-alpha.20 ,can not solve it

**Comment by CSNight** [comment]
directly change package file @vue\language-server\lib\initialize.js line:48 to 
```
fileWatcher = server.fileWatcher.watchFiles(['**/*.{' + [...watchingExtensions].join(',') + '}']);
```
can solve it

**Comment by CSNight** [comment]
upgrade to 2.4.0-alpha.20 can solve it

**Comment by pwang2** [comment]
@CSNight , thanks for the information.  I have been frustrated for a while in neovim lsp and have been doubt the hybridMode setup from [here]( https://github.com/vuejs/language-tools?tab=readme-ov-file#community-integration
)
Your workaround worked.  basically, I have to edit the `$HOME/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/package.json` as below. 

![image](https://github.com/user-attachments/assets/db01fd9b-236e-451a-88f3-2210598f36a7)

**Comment by drewbeno1** [comment]
This worked for me for a few hours, then i got off my computer and re-opened neovim later in the day and now I am having same error again.

**Comment by drewbeno1** [comment]
@johnsoncodehk When i run this 
rm -rf ~/.local/state/nvim
rm -rf ~/.local/share/nvim

and open nvim and run MasonInstallAll it works as expected. Then when i close nvim and re-open i am hit with the error again everytime

**Comment by drewbeno1** [comment]
@pwang2 did this solve it for you permanently?

**Comment by pwang2** [comment]
The workaround fix is reinstalling mason installed version with a dependency override.    if you reinstall,  the override will be flushed.   We don't have to be obsessed here to keep everything up to date.   New vue-language-server version should be able to fixed this.

**Comment by vrubezhny** [comment]
Any plans to release 2.1.0 or any intermediate version containing the fix for this issue?
