### ISSUE TITLE
Duplicate code hints

### ISSUE THREAD

**Issue by Simon-He95** [vuejs/language-tools#4718]
### Vue - Official extension or vue-tsc version

v2.0.28

### VSCode version

1.92.2

### Vue version

..

### TypeScript version

..

### Steps to reproduce

![录屏2024-08-25 11 52 00](https://github.com/user-attachments/assets/27e9b0bb-e97e-4d1e-9eb2-dd9817a00774)

after I disable language-tools will get expected hints

### What is expected?

no Duplicate code hints

### What is actually happening?

Duplicate code hints

**Comment by exzolink** [comment]
Same issue, v2.0.29, windows

**Comment by zhiyuanzmj** [comment]
Can you provide a mini reproduction.

**Comment by zhiyuanzmj** [comment]
Make sure the vscode configuration option `vue.server.includeLanguages` don't includes `typescript`.
``` json
// settings.json
"vue.server.includeLanguages": [
    "vue",
    "html",
    "htmx",
    // "typescript",
    // "typescriptreact"
  ],
  ```

**Comment by exzolink** [comment]
> Can you provide a mini reproduction.

Hmm, can't reproduce after latest updates

**Comment by Simon-He95** [comment]
> ```json
> vue.server.includeLanguages
> ```

it works for me, thx
