### ISSUE TITLE
Type hinting does not work in Vue SFC template part

### ISSUE THREAD

**Issue by Salmon42** [vuejs/language-tools#4739]
### Vue - Official extension or vue-tsc version

2.1.0

### VSCode version

1.92.2

### Vue version

Nuxt 3

### TypeScript version

5.5.2

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 47.21 GB / 49.59 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.14.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.14.0/bin/npm
```

### Steps to reproduce

After last update to v2.1.0 the typehinting / intellisense stops working in Vue SFC's template part - everything is inferred to any, even though the given references are correctly declared in `<script setup>`.

### What is expected?

In single previous version `2.0.28`, the opened source file looks like this:
![image](https://github.com/user-attachments/assets/1edcb758-0c1e-49aa-9c51-737f68e20e8a)
![image](https://github.com/user-attachments/assets/c3fb89aa-adbe-4e9e-a438-0b7f17161fb4)

### What is actually happening?

![image](https://github.com/user-attachments/assets/bd075f8f-01d0-4dc6-ac94-91f72cef2aa7)
![image](https://github.com/user-attachments/assets/33ebdf16-89ba-4127-89f9-79c00cbbf80a)

### Any additional comments?

To note, I was using Nuxt3 at that time, and the `AccomodationCard` component was auto-imported into the SFC automatically (through autogenerated directory `.nuxt`). I haven't tested this behavior on pure Vue3 setup or anywhere else.

My current workaround was to specifically revert the extension to version `2.0.28`

**Comment by RayGuo-ergou** [comment]
Reproduced in neovim too, by checking the log no error throw and can get generic vue proprieties (`is`, `key` and `ref`).

![image](https://github.com/user-attachments/assets/8888178b-2137-4825-9a3e-9761940739d3)

**Comment by Soveilove** [comment]
yes.2.1.0  it does not support corresponding function cabinets

**Comment by FilePlus** [comment]
![image](https://github.com/user-attachments/assets/9aae00ee-381e-484d-8836-be90169093d6)

I also encountered the same problem.

**Comment by FilePlus** [comment]
<img width="734" alt="image" src="https://github.com/user-attachments/assets/b3e56536-5598-4311-88c8-fc080ca8dfe1">
I also encountered the same problem.

**Comment by FilePlus** [comment]
<img width="740" alt="image" src="https://github.com/user-attachments/assets/276ae2d6-96c3-4860-ae03-76609fa4a5d3">
I also encountered the same problem.

**Comment by l246804** [comment]
+1

**Comment by FilePlus** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by moonwane** [comment]
+1
all globally typed components are now of "any" type

**Comment by Cyenoch** [comment]
Vue - Official extension or vue-tsc version
extension: 2.1.0
vue-tsc: 2.1.0

VSCode version
1.92.2

Vue version
Nuxt 3.13.0

TypeScript version
5.5.4

All components are `any`

<img width="174" alt="image" src="https://github.com/user-attachments/assets/815a4a6e-fb1a-45fd-856d-9ceff2d1afc7">

**Comment by davidmatter** [comment]
Workaround for now: Add the following to your tsconfig:

```json
"paths": {
      "vue/__globalTypes_3.4_false": ["node_modules/vue/__globalTypes_3.4_false.d.ts"]
}
```

**Comment by itliujia** [comment]
> +1 all globally typed components are now of "any" type
> 
> ![image](https://private-user-images.githubusercontent.com/12758132/362517992-8e8b2551-b2bf-4e19-b474-a7d9ec1d8d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTc1NTIsIm5iZiI6MTcyNDkxNzI1MiwicGF0aCI6Ii8xMjc1ODEzMi8zNjI1MTc5OTItOGU4YjI1NTEtYjJiZi00ZTE5LWI0NzQtYTdkOWVjMWQ4ZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOWUwNDE3NDFhNTVhMGQ4OTY5MzRiNGQ2MzZkMzA1MTg5NGEwMWNmZWQxM2Q1ODk2NGRhNzgzZDNkM2JlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lmqCGv7rdfBht7BwyfHUOXdPiZW08RuklS50zgsil_A)

I also encountered this problem, I lowered the version to `v2.0.28` and it worked fine.

**Comment by kingyue737** [comment]
I upgraded to v2.1.2 but still encountered this issue

**Comment by itliujia** [comment]
你好，我最近正在学习中，无法亲自回复你的邮件。我将尽快给你回复。

**Comment by Artles777** [comment]
v. 2.2.8 issue too

**Comment by AndriiGera** [comment]
v. 2.210 same issue, IDE - latest Webstorm. Why is this closed?

**Comment by so1ve** [comment]
> v. 2.210 same issue, IDE - latest Webstorm. Why is this closed?

Please open a new issue with a minimal reproduction
