### ISSUE TITLE
element-plus type tools is not working

### ISSUE THREAD

**Issue by INeverSayNo** [vuejs/language-tools#4743]
### Vue - Official extension or vue-tsc version

2.1.0

### VSCode version

1.92.2

### Vue version

3.4.29

### TypeScript version

5.4.5

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 3.51 GB / 15.75 GB
  Binaries:
    Node: 20.10.0 - ~\AppData\Local\Volta\tools\image\node\20.10.0\node.EXE
    npm: 10.2.3 - ~\AppData\Local\Volta\tools\image\node\20.10.0\npm.CMD
    pnpm: 9.7.1 - ~\AppData\Local\Volta\tools\image\pnpm\9.7.1\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Steps to reproduce

update Official, element-plus every component type is any
but if i use Official 2.0.28, it's working

### What is expected?

element-plus types should woking

### What is actually happening?

component type is any

**Comment by frasza** [comment]
Same behaviour observed with latest Nuxt with PrimeVue components

**Comment by hwhang0917** [comment]
Also happened to me, had to downgrade to v2.0.28 due to this issue.
