### ISSUE TITLE
#region does not show section headers in the minimap of VSCode

### ISSUE THREAD

**Issue by l246804** [vuejs/language-tools#4744]
### What problem does this feature solve?

方便在 minimap 中查看功能块信息。

### What does the proposed solution look like?

VSCode 在 TS 文件中会正常显示 #region 标题信息，但是在 Vue 中没有，希望能够正常显示。

## TS 文件
![image](https://github.com/user-attachments/assets/dc0cd261-5397-4d2c-a1a9-17dbe0cd92b1)

## Vue 文件
![image](https://github.com/user-attachments/assets/e4de7947-aa6d-472b-a1ef-3293d843fece)

**Comment by johnsoncodehk** [comment]
Please track https://github.com/microsoft/vscode/issues/213489
