### ISSUE TITLE
Suggestions appear slowly on Windows.

### ISSUE THREAD

**Issue by yulin96** [vuejs/language-tools#4745]
### Vue - Official extension or vue-tsc version

v2.1.2

### VSCode version

1.92.2

### Vue version

3.4.38

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 5.22 GB / 15.37 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.26 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
```

### Steps to reproduce

This issue was previously fixed in version 2.0.28, but it reappeared in version 2.1.

2.0.28
![2 0 28](https://github.com/user-attachments/assets/78357ca7-267b-44ed-a8ac-f54a8dbd28c9)

2.1.2
![2 1 2](https://github.com/user-attachments/assets/511c3595-f064-4b05-88c9-7d524760ef7a)

2.0.26
![2 0 26](https://github.com/user-attachments/assets/94657d71-3130-4138-8473-cee4d70baca5)

### What is expected?

The same speed as 2.0.28.
![2 0 28](https://github.com/user-attachments/assets/c4d13ad5-f67d-4f10-8a04-38aaf0a85992)

### What is actually happening?

Suggestions appear slowly.

### Any additional comments?

Many thanks to the author and contributors for their work. This plugin has helped me a lot.

**Comment by KazariEX** [comment]
Could you post the content of `tsconfig.json`?

**Comment by yulin96** [comment]
@KazariEX 
//  tsconfig.app.json
``` json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["typings/**/*", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*", "dist"],
  "compilerOptions": {
    "moduleResolution": "Bundler",
    "types": [],
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "baseUrl": "./",
    "paths": {
      "~/*": ["./src/*"]
    },
    "allowJs": true,
    "noImplicitAny": false
  }
}
```
// tsconfig.node.json
``` json
{
  "extends": "@tsconfig/node20/tsconfig.json",
  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "nightwatch.conf.*", "playwright.config.*"],
  "compilerOptions": {
    "composite": true,
    "noEmit": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",

    "module": "ESNext",
    "moduleResolution": "Bundler",
    "types": ["node"]
  }
}
```
// tsconfig.json
``` json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ]
}
```
