### ISSUE TITLE
The latest version. components lose all types

### ISSUE THREAD

**Issue by pungfen** [vuejs/language-tools#4754]
### Vue - Official extension or vue-tsc version

latest

### VSCode version

latest

### Vue version

latest

### TypeScript version

latest

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (28) x64 Intel(R) Core(TM) i7-14700
    Memory: 3.39 GB / 15.70 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Steps to reproduce

![image](https://github.com/user-attachments/assets/66b8caf6-3b1c-4468-af19-404f8906a36e)

### What is expected?

make types normal
make world peace

### What is actually happening?

lose all types

**Comment by KazariEX** [comment]
Please track #4747 or #4748
