### ISSUE TITLE
Error: `getClassOffset` is not a function (from element.ts)

### ISSUE THREAD

**Issue by J-Sek** [vuejs/language-tools#4759]
### Vue - Official extension or vue-tsc version

2.1.2

### VSCode version

1.92.2

### Vue version

3.4.38

### TypeScript version

5.5.4, 5.4.5

### System Info

```shell
System:
    OS: Linux 6.8 / Zorin OS 17.1
    CPU: i5-13600KF
    Memory: 18 / 32 GB
    Container: Yes
  Binaries:
    Node: 18.20.4 - ~/n/bin/node
    npm: 10.7.0 - ~/n/bin/npm
    bun: 1.1.26 - ~/.bun/bin/bun
```

### Steps to reproduce

- bootstrap barebones Nuxt project
- use complex refs or plugin references in Pug template within `*.vue` file

Pug version: 3.0.3, 3.0.2

### What is expected?

Type inference should work as usual - in Pug templates.

### What is actually happening?

Type inference stopped working **for Pug templates**.

### Link to minimal reproduction

[Nuxt starter project with Pinia and custom plugin](https://github.com/J-Sek/volar-reproduction)

### Any additional comments?

Following error does not appear on the minimal repro, but is constantly thrown on my main large project.

```
[Error - 11:30:20 AM] Server process exited with code 0.
[Vue Named Pipe Client] Deleting: /tmp/vue-named-pipe-2.1.2-configured-0
[Vue Named Pipe Client] Deleting: /tmp/vue-named-pipe-2.1.2-inferred-0
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-inferred-0 in 2ms
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-inferred-1 in 2ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-inferred-0 in 3ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-inferred-1 in 3ms
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-configured-0 in 1ms
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-inferred-2 in 1ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-configured-0 in 1488ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-inferred-2 in 1488ms
TypeError: a is not a function
    at fwe (/home/me/.vscode/extensions/vue.volar-2.1.2/dist/server.js:220:4828)
    at fwe.next (<anonymous>)
    at hB (/home/me/.vscode/extensions/vue.volar-2.1.2/dist/server.js:220:2167)
    at hB.next (<anonymous>)
    at rB (/home/me/.vscode/extensions/vue.volar-2.1.2/dist/server.js:220:1243)
    at rB.next (<anonymous>)
    at ki (/home/me/.vscode/extensions/vue.volar-2.1.2/dist/server.js:219:5773)
    at ki.next (<anonymous>)
    at ki (/home/me/.vscode/extensions/vue.volar-2.1.2/dist/server.js:219:5470)
    at ki.next (<anonymous>)
```

![image](https://github.com/user-attachments/assets/966a3ccf-43f0-4d05-b2f9-7ba5342f8e20)

[element.ts:605](https://github.com/vuejs/language-tools/blob/master/packages/language-core/lib/codegen/template/element.ts#L605)

TypeScript throws `[error] TSServer exited. Code: null. Signal: SIGTERM`, but I somehow doubt it is the exact cause.

**Comment by J-Sek** [comment]
I wouldn't mind digging deeper, debugging. Is there a way to use unminified source code?

**Comment by KazariEX** [comment]
I guess it happened on the pug template. #4652

https://github.com/vuejs/language-tools/blob/cb5d5a656e95bcd778b716fe2015490aecd7baff/packages/language-core/lib/codegen/template/element.ts#L618

**Comment by KazariEX** [comment]
If you are willing, you can try forking this repository and debugging it locally!

**Comment by J-Sek** [comment]
> _I guess it happened on the pug template. #4652_

Yes, I have updated the main description. Thanks for linking existing PR

**Comment by KazariEX** [comment]
Yes, it was merged into 2.1.0

**Comment by KazariEX** [comment]
Try install `@vue/language-plugin-pug` and adding it to `tsconfig. json`:

```json
"vueCompilerOptions": {
  "plugins": [
    "@vue/language-plugin-pug"
  ]
}
```

**Comment by J-Sek** [comment]
Great advice! Updating `@vue/language-plugin-pug` to `2.1.2` fixes the exception.

I don't like all that plugins and things like `$router` are still underlined with red squigglies, but it's a different issue.
