### ISSUE TITLE
losing typing of the event param in component custom event listener

### ISSUE THREAD

**Issue by n0099** [vuejs/language-tools#4778]
### Vue - Official extension or vue-tsc version

extension:`2.0.10` tsc:`2.1.2`

### VSCode version

1.92.2

### Vue version

3.4.28

### TypeScript version

5.5.4

### System Info

```
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
    Memory: 8.08 GB / 15.91 GB
  Binaries:
    Node: 22.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.4.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### package.json dependencies

https://github.com/n0099/open-tbm/blob/3d3386a67329099f953d08dfc959679e8b305246/fe/package.json

### Steps to reproduce

```bash
git clone https://github.com/n0099/open-tbm && cd open-tbm
git checkout 3d3386a67329099f953d08dfc959679e8b305246
cd fe
yarn
code src/components/post/queryForm/QueryForm.vue
```

### What is expected?

Not reporting.

### What is actually happening?

![image](https://github.com/user-attachments/assets/3f500b3d-5a76-4a51-95e7-5b81c41b49e4)
```
Parameter 'e' implicitly has an 'any' type. ts(7006)
```

### Link to minimal reproduction

https://github.com/n0099/open-tbm/blob/3d3386a67329099f953d08dfc959679e8b305246/fe

**Comment by KazariEX** [comment]
The latest version is 2.1.4, please try reinstalling from the marketplace.

https://marketplace.visualstudio.com/items?itemName=Vue.volar

**Comment by n0099** [comment]
https://github.com/vuejs/language-tools/issues/4227#issuecomment-2099911043
https://github.com/vuejs/language-tools/issues/4367
https://github.com/microsoft/vscode/issues/225398
