### ISSUE TITLE
Hover info in VScode gets crashed by pug plugin

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [vuejs/language-tools#4787]
### Vue - Official extension or vue-tsc version

Official

### VSCode version

1.92.2

### Vue version

3.4.37

### TypeScript version

5.4.5

### Steps to reproduce

1. Vue Sfc File with pug and ts script setup
2. hover over function causes error in language server destroying autocomplete and hover

### What is expected?

Hover should work in vue sfc files with pug

### What is actually happening?

No hover or type info in script body of vue sfc file with pug

**Comment by sschneider-ihre-pvs** [comment]
```
TypeError 'a' is not a function ...
```
and 'a' being  `getClassOffset`
https://github.com/vuejs/language-tools/blob/1a734cf9d9859da9ae72e1b8612e2f3613956ff9/packages/language-core/lib/codegen/template/element.ts#L586

**Comment by sschneider-ihre-pvs** [comment]
Is an issue since v2.1.0

**Comment by richardsimko** [comment]
Seeing the same issue with pug. Rolling back to v2.0.28 solves it for now.

**Comment by KazariEX** [comment]
update `@vue/language-plugin-pug`

**Comment by richardsimko** [comment]
Thanks, that solved it!
