### ISSUE TITLE
Stuttering when saving files `vue-official` 

### ISSUE THREAD

**Issue by Ali-ovo** [vuejs/language-tools#4802]
### Vue - Official extension or vue-tsc version

2.1.4

### VSCode version

1.92.2 (Universal)

### Vue version

@latest

### TypeScript version

5.0.4

### package.json dependencies

```json
{
"devDependencies": {
    "@ant-design-vue/nuxt": "^1.2.0",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@types/node": "^18",
    "@vite-pwa/nuxt": "^0.1.1",
    "eslint": "^8.40.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^9.27.0",
    "less": "^4.2.0",
    "less-loader": "^11.1.0",
    "nuxt": "^3.12.4",
    "nuxt-icon": "^0.6.10",
    "postcss": "^8.4.40",
    "prettier": "^3.3.3",
    "prettier-plugin-tailwindcss": "^0.6.5",
    "tailwindcss": "^3.4.7"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.5.2",
    "ant-design-vue": "^3.2.20",
    "axios": "^1.7.2",
    "dayjs": "^1.11.12",
    "jwt-decode": "^4.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "nuxt-icons": "^3.2.1",
    "pinia": "^2.2.0",
    "round-to": "^6.0.0",
    "tailwind-merge": "^2.4.0",
    "vue-hooks-plus": "^2.2.1",
    "vue-json-pretty": "^2.4.0",
    "vue3-emoji-picker": "^1.1.8"
  },

}
```

### Steps to reproduce

i use nuxt、antd-vue、tailwind in my project, Stuttering when saving vue files

### What is expected?

No more lag when saving files

### What is actually happening?

When I save the  `.vue`  file, vscode is very stuck and gives me this prompt
<img width="610" alt="image" src="https://github.com/user-attachments/assets/13e5f1d4-837c-486e-b412-fd111ee2d72b">

But when I downgraded `vue-official`  to `2.1.2`, vscode was very smooth when saving.

**Comment by Ali-ovo** [comment]
The latest version fixes this issue， its worked

**Comment by AemonCao** [comment]
> 最新版本修复了这个问题，已经解决了

我在升级到 v2.1.8 后还是有这个问题，请问你在升级后还有这个问题嘛？
