### ISSUE TITLE
vue 3.5 `useTemplateRef` is transform type mistake of  `unplugin-vue-macros/volar`

### ISSUE THREAD

**Issue by Gehbt** [vuejs/language-tools#4803]
### Vue - Official extension or vue-tsc version

2.1.4

### VSCode version

1.92.2

### Vue version

3.5.0

### TypeScript version

5.4.5

### package.json dependencies

```json
{
  "dependencies": {
    "vue": "^3.5.0"
  },
  "devDependencies": {
    "unplugin-vue-macros": "^2.11.6",
  },
}
```

### Steps to reproduce

- go to `src/App.vue`
- hover variate `main`

solve
- remove`"plugins": ["unplugin-vue-macros/volar"]` in tsconfig.app.json

### What is expected?

![image](https://github.com/user-attachments/assets/846137db-e914-4939-932d-a66461dc1531)

### What is actually happening?

![image](https://github.com/user-attachments/assets/eda42d75-fd06-40be-a40f-a5032b26ecd4)

### Link to minimal reproduction

https://github.com/Gehbt/vls-bug-repro1

### Any additional comments?

It also cause any virtual file generate error
![image](https://github.com/user-attachments/assets/651bf7a8-03a2-4822-ada5-2b1477005f84)

**Comment by zhiyuanzmj** [comment]
useTemplateRef will be removed from vue-macros in next version.
