### ISSUE TITLE
The syntax highlighting is not applied when destructuring props

### ISSUE THREAD

**Issue by yoshi-pi** [vuejs/language-tools#4811]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.92.2

### Vue version

3.5.1

### TypeScript version

5.4.0

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.88 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.4 - /usr/local/bin/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 128.0.6613.115
    Edge: 128.0.2739.63
    Safari: 17.3.1
```

### package.json dependencies

```json
{
  "dependencies": {
    "vue": "^3.5.1"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.8.0",
    "@tsconfig/node20": "^20.1.4",
    "@types/node": "^20.14.5",
    "@vitejs/plugin-vue": "^5.0.5",
    "@vue/eslint-config-prettier": "^9.0.0",
    "@vue/eslint-config-typescript": "^13.0.0",
    "@vue/tsconfig": "^0.5.1",
    "eslint": "^8.57.0",
    "eslint-plugin-vue": "^9.23.0",
    "npm-run-all2": "^6.2.0",
    "prettier": "^3.2.5",
    "typescript": "~5.4.0",
    "vite": "^5.3.1",
    "vue-tsc": "^2.0.21"
  }
}
```

### Steps to reproduce

Write the following code:
```vue
<script setup>
const { foo } = defineProps({
  foo: {
    type: String,
    required: true
  }
})
console.log(foo)
</script>
<template>
  <div></div>
</template>

```

### What is expected?

The object passed as an argument to defineProps should have syntax highlighting applied.

### What is actually happening?

It is not highlighted.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/41275070-d0e8-49df-88cc-9c0c58fe7075">

As a note, syntax highlighting works if destructuring is not used.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/0813f640-e0ce-45b1-a5b0-84e81ed2b4a8">

**Comment by ferferga** [comment]
Same thing happens if using TypeScript type signature syntax:

![image](https://github.com/user-attachments/assets/0ccfff50-d858-4278-9bff-e6aa2f76ced4)

But if it's in a single line, syntax highlighting is correct:

![image](https://github.com/user-attachments/assets/98d6d54b-ddd2-4b79-884c-d0cee977f98c)

**Comment by teco-yokoyama** [comment]
same

**Comment by KazariEX** [comment]
This issue occurs on the theme of prioritizing semantic tokens (or explicitly set `editor.senticHighlighting.enabled` as `true`).
