### ISSUE TITLE
not unwrapping `DistributeRef<>` for destructed props

### ISSUE THREAD

**Issue by n0099** [vuejs/language-tools#4820]
### Vue - Official extension or vue-tsc version

both 2.1.6

### VSCode version

1.93.0

### Vue version

3.5.1

### TypeScript version

5.5.4

### System Info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
  Memory: 7.49 GB / 15.91 GB
Binaries:
  Node: 22.8.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 4.4.1 - C:\Program Files\nodejs\yarn.CMD
  npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Chromium (127.0.2651.74)
  Internet Explorer: 11.0.22621.3527
```

### package.json dependencies

https://github.com/n0099/open-tbm/blob/2567a865f055a64629633a812ecd59197411bbca/fe/package.json

### Steps to reproduce

```bash
git clone https://github.com/n0099/open-tbm && cd open-tbm
git checkout 2567a865f055a64629633a812ecd59197411bbca
cd fe
yarn
code -g src/components/post/badge/Time.vue:6
```
https://github.com/n0099/open-tbm/blob/2567a865f055a64629633a812ecd59197411bbca/fe/src/components/post/badge/Time.vue#L6

### What is expected?

Not reporting.

### What is actually happening?

```typescript
Argument of type 'TPostIDKey' is not assignable to parameter of type 'keyof DistributeRef<TPost> & PostIDOf<DistributeRef<TPost>>'.
  Type 'keyof TPost & PostIDOf<TPost>' is not assignable to type 'keyof DistributeRef<TPost> & PostIDOf<DistributeRef<TPost>>'.
    Type 'keyof TPost & PostIDOf<TPost>' is not assignable to type 'keyof DistributeRef<TPost>'.
      Type 'TPostIDKey' is not assignable to type 'keyof DistributeRef<TPost>'.
        Type 'keyof TPost & PostIDOf<TPost>' is not assignable to type 'keyof DistributeRef<TPost>'.
          Type 'keyof TPost & PostIDOf<TPost>' is not assignable to type '"tid" | "createdAt" | "updatedAt" | "authorUid" | "postedAt" | "lastSeenAt" | "agreeCount" | "disagreeCount"'.
            Type 'TPostIDKey' is not assignable to type '"tid" | "createdAt" | "updatedAt" | "authorUid" | "postedAt" | "lastSeenAt" | "agreeCount" | "disagreeCount"'.
              Type 'keyof TPost & PostIDOf<TPost>' is not assignable to type '"tid" | "createdAt" | "updatedAt" | "authorUid" | "postedAt" | "lastSeenAt" | "agreeCount" | "disagreeCount"'.
ts-plugin(2345)
```

### Link to minimal reproduction

https://github.com/n0099/open-tbm/blob/2567a865f055a64629633a812ecd59197411bbca/fe

### Any additional comments?
Not destructing props will fix this:
```diff
-const { previousPost, nextPost, currentPost, parentPost, postTimeKey } = defineProps<{
+const props = defineProps<{
```
Another example can be found at https://github.com/n0099/open-tbm/blob/2567a865f055a64629633a812ecd59197411bbca/fe/src/components/post/badge/Common.vue#L3
```typescript
Type 'TPostIDKey' cannot be used to index type 'DistributeRef<TPost>'.
ts-plugin(2536)
```

Another typing error for prop `timestampType` is already reported as https://github.com/vuejs/language-tools/issues/4798

**Comment by n0099** [comment]
Another example can be found at https://github.com/n0099/open-tbm/blob/2567a865f055a64629633a812ecd59197411bbca/fe/src/components/post/badge/Common.vue#L3

**Comment by KazariEX** [comment]
Unfortunately, it works well on my machine without any errors.

**Comment by n0099** [comment]
Did you ran `git checkout 2567a865f055a64629633a812ecd59197411bbca`? It's reproductible in CI: https://github.com/n0099/open-tbm/actions/runs/10736670983/job/29776575723
