### ISSUE TITLE
Code save is terribly slow (with Biome)

### ISSUE THREAD

**Issue by ragrag** [vuejs/language-tools#4833]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.93.0

### Vue version

3.5.2

### TypeScript version

5.5.4

### Steps to reproduce

Saving a vue file with biome installed and configured with

```json
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit"
  },
```

if those settings are removed saving becomes extremely fast again

### What is expected?

Save should not be this slow

### What is actually happening?

~2 second delay for file to be saved

some warnings show up in the extension host output

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/9b4becd1-e49a-4ef4-bc75-90466f5ecde5">

**Comment by RayGuo-ergou** [comment]
These requests should not send to volar, I guess biome has their own LSP? Are you able to configure which server send the code action request to? If so that will solve your issue.

**Comment by RayGuo-ergou** [comment]
Did a bit research `*.biome` means send all code action request to biome lsp, make sure your biome lsp(extension) working properly. Definitely upstream issue either vscode or bimoe.

**Comment by ragrag** [comment]
thank youu for the help much appreciated🙏🏻 
i upstreamed issue to biome and hopefully it gets resolved on their end
