### ISSUE TITLE
Cannot assign to 'WritableComputedRef defined inside defineStore' because it is a read-only property

### ISSUE THREAD

**Issue by eliseevmikhail** [vuejs/language-tools#4837]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.93.0

### Vue version

3.5.3

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD Ryzen 5 PRO 3400G with Radeon Vega Graphics
    Memory: 6.56 GB / 15.70 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 128.0.6613.120
    Edge: Spartan (44.19041.1266.0), Chromium (128.0.2739.67)   
    Internet Explorer: 11.0.19041.1566
```

### Steps to reproduce

Define a simple store and try to assing 
```
const useStore = defineStore('store', () => {
  const x = computed<number>({
    get: () => 0,
    set: (_) => null,
  })

  return { x }
})

useStore().x = 1
```

### What is expected?

no error

### What is actually happening?

Cannot assign to 'x' because it is a read-only property.ts(2540)

### Link to minimal reproduction

https://play.vuejs.org/#eNp9ks1O40AQhF+lNZck2ux4d2EvURLtjzjsHgABx5GQsTtmwO4ZzY+xFOXd6RmHEBBCOcSqrnZ/VfJW/LZW9hHFQix95bQN4DFEC21JzUqJ4JVYK9KdNS7AFirT2Riwhh1snOlgwruTo3mNG014HYzDg8Vq0iWbFFWGfIDo94bVsX068elvMofpDFZr2CoCPpcWBnYeDi+BYneHDtYwzR6ABsNiv/VtPkocgqU+a+klpkXZmoaVbNjNEg6A46yOmHuAnaJRfcGbzmQ6/F3Rshir4SLEXIxZv3allQ/eEDeXMdR+wIUtRvik5exJUeI+BOsXRVHVxIs1trp3kjAUZLsi+379kPwrvqDvlMiYzMQXg+cIG928u5cq0S26Cxs0R3xzt2xb8/Q/a8FF3LfCO/dYPX6gP/hhpLx06NH1qMRhFkrHDY/js+tzHPj5MOxMHVt2fzK8Qq4/JsbR9idSzdhHvkz7L9enqbnxZ0NA8i+hEmhuI/uV4E/u7yfRX3FP5OlRi7c9uvROLvBE/pSnYvcMWiD5tA==

### Any additional comments?

2.0.29 worked well

**Comment by KazariEX** [comment]
This doesn't seem to be an issue with language tools, as it also occurs in the TS file.

**Comment by eliseevmikhail** [comment]
Looks like you are right. Downgrade vue to 3.4.29 fixes the issue.

**Comment by eliseevmikhail** [comment]
Actual ticket here https://github.com/vuejs/pinia/issues/2767
