### ISSUE TITLE
Asynchronous function inline failed

### ISSUE THREAD

**Issue by zhangenming** [vuejs/language-tools#4838]
### Vue - Official extension or vue-tsc version

lastest

### VSCode version

lastest

### Vue version

lastest

### TypeScript version

lastest

### Steps to reproduce

https://play.vuejs.org/#eNp9UU1PAjEQ/SvNnCAhSwweDFmIH+GgBzXqsYlZy7gWum3TTgFD9r873Q3IgXBq5703r2+me7jzvtgkhCmUUQXtSUSk5OfSSluOe6gvCBtvKkKuhBDlVyJyVtwqo9V6JqGKv1YNhrP5XjkbncHCuHpQbStN4mrYSpj3HeW4P9mmHJ94wggocuu3rotVdJYT7fNLEpRrvDYYXjxptpYwFR2TucoYt33qMAoJRwdc/aBan8FXcZcxCa8BI4YNSjhyVIUaqacX78+44/uRbNwyGVZfIN+Qx045Yy+7T3bJsU90XdrHxrtA2tYfcbEjtPEwVA6alW2nl8Df8nBh9P+4k+K665O25S1+bjBkT14gE8XkBto/zOCgzA==

### What is expected?

```
<template>
   <button @click="async()=>{console.log(await 1)}">button</button>
</template>
```

### What is actually happening?

```
<template>
   <button @click=";async()=>{console.log(await 1)}">button</button>
                   ;here
</template>```

### Link to minimal reproduction

_No response_

### Any additional comments?

_No response_

**Comment by KazariEX** [comment]
This example doesn't seem to have any errors.

**Comment by zhangenming** [comment]
<button @click="async()=>{console.log(await 1)}">button</button>
这个代码会被格式化成这样
   <button @click=";async()=>{console.log(await 1)}">button</button>
async前面多了一个分号
导致整个函数失效了

**Comment by KazariEX** [comment]
你用的格式化程序来自哪个扩展？

**Comment by zhangenming** [comment]
靠 抱歉 忘了我用的是prttier格式化

**Comment by zhangenming** [comment]
不过话说 vue插件本来的格式化根本没法用把 太辣眼了 才一直用的prettier

**Comment by KazariEX** [comment]
我这边用 prettier 并不会加分号

![image](https://github.com/user-attachments/assets/b5cd1a8d-fa0d-4955-8075-1559a7fcf096)
