### ISSUE TITLE
When a class with value of type object is added, the colour formatting is "off" in the remainder of the file

### ISSUE THREAD

**Issue by xenia1** [vuejs/language-tools#4844]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

Version: 1.93.0 (Universal) Commit: 4849ca9bdf9666755eb463db297b69e5385090e3 Date: 2024-09-04T13:02:38.431Z Electron: 30.4.0 ElectronBuildId: 10073054 Chromium: 124.0.6367.243 Node.js: 20.15.1 V8: 12.4.254.20-electron.0 OS: Darwin arm64 23.6.0

### Vue version

3.4.31

### TypeScript version

n/a

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 61.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 128.1.69.153
    Chrome: 128.0.6613.121
    Edge: 113.0.1774.57
    Safari: 17.6
```

### package.json dependencies

```json
n/a
```

### Note to bear in mind while reading the remaining issue - 

Since creating the issue, I saw it doesn't just happen with `class`, it can happen with any prop that has a specific format. That format is - 

`:class="{ 'mustBeString': someValue }"`

The replication steps below will mention `class` as that is the most likely instance I experienced where this would occur, but that could actually be replaced with any prop name. 

I'll put some images of a comparison at the bottom of this issue. 

### Steps to reproduce

1. Create vue file in VS code (i.e. file with extension .vue or select language mode "vue") - 
<img width="300" alt="Screenshot 2024-09-11 at 12 36 43 PM" src="https://github.com/user-attachments/assets/489fa990-9f1c-4556-9bd9-66cf47697fca">

2. Type in the file the following text - 
```
<template>
    <div>
        <CustomComponent :class="{ 'newClass' }">{{ title }}</CustomComponent>
        <p>{{ message }}</p>
    </div>
</template>
```

You can see in the image that the formatting looks fine* - 
<img width="583" alt="Screenshot 2024-09-11 at 12 38 41 PM" src="https://github.com/user-attachments/assets/a16b479a-7509-4126-b676-582776dfb137">

*NOTE ! Ignore the red "squigglies", those are not relevant for this issue as they're not there in the actual files where this issue occurs

3. Add a colon + value to the class, such as the following code -
```
<template>
    <div>
        <CustomComponent :class="{ 'newClass': true }">{{ title }}</CustomComponent>
        <p>{{ message }}</p>
    </div>
</template>
```

### Result-
The colour of the text changes, affecting the remaining content in the file below the line with the class - 

<img width="579" alt="Screenshot 2024-09-11 at 12 39 20 PM" src="https://github.com/user-attachments/assets/2f17138f-8a47-4def-8238-8b7c44c81d75">

Note that for "native" HTML tags, it's fine, e.g the. following code - 
```
<template>
    <div>
        <p :class="{ 'newClass': true }">{{ message }}</p>
        <CustomComponent>{{ title }}</CustomComponent>
    </div>
</template>
```
And pic - 
<img width="498" alt="Screenshot 2024-09-11 at 12 42 34 PM" src="https://github.com/user-attachments/assets/85db1617-6b12-4796-8095-755948ca3159">

### What is expected?

What is expected is that adding a class such as `:class="{ 'newClass': someValue }"` will not "break" the colour formatting. 

Specifically, that the formatting would be the same as when you add such a class to native HTML tags, which is fine (as you can see in the last image in the replication steps above). 

It used to be like that (without colour issues, and consistent with nativeHTML tags) before the latest update. 

I installed the previous version so you can see the difference in the following images - 
**2.1.4**
<img width="500" alt="Screenshot 2024-09-11 at 12 52 31 PM" src="https://github.com/user-attachments/assets/9397644e-6779-4dc1-b1a7-d6470fe0a2f4">

**2.1.6**
<img width="500" alt="Screenshot 2024-09-11 at 12 54 23 PM" src="https://github.com/user-attachments/assets/e2359490-eaf8-448c-82d7-07087c2183af">

### What is actually happening?

As mentioned, the colour formatting "breaks", it's not as it was in the previous version and it makes it difficult to read. 

Here is an example with more content - 
<img width="500" alt="Screenshot 2024-09-11 at 12 59 11 PM" src="https://github.com/user-attachments/assets/6167691b-db1e-460f-acfc-d35638c28a69">

VS colours that would be expected - 
<img width="500" alt="Screenshot 2024-09-11 at 1 00 13 PM" src="https://github.com/user-attachments/assets/2f64f280-41e3-481e-9446-4bbcc9710f7c">

Code if you want to copy/paste into your own file - 
```
<template>
    <div>
        <CustomComponent :class="{ 'newClass': true }">{{ title }}</CustomComponent>
        <p>{{ message }}</p>
    </div>
</template>


<script setup>

import { toRefs } from 'vue';

import customComponent from '@/components/customComponent.vue';

const props = defineProps({
    foo: {
        type: [Object, null],
        required: true,
    },
});

const {
    foo,
} = toRefs(props);

function fooThing() {
    console.log('foo');
}

</script>
```

Finally, as mentioned in the "note" section towards the top, here is a comparison showing the issue happening (vs not) depending on whether or not the object key is a string - 

<img width="400" alt="Screenshot 2024-09-11 at 1 27 48 PM" src="https://github.com/user-attachments/assets/6f47b803-5659-4f06-ba3c-ec10a7778807">

<img width="400" alt="Screenshot 2024-09-11 at 1 27 36 PM" src="https://github.com/user-attachments/assets/6e3aaf70-ae6c-4604-accc-d181ad85b4f4">

### Link to minimal reproduction

Copy/pasting in your IDE will hopefully be sufficient to replicate

### Any additional comments?

No

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/user-attachments/assets/a4d507da-5d68-4e30-b344-87c49346b740)

I cannot reproduce with the code you provide, can you please try with only `vue-official` enabled?

**Comment by xenia1** [comment]
It does appear having another extension enabled as well is caused this issue (specifically, Vetur - when I disable it, it's fine). 

Sorry I didn't think to check that myself!  It was fine before the latest update but I guess something must have changed.
