### ISSUE TITLE
Vue - Official 插件 语法提示混乱

### ISSUE THREAD

**Issue by HHL-hhl** [vuejs/language-tools#4852]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.91.1

### Vue version

3.4.31

### TypeScript version

没用ts

### Steps to reproduce

在template 内任意标签内，任意类型为对象的属性中使用 [ ] 后续节点会出现样式混乱， 这个情况在 Vue-Official 中存在 Vetur
 没有这个情况

### What is expected?

![image](https://github.com/user-attachments/assets/52fbd865-8c57-4b0b-9218-61dfd52e4dc0)

### What is actually happening?

![image](https://github.com/user-attachments/assets/5290ac82-0f46-4a6d-8c2a-5ed14db4ebbb)

**Comment by KazariEX** [comment]
在禁用除 Vue - Official 以外的所有扩展后是否仍然存在该问题？

**Comment by HHL-hhl** [comment]
谢谢试了一下，是因为 WindiCSS IntelliSense 这个扩展导致的
