### ISSUE TITLE
withDefaults推导的类型有问题

### ISSUE THREAD

**Issue by qhl123456** [vuejs/language-tools#4853]
### Vue - Official extension or vue-tsc version

2.0.22

### VSCode version

1.93

### Vue version

3.2.25

### TypeScript version

5.5.4-编辑器版本

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 55.97 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.139
    Safari: 17.5
```

### package.json dependencies

```json
"dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.2.25",
  },
  "devDependencies": {
    "typescript": "^4.5.4",
    "vue-tsc": "^1.0.0"
  }
```

### Steps to reproduce

使用interface给defineProps指定了范型，但是加上withDefaults后推导类型有误
interface IProps {
  formState: Record<string, any>
  outBoundPlanFormParams: Record<string, any>
}
const _props = withDefaults(defineProps<IProps>(), {
  formState: () => ({}),
  outBoundPlanFormParams: () => ({
    data: {
      type: 'see',
    },
  }),
})

### What is expected?

_props.outBoundPlanFormParams 的类型应该为Record<string, any>,但是使用withDefaults包裹后，_props.outBoundPlanFormParams的类型应该不变，还是范型里定义的类型

### What is actually happening?

_props.outBoundPlanFormParams 的类型应该为Record<string, any>,但是使用withDefaults包裹后，_props.outBoundPlanFormParams的类型变为了data:{ type: string }的类型

**Comment by LeoKun1231** [comment]
我也遇到了，希望官方能尽快解决一下。

**Comment by KazariEX** [comment]
你这接口都没放到泛型里去，以及我无法复现。

![image](https://github.com/user-attachments/assets/933a2070-b5f7-4b31-b990-26ec135c07c0)

**Comment by KazariEX** [comment]
请尝试把 Vue - Official 和 vue 都更新到最新版本。

**Comment by qhl123456** [comment]
> 你这接口都没放到泛型里去，以及我无法复现。
> 
> ![image](https://private-user-images.githubusercontent.com/85992002/368471904-933a2070-b5f7-4b31-b990-26ec135c07c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTE1MzcsIm5iZiI6MTcyNjcxMTIzNywicGF0aCI6Ii84NTk5MjAwMi8zNjg0NzE5MDQtOTMzYTIwNzAtYjVmNy00YjMxLWI5OTAtMjZlYzEzNWMwN2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAyMDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMTg1Yjc3MjkzYzAxZjM0NmQyODIyN2VkNTIzMTUwYzI1NDQxYjMxOTA4ODlmZmEyNjM5YmJkNjBiZWRkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SmRivUrz3McmpR8pcH8bLT6K4WZdQWkcyTbTfUiy0kg)

没写范型是代码复制错误的问题，我把volar更到最新版可以了
