### ISSUE TITLE
Can't install 'vue.volar' extension because it is not compatible with the current version of Visual Studio Code (version 1.72.2)

### ISSUE THREAD

**Issue by dimasempe** [vuejs/language-tools#4873]
### Vue - Official extension or vue-tsc version

Vue - Official extension: 2.1.6

### VSCode version

1.72.2 (user setup)

### Vue version

3.4.29

### TypeScript version

-

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 4.60 GB / 11.75 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### package.json dependencies

```json
{
  "name": "vue-sfc",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.29"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.5",
    "vite": "^5.3.1"
  }
}
```

### Steps to reproduce

Install Vue - Official extension

### What is expected?

Vue - Official should be installed

### What is actually happening?

there is pop up that say: Can't install 'vue.volar' extension because it is not compatible with the current version of Visual Studio Code (version 1.72.2)
<img width="960" alt="image" src="https://github.com/user-attachments/assets/c964fef6-6755-457f-9a35-bbc2db40efde">

**Comment by KazariEX** [comment]
Try to update your vscode?

**Comment by dimasempe** [comment]
It always updates automatically

**Comment by KazariEX** [comment]
Now the latest version of vscode is 1.93.0

**Comment by dimasempe** [comment]
I am using an alternative extension now called Vetur. If I need this official extension, I might uninstall my old version of VSCode and install the new version. By the way, thanks for the response👍
