### ISSUE TITLE
Hover info in VScode gets crashed by pug plugin

### ISSUE THREAD

**Issue by hinogi** [vuejs/language-tools#4874]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.93.1

### Vue version

3.4

### TypeScript version

5.4.5

### System Info

```shell
Windows
```

### Steps to reproduce

Open Vue SFC with pug template

### What is expected?

vue.volar server.js does not crash

### What is actually happening?

vue.volar is trying to restart after error but does not succeed

`TypeError: a is not a function`
`a` is `getClassOffset`
https://github.com/vuejs/language-tools/blob/5a026761d246c77dd789b32200bf779a526a617d/packages/language-core/lib/codegen/template/element.ts#L597

**Comment by KazariEX** [comment]
#4787 ?

**Comment by hinogi** [comment]
oh, self duplication :D

**Comment by hinogi** [comment]
might be regression on my side then, thx
