### ISSUE TITLE
Backtrick quote highlight error in vscode

### ISSUE THREAD

**Issue by DeniroBlack** [vuejs/language-tools#4877]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.93.1

### Vue version

3.5.3

### TypeScript version

5.4.4

### Steps to reproduce

Error highlight in vscode extension
![image](https://github.com/user-attachments/assets/d1230f82-ba95-4f8e-b772-835791a3d339)
![image](https://github.com/user-attachments/assets/d6f9b167-31b2-4c0a-bd92-d8071132bf7c)

```pug
<template lang="pug">
.row
  template(v-for="(params, field) in data.fields")
    div(
      class="mb-3px"
      :class=`{
        ['col-'+(params.config?.grid?.cols ?? 12)]: true,
        ['row-'+(params.config?.grid?.rows ?? 1)]: params.config?.grid?.rows != 1,
        'field-pinned': openCollapsedPinned[field],
        'h[calc(100%-15px)]': !(openCollapsed[field] === false),
      }`
      style="align-self: baseline;"
    )
```

```html
<template lang="html">
<div
  class="mb-3px"
  :class=`{
    ['col-'+(params.config?.grid?.cols ?? 12)]: true,
    ['row-'+(params.config?.grid?.rows ?? 1)]: params.config?.grid?.rows != 1,
    'field-pinned': openCollapsedPinned[field],
    'h[calc(100%-15px)]': !(openCollapsed[field] === false),
  }`
  style="align-self: baseline;"
></div>
```

![image](https://github.com/user-attachments/assets/966d40c2-ad74-43dd-8453-10ef368c1451)

### What is expected?

Correct highlight

### What is actually happening?

Not correct highlight

**Comment by KazariEX** [comment]
Using backquote to wrap attribute values is not supported in HTML.

**Comment by DeniroBlack** [comment]
> Using backquote to wrap attribute values is not supported in HTML.
In phpstorm supporting
![image](https://github.com/user-attachments/assets/58618b05-3e18-4a5c-b5e1-cf53de1707b7)
And it works on production good

**Comment by KazariEX** [comment]
Because its lang is `pug` but not `html`.

**Comment by DeniroBlack** [comment]
Create issue in vscode
https://github.com/microsoft/vscode/issues/229464
I don't know whose bug it is

**Comment by KazariEX** [comment]
You can create a minimal reproduction for this and open a new issue.

**Comment by KazariEX** [comment]
It might be the problem about textmate.
