### ISSUE TITLE
No errors in template with ts-check enabled in Vue >= 3.5.7

### ISSUE THREAD

**Issue by twisterniq** [vuejs/language-tools#4891]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.93.1

### Vue version

3.5.9

### TypeScript version

5.5.4

### package.json dependencies

```json
{
  "name": "vuejs-ts-check-template-bug",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "dependencies": {
    "vue": "3.5.9"
  }
}
```

### Steps to reproduce

1. Clone the minimal reproduction.
2. npm install
3. Check that there are no errors in `App.vue`.
4. If you downgrade to Vue `3.5.6` and check again, you will see that `setDate` has an error.

### What is expected?

The errors in `<template>` should be shown when `// @ts-check` exists.

![image](https://github.com/user-attachments/assets/cba673db-5cf8-4d71-98de-e77e05850841)

### What is actually happening?

The errors in `<template>` are not shown when `// @ts-check` exists.

![image](https://github.com/user-attachments/assets/cf143366-9bf9-4f01-99fc-a60efbf1cad5)

### Link to minimal reproduction

https://github.com/twisterniq/vuejs-ts-check-template-bug

**Comment by KazariEX** [comment]
Feel free to create it!
