### ISSUE TITLE
Upgrade vue-tsc@2.16 And vue-offcial@2.1.6 Afterwards, the property '$xx' does not exist on 'CreateGroupPublicInstanceWithMixins'. ts-plugin(2339)

### ISSUE THREAD

**Issue by GreatHonour** [vuejs/language-tools#4896]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.93.1

### Vue version

3.5.10

### TypeScript version

5.6.2

### package.json dependencies

```json
"dependencies": {
    "axios": "^1.7.7",
    "clipboard": "^2.0.11",
    "crypto-js": "^4.2.0",
    "dayjs": "^1.11.13",
    "echarts": "5.4.2",
    "pinia": "^2.2.2",
    "vant": "^4.9.7",
    "vue": "^3.5.10",
    "vue-i18n": "9.2.2",
    "vue-router": "^4.4.5"
  },
  "devDependencies": {
    "@types/crypto-js": "^4.2.2",
    "@types/node": "^18.19.54",
    "@typescript-eslint/eslint-plugin": "^8.7.0",
    "@typescript-eslint/parser": "^8.7.0",
    "@vant/auto-import-resolver": "^1.2.1",
    "@vitejs/plugin-legacy": "^4.1.1",
    "@vitejs/plugin-vue": "^4.6.2",
    "@vue/eslint-config-prettier": "^7.1.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^8.57.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^9.28.0",
    "husky": "^9.1.6",
    "lint-staged": "^15.2.10",
    "postcss": "^8.4.47",
    "postcss-html": "^1.7.0",
    "postcss-pxtorem": "^6.1.0",
    "postcss-scss": "^4.0.9",
    "prettier": "^2.8.8",
    "sass": "~1.58.3",
    "stylelint": "^14.16.1",
    "stylelint-config-prettier": "^9.0.5",
    "stylelint-config-recess-order": "^3.1.0",
    "stylelint-config-recommended-vue": "^1.5.0",
    "stylelint-config-standard-scss": "^6.1.0",
    "stylelint-prettier": "^2.0.0",
    "stylelint-scss": "^4.7.0",
    "terser": "^5.34.1",
    "typescript": "^5.6.2",
    "unplugin-auto-import": "^0.16.7",
    "unplugin-vue-components": "^0.26.0",
    "vite": "^4.5.5",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-svg-icons": "^2.0.1",
    "vue-eslint-parser": "^9.4.3",
    "vue-tsc": "^2.1.6"
  },
```

### Steps to reproduce

![image](https://github.com/user-attachments/assets/afc934ed-c3d3-4185-a866-7505f1fd05d6)

### What is expected?

Do not issue a warning

### What is actually happening?

Upgrade vue-tsc@2.16 And vue-offcial@2.1.6 Afterwards, the property '$xx' does not exist on 'CreateGroupPublicInstanceWithMixins'. ts-plugin(2339)

**Comment by KazariEX** [comment]
Please provide a minimal reproduction.

**Comment by GreatHonour** [comment]
> Please provide a minimal reproduction.

![image](https://github.com/user-attachments/assets/0aa24773-f235-413b-8e3c-a74bb6fadf98)
![image](https://github.com/user-attachments/assets/2de3980b-31bb-428d-af2f-8180bd194501)
![image](https://github.com/user-attachments/assets/acca1953-8c94-462f-94c1-8ad8ea732960)

我需要怎么提供呢，我没升级之前，没有这个报错，但是升级之后就有，一直没有找到解决的方案，ComponentCustomProperties这个我也添加的l

**Comment by KazariEX** [comment]
你把所有依赖都更新了再看看，然后在 node_modules 里搜索 `declare module "@vue/runtime-core"`，仍然在使用这种方式增强类型的库会导致目前推荐的 `declare module "vue"` 所增强的类型失效。

**Comment by GreatHonour** [comment]
![image](https://github.com/user-attachments/assets/d0191981-b5e6-4d09-bd7e-54de5c58c313)
我回退到这个版本就没有问题，应该是我的typescript问题，回头我在研究下，给你添麻烦了
