### ISSUE TITLE
vue-tsc@2.1.6 reports variable as unused despite being used in template

### ISSUE THREAD

**Issue by WIStudent** [vuejs/language-tools#4915]
### Vue - Official extension or vue-tsc version

vue-tsc@2.1.6

### VSCode version

I did not use VSCode

### Vue version

vue@3.5.11

### TypeScript version

typescript@5.6.3

### Steps to reproduce

1. Create a simple component like this: `FooBar.vue`
  ```vue
  <script setup lang="ts">
  const foo = "bar";
  </script>
  
  <template>
      <div>
          {{ foo }}
      </div>
  </template>
  ```
2. Run `npx vue-tsc --noEmit`

### What is expected?

vue-tsc should run without errors.

### What is actually happening?

vue-tsc returns the following error:
```text
src/components/FooBar.vue:2:7 - error TS6133: 'foo' is declared but its value is never read.

2 const foo = "bar";
     
```

### Any additional comments?

This does not happen if I downgrade to `vue-tsc@2.1.4`

**Comment by WIStudent** [comment]
Nevermind, I still had
```json
"vueCompilerOptions": {
    "skipTemplateCodegen": true
  }
```
inside my `tsconfig.json`. Removing it fixed the issue.

**Comment by tristandubbeld** [comment]
I would love to be able to still use `skipTemplateCodegen` and `vue-tsc` to typecheck the script without throwing for unused variables. Did you find any docs on why we can't use `skipTemplateCodegen` anymore @WIStudent?

**Comment by WIStudent** [comment]
@tristandubbeld I could not find any docs. My best guess ist that with `skipTemplateCodegen` enabled no type information is generated from the `<template>` section, so the typescript compiler cannot see that the variable is used in the `<template>` section.
