### ISSUE TITLE
How to format the CSS in the style tag to remove automatic blank lines between CSS selectors?

### ISSUE THREAD

**Issue by Xin-Yi-21** [vuejs/language-tools#4954]
### What problem does this feature solve?

How to format the CSS in the style tag to remove automatic blank lines between CSS selectors?

### What does the proposed solution look like?

![1](https://github.com/user-attachments/assets/0fd18dd9-c445-4e08-8924-ec5899f54df9)

**Comment by KazariEX** [comment]
You can try [Stylelint](https://stylelint.io).

**Comment by Lefthandmedia** [comment]
additionaly;. sort scss properties alphabeticaly
RDG

**Comment by KazariEX** [comment]
You can use Stylelint and Stylistic to accomplish all of this.
