### ISSUE TITLE
slot

### ISSUE THREAD

**Issue by wlonghaha** [vuejs/language-tools#4979]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.95.1

### Vue version

3.5.12

### TypeScript version

5.7.0-dev.*

### Steps to reproduce

payload有test属性,但使用slot时没有提供该属性时应该显示ts错误
```ts
<script setup lang="ts">
defineSlots<{
  content?(payload: { test: string }): any;
}>();
</script>

<template>
  <slot name="content" haha=""></slot>
</template>
```

### What is expected?

slot attr缺失时显示ts错误

### What is actually happening?

payload有test属性,但使用slot时没有提供该属性时应该显示ts错误

### Any additional comments?

thanks for your job❤

**Comment by zcf0508** [comment]
[playground](https://play.vuejs.org/#eNp9Ul1P6zAM/Su+edkmcTtxubyMMgQICXgABEi8REKh9dpCmkSJO4aq/necjI89wJ5a+5xjH9vpxbFz2bJDMRN5KHzjCAJS5+bSNK2znqAHjwsYYOFtCyOmjqSRprAmELShgsOIj0fnqLWFB+t1+Wc0kSafrstxIQ4IW6cVIUcAeb077/skHoZ8ylHKNsZ1BMu/rS1RH0rBuBQwZTCfbujFjqDA7RdNlT0Ha9h5H/VSFLZ1jUZ/7ahhe1LMICERU+zu9TLlyHe485kvaixefsg/h1XMSXHjMaBfohRfGClfIa3hs7srXPH/F8juO83sLeAtBqu76HFNO+lMybY3eMntRdp/Y6r7cLYiNOFzqGg0MofEl4Jvcrpl9G+7e9n/pJNm4C1GzU+nB61MxfsnLsP7LnHRGLzTlkKeavLu2Q0djZ1601aV3AoIA83AdO0TehgmM1Dm7YDbzMcT/mx7C4ELg1EtcsePynz1WtWKE3XNFljNnMT+XfHN2ngsPOTjEn1cHA+5l+1nu//E8A7XYPvh) 可以复现
