### ISSUE TITLE
Completion for global directives

### ISSUE THREAD

**Issue by benedictleejh** [vuejs/language-tools#4988]
### What problem does this feature solve?

vuejs/core#3399 has landed in Vue 3.5, and the `GlobalDirectives` interface exists, but Volar does not seem to populate directive completions from the the `GlobalDirectives` interface.

On a fresh project created with `pnpm create vue@latest`, with VSCode,  adding the module declaration
```ts
declare module 'vue' {
  interface GlobalDirectives{
    vHelloWorld: any;
  }
}
```
(in `App.vue`) enables type hints and jump to definition (at least to the module declaration) on the directive in Vue SFCs, but the completion popup when attempting to use the directive does not include `v-hello-world`.

I only managed to make the directive completion work when doing
```ts
declare module 'vue' {
  interface ComponentCustomProperties {
    vHelloWorld: any;
  }
}
```

### What does the proposed solution look like?

Volar should provide completion for global directives declared in the `GlobalDirectives` interface.

**Comment by KazariEX** [comment]
I cannot reproduce it. You could try deleting the `node_modules/.vue-global-types` folder and executing `vue.action.restartServer`. If this does not solve the problem for you, please provide a minimal reproduction.

**Comment by KazariEX** [comment]
Do you mean that only completion does not take effect? Can you jump to the type definition through F12 after completely typing the directives?

**Comment by benedictleejh** [comment]
Yes, it's only completion that doesn't work. The jump to the type definition (whether ctrl+click or F12) works.
