### ISSUE TITLE
Vue - Official  The code suggestions are duplicated

### ISSUE THREAD

**Issue by leontom-comeing** [vuejs/language-tools#5000]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.95.2

### Vue version

3.5.12

### TypeScript version

5.6.3

### System Info

```shell
Windows 11,Chrome
```

### package.json dependencies

```json
{"dependencies": {
    "vue": "^3.5.12"
  },
  "devDependencies": {
    "@tsconfig/node20": "^20.1.4",
    "@types/node": "^20.17.6",
    "@vitejs/plugin-vue": "^5.1.4",
    "@vue/tsconfig": "^0.5.1",
    "npm-run-all2": "^7.0.1",
    "typescript": "~5.6.3",
    "vite": "^5.4.10",
    "vite-plugin-vue-setup-extend": "^0.4.0",
    "vue-tsc": "^2.1.10"
  }}
```

### Steps to reproduce

Code sample:
```js
export default {
    data() {
        return {
            name: "101"  // Missing a comma here, move the cursor to the error to see the error message
            age: 0
        }
    },
}
```
Here is the error message:
<img width="222" alt="errorMsg" src="https://github.com/user-attachments/assets/4b300bd6-e699-42cf-918e-a731f73ab301">

Duplicate error messages appear

### What is expected?

Expect only one error message to remain

### What is actually happening?

Here are all the extensions I have enabled:
![image](https://github.com/user-attachments/assets/ac16c6c5-a41b-4a4a-a493-58616122606c)

**Comment by leontom-comeing** [comment]
## The following information might be useful.

1.Start VSCode, and you will see duplicate suggestions.

2.Disable the vueVue - Official extension without starting it.

3.Restart VSCode.

4.Enable the vueVue - Official extension. 
// At this point, there will be only one suggestion.

5.Restart VSCode. 
// Now, the suggestions are duplicated again.

**Comment by KazariEX** [comment]
Have you turned off the hybrid mode?

**Comment by leontom-comeing** [comment]
> Have you turned off the hybrid mode?
yes,I know what's wrong.
I've turned it on now.
The problem has been solved.
thank you.
