### ISSUE TITLE
useTemplateRef finds unrelated references with same name

### ISSUE THREAD

**Issue by ludwig801** [vuejs/language-tools#5009]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.95.2

### Vue version

3.5.12

### TypeScript version

5.6.3

### Steps to reproduce

Assume the following 2 SFC components in the project:

**Component A**
```vue
<template>
  <div ref="name"></div>
</template>

<script setup lang="ts">
import { useTemplateRef } from 'vue'

const name = useTemplateRef('name')
</script>
```

**Component B**
```vue
<template>
  <main ref="name"></main>
</template>

<script setup lang="ts">
import { useTemplateRef } from 'vue'

const name = useTemplateRef('name')
</script>
```

Notice that the elements have a `ref` with the value of `"name"`.
There are 2 issues:

1. When performing "Find All References" on any of the `"name"` string, the system finds both references, even tough they are unrelated but for the name of the `ref` (see image below).
![image](https://github.com/user-attachments/assets/e1018a07-1fb6-4640-b6ae-86d0ff670e43)

2. This is actually the worst issue: when renaming one of the strings, the other also gets renamed in the <script setup>. In the image below, this is the result of renaming the ref inside `ComponentB.vue`. Both `useTemplateRef` in `ComponentA.vue` and `ComponentB.vue` have been renamed, and only `ref="name"` in  `ComponentB.vue` has been renamed to `"name2"` (this one was actually expected and the only thing working as expected).
![image](https://github.com/user-attachments/assets/48de26cf-d7e6-4390-9a15-93be71ceaaa5)

### What is expected?

When renaming a string ref inside an SFC file, only the refs inside that file get renamed. 
The rest of the project should be untouched, as it is unrelated to this action.

### What is actually happening?

Any `useTemplateRef` which references the same named string is renamed, throughout the project.
This is and incredibly dangerous and wild behaviour.

**Comment by KazariEX** [comment]
Currently, this is a limitation of TS. (notice the occurrences highlighting)

![image](https://github.com/user-attachments/assets/b8b1ea7e-33e2-4baf-a57b-dac2e53c1b4c)

I will commit a fix that allows renaming on `ref="..."` without affecting unrelated strings. However, please be careful not to rename `useTemplateRef('...')`.

**Comment by johnsoncodehk** [comment]
> However, please be careful not to rename `useTemplateRef('...')`.

https://github.com/vuejs/language-tools/commit/edf161a9c9832cc5963ea5bdbdd91309b48d35ca should fixed this case.
