### ISSUE TITLE
Is it possible to enhance the feature of prompting internal properties when importing JS files with aliases? This prompt is effective when using relative paths.

### ISSUE THREAD

**Issue by VioSea-hub** [vuejs/language-tools#5014]
### What problem does this feature solve?

I have detailed explanations in this discussion #5003

### What does the proposed solution look like?

I have detailed explanations in this discussion #5003

**Comment by KazariEX** [comment]
Have you configured alias paths in `tsconfig.json`?

**Comment by VioSea-hub** [comment]
I have configured it, and I have a screenshot in the discussion

**Comment by KazariEX** [comment]
The `alias` in the `vite.config.json` only provides build time support.

**Comment by VioSea-hub** [comment]
I'm sorry, I looked at it wrong. But my project doesn't use TypeScript, do I still need to configure it?

**Comment by KazariEX** [comment]
Yes, because it not only provides support for TypeScript.

**Comment by VioSea-hub** [comment]
I just configured tsconfig. json but still can't prompt. Is it because my configuration method is incorrect? It can only prompt. ts files
![image](https://github.com/user-attachments/assets/c96b8327-c0b7-4a0b-b180-16965a77d05e)
![image](https://github.com/user-attachments/assets/eb2903f6-a31f-437e-8b5a-8f8523ea3d3a)
![image](https://github.com/user-attachments/assets/7ecfa6b3-5987-49be-ac43-5765fcba2546)
This is my TS configuration

**Comment by KazariEX** [comment]
Try `allowJs`?

**Comment by VioSea-hub** [comment]
After configuring `allowJs` the correct prompt can be provided. Thank you
