### ISSUE TITLE
vue-tsc not work with typescript 5.7.2

### ISSUE THREAD

**Issue by devhaozi** [vuejs/language-tools#5018]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

none

### Vue version

3.5.13

### TypeScript version

5.7.2

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics         
    Memory: 9.81 GB / 31.21 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.13.2 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (129.0.2792.79)
    Internet Explorer: 11.0.26100.1882
```

### package.json dependencies

```json
{
  "dependencies": {
    "@fontsource-variable/jetbrains-mono": "^5.1.1",
    "@guolao/vue-monaco-editor": "^1.5.4",
    "@vue-js-cron/naive-ui": "^2.0.9",
    "@vueuse/core": "^11.3.0",
    "@xterm/addon-attach": "^0.11.0",
    "@xterm/addon-clipboard": "^0.1.0",
    "@xterm/addon-fit": "^0.10.0",
    "@xterm/addon-unicode11": "^0.8.0",
    "@xterm/addon-web-links": "^0.11.0",
    "@xterm/addon-webgl": "^0.18.0",
    "@xterm/xterm": "^5.5.0",
    "alova": "^3.2.4",
    "axios": "^1.7.7",
    "cronstrue": "^2.52.0",
    "echarts": "^5.5.1",
    "install": "^0.13.0",
    "lodash-es": "^4.17.21",
    "luxon": "^3.5.0",
    "marked": "^15.0.2",
    "mitt": "^3.0.1",
    "pinia": "^2.2.6",
    "pinia-plugin-persistedstate": "^4.1.3",
    "remove": "^0.1.5",
    "vue": "^3.5.13",
    "vue-echarts": "^7.0.3",
    "vue-i18n": "^10.0.4",
    "vue-router": "^4.4.5"
  },
  "devDependencies": {
    "@iconify/json": "^2.2.275",
    "@iconify/vue": "^4.1.2",
    "@rushstack/eslint-patch": "^1.10.4",
    "@tsconfig/node20": "^20.1.4",
    "@types/lodash-es": "^4.17.12",
    "@types/luxon": "^3.4.2",
    "@types/node": "^22.9.1",
    "@unocss/eslint-config": "^0.64.1",
    "@vitejs/plugin-vue": "^5.2.0",
    "@vue/eslint-config-prettier": "^10.1.0",
    "@vue/eslint-config-typescript": "^13.0.0",
    "@vue/tsconfig": "^0.6.0",
    "colord": "^2.9.3",
    "eslint": "^8.57.1",
    "eslint-plugin-vue": "^9.31.0",
    "md-editor-v3": "^5.0.2",
    "monaco-editor": "^0.52.0",
    "naive-ui": "^2.40.1",
    "npm-run-all2": "^7.0.1",
    "prettier": "^3.3.3",
    "prettier-plugin-organize-imports": "^4.1.0",
    "sass": "^1.81.0",
    "typescript": "^5.7.2",
    "unocss": "^0.64.1",
    "unplugin-auto-import": "^0.18.5",
    "unplugin-icons": "^0.20.1",
    "unplugin-vue-components": "^0.27.4",
    "vite": "^5.4.11",
    "vite-plugin-html": "^3.2.2",
    "vite-plugin-mock": "^3.0.2",
    "vite-plugin-static-copy": "^2.1.0",
    "vue-tsc": "^2.1.10"
  }
}
```

### Steps to reproduce

update typescript to 5.7.2

### What is expected?

no error

### What is actually happening?

throw error:

```
C:\path\to\project\node_modules\.pnpm\vue-tsc@2.1.10_typescript@5.7.2\node_modules\vue-tsc\index.js:34
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.15.0
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "type-check" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by pzgz** [comment]
Excatly same error message, tried 2.1.6 and 2.1.10

![CleanShot 2024-11-23 at 02 51 26@2x](https://github.com/user-attachments/assets/c969e6c8-ce7b-4f9d-a6e6-32cb11eb4156)

**Comment by acabreragnz** [comment]
Same here, in my local works but not in the CD pipeline 🤔 

![image](https://github.com/user-attachments/assets/505f422d-ba48-4f48-8d6d-c2d57bf2f459)

**Comment by acabreragnz** [comment]
I found the issue, Typescript was updated 1 hour ago to version 5.7.2.

For me, version 5.6.2 is working.

**Comment by teles** [comment]
I am experiencing the same problem when using vue-tsc version 2.1.10 with TypeScript 5.7.2. The error occurs when running the build script using pnpm 

```bash
/node_modules/.pnpm/vue-tsc@2.1.10_typescript@5.7.2/node_modules/vue-tsc/index.js:34
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
Node.js v22.11.0
```

To resolve this issue temporarily, I had to downgrade:
* vue-tsc to version 2.0.29
* typescript to version 5.6.2

Here is the updated portion of my package.json after the downgrade:

```json
{
  "scripts": {
    "build": ""vue-tsc -b && vite build"
    },
  "devDependencies": {
      "vue-tsc": "2.0.29",
      "typescript": "5.6.2",
      "vite": "^5.4.10",
      "@vitejs/plugin-vue": "^5.1.4"
  }
}
```

This downgrade fixed the issue. It appears to be related to an incompatibility between vue-tsc@2.1.10 and TypeScript 5.7.x.

**Comment by Dedicatus546** [comment]
same here

**Comment by sminnee** [comment]
At https://github.com/vuejs/language-tools/blob/cf70eda2c40c33e2458b09d6dcac0c5f3615067d/packages/tsc/index.ts#L6 the file `typescript/lib/tsc.js` is referenced.

This file is now `typescript/lib/_tsc.js`, because the former file is now just a shim.

To work in all typescript versions, it would need to apply the transformations on both `typescript/lib/tsc.js` and `typescript/lib/_tsc.js`, and avoid throwing an error if the search text isn't found.

It might be worth updating https://github.com/volarjs/volar.js/blob/master/packages/typescript/lib/quickstart/runTsc.ts#L11 to:
 * accept either a `string[]` or a `string` for the tscPath.
 * accept an option to disable 'search text not found' errors.

**Comment by JaguarJack** [comment]
This has a huge impact. When will the version be released to solve this problem?

**Comment by Andrija84** [comment]
Thanks

**Comment by RomkaLTU** [comment]
Nothing helped. I still get the same error even after downgrading the mentioned packages. Another solution with a patch is not clear. I can't find this file, and I don't use ppm.

**Comment by nosdmitry** [comment]
I use this command `npx --yes -p vue-tsc@2.1.2 --yes -p typescript@5.6.2 vue-tsc --noEmit --skipLibCheck` and it works fine on my local server.

But it continues falling with the same error on pipeline in gitlab.
I'm confused, everything worked fine until this Monday..

```
/root/.npm/_npx/4e06f8b322b12674/node_modules/vue-tsc/index.js:45
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
```

**Comment by Andrija84** [comment]
> At
> 
> https://github.com/vuejs/language-tools/blob/cf70eda2c40c33e2458b09d6dcac0c5f3615067d/packages/tsc/index.ts#L6
> 
> the file `typescript/lib/tsc.js` is referenced.
> This file is now `typescript/lib/_tsc.js`, because the former file is now just a shim.
> 
> To work in all typescript versions, it would need to apply the transformations on both `typescript/lib/tsc.js` and `typescript/lib/_tsc.js`, and avoid throwing an error if the search text isn't found.
> 
> It might be worth updating https://github.com/volarjs/volar.js/blob/master/packages/typescript/lib/quickstart/runTsc.ts#L11 to:
> 
> * accept either a `string[]` or a `string` for the tscPath.
> * accept an option to disable 'search text not found' errors.

I was able to fix this issue by changing the lib path which is now different, like above comment described. Why this sudden change I cant figure out

**Comment by davidmatter** [comment]
If my proposed patching solution doesn't work for you guys, consider using overrides to forcibly downgrade the resolved typescript version to the last minor. Here are the docs [for pnpm](https://pnpm.io/package_json#pnpmoverrides) or [npm](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) or [yarn](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

**Comment by juliandreas** [comment]
Removing the `^` from : `"typescript": "^5.6.3"` solved it for me.

**Comment by teles** [comment]
I wanted to share that, as a palliative solution, I resolved the issue by using these specific versions in my package.json without the ^ at the beginning:

```json
"devDependencies": {
  "typescript": "5.6.2",
  "vue-tsc": "2.0.29"
}
```

After making this change, the problem stopped occurring for me.
Hope this helps as a temporary workaround!

**Comment by kieranwv** [comment]
Which version of `vue-tsc` or `typescript` is available?

**Comment by hinogi** [comment]
"@vitejs/plugin-vue" this one is a constant problem with updates. it is not compliant with the vue sfc compiler so there are constant issues.

**Comment by KacperMalachowski** [comment]
JFYI: Typescript 5.6.3 and vue-tsc 2.0.0 works as well.

**Comment by yatendra121** [comment]
Same issue with latest version of these deps.

**Comment by greenpdx** [comment]
Same

**Comment by throrin19** [comment]
Same issue. Any news or release date of the fix ?

**Comment by yatendra121** [comment]
> Same issue with latest version of these deps.

It is working fine with deno 2.x

**Comment by kitsune7** [comment]
I submitted [an issue](https://github.com/volarjs/volar.js/issues/251) on Volar's repository. After a bunch of digging in `node_modules` I figured out the exact cause of the issue. If I'd seen this issue thread earlier, I probably would have just downgraded my Typescript version and moved on, but since I know what's going on now. I'm hoping to submit a PR to get things fixed on their side.

**Comment by lk77** [comment]
same issue here, i just rolled back my package-lock.json for now

**Comment by kitsune7** [comment]
I put up a [PR](https://github.com/volarjs/volar.js/pull/252) for a fix. The changes worked for me in my testing. Hopefully, we can get this merged in and unblock Typescript upgrades.

**Comment by silverwind** [comment]
Has there been any attempts to contribute the changes that `vue-tsc` to the official `tcs`? React JSX also works out of the box in `tsc`, so why can't Vue too?

**Comment by huyphung1602** [comment]
Any update? using v5.6.3 of typescript block other packages in my project and I cannot build to deploy bro!!!

**Comment by ST-DDT** [comment]
> I put up a [PR](https://github.com/volarjs/volar.js/pull/252) for a fix. The changes worked for me in my testing. Hopefully, we can get this merged in and unblock Typescript upgrades.

I got lightly confused because that PR fixes this issue in another repository.
The fix for this repository is https://github.com/vuejs/language-tools/pull/5020

- https://github.com/vuejs/language-tools/pull/5020

**Comment by davidmatter** [comment]
We've now landed the compatibility fix in master. To use this fix in your codebase, until we've released the next version, please point `vue-tsc` to:

`pnpm i https://pkg.pr.new/vuejs/language-tools/vue-tsc@3fb59af`

**Comment by Mettbrot** [comment]
Are there any plans to do a patch release for this anytime soon? I don't think vue-tsc@3fb59af is a viable option...

**Comment by johnsoncodehk** [comment]
Sorry for the delay, I am currently no longer able to maintain this project full time. Since the next version depends on some Volar.js updates, I'll be working on the backlog here once the next Volar.js version is completed and released.

This project currently relies heavily on the developers I'm sponsoring to work on in their spare time. If you would like to help keep this project sustainable, please consider joining the [insiders program](https://github.com/vuejs/language-tools/wiki/Get-Insiders-Edition), where we aim to support at least one part-time developer.

**Comment by amir20** [comment]
Can we reopen this issue until the patch has been released?

**Comment by thirdeyeclub** [comment]
I second @amir20  that we reopen this issue.

I experinced this issue with nuxt and was able to get around it by disabling the typescript.typecheck in the nuxt config.

**Comment by basil** [comment]
Fixed in https://github.com/vuejs/language-tools/pull/5020. Released in [2.2.0](https://github.com/vuejs/language-tools/releases/tag/v2.2.0).

**Comment by aryankarim** [comment]
```json
"typescript": "^5.3.2",
"vue-tsc": "^2.0.29"
``` 
works fine. 

Also, if your `vue - official` extension does not recognize types properly you can downgrade to `2.1.10`

**Comment by Brain1024** [comment]
"vue-tsc": "1.8.27",

and

 "typescript": "5.3.3",

can resolve this problem.
