### ISSUE TITLE
`defineEmits<{()}>()` causes the vue server to crash

### ISSUE THREAD

**Issue by wrong-g** [vuejs/language-tools#5027]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.95.3

### Vue version

3.5.13

### TypeScript version

5.8.0-dev*

### Steps to reproduce

vue server崩溃后,选中高亮正常了,ts提示工作正常,但是模板提示(html标签,vue指令),折叠代码失效了,

![QQ20241205-155530](https://github.com/user-attachments/assets/dada1d2e-bc50-43e6-ba64-d5a6a5c2a2a5)
![QQ20241205-155642](https://github.com/user-attachments/assets/7f98abce-7f1a-42e7-9fc3-ae9c00a72b22)

### What is expected?

❤

### What is actually happening?

❤

### Any additional comments?

❤

**Comment by KazariEX** [comment]
因为这个高亮失效是混合模式导致的。

**Comment by KazariEX** [comment]
是什么导致了 vue server 崩溃？

**Comment by wrong-g** [comment]
> 是什么导致了 vue server 崩溃？

输入括号就崩溃了
![QQ20241205-171927](https://github.com/user-attachments/assets/3badbcfe-15c0-49f3-9c69-2dedc5446187)

[1-Vue Language Server.log](https://github.com/user-attachments/files/18020618/1-Vue.Language.Server.log)
