### ISSUE TITLE
最新版本插件仍然卡的不行，真的到了没办法开发的地步

### ISSUE THREAD

**Issue by ashuicoder** [vuejs/language-tools#5035]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.95.3

### Vue version

3.5.12

### TypeScript version

5.6.3

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13490F
    Memory: 18.90 GB / 31.84 GB
  Binaries:
    Node: 18.20.4 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.10.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.3527
```

### package.json dependencies

```json
{
  "dependencies": {
    "@imengyu/vue3-context-menu": "^1.4.3",
    "@vueuse/core": "^11.3.0",
    "await-to-js": "^3.0.0",
    "codemirror": "^5",
    "codemirror-editor-vue3": "^2.8.0",
    "csstype": "^3.1.3",
    "es-toolkit": "^1.27.0",
    "naive-ui-form": "^3.1.0",
    "pinia": "^2.2.6",
    "react-dnd-html5-backend": "^16.0.1",
    "vue": "^3.5.12",
    "vue-router": "^4.4.5",
    "vue3-dnd": "^2.1.0"
  },
  "devDependencies": {
    "@tsconfig/node22": "^22.0.0",
    "@types/codemirror": "^5.60.15",
    "@types/jsdom": "^21.1.7",
    "@types/node": "^22.9.0",
    "@vicons/fluent": "^0.12.0",
    "@vicons/ionicons5": "^0.12.0",
    "@vicons/material": "^0.12.0",
    "@vicons/tabler": "^0.12.0",
    "@vitejs/plugin-vue": "^5.1.4",
    "@vitejs/plugin-vue-jsx": "^4.0.1",
    "@vitest/eslint-plugin": "1.1.7",
    "@vue/eslint-config-prettier": "^10.1.0",
    "@vue/eslint-config-typescript": "^14.1.3",
    "@vue/test-utils": "^2.4.6",
    "@vue/tsconfig": "^0.5.1",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.14.0",
    "eslint-plugin-vue": "^9.30.0",
    "jsdom": "^25.0.1",
    "naive-ui": "^2.40.2",
    "npm-run-all2": "^7.0.1",
    "postcss": "^8.4.49",
    "prettier": "^3.3.3",
    "sass": "^1.81.0",
    "tailwindcss": "^3.4.15",
    "typescript": "~5.6.3",
    "vite": "^5.4.10",
    "vite-plugin-vue-devtools": "^7.5.4",
    "vitest": "^2.1.4",
    "vue-tsc": "^2.1.10"
  }

}
```

### Steps to reproduce

只要是.vue文件，typescript代码提示真的是异常缓慢，有的时候直接就卡死了直接不提示，错位类型也没有，有的时候代码提示要等个十几秒甚至更久。有的时候更恐怖的是ctrl+s保存代码的时候都能卡死了，要卡三四秒才能保存。我严重怀疑是此工具存在重大的性能bug，希望官方好好排查一下或者给出排查问题的解决方案。我32G的内存还卡成这样？翻半天issure总是看到一个有用的东西可以临时补救一下了
```json
{
   "vue.server.maxOldSpaceSize": 6144,
  "vue.server.hybridMode": true,
  "typescript.tsserver.maxTsServerMemory": 6144
}
```

官方能不能出一个诊断的工具，看一看到底是什么问题导致这么卡，完全没办法写ts的代码了，

### What is expected?

修复卡顿

### What is actually happening?

刚用vscode打开项目还勉强能提示，后面就是越来越卡

**Comment by KazariEX** [comment]
如果可以的话贴一下你的项目地址，我在本地测试看看。

**Comment by KazariEX** [comment]
性能问题肯定是有的，但没有人协助我们的话修复也就无从谈起。

**Comment by ashuicoder** [comment]
> 如果可以的话贴一下你的项目地址，我在本地测试看看。

地址： https://github.com/ashuicoder/lowcode-engine，请拉取代码后回复一下我，我会删除该仓库代码，内部项目

**Comment by KazariEX** [comment]
> > 如果可以的话贴一下你的项目地址，我在本地测试看看。
> 
> 地址： [项目地址](https://github.com/ashuicoder/lowcode-engine)，请拉取代码后回复一下我，我会删除该仓库代码

好了。

**Comment by KazariEX** [comment]
可以复现，我会继续检查。

**Comment by KazariEX** [comment]
不出意外问题应该出自 vicons 和 naive-ui，前者包含上万个 .d.ts 文件，如果在 .ts 文件中导入同样很卡；后者本身也有 TS 上的性能问题。

![image](https://github.com/user-attachments/assets/3fe92299-0509-438c-8621-ba98cd49fe12)

![image](https://github.com/user-attachments/assets/9a15cb69-9ed6-4ae2-98ca-aa2cb56d9644)

**Comment by CauseMyLove** [comment]
这是什么分析工具呀 @KazariEX

**Comment by ashuicoder** [comment]
> 不出意外问题应该出自 vicons 和 naive-ui，前者包含上万个 .d.ts 文件，如果在 .ts 文件中导入同样很卡；后者本身也有 TS 上的性能问题。
> 
> ![image](https://private-user-images.githubusercontent.com/85992002/393777914-3fe92299-0509-438c-8621-ba98cd49fe12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODU2MDYsIm5iZiI6MTczMzk4NTMwNiwicGF0aCI6Ii84NTk5MjAwMi8zOTM3Nzc5MTQtM2ZlOTIyOTktMDUwOS00MzhjLTg2MjEtYmE5OGNkNDlmZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA2MzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NDQxMDI2YjJhYmQ1ZTlkYmQ4OGVmMzUzZGViYzRjZjc0NjFmNTJjN2MyMzQ4NTU1NTM2YmFlNDljOWFiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6qYJXTGr_YhjrOghVshAmCwAjCGj7JPizxLmz9GAyUM)
> 
> ![image](https://private-user-images.githubusercontent.com/85992002/393778704-9a15cb69-9ed6-4ae2-98ca-aa2cb56d9644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODU2MDYsIm5iZiI6MTczMzk4NTMwNiwicGF0aCI6Ii84NTk5MjAwMi8zOTM3Nzg3MDQtOWExNWNiNjktOWVkNi00YWUyLTk4Y2EtYWEyY2I1NmQ5NjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA2MzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMWQzN2M5NmFkNTc3MDMzMWJkNDExNGJjYmM2Y2IwNDJkNWZmOWExMzNlMzRkZWU3ZDc4Njg2ZWFkNDMxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YR4hF13W4q73s-_9icdXkUvwiaYtTUXlSLbm7RxSj14)

非常感谢，我已经卸载了多余的图标库，速度就很快了

**Comment by 642661520** [comment]
@KazariEX 我项目中也在使用naive-ui，有没有什么好的解决办法？

**Comment by xiaojia21190** [comment]
依然存在
