### ISSUE TITLE
Hybrid Mode is disabled automatically because there is a potentially incompatible GitHub.copilot-chat TypeScript plugin installed.

### ISSUE THREAD

**Issue by lvzhenbo** [vuejs/language-tools#5044]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.96.0

### Vue version

3.5.13

### TypeScript version

pj:5.6.3 vsc:5.7.2

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500
    Memory: 5.41 GB / 15.62 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.79)
    Internet Explorer: 11.0.26100.1882
```

### package.json dependencies

```json
Not related
```

### Steps to reproduce

![image](https://github.com/user-attachments/assets/daa97254-4f79-4b59-9da9-ccb766d40131)

![image](https://github.com/user-attachments/assets/053ae91b-599f-47f7-8179-1495161fc019)
![image](https://github.com/user-attachments/assets/437e39aa-4b5a-414f-b270-861da8f80470)

### What is expected?

Will not receive any warning

### What is actually happening?

![image](https://github.com/user-attachments/assets/40c73a59-c177-4a47-9802-877bb1972efa)

### Any additional comments?

![image](https://github.com/user-attachments/assets/1ed1043e-3d29-4501-9f10-1cf568fc5e2e) Force this setting to true to be effective

**Comment by KazariEX** [comment]
The original intention of this warning is to inform users that an extension with the ts plugin may be incompatible with this extension, and auto mode exists for this purpose.

**Comment by lvzhenbo** [comment]
The most recent new feature is Copilot Edits, does that have anything to do with it?

**Comment by KazariEX** [comment]
idk, you can check it yourself.

![image](https://github.com/user-attachments/assets/4fa0d5ad-a01a-44f3-99ad-20f2a841c817)

**Comment by ferothefox** [comment]
This is also causing my typescript server to be duplicated and VSCode cannot determine what my workspace typescript version is.

**Comment by DonRedwoood** [comment]
I just started having this message popup after the latest VSCode update (v1.96.0).

**Comment by Steve-Mcl** [comment]
also seeing this

VSCode 1.96.0

**Comment by alebar42** [comment]
I has to force it to `enabled` using `true` as `false` (disabled) was causing typescript errors in my project. Why is it incompatible?

**Comment by christiandesantis** [comment]
I'm having the same issue. Could forcing enable to true cause issues with copilot when using it in other projects that don't use Vue? Has someone found the right fix for this yet?

**Comment by abarke** [comment]
> I'm having the same issue. Could forcing enable to true cause issues with copilot when using it in other projects that don't use Vue? Has someone found the right fix for this yet?

I haven't run into any issues so far, anyone else?

**Comment by KazariEX** [comment]
The fix will be released at next version, please set it to true temporarily.

**Comment by qiaozhididi** [comment]
I'm encountering this issue too. When will the updated and fixed version be released?

**Comment by owennewo** [comment]
Thanks v2.2 seems to have fixed it!

**Comment by Kasopej** [comment]
still happens on v2.2.8
had to set hybrid mode to true
