### ISSUE TITLE
Component events auto-completion doesn't work

### ISSUE THREAD

**Issue by makedopamine** [vuejs/language-tools#5072]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.93.1

### Vue version

3.5.13

### TypeScript version

5.6.4

### package.json dependencies

```json
{
  "devDependencies": {
    "typescript": "5.6.3",
    "vue": "^3.5.13",
    "vue-tsc": "^2.1.10"
  }
}
```

### Steps to reproduce

Foo.vue
```
<script lang="ts" setup>
defineEmits<{
  (e: 'change', id: number): void
}>()
</script>
```
Bar.vue
```
<template>
    <Foo @></Foo>
         ^ Type @ here
</template>
<script setup lang="ts">
import Foo from './Foo.vue'
</script>
```

### What is expected?

When I type @ it should give me intellisense of all valid events.

### What is actually happening?

When I type @, 'change' is not on the intellisense menu.

### Any additional comments?

Version 2.1.6 works fine

**Comment by KazariEX** [comment]
Hmm it works on my end. Could you please provide a minimal reproduction?

![image](https://github.com/user-attachments/assets/b559da63-8f37-4402-8f8e-137a2bc2a9a4)

**Comment by makedopamine** [comment]
It might be that I just did something wrong on my end, closing this ticket.
