### ISSUE TITLE
JSDoc提示出现重复(Prompt for duplicate occurrence)

### ISSUE THREAD

**Issue by Lazygui** [vuejs/language-tools#5074]
### Vue - Official extension or vue-tsc version

v2.1.10

### VSCode version

1.96.2(system setup)

### Vue version

^3.4.37

### TypeScript version

^5.5.3

### package.json dependencies

```json
{
  "name": "adminui",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc -b && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "dayjs": "^1.11.13",
    "element-plus": "^2.8.4",
    "file-saver": "^2.0.5",
    "pinia": "^2.3.0",
    "vite-plugin-commonjs": "^0.10.3",
    "vue": "^3.4.37",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@originjs/vite-plugin-commonjs": "^1.0.3",
    "@types/file-saver": "^2.0.7",
    "@types/node": "^22.7.4",
    "@types/postcss-pxtorem": "^6.0.3",
    "@vitejs/plugin-vue": "^5.1.2",
    "autoprefixer": "^10.4.20",
    "postcss-pxtorem": "^6.1.0",
    "sass": "^1.80.6",
    "sass-loader": "^16.0.3",
    "typescript": "^5.5.3",
    "unplugin-auto-import": "^0.18.3",
    "unplugin-vue-components": "^0.28.0",
    "vite": "^5.4.1",
    "vite-svg-loader": "^5.1.0",
    "vue-router": "^4.4.5",
    "vue-tsc": "^2.0.29"
  }
}
```

### Steps to reproduce

vscode安装这个版本的插件随便一个vue文件鼠标移动到任意一个可用的变量或函数上就会出现重复提示
（VScode installation of this version of the plugin will result in duplicate prompts when moving the mouse over any available variable or function in any Vue file）
![image](https://github.com/user-attachments/assets/5aa249f5-f9de-4502-9c4e-f1811a0906d5)

### What is expected?

vscode安装这个版本的插件随便一个vue文件鼠标移动到任意一个可用的变量或函数上就会出现重复提示
（VScode installation of this version of the plugin will result in duplicate prompts when moving the mouse over any available variable or function in any Vue file）
![image](https://github.com/user-attachments/assets/fba42ea4-f996-431b-864f-7c4724a33b87)

### What is actually happening?

vscode安装这个版本的插件随便一个vue文件鼠标移动到任意一个可用的变量或函数上就会出现重复提示
（VScode installation of this version of the plugin will result in duplicate prompts when moving the mouse over any available variable or function in any Vue file）
![image](https://github.com/user-attachments/assets/1d08232c-afa3-444b-a27e-a3543a1b44bf)

**Comment by zcf0508** [comment]
You can set `HybridMode` to `true`.

![image](https://github.com/user-attachments/assets/157a2549-d48f-459d-9be7-c89974c45d51)
