### ISSUE TITLE
vue内点击变量不会自动高亮代码？降级到1.8版本就可以

### ISSUE THREAD

**Issue by panpanplan** [vuejs/language-tools#5093]
### Vue - Official extension or vue-tsc version

V2.2.0

### VSCode version

1.96.2

### Vue version

20

### TypeScript version

母鸡

### Steps to reproduce

vue内点击变量不会自动高亮代码？降级到1.8版本就可以

### What is expected?

vue内点击变量不会自动高亮代码？降级到1.8版本就可以

### What is actually happening?

vue内点击变量不会自动高亮代码？降级到1.8版本就可以

### Link to minimal reproduction

vue内点击变量不会自动高亮代码？降级到1.8版本就可以

### Any additional comments?

vue内点击变量不会自动高亮代码？降级到1.8版本就可以

**Comment by KazariEX** [comment]
Duplicate of #4850
