### ISSUE TITLE
Priority of imported component and self-reference on v2.2.0

### ISSUE THREAD

**Issue by sxzz** [vuejs/language-tools#5097]
### Vue - Official extension or vue-tsc version

2.2.0

### VSCode version

N/A

### Vue version

3.5.13

### TypeScript version

5.7.2

### Steps to reproduce

```vue
// Foo.vue
<script setup lang="ts">
import Foo from './Other.vue'
</script>

<template>
  <Foo /> <!-- should not be self-referencing -->
</template>
```

### What is expected?

Referencing to imported component

<img width="429" alt="image" src="https://github.com/user-attachments/assets/f30640a3-d2f8-4ce2-b4f0-124f45f8ab77" />

### What is actually happening?

Self-referencing

### Link to minimal reproduction

https://github.com/oxc-project/playground and upgrade vue-tsc to v2.2.0

### Any additional comments?

Works well in v2.1.x, but failed on v2.2.0

**Comment by KazariEX** [comment]
It seems that it was just missing a required prop `title`?

**Comment by sxzz** [comment]
I prepared a minimal reproduction https://github.com/sxzz/vue-tsc-5097-issue. It'll be more clear
