### ISSUE TITLE
Add a manual for volar extension like rust-analyzer

### ISSUE THREAD

**Issue by IWANABETHATGUY** [vuejs/language-tools#758]
Maybe we should write a manual  like https://rust-analyzer.github.io/manual.html, additionally wo can centralize some common issue like https://github.com/johnsoncodehk/volar/issues/682, it maybe reduce some duplicate issue.

**Comment by johnsoncodehk** [comment]
Sorry for the false hope, I don't think we'll have it in the end.

- Maintaining a complete manual is way beyond what we can afford, and our project architecture is constantly changing.
- I don't think it helps much to avoid duplicate issues, we actually don't get many duplicate issues with a large time span, and I think very few people read it before opening an issue.

As an alternative, I will continue to improve the readme for each package. Thank you for your suggestion.
