### ISSUE TITLE
Yarn 3 incompatibility

### ISSUE THREAD

**Issue by orimay** [vuejs/language-tools#918]
Thank you for the awesome extension! I loved using it with takeover mode, but it seems completely broken as of moving off to Yarn 3 without the node_modules folder.

First of all, it doesn't seem to work with Yarn 3 relative path workspaces. If I have my dependency like
```
"gun": "workspace:packages/gun",
```
I can't refer to it like 
```ts
import Gun from 'gun';
```
And get to refer to it like
```ts
import Gun from '@/../../gun';
```
instead.

Even though without Volar, Yarn 3 workspaces are perfectly handled.

If I disable Take Over Mode, Vue TS checks fail completely:
![image](https://user-images.githubusercontent.com/4993319/151738995-9920f871-3b16-4dfa-bec3-06048800bb2b.png)

Then, VSCode shows two tooltips rather than one:
![image](https://user-images.githubusercontent.com/4993319/151738417-850d393e-323b-4689-b8ba-80c0b75551c8.png)

If Volar has any issues that VSCode has not, these messages differ:
![image](https://user-images.githubusercontent.com/4993319/151738520-fa563a40-88aa-4abc-84b5-b3095e84eb14.png)

The upper one finds the module, the lower one (Volar) does not.

Last, but not least -- Volar doesn't import packages from .yarn:
![image](https://user-images.githubusercontent.com/4993319/151738595-048d01d0-1d70-43b7-8210-3e84c0458e2a.png)

Is Yarn 3 support not intended? I really wish it was working. Hope it's not much of a headache to fix this. Thank you in advance!

**Comment by johnsoncodehk** [comment]
Hi @Orimay, first thanks for the report!

I'm not familiar with yarn3, do I just need to switch to yarn v3 and can this problem reproduce in https://github.com/johnsoncodehk/volar-starter too? I will check it later.

**Comment by merceyz** [comment]
Could you provide a reproduction? I have Volar working with PnP in my projects.

**Comment by ferm10n** [comment]
@merceyz here's a repro, without the use of workspaces or anything fancy really. I'd actually be interested in taking a look at one of your projects that has volar working with pnp.

@johnsoncodehk to switch to yarn3 and pnp, you should only need to do:
- `yarn set version berry`
- `yarn config set nodeLinker pnp` (this is default on new projects, but if you're in a project previously managed by npm this is needed)
- `yarn install`

**Comment by ferm10n** [comment]
@Orimay I was able to create a simple project that uses yarn pnp and workspaces. Made a couple of dumb mistakes along the way, but ended up with a sanity verifying checklist which might be helpful:
- are you able to import a workspace package from a .ts file?
- is vscode using the workspace version of typescript?
- does importing your package if you use the `"gun": "workspace:*"` notation instead of the experimental relative path one (`"gun": "workspace:packages/gun"`)?
- is the latest version of vue-tsc installed?
- any weird output from "Volar - API" ?

**Comment by adalinesimonian** [comment]
here's a reproduction repository: https://github.com/adalinesimonian/volar-pnp-test

i've tested this in a workspace and without and it happens either which way.

![Screenshot of module resolution errors in VS Code](https://user-images.githubusercontent.com/9868643/192816564-8e586063-0f8f-42ca-908f-aee68f5e16e4.png)

**Comment by adalinesimonian** [comment]
i added some logs into volar's `reloadServers` to see if the tsdk path was resolved correctly, and the path is correct:

```
/.../volar-pnp-test/.yarn/sdks/typescript/lib/tsserverlibrary.js
```

continuing to dig further

**Comment by merceyz** [comment]
> here's a reproduction repository: https://github.com/adalinesimonian/volar-pnp-test

See https://github.com/yarnpkg/berry/issues/4915

**Comment by adalinesimonian** [comment]
downgraded to 4.8.3. now, in a single repo, it works as expected. however, in a monorepo, the same resolution errors occur.

here's a reproduction monorepo: https://github.com/adalinesimonian/volar-workspaces-pnp-test

**Comment by johnsoncodehk** [comment]
Sorry i'm not familiar with this part, I assume that we just need setting the yarn 3 version tsdk to `typescript.tsdk`?

I will add documentation for it. (If I'm right)

**Comment by Lexpeartha** [comment]
> Sorry i'm not familiar with this part, I assume that we just need setting the yarn 3 version tsdk to `typescript.tsdk`?

In Volar "Take-over" mode TS/JS language server gets completelly replaced by Vue + TS server, which presumably doesn't recognise ts sdk provided by yarn

**Comment by merceyz** [comment]
> however, in a monorepo, the same resolution errors occur.
here's a reproduction monorepo: https://github.com/adalinesimonian/volar-workspaces-pnp-test

@adalinesimonian The error I get in that repo is
```
Cannot find module 'vue'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?ts(2792)
```
If I then set the `moduleResolution` to `node` it works.

---

> Sorry i'm not familiar with this part, I assume that we just need setting the yarn 3 version tsdk to typescript.tsdk?
I will add documentation for it. (If I'm right)

@johnsoncodehk `typescript.tsdk` is set by Yarn so Volar needs to be told to use the workspace version. https://yarnpkg.com/getting-started/editor-sdks/#vscode
If the workspace is trusted and `typescript.tsdk` is set Volar could probably pick the workspace version automatically.

--- 

> which presumably doesn't recognise ts sdk provided by yarn

@Lexpeartha it recognizes it.

**Comment by XiangShuUncle** [comment]
@johnsoncodehk  Is there a solution to this problem?

**Comment by GuilhermeAB** [comment]
This works for me:
![image](https://user-images.githubusercontent.com/27172892/209559308-641e61ab-26e3-4964-bdec-58a57b3541b1.png)

![image](https://user-images.githubusercontent.com/27172892/209559334-e2d65976-1143-48fc-b9c1-207135281cfe.png)

**Comment by gavin-lb** [comment]
I am still unable to get the "Go To Definition" feature of VS Code to work when using Yarn PnP and Volar. 

There has been [an issue open with Yarn](https://github.com/yarnpkg/berry/issues/3123) for several years without fix. Is this something that could be fixed from Volar side instead?
