### ISSUE TITLE
Incorrect reference count for default slot

### ISSUE THREAD

**Issue by iliubinskii** [vuejs/language-tools#932]
Volar shows "1 reference" (correct) in this scenario:
```vue
Child.vue:
<template>
  <div>
    <slot></slot>
  </div>
<template>

Parent.vue:
<Child>
  <template #default>
    Some code
  </template>
</Child>
```

But it shows "0 references" (incorrect) in this scenario:
```vue
Child.vue:
<template>
  <div>
    <slot></slot>
  </div>
<template>

Parent.vue:
<Child>
  Some code
</Child>
```
![image](https://user-images.githubusercontent.com/70687432/152396803-f365fc43-d98b-4b5f-9315-55f94dff7c1b.png)

This is not right.
Default slot is used once in both of the above scenarios.

Here is the only scenario when default slot is not used:
```vue
Child.vue:
<template>
  <div>
    <slot></slot>
  </div>
<template>

Parent.vue:
<Child />
```

**Comment by sethidden** [comment]
Related https://github.com/johnsoncodehk/volar/issues/934

**Comment by peteringram0** [comment]
@johnsoncodehk v0.32.1 doesn't seem to fix this issue. Can this be re-opened?

**Comment by johnsoncodehk** [comment]
@peteringram0 it's fixed for me, could you provide repro case?

**Comment by markbrockhoff** [comment]
Hi @johnsoncodehk I'm facing the same issue using Volar v0.33.2. For reproduction I used the same example @ilyub posted initially:

![image](https://user-images.githubusercontent.com/95471369/158786025-b4508ab5-1f39-43cc-a432-89d35686be7a.png)

![image](https://user-images.githubusercontent.com/95471369/158786089-2e4f1b09-ec12-4b95-b2bf-31a8fac5071b.png)

When replacing the divs inside the parent with template tags with v-slot attribute "default" the count changes to 1 like it should.
I agree with @peteringram0 that this issue doesn't seem to be fixed and should probably be re-opened.

**Comment by ElToroDM** [comment]
Hi, same here. Still the same bug, could anyone else confirm it?

**Comment by moracabanas** [comment]
Still an issue please reopen

![image](https://github.com/vuejs/language-tools/assets/4382333/f819b385-1450-464e-aafa-e7640326d121)

**Comment by regurgitate** [comment]
I can confirm that bug is still present.
![image](https://github.com/vuejs/language-tools/assets/121431545/ebcf45bf-85d6-473d-85d5-ad531fa742b1)

**Comment by so1ve** [comment]
@regurgitate Which version are you using?

**Comment by regurgitate** [comment]
@so1ve 
> @regurgitate Which version are you using?

v1.8.4
