### ISSUE TITLE
vscode dont see vue-router auto import or vue3

### ISSUE THREAD

**Issue by productdevbook** [vuejs/language-tools#963]
It doesn't detect any import library on the vue side.

![image](https://user-images.githubusercontent.com/38668796/153842612-92cf9b38-cedf-487c-a8cf-439d0d4655c8.png)

**Comment by johnsoncodehk** [comment]
Seems must to implement extra logic for this.
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#smarter-auto-imports
- https://github.com/microsoft/TypeScript/blob/e4fe50cca477a3e46f9b629a6c5be0b0ed8b010f/src/server/project.ts#L1725-L1753
- https://github.com/microsoft/TypeScript/blob/e4fe50cca477a3e46f9b629a6c5be0b0ed8b010f/src/server/project.ts#L1907-L2162
